### ISSUE TITLE
IDE2-2018-07-10 (Sprint: 151)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#10059]
### Sprint Goals:
1. Plugin model implementation
2. Factories support in Theia IDE
3. Sample plugins in Theia IDE

## 1. Extensibility model implementation
- [x] Implement showInputBox method for Theia plugin system https://github.com/eclipse/che/issues/9980 20sp
- [ ] Implement 'showOpenDialog' method of plugin API  https://github.com/theia-ide/theia/issues/2153 25sp
- [ ] Implement 'showSaveDialog' method of plugin API https://github.com/theia-ide/theia/issues/2173
- [x] New plugin model doesn't work in electron version of Theia https://github.com/eclipse/che/issues/9767 10sp
- [ ] [WIPTheia] Add support for preferences schema from contribution point of a manifest file https://github.com/eclipse/che/issues/9990 [TODO re-estimate with more details]

## 2. Factories support in Theia IDE
- [x] List the actions and IDE events, that are already defined for GWT IDE https://github.com/eclipse/che/issues/10160 10sp
- [ ] Implement the factory events handing in Theia https://github.com/eclipse/che/issues/10162 25sp
- [ ] Handle the OpenFile factory's action in Theia https://github.com/eclipse/che/issues/10163
- [ ] Handle the runCommand factory's action in Theia https://github.com/eclipse/che/issues/10167

## 3. Sample plugins in Theia IDE
- [ ] Add options to generate different plugin samples in Theia plugin generator https://github.com/eclipse/che/issues/9956 25sp

## Other  issues: 
- [x] Investigation: Generic authentication/authorization components https://github.com/theia-ide/theia/issues/2126 40sp
- [x] Merge wiptheia dockerfile with Che Theia IDE dockerfile https://github.com/eclipse/che/issues/10124 
- [x] User Dashboard installers: page scrolls down when enabling/disabling workspace api installer https://github.com/eclipse/che/issues/10097 15sp
- [x] Multiple installers in UD https://github.com/eclipse/che/issues/10098 10sp

### **Unplanned:**
- [x] [plug-in] we don't receive EditorChange event for editors loaded before plug-in startup https://github.com/theia-ide/theia/issues/2190
- [x] Save/Cancel buttons on stack details page is missed if reject changes in Agents list https://github.com/eclipse/che/issues/10256

**Total planned = [todo]sp**

### Pending PRs
- [x] https://github.com/eclipse/che-theia-terminal-plugin/pull/1 - X [Moby CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187tps://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187)
- [x] https://github.com/theia-ide/theia/pull/2141

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova | 5 |
| Mykola Morhun | 5 |
| Oleksandr Andriienko | 12 | 
| Oleksii Kurynniy | 6 |
| Oleksii Orel | 8 |
| Sun Tan | 13 |
| Vitaliy Guliy | 12 |
| Yevhen Vydolob | 11  |
| **Total Budget** | **72** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1C1hMsWOPptV0hgQVf85KCI2AOoUr_pkm8e72pbS9CT0/edit)

**Comment by skabashnyuk** [comment]
@ashumilova  can you start investing some time in https://github.com/theia-ide/theia/issues/2126?
