### ISSUE TITLE
Create E2E selenium tests to cover stacks in Che Dashboard

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#10050]
### Description
Eclipse Che Dashboard provides ability to create workspace from predefined or self-created stacks 
https://www.eclipse.org/che/docs/stacks.html :
![screenshot from 2018-06-14 15-09-50](https://user-images.githubusercontent.com/1197777/41411439-8da65df2-6fe5-11e8-9db8-25f11d952aa7.png)

We need to cover this functionality by E2E selenium tests for next stacks:

- [x]  .NET https://github.com/eclipse/che/issues/10270
- [x]  Android https://github.com/eclipse/che/pull/10255
- [x]  Blank https://github.com/eclipse/che/issues/10144
- [x]  C++ https://github.com/eclipse/che/issues/10270
- [x]  CentOS blank https://github.com/eclipse/che/pull/10255
- [x]  CentOS Go https://github.com/eclipse/che/pull/10255
- [x]  CentOS nodejs https://github.com/eclipse/che/pull/10255
- [x]  CentOS WildFly Swarm https://github.com/eclipse/che/pull/10255
- [x]  Ceylon with Java JavaScript Dart on CentOS https://github.com/eclipse/che/pull/10255
- [x]  Eclipse Che - https://github.com/eclipse/che/issues/10107
- [x]  Eclipse Vert.x https://github.com/eclipse/che/pull/10255
- [x]  Go https://github.com/eclipse/che/issues/10270
- [x]  Java https://github.com/eclipse/che/pull/10214
- [x]  Java CentOS https://github.com/eclipse/che/pull/10255
- [x]  Java Theia (docker) #10280 https://github.com/eclipse/che/issues/10270
- [x]  Java Theia (openshift) #10280 https://github.com/eclipse/che/issues/10270
- [x]  Java-MySQL https://github.com/eclipse/che/pull/10147
- [x]  Java-MySQL CentOS https://github.com/eclipse/che/pull/10255
- [x]  Kotlin https://github.com/eclipse/che/issues/10270
- [x]  Node https://github.com/eclipse/che/pull/10147
- [x]  PHP https://github.com/eclipse/che/issues/10270
- [x]  Python - https://github.com/eclipse/che/issues/10056
- [x]  Rails https://github.com/eclipse/che/issues/10270
- [x]  Spring Boot https://github.com/eclipse/che/pull/10255

### Subtask
- [x]  Check the working of all workspaces with samples according to optimize the list of stacks (#10027)

### Related issues
- Remove unused stacks and add docs instructions on how to create workspaces from docs not in the default list (#9899)
