### ISSUE TITLE
Languages Sprint 151

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10075]
# Availability
@tsmaeder: 7d
@tolusha 14d
@svor 13d
@vrubezhny 14d 
@JPinkney 14d
@fbricon 8d
@snjeza 14d

84 * 0.6= 50 d
(24d)

- [ ] #8666 Cleanup unused Java support Part 2 1d (@JPinkney )
- [x] #8940 (Theia) Create Che Java Contribution 1d @tsmaeder
- [ ] #8965 Theia: Implement Java "libraries" feature (4d) (@JPinkney)
- [ ] #9591 Address Selenium Test Merge Blockers (timeboxed: 15d)
  - [x] #10034 Fix Rename Selenium Failures 1d (@svor)
  - [x] #10052 Selenium: Source Folder Paths have wrong base (@tsmaeder) (2d)
  - [ ]  #10115 New folders do not register in the jdt.ls workspace (@vrubezhny )
  - [x] #10112 Different Quickfix Behaviour Java vs. LSP (@vrubezhny)
  - [x] #10095 Fix selenium tests from org.eclipse.che.selenium.refactor.preview (@svor)
  - [x] #10094 Fix selenium tests from org.eclipse.che.selenium.refactor.fields (@svor)
- [x] #9972 Open Editor on Library Class Files in Theia (@svor) 5d
- [x] #10049 Javadoc is duplicated 2d (@vrubezhny)
- [x] #10077 DAP Create Line Breakpoint 13d (@tolusha 
- [ ] #9971 Show Progress Reports from jdt.ls (@JPinkney)
- [x] #10079 Investigate Java Debug Adapter  (5d timebox)
- [x] [#688](https://github.com/eclipse/eclipse.jdt.ls/issues/688) Insert best guessed parameters (@snjeza 4d))
- [ ] [#696](https://github.com/eclipse/eclipse.jdt.ls/issues/696) Convert from  `var` to type code action (@snjeza 3d)
- [ ] [#697](https://github.com/eclipse/eclipse.jdt.ls/issues/697) Convert from type to `var` code action (@snjeza 3d)

Open PR's (5.5d)
- [x] https://github.com/eclipse/che/pull/10028 Simple Java project is not recognized 1d (@vrubezhny)
- [x] https://github.com/eclipse/che/pull/9616 Custom socket provider and java language server in sidecar
- [x] https://github.com/eclipse/che/pull/9999 Added che-theia-java-extension to default theia plugins
- [x] https://github.com/theia-ide/theia/pull/2069 Consume che-ls-jdt (1d)
- [x] https://github.com/theia-ide/theia/pull/2092 Support jdt.ls Status Reports 0.5d
- [x] https://github.com/che/che-ls-jdt/pull/52 ,  #9983 Fix job watching in "reimport projects 2d
- [x] [#690](https://github.com/eclipse/eclipse.jdt.ls/pull/690) Use SurroundWithAnalyzer from o.e.jdt.core.manipulation 0.5d
- [ ] [#684](https://github.com/eclipse/eclipse.jdt.ls/pull/684) convert anonymous class creation to lambda expression 0.5d

Previous sprint: https://github.com/eclipse/che/issues/9804

**Comment by fbricon** [comment]
jdt.ls

- [ ] [#688](https://github.com/eclipse/eclipse.jdt.ls/issues/688) Insert best guessed parameters
- [ ] [#696](https://github.com/eclipse/eclipse.jdt.ls/issues/696) Convert from  `var` to type code action
- [ ] [#697](https://github.com/eclipse/eclipse.jdt.ls/issues/697) Convert from type to `var` code action
