### ISSUE TITLE
Platform-2018-07-10 (Sprint: 151) 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10085]
### Features related to Authentication and security in Theia IDE 
 - [ ] Cover ws-agent/exec-agent/terminal with JWT proxy https://github.com/eclipse/che/issues/10081 13sp
- [x] Create CQ for jwtproxy https://github.com/eclipse/che/issues/10078  5sp
- [x] Make a unique nonce as optional check in jwtproxy https://github.com/eclipse/che/issues/10090 5sp
- [ ] Make public/private signing keys pair per-workspace and synch with workspace runtime (renew pair on each workspace restart) https://github.com/eclipse/che/issues/10074 13sp
- [x] Make it possible for Go agents to accept authentication tokens from header https://github.com/eclipse/che/issues/10101 8sp

### Features related to Workspace.Next Phase 1
 - Talks, discussions, prototypes.

### Technical debts and bugs
- [ ] http/https proxy ENV in helm chart https://github.com/eclipse/che/issues/9549 8sp
- [x] Consider using the final version of Keycloak image | https://github.com/eclipse/che/issues/10100 5sp

### Unplanned
- [x] Make sure eclipse/che-dev/pom.xml are not depend on eclipse/che-parent/pom.xml https://github.com/eclipse/che/issues/10170
- [x] API requests from ws-agent to ws-master have the same authorization header https://github.com/eclipse/che/issues/10243 
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 10d |
| Max Shaposhnik | 14d | 
| Michail Kuznyetsov | 14 d | 
| Sergii Leshchenko | 14 d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 57 | 23 |
