### ISSUE TITLE
IDE-2018-07-10 (Sprint: 151)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#10089]
#### Artem 
- [ ] Restore dependencies on creating a C# project #10047
- [x] Make a command's target optional for Che tasks #10135
- [ ] Che task in Theia may have the multiple targets defined #10136
- [x] Show info about the running Che task in Theia's terminal widget #10137

#### Dmytro 
- [x] Not possible to configure projects sources for LS launched on standalone machine #10032
- [ ] csharp language server init failed when open demo.csproj file #10055
- [x] Ws-agent prints errors when applying Go to definition (outside project) in a Go project #10035
- [x] Go language server doesn't format selected code fragment properly #10066
- [x] Formatting for python editor does not apply properly in a workspace with enabled python LS #9854 
- [x] Python language server doesn't format selected code fragment properly #10086
- [x] TypeScript language server doesn't format selected code fragment properly #10068
- [ ] Ability to handle the stacktrace (Java + JavaScript?) #9248 (analyzing depends on #9595 )

#### Roman 
- [ ] Theia Editor Key Bindings switching (Default, VI, Emacs) #9244 6d

#### Vitalii 
- [x] space character in path of REST call #10064
- [x] A web page is not redirected correctly, if after "http:" a link has only one slash #4992
- [ ] Unexpected exceptions in the dev-machine console after initialization LS for GO lang #9796 

#### Vlad
- [ ] There are two parent folders with a same name when import recursively maven project #10012
- [x] Wrong behavior the 'Save' button in the 'Preferences' #9959
- [x] Font of the workspace loader is very bad visible on the white theme. #9958
- [x] File icon moves to middle of file tab when you provide key input to code editor in Firefox #5763

#### Igor 
- [ ] _[Theia]_ Preferences UI for Theia IDE #9730 5d
- [x] Tag name does not display when perform git status #9418
- [x] Wrong committer when sharing a workspace in an org #9362
- [x] Confusing error messages on failed git push #9154
- [x] Copy and pasting a file onto itself will delete its contents #9052

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |  
| Dmytro  | 14 |   
| Roman  |8 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 71/65 |  |
| **Velocity** | |  |
