### ISSUE TITLE
[lsp][plug-in] Ease the integration of a new LSP into Eclipse Che with plug-ins

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#10206]
### Description
Eclipse Che is becoming more and more extensible and customizable.

Workspace.next engine is allowing to plug new `tool container` into the workspace
Theia and plug-in model is allowing an easy way to plug new IDE components as well. (instead of Theia extension)

Goal of this epic is to get advantages of these two when we talk about LSP implementations.

Plug-in's model API should provide LSP plug-ability for the client side. (like the textmate configuration, the lsp options, etc)
Definition of the container providing LSP server should be a workspace.next configuration.

All of this should be then packaged as a Che Plugin.

Tasks
- [ ] define LSP Theia plug-in API 
- [ ] check workspace.next configuration with a plugin
- [ ] documentation on writing Che plugin with ws.next part + theia plugin.
- [ ] video demo of this e2e flow.

**Comment by tsmaeder** [comment]
> define LSP/theia API (it could be che API if specific to Eclipse Che)
Please no! Let's keep make it so that we can take any lsp, package it in a container and then run it as a che plugin. Special Che API would sabotage that goal.

**Comment by benoitf** [comment]
@tsmaeder how do you will bring syntax highlight and other stuff ?
also "what kind of sabotage" are you seeing ?
AFAIK today there is IDE plugin for each language on Che.

**Comment by tsmaeder** [comment]
Maybe I don't get it: there is already api to contribute syntax highlighting in Theia. Why would we add something incompatible?

**Comment by benoitf** [comment]
@tsmaeder I don't know if you read too quickly but it would be *only* if there is something specific to che that we could require a Che API (like grabbing the url of a container, getting some container metadata, or anything else specific due to Che and Theia integration).

Also AFAIK for now syntax highlighting is through extension not plug-in model.

to sum-up, goal is more to provide Theia "plug-in" model  to LSPs.
