### ISSUE TITLE
Che’s Theia extension-ready package

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#10275]
### Description
On our road to introduce the new IDE, based on Eclipse Theia, we have been building a set of specific extensions for Che.

| Project        | Description  |
| ----------- |-----|
| [GitHub Plugin](https://github.com/eclipse/che-theia-github-plugin) | GitHub VCS support.  |
| [Java Plugin](https://github.com/eclipse/che-theia-java-plugin) | Java language support. |
| [SSH Plugin](https://github.com/eclipse/che-theia-ssh-plugin) | SSH public/private key pairs management. |
| [Terminal Plugin](https://github.com/eclipse/che-theia-terminal-plugin) | Terminal plugin. |
| [Machines Plugin](https://github.com/eclipse/che-theia-machines-plugin) | Workspace's containers controller plugin. |
| [Hosted plugin manager](https://github.com/eclipse/che-theia-hosted-plugin-manager-extension) | IDE hosting handler for url changing and port forwarding. |
| [Commands plugin](https://github.com/eclipse/che-theia-task-plugin) | Commands support of Che workspaces. |
| [Factories plugin](https://github.com/eclipse/che-theia-factory-extension) | Factories extension to support Che's factories in Eclipse Theia. |

We need to:
- create a Che's Theia package with all the existing plugins (or extensions) we have
- identify from the list, the specific tools for che which needs to adopt the plugin model and migrate those
- make that Che's Theia package available for anyone looking to the new IDE from Che.

### Sub-Tasks

- [x] **STEP 1**: Create a `che-theia` Docker image with all plugins packaged in it (frontend and backend in the same container)
  - [x] Create a Dockerfile (and eventual scripts/metadata)
  - [x] Setup a CI to push the image on DockerHub
  - [x] Create a new stack with a Dockerimage recipe that point to the Che image

- [ ] Make extensions and plugins properly work on k8s infrastructure (TODO add depency issues)

**Comment by AndrienkoAleksandr** [comment]
@slemeur I removed env-variables-plugin from the table this is deprecated stuff. For Theia extensions this functionality is available from theia-core, for plugins we have https://github.com/theia-ide/theia/blob/master/packages/plugin/src/theia.d.ts#L2405

**Comment by slemeur** [comment]
Thanks @AndrienkoAleksandr !

**Comment by l0rd** [comment]
@slemeur should this run on top of ws.next or on top of current workspace model?

**Comment by l0rd** [comment]
If this should run on top of ws.next the goal should be to publish in a Docker registry (docker hub):
- [ ] A Docker image of Theia with the mentioned plugins preloaded (the frontend side of the plugins)
- [ ] One Docker image for each Che plugin (the backend side of the plugin)

**Comment by benoitf** [comment]
I would say steps are
short term:
- che-theia image with all theia plugins packaged inside the image

mid term
- theia plugins are added through ws.next configuration (hot deploy) in the same theia container

long term:
- theia plugins instead of running in a forked instance of the theia container, could be launched in a separate container

**Comment by azatsarynnyy** [comment]
I've updated the link to the `che-theia-task-plugin` since it's merged from my own repo into the eclipse one.

**Comment by benoitf** [comment]
Now in latest Che-Theia image, all extensions that are working in openshift have been integrated.
It's quite easy to add new extensions
https://github.com/eclipse/che/blob/master/dockerfiles/theia/src/extensions.json

**Comment by slemeur** [comment]
Can we document that for Che contributors but also users? 

I'm thinking about the following use case for users:
- I want to provide a custom workspace with my own stack
- with that workspace, the IDE will be configured with a set a extensions that I'm defining
How can a user do that?

**Comment by ashumilova** [comment]
Removing the step 2 from description:
`- [ ] **STEP 2**: Extract the backend part of the plugins in a separate docker image and leverage ws.next (this step should be done after the ws.next skeleton is completed)`
