### ISSUE TITLE
IDE-2018-07-31 (Sprint: 152)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#10284]
#### Artem 
- [x] Restore dependencies on creating a C# project #10047
- [x] csharp language server init failed when open demo.csproj file #10055
- [ ] Theia Command Palette Improvement #8976 

#### Dmytro 
- [ ] Ability to handle the stacktrace (Java + JavaScript?) #9248 
- [ ] Clean up subscriptions for expired websocket sessions #6177 

#### Roman 
- [ ] Theia Editor Key Bindings switching (Default, VI, Emacs) #9244 6d
- [x] Opening an editor that does not correspond to an existing resource throws an exception #10222
- [ ] IDE does not re-initializes FileTypeRegistry on workspace restart #9467 3d
- [ ] Marked html/js tags are too hard to read #8867 
- [x] Do not track command editor changes on server side #8984

####  Vitalii
- [x] Open in Terminal feature #10356 2d
- [ ] Open on github feature #10359 3d
- [ ] Command removed after a freeze #10309 2d
- [ ] clangd completion is too slow #9786

#### Vlad
- [x] Websocket ID registered twice #10241 2d
- [ ] The Refactor -> Rename feature does not work properly for C# #10180 3d
- [x] Che doesn't notify a user when saving of files fails because of lack of space on disk #9769 4d
- [ ] Add an ability to re-run a task in Theia from a terminal widget #10381 2d
- [x] Add an ability to clear terminal's output in Theia #10380 2d
 
#### Igor 
- [ ] _[Theia]_ Preferences UI for Theia IDE #9730 3d
- [x] Fail of cloning a "Che" project to workspace which based on "Eclipse Che" stack #10286 3d
- [x] Consistent Lifecycle Events for Projects #9924 6d
- [ ] Zend stack: Errors when creating composer project type, command failures #9937 2d

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |  
| Dmytro  | 14 |   
| Roman  |8 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 71/65 |  |
| **Velocity** | |  |
