### ISSUE TITLE
Languages Sprint 152

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10299]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 2d  | 1.2d | 1
@tolusha | 10d | 6d | 7.5
@svor | 8 d | 4.8 | 5.5 | 
@vrubezhny | 9 d |  5.4 | 5
@JPinkney | 12d  | 7.2 | 9
@fbricon | 8d | 4.8 | 4.5
@snjeza 14d | 8.5 |

x * 0.6= y d

- [x] #9591 Address Selenium Test Merge Blockers (timeboxed: 20d) (@svor @tsmaeder @vrubezhny @tolusha )
- [ ]  #10115 New folders do not register in the jdt.ls workspace (@vrubezhny 5d)
- [ ] #9971 Show Progress Reports from jdt.ls (needs clarification) (5d) (jpinkney)
- [ ] https://github.com/eclipse/che/issues/10324 Search for implementers (2d) (jpinkney)
- [x] #8666 Cleanup unused Java support Part 2 1d (@tsmaeder)
- [x] https://github.com/eclipse/che/issues/10076 Step in, Out, Over (1.5)
- [x] https://github.com/eclipse/che/issues/9243 Spring Boot and Vert.x: Debugger does not list frames and 
variables (2d) (@tolusha )
- [ ] https://github.com/eclipse/che/issues/10325 Reuse jdt.ls workspace
- [ ] https://github.com/theia-ide/theia/issues/1878 (jdt.ls extensions for Theia)
- [x]  #10326 File structure view (5.5) (@svor)
- [ ] Prepare debugger for merge (5d) (@tolusha)
  - [ ] Prepare developer documentation
  - [x] Prepare PR
-  [ ] #10327 Theia: Show class path dialog (8d)

Open PR's 
- [ ] https://github.com/eclipse/che-theia-java-plugin/pull/2/files (#8965) (libraries feature) (1.5d)
- [x] https://github.com/theia-ide/theia/pull/2321 breakpoint manager 0.5d
- [x] https://github.com/eclipse/che/pull/10323 Remove rename & move refactorings 0.5

Previous sprint: https://github.com/eclipse/che/issues/10075

**Comment by JPinkney** [comment]
12d for me

**Comment by fbricon** [comment]
5d for me. (Will take some PTO)

As for the jdt.ls stuff planned for end of july:

[#556](https://github.com/eclipse/eclipse.jdt.ls/issues/556) Add ImplementationProvider Support enhancement 
[#697](https://github.com/eclipse/eclipse.jdt.ls/issues/697) Convert from type to `var` Java 10 code-actions 
[#696](https://github.com/eclipse/eclipse.jdt.ls/issues/696) Convert from `var` to the appropriate type Java 10 code-actions
[#658](https://github.com/eclipse/eclipse.jdt.ls/issues/658) Refactor: Convert annoymous class to lambda express code-actions 
[#620](https://github.com/eclipse/eclipse.jdt.ls/issues/620) JDK API leaks despite source/target compatibility settings bug

**Comment by snjeza** [comment]
10d for me
