### ISSUE TITLE
Platform-2018-07-31 (Sprint: 152)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10307]
### Features related to Authentication and security in Theia IDE 

- [x] Cover ws-agent/exec-agent/terminal with JWT proxy | https://github.com/eclipse/che/issues/10081 | 3sp
- [x] Make a unique nonce as optional check in jwtproxy | https://github.com/eclipse/che/issues/10090 | 5sp
- [x] Create exclude rules for jwtproxy | https://github.com/eclipse/che/issues/10312 | 8sp
- [x] Make `aud` claim optional StringOrURI in JWTProxy | https://github.com/eclipse/che/issues/10308 | 8sp
- [x] Authentication cookie set up mechanism | https://github.com/eclipse/che/issues/10349 | 13sp

### Technical debts and bugs
- [x] Propagate proxy settings to ws containers on OpenShift | https://github.com/eclipse/che/issues/10350 5sp
- [x] Display Che version in swagger UI | https://github.com/eclipse/che/issues/10351 5sp
- [x] Add an ability to configure public accessible paths for Che secure servers | https://github.com/eclipse/che/issues/10400 5sp

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 10d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15 d | 
| Sergii Leshchenko | 8 d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 47 | 47 |
