### ISSUE TITLE
QE-2018-07-31 (Sprint: 152)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#10311]
### Sprint goals
- Create new Selenium tests according to test plan.

### Issues tied to objectives
- [x] Cover use cases of "Kubernetes/OpenShift machines are started sequentially" issue by selenium tests https://github.com/eclipse/che/issues/10305 5sp
- [x] Investigate problem of running selenium tests on the Kubernetes infrastructure https://github.com/eclipse/che/issues/10322 2sp
- [x] Unexpected destroy of selenium test objects in case of executing the package of tests https://github.com/eclipse/che/issues/10373 2sp
- [x] Delete the 'try/catch' block from the 'ContributeTabTest' according to close the issues #9959 #10019 https://github.com/eclipse/che/issues/10375 1sp
- [x] Create selenium test to cover the 'Upload Folder/File' feature https://github.com/eclipse/che/issues/10204 2sp
- [x] Cover Apache Camel language server functionality by selenium test https://github.com/eclipse/che/issues/10316 2sp
- [x] Improve language servers test plan https://github.com/eclipse/che/issues/10120 3sp
- [x] Cover Golang language server functionality by selenium test https://github.com/eclipse/che/issues/10084 2sp
- [x] Create selenium test to cover import the 'Eclipse Che' project https://github.com/eclipse/che/issues/10107 5sp

### Unplanned 
- [ ] Fix selenium test after update xterm.js from 2.4.0 to 3.3.0 version https://github.com/eclipse/che/issues/9909 5sp
- [x] Unexpected fail of "MacrosCommandsEditorTest" selenium test https://github.com/eclipse/che/issues/10392 1sp
- [x] Adapt selenium tests according to changes in the flow for adding a new stack https://github.com/eclipse/che/issues/10415 2sp
- [x] Cover JSON language server functionality by selenium test https://github.com/eclipse/che/issues/10398 2sp
- [x] Unexpected fail of "che-multiuser-master-ocp-oauth-test" and "che-multiuser-master-ocp-recreate-strategy-test" jobs https://github.com/eclipse/che/issues/10430 1sp
- [x] Cover Yaml language server functionality by selenium test https://github.com/eclipse/che/issues/10442 2sp
- [x] Increase stability of the "CheckIntelligenceCommandFromToolbarTest" selenium test https://github.com/eclipse/che/issues/10449 1sp
- [x] Investigate the failing selenium test 'AmendCommitTest' on CI job https://github.com/eclipse/che/issues/10520 1sp
- [x] Adapt selenium tests that checks factories for kubernetes infrastructure https://github.com/eclipse/che/issues/9768 2sp
- [ ] Figure out reason differences in the selenium tests on K8S infrastructure https://github.com/eclipse/che/issues/10532 3sp
- [x] Create "SeleniumWebDriverHelper#waitCondition(ExpectedCondition<Boolean> expectedCondition)" method for selenium tests https://github.com/eclipse/che/issues/10105 2sp
- [x] Fix logical mistakes in the "SeleniumWebDriverHelper" class methods https://github.com/eclipse/che/issues/10347 2sp
- [ ] Change steps in the CSharpFileEditingTest after resolving of restore C# dependencies https://github.com/eclipse/che/issues/10557 2sp
- [x] Add method to the "WaitUtils" class for waiting specified condition happens without using of "WebDriverWait" https://github.com/eclipse/che/issues/10292 2sp
- [ ] Make it possible to define selenium tests for several infrastructures at a time https://github.com/eclipse/che/issues/10583 3sp

### PR under review
- [x] https://github.com/eclipse/che/pull/10367
- [x] https://github.com/eclipse/che/pull/10252
- [x] https://github.com/eclipse/che/pull/10367
- [x] https://github.com/eclipse/che/pull/10393
- [x] https://github.com/eclipse/che/pull/10385
- [x] https://github.com/eclipse/che/pull/10328
- [x] https://github.com/eclipse/che/pull/10421
- [x] https://github.com/eclipse/che/pull/10405
- [x] https://github.com/eclipse/che/pull/10422
- [x] https://github.com/eclipse/che/pull/10440
- [x] https://github.com/eclipse/che/pull/10463
- [x] https://github.com/eclipse/che/pull/10534
- [x] https://github.com/eclipse/che/pull/10527
- [ ] https://github.com/eclipse/che/pull/10529
- [x] https://github.com/eclipse/che/pull/10533

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 10 |
| Maxim Musienko | 10 |
| Dmytro Nochevnov | 5 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
| Total | 55 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 24 | 24 |
