### ISSUE TITLE
Add openshift implemetation for terminal server side in the che-theia-terminal-plugin and che-theia-task-plugin

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#10314]
### Description
We have extension to provide multi-container terminal experience  https://github.com/eclipse/che-theia-terminal-plugin.git  for Theia . But it's works only on the docker. We should provide openshift implementation. Client side can be the same, server side can contains some trigger to have ability work on the both environments.

Edit: This is also an issue for `che-theia-task-plugin`

- [x] Investigation of Openshift API to provide the solution for exec work on it: https://github.com/eclipse/che/issues/10813
- [x] Implement terminal sidecar compatible with Kubernetes (and Openshift) https://github.com/eclipse/che/issues/10357
- [x] Implement exec sidecar compatible with Kubernetes (and Openshift) https://github.com/eclipse/che/issues/10358

**Comment by AndrienkoAleksandr** [comment]
Seems server side should be moved to the separated repo. It's works with task extension to spawn command, so it's not very good to store this server side in the terminal repo.

**Comment by sunix** [comment]
@AndrienkoAleksandr and team, could we list the plugins and extensions that are currently using just the Docker exec api ? (not openshift)

**Comment by AndrienkoAleksandr** [comment]
I think for know it's two extensions

**Comment by sunix** [comment]
- che-theia-task
- che-theia-terminal
?

**Comment by AndrienkoAleksandr** [comment]
yes

**Comment by AndrienkoAleksandr** [comment]
Working on subtask: https://github.com/eclipse/che/issues/10813
