### ISSUE TITLE
IDE2-2018-07-31 (Sprint: 152) 

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#10348]
## 1. Extensibility model implementation
- [x] Implement 'showOpenDialog' method of plugin API  https://github.com/theia-ide/theia/issues/2153 25sp
- [ ] Introduce Folder Pick API https://github.com/theia-ide/theia/issues/2337 25sp
- [ ] Implement 'showSaveDialog' method of plugin API https://github.com/theia-ide/theia/issues/2173 25sp
- [ ] Add support for preferences schema from contribution point of a manifest file https://github.com/eclipse/che/issues/9990 25sp
- [x] [plug-in][languages] Add get languages, set language configuration and match to Plugin API https://github.com/theia-ide/theia/issues/2348

## 2. Factory post loading action support in Theia IDE
- [ ] [todo for Sun] add issues for met issues on running Che on docker infra
- [ ] Handle the runCommand factory's action in Theia https://github.com/eclipse/che/issues/10167 25sp
- [ ] Find/Replace investigation 10sp

## 3. Sample plugins in Theia IDE
- [x] Add options to generate different plugin samples in Theia plugin generator https://github.com/eclipse/che/issues/9956 10sp

## Other  issues: 
- [x] [plug-in] output channel visibility https://github.com/theia-ide/theia/issues/2330 15sp
- [x] [plugin-ext] NPE in `TextEditorPropertiesMain.getOptionsFromEditor` https://github.com/theia-ide/theia/issues/2258 10sp
- [x] Display logs in the main Theia instance from hosted one https://github.com/theia-ide/theia/issues/2338 40sp
- [x] Authentication cookie set up mechanism https://github.com/eclipse/che/issues/10349 25sp
- [x] Apply javascript method https://github.com/eclipse/che/issues/10258 15sp
- [x] User Dashboard: What is Add Stack Button Supposed to Do? https://github.com/eclipse/che/issues/10335 in progress 5sp
- [x] Add websocket reconnection feature to workspace loader app https://github.com/eclipse/che/issues/10365 25sp

**Total planned = [todo]sp**

### Pending PRs
- [x] [CHE-9840 add factory events handling](https://github.com/eclipse/che-theia-factory-extension/pull/3)
- [x] [CHE-10097, CHE-10098, CHE-256: fix bugs related to installers on Stack Details page](https://github.com/eclipse/che/pull/10367)
- [x] [Generate yarn cache with THEIA_VERSION. Generate resolutions to use strict Theia dependencies](https://github.com/eclipse/che/pull/10164)
- [ ] X [CHE-LIB-57: Update xterm.js to the version 3.3.0](https://github.com/eclipse/che/pull/10037) qa should adaptate selenium tests;
(https://github.com/eclipse/che/issues/9909)

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[The retrospective document.](https://docs.google.com/drawings/d/1sdybv33BsTmvTzRMjlONv0V_aaJrzLXAFoG5XBmVgxY/edit)
