### ISSUE TITLE
IDE2-2018-08-21 (Sprint: 153) 

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#10461]
### Sprint Goals:
1. Harden plug-in system: languages and views
2. Processing post-loading actions for factories

## 1. Extensibility model implementation
- [x]  [plug-in][languages] Add ability to register completion provider to Plugin API https://github.com/theia-ide/theia/issues/2350 60sp
- [x] Introduce Folder Pick API https://github.com/theia-ide/theia/issues/2337 25sp
- [x] Implement 'showSaveDialog' method of plugin API https://github.com/theia-ide/theia/issues/2173 25sp
- [ ] [plug-in] Implement 'views' and 'viewsContainers' contribution points and Tree API https://github.com/theia-ide/theia/issues/2498
  - [ ] [plug-in] Implement 'viewsContainers' contribution point https://github.com/theia-ide/theia/issues/2505 30sp
  - [ ] [plug-in] Implement 'views' contribution point https://github.com/theia-ide/theia/issues/2507  60sp

## 2. Sample plugin
- [x] Add license option for plugin generator https://github.com/eclipse/theia-generator-plugin/issues/6 30sp

## 3. Hosted mode polishing
- [x] Add watch mode to the generated plugins https://github.com/theia-ide/theia/issues/2434

## 4. Factory post loading action support in Theia IDE
- [ ] Handle the runCommand factory's action in Theia https://github.com/eclipse/che/issues/10167 25sp
- [x] Find replace for factories in Theia https://github.com/eclipse/che/issues/10653 10sp
- [x] Support the macros - {$current.project.path} in Theia tasks https://github.com/eclipse/che/issues/10657

## Other  issues: 
- [ ] Upgrade project license from EPL-1.0 to EPL-2.0 https://github.com/eclipse/che/issues/10465 15sp
- [x] Workspace-loader app should show error when request to start a workspace fails https://github.com/eclipse/che/issues/10538
- [x] Make workspace-loader (or UD) show an error received from websocket on workspace start failure https://github.com/eclipse/che/issues/10540 15sp
- [x] Deleting a not supported workspace breaks dashboard in OpenShift https://github.com/eclipse/che/issues/10544 20sp
- [x] Plugin panel is always empty https://github.com/theia-ide/theia/issues/2428 40sp
- [ ] Create image to build machine exec for terminal-extension and for task api extension https://github.com/eclipse/che/issues/10590
- [x] Persist package.lock with fixed dependency versions https://github.com/eclipse/che/issues/10656

**Unplanned:**
- [x] Wrong order of stacks after sorting https://github.com/eclipse/che/issues/5650
- [x] A workspace item in an organization workspaces list is not clickable https://github.com/eclipse/che/issues/9148
- [x] Workspace loader hangs up when a user doesn't have permissions to use a workspace https://github.com/eclipse/che/issues/10687
- [ ] Upgrade lodash to version 4.17.5 or higher https://github.com/eclipse/che/issues/10775
- [x] Improve loader.html to be more user-friendly https://github.com/eclipse/che/issues/10769

**Total planned = [todo]sp**

### Pending PRs
- [x] [OpenDialog Plugin API](https://github.com/theia-ide/theia/pull/2398)
- [x] [Add ability to provide language and syntax highlight by plugin](https://github.com/theia-ide/theia/pull/2477)
- [x] [NPE in `TextEditorPropertiesMain.getOptionsFromEditor`](https://github.com/theia-ide/theia/pull/2479)

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[The retrospective document](https://docs.google.com/document/d/1zF414-CLUJMV-WD92hJcgkeszTc9PUwa42GbiqIZV4o/edit)
