### ISSUE TITLE
Delivering of ChePlugins binaries to the editor container

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10561]
### Description
Walking skeleton epic describes that we need an ability to deliver ChePlugins binaries to a che editor sidecar container. This would allow us, for example, to have a dynamic pluggability in Che Theia. 
There might be different ways to deliver those binaries, so we need to investigate options and implement at least one of them for the walking skeleton POC.
Delivering options:
1. Usage of data containers that don't run any process but pulled from a registry and mount some folder to another container (editor container)
1. Download binaries from a marketplace (for now it is just an Apache server)
1. Usage of init container in kubernetes

We might also think about ChePlugins owners being able to use different mechanisms (described here or others) depending on their needs but this is not needed for a POC and it might complicate the flow, so having just one mechanism seems more natural for me for the time being. 

**Subtasks**:
- [ ] Investigate delivering of Theia plugins with data containers #10369
- [ ] Add a plugin downloader component in wsmaster that
   - Get as input the workspace config list of plugins and editor
   - Downloads the plugins and editor files (`*.tar.gz` and `*.theia`) from the plugin registry
   - Extract the tar.gz in `che-plugins` and `che-editor` folders
   - Copies `*.theia` files in a `theia-plugins` folder
   - Returns the local paths to the `che-plugin.yml` and `che-editor.yml` files
- [ ] Add an editor plugin injector component in wsmaster that copies the content of editor plugins folder (theia-plugins) in the volume that will be mounted in the theia container

**Comment by l0rd** [comment]
I have created [this document] (https://docs.google.com/document/d/1CdKjN0M8vxTpnDxDI1JWttelNQp5gb3B_xRjhzjVHKU/edit#) to discuss this issue implentation and introduce the concept of Che Plugin Broker.

**Comment by garagatyi** [comment]
Work was done in a [branch](https://github.com/eclipse/che/compare/master...garagatyi:integrateBroker) but there were technical difficulties. 
The plan is to:
- clean up the code from the mentioned branch and update PR https://github.com/eclipse/che/pull/10740
