### ISSUE TITLE
Add Theia Plugin APIs to support VS Code Kubernetes Tooling 

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#10574]
The goal is to be able to run [VSCode Kubernetes Tooling](https://github.com/Azure/vscode-kubernetes-tools) as a Theia plugin. To achieve it we should extend [Theia Plugin API](https://github.com/theia-ide/theia/blob/master/packages/plugin/API.md).

This is the list of initial k8s tooling commands we want to support:
- apply
- get
- describe
- follow
- logs
- follow events

TODO: List the needed API 
Workspace API's:

- [x] workspace.registerTextDocumentContentProvider https://github.com/theia-ide/theia/issues/2786
- [x] workspace.registerFileSystemProvider https://github.com/theia-ide/theia/issues/2861
- [x] workspace.applyEdit https://github.com/theia-ide/theia/issues/2784
- [x] workspace.onDidSaveTextDocument https://github.com/theia-ide/theia/issues/3201

Languages API's: https://github.com/theia-ide/theia/issues/2341

- [x] - languages.registerHoverProvider https://github.com/theia-ide/theia/issues/2601
- [x] - languages.registerDocumentLinkProvider https://github.com/theia-ide/theia/issues/2964
- [x] - languages.registerCodeLensProvider https://github.com/theia-ide/theia/issues/3199
- [ ] - languages.registerTelemetry
- [x] - languages.registerDocumentSymbolProvider https://github.com/theia-ide/theia/issues/3200

Window :

- [x] window.registerTreeDataProvider https://github.com/theia-ide/theia/issues/2782
- [x] window.showTextDocument theia-ide/theia#2801
- [x] window.withProgress theia-ide/theia#2802

Debug:

- [x] debug.registerDebugConfigurationProvider
- [x] debug.activeDebugSession
- [x] onDidTerminateDebugSession
- [x] onDidChangeActiveDebugSession
- [x] startDebugging

Menu API : 

- [x] Menu Plugin API https://github.com/theia-ide/theia/issues/2785
- [x] Add support for the context menus in the contributed views https://github.com/theia-ide/theia/issues/3646
- [x] Add support for 'when' expressions https://github.com/theia-ide/theia/issues/3658

Contribution Points used in package.json :

- [x] - confuguration
- [x] - views
- [x] - menus https://github.com/theia-ide/theia/issues/2785
- [x] - commands
- [ ] - languages
- [x] - debuggers

Related PR's:

- [x] support vscode.workspace.findFiles https://github.com/theia-ide/theia/pull/3128

**Comment by l0rd** [comment]
cc @evidolob @benoitf @ashumilova @slemeur

**Comment by vparfonov** [comment]
One more problem detected: 
```
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]
root INFO Started watching the git repository: file:///Users/vparfonov/Projects/RedHat/vscode-kubernetes-tools
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO [nsfw-watcher: 5862] Started watching: /Users/vparfonov/.theia
Started watching: /Users/vparfonov/Projects/RedHat/vscode-kubernetes-tools
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.15.0'.
task INFO Config file tasks.json does not exist under file:///Users/vparfonov/Projects/RedHat/vscode-kubernetes-tools
root ERROR No plugin resolver found for the entry local-path:/Users/vparfonov/Projects/vsix
```

**Comment by l0rd** [comment]
@vparfonov @slemeur I added the list of commands to support first:
- apply
- get
- describe
- follow
- logs
- follow events

**Comment by apupier** [comment]
It would be nice to cover the use case of Camel Language Server.
The VS Code plugin is here https://github.com/camel-tooling/camel-lsp-client-vscode
The Server code is here https://github.com/camel-tooling/camel-language-server

I'm not sure how to know all the API/commands that are used.

On Language Server side, we can see the "activated" features here https://github.com/camel-tooling/camel-language-server/blob/c50fb5954cf521b3471651e2856ca4e1ce00b8a9/src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java#L78-L86

Please note that for now when using the released VS Code plugin NPEs are thrown, which seems to be due to the fact that exitServer is called before a startServer. I made it more robust to avoid NPE https://github.com/camel-tooling/camel-language-server/pull/166 and it will be better in next release.
Even wit this new version, it is not working, there is no more errors or logs.
Reported https://github.com/camel-tooling/camel-lsp-client-vscode/issues/72 to be able to remote debug the server part.

**Comment by slemeur** [comment]
Hi @apupier.
Are you asking to prioritize the different plugin APIs that you might need for the Camel Language Server? 
Or do you have a particular use case related to a Camel with Kubernetes that you'd like to see covered?

**Comment by slemeur** [comment]
ok :)
That's why I asked. This issue is related to the work needed to support the VSCode Kubernetes plugin in Che. 
Do you mind creating a separate issue for your requirement?

**Comment by apupier** [comment]
> That's why I asked. This issue is related to the work needed to support the VSCode Kubernetes plugin in Che.

oups sorry, I thought it was a top level issue for all VS code plugins. my bad.

> Do you mind creating a separate issue for your requirement?

here it is https://github.com/eclipse/che/issues/11705

**Comment by l0rd** [comment]
For `apply` command we need https://github.com/theia-ide/theia/pull/2979 to be merged upstream

**Comment by azatsarynnyy** [comment]
For context menus we need https://github.com/theia-ide/theia/issues/3646

**Comment by azatsarynnyy** [comment]
I've updated the description with a couple of tasks related to Menu API

**Comment by vparfonov** [comment]
Need to fix:

- [ ] Command "Kubernetes: Delete Context" of Kubernetes Tolling don't work in Theia #12745
- [ ] Command "Kubernetes: Set Kubeconfig" of Kubernetes Tolling don't work in Theia #12746

**Comment by PavelSosin** [comment]
Hint: if you had minikube installed on you computer (  desktop/laptop) and now is trying to switch to Docker desktop Kubernetes cluste) you can experience context switch glitch - minikube is the only choice. It is easily repairable: rename you minikube config.json to something like configOld.json and set KUBECONFIG system variable pointing to kubeconfig file create by Docker Desktop installation.

**Comment by vparfonov** [comment]
Going to close this epic, will continue working on some separate issues like:
[k8s plugin] Kubernetes:Run command should work w/o Docker che#13316
