### ISSUE TITLE
Languages Sprint 153

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#10571]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 5d  | 3d | 3d
@tolusha |  15d | 9d | 9d
@svor | 14d | 8d | 10d
@vrubezhny | 13d | 8d | 8d
@JPinkney | 13d | 8d | 8d

- [x] Address Selenium Test Merge Blockers #9591 (@svor 5d, @tolusha 3d, @tsmaeder 3d )
- [ ] Reuse jdt.ls workspace #10325 
- [ ] Source folders of Plain Java project are not properly shown in Project Explorer after WS is restarted #10456 (3d) (@vrubezhny)
- [ ] New folders do not register in the jdt.ls workspace #10115 (@vrubezhny 5d)
- [ ] Implementers is Broken for Class Files #10337 (2d)
- [ ] (jdt.ls extensions for Theia) https://github.com/theia-ide/theia/issues/1878 (5d) (@svor)
- [x] Debugger merge (5d) (@tolusha)
-  [ ] Theia: Show class path dialog #10327 (8d)
- [x] Rebase on master (1d) @tolusha 
Open PR's 
-  [x] https://github.com/eclipse/che-theia-java-plugin/pull/5 #10324 
-  [ ] https://github.com/theia-ide/theia/pull/2461 #9971 
-  [ ] https://github.com/eclipse/che-theia-java-plugin/pull/2 #8965

Previous sprint: https://github.com/eclipse/che/issues/10299

**Comment by vrubezhny** [comment]
availability 13 days (taken out 1 day for WTP and 1 day of holiday in 
Spain - Wednesday, August 15,
2018)

**Comment by snjeza** [comment]
availability 13d.
x0.6=8d
