### ISSUE TITLE
Platform-2018-08-21 (Sprint: 153)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10585]
### Features related to Authentication and security in Theia IDE 

- [x] Make loader page URL configurable within property | https://github.com/eclipse/che/issues/10611 | 5sp
- [x] Make public/private signing keys pair per-workspace and synch with workspace runtime (renew pair on each workspace restart) | https://github.com/eclipse/che/issues/10074 | 13sp
- [ ] ~~~Inject a jwtproxy container into each Pod instead of creating a separated Pod for it | https://github.com/eclipse/che/issues/10404 | 13sp~~~
- [x] Rework JwtProxyConfigBuilder to use Objects instead of formatting string config template | https://github.com/eclipse/che/issues/10402 | 5sp

### Features related to ws.next
- [x] Build a container to run the plugin registry and document how to use it to serve theia and the 2 plugins needed to run the scenario | https://github.com/eclipse/che/issues/9868 8sp
- [x] Move the plugin registry files (YAML file, instructions, script etc) from eclipse/che to eclipse/che-plugin-registry | https://github.com/eclipse/che/issues/10615 8sp

### Technical debts and bugs
- [ ] Migrate to mockito/mockito-testng | https://github.com/eclipse/che/issues/10617 8sp
- [x] Enable DELETE /api/user api method | https://github.com/eclipse/che/issues/10620 8sp

### Unplanned
- [x] Read workspace permission allows to use/delete projects as well https://github.com/eclipse/che/issues/10536
- [x] Move the Plugin Registry to its own repository https://github.com/eclipse/che/issues/10615
- [x] [Walking Skeleton] Setup a CI for the Plugin Registry https://github.com/eclipse/che/issues/10651
- [x] Factory and stack features are not supported in Workspace.Next https://github.com/eclipse/che/issues/10368
- [x] Add an ability to configure if a secure server should supports authentication with a cookie or not  https://github.com/eclipse/che/issues/10725
- [x] Add an ability to configure a JwtProxy image https://github.com/eclipse/che/issues/10733
- [x] Add a "Plugin Registry API" to retrieve the list of plugins https://github.com/eclipse/che/issues/10745
- [x] Restore and actualize README.md file in che-jwproxy repo https://github.com/eclipse/che-jwtproxy/issues/7
- [ ] Document "Authentication and security in Theia IDE" feature  https://github.com/eclipse/che/issues/10762
- [x] Add type of the object to the index file of che-plugin-registry https://github.com/eclipse/che/issues/10781
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15 d | 
| Sergii Leshchenko | 12 d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 68 | 47 |
#### Retrospective Comments
 - Action item @skabashnyuk find a way to publish videos on official Eclipse Che account.
 - Action item @sleshchenko evaluate Zandhub to use in platform team scrum process.
 - Action item @mshaposhnik talk with @vkuznyetsov about the stability of Selenium tests.

**Comment by garagatyi** [comment]
@skabashnyuk you took issue https://github.com/eclipse/che/issues/10404 into the sprint.
It's not clear to me how you want to overcome issues described in my comment https://github.com/eclipse/che/issues/10404#issuecomment-405186403
For example our current mysql stack would be broken with this change.
Do you think those points are not valid and user's won't suffer because of that?

**Comment by garagatyi** [comment]
After discussing with @sleshchenko I figured out that my previous message is not clear enough. 
So here I'll try to explain it in a better way.
If we decide to run workspaces of multiple users at the same namespace than we would have to forbid usage of services by users. We also use it on a mysql stack. 
If we forbid services then a lot of apps and mysql stack would be broken. 
I'm not aware whether we have a requirement to run different users' workspaces  in the same namespace but creation of proper isolation seems a very hard task. Kubernetes already has isolation with namespaces but we are considering creating an alternative implementation. So I'm wondering how much we would benefit by doing that instead of just using separate namespaces.
Apart from that walking skeleton already has service discovery in place and it works over kubernetes services. We would have to rework it too if we want to forbid creation of services in a workspaces because of their insecure nature.

**Comment by skabashnyuk** [comment]
@garagatyi @sleshchenko you are right. There is a lot of small details that we need to take into account. I think we can postpone https://github.com/eclipse/che/issues/10404 until we have time to discuss it with @l0rd and @ibuziuk .

**Comment by garagatyi** [comment]
:+1:
