### ISSUE TITLE
QE-2018-08-21 (Sprint: 153)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#10589]
### Sprint goals
- Create new Selenium tests according to test plan.
- Stabilization of unstable tests

### Issues tied to objectives
- [ ] Cover "Dashboard/Workspace Details" part of test plan by selenium tests https://github.com/eclipse/che/issues/10588 8sp
- [x] Create test session for checking interaction of language servers with two open browser instances https://github.com/eclipse/che/issues/10581 3sp
- [x] Figure out of reason increasing building time of maven project between docker and k8s infrastructure https://github.com/eclipse/che/issues/10582 3sp
- [x] Fix selenium test after update xterm.js from 2.4.0 to 3.3.0 version https://github.com/eclipse/che/issues/9909 5sp
- [x] Figure out reason differences in the selenium tests on K8S infrastructure https://github.com/eclipse/che/issues/10532 3sp
- [x] Change steps in the CSharpFileEditingTest after resolving of restore C# dependencies https://github.com/eclipse/che/issues/10557 2sp
- [x] Make it possible to define selenium tests for several infrastructures at a time https://github.com/eclipse/che/issues/10583 3sp

### Unplanned 
- [x] Fix selenium tests after updating licenses headers https://github.com/eclipse/che/issues/10612 3sp
- [x] Improve language servers test plan https://github.com/eclipse/che/issues/10120 2sp
- [x] Increase stability of the "WorkspacesListTest" selenium test https://github.com/eclipse/che/issues/10671 1sp
- [x] Fix TestGitHubRepository class to be able to delete test repository by name https://github.com/eclipse/che/issues/10679 1sp
- [x] Increase stability of "OpenExternalLibraryFileAfterRefreshTest" selenium test  https://github.com/eclipse/che/issues/10723 1sp
- [x] Fix unstable selenium tests from dashboard and miscellaneous package https://github.com/eclipse/che/issues/10724 1sp
- [x] Unexpected fail of CheckIntelligenceCommandFromToolbarTest selenium test https://github.com/eclipse/che/issues/10776 1sp
- [x] Remove unnecessary Service class from all depended tests https://github.com/eclipse/che/issues/10821 2sp
- [ ] Unexpected fail of AddOrImportProjectFormTest selenium test https://github.com/eclipse/che/issues/10849 1sp
- [ ] Remove info about resolved issues from selenium tests https://github.com/eclipse/che/issues/10848 1sp

### PR under review
- [x] https://github.com/eclipse/che/pull/10670
- [x] https://github.com/eclipse/che/pull/10642
- [x] https://github.com/eclipse/che/pull/10685

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 2 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 7 |
| Sergey Skorik | 15 |
| Total | 54 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 27 | 19 |

### Retrospective Comments
Cover "Dashboard/Workspace Details" part of test plan by selenium tests https://github.com/eclipse/che/issues/10588 will be finished in next sprint
