### ISSUE TITLE
Cover "Dashboard/Workspace Details" part of test plan by selenium tests

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#10588]
### Description
We have the test plan where described all use cases for dashboard:
https://docs.google.com/document/d/1aXUAWFOOylrk-_nO5Iqm77M0Viu8ykCjaQMtJuEBvUA/edit#heading=h.wf4eguoewmmg
 
We should create selenium tests according to the use cases which described in the "Dashboard/Workspace Details" section.

#### Workspace details
- [x] overview: https://github.com/eclipse/che/issues/10631
- [x] projects: https://github.com/eclipse/che/issues/10662
- [x] machines: https://github.com/eclipse/che/issues/10692
- [ ] installers
- [ ] servers
- [ ] env variables
- [ ] volumes
- [ ] config
- [ ] SSH
- [ ] Share
