### ISSUE TITLE
IDE-2018-08-21 (Sprint: 153)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#10599]
### Issues

- [ ] JDT.LS integration issues #10621

#### Artem 
- [x] Theia: Command Palette Improvement #8976 8d

#### Dmytro 
- [ ] Theia: Ability to handle the stacktrace (Java + JavaScript?) #9248 10d
- [ ] Clean up subscriptions for expired websocket sessions #6177 4d

#### Roman 
- [ ] Theia: Editor Key Bindings switching (Default, VI, Emacs) #9244 6d 
- [x] IDE does not re-initializes FileTypeRegistry on workspace restart #9467 3d
- [ ] File in /projects treated as a project #10586 3d
- [x] Command removed after a freeze #10309 2d

####  Vitalii
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574 (will work under some specification for this issue and adding sub issues) 5d
- [x] replace orion patches with forked code https://github.com/eclipse/che-lib/issues/93 3d

#### Vlad
- [ ] The Refactor -> Rename feature does not work properly for C# #10180 3d
- [ ] Add an ability to re-run a task in Theia from a terminal widget #10381 5d
- [x] Right-click menu can not display completely in some resolution #10447 4d
- [x] Add an ability to clear terminal's output in Theia #10380 2d

#### Igor 
- [x] _[Theia]_ Preferences UI for Theia IDE #9730 3d
- [ ] Unexpected the 'java.lang.OutOfMemoryError' in ws-agent after import Eclipse Che #10543 3d
- [x] Failed to create maven submodule with archetype #10360	3d
- [ ] Implement Git Status Cache #10696 

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 8 |  
| Vlad |14 |  
| Dmytro  | 14 |   
| Roman  |14 | 
| Vitalii  |8|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 71/65 |  |
| **Velocity** | |  |

**Comment by vparfonov** [comment]
ok
