### ISSUE TITLE
EclipseCon Europe Workshop

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#10644]
## Epic Description

**Goal** Enable the self-hosting experience for any Che user and inspire users to build and share new Che plugins

**Story** As a plugin contributor, I want to create a plugin (server + ui) on che.openshift.io and add it to the plugin registry so that I can showcase it

Example use cases: 
  - Integrate a new LS
  - Integrate a code prettifier 

#### Success Criteria

- Plugin Authoring Workshop has been run both internally and externally using che.openshift.io
- Plugin Authoring Getting Started Documentation is available on eclipse che documentation web site (not for che.openshift.io only)
- Che website part on how to extend Che has been updated
- Contribution guidelines are in the che-plugin-registry repository
- There are a few Plugin Samples with corresponding factories for che.openshift.io (a language server, a code prettifier)
- Plugin Scaffolding (tool to generate a che plugin repository template)
- When creating a workspace I can choose the plugins to add to it
- BONUS: Plan B to run a workshop if che.openshift.io is not available (internet is down)
- BONUS: An Editor swapping example (with Jupyter for example demo and blog post should be enough)

**What’s in EclipseCon Europe milestone** Easy self-hosting environment setup (for che and theia plugin authoring using che) on che.openshift.io

**What’s not in EclipseCon Europe milestone** Using a plugin marketplace to publish, search plugins for Che workspaces, the deployment of a public plugin registry to use from any Che instance

**Target** 23 October 

**Prerequisite and Architectural details**  #10123 

### For EclipseCon EU

- [x] Plugin registry should have validation of meta file path (alligned with id, version from meta.yaml) #10839 
- [x] Add PR check for che-plugin-registry to prevent merging invalid meta.yaml files #10844 
- [x] Add PR check for che-plugin-registry to prevent merging invalid meta.yaml files #10844
- [x] Plugin registry build process should ensure that meta.yaml content is aligned with its location #10839
- [x] Factory feature doesn't support Workspace.Next #10368
- [x] Add type of the object to the index file of che-plugin-registry #10781
- [x] Plugin registry should have a description how to get a list of plugins, how to get meta.yaml of a plugin from this list #10834
- [x] Add a Plugin Registry API to retrieve the list of plugins  https://github.com/eclipse/che/issues/10745
- [x] Add websocket reconnection feature to workspace loader app #10365

#### OSIO team

- [x] Add che-plugin-registry route on OSIO to be able to use it from UD https://github.com/redhat-developer/rh-che/issues/807
- [x] Add memory limit for ChePlugin container #10272
- [x] Registry doesn't support plugins with several versions https://github.com/eclipse/che-plugin-registry/issues/31
- [x] Make Workspace.Next work with Dockerimage recipe type #9871
- [x] Allow to customize Broker image and pull strategy for the development purposes
- [x] Add memory limits configuration into walking skeleton flow #11097
- [x] Cleanup plugins on Che Plugin Broker start to avoid usage of Theia plugins that were removed from workspace #11095
- [x] Do not allow the start of a workspace that has both installers and WS.NEXT plugins #11259
- [x] Allow to use JWT-proxy based Che workspace security for a particular user/workspace https://github.com/redhat-developer/rh-che/issues/853
- [x] How to avoid issues with k8s service number limit in WS.NEXT https://github.com/redhat-developer/rh-che/issues/934
- [x] Check if plugin-registry is configured when starting workspace with plugins #11124
- [x] An Editor swapping example ( with Jupyter for example demo and blog post should be enough) https://github.com/eclipse/che/issues/11383
- [x] Set memory request  for sidecars and broker https://github.com/eclipse/che/issues/11382
- [x] Check exec/terminal on OSIO https://github.com/redhat-developer/rh-che/issues/933 
- [x] Fix memory request for jwtproxy sidecar #11547

#### PLATFORM team

- [x] Cover plugin broker service methods with authorization checks https://github.com/eclipse/che/issues/11080
- [x] Plugin Broker doesn't work on multi-user Che #11071
- [x] Add public link for che-plugin-registry #10918
- [x] Add plugin's description to plugins list response https://github.com/eclipse/che/issues/11055
- [x] Set sidecar container name from sidecar definition #11096
- [x] Prevent caching of index file by browser https://github.com/eclipse/che-plugin-registry/issues/30
- [x] Plugin Broker does not respect pod status #11070
- [x] Provide an access token for `terminal` and `exec` sidecar #10991
- [x] Workspace.Next: Errors of broker pod are not propagated to a client #11068
- [x] Workspace.Next: Propagate logs from broker pod to ws-master #11069
- [x] Walking skeleton tooling in a workspace uses different pulling strategies for different containers https://github.com/eclipse/che/issues/11017
- [x] Configure broker timeout in Che #11120
- [x] Container tooling naming https://github.com/eclipse/che/issues/11031 
- [x] An Editor swapping example ( with Jupyter for example demo and blog post should be enough) https://github.com/eclipse/che/issues/11383
- [x] Setup default plugin registry url https://github.com/eclipse/che/issues/11352
- [x] Provide the possibility to specify the plugin registry at the plugin definition level #11265
- [x] Define plugin testing process https://github.com/eclipse/che/issues/11555
- [x] Add an ability to disable discover-ability of a plugin endpoint #11606
- [x] Add an ability to use a custom registry for WS.NEXT plugins https://github.com/eclipse/che/issues/11265
- [x] Add an ability to disable discover-ability of a plugin endpoint https://github.com/eclipse/che/issues/11606

#### IDE2 team

- [x] Add Dashboard widget to select the plugins when editing a workspace form https://github.com/eclipse/che/issues/10780
- [x] Avoid that an active workspace get killed after 15 minutes on osio #11267
- [x] Add Dashboard widget to select the plugins when creating a workspace form https://github.com/eclipse/che/issues/10780
- [x] Ask a user to remove installers from a workspace when they enables WS.NEXT editor or plugin #11401
- [x] Che Theia image doesn't have syntax hilighting for most languages (only typescript). We probably miss textmate extensions..

#### Florent

- [x] Access the Theia Plugin API from a remote container
- [x] Java, Typescript and nodejs debug support (as Theia extensions embedded in the Che Theia image)
- [x] Fix yeoman first time question (submit or not statistics)
- [x] Fix git
- [x] Cleanup env variables required for remote containers/ theia plugin broker after chat with Oleksandr  --> https://github.com/ws-skeleton/che-theia-remote-extension/commit/b7e6b40b78f3313b7bd9a680749169c8236cf213

#### Mario

- [x] Work with QE to add 2 tests for the Walking Skeleton scenarios #11047
- [x] Workshop script for plan A (everything on openshift.io) - [Draft](https://docs.google.com/document/d/1kMCvqqFRoi6mnljpgj9kYCZ1K7LIjPV0bqoqPkAn99U/edit#heading=h.erxag282u4mg)
- [x] Replace the 2 walking skelethon stacks with a Che 7 preview stack #11502

### Timeline

10th August: Friday Demos
17th August: Friday Demos
**21st August (Sprint Review)**: Walking Skeleton demos (not OSIO) at Sprint Review
24th August: Friday Demos
31th August: Friday Demos
7 September: Friday Demos
**10 September (Sprint Review)**: Walking Skeleton demos on OSIO at Sprint Review
14 September: Friday Demos
21 September: Friday Demos
28 September: Friday Demos
**2 October (Sprint Review)**: Terminal+Task plugins and Factories running on OSIO
*3 October: Start of K Train*
5 October: Friday Demos + Preview Workshop (walking skeleton team)
12 October: Friday Demos + First draft of the Documentation/Getting Started/Website/Repo Updated
19 October: Friday Demos + Internal Workshop (rh dev tools)
22 October: Che community event (workshop) 
23 October: Conference starts
25 October: Conference ends

**Comment by garagatyi** [comment]
Added `Add public link for che-plugin-registry` #10918 to the tasks list

**Comment by garagatyi** [comment]
I've rearranged tasks, marked some as finished, added splitting tasks by teams. There are plenty of tasks not moved to a specific team - we will need to triage them. 
I also think that we might want to move a couple of tasks from `After EclipseCon EU` to `For EclipseCon EU` section:
 - Add memory limit for ChePlugin container #10272 : without this tasks a workspace with Theia + user's image + service plugin sidecar takes 3GB of RAM which is way too much. It might also affect us to add more sidecar toolings into a workspace.
- Allow consuming LS functionality running as a sidecar in Theia base ide #9441 : seems as a prerequisite for this task `Java and Typescript LS packaged as Che plugins` which is included into `For EclipseCon EU` section

**Comment by dneary** [comment]
I would like to add a few more topics that we need to get done - I do not have permissions to edit the ticket.

1. We will have 2 Chromebooks on the Che stand, with wired internet, to do demos and to show Che. We can give these Chromebooks away at the end of the week, and I would like to have a challenge - have people complete a small coding challenge on che.openshift.io to enter a draw, and then Thursday we do the draw to give them away.
 - Define the challenge to be done
 - Create a Factory link to get people started
 - Something printed for the desk about the challenge and giveaway

2. "Walking Skeleton" blog post and/or tutorial - we need to make sure that we have some content on the website that supports the workshop on the walking skeleton

@eivantsov The first two items in #1 were the things I need your help with. My thinking is that we could do something like a Java, Python, and Javascript factory with (say) a list of numbers, and a requirement to print the numbers in order (very simple - the goal is sign-ups and get them with hands on code) with the language of their choice. What do you think?

**Comment by skabashnyuk** [comment]
added to the list of the Platform team tasks
- [ ] Define plugin testing process https://github.com/eclipse/che/issues/11555
- [ ] Add an ability to use a custom registry for WS.NEXT plugins https://github.com/eclipse/che/issues/11265

**Comment by garagatyi** [comment]
@skabashnyuk I added an entry:
Meta files must contain field type for Che to be able to recognize what broker to use with it eclipse/che-plugin-registry#41
Would your team be able to pick it up ASAP?

As far as I understand your team will also address: Add an ability to disable discover-ability of a plugin endpoint #11606
Am I correct? (I added an explanation for to make it an easyfix)

**Comment by skabashnyuk** [comment]
>Meta files must contain field type for Che to be able to recognize what broker to use with it >eclipse/che-plugin-registry#41
>Would your team be able to pick it up ASAP?

Commented in issue. Please take a look. https://github.com/eclipse/che-plugin-registry/issues/41#issuecomment-429660805
