### ISSUE TITLE
IDE2-2018-09-11 (Sprint: 154)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#10779]
### Sprint Goals:
1. Make execs work on Openshift
2. Views Plugin API
3. Languages Plugin API
4. Documentation clean-up: factories, tasks. User stories, requirements.
5. Start work on EclipseCon Europe Workshop
6. Dashboard integration with Theia IDE

##  1. Make execs work on Openshift
- [x] Investigation of Openshift API to provide the solution for exec work on it https://github.com/eclipse/che/issues/10813 25sp 
- [ ] Add openshift implemetation for terminal server side in the che-theia-terminal-plugin and che-theia-task-plugin https://github.com/eclipse/che/issues/10314 15sp

## 2. Views Plugin API
- [x] [plug-in] Implement 'viewsContainers' contribution point https://github.com/theia-ide/theia/issues/2505 30sp
- [x] [plug-in] Implement 'views' contribution point https://github.com/theia-ide/theia/issues/2507  60sp

## 3. Languages Plugin API
- [x] [plug-in][languages] Provide code diagnostic support to languages https://github.com/theia-ide/theia/issues/2351 25sp
- [x] [plug-in][languages] Register hover provider https://github.com/theia-ide/theia/issues/2601 25sp

## 4. Documentation clean-up: factories, tasks. User stories, requirements.
- [ ] improve che-theia-task-extension README file https://github.com/eclipse/che/issues/10683
- [ ] FAQ https://github.com/eclipse/che/wiki/Technical-FAQ [todo sub issues]

## 5. Start work on EclipseCon Europe Workshop
- [x] Add Dashboard widget to select the plugins https://github.com/eclipse/che/issues/10780 25sp

## 6. Dashboard integration with Theia IDE
- [x] Theia IDE and Che dashboard integration https://github.com/eclipse/che/issues/10798 5sp

## Other  issues:
- [x] [plug-in] Implement Plugin API https://github.com/theia-ide/theia/issues/2561 25sp
- [x] Error message not shown properly when failing to run a command in Che + Theia https://github.com/eclipse/che/issues/10800 5sp
- [x] Clean up branches in Che Theia hosted pluging extension https://github.com/eclipse/che/issues/10808 10sp
- [x] none of the branches are compiling for che-theia-hosted-plugin-manager-extension https://github.com/eclipse/che/issues/10810 10sp
- [x] Factory doesn't clone Che blank project on Openshift https://github.com/eclipse/che-theia-factory-extension/issues/8 10sp
- [x] Yo generator doesn't work in Theia image https://github.com/eclipse/che/issues/10756 10sp
- [x] Upgrade project license from EPL-1.0 to EPL-2.0 https://github.com/eclipse/che/issues/10465 15sp

**Unplanned:**
- [ ] Migrate Che Dashboard from bower to yarn https://github.com/eclipse/che/issues/10881
- [x] Machines are not displaying in the widget https://github.com/eclipse/che-theia-machines-plugin/issues/5
- [ ] Implement Webview API https://github.com/theia-ide/theia/issues/2708
- [x] Add technical info into readme of che-theia-hosted-plugin-manager-extesion https://github.com/eclipse/che-theia-hosted-plugin-manager-extension/issues/8
- [ ] Documentation with features, user stories and use cases of Che + theia self hosting https://github.com/eclipse/che/issues/11004
- [ ] Update to the newer Theia core https://github.com/eclipse/che-theia-terminal-extension/issues/3
- [x] [plug-in] Backend plugins doesn't work after Theia reload https://github.com/theia-ide/theia/issues/2840
**Total planned = [todo]sp**

### Pending PRs
- [x] CHE-10167 Add a handler to the runCommand factory's actions https://github.com/eclipse/che-theia-factory-extension/pull/5
- [x] https://github.com/eclipse/che-machine-exec/pull/1
- [x] https://github.com/eclipse/che-theia-terminal-extension/pull/4

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1zanT_J5LjSxMtuOQUX8dUySle8xokV50EIHimC3lPFU/edit)

**Comment by ashumilova** [comment]
[Retrospective document](https://docs.google.com/drawings/d/1zanT_J5LjSxMtuOQUX8dUySle8xokV50EIHimC3lPFU/edit)
