### ISSUE TITLE
QE-2018-09-11 (Sprint: 154)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#10818]
### Sprint goals
- Create new Selenium tests according to test plan.
- Stabilization of unstable tests

### Issues tied to objectives
- [ ] Cover "Dashboard/Workspace Details" part of test plan by selenium tests https://github.com/eclipse/che/issues/10588 8sp
- [x] Rework language server test plan to cover all supported language servers features https://github.com/eclipse/che/issues/10816 5sp
- [x] Change the method to expand the project tree in the 'SplitEditorFeatureTest' #10895 1sp
- [x] Get rid of test GitHub repositories in selenium tests of Eclipse Che #10890 5sp
- [x] Create E2E selenium tests to check creation of workspace from Java Theia stacks #10280 2sp
- [ ] [Language server] Unexpected fail of YamlFileEditingTest selenium test #10674 2sp
- [ ] Add a selenium test case to create the Pull Request from non-default branch #10000 2sp
- [x] Update selenium chrome-node version #10868 2sp
- [ ] Log reasonable error messages in case of confusing selenium launcher parameters #10248 5sp
- [x] Selenium test report html page lost its styles #10257 2sp
- [ ] Unexpected failing of NavigateToFileTest selenium test on CI #8465 3sp
- [ ] [Che-6] Create selenium test for checking add maven project and module #6905 3sp
- [x] Complete selenium tests for C# LS by Go to definition and Refactoring -> Rename features #10195 2sp
- [x] Complete E2E test for covering Open on github feature https://github.com/eclipse/che/issues/10952 2sp

### Unplanned 
- [x] Unexpected fail of "RollingUpdateStrategyWithWorkspacesStartStopTest" selenium test #10966 1sp
- [x] Update the "MachinesAsynchronousStartTest" selenium test according to the new expected behavior #10980 2sp
- [x] Update workspace templates to actual state #11048 2sp
- [x] Fix running the E2E tests on K8S CI job #11035 2sp
- [x] Create E2E test for covering skip root directory feature in a factoty #11081 3sp
- [x] WebDriverWait Instances Should not be Shared #11149 1sp
- [x] Use stable version of selenium chrome-node in E2E selenium tests #11160 1sp
- [x] Unexpected fail of "CheckErrorsWarningsTabTest" selenium test #11086 1sp
- [x] Add method to the "WaitUtils" class for waiting specified condition happens without using of "WebDriverWait" #10292 2sp

### PR under review
- [x] https://github.com/eclipse/che-parent/pull/78
- [x] https://github.com/eclipse/che/pull/10947
- [x] https://github.com/eclipse/che/pull/10968
- [x] https://github.com/eclipse/che/pull/10740
- [x] https://github.com/eclipse/che/pull/11002
- [x] https://github.com/eclipse/che/pull/11119
- [x] https://github.com/eclipse/che/pull/11043 
- [x] https://github.com/eclipse/che/pull/11037 
- [x] https://github.com/eclipse/che/pull/10997

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 14 |
| Maxim Musienko | 14 |
| Dmytro Nochevnov | 14 |
| Igor Ohrimenko | 10 |
| Sergey Skorik | 14 |
| Total | 66 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 44 | 21 |
