### ISSUE TITLE
Platform-2018-09-11 (Sprint: 154)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#10819]
### Features related to ws.next
- [x] Create README.md to eclipse/che-plugin-registry | https://github.com/eclipse/che/issues/10834 5sp
- [x] Plugin registry build process should ensure that meta.yaml content is aligned with its location | https://github.com/eclipse/che/issues/10839 5sp
- [x] Add PR check for che-plugin-registry to prevent merging invalid meta.yaml files | https://github.com/eclipse/che/issues/10844 5sp

### Technical debts and bugs
- [x] Permissions on Json/RPC | https://github.com/eclipse/che/issues/10861 | 13sp
- [ ] Limit scope of APIs that can be called with machine token | https://github.com/eclipse/che/issues/10710 | 13sp

### Finalize issues started in the previous sprint.
- [ ] Migrate to mockito/mockito-testng | https://github.com/eclipse/che/issues/10617 | 3sp
- [x] Factory doesn't support skipFirstLevel on projects | https://github.com/eclipse/che/issues/10464 | 5sp
- [x] No end-user indicator when Keycloak user has no email | https://github.com/eclipse/che/issues/10768 | 8sp

### Unplanned
- [ ] Db support documentation https://github.com/eclipse/che/issues/10950
- [ ] Integrate che-plugin-registry deployment with the deployments of Che on k8s/OS https://github.com/eclipse/che/issues/10842
- [ ] ~Move preparing of RuntimeContext to the async phase of workspace start https://github.com/eclipse/che/issues/8989~
- [x] Cover plugin broker service methods with authorization checks https://github.com/eclipse/che/issues/11080
- [x] Add public link for che-plugin-registry https://github.com/eclipse/che/issues/10918
- [x] Move Plugin broker to start of Kubernetes runtime https://github.com/eclipse/che/issues/11042
- [x] Add plugin's description to plugins list response https://github.com/eclipse/che/issues/11055
- [x] Plugin Broker doesn't work on multi-user Che https://github.com/eclipse/che/issues/11071
- [ ] Provide an access token for `terminal` and `exec` sidecars https://github.com/eclipse/che/issues/10991
- [x] Enable cross domain requests for plugin registry service 
- [x] Cover delete factory method with authorization check https://github.com/eclipse/che/issues/11155
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 14d |
| Max Shaposhnik | 7d | 
| Michail Kuznyetsov | 7d | 
| Sergii Leshchenko | 14 d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 57  | 41 |
#### Retrospective Comments
- Find if it possible to have push notifications from Mattermost
- Team members have to add his vacation dates to  dev-tools PTO calendar
