### ISSUE TITLE
IDE-2018-09-11 (Sprint: 154)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#10836]
### Issues

- [x] JDT.LS integration issues #10621

#### Artem 
- [x] JDT.LS: fix selenium tests in org.eclipse.che.selenium.intelligencecommand #10803 2d
- [ ] C# language server fails with timeout initializing error during selenium test session #10789 (analizing)
- [x] Open a preview URL in an embedded panel in Theia #10738 10d
- [x] che-theia-tasks-extension: fix last tslint errors #10825 3d
- [x] che-theia-tasks-extension: rewrite from scratch classes in https://github.com/eclipse/che-theia-task-plugin/tree/master/che-theia-task-extension/src/node/messaging #10822 

#### Dmytro 
PTO
#### Roman 
- [ ] Theia: Editor Key Bindings switching (Default, VI, Emacs) #9244 3d 
- [x] [Maven language server] 'Pom.xml' tab name is not valid after restarting of workspace #10755 2d 
- [x] [Maven language server] Unexpected exception in the 'dev-machine' console if file is not valid #10754 2d 
- [x] K8S: IDE is loaded after tab refresh only #10403 6d

####  Vitalii
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574 (will work under some specification for this issue and adding sub issues) 5d
- [ ] [Language server] Unexpected exceptions in the dev-machine console after initialization LS for GO lang #9796 2d
- [ ] Open in Terminal feature does not work if workdir is not set to the projects root #10894

#### Vlad
- [ ] The Refactor -> Rename feature does not work properly for C# #10180 3d
- [ ] Add an ability to re-run a task in Theia from a terminal widget #10381 5d
- [x] The "Create New Project" form does not close during timeout #10713 2d
- [x] Debug Name Xss attack #10613 2d
- [x] Create Project Make XSS attack ~~~ #10549 2d
- [x] XSS attack #10489 2d

#### Igor 
- [x] [Yaml language server] Unexpected warnings in the 'dev-machine' console after every changes in file #10735
- [x] [Language server] Exceptions in the 'dev-machine' console if 'camel.xml' file doesn't have content #10730
- [x] Not exist a user friendly info message when the workspace is stopped by timeout #10850
- [ ] Fill all PreferenceSchemas with missed default values theia-ide/theia#2470
- [ ] Add search functionality to the tree widget theia-ide/theia#2472

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |  
| Dmytro  | PTO |   
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
