### ISSUE TITLE
Dropping single user support

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#10996]
@riuvshin started a [discussion on che-dev mailing list](https://dev.eclipse.org/mhonarc/lists/che-dev/msg02643.html) proposing that we drop the support for Che single user (Che multi user would be the only option).

In this epic we want to track the tasks needed to drop single user support. 

- [ ] 1. adapt minishift addon to support multi-user Che https://github.com/minishift/minishift/issues/2746
- [ ] 2. find an alternative to keycloak for local development (e.g. a lightweight OIDC provider) #10998
- [ ] 3. provide details on the performances (disk/network/RAM/CPU/boot time) and get PM signoff 
- [ ] 4. drop single user support from deployment scripts/tools:
  - [ ] che CLI
  - [ ] ocp.sh
  - [ ] minishift addon
  - [ ] helm chart
- [ ] 5. Drop support for single user Che in build / CI / QE (#10999)
- [ ] 6. Remove single user Che related modules
- [ ] 7. Remove single user references in documentation

**Comment by dmytro-ndp** [comment]
@l0rd: please, take into consideration E2E selenium tests as well https://github.com/eclipse/che/issues/10999
