### ISSUE TITLE
QE-2018-10-02 (Sprint: 155)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#10992]
### Sprint goals
- Improvement and stabilization of existing E2E selenium tests of Eclipse Che, creation of new tests and test plans.
- Review E2E tests to remove duplication and outdated verification.
- Start analyzing of coverage of all Eclipse Che functional units by E2E tests (apply decomposition approach and check coverage).
- Investigate an ability to create optional E2E tests of work in Eclipse Che with private repo and organization.

### Issues tied to objectives
- [ ] Log reasonable error messages in case of confusing selenium launcher parameters #10248 3sp
- [ ] Investigate an ability to create optional selenium tests of work with private repo and organization #8645 3sp
- [x] Cover the "PHP" language server functionality by selenium test https://github.com/eclipse/che/issues/11180 3 sp
- [x] Cover the "Python" language server functionality by selenium test #11218 3 sp
- [x] Cover the "JSON" language server functionality by selenium test #11219 2 sp
- [x] Cover the "CLang" language server functionality by selenium test #11198 3 sp
- [x] Cover the "TypeScript" language server functionality by selenium test #11220 3 sp
- [x] Cover the "Yaml" language server functionality by selenium test #11221 2 sp
- [x] Cover the "ApacheCamel" language server functionality by selenium test #11222 2 sp
- [x] Cover the "GoLang" language server functionality by selenium test #11209 3 sp
- [x] Add checking find definition, comment hovering and go to symbol features for C# language server #11202 5 sp
- [x] Create coverage map for ImportWizard widget by decomposition approach #11141 3 sp
- [x] Add a selenium test case to create the Pull Request from non-default branch #10000 3 sp
- [x] Unexpected fail of FindUsagesBaseOperationTest selenium test https://github.com/eclipse/che/issues/11171 2 sp
- [ ] Housekeeping of legacy Eclipse Che E2E selenium tests https://github.com/eclipse/che/issues/11189 3 sp

### Unplanned 
- [x] Read test workspace logs despite its status in case of start workspace failure #11200 1sp
- [x] Create selenium page object for working with assistant features #11201 1sp
- [x] Browser window didn't close automatically in factory related E2E selenium tests #11204 1sp
- [x] Unexpected fail of "ImportAndValidateEclipseCheProjectTest" selenium test #11121 1sp
- [x] Unexpected fail of "CheckErrorsWarningsTabTest" selenium test #11086 1sp
- [x] Correct some selenium tests from package 'git' for increase their reliability #11105 2sp
- [x] Add the 'try/catch' to the 'ImportAndValidateEclipseCheProjectTest' related to known issue #11179 1sp
- [x]  Add the 'try/catch' to the tests in the 'refactor.parameters' related to known issue #11187 1sp
- [ ] Investigate the failing selenium test 'GitPullTest' on CI job #11223 2sp
- [x] Investigate the failing selenium test 'ImportWizardFormTest' on CI job #11227 2sp
- [x] Remake the 'waitAndClick()' method from the 'SeleniumWebDriverHelper' according to the 'StaleElementReferenceException' #11241 2sp
- [x] Unexpected fail of selenium tests from dashboard package #11256 1sp
- [x] Correct the 'doRenamingByLanguageServerField()' method in the 'CodenvyEditor' #11250 1sp
- [x] Unexpected fail of "CheckWorkingWithTabsByUsingContextMenuTest" selenium test #11276 1sp
- [x] Adapt OpenShift-related E2E test workspace templates to use JDT LS #11304 1sp
- [x] Rework "FileStructure" selenium page object by "SeleniumWebDriverHelper" class #11346 2sp
- [x] Update usecases in "PhpAssistantFeaturesTest" for catching known bugs #10117 #10698 #11281 1sp
- [x] Unexpected fail of "CheckRestoringSplitEditorTest" selenium test #11302 1sp
- [x] Unexpected fail of "InheritClassTest" selenium test #11319 2sp
- [x] Selenium: Create the method to set the 'Contribute' property in 'true' when the test start #11206 2sp
- [x] Create Selenium test covered Theia stack #11327 2sp
- [x] Investigate the failing selenium test 'GitChangeMarkersTest' on CI job #11317 1sp
- [ ] Investigate the failing selenium test 'RenamePackageSpringTest' on CI job #11373 1sp
- [x] Unexpected fail of "UploadIntoProjectTest" selenium test #11397 1sp
- [ ] Create Selenium test covered "start Theia in hosted mode and test the plugin" #11400 3sp
- [x] [Che-6] Create selenium test for checking add maven project and module #6905 3sp
- [x] Unexpected fail of "TheiaBuildPluginTest" selenium test #11416 1sp

### PR under review
- [ ] https://github.com/eclipse/che/pull/11301
- [x] https://github.com/eclipse/che/pull/11367
- [x] https://github.com/eclipse/che/pull/11344
- [x] https://github.com/eclipse/che/pull/11410
- [x] https://github.com/eclipse/che/pull/11413

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
| Total | 75  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 40 | 31 |
