### ISSUE TITLE
IDE2-2018-10-02 (Sprint: 155)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#11067]
### Sprint Goals:
1. Make execs work on Openshift
2. EclipseCon Europe Workshop
3. WebView API
4. Languages Plugin API
5. Tree View API
6. Documentation

##  1. Make execs work on Openshift
- [x] Add openshift implemetation for terminal server side in the che-theia-terminal-plugin and che-theia-task-plugin https://github.com/eclipse/che/issues/10314 15sp
- [x] Update to the newer Theia core https://github.com/eclipse/che-theia-terminal-extension/issues/3 15sp
- [ ] Check compatibility che-theia-terminal-extension to the "plugin-api" and fix if something is not working https://github.com/eclipse/che/issues/11279
- [x] Implement terminal sidecar compatible with Kubernetes (and Openshift) https://github.com/eclipse/che/issues/10357
- [x] Implement exec sidecar compatible with Kubernetes (and Openshift) https://github.com/eclipse/che/issues/10358
- [x] Create side cars for che-theia-terminal-extension and che-theia-task-extension https://github.com/eclipse/che/issues/11235

##  2. Tree View API
- [ ] [plug-in] Add Tree View and Tree Data Provider APIs https://github.com/theia-ide/theia/issues/2782 65sp

## 3. Languages Plugin API
- [x] [plug-in][languages] Register hover provider https://github.com/theia-ide/theia/issues/2601 to finish
- [x] [plug-in][languages] Add API for registering a formatting provider for a document https://github.com/theia-ide/theia/issues/2797 25sp
- [x] [plug-in][languages] Add API for registering a formatting provider for a document range https://github.com/theia-ide/theia/issues/2798 25sp
- [x] [plug-in][languages] Add API for registering a formatting provider that works on type https://github.com/theia-ide/theia/issues/2799 25sp
- [x] [plug-in][languages] Add ability for registering signature help provider https://github.com/theia-ide/theia/issues/2792 [to finish]
- [x] [plug-in][languages] Provide support for registering definition providers https://github.com/theia-ide/theia/issues/2353 30sp
- [ ] [plug-in] Add API to apply workspace edit https://github.com/theia-ide/theia/issues/2784 40sp

## 4. WebView API 
- [ ] Implement Webview API https://github.com/theia-ide/theia/issues/2708 [to finish]

## 5. Documentation clean-up: review all our README files, 
How to setup developer environment for extensions - TODO
do FAQ
- [ ] how to add plugin API 20sp
- [x] the list of the APIs that we have
- [ ] Improve che-machine-exec docs https://github.com/eclipse/che-machine-exec/issues/2
- [x] Theia user documentation : APIs 

## 6. EclipseCon Europe Workshop
- [x] Add Dashboard widget to select the plugins https://github.com/eclipse/che/issues/10780 10sp

## Other  issues:
- [ ] Factory in Theia doesn't clone project on OSIO https://github.com/eclipse/che/issues/11144 40sp
- [x] Migrate Che Dashboard from bower to yarn https://github.com/eclipse/che/issues/10881 15sp
- [ ] Terminal font excessive spacing in 6.10.0 https://github.com/eclipse/che/issues/10945 10-25sp
- [ ] Documentation with features, user stories and use cases of Che + theia self hosting https://github.com/eclipse/che/issues/11004 [to check]
- [x] Che + theia: Theia IDE do not send any activity events to wsmaster https://github.com/eclipse/che/issues/11267

**Unplanned:**
- [x] Create side cars for che-theia-terminal-extension and che-theia-task-extension https://github.com/eclipse/che/issues/11235

**Total planned = [todo]sp**

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova | 5 |
| Mykola Morhun | 13 |
| Oleksandr Andriienko | 13 | 
| Oleksii Kurynniy | 13 |
| Oleksii Orel | 13 |
| Sun Tan | 13 |
| Vitaliy Guliy | 13 |
| Yevhen Vydolob | 3 |
| **Total Budget** | **56** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1szIS-IYwlniYP2nRB0cZ5CeW3Uizl_9694rS8Nu3koU/edit)
