### ISSUE TITLE
IDE-2018-10-02 (Sprint: 155)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#11083]
#### Theia goals

- [x] [plug-in] Menu Plugin API theia-ide/theia#2785
- [ ] [plug-in] API for register text document content provider theia-ide/theia#2786
- [ ] [plug-in] Keyboard Shortcuts Plugin API  theia-ide/theia#2783
- [ ] [plug-in] API endpoint for window.withProgress theia-ide/theia#2802 
- [ ] [plug-in] API endpoint for window.showTextDocument theia-ide/theia#2801

#### Che goals
- [x] Allow Git Committer details to be mapped from Keycloak user details #10909
- [ ] File in /projects treated as a project #10586
- [ ] [Language server] Content of language server hover feature is duplicated #10117
- [ ] Unexpected exceptions in dev console after enabling/disabling maven modules #9916

#### Artem 
- [x] [plug-in] Menu Plugin API theia-ide/theia#2785
- [x] [plug-in][languages] Register a document link provider  theia-ide/theia#2964 

#### Dmytro 
- [ ] [plug-in] API for register a filesystem provider theia-ide/theia#2861

#### Roman 
- [ ] [plug-in] Keyboard Shortcuts Plugin API  theia-ide/theia#2783
- [x] Unexpected exceptions in dev console after enabling/disabling maven modules #9916

####  Vitalii
- [ ] [plug-in] API for register text document content provider theia-ide/theia#2786
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574 (will work under some specification for this issue and adding sub issues) 5d

#### Vlad
- [ ] Unexpected behavior the 'Project Configuration' when configure the Eclipse Che project #11145
- [ ] Add an ability to re-run a task in Theia from a terminal widget #10381
- [x] File in /projects treated as a project #10586
- [ ] [Language server] Content of language server hover feature is duplicated #10117

#### Igor
- [x] Allow Git Committer details to be mapped from Keycloak user details #10909
- [ ] [plug-in] API endpoint for window.withProgress theia-ide/theia#2802 
- [ ] [plug-in] API endpoint for window.showTextDocument theia-ide/theia#2801
- [ ] Rework SSH extension to SSH plugin #9720

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |  
| Dmytro  | 14 |   
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
