### ISSUE TITLE
Feedbacks on using Theia IDE in Che on daily basis

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#11082]
### Description
List of issue such as bugs or UX improvements or missing features to improve Theia IDE on Che to develop Theia and Che plugins or extension.

#### Small issues
- [ ] Git: hard to see where we are ... current branch ? current repo ? how to switch ? etc ... 
- [ ] Git ... annotate ?
- [ ] Dashboard: sometimes, after changing a workspace definition and reloading it, workspace loading immediatly fails showing the error `undefined` and asking to hit F5 to refresh. https://github.com/eclipse/che/issues/11773
- [x] Regression Factory: branch checkout is not working anymore with the error `can not find reference`;
- [x] Regression Task/Commands (with Theia 0.3.14): Running a command is not showing any more the output of the commands https://github.com/eclipse/che/issues/11157 PR https://github.com/eclipse/che-theia-task-plugin/pull/8
- [ ] Double click on a editor tab should maximize it (minimizing other views)
- [ ] How to stop a Che command (theia task) ?
- [ ] Hosted mode: should be able to start hosted instance from a factory action
- [ ] Hosted mode: restart should just start if theia-dev is not started. ATM, it pops up an message saying the theia-dev instance is not started ...
- [ ] Hosted mode: should define its own workspace root folder: at the moment it is suggesting to open a workspace.
- [x] Yeoman plugin generator: by default create a folder where to generate the files https://github.com/eclipse/theia-generator-plugin/pull/10
- [x] Yeoman plugin generator: name provided for 'module name' should be use as it is in module name. ATM it is adding '-plugin' at the end
- [x] Yeoman plugin generator: if no license is specify, it generates "license": "[object Object]" where it shouldn't print any line about license. https://github.com/eclipse/theia-generator-plugin/pull/10
- [ ] Che Theia commands (tasks) should support `${current.project.eldest.parent.path}` substitution https://github.com/eclipse/che/issues/11064
- [ ] Che Theia commands (tasks)  `${current.project.path}` is only giving the project folder name, not the complete path `/projects/projectname`
- [ ] Theia should have a view showing all the errors that has been displayed in the error popup dialog (problem when an error occurs and the popup has disappeared.
- [ ] Factory should have a kind of loader for progress rather then showing notification. factory loader could be on status bar and showing all the ongoing tasks when clicking on it.
- [ ] Rethink where to display preview urls when running a command: the legacy Che IDE were showing it next to the output terminal when running a command which makes sense
- [ ] Machine view:
   - [ ] polish icons
   - [ ] tree items should have name containing urls, not the opposite or a same item with `name: url`
   - [ ] urls should be clickable and user should be able to copy the url
   - [ ] why not showing it in the status bar ?
- [x] terminal extension: is it supposed to connect to the terminal of another container ? maybe fixed with https://github.com/eclipse/che-theia-terminal-extension/pull/9 but che terminal extension cannot run with theia terminal extension
- [ ] <div id="clone">if projects are defined in the che workspace config, but do not exist in the workspace, theia should clone the projects</div>
- [ ] By default, open Che specific views and file explorer
- [ ] How can I set up my custom preferences (.gitconfig, etc ...) to be used from the terminal

#### Big issues, feature requests
- [ ] Build che-theia image from che-theia !!!! 
- [ ] Would be nice to have named factory id. For instance: `sunix/che-theia-in-che-theia`
- [ ] Run any factory in any of user's Che instances (che.openshift.io, minishift or other). chrome ext ? https://github.com/eclipse/che/issues/11584
- [ ] Code completion in package.json#contribute
- [ ] Pull Request panel
- [ ] Inject git preferences from che user profile to env variable of terminal
- [ ] Pair programming / co-editing
