### ISSUE TITLE
Languages Sprint 155

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11111]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 8d  | 5d | 6d
@tolusha | 15d | 9d | 8d
@svor | 15d | 9d | 10d
@vrubezhny | 7d | 4d | 4d

# Candidate issues 
- [x] It is not possible to attach to nodejs debugger on non-default port https://github.com/theia-ide/theia/issues/2829 (3d) (@tolusha)
- [x] Move step actions into threads panel toolbar https://github.com/theia-ide/theia/issues/2847 (2d) (@tolusha)
- [x] Make Debug Session Views Act like Panels https://github.com/theia-ide/theia/issues/2846 (1d) (@tolusha)
- [x] Make a release of che-ls-jdt https://github.com/eclipse/che/issues/11182 (1d) (@tsmaeder)
- [x] Theia: Investigate Reuse jdt.ls workspace #10325 (3d) (@svor)
- [ ] Theia Consume che-ls-jdt as jdt.ls extension https://github.com/theia-ide/theia/issues/2849 (5d)
- [x] Implementers is Broken for Class Files #10337 (2d) (@vrubezhny)
- [ ] Allow consuming LS functionality running as a sidecar in Theia base ide #9441 (5d) (@tsmaeder)
- [x] Victor: set up Theia development environment (2d) (@vrubezhny )
- [x] Investigate Batching of Progress Notifications from jdt.ls https://github.com/eclipse/che/issues/11164 (2d timebox) (@svor)
- [x] Investigatge Batching for didChangeWatchedFiles https://github.com/eclipse/che/issues/11163 (2d timebox) ) (@tolusha)

# Open PR's 
- [ ] https://github.com/eclipse/che-theia-java-plugin/pull/2
- [x] https://github.com/eclipse/che/pull/11133 (1d)
- [x] https://github.com/eclipse/che/pull/11094 (1d)
- [x] https://github.com/theia-ide/theia/pull/2593 (3d)
- [ ] https://github.com/theia-ide/theia/pull/2461
- [ ] https://github.com/theia-ide/theia/pull/2953
- [x] https://github.com/theia-ide/theia/pull/2996
- [x] https://github.com/eclipse/che/pull/11395

Previous sprint: #10870

**Comment by svor** [comment]
15d
