### ISSUE TITLE
Platform-2018-10-02 (Sprint: 155)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11131]
### Features related to ws.next

- [x] Create README.md to eclipse/che-plugin-registry | https://github.com/eclipse/che/issues/10834 | 5sp
- [ ] Improve naming for wsnext tooling containers | https://github.com/eclipse/che/issues/11031 | 5sp
- [x] Provide an access token for `terminal` and `exec` sidecars | https://github.com/eclipse/che/issues/10991 | 8sp
- [ ] Walking skeleton pulling strategies | https://github.com/eclipse/che/issues/11017 | 5sp
- [ ] Workspace.Next: Propagate logs from broker pod to ws-master | https://github.com/eclipse/che/issues/11069 | 8sp
- [x] Configure broker timeout in Che | https://github.com/eclipse/che/issues/11120 | 5sp
- [x] Plugin Broker does not respect pod status | https://github.com/eclipse/che/issues/11070 | 5sp

### Finalize issues started in the previous sprint.

- [x] Db support documentation | https://github.com/eclipse/che/issues/10950 | 13 sp
- [ ] Migrate to mockito/mockito-testng | https://github.com/eclipse/che/issues/10617 | 3 sp
- [x] Unexpected error in che-server pod logs during selenium test session on OpenShift infra | https://github.com/eclipse/che/issues/10903 | 5 sp
- [x] Limit scope of APIs that can be called with machine token | https://github.com/eclipse/che/issues/10710 | 13 sp

### Unplanned
- [x]  Prevent caching of index file by browser https://github.com/eclipse/che-plugin-registry/issues/30
- [x] Workspace.Next: Errors of broker pod are not propagated to a client https://github.com/eclipse/che/issues/11068
- [x] Setup default plugin registry url https://github.com/eclipse/che/issues/11352
- [x]  An Editor swapping example ( with Jupyter for example demo and blog post should be enough) https://github.com/eclipse/che-plugin-registry/pull/39
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 10d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 12d | 
| Sergii Leshchenko | 15 d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 75  | 54 |
