### ISSUE TITLE
RFE: Expose usage metrics via Che Server API

### ISSUE THREAD

**Issue by aditya-konarde** [eclipse-che/che#11242]
### Description
As an engineer working on a maintaining a hosted Eclipse Che Server, I would like to have access to metrics on the the number of provisioned Che accounts on the Server. Currently, this can be obtained with queries to the backing database. The request here is to expose these metrics via a metrics endpoint, so that they can be consumed directly by a monitoring system. 

The metrics I am looking at are: 
- [x]  Number of provisioned Che accounts .  [Metric] Number of users | https://github.com/eclipse/che/issues/12093
- [x] Number of Che Workspaces Create REST method to get all workspaces with filter | https://github.com/eclipse/che/issues/12091
- [x] Number of Che workspace per user OR the average number of workspaces per user https://github.com/eclipse/che/issues/12091

The developers might be able to add in more metrics which are needed for development/troubleshooting. Exposing these will definitely help with a faster feedback loop for the developers, and help us look at trends in the usage for better capacity planning.

CC @ibuziuk 

### Reproduction Steps
Not applicable

**OS and version:**    
Not applicable

**Diagnostics:** 
Not applicable

**Comment by l0rd** [comment]
@aditya-konarde I am afraid we don't have such a concept of a "super user" or "admin" in Che but @skabashnyuk may provide more details.

**Comment by skabashnyuk** [comment]
@aditya-konarde @l0rd we do have a concept of "super user" or "admin". We call it user with "manageSystem" permission.
> Number of provisioned Che accounts

Small remark. If Che is connected to Keycloak or other OIDC provider it will mean a number of users who at least once used Che.
>Number of Che Workspaces

ok

>Number of Che workspace per user OR the average number of workspaces per user

We might need pagination here.

I'll try to make a prototype of json so we can make sure we are talking about the same thing.

**Comment by mshaposhnik** [comment]
So it might be like:
GET `/api/metrics?metric_type=total_accounts`
GET `/api/metrics?metric_type=total_workspaces`
GET `/api/metrics?metric_type=average_workspaces`
with the JSON output  in form:
```
{
 "total_workspaces": "136",
 "running_workspaces: "62",
 "timestamp" : "2018-10-23 13:34:55"
}
```

**Comment by aditya-konarde** [comment]
@fche fyi^

**Comment by aditya-konarde** [comment]
Best if we use a prometheus-style format: https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-example

**Comment by fche** [comment]
suggest a prometheus-exporter plain-text format instead (or in addition) please

**Comment by fche** [comment]
As Aditya said: Best if we use a prometheus-style format:
https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposit
ion_formats.md#text-format-example

**Comment by fche** [comment]
(sorry for the repeat comments here - github is dropping them for some reason?!?!?!!)

**Comment by ibuziuk** [comment]
```
Number of provisioned Che accounts
Number of Che Workspaces
Number of Che workspace per user OR the average number of workspaces per user
```
Those metrics are really interesting and nice to have, but they will not really help from maintaining perspective. IMO, the most important metric that we could currently get is list of workspaces that are running more than X minutes (with info about user / namespace). I believe it should be the first usage metric exposed via Che Server API

**Comment by skabashnyuk** [comment]
@ibuziuk @aditya-konarde  FYI

- Create REST method to get all workspaces with filter | https://github.com/eclipse/che/issues/12091
- [Metric] Number of workspaces by state | https://github.com/eclipse/che/issues/12092
- [Metric] Number of users | https://github.com/eclipse/che/issues/12093

**Comment by ibuziuk** [comment]
@skabashnyuk based on our SLA discussion I have created the following issues:
- [Metric] Number of failed workspace startup https://github.com/eclipse/che/issues/12242
- [Metric] API error rate (number of 500 responses from che server) https://github.com/eclipse/che/issues/12244

Please, consider those issues as a priority from the overall list of metrics.

**Comment by skabashnyuk** [comment]
implemented
