### ISSUE TITLE
Setup QA process for CHE with Theia onboard.

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#11295]
### This is an epic issue about setting QA process for CHE with Theia functionality.

- [ ] Setup infrastructure on CI for nightly running Selenium test suit on CHE with Theia.
- [x] Define use cases we need to cover with automatic tests for CHE with Theia. #12170
- [ ] Create a test plan for covering CHE with Theia functionality.
- [ ] Create a test suit for testing CHE with Theia.

**Comment by garagatyi** [comment]
> Define use cases we need to cover with automatic tests for CHE with Theia. [specification TBD Stevan?]

@vkuznyetsov the first case that I can suggest (and the most important in any case) is that Theia gets opened from UD when WS.NEXT workspace with Theia editor is started. The same should be true for a factory. Here are 2 cases which are pretty clear to me. If they are not clear to QA team they can comment here to get more info from me. Since this stuff is important, I believe, there is no need to wait for @slemeur input to start work on that.

> Setup infrastructure on CI for nightly running Selenium test suit on CHE with Theia. 

This is a pretty simple task and QA team can grab me or @eivantsov to get more info. In particular, when Che deployment is called the addition of a single parameter `--deploy-che-plugin-registry`. After that, you can use WS.NEXT workspaces on that Che installation.
I would consider adding this property by default to the Che tests and add simple tests I've described above to the default set of tests. This would eliminate a lot of complexity and would allow creating those test in just a couple of days.

**Comment by slemeur** [comment]
@vkuznyetsov : thanks for creating the epic. 

+1 with @garagatyi : you should work with the engineers to get the understanding of what are the most important pieces which can be tested now (and automated). And then, you also have all the use cases from the previous IDE that you should be covering too.

**Comment by vkuznyetsov** [comment]
Not actual
