### ISSUE TITLE
IDE2-2018-10-23 (Sprint: 156)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#11345]
### Sprint Goals:
1. Make execs work on Openshift
2. EclipseCon Europe Workshop
3. Extend Plugin API with Che API
4. Finalize APIs: TreeView, WebView, Languages 

##  1. Make execs work on Openshift
- [x] Check compatibility che-theia-terminal-extension to the "plugin-api" and fix if something is not working https://github.com/eclipse/che/issues/11279 [TODO add documentation] 20sp
- [x] Improve che-machine-exec docs. https://github.com/eclipse/che-machine-exec/issues/2
- [x] che-machine-exec filter doesn't work(Regresion) on the Openshift/Kubernetes https://github.com/eclipse/che/issues/11496
- [x] We should have nice terminal label with machine info https://github.com/eclipse/che-theia-terminal-extension/issues/8

## 2. EclipseCon Europe Workshop
- [ ] Replace git clone with a command that generates a hello world plugin scaffold (task that executes the yarn and command that calls that task): Add necessary source to plugin generator, add it to plugin registry, adding generator with UI plugin to default theia [TODO add issue and description] 25sp
- [ ] Convert Che-theia factory extension to plugin https://github.com/eclipse/che/issues/11249 [clone to test, execution of task - API for this, open file? ] 40sp
- [ ] Che Theia - CORS issue when Theia IDE client side browser trying to reach Che master https://github.com/eclipse/che/issues/11240 [to check after 11249]
- [ ] Factory in Theia doesn't clone project on OSIO https://github.com/eclipse/che/issues/11144 [to check after 11249]
- [x] ISSUE: Implement a sample code formatter plugin [TODO describe the steps how to use on workshop] 10sp
- [x] ISSUE: Think of ways to debug the plugin (describe the steps) 10sp
- [x] Ask a user to remove installer from a workspace when they enables WS.NEXT editor or plugin https://github.com/eclipse/che/issues/11401 15sp
- [x] Sample plugin: TODO plugin -> highlight the TODOs in editor 10sp
- [x] Che Theia: che-theia packaging and default theia packaging should be as close as possible https://github.com/eclipse/che/issues/11390 15sp
- [x] Add support for preferences schema from contribution point of a manifest file https://github.com/eclipse/che/issues/9990

## 3 Extend Plugin API with Che API
- [ ] Add new "che" namespace to Plugin API to have dedicated APIs https://github.com/eclipse/che/issues/11306 (POC) (50sp)

##  4. Finalize APIs: TreeView, WebView, Languages 
- [ ] [Languages] define and add the needed APIs [TODO try on real LS (XML as example)]
- [ ] [plug-in][languages] Add API for registering a code actions provider https://github.com/theia-ide/theia/issues/3162
- [x] [plug-in] Add Tree View and Tree Data Provider APIs https://github.com/theia-ide/theia/issues/2782 25sp

## Other  issues:
- [x] Terminal font excessive spacing in 6.10.0 https://github.com/eclipse/che/issues/10945 + CQ  15sp
- [ ] Analyze how we can convert che-theia extensions to plugins https://github.com/eclipse/che/issues/11050
- [ ] [TODO] stack - Java + Theia IDE + sample (petclinic) + define commands 15sp
- [x] Add ability to debug backend plugin in hosted mode https://github.com/theia-ide/theia/issues/3062 25sp

## Selenium test failures:
- [x] Empty "Edit the machine" form after changing the workspace machine name https://github.com/eclipse/che/issues/10732 10sp
- [x] Incorrect workspace name is not covered by checking in the "Name" field https://github.com/eclipse/che/issues/10659 5sp

**Unplanned:**
- [x] Cyclic dependencies between the modules https://github.com/theia-ide/theia/issues/2892
- [x] In the terminal widget doesn't work Ctrl + C (to stop process) and some other hotkeys. https://github.com/eclipse/che-theia-terminal-extension/issues/18
- [x] Investigate how we can inject default terminal when che-theia-terminal-extension is hidden.https://github.com/eclipse/che-theia-terminal-extension/issues/19
- [ ] Implement Webview API https://github.com/theia-ide/theia/issues/2708
- [ ] che-machine-exec(Kubernetes infra) after few hours get connection refused https://github.com/eclipse/che-machine-exec/issues/9

**Total planned = [todo]sp**

### Pending PRs
- [x] CHE-9595: Apply terminal api examples https://github.com/theia-demo-plugins/theia-backend-plugin/pull/5
- [x] Override default Theia terminal extension contributions. https://github.com/eclipse/che-theia-terminal-extension/pull/14
- [x] [plug-in] Languages API - Register formatting provider for a document range https://github.com/theia-ide/theia/pull/2957
- [x] [WIP] CHE-10883 migrate from bower to yarn https://github.com/eclipse/che/pull/11301

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

**Comment by benoitf** [comment]
is
`Replace git clone with a command that generates a hello world plugin scaffold (task that executes the yarn and command that calls that task)`
to integrate https://github.com/eclipse/theia-yeoman-plugin ?

**Comment by ashumilova** [comment]
@benoitf yes, we wanted to include theia-yoman-plugin to plugin registry and create workspace from stack that includes it.
