### ISSUE TITLE
IDE-2018-10-23 (Sprint: 156)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#11379]
#### Theia goals
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574

#### Che goals

- [ ] [Language server] Content of language server hover feature is duplicated #10117 
- [x] Import project from CHE config feature looks outdated #10864
- [x] [Language server] Signature Help feature doesn't work with "(" character #10699
- [x] [Language server] Find References feature displays incorrect line positions #10698

#### Artem 
- [x] Can not delete Command #10609
- [x] Welcome checkbox in the Preferences widget looks like is not actual #11166
- [x] Process names in Processes list doubled after restarting workspace #10927
- [x] Unable to import project from Git with branch that contains a slash ("/") #11012
- [x] A new line is added to a file if confirm line selection in the "Go to specified line number" window by pressing ENTER button #10982
- [x] Editor behaves improperly when in debug mode #11398

#### Dmytro 
- [x] [Language server] Apache Camel language server features do not work with a file correctly after renaming it #10962
- [x] [Language server] TypeScript language server features do not work with a file correctly after renaming it #10948
- [x] [Language server] Yaml language server features do not work with a file correctly after renaming it #10937
- [x] [Language server] Golang language server features do not work with a file correctly after renaming it #10936
- [x] [Language server] Python language server features do not work correctly with a file after renaming it #10935
- [x] [Language server] PHP language server features do not work correctly with a php file after renaming it #10932
- [x] No didChangeWatchedFiles notification for existing files in the LSP? #10794

#### Roman 
- [x] Add permanently displayed message when IDE lost connection to ws-agent #11406
- [ ] Unexpected behavior the 'Project Configuration' when configure the Eclipse Che project #11145
- [ ] Unexpected appearing the error information dialog when resolve the Eclipse Che project #10515

#### Vlad
PTO
#### Igor
PTO

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |7 |  
| Dmytro  | 14 |   
| Roman  |9 | 
| Vitalii  |14|    
| Igor |0 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
