### ISSUE TITLE
QE-2018-10-23 (Sprint: 156)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#11381]
### Sprint goals
- Improvement and stabilization of existing E2E selenium tests of Eclipse Che, creation of new tests and test plans.

### Issues tied to objectives
- [ ] Create Selenium test covered "start Theia in hosted mode and test the plugin" #11400 2sp
- [ ] Get rid of legacy code in the "Consoles" selenium page object #11217 3sp
- [x] Cover creation stacks from recipe by selenium test #11451 3sp
- [x] Unexpected fail of selenium tests from 'refactor' package #10989 1sp
- [x] Adapt Eclipse Che selenium tests from dashboard package to execute on OSIO #10584 2sp

### Unplanned 
- [x] Unexpected fail of "MacrosCommandsEditorTest" selenium test #11497 1sp
- [x] Store logs of test workspaces which are created during the E2E test scenario execution #11506 3sp
- [x] Unexpected fail of "TheiaBuildPluginTest" selenium test #11416 1sp
- [x] Adapt the "TheiaBuildPluginTest" selenium test to changes in the top menu #11545 1sp
- [x] Unexpected fail of "TheiaBuildPluginTest" selenium test #11416 1sp
- [x] Adapt the "TheiaBuildPluginTest" selenium test to changes in the top menu #11545 1sp
- [x] Investigate the failing selenium test 'ImportWizardFormTest' on CI job #11558 1sp
- [x] Unexpected fail of "AutocompleteFeaturesInEditorTest" selenium test #11564 1sp
- [x] Adapt the "TheiaBuildPluginTest" selenium test to the new terminal tab titles #11604 1sp
- [x] Investigate the failing selenium test 'GitPullTest' on CI job #11223 1sp
- [x] Investigate the failing selenium test 'PushingChangesTest' on CI job #11553 1sp
- [x] [ JDT-LS ] Rework selenium tests in the "preferences", "autocomplete", "projectexplorer", "dependencies", "editor" packages for adopting to branch changes #11609 3sp
- [x] Add catching of the known bug (#11624) to the "TheiaBuildPluginTest" selenium test #11625 1sp
- [x] Unexpected fail of ResolveDependencyAfterRecreateProjectTest selenium test #11591 1sp
- [x] Add the 'try-catch' to the 'GitPullTest' selenium test #11649 1sp
- [ ] Adapt tests after merging JDT.LS branch in master #11659 3sp
- [x] Adapt selenium tests after merging JDT.LS branch in master #11663 2sp
- [x] Delete the try-catch from the 'checkFindReferencesFeature()' in the 'GolangFileEditingTest' #11666 1sp
- [x] Adapt selenium tests after merging JDT.LS branch in master #11668 3sp

### PR under review
- [x] Introduce java language server #10863
- [x] Fix memory request jwt #11556
- [x] CHE-10945: Fix terminal font for some systems. #11576
- [x] Fix importing a project from Git VCS with a branch that contains slash symbol #11579
- [x] Improve and clean up factory validation exception messages #11585

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 14 |
| Maxim Musienko | 14 |
| Dmytro Nochevnov | 14 |
| Igor Ohrimenko | 14 |
| Sergey Skorik | 14 |
| Total | 70  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 11 | 6 |
