### ISSUE TITLE
Platform-2018-10-23 (Sprint: 156)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11380]
### Features related to ws.next
- [x] Improve naming for wsnext tooling containers | https://github.com/eclipse/che/issues/11031 | 8
- [x] Walking skeleton pulling strategies | https://github.com/eclipse/che/issues/11017 | 5
- [x] Workspace.Next: Propagate logs from broker pod to ws-master | https://github.com/eclipse/che/issues/11069 | 3

### New features
 -  [ ] RFE: Expose usage metrics via Che Server API  https://github.com/eclipse/che/issues/11242 13

### Technical debts and bugs
- [x] OpenShift/K8S: PVC helper errors when workspaces share one PV | https://github.com/eclipse/che/issues/9691 | 1
- [ ] Go-agent tests sometimes fail on CI | https://github.com/eclipse/che/issues/10914 | 5
- [ ] Add debug logging on each step of K8s/OS runtime start | https://github.com/eclipse/che/issues/10408 | 8
- [ ] Respect unrecoverable event that occurs when Pod spec is considered invalid by a k8s cluster | https://github.com/eclipse/che/issues/11411 | 5

### Finalize issues started in the previous sprint.
- [x] Migrate to mockito/mockito-testng | https://github.com/eclipse/che/issues/10617 | 8 sp

### Unplanned
 - [ ] Allow to collect JVM statistic from JMX on Che-master on OS/K8S https://github.com/eclipse/che/issues/11384
 - [x] Investigate if we need to limit amount of threads which are used for processing of JSON-RPC messages https://github.com/eclipse/che/issues/5443
- [x] Create Che Plugin with GWT IDE and Workspace Agent https://github.com/eclipse/che/issues/11453
- [x] Add an ability to disable discover-ability of a plugin endpoint https://github.com/eclipse/che/issues/11606
- [x] Clean up workspace hanging in the starting state when Che master forcefully restarts during the workspace start https://github.com/eclipse/che/issues/11364
- [x] Move recovering of Runtimes from @PostConstruct phase https://github.com/eclipse/che/issues/11589
- [x] Define plugin testing process https://github.com/eclipse/che/issues/11555
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 13d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 56  | 25 |
