### ISSUE TITLE
Languages Sprint 156 (K-1)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11438]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 7d  |  4d | 4d
@tolusha | 8d | 5d | 5d
@svor | 8d | 5d | 5d
@vrubezhny | 13d | 8d | 10d

@tsmaeder @tolusha have to prep eclipse-con talk

# Candidate issues 
- [x] Make a release of che-ls-jdt https://github.com/eclipse/che/issues/11182 (1d) (@tsmaeder)
- [ ] Provide Plugin API for contributing Debug Adapters https://github.com/theia-ide/theia/issues/2990 (@tolusha get started on this: 2d)
- [ ] Theia Consume che-ls-jdt as jdt.ls extension https://github.com/theia-ide/theia/issues/2849 (3d) @svor 
- [ ] Use the `DocumentSymbol.detail` not just only the `DocumentSymbol.name` https://github.com/theia-ide/theia/issues/2894 (5d) @vrubezhny )
- [x] Prepare EclipseconTalk @tolusha (3d)
- [x] Prepare EclipsecontTalk @tsmaeder (3d)
- [ ] Register a document symbol provider see: https://github.com/theia-ide/theia/issues/2341 (5d) @vrubezhny (stretch)
- [ ] Register a workspace symbol provider see: https://github.com/theia-ide/theia/issues/2341  (5d) (@JPinkney)
- [ ] Plan out K-Train (@tsmaeder) 2d

Unplanned:
- [ ] Contribute Java Debug Adapter https://github.com/theia-ide/theia/issues/3059
- [ ] Add MS Debug Adapter as a jdt.ls Extension https://github.com/theia-ide/theia/issues/3058

# Open PR's 
- [x] https://github.com/theia-ide/theia/pull/2970 2d
- [ ] https://github.com/theia-ide/theia/pull/2461
- [x] https://github.com/theia-ide/theia/pull/2953 (peding cq https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17675)
- [x] https://github.com/theia-ide/theia/pull/2996

Previous sprint: #11111

**Comment by benoitf** [comment]
Hello, how is overlapping https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug  / https://github.com/Microsoft/vscode-java-debug with 

- Contribute Java Debug Adapter theia-ide/theia#3059
- Add MS Debug Adapter as a jdt.ls Extension theia-ide/theia#3058
