### ISSUE TITLE
Theia Terminal plugin: add missing API and implement the Plugin

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11442]
In Che 7 model, terminal connection logic may differ from upstream theia one:
- Theia is connecting directly to a host
- Che is connecting through a remote container exec

The goal of this issue is to be able to provide the logic through an extension point in Che. Che extension point would override the one defined in Theia.

List of missing Theia API to implement:
- [ ] Upstream changes: #12609
  - split terminal widget logic:
    - terminal widget part (without any connection logic).
    - terminal connection logic.

This split means: define common interface and default implementation for connection part to the separated Theia package: terminal. Xterm.js specific implementation of the terminal widget move to the separated package xterm.js-terminal
- [ ] terminal widget api with ability:
   - Create new terminal widget
   - Ability apply widget to the bottom panel.
   - Ability resize terminal widget.
   - Ability send text to the terminal widget.
   - Ability destroy terminal widget.
   - Ability track user input from terminal widget.
- [ ] rework che-theia-terminal-extension to the plugin. We should use terminal widget api to create new terminal in the plugin and wrote connection logic for stdin/stdout for terminal widget.
- [ ] rename repository from che-the-terminal-extension to the che-theia-terminal-plugin.

**Comment by l0rd** [comment]
Already implement ed
