### ISSUE TITLE
Theia Machine Plugin: add missing API and implement the plugin

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11443]
List of missing Theia API to implement:

- [x] TreeView API
- [x] [Rendering hyperlinks in the Tree](https://github.com/theia-ide/theia/issues/3304)

Features:
- [x] have a view that shows machine/service and URL
   - [x] be able to click on URL (rendered in Tree node)
   - [x] quick access to terminal
- [ ] have a command to access to all available machine/service URL
- [ ] [Run a command with predefined ID when click on hyperlink in the Tree View](https://github.com/theia-ide/theia/issues/3491)

**Comment by olexii4** [comment]
@l0rd  Could you explain more about "have a command to access to all available machine/service URL". As I understand, it can be a command, registered by containers plugin and show a list of servers in the modal notification window or something else?
