### ISSUE TITLE
[Theia][Plugin]Rework Task extension to Task plugin

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#11458]
The existing https://github.com/eclipse/che-theia-task-plugin is developed based on the existing extensibility model in Theia IDE. But as far as new plugin model is on it's way and will be used in Che as the main one - there is need to rework Task extension to Task plugin.

P.S.: add subtask here if need

Missing Theia Plugin APIs to implement:
- [x] `tasks.registerTaskProvider` https://github.com/theia-ide/theia/issues/3503
- [x] `tasks.onDidStartTask` https://github.com/theia-ide/theia/issues/3505
- [x] `che.registerVariableProvider` https://github.com/eclipse/che/issues/11953
- [x] `che.registerTaskRunner` https://github.com/eclipse/che/issues/11954
- [x] Fix 'onDidSelectItem' behavior for Quick Pick widget  https://github.com/theia-ide/theia/issues/4046
- [x] Ability to open URL in the Preview Tab https://github.com/theia-ide/theia/pull/4243
- [x] Ability to get current selection in the explorer view https://github.com/theia-ide/theia/issues/4043
- [x] Theia Terminal plugin https://github.com/eclipse/che/issues/11442
- [x] Ability to specify container for webview panel https://github.com/theia-ide/theia/issues/4257
- [x] Ability to check whether the webview panel is active and visible https://github.com/theia-ide/theia/issues/4342
- [x] Implement 'WebviewPanel.reveal() https://github.com/theia-ide/theia/issues/4339
- [x] Add 'tasks.taskExecutions' API https://github.com/theia-ide/theia/issues/4372
- [x] Improve the way of storage runtime info for Che tasks https://github.com/eclipse/che-theia/issues/78

To implement Task plugin features progressively we can implement it in the following order:

- once the `tasks.registerTaskProvider` API is done
  - [x] implement [providing](https://github.com/eclipse/che-theia-task-plugin/blob/master/che-theia-task-extension/src/browser/che-task-provider.ts#L25) the Che workspace commands as Theia tasks
- once the `che.registerTaskRunner` API is done
  - [x] implement [CheTaskRunner](https://github.com/eclipse/che-theia-task-plugin/blob/master/che-theia-task-extension/src/node/che-task-runner.ts) for running the tasks via machine-exec server
- once the `che.registerVariableProvider` API is done
  - [x] implement [`resolving`](https://github.com/eclipse/che-theia-task-plugin/blob/master/che-theia-task-extension/src/browser/che-task-resolver.ts#L37) the variables in a Che task
  - [x] add [VariableProvider](https://github.com/eclipse/che-theia-task-plugin/blob/master/che-theia-task-extension/src/browser/variable/server-variables-contribution.ts) for resolving server's address by name, e.g.: `${server.tomcat}`
- once the `tasks.onDidStartTask` API and Terminal API is done
  - [x] make it possible to connect to machine-exec container to show a task's output
  - [x] implement Preview URL functionality(info message with ability to open preview URL in the preview widget of Thea project or in a new tab of browser)
- once ability to specify container for webview panel is done
  - [x] implement widget for displaying list of preview URLs (server name ---> Preview button ---> Go to button) and ability to display it from status bar item
- once the 'tasks.taskExecutions' API is done
  - [x] add ability to display preview URL for running tasks 
- once ability to get current selection in the explorer view is done 
  - [x] implement [project path variable resolver](https://github.com/eclipse/che-theia-task-plugin/blob/master/che-theia-task-extension/src/browser/variable/che-task-variables-contribution.ts#L39-L81), e.g.: `${current.project.path}`
- once Theia Terminal plugin is done
  - [x] switch task's output from output channel to terminal widget
- once Webview API is improved
  - [ ] improve way of updating previews widget

**Comment by azatsarynnyy** [comment]
Useful links that might be helpful:

- User's guide https://code.visualstudio.com/docs/editor/tasks
- Task API guide https://code.visualstudio.com/docs/extensions/example-tasks
- Task API reference https://code.visualstudio.com/docs/extensionAPI/vscode-api#_tasks
- `taskDefinitions` contribution point https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributestaskdefinitions

**Comment by azatsarynnyy** [comment]
I've updated the description with the subtasks.

**Comment by slemeur** [comment]
How are we doing on this issue and what's remaining? is the task list in the issue description up to date?
