### ISSUE TITLE
Kubernetes Operator for Che deployment

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11469]
### Description

Implement an Operator for che-server deployment.  The shopping list:

- [x] Should be able to create che-host route
- [x] Should be able to create che SA rolebinding
- [x] Support single-user Che with default parameters
- [x] Support multi-user Che with default parameters
- [x] Parameters:
  - [x] Support external Keycloak and Postgre
  - [x] Support with/without HTTPS
- [x] Support Che configuration to use Users tokens to create workspaces/namespaces
- [x] Should work on both Kube and OpenShift (v3.11+)
- [x] Publish on [awesome operators](https://github.com/operator-framework/awesome-operators) [PR](https://github.com/operator-framework/awesome-operators/pull/118)
- [x] Publish on OperatorHub

**Comment by l0rd** [comment]
@eivantsov yes I think we are ready for that :-) (e.g. `eclipse/che-operator`)

@jasonmadigan yes @eivantsov has a working che-operator and we are considering to make it the default way to deploy Che on kube and OpenShift. We need to address a couple of things to make deployment UX easier and then we will do a proposal to the Che community.

**Comment by eivantsov** [comment]
@l0rd ok, I will request a new repo, write a good README, setup automated build for a Docker image, polish some parts of code, add missing configmap envs, set reasonable defaults etc.

**Comment by eivantsov** [comment]
Waiting for the remaining CQs and proposing a PR https://github.com/eclipse/che-operator/tree/initial_pr

**Comment by tolusha** [comment]
@l0rd 
Can we close it?

**Comment by l0rd** [comment]
I have created the PR for the last bullet point https://github.com/operator-framework/awesome-operators/pull/118

**Comment by l0rd** [comment]
@tolusha che operator has been included in the [awesome operators list](https://github.com/operator-framework/awesome-operators) 🎉🎉🎉.
I am closing this issue.
