### ISSUE TITLE
IDE2-2018-11-13  (Sprint: 157)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#11638]
### Sprint Goals:
1. Fix execs bugs on Openshift
2. Extend Plugin API with Che API
3. Finalize APIs: WebView, Languages 
4. Polish Theia development flow
5. Convert extensions to plugins

##  1. Fix execs bugs on Openshift
- [x] che-machine-exec(Kubernetes infra) after few hours get connection refused https://github.com/eclipse/che-machine-exec/issues/9
- [x] Terminal on close connection doesn't remove key listener https://github.com/eclipse/che-theia-terminal-extension/issues/24
- [ ] Blog post about terminal 10sp
- [x] Prepare presentation about terminal for F2F 5sp

## 2. Extend Plugin API with Che API
- [ ] Add new "che" namespace to Plugin API to have dedicated APIs https://github.com/eclipse/che/issues/11306 (POC) (50sp)

##  3. Finalize APIs: TreeView, WebView, Languages 
- [ ] [Languages] define and add the needed APIs [TODO create issue about packaging XML VSCode extension as Che Theia plugin and publish in plugin registry] 10sp
- [ ] [plug-in] Implement inspect configuration https://github.com/theia-ide/theia/issues/2289 
- [ ] [plug-in] Implement Webview API https://github.com/theia-ide/theia/issues/2708 15sp in progress
- [x] [plug-in][languages] Add API for registering a code actions provider https://github.com/theia-ide/theia/issues/3162  in progress
- [ ] [plug-in] create a file system watcher https://github.com/theia-ide/theia/issues/3163 40sp
- [x] [plug-in] API for registering Text Document Content Provider https://github.com/theia-ide/theia/issues/2786 25sp
- [x] [plug-in] Make it possible to render hyperlinks in the Tree node  https://github.com/theia-ide/theia/issues/3304 5sp

## 4. Polish Theia development flow
- [ ] Create a test framework to test interactions between API and plugin runtime https://github.com/theia-ide/theia/issues/3160 50sp
- [ ] [plug-in] Improve Theia plugin hosted mode launch https://github.com/theia-ide/theia/issues/3345

## 5. Convert extensions to plugins
- [ ] Theia Machine Plugin: add missing API and implement the plugin https://github.com/eclipse/che/issues/11443 40sp
- [ ] Convert Che-theia factory extension to plugin https://github.com/eclipse/che/issues/11249 [clone to test, execution of task - API for this, open file? ] 10sp

## Other  issues:
- [x] [TODO] stack - Java + Theia IDE + sample (petclinic) + define commands 10sp
- [ ] Git clone command: return repository location URI https://github.com/theia-ide/theia/issues/3191 10sp

**Unplanned:**
- [ ] Minimal set of dashboard improvements for Che 7 https://github.com/eclipse/che/issues/11788
- [ ] Minimal set of Theia terminal improvements for Che 7 https://github.com/eclipse/che/issues/11789

**Candidates for the next sprint:**
- [ ] Workspace is restarted after start interruption https://github.com/eclipse/che/issues/11077
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [ ] Project view is broken if Theia is used as IDE in a workspace https://github.com/eclipse/che/issues/10915
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [ ] Include sidecars memory into total memory of workspace on dashboard https://github.com/eclipse/che/issues/11801

**Total planned = [todo]sp**

### Pending PRs
- [x] CHE-9595: Apply terminal api examples https://github.com/theia-demo-plugins/theia-backend-plugin/pull/5

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1waFnThEYwO_30oX5DrW1LBLZCCczRMFUSf8B64zzDo4/edit)
