### ISSUE TITLE
IDE-2018-11-13 (Sprint: 157)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#11640]
#### Theia goals
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574
- [ ] [plug-in] API for register a filesystem provider theia-ide/theia#2861
- [x] [plug-in][languages] Register a code lens provider https://github.com/theia-ide/theia/issues/3199
- [ ] [plug-in][languages] Register a document symbol provider https://github.com/theia-ide/theia/issues/3200
- [x] [plug-in] Add API for onDidSaveTextDocument in workspace namespace https://github.com/theia-ide/theia/issues/3201 
- [x] [Theia][Plugin]Rework SSH extension to SSH plugin #9720
- [x] [Theia][Plugin]Rework GitHub extension to GitHub plugin #11457  

#### Che goals
- [x] [Language server] Signature Help feature doesn't work with "(" character #10699 
- [ ] Go to symbol feature do not show items with enabled C# language server #11258
- [x] Che fails on hover if Language Server returns Hover object with null contents #10480
- [x] Upload private SSH key to VCS does not work on the multi-user assembly #11574
- [x] 'Build' console tab switches to another tab if rerun it by 'Re-run' button #10979 
- [x] The "Rename method" form does not close during timeout #10784
- [x] There is a duplicate commands goal in a project context menu after changing a command settings #4940
- [x] Unexpected alert is displayed in the 'git compare form' #2299
- [x] Add links to GitHub and Mattermost channel in the IDE #6321

#### Artem 
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574
- [x] [plug-in][languages] Register a code lens provider https://github.com/theia-ide/theia/issues/3199
- [ ] [plug-in][languages] Register a document symbol provider https://github.com/theia-ide/theia/issues/3200

#### Dmytro 
- [x] [Language server] The Refactor -> Rename feature does not work for Golang language server #10524
- [x] [Python language server] The Refactor -> Rename feature does not work if py file not formatted properly #10523
- [ ] [plug-in] API for register a filesystem provider theia-ide/theia#2861

#### Roman 
- [x] The "Rename method" form does not close during timeout #10784
- [x] 'Build' console tab switches to another tab if rerun it by 'Re-run' button #10979 
- [x] [plug-in] Add API for onDidSaveTextDocument in workspace namespace https://github.com/theia-ide/theia/issues/3201 

####  Vitalii
- [x] Unexpected alert is displayed in the 'git compare form' #2299
- [x] Add links to GitHub and Mattermost channel in the IDE #6321

#### Vlad
- [x] [Language server] Content of language server hover feature is duplicated #10117 
- [x] Project tree items are not updated with VCS status colors after changes in the terminal #10875
- [x] There is a duplicate commands goal in a project context menu after changing a command settings #4940

#### Igor
- [x] [Theia][Plugin]Rework SSH extension to SSH plugin #9720
- [x] [Theia][Plugin]Rework GitHub extension to GitHub plugin #11457  

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |7 |  
| Dmytro  | 14 |   
| Roman  |9 | 
| Vitalii  |14|    
| Igor |0 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
