### ISSUE TITLE
QE-2018-11-13 (Sprint: 157)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#11677]
### Sprint goals
- Remain only stable tests in E2E test suit, move flaky tests to a separate suit
- Adapt E2E tests for changes caused by jdt.ls branch merge.

### Issues tied to objectives
- [x] Create Selenium test covered "start Theia in hosted mode and test the plugin" #11400 2sp
- [x] Adapt tests after merging JDT.LS branch in master #11659 3sp
- [x] Exclude constantly/randomly failing selenium tests from execution #11688 32sp

### Unplanned 
- [x] Unexpected fails of "CheckBasicFunctionalityInCommandsExplorerTest", "CheckOnValidAndInvalidPackageNameTest" and "CheckShowHideHiddenFilesTest" selenium tests #11716 1sp
- [x] Investigate failing the 'checkRenameParameters15()' from the 'RenameParametersTest' on CI  #11729 1sp
- [x]  Investigate failing the 'checkFindProjectSymbolFeature() from the 'GolangFileEditingTest' on CI #11730  1sp
- [x] Investigate failing some test methods from the 'RenamePackageTest' on CI #11731 1sp
- [x] Unexpected fails of "TheiaBuildPluginTest", "JavaDocPopupTest", "CheckAutocompleteFeaturesInTheTestFolderTest", "ContextMenuEditorTest" selenium tests #11728 1sp
- [x] Unexpected fails of "AutocompleteProposalJavaDocTest", "ShowHintsCommandTest", "DownloadProjectTest", "CheckRestoringSplitEditorTest" selenium tests #11741 1sp
- [x] Delete the 'try-catch' from the 'ImportAndValidateEclipseCheProjectTest' #11757 1sp
- [x] Create selenium test for checking of the "Che 7 Preview" stack creation #11797 1sp
- [x] Unexpected fail of "TheiaBuildPluginTest" and "Che7PreviewStackStartTest" selenium tests #11810 1sp
- [x] Get rid of boilerplate code in the "Menu" selenium page object #11871 1sp
- [x] Get rid of legacy code in the "Consoles" selenium page object #11217 1sp
- [x] Unexpected fail of "TheiaBuildPluginTest" selenium test #11897 1sp
- [ ] Get rid of redundant methods in the "SeleniumWebDriverHelper" class #11911 2sp

### PR under review
- [x] https://github.com/eclipse/che/pull/11681
- [x] https://github.com/eclipse/che/pull/11698
- [x] https://github.com/eclipse/che/pull/11698
- [x] https://github.com/eclipse/che/pull/11691
- [x] https://github.com/eclipse/che/pull/11745
- [x] https://github.com/eclipse/che/pull/11771
- [x] https://github.com/eclipse/che/pull/11768
- [ ] https://github.com/eclipse/che/pull/10454
- [x] https://github.com/eclipse/che/pull/11778

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
| Total |  75 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 37 | 37 |
