### ISSUE TITLE
Platform-2018-11-13 (Sprint: 157)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11679]
### Features related to Devfile
- [x] Setup Devfile implementation plan fro Phase 1 | https://github.com/eclipse/che/issues/11719 | 5

### Features related to  Opentracing support for k8s / OpenShift infrastructures in Che
- [x] Implementation plan for Opentracing support for k8s / OpenShift infrastructures in Che | https://github.com/eclipse/che/issues/11720 | 5
### Technical debts and bugs

- [x] Unable to open secure server with cookiesAuthEnabled if server has https protocol | https://github.com/eclipse/che/issues/11664 | 8
- [x] Add env var for enabling wsagent debug in the docs | https://github.com/eclipse/che/issues/11682 | 3
- [x] Che samples docs | https://github.com/eclipse/che/issues/11721 | 8
- [x] Add debug logging on each step of K8s/OS runtime start | https://github.com/eclipse/che/issues/10408 | 8
- [x] Go-agent tests sometimes fail on CI | https://github.com/eclipse/che/issues/10914 | 5
- [ ] Respect unrecoverable event that occurs when Pod spec is considered invalid by a k8s cluster | https://github.com/eclipse/che/issues/11411 | 5
- [ ] Revise model of meta.yaml and che-plugin.yaml | https://github.com/eclipse/che/issues/11479 | 8
- [ ] Support Template object in OpenShift recipe | https://github.com/eclipse/che/issues/11504 | 13

### Unplanned
- [x] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-8:compile (default) on project assembly-ide-war: GWT exited with status 137 https://github.com/eclipse/che/issues/11675
- [x] Building che-plugin-wizard (sample) https://github.com/eclipse/che/issues/11645
- [x] Multi-user Che on Kubernetes doesn't work  https://github.com/eclipse/che/issues/11831
- [x] Upgrade fabric8-kubernetes-client version to v.4.1.0 https://github.com/eclipse/che/issues/11112
- [x] Make Kubernetes infrastructure create a special service account for workspaces https://github.com/eclipse/che/issues/11349
- [ ] Remove pure kubectl deployment https://github.com/eclipse/che/issues/11135
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 13d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 68  | 42 |
#### Retrospective Comments
 Action Item (Sergii K) 
- Study usage of Google Draw to vote for retro action items.
- Study IDE2 like google doc for daily reports
- Find some tools for online Scrum Pocker
