### ISSUE TITLE
Languages Sprint 157 (K-2)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11733]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 6 | 4 | 5d
@tolusha | 10 | 6 | 5d 
@svor | 11 | 7 | 2d
@vrubezhny | 9d | 6d | 7d 
@JPinkney | 3d | 2d | 3d

# Candidate issues 
- [ ] The plain java project is not detected after importing from github #11516 (3d) @tsmaeder 
- [ ] Provide Plugin API for contributing Debug Adapters https://github.com/theia-ide/theia/issues/2990 5d (@tolusha )
- [x] Theia Consume che-ls-jdt as jdt.ls extension https://github.com/theia-ide/theia/issues/2849 (2d) @svor 
- [ ] Use the `DocumentSymbol.detail` not just only the `DocumentSymbol.name` https://github.com/theia-ide/theia/issues/2894 (2d)
- [ ] Register a workspace symbol provider see: https://github.com/theia-ide/theia/issues/2341  (1d) 
- [ ] Register a references provider https://github.com/theia-ide/theia/issues/3308 (5d)
- [x] Plan out K-Train (@tsmaeder) 2d

Unplanned:
- [ ] Contribute Java Debug Adapter https://github.com/theia-ide/theia/issues/3059
- [x] Add MS Debug Adapter as a jdt.ls Extension https://github.com/theia-ide/theia/issues/3058
- [x] The "Navigate File Form" has difference if compare with upstream #11490 (2d) (@tsmaeder)

# Open PR's 
- [ ] https://github.com/theia-ide/theia/pull/2970 2d
- [ ] https://github.com/theia-ide/theia/pull/2461 2d
- [x] https://github.com/eclipse/che-ls-jdt/pull/83

Previous sprint: https://github.com/eclipse/che/issues/11438
