### ISSUE TITLE
IDE-2018-12-04 (Sprint: 158)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#11852]
#### Theia goals
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574
- [ ] [Theia][Plugin]Rework Task extension to Task plugin #11458
  - [x] [plug-in][tasks] Register a task provider https://github.com/theia-ide/theia/issues/3503
- [ ] [plug-in] API for register a filesystem provider theia-ide/theia#2861
- [x] [plug-in][languages] Register a document symbol provider https://github.com/theia-ide/theia/issues/3200
- [x] [plug-in] API endpoint for window.withProgress https://github.com/theia-ide/theia/issues/2802
- [x] [plug-in] API endpoint for window.showTextDocument https://github.com/theia-ide/theia/issues/2801
- [x] [plug-in] Add an ability to open editor in the specified column https://github.com/theia-ide/theia/issues/3553 (needed for `window.showTextDocument` API)

#### Che goals
- [x] The editor tab closes after performing refactor/move action in the editor by context menu #11697
- [x] Unexpected hanging of the Loader after actions #8300
- [x] Open in Terminal feature does not work if workdir is not set to the projects root #10894 (PR: https://github.com/eclipse/che/pull/11914)
- [x] Go to line does not work properly in the 'diff git compare' form #11791
- [x] Not possible to configure projects sources for LS launched on standalone machine #10032
- [x] [Regression] File Structure feature doesn't work #11927
- [x] Fix rename operation availability for golang language server https://github.com/eclipse/che/issues/11907

#### Artem 
- [ ] Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574
- [x] [plug-in][languages] Register a document symbol provider https://github.com/theia-ide/theia/issues/3200

#### Dmytro 
- [x] Not possible to configure projects sources for LS launched on standalone machine #10032
- [ ] [plug-in] API for register a filesystem provider theia-ide/theia#2861

#### Roman 
- [x] Go to line does not work properly in the 'diff git compare' form #11791
- [x] [plug-in][tasks] Register a task provider https://github.com/theia-ide/theia/issues/3503

#### Vlad
- [x] Unexpected hanging of the Loader after actions #8300
- [x] Open in Terminal feature does not work if workdir is not set to the projects root #10894 (PR: https://github.com/eclipse/che/pull/11914)
- [x] [Regression] File Structure feature doesn't work #11927
- [x] Fix rename operation availability for golang language server https://github.com/eclipse/che/issues/11907

#### Igor
- [x] The editor tab closes after performing refactor/move action in the editor by context menu #11697
- [x] [plug-in] API endpoint for window.withProgress https://github.com/theia-ide/theia/issues/2802
- [x] [plug-in] API endpoint for window.showTextDocument https://github.com/theia-ide/theia/issues/2801
- [x] [plug-in] Add an ability to open editor in the specified column https://github.com/theia-ide/theia/issues/3553

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |7 |  
| Dmytro  | 14 |   
| Roman  |9 | 
| Vitalii  |14|    
| Igor |0 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
