### ISSUE TITLE
IDE2-2018-12-04 (Sprint: 158)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#11864]
### Sprint Goals:
0. Team F2F
1. Extend Plugin API with Che API
2. Introduce Che Theia terminal as plugin
3. Introduce Theia Machine Plugin
4. Pull request plugin for Che's Theia
5. Finalize APIs: Languages
6. Testing framework for Plugin API
7. Che Theia in Che Theia

## 1. Extend Plugin API with Che API
- [ ] Add new "che" namespace to Plugin API to have dedicated APIs https://github.com/eclipse/che/issues/11306 (POC) (65sp)

## 2. Introduce Che Theia terminal as plugin
- [ ] Theia Terminal plugin: add missing API and implement the Plugin https://github.com/eclipse/che/issues/11442 plan only `Upstream changes` (40sp)

## 3. Introduce Theia Machine Plugin
- [x] [plug-in] Make it possible to render hyperlinks in the Tree node  https://github.com/theia-ide/theia/issues/3304 5sp
- [ ] Theia Machine Plugin: add missing API and implement the plugin https://github.com/eclipse/che/issues/11443 20sp

## 4. Pull request plugin for Che's Theia
- [x] Include existing GitHub plugin in Che Theia IDE https://github.com/eclipse/che/issues/11867 spend one day to find missing API than create issue, if plugin works we should publish on plugin registry (10sp)
- [ ] Implement open link command https://github.com/theia-ide/theia/issues/3639
- [ ] Add support for multiroot workspace in workspace folders part of plugin API https://github.com/theia-ide/theia/issues/3573
- [ ] Implement plugin API to get workspace folder by file uri https://github.com/theia-ide/theia/issues/3647

##  5. Finalize APIs: Languages 
- [ ] [plug-in] Implement inspect configuration https://github.com/theia-ide/theia/issues/2289 (40sp)
- [x] [plug-in] create a file system watcher https://github.com/theia-ide/theia/issues/3163 25sp
- [x] [plug-in] API for registering Text Document Content Provider https://github.com/theia-ide/theia/issues/2786 25sp

## 6. Testing framework for Plugin API
- [ ] Create a test framework to test interactions between API and plugin runtime https://github.com/theia-ide/theia/issues/3160 50sp

## 7. Che Theia in Che Theia
- [ ] Image for dev che-theia in che-theia should be the che-theia builder https://github.com/eclipse/che/issues/11938

## Other  issues:
- [ ] Minimal set of dashboard improvements for Che 7 https://github.com/eclipse/che/issues/11788 20sp
- [ ] Minimal set of Theia terminal improvements for Che 7 https://github.com/eclipse/che/issues/11789 15sp
- [ ] Add shell probe https://github.com/eclipse/che-machine-exec/issues/7 15sp
- [ ] Make it possible to specify path for command execution in it's configuration https://github.com/eclipse/che/issues/11866 15sp

## Technical debts 
- [ ] Workspace is restarted after start interruption https://github.com/eclipse/che/issues/11077
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [ ] Project view is broken if Theia is used as IDE in a workspace https://github.com/eclipse/che/issues/10915
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [ ] Che-theia loader undefined https://github.com/eclipse/che/issues/11773

**Total planned = [todo]sp**

### Pending PRs
- [ ] [plug-in] [WIP] Plugin API documentation https://github.com/theia-ide/theia/pull/3045

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1jJ1nk60uVVoCTQLF4nkl8sRfuFbW2WsTO8Kr3_SNBSk/edit?usp=sharing)

**Comment by garagatyi** [comment]
@ashumilova @evidolob I would remove `Include sidecars memory into total memory of workspace on dashboard #11801` from the sprint. For now, it is not possible to implement that on UD side. This would require some architectural changes in the workspace bootstrapping to provide that from server side, whereas it is next to impossible to do that on UD.

**Comment by ashumilova** [comment]
@garagatyi Thank you for notifying.
