### ISSUE TITLE
Platform-2018-12-04 (Sprint: 158)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11887]
### Features related to Devfile

- [ ] Implementation of local part of devfile feature | https://github.com/eclipse/che/issues/11832 | 8
- [x] Describe DevFile model via Json Scheme | https://github.com/eclipse/che/issues/11904 | 8
- [x]  Commands API for Workspace.Next | https://github.com/eclipse/che/issues/9546 | 13

### Features related to  Opentracing support for k8s / OpenShift infrastructures in Che
- [x] Tracing workspace related operation | https://github.com/eclipse/che/issues/11922 | 8

### Features related to  Monitoring
- [x] Exposing JMX Beans via HTTP for Prometheus consumption | https://github.com/eclipse/che/issues/11384 | 13

### Technical debts and bugs
- [ ] Upgrade depenendecies | https://github.com/eclipse/che/issues/11902 | 8
- [x] Slow pvc binding: Che workspace fails to start because of pod has unbound PersistentVolumeClaims | https://github.com/eclipse/che/issues/11848 | 3
### Unplanned
- [x] Jaeger deployment for Kubernetes https://github.com/eclipse/che/issues/12013
- [ ] Automated way to trust certs in a stack  https://github.com/eclipse/che/issues/10910
- [x] Display installers logs when a workspace is starting https://github.com/eclipse/che/issues/11572
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Lukas Krejci | 15d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 61  | 45 |
