### ISSUE TITLE
Languages Sprint 158 (K-3)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#11903]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 8 | 5 | 8
@tolusha | 12 | 7 | 7
@svor | 15 | 9  | 9
@vrubezhny | 14  | 8  | 8
@JPinkney | 3d | 2d | 3d

# Candidate issues 
- [ ] The plain java project is not detected after importing from github #11516 (3d) @tsmaeder 
- [ ] Provide Plugin API for contributing Debug Adapters https://github.com/theia-ide/theia/issues/2990 7d (@tolusha )
- [ ] LSP client wrapper for Theia #11468 (5d timebox) (@svor)
- [x] Register a type definition provider [#3463](https://github.com/theia-ide/theia/issues/3463) 3d (@vrubezhny )
- [x] Register a implementation provider [#3465](https://github.com/theia-ide/theia/issues/3465) 3d (@vrubezhny)
- [x] Plan out L-Train (@tsmaeder) 5d

Unplanned:
- [ ] Code Documentation Standards for Theia Code 3d #11900

# Open PR's 
- [ ] https://github.com/theia-ide/theia/pull/2970 2d
- [ ] https://github.com/theia-ide/theia/pull/2461 2d
- [x] https://github.com/theia-ide/theia/pull/3401 2d
- [x] https://github.com/theia-ide/theia/pull/3402
- [x] https://github.com/theia-ide/theia/pull/3314 2d
- [ ] https://github.com/eclipse/che-theia-java-plugin/pull/12
- [x] https://github.com/eclipse/che-theia-java-plugin/pull/2
- [ ] Detect Simple Java Projects on Import #12041 https://github.com/eclipse/che/pull/12041

Previous sprint: https://github.com/eclipse/che/issues/11733
