### ISSUE TITLE
QE-2018-12-04 (Sprint: 158)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#11935]
### Issues tied to objectives
- [x] Get rid of redundant methods in the "SeleniumWebDriverHelper" class #11911 2sp

### Unplanned 
- [x] Unexpected fail of "CheckOnValidAndInvalidClassNameTest" and "RenamedAlreadyCreatedNotJavaFileTest" selenium tests #11978 1sp
- [x] Unexpected fail of "CheckErrorsWarningsTabTest" selenium test #11992 1sp
- [x] Cover workspace sharing feature by selenium test #11993 2sp
- [x] Unexpected fail of "TheiaBuildPluginTest" and "RenameProjectTest" selenium tests #11997 1sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
| Total |  75 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
