### ISSUE TITLE
Plugin Brokers Improvements

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#11980]
### Description

We have introduced the plugin brokers to support [workspace.next walking skelethon](https://github.com/eclipse/che/issues/10123). The skeleton has been implemented and we received the first feedbacks at EclipseCon Europe. This epic is to organize the work to implement production-ready brokers that will be GA on next Che next major release (Che 7).

### Tasks

- [x] Add Unit Tests for brokers
- [x] Brokers refactoring (remove duplicate code)
- [x] Add the support for plugins of type VS Code Extension (registry, wsmaster and broker side) (#12026)
- [x] Add sidecar image attribute in `meta.yaml` (part of the #12026)

**Comment by l0rd** [comment]
cc @garagatyi @sleshchenko @benoitf @skabashnyuk @ibuziuk @azatsarynnyy

**Comment by azatsarynnyy** [comment]
> Theia should support loading a remote plugin without requiring the main process to scan of a local plugin

Currently, Theia already supports loading the remote plugins which are:
- hosted on Visual Studio Marketplace
- published as a GitHub release
- accessible by any http(s) link

@benoitf correct me if I'm wrong, please

**Comment by benoitf** [comment]
@azatsarynnyy the idea is that the .theia file should only be inside the remote container or only in volume only accessible by this theia endpoint container. Today we need to provide .theia file to the main theia container

About `hosted on Visual Studio Marketplace` for now it works in plain theia (with the command palette/deploy command) but we want to see as well these plug-ins from Dashboard when configuring the workspace.

**Comment by l0rd** [comment]
Opened #12392 and removed "Theia should support loading a remote plugin without requiring the main process to scan of a local plugin" from the list.

**Comment by l0rd** [comment]
Moved the non Che 7 task to #12398
