### ISSUE TITLE
IDE2-2018-12-25 (Sprint: 159)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#12057]
### Sprint Goals:
1. Extend Plugin API with Che API
2. Pull request plugin for Che's Theia
3. Finalize APIs: Languages
4. Testing framework for Plugin API
5. Che Theia in Che Theia

## 1. Extend Plugin API with Che API
- [ ] Add new "che" namespace to Plugin API to have dedicated APIs https://github.com/eclipse/che/issues/11306 (POC):
- [ ] for factories [TODO issue] 50sp

## 2. Pull request plugin for Che's Theia
- [ ] Include existing GitHub plugin in Che Theia IDE https://github.com/eclipse/che/issues/11867 spend one day to find missing API than create issue, if plugin works we should publish on plugin registry (10sp)
- [ ] Finish implementation of plugin context https://github.com/theia-ide/theia/issues/3607 (in progress TODO issues for tasks) 
- [x] Implement logPath for plugin context. https://github.com/theia-ide/theia/issues/3660 10sp 
- [ ] [plugin-in] Implement Plugin Context 'globalState' and 'workspaceState' https://github.com/theia-ide/theia/issues/3732 40sp
- [x] [plug-in] Implement Plugin Context 'storagePath' https://github.com/theia-ide/theia/issues/3733 20sp
- [x] Implement open link command https://github.com/theia-ide/theia/issues/3639 15sp
- [x] Add support for multiroot workspace in workspace folders part of plugin API https://github.com/theia-ide/theia/issues/3573 
- [x] Implement plugin API to get workspace folder by file uri https://github.com/theia-ide/theia/issues/3647

##  3. Finalize APIs: Languages 
- [ ] [plug-in] Implement inspect configuration https://github.com/theia-ide/theia/issues/2289 (depends on https://github.com/theia-ide/theia/pull/3247)

## 4. Testing framework for Plugin API
- [ ] mocking plugin API [TODO issue] 40sp

## 5. Che Theia in Che Theia
- [x] Image for dev che-theia in che-theia should be the che-theia builder https://github.com/eclipse/che/issues/11938
- [x] Start Che Theia on another than 3000 port by default https://github.com/eclipse/che/issues/12074 15sp

## Other  issues:
- [ ] Minimal set of dashboard improvements for Che 7 https://github.com/eclipse/che/issues/11788 10sp
- [ ] Minimal set of Theia terminal improvements for Che 7 https://github.com/eclipse/che/issues/11789 15sp
- [x] Add shell probe https://github.com/eclipse/che-machine-exec/issues/7 15sp
- [ ] Make links to docs and support Configurable in Dashboard https://github.com/eclipse/che/issues/12052 5sp
- [ ] Fix 'add a new machine' flow for che7-workspace https://github.com/eclipse/che/issues/12047 15sp
- [ ] TODO issue add workspace APIs for Che plugin API

## Unplanned tasks
- [ ] Update xterm.js to the latest https://github.com/eclipse/che-theia-terminal-extension/issues/32 Piggyback created https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18571
- [ ] Dashboard factory: Remove mandatory aspect from workspace.projects[x].type property when creating a factory from a workspace https://github.com/eclipse/che/issues/12217

## Pending PR
- [x] Use shell options from terminal widget options or doesn't set up shell at all. Server side should auto-detect it https://github.com/eclipse/che-theia-terminal-extension/pull/31
- [x] Use shell detector https://github.com/ws-skeleton/che-machine-exec/pull/13
- [x] Fix Theia test with command terminal name. https://github.com/eclipse/che/pull/11973
- [x] Implement terminal exit https://github.com/eclipse/che-theia-terminal-extension/pull/27
- [x] Send to client exit or error event for exec https://github.com/ws-skeleton/che-machine-exec/pull/12
- [x] Opened editors list view https://github.com/eclipse/che-theia-samples/pull/17
- [x] Add Webwiew API to the plugin system https://github.com/theia-ide/theia/pull/3484
- [x] Implement plugin API to get workspace folder by file URI https://github.com/theia-ide/theia/pull/3718
- [x] Initial Che api for Theia https://github.com/eclipse/che-theia/pull/1
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045

## Technical debts 
(_some time in sprint is allocated to handle those issues_ )
- [ ] Workspace is restarted after start interruption https://github.com/eclipse/che/issues/11077
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [ ] Project view is broken if Theia is used as IDE in a workspace https://github.com/eclipse/che/issues/10915
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [ ] Che-theia loader undefined https://github.com/eclipse/che/issues/11773
- [ ] Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state. https://github.com/eclipse/che/issues/11893
- [ ] Make it possible to specify path for command execution in it's configuration https://github.com/eclipse/che/issues/11866 15sp
- [ ] Add image with debugger to speed up development https://github.com/eclipse/che-machine-exec/issues/12

**Total planned = [todo]sp**

### Next sprint proposals
- [ ] Theia Container Plugin: add missing API and implement the plugin https://github.com/eclipse/che/issues/11443 20sp
 - [ ] Move latest che-machine-exec to the eclipse repo https://github.com/eclipse/che-machine-exec/issues/13 15sp
- [ ] Fix incorrect terminal size on open on the Minikube https://github.com/eclipse/che-theia-terminal-extension/issues/35 10sp - very annoying for internal use.

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |
