### ISSUE TITLE
IDE-2018-12-25 (Sprint: 159)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12067]
#### Theia goals
**Add Theia Plugin APIs to support VS Code Kubernetes Tooling #10574**
- [ ] [plug-in] Add API to apply workspace edit theia-ide/theia#2784
- [x] Add support for the context menus in the contributed views theia-ide/theia#3646
- [x] Add support for 'when' expressions theia-ide/theia#3658

**Rework Theia Task extension to Task plugin #11458**
- [x] [plug-in][tasks] Register a task provider theia-ide/theia#3503
- [ ] [plug-in][tasks] Add tasks.onDidStartTask API theia-ide/theia#3505
- [x] [Theia][Plugin] Add VariableProvider API #11953
- [ ] [Theia][Plugin] Add TaskRunner API #11954

- [x] Theia Tasks Run fails on Che 7 Kubernetes workspaces #12125

#### Che goals
- [ ] Che Server rejects JSON RPC messages which may lead to losing events #11961
- [ ] IDE should respect commands from Runtime #12053
- [x] 'Stop process' button is displayed at closing another tab #11746
- [x] Process tree node lose selection #11744
- [x] Find References panel icon has incorrect hover message #10700
- [x] Invisible buttons in quickfix popups with light theme #10342
- [x] Cursor jumps when edit file content #9272

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 13 |  
| Vlad |13 |  
| Dmytro  | 13 |   
| Roman  |8 | 
| Vitalii  |13|    
| Igor |13 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
