### ISSUE TITLE
Languages Team L-Train Targets

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12071]
A place to keep track of issues describing L-Train related items

**Beta (Feb 5.)**

* LS and Debuggers as remote Theia plugins
Since all Theia plugins are remote plugins, this item comes down to making language servers and debug adapters run as Theia plugins. Packaging language servers and their native dependencies as a Che plugin is up to the individual plugin.
One of the issues here is that debuggers may try to launch the debuggee (not the debug adapter) in the container they are in, which is bogus. This means running vscode debug extensions is not generally a solution.

  * [x] Languages API https://github.com/theia-ide/theia/issues/2341
  * [x]  Provide Plugin API for contributing Debug Adapters  https://github.com/theia-ide/theia/issues/2990
  * [x] LSP client wrapper for Theia https://github.com/eclipse/che/issues/11468
  * [ ] **How to send/receive messages (e.g. extended protocol like "progress") to and from contributed language servers?**  
  * [x] TextMate grammars? (part of package.json, see https://github.com/evidolob/theia-docker-plugin)
* Java LS and Debugger as plug-in (Java Language Plugin https://github.com/theia-ide/theia/issues/3778) 
  * both plugins need to have a shared file system (debugger plugin needs to contribute bundles to jdt.ls)
  * java plugin needs API's: 
    * [ ] Label provider
    * [ ] Commands API
    * [ ] Menu API
    * [ ] ApplyWorkspaceEdit API
  * Need to make or find an appropriate base image for jdt.ls-based tools
  * Publish a che plugin with Theia Java plugin + image
  * New repo for github/eclipse/theia-java-plugin, che-plugin in Che-Theia repo
* TypeScript LS and Debugger as plug-in
  * [x] Nodejs Debug Adapter Plugin https://github.com/theia-ide/theia/issues/3766, https://github.com/eclipse/che/issues/12409
  * [x] Typescript Language Plugin https://github.com/theia-ide/theia/issues/3767, https://github.com/eclipse/che/issues/12408
  * Typescript, too has a mechanism to be extended: see tslint extension package.xml, "typescriptServerPlugins"
  * CallhierarchyService extensions: need to make this into API like languages API https://github.com/theia-ide/theia/issues/3765
  * need preferences API
  * tslint extension
  * Issue: run typescript tools in Theia image?

* [x] Go LS and Debugger as plug-in https://github.com/eclipse/che/issues/12025
There is https://github.com/theia-ide/go-language-server for a langugage server, but I don't think it has DAP support. 
* YAML LS as plug-in (Typescript-based)
* Scalability Issues (Che-in-Che)
* Maintain JDT.LS in CodeReady Workspaces
* [x] Lost debug Panels https://github.com/theia-ide/theia/issues/3377

**GA (Mar. 19)**
* Python LS and Debugger as plug-in
* PHP LS and Debugger as plug-in
* C# LS and Debugger as plug-in
* XML LS as plug-in (Java-based)
* Extending How-to: How to Add Support for a new language
* Extending How-to: How to Add Support for a new debugger
