### ISSUE TITLE
QE-2018-12-25 (Sprint: 159)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#12084]
### Unplanned 
- [x] Fix build of selenium tests to be comply with new version of guava #12184 3sp
- [x] [Selenium] Change selenium tests from 'projectexplorer' package to wait that jdtls is fully initialized before working with project #12205 1sp
- [x] Delete the 'try-catch' expression from the 'refactor.parameters' tests #12209 1sp
- [x] Delete the 'try-catch' expression from the 'CodeAssistAfterMoveItemTest' test #12211 1sp
- [x] Correct the tests from 'git ' package to increase reliability when run on CI #12216 2sp
- [x] Correct the 'ConfigureSomeSourceFoldersTest' to increase reliability when run on CI #12223 2sp
- [x] Correct the 'InitializeAndDeleteLocalRepositoryTest' to increase reliability when run on CI #12241 1sp
- [x] Investigate e2e technologies for Thea #12204 5sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 14 |
| Maxim Musienko | 14 |
| Dmytro Nochevnov | 14 |
| Igor Ohrimenko | 14 |
| Sergey Skorik | 14 |
| Total |  70 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
