### ISSUE TITLE
Platform-2018-12-25 (Sprint: 159)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12090]
### Features related to Devfile
- [x] Create a JSON-schema for the Devfile | https://github.com/eclipse/che/issues/11904 | 1
- [x] Check devfile format matches Kubernetes naming format | https://github.com/eclipse/che/issues/12080 | 5
- [x] Implement logical integrity validation on Devfile AP | https://github.com/eclipse/che/issues/12079 | 8

### Features related to  Monitoring
- [x] Create REST method to get all workspaces with filter | https://github.com/eclipse/che/issues/12091 | 8
- [ ] [Metric] Number of workspaces by state | https://github.com/eclipse/che/issues/12092 | 8

### Technical debts and bugs
- [x] Upgrade depenendecies | https://github.com/eclipse/che/issues/11902 | 5
- [x] [Plugin-registry] Convert icons to svg format | https://github.com/eclipse/che/issues/12095 | 5
- [ ] Che on OpenShift/K8S: https proxy and no proxy issues | https://github.com/eclipse/che/issues/12097 | 8
- [x] Make it possible to turn on verbose mode for fabric8 client | https://github.com/eclipse/che/issues/12055 | 8
- [x] Jaeger deployment for Kubernetes | https://github.com/eclipse/che/issues/12013 | 3
- [ ] Deploy Prometheus in Che Helm Chart | https://github.com/eclipse/che/issues/12059 | 3
- [x] Allow configuration of CORS credential settings for WS Master | https://github.com/eclipse/che/issues/12058 | 3
- [ ] Upgrade to latest Tomcat 8  https://github.com/eclipse/che/issues/12127 
### Finalize issues started in the previous sprint.
- [x] Automated way to trust certs in a stack  https://github.com/eclipse/che/issues/10910

### Unplanned
 - [x] Implement suggestions made in PR Support PerWorkspacePVCStrategy  https://github.com/eclipse/che/issues/12165
- [x] Package GWT IDE as Che Editor https://github.com/eclipse/che/issues/12172
- [x] Prometheus and Grafana ingress is created even if metrics are not enabled  https://github.com/eclipse/che/issues/12191
- [ ] Track workspace pod existence https://github.com/eclipse/che/issues/12207
- [ ] Devfile support in factory https://github.com/eclipse/che/issues/12186

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 11d |
| Max Shaposhnik | 16d | 
| Michail Kuznyetsov | 16d | 
| Sergii Leshchenko | 16d | 
| Lukas Krejci | 16d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 65  |46 |
