### ISSUE TITLE
Languages Sprint 159 (L-1)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12135]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 10 | 6
@tolusha | 14 | 8 | 12
@svor | 14 | 8 | 13
@vrubezhny | 13 | 8 | 9

# Candidate Issues 
- [ ] The plain java project is not detected after importing from github #11516 (2d) @tsmaeder 
- [ ] Rename project problem #12000 (@tsmaeder)
- [x] Provide Plugin API for contributing Debug Adapters https://github.com/theia-ide/theia/issues/2990 7d (@tolusha )
- [x] LSP client wrapper for Theia #11468 (7d) (@svor)
- [x] Register a document highlight provider https://github.com/theia-ide/theia/issues/3635 @vrubezhny 2d
- [ ] CallHierarchyService Plugin API https://github.com/theia-ide/theia/issues/3765 7d (@vrubezhny )
- [x] Lost debug Panels https://github.com/theia-ide/theia/issues/3377 5d @tolusha 
- [ ] Java Language Plugin https://github.com/theia-ide/theia/issues/3778 (@svor)
- [x] Remove che-plugin-maven-server https://github.com/eclipse/che/issues/12164

# Unplanned Issues
- [ ] Typescript Language Plugin https://github.com/theia-ide/theia/issues/3767
- [ ] Golang plugin https://github.com/eclipse/che/issues/12145
- [ ] Nodejs debugger plugin https://github.com/theia-ide/theia/issues/3766
- [ ] Yaml plugin https://github.com/eclipse/che/issues/12142

Prerequisite for Che 7 vscode plugins: https://github.com/eclipse/che/issues/12026

# Open PR's 
- [x] Reuse jdt.ls workspaces https://github.com/theia-ide/theia/pull/2970 1d
- [ ] https://github.com/theia-ide/theia/pull/2461 2d
- [ ] https://github.com/eclipse/che-theia-java-plugin/pull/12
- [ ] Detect Simple Java Projects on Import #12041 (2d)
- [x] Register an implementation provider https://github.com/theia-ide/theia/issues/3465 
- [x] Workspace symbol API https://github.com/theia-ide/theia/pull/3513 (@vrubezhny)

Previous Sprint: https://github.com/eclipse/che/issues/11903
