### ISSUE TITLE
Che 7 Beta

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12170]
## Che 7 Beta Details
**Goal:** The implementation of the new capabilities for Che 7 has been targeting the self-hosting mode from its start. The goal of the Che 7 Beta, is to finalize the new Che version with the ability for everyone to use Eclipse Che to extend/customize it. That version will also include the first part of a new CLI which simplify the installation and management of Che.

**User Story 1 (hosted theia plugin dev):** As a Che developer I want to start a ws.next based workspace that is configured to load theia as the editor and an “hello world” frontend theia plugin (using an existing che stack from the dashboard and with the editor and plugins definition available in a remote plugin registry) so that I will be able to easily extend this model developing new theia plugins.

**User Story 2 (java/nodejs dev):** As a developer using Che, I want to start a ws.next based workspace that is configured with the tooling that I defined for my NodeJS/Java project (configuring it from the dashboard, or using a devfile on the repository) so that I will be able to develop on my project and get all language tooling.

**User Story 3 (chectl and operator):** As an admin of Che, I want to use a CLI based tool that is provided with Che to install and configure my Eclipse Che using (using the operator) so that I can easily control my installation.

**User Story 4 (k8s plugin basic flow):** As a developer using Che, I want to interact with my K8S / OpenShift cluster using dedicated plugins, so I can manage my cluster and push my source code onto the cluster.

**Success Criteria:**
Implementation of the 4 user stories with:
- The plugin registry ~~is deployed with the plugin viewer~~
- The user is able to configure the workspace for his project with the tools he wants
- Complete inner loop is working in the new IDE: Code, Build, Run and Debug
- Java and NodeJS Supported (including Debugger)
- Complete support of K8S objects into workspaces
- Installation flow managed from the CLI

**What's in Che 7 Beta:**
- Workspace.Next finalization: Support all K8S objects
- IDE.Next: Plug-ins API and support for Java, Typescript, XML, YAML
- Plugin Broker
- DevFile Support
- Introduction of a new CLI
- Che-in-Che development
- Introduction of tests for Theia IDE
- Minimal experience refinements (Terminal, Dashboard, Configuration) 
- Minimal set of documentation

**What's not in Che 7 Beta:** 
- Implementation of a new dashboard to better fit with Workspace.Next and devfile changes
- Go, Python, PHP Support
- Pull Request plugin
- Complete CLI

**Target:** 5th February

#### Che OSIO
- [x] Improving the Plugin Broker (WIP) https://github.com/eclipse/che/issues/11980
- [x] Introducing the VSCode Plugin Broker (PRs sent) https://github.com/eclipse/che/issues/12026
   - https://github.com/eclipse/che-plugin-broker/pull/19
   - https://github.com/eclipse/che/pull/12149
   - https://github.com/eclipse/che-plugin-registry/pull/66
However, Kubernetes VS Code extension will not work due to https://github.com/eclipse/che/issues/12292
- [x] Workspace.Next finalization: support K8S Deployment  https://github.com/eclipse/che/issues/11505 
- [x] Workspace.Next finalization: support K8S ConfigMap  https://github.com/eclipse/che/issues/11507
- [x] Remote plugin runner should copy env vars when it starts plugin process #12298 
- [x] Workspace.Next finalization: support K8S Routes https://github.com/eclipse/che/issues/11530 
- [x] Workspace.Next finalization: support K8S Template https://github.com/eclipse/che/issues/11504
- [x] Workspace.Next finalization: support K8S Secret https://github.com/eclipse/che/issues/11508
- [x] Allow multiple Che 7 workspaces to run at the same time #12238
- [x] Better support form devfile linked yamls #12572

#### IDE
- [x] IDE should respect commands from runtime #12053
- [x] Workspace commands should be in Theia command palette #12239 
- [x] Add new workspace:inject --kubeconfig command https://github.com/che-incubator/chectl/issues/31

#### IDE 2
- [x] Theia Plugin APIs for Language (WIP) https://github.com/theia-ide/theia/issues/2341
- [x] Che specific Plug-in APIs (WIP) https://github.com/eclipse/che/issues/11306 and https://github.com/eclipse/che/issues/11240
- [x] Minimal set of Theia terminal improvements (WIP) https://github.com/eclipse/che/issues/11789
- [x] Minimal set of dashboard improvements https://github.com/eclipse/che/issues/11788
- [x] Projects sync (cloned from Theia) to workspace definition (WIP) https://github.com/eclipse/che/issues/12006
- [x] Remote plugin can't call tool included into a sidecar container  https://github.com/eclipse/che/issues/12292
- [x] Fix Che-Theia Extensions to work with latest upstream Theia https://github.com/eclipse/che-theia/issues/37
- [ ] Define and Document how to develop Che Theia and plugins with Che (WIP) [Google doc](https://docs.google.com/document/d/1V292nYN655ekPPZvzdg7zbLpwVXW5uFjmffgoN2CmpM/edit#)
- [x] Publish a nightly Che-Theia image and editor in the registry that uses nightly upstream Theia https://github.com/eclipse/che-theia/issues/39
- [x] Remove JDK and Java LS extension from Che-Theia https://github.com/eclipse/che-theia/issues/55
- [x] Fix factories https://github.com/eclipse/che/issues/12581

#### Languages

- [x] Theia Plugin APIs for Debug Adapter  https://github.com/theia-ide/theia/issues/2990
- [x] LS and Debuggers as remote Theia plugins 
- [x] Java LS as plug-in https://github.com/theia-ide/theia/issues/3778
- [ ] Java  Debugger as plug-in https://github.com/theia-ide/theia/issues/3778
- [x] TypeScript LS and Debugger as plug-in https://github.com/theia-ide/theia/issues/3767
- [x] YAML LS as plug-in https://github.com/eclipse/che/issues/12142
- [x] XML LS as plug-in https://github.com/theia-ide/theia/issues/3317
- [x] GO as plugin https://github.com/eclipse/che/issues/12145

#### Platform
- [ ] Devfile Support #11549
  - [x] Devfile support in factory (WIP) #12186
  - [x] Add ability to specify workspace environment in Devfile  #11906 ([doc](https://docs.google.com/document/d/1ywDiI4ZWq81w32d3bIkYe1PY1m_ANxSLXBzRHi5MYsc/edit?usp=sharing), [PR1](https://github.com/redhat-developer/devfile/pull/2))
  - [x] Factory flow should support k8s/OS tool in Devfile (WIP) #12266
  - [x] Generate Devfile Spec documentation => https://github.com/eclipse/che/issues/12272
  - [x] Publish Devfile documentation on http://redhat-developer.github.io/devfile  https://github.com/eclipse/che/issues/12524
  - [ ] Add support for docker image devfile tools #12389
  - [ ] Add an ability to specify entrypoint for dockerimage tool in Devfile #12668 
  - [ ] Add an ability to specify entrypoint for dockerimage tool in OpenShift and Kubernetes #12693 
- [x] wsmaster prometheus metric endpoint: Number of failed Workspaces startup #12242

#### Deploy
- [x] Operator for K8S and OpenShift https://github.com/eclipse/che/issues/11469
- [ ] chectl initial milestone https://github.com/che-incubator/chectl/issues/1
- [x] Operator support for chectl https://github.com/che-incubator/chectl/issues/23 

#### Docs
- [ ] Get Started with Eclipse Che 7 [RHDEVDOCS-917](https://issues.jboss.org/browse/RHDEVDOCS-917)
- [ ] User How-to: Create a workspace from code sample
- [ ] User How-to: Create a workspace by import source code of your project
- [ ] Che Workspaces [outline](https://docs.google.com/document/d/1RuLh2w3DPdlYlebadNdf90n_xM5Nw5rHIDEBrXHy6I4/edit#heading=h.rc25t5yk4hfp)
- [ ] Creating Eclipse Theia Plug-ins with Eclipse Che [outline](https://docs.google.com/document/d/1RuLh2w3DPdlYlebadNdf90n_xM5Nw5rHIDEBrXHy6I4/edit#heading=h.rc25t5yk4hfp)
- [ ] Extending How-to: How to Add Support for a new language [outline](https://docs.google.com/document/d/1RuLh2w3DPdlYlebadNdf90n_xM5Nw5rHIDEBrXHy6I4/edit#heading=h.rc25t5yk4hfp)
- [ ] Extending How-to: How to Add Support for a new debugger [outline](https://docs.google.com/document/d/1RuLh2w3DPdlYlebadNdf90n_xM5Nw5rHIDEBrXHy6I4/edit#heading=h.rc25t5yk4hfp)
- [ ] Extending How-to: How to switch the default editor from Che, to another one [outline](https://docs.google.com/document/d/1RuLh2w3DPdlYlebadNdf90n_xM5Nw5rHIDEBrXHy6I4/edit#heading=h.rc25t5yk4hfp)
- [ ] Update the readme.MD and customizing.MD with the new information about Che-in-Che [outline](https://docs.google.com/document/d/1RuLh2w3DPdlYlebadNdf90n_xM5Nw5rHIDEBrXHy6I4/edit#heading=h.rc25t5yk4hfp)

#### Others

- [ ] Create Che 7 stacks https://github.com/eclipse/che/issues/12620
- [x] Release Che 7 https://github.com/eclipse/che/issues/12621

### IDE2
- [ ] Detect services that are listening to a port and propose to expose it https://github.com/eclipse/che/issues/12061 (**Not Started** / **Not critical for Che 7 Beta**)

#### IDE
- [ ] Finalize Kubernetes Plugin Support (WIP) https://github.com/eclipse/che/issues/10574
- [ ] Finalize OpenShift Plugin Support https://github.com/eclipse/che/issues/11488
- [ ] Rework Task extension to a plug-in https://github.com/eclipse/che/issues/11458
- [x] wsmaster scalability issues: Output Endpoint https://github.com/eclipse/che/issues/11961 

#### Languages
- [ ] Scalability Issues (Che-in-Che) https://github.com/eclipse/eclipse.jdt.ls/issues/865

#### Platform

- [ ] Take into account Plugins memory requirements when creating a workpsace https://github.com/eclipse/che/issues/11801 
- [ ] Add more fields to the plug-in registry https://github.com/eclipse/che-plugin-registry/issues/71
- [ ] Integration of Plugin Viewer with Plugin Registry https://github.com/eclipse/che/issues/12373

#### QE
- [x] Define the strategy to add tests on Theia (WIP) (Investigate e2e technologies for Thea #12204)
- [ ] Che in Che QE
- [ ] Test for Yeoman Generate plugins
- [ ] Scalability testing (WIP)

**Comment by garagatyi** [comment]
@slemeur what if we also create Che GA epic and put there everything we want for the GA to keep track of the stuff?

**Comment by slemeur** [comment]
sure go ahead!

**Comment by garagatyi** [comment]
Since Florent self-assigned https://github.com/eclipse/che/issues/12292 I moved it from others section to IDE2 team section which used to accommodate Florent's issues.
