### ISSUE TITLE
IDE2-2019-01-15 (Sprint: 160)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12229]
### Sprint Goals:
1. Theia Plugin APIs for Language - Beta
2. Che specific Plug-in APIs - Beta
3. Define and Document how to develop Che Theia with Che - Beta
4. Projects sync (cloned from Theia) to workspace definition - Beta
5. Minimal set of dashboard improvements for Che 7 - Beta
6. Minimal set of Theia terminal improvements for Che 7 - Beta

Che 7 Beta Epic - https://github.com/eclipse/che/issues/12170

##  1. Theia Plugin APIs for Language - Beta
- [ ] [plug-in] Implement inspect configuration https://github.com/theia-ide/theia/issues/2289 (depends on https://github.com/theia-ide/theia/pull/3247)
- [x] [plug-in] Implement 'registerRenameProvider' for Languages API https://github.com/theia-ide/theia/issues/3861 6d
- [x] [plug-in] Implement 'registerColorProvider' Language API https://github.com/theia-ide/theia/issues/3862 5d
- [x] [plug-in] Implement 'registerFoldingRangeProvider' Languages API https://github.com/theia-ide/theia/issues/3863 2d

## 2. Che specific Plug-in APIs - Beta
- [x] Add new "che" namespace to Plugin API to have dedicated APIs https://github.com/eclipse/che/issues/11306 3d
- [x] Theia Container Plugin: add missing API and implement the plugin https://github.com/eclipse/che/issues/11443 5d

## 3. Define and Document how to develop Che Theia with Che - Beta
 TODO - issue

## 4. Projects sync (cloned from Theia) to workspace definition - Beta
- [ ] Che-theia: projects cloned in Theia are not synchronized back to Che workspace definition https://github.com/eclipse/che/issues/12006 4d

## 5. Minimal set of dashboard improvements for Che 7 - Beta
- [x]  Configuration should be saved automatically (remove SAVE button) -> moving to separate issue #12136 3d

## 6. Minimal set of Theia terminal improvements for Che 7 - Beta
- [ ] Minimal set of Theia terminal improvements for Che 7 https://github.com/eclipse/che/issues/11789 3d
  - [ ] Add as many "Open Terminal" commands as there are containers (but filter out the exec plugin container). So user could select directly from the command palette the terminal to open:
    - [x]  Add as many "Open Terminal" commands as there are containers
    - [ ]  Filter out the exec plugin containers from terminal commands: depends on https://github.com/eclipse/che/issues/11804 
  - [ ] "Open Terminal" and "Open Terminal in specific container" should appear in Theia View menu 

## Other  issues:
- [ ] Add the needed methods for Webview API https://github.com/theia-ide/theia/issues/3896 4d
- [ ] mocking plugin API [TODO issue] 40sp
- [x] Make links to docs and support Configurable in Dashboard https://github.com/eclipse/che/issues/12052 1d
- [x] Fix 'add a new machine' flow for che7-workspace https://github.com/eclipse/che/issues/12047 3d
- [ ] Move latest che-machine-exec to the eclipse repo https://github.com/eclipse/che-machine-exec/issues/13 3d
- [x] Fix incorrect terminal size on open on the Minikube https://github.com/eclipse/che-theia-terminal-extension/issues/35 2d - very annoying for internal use.
- [x] Update xterm.js to the latest https://github.com/eclipse/che-theia-terminal-extension/issues/32 Piggyback created https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18571
- [x] Dashboard factory: Remove mandatory aspect from workspace.projects[x].type property when creating a factory from a workspace https://github.com/eclipse/che/issues/12217 2d
- [x] [plugin-in] Implement Plugin Context 'globalState' and 'workspaceState' https://github.com/theia-ide/theia/issues/3732 4d - Che 7 GA

## Unplanned tasks
- [ ] Apply ability filter user containers from among others https://github.com/eclipse/che/issues/11804 need for `Minimal set of Theia terminal improvements for Che 7` goal

## Pending PR
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045

## Technical debts 
(_some time in sprint is allocated to handle those issues_ )
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871
- [ ] Move all che-theia related extensions/plugins in che-theia repository https://github.com/eclipse/che/issues/12306 IDE2 team part
- [ ] Workspace is restarted after start interruption https://github.com/eclipse/che/issues/11077
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [ ] Project view is broken if Theia is used as IDE in a workspace https://github.com/eclipse/che/issues/10915
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [ ] Che-theia loader undefined https://github.com/eclipse/che/issues/11773
- [ ] Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state. https://github.com/eclipse/che/issues/11893
- [ ] Make it possible to specify path for command execution in it's configuration https://github.com/eclipse/che/issues/11866 15sp (needed for devfile - for platform team)
- [ ] Add image with debugger to speed up development https://github.com/eclipse/che-machine-exec/issues/12

**Total planned = [todo]sp**

### Next sprint proposals
- Make Theia plugin state and workspace state persistent https://github.com/eclipse/che/issues/12260
- Open link vscode command doesn't work https://github.com/theia-ide/theia/issues/3936
### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1-LZ-YGcYb0JlHER5GV9UQfRh3SV9xBm3ldHhH7otlgc/edit)
