### ISSUE TITLE
Platform-2019-01-15 (Sprint: 160)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12224]
### Features related to Devfile
- [ ] Devfile Spec documentation generator | https://github.com/eclipse/che/issues/12272 | 8
- [x] Factory flow should support k8s/OS tool in Devfile as relative file path in repository | https://github.com/eclipse/che/issues/12266 | 13
- [x] An ability to specify Kubernetes/OpenShift List as tool in Devfile | https://github.com/eclipse/che/issues/11906 | 5
- [ ] Support Kubernetes PVCs in recipes and resolves them as Che Volume. Note that PVCs strategies should be supported as well | https://github.com/eclipse/che/issues/12269 | 13

### Features related to  Monitoring

- [x] [Metric] Number of failed workspace startup | https://github.com/eclipse/che/issues/12242 | 8
- [x] [Metric] API error rate (number of 500 responses from che server) | https://github.com/eclipse/che/issues/12244 | 8

### Tasks, Technical debts and bugs

- [ ] Refresh workspace activity during runtime restore on workspace master startup | https://github.com/eclipse/che/issues/12225 | 8
- [ ] Handle more metadatas for the plugin viewer | https://github.com/eclipse/che-plugin-registry/issues/71 | 5

### Finalize issues started in the previous sprint.
- [x] Factory devfile | https://github.com/eclipse/che/pull/12232 | 5
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 6d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Lukas Krejci | 10d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 73  | 39 |

#### Retrospective Comments

- Do pre-planning after prioritization meeting.
  It will allow to determinate which issue need additional information.
  We need that to be able correctly determinate a scope of big tasks or reduce the number of such tasks. Ideally, after prioritization, we should not have unexpected items that are not related to our L train backlog.

- Reduce the number of story points we are taking into the sprint since for the last couple of sprints
  we have a set of PRs at the end of the sprint that almost-merged but we need a day or two to finalize it.
