### ISSUE TITLE
Improve che-plugin.yaml (and devfile) format

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12249]
### Description

This is issue is to address some comments that have been identified in PR https://github.com/redhat-developer/devfile/pull/2:

-  [x] Use of the property `mountProjectSources` (or even the simpler `mountSources`) for a tool/plugin https://github.com/eclipse/che/issues/12413
- [x]  Add the ability to specify `subPath` of a volume https://github.com/eclipse/che/issues/12414
- [x] Improve `che-plugin.yaml` fields names https://github.com/eclipse/che/issues/12415
   * `public` should become an endpoint `attribute` 
   * consider renaming `Devfile#dockerimageTool#endpoints[]#targetPort` field to `port` https://github.com/redhat-developer/devfile/pull/2#discussion_r242894015
  * consider renaming `Devfile#dockerimageTool#services` field to `endpoints` to sync `che-plugin.yaml` and Dockerimage tool models https://github.com/redhat-developer/devfile/pull/2/files#diff-238112cd9401c996e39c118cb7008fdcR19

**Comment by sleshchenko** [comment]
Also:
* consider renaming `Devfile#dockerimageTool#endpoints[]#targetPort` field to `port` https://github.com/redhat-developer/devfile/pull/2#discussion_r242894015
* consider renaming `Devfile#dockerimageTool#services` field to `endpoints` to sync `che-plugin.yaml` and Dockerimage tool models

**Comment by metlos** [comment]
Note I've split #12413 into more fine grained issues:
* [ ] Implement mountSources boolean attribute in che-plugin.yaml #12510 
* [ ] Support mountSources for non-plugin tools in devfile #12554
* [ ] Support custom environment variables for tools in devfile #12555
* [ ] Implement a way for the devfile user to specify the root path of the projects. #12531
* [ ] Support checkoutPath in devfile #12557
* [ ] Support autodetection of checkoutPath of projects #12558
