### ISSUE TITLE
Eclipse Che plan regarding Docker infrastructure and GWT IDE

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12243]
### Description
On the last Eclipse Che community meeting, we announced some plans
regarding Docker infrastructure and GWT IDE. I

#### Phase 1
- [x] Discussion on Che community meeting. 
- [x] Сomunity notes about deprecation plans.
- [x] Start releasing GWT IDE as sidecar package with each Che release https://github.com/eclipse/che/issues/12172
#### Phase 2
- [ ] Adapt GWT IDE to run natively in sidecar.
- [ ] Check authentication with GWT IDE running in sidecar. https://github.com/eclipse/che/issues/12273
- [ ] Remove traefik routing from GWT IDE sidecar.
- [ ] Update docs with notice about deprecation plans 
- [ ] Gwt ide in sidecar is not working due to CORS configuration on ws-agent  https://github.com/eclipse/che/issues/12403
#### Phase 3
- [ ] After the release of 6.17 we should create a new Che 6.x branch (for bug fixing and GWT IDE and Docker stuff). At the end we will do 2 releases: 6.18.0 (based on branch 6.x) and 7.0.0.beta (based on master).
- [ ] Move GWT IDE to separate repo.
- [ ] Che7 Remove gwt ide from workspace master.
- [ ] Remove Che 6 stacks from master.
#### Phase 4
- [ ] Docker CLI and Docker infra removed.
- [ ] Documentation about Docker CLI and Docker infra removed.
- [ ] Docs about GWT IDE updated

I would like to underline that Phases are approximate and you should not consider them as an obligation.
Potentially we could add release or two to achieve our goals to provide better UX.

**Comment by skabashnyuk** [comment]
There are some options like 
- https://blog.docker.com/2018/07/kubernetes-is-now-available-in-docker-desktop-stable-channel/ 
- https://che.eclipse.org/running-eclipse-che-on-kubernetes-using-docker-desktop-for-mac-5d972ed511e1

**Comment by l0rd** [comment]
@skabashnyuk you have added this issue to `7.0.0` but https://github.com/eclipse/che/pull/13788 has been merged and I we don't plan to do more of this epic for v7.0.0 don't we?

**Comment by skabashnyuk** [comment]
@l0rd no plans left. Closing.
