### ISSUE TITLE
IDE-2019-01-15 (Sprint: 160)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12254]
#### Sprint goals
- [x] Add new workspace:inject --kubeconfig command https://github.com/che-incubator/chectl/issues/31
- [x] Workspace commands should be in Theia command palette #12239
- [x] [plug-in] Add API to apply workspace edit theia-ide/theia#2784
- [ ] Rework Theia Task extension to Task plugin #11458**
- [x] [plug-in][tasks] Add tasks.onDidStartTask API theia-ide/theia#3505
- [ ] [Theia][Plugin] Add TaskRunner API #11954
- [ ] Che Server rejects JSON RPC messages which may lead to losing events #11961
- [x] IDE should respect commands from Runtime #12053
- [x] Editor header text has multiple striketrhoughs making the title unreadable #10905 
- [ ] Wrong behavior in the editor when perform git pull after delete files #11648
- [x] Regexp for pom.xml not working in LanguageServerConfig #12329

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 4 |  
| Vlad |13 |  
| Dmytro  | 3 |   
| Roman  |13 | 
| Vitalii  |13|    
| Igor |13 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
