### ISSUE TITLE
QE-2018-01-15 (Sprint: 160)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#12280]
### Sprint goals
- Setup QA process for Che7

### Issues tied to objectives
- [x] Investigate e2e technologies for Thea #12204 5sp
- [x] Add an ability to exclude flaky selenium tests from execution #12129 1sp
- [x] Adapt selenium tests from 'factory' package according to factory creation changes #12295 1sp
- [x] Refactoring selenium tests from the 'debugger' package #12299 2sp
- [x] Test LoginNewUserWithOpenShiftOAuthTest#checkNewCheUserOcpProjectCreationAndRemoval failed on CI #12309 1sp
- [x] Refactoring selenium tests from the 'editor' package #12312 2sp
- [x] Selenium: Refactoring selenium tests from the 'factory' package #12322 2sp

### Unplanned 
- [ ] Selenium: Refactoring selenium tests from the 'dashboard' package #12328 2sp
- [x] Selenium: Refactoring selenium tests from the 'intelligencecommand' package #12330 2sp
- [x] Selenium: Refactor selenium tests from the 'languageserver' package #12332 2sp
- [ ] Selenium: Refactor selenium tests from the 'miscellaneous' package #12356 2sp
- [x] Update version of selenium chrome-node in E2E selenium tests to 3.141.59-dubnium #11455 2sp
- [x] Role "user" looks redundant in Eclipse Che keycloak #12261 2sp
- [x] Create e2e test for Theia with Cypress framework #12364 5sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 13 |
| Maxim Musienko | 13 |
| Dmytro Nochevnov | 13 |
| Igor Ohrimenko | 13 |
| Sergey Skorik | 13 |
| Total |  65 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
