### ISSUE TITLE
Move all che-theia related extensions/plugins in che-theia repository

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12306]
### Description
As we discuss on che-dev mail we should move all Che + Theia related projects in one repo:
https://github.com/eclipse/che-theia

### IDE1
- [ ] che-theia-emacs-plugin https://github.com/eclipse/che-theia-emacs-plugin empty repo
- [ ] che-theia-vi-plugin https://github.com/eclipse/che-theia-vi-plugin empty repo
- [x] Theia - Che Task Extension https://github.com/eclipse/che-theia-task-plugin
- [x] Theia - SSH Plug-in https://github.com/eclipse/che-theia-ssh-plugin https://github.com/eclipse/che-theia/pull/31

### IDE 2
- [ ] Theia - GitHub Plug-in https://github.com/eclipse/che-theia-github-plugin
- [x] Terminal exec extension https://github.com/eclipse/che-theia-terminal-extension. Subtask:  https://github.com/eclipse/che/issues/12423
- [x] Theia Hosted Plugin Manager extension https://github.com/eclipse/che-theia-hosted-plugin-manager-extension
- [x] Che Theia factory https://github.com/eclipse/che-theia-factory-extension
- [x] Theia Machines Extension https://github.com/eclipse/che-theia-machines-plugin
- [x] che-theia-activity-tracker extension https://github.com/eclipse/che-theia-activity-tracker
- [x] Che Theia dashboard https://github.com/eclipse/che-theia-dashboard-extension

### Languages
- [ ] Che-Theia - Java Plugin https://github.com/eclipse/che-theia-java-plugin

### ws-skeleton
- [x] che-editor-theia https://github.com/ws-skeleton/che-editor-theia
- [x] che-theia-generator https://github.com/ws-skeleton/che-theia-generator
- [x] che-machine-exec https://github.com/ws-skeleton/che-machine-exec ?
- [x] che-theia-remote-extension https://github.com/ws-skeleton/che-theia-remote-extension
- [x] theia-endpoint-java8 https://github.com/ws-skeleton/theia-endpoint-java8 ?

### Deprecated repository(delete or archive): 
- [ ] che-theia-oauth-authentication-plugin https://github.com/eclipse/che-theia-oauth-authentication-plugin empty, there are no files in repo
- [ ] Environment Variables Extension https://github.com/eclipse/che-theia-env-variables-plugin deprecated

**Comment by vparfonov** [comment]
@slemeur 
che-theia-emacs-plugin https://github.com/eclipse/che-theia-emacs-plugin 
che-theia-vi-plugin https://github.com/eclipse/che-theia-vi-plugin
Probably will be better to use VS Code plugins instead of spend time on reworking our extensions to the plugins.
What do you think?

**Comment by dneary** [comment]
@vparfonov For me, the decision comes down to where to spend effort: is it better to identify the work required to make VS Code plugins to work, or to implement plugins for the feature for Che? Part of that depends on how much work is needed in each case, and how many other things will be enabled in each case.

In general, I would favour evaluating whether the equivalent VS Code plug-ins work - if they work today, great! Effort saved. And if they do not, then identifying which plug-in APIs or functionalities need work to enable them to work. At that point, you have information to decide whether to get the VS Code plug-ins working unchanged, or whether to "port" them to Theia.

**Comment by vparfonov** [comment]
My personal experience give feeling it would be not fast. For example, we spent a lot of time for K8s plugin and still not done. But in same time covering API one time we will open the door for all plugins which use this API. There are potential risks of being not able to implement all existed VS Code APIs  in Theia. 
So if talk about this concrete plugin will be faster to transform it form Theia Extension to Theia Plugin, BTW it not covered all VI behavior instead of VS Code https://marketplace.visualstudio.com/items?itemName=vscodevim.vim.

**Comment by sunix** [comment]
che-theia repo should only contain plugins and extensions that are specific to Che
- using Che api's
- provide features that only works on Che use cases
- features that have high value on Che
The more we integrate VSCode extensions, the faster integration of new VSCode extension would be to implement.
For all these reasons, I would not include emacs and vi plugins to che-theia repo.

**Comment by benoitf** [comment]
done
