### ISSUE TITLE
Languages Sprint 160 (L-2)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12352]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 4 | 2 | 2
@tolusha | 14 | 8 | 12
@svor | 14 | 8 | 13
@vrubezhny | 13 | 8 | 9

# Candidate Issues 
- [ ] Rename project problem #12000 (@tsmaeder)
- [ ] Plugin as sidecar initialization fails when browser is refreshed https://github.com/theia-ide/theia/issues/3970 (@tolusha)
- [ ] Golang plugin https://github.com/eclipse/che/issues/12145 (@tolusha)
- [ ] CallHierarchyService Plugin API https://github.com/theia-ide/theia/issues/3765 3d (@vrubezhny )
- [ ] Java Language Plugin https://github.com/theia-ide/theia/issues/3778 (@svor)
- [ ] Code lens feature doesn't work correctly https://github.com/theia-ide/theia/issues/3946 (2d)
- [ ] Update jdt.ls https://github.com/eclipse/che/issues/12263
# Unplanned Issues

- [ ] Commands API is not implemented clearly https://github.com/theia-ide/theia/issues/3968
- [ ] workspace/didChangeConfiguration not sending correct params to YAML language server when deployed by plugin ID https://github.com/theia-ide/theia/issues/3892
- [x] Typescript Language Plugin https://github.com/theia-ide/theia/issues/3767
- [ ] Nodejs debugger plugin https://github.com/theia-ide/theia/issues/3766
- [ ] Yaml plugin https://github.com/eclipse/che/issues/12142

Prerequisite for Che 7 vscode plugins: https://github.com/eclipse/che/issues/12026

# Open PR's 
- [ ] https://github.com/theia-ide/theia/pull/2461 2d
- [ ] https://github.com/eclipse/che-theia-java-plugin/pull/12
- [x] Detect Simple Java Projects on Import #12041 (2d)
- [ ] Use problem manager to handle markers from plugins https://github.com/theia-ide/theia/pull/4178
Previous Sprint: https://github.com/eclipse/che/issues/12135
