### ISSUE TITLE
IDE2-2019-02-05 (Sprint: 161)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12362]
### Sprint Goals:
1.  Adapt dashboard to allow configuring ephemeral mode for workspaces - Beta
2. Define and Document how to develop Che Theia with Che - Beta
3. Projects sync (cloned from Theia) to workspace definition - Beta
4. Minimal set of Theia terminal improvements for Che 7 - Beta

Che 7 Beta Epic - https://github.com/eclipse/che/issues/12170

Next Goals - Che 7 GA: 
-  Implement flow to install a plugin from the IDE - GA
- Rework Terminal extension to a plug-in
- Docs:
  - Extending Eclipse Che
  - Extending How-to: How to provide a "custom IDE" based on Eclipse Theia
  - Extensibility Reference

##  1.  Adapt dashboard to allow configuring ephemeral mode for workspaces - Beta
- [x] Add ability to configure ephemeral mode for workspaces from dashboard https://github.com/eclipse/che/issues/12374 2d

## 2. Define and Document how to develop Che Theia with Che - Beta
- [ ] Write documentation on how to 'Creating Eclipse Theia Plug-ins with Eclipse Che'  https://github.com/eclipse/che/issues/12425  - 1 sprint
- [ ] Update the readme.MD and customizing.MD with the new information about Che-in-Che https://github.com/eclipse/che/issues/12426 - 1 sprint

## 3. Projects sync (cloned from Theia) to workspace definition - Beta
- [x] Che-theia: projects cloned in Theia are not synchronized back to Che workspace definition https://github.com/eclipse/che/issues/12006 3d

## 4. Minimal set of Theia terminal improvements for Che 7 - Beta
- [ ] Minimal set of Theia terminal improvements for Che 7 https://github.com/eclipse/che/issues/11789 3d
  - [ ] Add as many "Open Terminal" commands as there are containers (but filter out the exec plugin container). So user could select directly from the command palette the terminal to open:
    - [x]  Filter out the exec plugin containers from terminal commands: depends on https://github.com/eclipse/che/issues/11804 - 1d 
    - [ ] Apply ability filter user containers from among others https://github.com/eclipse/che/issues/11804 need for `Minimal set of Theia terminal improvements for Che 7` goal - pull under review

## Other  issues:
- [ ] [Theia] Cannot create project by Yeoman wizard https://github.com/eclipse/che/issues/12315 - 2d
- [ ] Investigate how to synchronise Theia global preferences between Che workspaces  https://github.com/eclipse/che/issues/12442 - 3d
- [ ] Bug with an empty containers tree  https://github.com/eclipse/che-theia/issues/25 - 3d
- [ ] [plug-in] Implement onWillSaveTextDocument event  https://github.com/theia-ide/theia/issues/4009 L&T team ask for it - 5d
- [x] Open link vscode command doesn't work https://github.com/theia-ide/theia/issues/3936 merge pull
- [ ] Factory for dashboard dev environment https://github.com/eclipse/che/issues/12228 - 5d

## Unplanned tasks
- [x] Move theia and theia-dev docker files in to che-theia repository https://github.com/eclipse/che/issues/12458 
- [x] che-theia-terminal extension is broken with latest theia https://github.com/eclipse/che-theia/issues/29
- [x]  Add machine token to request to exec sidecar clients https://github.com/eclipse/che/issues/12573

## Pending PR
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [x] [plug-in] Implement inspect configuration https://github.com/theia-ide/theia/issues/2289 (depends on https://github.com/theia-ide/theia/pull/3247)

## Technical debts 
(_some time in sprint is allocated to handle those issues_ )
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871
- [ ] Move all che-theia related extensions/plugins in che-theia repository https://github.com/eclipse/che/issues/12306 IDE2 team part
- [ ] Workspace is restarted after start interruption https://github.com/eclipse/che/issues/11077
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [x] Project view is broken if Theia is used as IDE in a workspace https://github.com/eclipse/che/issues/10915
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [ ] Che-theia loader undefined https://github.com/eclipse/che/issues/11773
- [x] Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state. https://github.com/eclipse/che/issues/11893
- [ ] Make it possible to specify path for command execution in it's configuration https://github.com/eclipse/che/issues/11866 15sp (needed for devfile - for platform team)
- [ ] Add image with debugger to speed up development https://github.com/eclipse/che-machine-exec/issues/12

**Total planned = [todo]sp**

### Next sprint proposals
- [ ] support yarn workspaces https://github.com/eclipse/theia-plugin-packager/issues/3 
- [ ] Make Theia plugin state and workspace state persistent https://github.com/eclipse/che/issues/12260
- [ ] Add the needed methods for Webview API https://github.com/theia-ide/theia/issues/3896 4d
- [ ] mocking plugin API [TODO issue] 40sp
- [x] Move latest che-machine-exec to the eclipse repo https://github.com/eclipse/che-machine-exec/issues/13 3d
- [ ] Ability to define another list of extensions when invoking che:theia init https://github.com/ws-skeleton/che-theia-generator/issues/7
- [ ] che:theia clean https://github.com/ws-skeleton/che-theia-generator/issues/8
- [ ] [Che 7] Cannot add new env variable, server or volume to Che 7 stack https://github.com/eclipse/che/issues/12337
- [ ] Improvements for containers plugin https://github.com/eclipse/che-theia/issues/21  - 4d
- [ ] Container plugin view displays each time after page refresh https://github.com/eclipse/che-theia/issues/22
- [ ] Add ability to import project with sparse checkout feature https://github.com/eclipse/che-theia/issues/33

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1dAZXwIHpROBoRDBT5gUHfgDXZPh-PMl5UkcTe15iioU/edit)
