### ISSUE TITLE
IDE-2019-02-05 (Sprint: 161) 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12379]
#### Sprint goals
- [ ] Rework Theia Task extension to Task plugin #11458
- [x] [Theia][Plugin] Add TaskRunner API #11954 
- [ ] Include existing GitHub plugin in Che Theia IDE #11867
- [ ] [plug-in] API for register a filesystem provider https://github.com/theia-ide/theia/issues/2861
- [ ] Move all che-theia related extensions/plugins in che-theia repository #12306
- [ ] [plug-in] Implement 'vscode.previewHtml' VS Code Built-in Command https://github.com/theia-ide/theia/issues/4051
- [ ] [plug-in] Implement 'vscode.diff' VS Code Built-in Command https://github.com/theia-ide/theia/issues/4052
- [ ] [plug-in] Ability to get current selection in the explorer view https://github.com/theia-ide/theia/issues/4043
- [x] [plug-in][tasks] Add tasks.onDidEndTask API https://github.com/theia-ide/theia/issues/3931
- [ ] support vscode scm api https://github.com/theia-ide/theia/issues/4103

#### Bugs
- [x] Wrong behavior in the editor when perform git pull after delete files #11648
- [x] Cannot add ZIP as Project #12359
- [ ] IDE crashes after importing Sample Projects #12382
- [x] Navigating to `ide` link provided by workspace API does not open Theia IDE in Che 7 #12376 
- [x] [plug-in] Fix 'onDidSelectItem' behavior for Quick Pick widget https://github.com/theia-ide/theia/issues/4046

### Merge-ready PRs  
- [ ] Che Server rejects JSON RPC messages which may lead to losing events #11961

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 11 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
