### ISSUE TITLE
Platform-2019-02-05 (Sprint: 161)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12371]
### Features related to Devfile
- [x]  Introduce selector field for Kubernetes/OpenShift tools in Devfile | https://github.com/eclipse/che/issues/12361 13 

### Features related to Plugin Registry

- [ ] Integrate plugin-viewer | https://github.com/eclipse/che/issues/12373 | 8
- [x] Implement mountSources boolean attribute in che-plugin.yaml | https://github.com/eclipse/che/issues/12510 | 8

### Technical debts and bugs
- [x] Investigate possible ways of adaptation of Resource API to sidecars machines https://github.com/eclipse/che/issues/12334 | 8

### Finalize issues started in the previous sprint.
- [ ] Handle more metadatas for the plugin viewer | https://github.com/eclipse/che-plugin-registry/issues/71 | 3
- [x] Devfile Spec documentation generator | https://github.com/eclipse/che/issues/12272 | 8
- [x] Support Kubernetes PVCs in recipes and resolves them as Che Volume. Note that PVCs strategies should be supported as well | https://github.com/eclipse/che/issues/12269 | 5
- [x] Refresh workspace activity during runtime restore on workspace master startup | https://github.com/eclipse/che/issues/12225 | 8

### Unplanned
- [x] Import/Create project does not work on docker platform https://github.com/eclipse/che/issues/12463
- [x] [per-workspace PVC strategy] - When deleting workspace, PVC is not deleted, nor cleaned up https://github.com/eclipse/che/issues/12521
- [x] Starting workspace when using "per-workspace" PVC strategy not working properly https://github.com/eclipse/che/issues/12520
- [x] Change Che master Java from JRE to JDK https://github.com/eclipse/che/issues/11872 
- [ ]  [Devfile] Support commands for Os/K8s tool  https://github.com/eclipse/che/issues/12479
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Lukas Krejci | 15d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 64  | 53 |
