### ISSUE TITLE
QE-2018-02-05 (Sprint: 161)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#12390]
### Sprint goals
- Setup QA process for Che7

### Issues tied to objectives
- [ ] Selenium: Refactoring selenium tests from the 'dashboard' package #12328 2sp
- [x] Selenium: Refactor selenium tests from the 'miscellaneous' package #12356 2sp
- [ ] Implement first component UI cypress test #12457 8sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 12 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 4 |
|Radim Hopp | 10 |
| Total |  61 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 12 | 2 |
