### ISSUE TITLE
Plugin Brokers Improvements - part 2

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12398]
### Description

- [ ] Cache brokering results as a base64 attribute in the workspace defintions
- [ ] Allow brokers to run as Deployments that serves all workspaces rather than workspace specific Jobs
- [ ] Split brokers in 2 parts: independent service (retrieve and process plugin metadata) and init container (prepare the sidecar container to run the plugin)

This is #11980 second part. These tasks are not in Che 7 scope.

**Comment by l0rd** [comment]
Superseded by #14494
