### ISSUE TITLE
Update Development Workflow Documentation for Che 7

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12411]
### Description

This issue is to plan and track the updates to the [Development Workflow in the Wiki ](https://github.com/eclipse/che/wiki/Development-Workflow) required for Che 7 (Docker support will be dropped and plugins development changes significantly). 

- [ ] Deploy Che using local assembly (mounting repo folder):
    - [ ] Provide manual instructions to deploy Che using local assembly for minikube and minishift
    - [ ] Implement new **chectl** `server:start` options:
        - [ ] `--mount-repo=<path-to-repo> : Deploy Che and mount local assembly`
        - [ ] `--mount-data=<local-path> : Deploy Che and mount the given path as the server data folder`
- [ ] Remote Plugin Development:
    - [ ] Provide manual instructions to start/stop a local/osio plugin registry
    - [ ] Provide manual instructions to locally deploy a remote Theia extension
    - [ ] Provide manual instructions to locally deploy a remote VS Code extension
    - [ ] Provide manual instructions to locally deploy a remote Che plugin
    - [ ] Implement new **chectl** commands:
        - [ ] `plugin:start-registry : Start a local Che plugin registry`
        - [ ] `plugin:stop-registry : Stop the local Che plugin registry`
        - [ ] `plugin:publish --che-plugin=<che-plugin-yaml-path> : Build tar.gz and publish the plugin definition to a local registry`
        - [ ] `plugin:publish --theia-file=<theia-file-path> --sidecar-container=<container-image> : Generate che-plugin.yaml, build tar.gz and publish the plugin definition to a local registry`
        - [ ] `plugin:publish --vsx-file=<vsx-file-path> --sidecar-container=<container-image> : Generate che-plugin.yaml, build tar.gz and publish the plugin definition to a local registry`
        - [ ] `plugin:release --local-repo-path=<path-to-github-repo> : Create a new GitHub release and open a PR to update the plugin definition in eclipse/che-plugin-registry repository `
        - [ ] `workspace:update --rollout : Restart the workspace pods`
- [ ] Update Development Workflow in the wiki
    - [ ] Update dependencies (add chectl + minikube or minishift)
    - [ ] Clone and build don't change
    - [ ] To run Che a dev should use chectl instead of docker run
    - [ ] Add a new section for Che 7 plugins development:
       - [ ] link to VSCode Extensions documentation
       - [ ] link to Theia Plugins documentation
       - [ ] Document the development workflow:
            1. Build locally or download existing theia plugin/vscode plugin
            2. Write sidecar container Dockerfile and build / push to registry
            3. [Optional] Write che-plugin.yaml and build the tar.gz file
            4. Start local/osio registry and publish che-plugin.yaml
            5. Test in local workspace and inner loop (update plugin or image / publish plugin or push image / update workspace)
            6. Release the plugin and update Che Plugin Registry repository

**Comment by slemeur** [comment]
cc @slemeur

**Comment by sushmithakumar** [comment]
one thing I have noted when used docker image 6.13.0 che-server gives .the terminal in kubernetes cluster .the terminal becomes inactive if not used for 5 sec or more ..what can be the reason behind it?

**Comment by sushmithakumar** [comment]
I don't see the same behavior of the terminal when used open source codenvy for eclipse che

**Comment by l0rd** [comment]
@sushmithakumar your comments don't look related to this issue
