### ISSUE TITLE
Languages Sprint 161 (L-3)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12427]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 10 | 6 | 5d
@tolusha | 15 | 10 | 10.5
@svor | 15 | 10 | 12d
@vrubezhny | 15 | 10 | 9d

# Candidate Issues 
- [x] Describe process for making and testing Che 7 plugin from vscode plugin #12447 0.5d @tolusha 
- [ ] Golang plugin https://github.com/eclipse/che/issues/12145 3d (@tolusha)
- [ ] CallHierarchyService Plugin API https://github.com/theia-ide/theia/issues/3765 3d (@vrubezhny )
- [ ] Java Language Plugin https://github.com/theia-ide/theia/issues/3778 (@svor) 1d
- [ ] Che 7 plugin: vscode-java #12436 3d (@svor)
- [ ] Che 7 plugin: vscode-java-debug #12446 (6d stretch) @svor 
- [ ] Typescript Language Plugin https://github.com/theia-ide/theia/issues/3767 (4d) @tolusha 
- [ ] Che 7 plugin: Typescript language support #12408
- [ ] Yaml plugin https://github.com/eclipse/che/issues/12142 (@JPinkney)
- [ ] Support VS Code XML Tooling https://github.com/theia-ide/theia/issues/3317 3d @vrubezhny 
- [ ] Che 7 plugin: vscode-xml #12437 2d
- [ ] Che 7 plugin: vscode-yaml #12438 2d
- [ ] workspace/didChangeConfiguration not sending correct params to YAML language server when deployed by plugin ID https://github.com/theia-ide/theia/issues/3892 3d (@tsmaeder )
- [ ] Add Theia Plugin APIs to support VS Code XML Tooling https://github.com/eclipse/che/issues/11775 (3d) (@vrubezhny)
- [x] Code lens feature doesn't work correctly https://github.com/theia-ide/theia/issues/3946 2d (@svor)
- [x] Go to definition doesn't work https://github.com/theia-ide/theia/issues/4044 3d (@tolusha )
- [ ] Diagnostics are not represented in Problem view https://github.com/theia-ide/theia/issues/4097 (2d) @tsmaeder 
# Open VS Code API problems
- [x] *Commands API is not implemented clearly https://github.com/theia-ide/theia/issues/3968
- [ ] Can not execute show references command https://github.com/theia-ide/theia/issues/4084 
- [ ] (IDE2 team) Implement onWillSaveTextDocument event https://github.com/theia-ide/theia/issues/4009 
- [x] (anton?) Progress bar doesn't work correctly with plugins https://github.com/theia-ide/theia/issues/4027 
- [x] Register setContext command https://github.com/theia-ide/theia/issues/4053 
- [x] Apply code action does not work https://github.com/theia-ide/theia/issues/4081
- [ ] Plugin as sidecar initialization fails when browser is refreshed https://github.com/theia-ide/theia/issues/3970 
- [ ] `workspace.onDidRenameFile` `workspace.onWillRenameFile` implementations are missed https://github.com/theia-ide/theia/issues/4167
- [ ] Run/Debug code lenses don't work https://github.com/theia-ide/theia/issues/4188

# Unplanned Issues

# Open PR's 
- [ ] Diagnostics are not represented in Problem view #4097 https://github.com/theia-ide/theia/pull/4178
- [ ] https://github.com/theia-ide/theia/pull/2461 2d
- [ ] https://github.com/eclipse/che-theia-java-plugin/pull/12
- [x] Detect Simple Java Projects on Import #12041 (2d)

Previous Sprint: https://github.com/eclipse/che/issues/12352
