### ISSUE TITLE
IDE2-2019-02-26 (Sprint: 162)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12551]
### Sprint Goals:
1. Support L&T team on Theia Plugin API
2. Fix critical technical deps
3. Show a warning when starting an ephemeral workspace
4. Define and Document how to develop Che Theia with Che - Beta
5. Rework Terminal extension to a plug-in - GA

Che 7 Beta Epic - https://github.com/eclipse/che/issues/12170

Next Goals - Che 7 GA: 
-  Implement flow to install a plugin from the IDE - GA
   - Extending Eclipse Che - GA
   - Extending How-to: How to provide a "custom IDE" based on Eclipse Theia - GA
   - Extensibility Reference - GA

## 1. Support L&T team on Theia Plugin API
- [x] Several extensions are broken with latest Theia https://github.com/eclipse/che-theia/issues/37
- [x] Update Theia image to the newer version (for example 0.3.19) https://github.com/eclipse/che-theia/issues/39
- [x] [plug-in] Implement onWillSaveTextDocument event  https://github.com/theia-ide/theia/issues/4009 L&T team ask for it - 5d
- [ ] [plug-in][debug]Run/Debug code lenses don't work https://github.com/theia-ide/theia/issues/4188 5d
- [ ] Doc: Define and document the flow how to develop remote plugins with a che7 dev environment https://github.com/eclipse/che/issues/12604 5d

## 2. Fix critical technical deps 
- [x] che-theia: factory, theia plugins are not loaded sometimes https://github.com/eclipse/che/issues/12581 P1 8d
- [x] Broken CI https://github.com/eclipse/che-machine-exec/issues/18 2d
- [ ] Build and package che-theia plugins during che-theia image build.  https://github.com/eclipse/che-theia/issues/45 8d
- [ ] Loader.js should execute authentication promise only after successful execution of check server promise https://github.com/eclipse/che/issues/12574 - OSIO team wants get fix ASAP 1d
- [x] [plug-in] TreeView should be created on registering a TreeDataProvider https://github.com/theia-ide/theia/issues/3907 4d

## 3. Show a warning when starting an ephemeral workspace
- [ ] Show a warning when starting an ephemeral workspace https://github.com/eclipse/che/issues/12565 5d

## 4. Define and Document how to develop Che Theia with Che - Beta
- [ ] Write documentation on how to 'Creating Eclipse Theia Plug-ins with Eclipse Che'  https://github.com/eclipse/che/issues/12425  - 1 sprint
- [ ] Update the readme.MD and customizing.MD with the new information about Che-in-Che https://github.com/eclipse/che/issues/12426 - 1 sprint

## 5. Rework Terminal extension to a plug-in - GA 
- [ ] Split Theia terminal widget logic https://github.com/eclipse/che/issues/12609 10d

## Other  issues:
- [x] [Theia] Cannot create project by Yeoman wizard https://github.com/eclipse/che/issues/12315 - 2d
- [x] Investigate how to synchronise Theia global preferences between Che workspaces  https://github.com/eclipse/che/issues/12442 - 3d
- [x] Bug with an empty containers tree  https://github.com/eclipse/che-theia/issues/25 - 3d
- [ ] Factory for dashboard dev environment https://github.com/eclipse/che/issues/12228 - 5d
- [ ] Logged out while working in IDE  https://github.com/eclipse/che/issues/12099 - to investigate/address to platform team - 3d for investigation 
- [ ] Che-theia: progress in status bar when performing any git clone (factory, workspace sync, git clone command) https://github.com/eclipse/che/issues/12564 5d

## Pending PR
- [x] Display only containers defined with recipe source https://github.com/eclipse/che-theia/pull/49
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045

## Technical debts 
(_some time in sprint is allocated to handle those issues_ )
- [ ] [plug-in] window.onDidChangeActiveTextEditor is not fired https://github.com/theia-ide/theia/issues/4218
- [ ] [plug-in] window.onDidChangeVisibleTextEditors event contains wrong amount of editors https://github.com/theia-ide/theia/issues/4221
- [x] [plug-in] window.onDidOpenTerminal is not implemented https://github.com/theia-ide/theia/issues/4222
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871
- [ ] Move all che-theia related extensions/plugins in che-theia repository https://github.com/eclipse/che/issues/12306 IDE2 team part
- [ ] Workspace is restarted after start interruption https://github.com/eclipse/che/issues/11077
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [ ] Che-theia loader undefined https://github.com/eclipse/che/issues/11773
- [ ] Make it possible to specify path for command execution in it's configuration https://github.com/eclipse/che/issues/11866 15sp (needed for devfile - for platform team)
- [ ] Add image with debugger to speed up development https://github.com/eclipse/che-machine-exec/issues/12
- [ ] Users inconsistance when run nodejs script https://github.com/eclipse/che-theia/issues/60

**Total planned = [todo]sp**

### Next sprint proposals
- [ ] Make Theia plugin state and workspace state persistent https://github.com/eclipse/che/issues/12260
- [ ] Add the needed methods for Webview API https://github.com/theia-ide/theia/issues/3896 4d
- [ ] mocking plugin API [TODO issue] 40sp
- [x] Ability to define another list of extensions when invoking che:theia init https://github.com/ws-skeleton/che-theia-generator/issues/7
- [x] che:theia clean https://github.com/ws-skeleton/che-theia-generator/issues/8
- [x] [Che 7] Cannot add new env variable, server or volume to Che 7 stack https://github.com/eclipse/che/issues/12337
- [ ] Improvements for containers plugin https://github.com/eclipse/che-theia/issues/21  - 4d
- [ ] Container plugin view displays each time after page refresh https://github.com/eclipse/che-theia/issues/22
- [ ] Add ability to import project with sparse checkout feature https://github.com/eclipse/che-theia/issues/33
- [] https://github.com/eclipse/che-machine-exec/issues/20

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1KdnaKPOhjFJ-BmRa0Z61VBrKsxZmXRg-hwyILdMXAH8/edit)
