### ISSUE TITLE
Platform-2019-02-26 (Sprint: 162)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12571]
### Features related to Devfile
- [x] Publish Devfile documentation on http://redhat-developer.github.io/devfile | https://github.com/eclipse/che/issues/12524 | 8
- [x] Study/Devfile: proper object hierarchy for tools in the schema and java model | https://github.com/eclipse/che/issues/12587 | 5
- [x] Support reassigning of env variables in che-plugin.yaml | https://github.com/eclipse/che/issues/12577 | 8
- [x] Add support of dockerimage tool in Devfile | https://github.com/eclipse/che/issues/12389 | 8

### Other tasks

- [x] [Tracing] Provide more context information about workspace related operation. | https://github.com/eclipse/che/issues/12533 | 5
- [ ]  Study how to fix issue: Command in Runtime updated only after restarting workspace | https://github.com/eclipse/che/issues/12588 | 8

### Finalize issues started in the previous sprint.
- [x] [Devfile] Support commands for Os/K8s tool | https://github.com/eclipse/che/issues/12479 | 5
- [x] Handle more metadatas for the plugin viewer | https://github.com/eclipse/che-plugin-registry/issues/71 | 3
- [x]  Che Server rejects JSON RPC messages which may lead to losing events Impediments: | https://github.com/eclipse/che/issues/11961 | 5

### Unplanned
- [x] Workspace stopping by idle timeout does not work on multiuser docker and openshift https://github.com/eclipse/che/issues/12636 
- [x] Refactor DevfileConverter https://github.com/eclipse/che/issues/12659
- [x] Make it possible for ApiInfoService to get project version from property https://github.com/eclipse/che/issues/12686
- [x] Try to use https://github.com/leadpony/justify as an devfile schema validator 
 https://github.com/eclipse/che/issues/12714
- [x] Improve JSON schema validation messages by looking into nested errors https://github.com/eclipse/che/issues/12694 
- [ ] Add an ability to specify entrypoint for dockerimage tool in Devfile  https://github.com/eclipse/che/issues/12668

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 13d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 14d | 
| Lukas Krejci | 10d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 55  | 47 |
