### ISSUE TITLE
IDE-2019-02-26 (Sprint: 162)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12591]
### Sprint goals

1. Add needed VS Code API for finalizing Kubernetes Plugin Support 
2. Rework Theia Task extension to Task plugin
3. Include existing GitHub PullRequest  plugin in Che Theia IDE

### Sprint details:
_**Che 7 Beta Epic - #12170**_ 

#### 1. Add needed VS Code API for finalizing Kubernetes Plugin Support
- [x] [plug-in] Implement 'vscode.previewHtml' VS Code Built-in Command https://github.com/theia-ide/theia/issues/4051
- [x] [plug-in] Implement 'vscode.diff' VS Code Built-in Command https://github.com/theia-ide/theia/issues/4052
- [ ] [plug-in] API for register a filesystem provider https://github.com/theia-ide/theia/issues/2861

#### 2. Rework Theia Task extension to Task plugin (#11458)
- [ ] [plug-in] Ability to get current selection in the explorer view https://github.com/theia-ide/theia/issues/4043
- [x] [plug-in] Ability to specify container for webview panel [theia-ide/theia#4257](https://github.com/theia-ide/theia/issues/4257)
- [x] [plug-in] [tasks] Add 'tasks.taskExecutions' API theia-ide/theia#4372
- [x] Che tasks are not returned by task manager eclipse/che-theia#76

#### 3. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [ ] support vscode scm api https://github.com/theia-ide/theia/issues/4103
- [ ] support scm menu contributions https://github.com/theia-ide/theia/issues/4171
- [ ] [plug-in] VS Code Git extensions #4266

#### Other tasks:
- [ ] Move all che-theia related extensions/plugins in che-theia repository #12306

#### Merge-ready PRs  
- [ ] Che Server rejects JSON RPC messages which may lead to losing events #11961
- [x] Navigating to `ide` link provided by workspace API does not open Theia IDE in Che 7 #12376 

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
### Retrospective Comments
