### ISSUE TITLE
Sprint 162 (L-4)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12635]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 5 | 3| 3.5
@tolusha | 12 | 7 | 4.5 d
@svor | 12 | 7 | 5.5
@vrubezhny | 12 | 7 | 7

# Candidate Issues 
- [x] Che 7 plugin: vscode-java #12436 (3d) (@svor)
- [ ] Che 7 plugin: vscode-java-debug #12446 (1d) (@svor)
- [x] Che 7 plugin: Typescript language support #12408 1d (@tolusha)
- [x] Che 7 plugin: Node https://github.com/eclipse/che/issues/12409 (@tolusha)
- [x] Yaml plugin https://github.com/eclipse/che/issues/12142 (@JPinkney)
- [x] Support VS Code XML Tooling https://github.com/theia-ide/theia/issues/3317 1d @vrubezhny 
- [x] Che 7 plugin: vscode-xml #12437 3d (@vrubezhny)
- [x] Che 7 plugin: vscode-yaml #12438 2d (@JPinkney)
- [x] Remove JDK and Java LS extension (and java debug) from Che-Theia https://github.com/eclipse/che-theia/issues/55 (0.5) (@svor)
- [ ] support vscode task contribution points https://github.com/theia-ide/theia/issues/4211 (@tolusha) 3d
- [ ] Remove typescript from che-theia (0.5) (@tolusha)
- [x] Cannot read property 'hasOwnProperty' of undefined https://github.com/theia-ide/theia/issues/4254 (1d)
@svor
- [ ] Duplicate hovers in vscode-camel https://github.com/theia-ide/theia/issues/4181 @tolusha  (2d)
- [x] Can not execute show references command https://github.com/theia-ide/theia/issues/4084 (3d) (@tsmaeder)
- [ ] workspace.onDidRenameFile and workspace.onWillRenameFile https://github.com/theia-ide/theia/issues/4167 (4d) @vrubezhny 

# Unplanned Issues
- [ ] CallHierarchyService Plugin API https://github.com/theia-ide/theia/issues/3765 3d (@vrubezhny )
- [x] Pending CQ: Golang plugin https://github.com/eclipse/che/issues/12145 3d (@tolusha)

# Open PR's 
- [x] Diagnostics are not represented in Problem view https://github.com/theia-ide/theia/issues/4097 https://github.com/theia-ide/theia/pull/4178
- [ ] https://github.com/theia-ide/theia/pull/2461 2d
- [ ] https://github.com/eclipse/che-theia-java-plugin/pull/12

Previous Sprint: https://github.com/eclipse/che/issues/12427

**Comment by tolusha** [comment]
https://github.com/eclipse/che/issues/12170
