### ISSUE TITLE
IDE2-2019-03-19 (Sprint: 163)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#12705]
### Sprint Goals:
1. Support L&T team on Theia Plugin API
2. Fix critical technical deps
3. Rework Terminal extension to a plug-in - GA
4. Define and Document how to develop Che Theia with Che - Beta

Che 7 Beta Epic - https://github.com/eclipse/che/issues/12170

Next Goals - Che 7 GA: 
-  Implement flow to install a plugin from the IDE - GA

- Documentation for GA:
   - Extending Eclipse Che - GA
   - Extending How-to: How to provide a "custom IDE" based on Eclipse Theia - GA
   - Extensibility Reference - GA

## 1. Support L&T team on Theia Plugin API
- [ ] [plug-in][debug]Run/Debug code lenses don't work https://github.com/theia-ide/theia/issues/4188 3d
- [ ] Doc: Define and document the flow how to develop remote plugins with a che7 dev environment https://github.com/eclipse/che/issues/12604 1d
  - [ ] Develop discovery mechanism for launching remote plugins https://github.com/eclipse/che/issues/12721 4d

## 2. Fix critical technical deps 
- [ ] Build and package che-theia plugins during che-theia image build.  https://github.com/eclipse/che-theia/issues/45 6d
- [x] Loader.js should execute authentication promise only after successful execution of check server promise https://github.com/eclipse/che/issues/12574 - OSIO team wants get fix ASAP 1d
- [x] Workspace is restarted after start interruption https://github.com/eclipse/che/issues/11077 2d
- [ ] Add the needed methods for Webview API https://github.com/theia-ide/theia/issues/3896 4d
- [x] Revisit name of docker images  https://github.com/eclipse/che-theia/issues/63 2d
- [x] Output channel doesn't work without timeout https://github.com/theia-ide/theia/issues/4155 3d
- [x] hosted plugin leaking json rpc proxy factories https://github.com/theia-ide/theia/issues/3523 5d
- [x] [plug-in] window.onDidChangeActiveTextEditor is not fired https://github.com/theia-ide/theia/issues/4218 3d
- [x] [plug-in] window.onDidChangeVisibleTextEditors event contains wrong amount of editors https://github.com/theia-ide/theia/issues/4221 3d

## 3. Rework Terminal extension to a plug-in - GA 
- [ ] Split Theia terminal widget logic https://github.com/eclipse/che/issues/12609 4d
- [ ] TODO create sub issue for https://github.com/eclipse/che/issues/11442 - 10d

## 4. Define and Document how to develop Che Theia with Che - Beta
- [ ] Write documentation on how to 'Creating Eclipse Theia Plug-ins with Eclipse Che'  https://github.com/eclipse/che/issues/12425 
- [ ] Update the readme.MD and customizing.MD with the new information about Che-in-Che https://github.com/eclipse/che/issues/12426

## Other  issues:
- [ ] Make it possible to specify path for command execution in it's configuration https://github.com/eclipse/che/issues/11866 5d (needed for devfile - for platform team)
- [ ] Start a workspace from a devfile located in a workspace. https://github.com/eclipse/che/issues/12707 6d
- [x] Logged out while working in IDE  https://github.com/eclipse/che/issues/12099 - to investigate/address to platform team - 3d for investigation 
- [ ] Che-theia: progress in status bar when performing any git clone (factory, workspace sync, git clone command) https://github.com/eclipse/che/issues/12564 3d
- [x] Improvements for containers plugin https://github.com/eclipse/che-theia/issues/21  - 4d
- [ ] Terminal client connection fail. https://github.com/eclipse/che-machine-exec/issues/20 5d
- [x] Show a warning when starting an ephemeral workspace https://github.com/eclipse/che/issues/12565 2d
- [ ] TreeView widget improvements https://github.com/theia-ide/theia/issues/4386 5d

## Pending PR
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [x] Factory for dashboard dev environment https://github.com/eclipse/che/issues/12228  - https://github.com/eclipse/che/pull/12757

## Technical debts 
(_some time in sprint is allocated to handle those issues_ )
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871
- [ ] Move all che-theia related extensions/plugins in che-theia repository https://github.com/eclipse/che/issues/12306 IDE2 team part
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [x] Che-theia loader undefined https://github.com/eclipse/che/issues/11773
- [ ] Add image with debugger to speed up development https://github.com/eclipse/che-machine-exec/issues/12
- [ ] Users inconsistance when run nodejs script https://github.com/eclipse/che-theia/issues/60

**Total planned = [todo]sp**

### Next sprint proposals
- [ ] Sharing from the IDE https://github.com/eclipse/che/issues/12722
- [ ] Show the progress of installing a plugin  https://github.com/theia-ide/theia/issues/3632
- [ ] Mark plugin logs with plugin name https://github.com/theia-ide/theia/issues/2458
- [ ] Make Theia plugin state and workspace state persistent https://github.com/eclipse/che/issues/12260
- [ ] mocking plugin API [TODO issue] 40sp
- [ ] Add ability to import project with sparse checkout feature https://github.com/eclipse/che-theia/issues/33
- [x] Could the Dashboard support a parameterized version string? https://github.com/eclipse/che/issues/12664

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun |  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |  |
| **Total Budget** | ** ** |

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1uRJl-idkO6y4HztZjCqvI1lke0YuRa3At-VwfCMUqEc/edit?usp=sharing)
