### ISSUE TITLE
Integrate Che7-compatible workspace telemetry, and extend it to meet Upstream Che needs

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#12717]
### Description

Che 7-compatible telemetry (as initially implemented for downstream RhChe) should be integrated into upstream Che, and extended to meet additional needs of the various upstream Che telemetry use cases, as mentioned in the corresponding brief.
Additional feature should include:
-  the ability to globally enable / disable a given telemetry backend (docker image) on all users by default
- the ability to opt in / opt out from telemetry per-user (with a way to get the current number / proportion of users that are currently in or out)
- the ability to register new event types (with related properties) for plugins to contribute their own telemetry events, but in away that would still make it easy to check for consistency, avoiding various plugins to register colliding events,
- the ability to get the list of currently available event types with their properties 
- a default configurable telemetry backend based on Google Analytics that would be compatible with Eclipse telemetry policy.

Related rh-che issues:
- [ ] Provide more detailed documentation about Che telemetry implementation https://github.com/redhat-developer/rh-che/issues/914
- [x] Investigate complexity of enabling telemetry support in Che 7 and create list of sub-taks https://github.com/redhat-developer/rh-che/issues/1154
- [x] Prepare the telemetry Che support for the Theia switch https://github.com/redhat-developer/rh-che/issues/690
- [x] Migrate the Woopra telemetry main component in a dedicated service for Che 7 https://github.com/redhat-developer/rh-che/issues/1229
- [ ] Telemetry Events for che.openshift.io https://github.com/redhat-developer/rh-che/issues/765
