### ISSUE TITLE
IDE-2019-03-19 (Sprint: 163)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12730]
### Sprint goals

1. Add needed VS Code API for finalizing Kubernetes Plugin Support 
2. Rework Theia Task extension to Task plugin
3. Include existing GitHub PullRequest  plugin in Che Theia IDE
4. Che commands should be first class citizens in Theia

### Sprint details:
_**Che 7 Beta Epic - #12170**_ 

#### 1. Add needed VS Code API for finalizing Kubernetes Plugin Support
- [x] [plug-in] API for register a filesystem provider https://github.com/theia-ide/theia/issues/2861
- [x] Command "Kubernetes: Delete Context" of Kubernetes Tolling don't work in Theia #12745
- [x] Command "Kubernetes: Set Kubeconfig" of Kubernetes Tolling don't work in Theia #12746
- [x] Kubernetes: Diff command from VSCode Kubernetes extension doesn't work in Theia #12747

#### 2. Rework Theia Task extension to Task plugin (#11458)
- [x] [plug-in] Ability to get current selection in the explorer view https://github.com/theia-ide/theia/issues/4043

#### 3. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [ ] support vscode scm api https://github.com/theia-ide/theia/issues/4103
- [ ] support scm menu contributions https://github.com/theia-ide/theia/issues/4171
- [ ] [plug-in] VS Code Git extensions https://github.com/theia-ide/theia/issues/4266

#### 4. Che commands should be first class citizens in Theia #12709
- [ ] User defined Che tasks commands should be exported in a tasks.json file #12712 

#### Other tasks:
- [ ] Move all che-theia related extensions/plugins in che-theia repository #12306
     - che-theia-emacs-plugin https://github.com/eclipse/che-theia-emacs-plugin empty repo
     - che-theia-vi-plugin https://github.com/eclipse/che-theia-vi-plugin empty repo
- [x] [Plug-in] workspace.findFiles not working as expected https://github.com/theia-ide/theia/issues/4323

#### Bugs
- [x] Direct workspace URL doesn't open IDE #12830

#### Merge-ready PRs  
- [x] Theia - SSH Plug-in https://github.com/eclipse/che-theia-ssh-plugin https://github.com/eclipse/che-theia/pull/31

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
### Retrospective Comments
