### ISSUE TITLE
Languages Sprint 163 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12759]
# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 8 | 5 | 5
@tolusha | 13 | 7 | 7
@svor | 13 | 7 | 9
@vrubezhny | 13 | 8 | 9

# Candidate Issues
- [ ] Che 7 Plugin: Python https://github.com/eclipse/che/issues/12771 @tolusha 2d
- [x] Python VS Code extension https://github.com/theia-ide/theia/issues/3771 @tolusha 3d
- [ ] PHP Language Support https://github.com/eclipse/che/issues/12772
  - [x] Investigate PHP VS Code extensions #12796 @vrubezhny 2d
  - [ ] Che 7 plugin: PHP Language Server #12797 @vrubezhny 5d
  - [ ] Che 7 plugin: PHP Debugger #12795
- [ ] C# LS and Debugger as plug-in https://github.com/eclipse/che/issues/12773 
  - [x] Investigate MS C# Plugin Capabilities #12794 2d
  - [x] Theia plugin: .Net Debugger #12790
  - [x] Theia plugin: C# #12791 @svor 7d
  - [ ] Che 7 plugin: C# #12792 
  - [ ] Che 7 plugin: .Net debugger #12793
- [ ] Find a Home for repackaged VS Code extensions https://github.com/eclipse/che/issues/12774
- [ ] Don't use Monaco Concepts in Main/Ext Interface https://github.com/theia-ide/theia/issues/4355 @tmader 5d
- [ ] Duplicate hovers in vscode-camel https://github.com/theia-ide/theia/issues/4181 @tolusha  (2d)
# From Last Sprint
- [x] workspace.onDidRenameFile and workspace.onWillRenameFile https://github.com/theia-ide/theia/issues/4167 (2d) @vrubezhny 
- [ ] ~~support vscode task contribution points https://github.com/theia-ide/theia/issues/4211 3d~~ https://github.com/theia-ide/theia/issues/4211#issuecomment-469646126

# Blocked issues 
- [ ] Che 7 plugin: vscode-java-debug #12446 (1d) (@svor)
# Unplanned Issues
# Open PR's

Previous Sprint: https://github.com/eclipse/che/issues/12635
