### ISSUE TITLE
Platform-2019-03-19 (Sprint: 163)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12766]
### Features related to Devfile

- [x] Add an ability to specify entrypoint for dockerimage tool in Devfile | https://github.com/eclipse/che/issues/12668 | 3
- [x] Devfile on-boarding and learning experience | https://github.com/eclipse/che/issues/12732 | 8
- [ ] Add an ability to specify entrypoint for kube and openshift tool in Devfile | https://github.com/eclipse/che/issues/12693 | 8
- [ ] Inform users about what devifle was used to create a workspace with the factory | https://github.com/eclipse/che/issues/12741 | 8
- [ ] Support devfile with more than one Kubernetes tool | https://github.com/eclipse/che/issues/12719 | 13

### Features related to Monitoring/Tracing

- [ ] Create documentation for monitoring use-case | https://github.com/eclipse/che/issues/12543 8sp
- [x] [Metric] Provide a successfully started workspaces ratio |https://github.com/eclipse/che/issues/12723  5
- [x] Propagate traces as Prometheus metrics | https://github.com/eclipse/che/issues/12697 | 5

### Finalize issues started in the previous sprint.
- [x]  Che Server rejects JSON RPC messages which may lead to losing events Impediments: | https://github.com/eclipse/che/issues/11961 | 5
- [x] Support resolving referenced files when building a factory from a link to raw content of the devfile 
 https://github.com/eclipse/che/issues/12798
- [ ] Update Devfile diagrams https://github.com/redhat-developer/devfile/issues/8
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Lukas Krejci | 15d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 58  | 21 |
