### ISSUE TITLE
Che 7 plugin: PHP Language Support

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12772]
Since the VS Code built-in plugins are very basic we should go with https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense and https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug
In case the one from felix is not to our liking, there is also https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
- [x] Investigate PHP VS Code extensions #12796
- [x] Che 7 plugin: PHP Language Server #12797
- [x] Che 7 plugin: PHP Debugger #12795

**Comment by tsmaeder** [comment]
Debugger usese XDebug. Need to find out how php programmers use the debugger, what we need to install and how to run it.

**Comment by tsmaeder** [comment]
Split this task into two issues, debugger and language support.
