### ISSUE TITLE
Branding for Che 7 

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#12811]
### Description
Adopters of the Che should be able to rebrand Che. Ideally we should be able to provide instructions for creating a rebranded Che without rebuilding the whole server. 

- [ ] Rebranding and customization of Dashboard
   - [ ] Adding custom stacks
   - [ ] Rebranding dashboard 
- [ ] Rebranding of Theia IDE.

**Comment by gorkem** [comment]
@slemeur @eivantsov This can be as simple as providing a branding guide for Che 7 as well.

**Comment by kfowlks** [comment]
I concur a branding guide would be very useful.

**Comment by kimholmes** [comment]
Pasting Branding guide from Redhat here:
https://github.com/redhat-developer/codeready-workspaces#branding

This Epic is being tracked in this issue:
https://github.ibm.com/dev-ex/portal-ui/issues/566
