### ISSUE TITLE
VS Code marketplace rate limit error

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12840]
### Description
VS Code marketplace impose rate limiting on access to the extensions binaries.
PR https://github.com/eclipse/che-plugin-broker/pull/35 makes broker do retries and send pretty error to Che but still doesn't prevent blocking of workspace start because of rate limiting.
This often happens when user sets many VS Code extensions in his workspace configuration or several users share public IP which gets blocked when access rate is too high.
It seems VS Code itself bypasses this problem, but I haven't found how. We need to investigate how exactly it is done.
Another possible improvement is not to download extensions when workspace plugins list doesn't change, so provisioning could be cached.

Related issues:
https://github.com/eclipse/che/issues/12831
https://github.com/eclipse/che/issues/12762

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@l0rd it is problem we discussed today.
@ibuziuk @skabashnyuk @benoitf @evidolob FYI

**Comment by l0rd** [comment]
Full exception as reported by @benoitf:

```json
{
"$id":"1",
"innerException":null,
"message":"Anonymous usage from IP address ***** has exceeded our rate limits and is being blocked. Anonymous access from this IP address will be unblocked within the next 1 minute. You can also consider logging in to get unblocked. Logged in users have higher limits. Learn more: https://go.microsoft.com/fwlink/?LinkId=823950.",
"typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException,Microsoft.TeamFoundation.Framework.Server",
"typeKey":"RequestBlockedException",
"errorCode":0,
"eventId":3000
}
```

cc @slemeur

**Comment by l0rd** [comment]
The possible solution for this problem can range from a lazy caching mechanism (once we request one  vs code extensions we don't request it anymore) to a vs code extension mirror (we pre-fetch all the extensions).

In the short term, to mitigate the problem, we could look at these solutions:
- embed the vs code extensions that are currently in the che-plugin-registry in their sidecar image
- embed the extensions in the che-plugin-registry docker image and change the meta.yml to point to it.
- look at some already existing alternative URLs to download the extension (i.e. the artifact produced by the CI/CD of the extensions)

**Comment by garagatyi** [comment]
Additional details for the assignee:
We have 10 VS Code plugins in the [registry](https://github.com/eclipse/che-plugin-registry/tree/master/plugins) that are useful (I do not treat sonarlint extension as such).
4 of them are published by Red Hat.
We should check if any of plugins (especially non-redhat owned ones) are publishing github releases or host archive binaries anywhere else.

**Comment by apupier** [comment]
I also hit this issue having just 1 or 2 plugins in my stack. this is quite annoying and it was not easy to find the root cause.

**Comment by fbricon** [comment]
The latest vsix have been "released" on github:
- vscode-yaml:  https://github.com/redhat-developer/vscode-yaml/releases/download/0.4.0/redhat.vscode-yaml-0.4.0.vsix
- vscode-xml: https://github.com/redhat-developer/vscode-xml/releases/download/0.5.1/redhat.vscode-xml-0.5.1.vsix

**Comment by ibuziuk** [comment]
@skabashnyuk @garagatyi @l0rd guys, I'm not very fluent with plugin versioning update process. Could you please clarify the policy? e.g. both xml and yaml plugins used in our registry are obsolete. Should we create dedicated folders with versioning? So, far I created https://github.com/eclipse/che-plugin-registry/pull/113 just for url switch

**Comment by garagatyi** [comment]
@ibuziuk problematic part is that we do not have proper ways for a user to use newer version of plugins in a workspace. So, we usually update just URL to the binary of the plugin. 
But since VS Code plugins are properly versioned this seems a bad practice. 
We should definitely invest in https://github.com/eclipse/che/issues/12937

At this point of time I'm +1 to create new version for yaml and xml plugins.

**Comment by ibuziuk** [comment]
> At this point of time I'm +1 to create new version for yaml and xml plugins.

@garagatyi @l0rd so are you ok if UD would display 'n' versions of plugin atm once we add latest versions to the registry?

**Comment by l0rd** [comment]
@ibuziuk yes that's ok. That's a UD problem and we are removing the list of plugins and editors from the create workspace panel in UD #12896 and moving it inside che-theia #12905.

**Comment by l0rd** [comment]
@ibuziuk since you have done the first PR can you add the newest version of JDT LS as well?

**Comment by ibuziuk** [comment]
@l0rd sure thing will do
@fbricon @gorkem could you please give a hand with https://github.com/redhat-developer/vscode-java/issues/892

**Comment by ibuziuk** [comment]
Some updates before updating plugin registry on prod:
 - [ ] vscode-kubernetes-tools (still uses markeplace) - https://github.com/Azure/vscode-kubernetes-tools/issues/527
- [x] ms-python.python (old version uses marketplace / new version uses github release) - https://github.com/eclipse/che-plugin-registry/pull/119
- [ ] vscode.go (still uses marketplace) - https://github.com/Microsoft/vscode-go/issues/2456
- [ ] vscode.node-debug (still uses marketplace) - https://github.com/Microsoft/vscode-node-debug/issues/191
- [ ]  vscode.node-debug2 (node 8 < )(still uses marketplace) - https://github.com/Microsoft/vscode-node-debug2/issues/232
- [x] vscode.typescript **!!!** uses `che-incubator` https://github.com/che-incubator/ms-code.typescript/releases/download/v1.30.2/che-typescript-language.vsix
- [ ] vscode-redhat.java (still uses marketplace / should be fixed soon) - https://github.com/redhat-developer/vscode-java/issues/892
- [x] vscode-sonarlint - uses GH release - https://github.com/eclipse/che-plugin-registry/pull/118 (but looks like extention does not work atm with the latest release)
- [x] openshift-connector - uses GH release https://github.com/eclipse/che-plugin-registry/pull/117
- [x] vscode-xml - uses GH release - https://github.com/eclipse/che-plugin-registry/pull/114
- [x] vscode-yaml - uses GH release (but not obsolete 0.3.0 - https://github.com/redhat-developer/vscode-yaml/issues/176) - https://github.com/eclipse/che-plugin-registry/pull/114

**Comment by fbricon** [comment]
vscode-yaml 0.3.0 and vscode-redhat.java recent builds have now been attached to github releases

**Comment by apupier** [comment]
Is usage of Github release artefact a temporary hack?
We are loosing the metrics having them.
it is forcing to add an extra step to configure jobs to push the artefact too.

**Comment by ibuziuk** [comment]
@apupier yes, this might be temporary if we find a better way to avoid rate limit issues, so far there was no straight forward solution found

**Comment by l0rd** [comment]
@ibuziuk @apupier this **is a temporary solution** to mitigate a blocking problem. After Che 7 GA is released we should start working on a lazy caching mechanism or a VS Code Marketplace mirroring as described https://github.com/eclipse/che/issues/12840#issuecomment-473870618.

**Comment by l0rd** [comment]
@ibuziuk thanks makes sense

**Comment by ibuziuk** [comment]
Sometimes hit this problem during installation of java debugger - https://github.com/microsoft/vscode-java-debug/issues/583

**Comment by benoitf** [comment]
@ibuziuk 
would these links work ? AFAIK there is no limit rate on the assets
https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/java/0.44.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by ibuziuk** [comment]
@benoitf I haven't tried but I believe any link with valid vix would work

**Comment by benoitf** [comment]
I mean, these links are generics, it's easy to have links for any vs code extension and it's like the final redirect of marketplace download so there is no limit rate
