### ISSUE TITLE
Platform-2019-04-09 (Sprint: 164)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12868]
### Features related to Devfile
- [x] Default devfile name | https://github.com/eclipse/che/issues/12837 | 5
- [x] Devfile: tools should be renamed components | https://github.com/eclipse/che/issues/12836 | 5
- [x] [Devfile] OpenShift/K8s tool - reference to content | https://github.com/eclipse/che/issues/12733 | 5
- [x] [devfile] Che commands (Theia task) targeting a container tool defined by url is not working | https://github.com/eclipse/che/issues/12765 | 8
- [x] Add more flexibility into devfile project source - checkout branch, commit ID etc | https://github.com/eclipse/che/issues/12775 | 8
- [x] Support clonePath in devfile | https://github.com/eclipse/che/issues/12557 | 5
- [x] Support multiple dockerimage tools in Devfile https://github.com/eclipse/che/issues/12875

### Features related to Monitoring/Tracing
- [x]  [Metric] Number of users | https://github.com/eclipse/che/issues/12093 | 5

### Other tasks
- [x] Provide a way to push additional build-time information to the Che Help > About dialog | https://github.com/eclipse/che/issues/12871 | 5
- [x] Create a list of OpenShift objects that we can/can't support in devfile or workspace recipe | https://github.com/eclipse/che/issues/12899 | 3

### Finalize issues started in the previous sprint.

- [x] Add an ability to specify entrypoint for kube and openshift tool in Devfile | https://github.com/eclipse/che/issues/12693 | 2
- [x] Inform users about what devifle was used to create a workspace with the factory | https://github.com/eclipse/che/issues/12741  2
- [x] Support devfile with more than one Kubernetes tool | https://github.com/eclipse/che/issues/12719 5

### Unplanned
- [x] Theia should be the default editor https://github.com/eclipse/che/issues/12835
- [x] [POC] Devfile format for Stack, Factory, Workspace API https://github.com/eclipse/che/issues/13018
- [x] Move master related code out of plugins https://github.com/eclipse/che/pull/13004

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Lukas Krejci | 15d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 58  | 58 |
