### ISSUE TITLE
IDE-2019-04-09 (Sprint: 164)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#12894]
### Sprint goals

1. Add needed VS Code API for finalizing Kubernetes Plugin Support 
2. Include existing GitHub PullRequest  plugin in Che Theia IDE
3. Che commands should be first class citizens in Theia

### Sprint details:
_**Che 7 GA Epic - #12170**_ 

#### 1. Add needed VS Code API for finalizing Kubernetes Plugin Support
- [x] Command "Kubernetes: Delete Context" of Kubernetes Tolling don't work in Theia #12745
- [ ] [views] pass the selected tree item to a command's argument https://github.com/theia-ide/theia/issues/3882
- [x] Kubernetes Plugin: Helm cannot interact with chart repositories #12982

#### 3. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [ ] [plug-in] VS Code Git extensions https://github.com/theia-ide/theia/issues/4266
- [x] Add possibility to register Argument processor for Commands Plugin Api https://github.com/theia-ide/theia/issues/4576
- [x] [plug-in] Implement 'window.registerDecorationProvider' Plugin API method in theia-proposed.d.ts https://github.com/theia-ide/theia/issues/4666

#### 4. Che commands should be first class citizens in Theia #12709
- [x] User defined Che tasks commands should be exported in a tasks.json file #12712 
- [ ] Che commands should be of type task or launch #12710

#### Other tasks:
- [ ] Track che tasks #12838
- [ ] Ability to check whether the webview panel is active and visible https://github.com/theia-ide/theia/issues/4342
- [x] Implement 'WebviewPanel.reveal() https://github.com/theia-ide/theia/issues/4339
- [x] Tweak ephemeral workspace warning https://github.com/eclipse/che/issues/12960

#### Merge-ready PRs  
- [ ] Introduce SCM Plugin-Api theia-ide/theia#4279

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 11 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
### Retrospective Comments
