### ISSUE TITLE
Adopt devfile format for Stacks

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12924]
### Description
A stack is a workspace template, providing ready to use developer stack for a particular technology. 
That concept will remain in Che 7, but will need to be adapted to the devfile.

The goal is that we don't want to rely anymore on workspace json, we don't want to display that to end-user.

Today, the way the stacks are getting configured is not easy to manage. If someone wants to provide a different set of stacks, it needs a complete new assembly. We should be improving this. 

As we are going to introduce a registry of plugin - we should be thinking about providing the stacks as a registry of specific devfile too.

##  **Stacks Registry**
As we are going to introduce a registry of plugin - we should be looking at providing the stacks as a registry of specific devfile too.
- As an admin of Eclipse Che, at installation/deployment I should be able to configure the repository that is used to provide the list of stacks.
- As an admin of Eclipse Che, I should be possible to change the list of stacks and replace it by pulling a different repository 
- As an admin of Eclipse Che, I should be able to extend the list of stacks with another repository, in the case I want to provide the upstream stacks + a list of stacks that I'm going to manage myself.

##  **Stacks for End-User**
- As a developer, I can see the list of stacks and when I look at the configuration of the stack, I can see it is defined with a devfile
- As a developer, I can use a stack (define as a devfile) to create a workspace
- As a developer, I can register new stack by providing a devfile with a set of other meta-information. That stacks will be available only to me.

## **Implementation**
- [x]  Create eclipse/che-devfile-registry repository https://bugs.eclipse.org/bugs/show_bug.cgi?id=547414
- [x] ~~Add an ability to use Devfile as part of Stack API  https://github.com/eclipse/che/issues/13338~~
- [x] Initial setup of Che Defvile registry  https://github.com/eclipse/che/issues/13353
- [x] Adjust dashboard to use devfile registry https://github.com/eclipse/che/issues/13354
- [x] Deploy and use public che devfile registry on https://che.openshift.io infrastructure https://github.com/eclipse/che/issues/13355
- [x] StackService decommissioning  https://github.com/eclipse/che/issues/13459

**Comment by slemeur** [comment]
closing as everything has been handle
