### ISSUE TITLE
Languages Spring 164 (M1)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12920]
March 20-April 09

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 12 | 7 | 7
@tolusha | 14 | 8 | 7
@svor | 13 | 8 | 8
@vrubezhny | 7 | 4

# Candidate Issues
- [x] Documentation: How to Add Support for a New Debugger #12916 @tolusha  5d
- [x] Che 7 Plugin: Python https://github.com/eclipse/che/issues/12771 @tolusha  0d
- [ ] PHP Language Support https://github.com/eclipse/che/issues/12772
  - [ ] Che 7 plugin: PHP Language Server #12797 @vrubezhny 
  - [ ] Che 7 plugin: PHP Debugger #12795
- [ ] C# LS and Debugger as plug-in https://github.com/eclipse/che/issues/12773 
   - [x] Theia plugin: .Net Debugger #12790 @svor (5d)
  - [x] Che 7 plugin: C# #12792 @svor 3d
  - [ ] Che 7 plugin: .Net debugger #12793
- [x] Find a Home for repackaged VS Code extensions https://github.com/eclipse/che/issues/12774
- [ ] Don't use Monaco Concepts in Main/Ext Interface https://github.com/theia-ide/theia/issues/4355 @tsmader 3d
- [x] Duplicate hovers in vscode-camel https://github.com/theia-ide/theia/issues/4181 @tolusha  1d
- [ ] Need to implement "files.associations" configuration property https://github.com/theia-ide/theia/issues/4581 @tolusha  (1d)
- [x] Add adding files.associations property https://github.com/theia-ide/theia/pull/4721 @tolusha 
- [ ] Che 7 plugin: vscode-java-debug #12446 (1d) @tsmaeder  see https://github.com/eclipse/che-plugin-broker/pull/36
New since yesterday.
- [x] Test Language Support Plug-ins on Minishift #12941 @tsmaeder  3d
- [x] Python Stack #12944 @tolusha 
- [ ] Django Stack #12945
- [ ] Implement some editor related VS Code commands #12943 

# From Last Sprint

# Blocked issues 
# Unplanned Issues

- [x] Use latest theia-generator version https://github.com/eclipse/che-theia/pull/140 @tolusha 
- [x] Replace python 3.7.2 on 3.7.3 https://github.com/eclipse/che-theia/pull/158 @tolusha 
- [x] Update Python sidecar image version https://github.com/eclipse/che-plugin-registry/pull/108 @tolusha 

# Doc
[How to add support for a new debugger for Che Theia](https://che.eclipse.org/how-to-add-support-for-a-new-debugger-for-che-theia-f459ea806ff)

Previous Sprint: https://github.com/eclipse/che/issues/12759
