### ISSUE TITLE
Adopt devfile format for workspaces configuration

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#12926]
### Description
Devfile is becoming the new way to define a workspace and we need to adopt its format for the workspaces.

### User Stories
- In the dashboard, when the user is editing the definition of his workspaces, it must be based on the devfile format. [issue](https://github.com/eclipse/che/issues/13067)
- In the dashboard, a user should be able to create a workspace by providing a devfile [issue]( https://github.com/eclipse/che/issues/13058)
- In the dashboard, a user should be able to export a workspace to a devfile. 

(In other words, whereever we are displaying the workspace.json configuration in the dashboard, it should be replaced by devfile)

- [x] [POC] Devfile format for Stack, Factory, Workspace API | https://github.com/eclipse/che/issues/13018
- [x]  Provide database layer storage and integrity of devfile as part of workspace | https://github.com/eclipse/che/issues/13075
- [x] [UD] Allow user to manage workspace devfile https://github.com/eclipse/che/issues/13067
- [x] [UD] Workspace creation from devfile https://github.com/eclipse/che/issues/13058
- [x] Add an ability to use Devfile as workspace configuration as alternative to WorkspaceConfig https://github.com/eclipse/che/issues/13079
- [x] Make Theia respect Devfile of a field of Workspace https://github.com/eclipse/che/issues/13112

**Comment by skabashnyuk** [comment]
@slemeur all issues are done. can we close this epic?
