### ISSUE TITLE
QE-2018-04-09 (Sprint: 164)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#12978]
### Issues tied to objectives
- [x] Rework "cypress-tests" module with using "InversifyJS" library #12866 3sp
- [ ] [Cypress] Rework "WorkspaceCreationAndLanguageServerInitialization.spec.ts" cypress test for launching on multiuser assembly #12888 3sp

### Unplanned 
- [x] [Cypress] Update the "WorkspaceCreationAndLanguageServerInitialization.spec.ts" cypress test according to the last changes #13028 1sp
- [x] [Cypress] Use an "Electron" browser for "headless" mode #13038 1sp
- [x] [Cypress] Update the "WorkspaceCreationAndLanguageServerInitialization.spec.ts" cypress test according to the dashboard changes #13053 1sp

### PR under review
- [x] Fix work of Devfile with multiple dockeimages components #13009
- [x] Added provisioning of Default Editor into Devfile #13003
- [x] Fixed NPE during provisioning of selector for Deployments #13041 
- [x] Add metrics for number of users #13001
- [x] Used manually written Devfile POJOs instead of generated ones. #13048
- [x] Fix validation devfile for components with id like gist url. #13056

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 10 |
| Total | 85  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 6 | 3 |

### Retrospective Comments
- [ ] [Cypress] Rework "WorkspaceCreationAndLanguageServerInitialization.spec.ts" cypress test for launching on multiuser assembly #12888 - progress stopped due to change the priority
