### ISSUE TITLE
Che 7 doc for GA

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12974]
Putting here the parts of [Che doc outline](https://github.com/eclipse/che-docs/issues/712) that are mandatory for Che 7 GA:

**When you start adding content to google docs, please, tag rkratky@redhat.com, so that I know I can start reviewing. Thanks. Robert**

- [ ] 🔥Running Che remotely - @benoitf - [google-doc](https://docs.google.com/document/d/1BAnjIZgBLjkUu_7RG9EgSDMQ1MbzWRbC0yVqfU18IcM/)
- [ ] 🔥Hosted Che - [IN PROGRESS] - @ibuziuk - [PR #729](https://github.com/eclipse/che-docs/pull/729)
- [ ] 🔥Che architecture [IN PROGRESS] - @l0rd - [google-doc](https://docs.google.com/document/d/1HVVzuMZO7qVxEm6FosAhL5XuUzrMe2ooAAsvmnIWB6k/)
- [ ] Che-Theia IDE basics - **@teams/ide1** - [google-doc](https://docs.google.com/document/d/15OGTxr1ChL74DcBMaiUeL0QKJqdPHn2HnTm8WRtrn7k/)
  - 🔥Commands
  - 🔥Version control
- [ ] 🔥Making a workspace portable using a Devfile - [ON REVIEW] - @sleshchenko - [google doc](https://docs.google.com/document/d/1CEgtZVd5Y1P4IKutpxiHkrgUS3258xZY0Yp0PZs950M/edit#)
- [ ] 🔥Migrating an old Che 6 workspace - [IN PROGRESS] - @olexii4 - [google doc](https://docs.google.com/document/d/1qrHg4F2FvTpafJAvgqgzeYTu6M0UA1mSjm_UCoQNFHc/)
- [ ] 🔥Retrieving Che logs - **@teams/languages** - [google-doc](https://docs.google.com/document/d/182PBN5LBNTlbhsqqsb5QHg9t5HNK3rSLrnIMPSGjyN0/)
- [ ] 🔥Devfile and Plugin registries customization - @l0rd - [google-doc](https://docs.google.com/document/d/1K4pax-mmnOs98OXE7TcmzA0Kp0oo7AnjdAq6iFf7x0k/)
- [ ] Securing Che - **@teams/ide1** - [google-doc](https://docs.google.com/document/d/1gvki1dXWtq0Pha4Nv6yAVmuZfVx8U_MIHgv8C59t_3A/edit#)
    - 🔥User authentication and authorization
    - 🔥Using GitHub OAuth

Hands-On articles:

- [ ] 🔥Creating a workspace from code sample - @nickboldt - [PR #737](https://github.com/eclipse/che-docs/pull/737)
- [ ] 🔥Creating a workspace by importing source code of your project - @nickboldt - [PR #737](https://github.com/eclipse/che-docs/pull/737)
- [ ] 🔥Importing a Kubernetes application into a Che workspace - @l0rd - [google-doc](https://docs.google.com/document/d/1VZJSRh8kFpr5U8R_DDycv-4MgFqzdyZybmCcco_ShUg/edit#)
- [ ] 🔥Using a Visual Studio Code extension in Che - **@teams/ide2** - [google-doc](https://docs.google.com/document/d/1gZHKXe1GEduY48RgntMUrqjSs9llq8WpCmgqssY5Ikw/edit#) (see [Converting a Visual Studio Code extension to a Che-Theia plug-in](https://www.eclipse.org/che/docs/che-7/extending-che.html#converting-a-visual-studio-code-extension-to-a-che-theia-plug-in_developing-che-theia-plug-ins) to avoid duplication)
- [ ] 🔥Remotely accessing your workspace (open a shell) - @l0rd - [google-doc](https://docs.google.com/document/d/1t5kRcvB3GKycB7LtbuhUNH8oBgrrCEqcUCEdCKOBhcg/edit#)
- [ ] 🔥Use an alternative Che workspace editor - **@teams/platform** - [google-doc](https://docs.google.com/document/d/1RvCgANwRr4gqcVikS-FaVkerlTpOdLDOf4tcJjPUYUQ/edit#) (see [Using alternative IDEs in Che](https://www.eclipse.org/che/docs/che-7/extending-che.html#using-alternative-ides-in-che_extending-che) for an intro)

**Comment by l0rd** [comment]
Closing this issue since it's replaced by https://github.com/eclipse/che/issues/13637
