### ISSUE TITLE
Missing API for Language Support Che 7 Plug-Ins

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13007]
This lists missing VS Code API referenced from Language Support Plugins used in Che 7 GA.

**Comment by tsmaeder** [comment]
#Commands
- [ ] editor.action.formatSelection (vscode-java)
- [ ] workbench.action.debug.restart (vscode-java-debug)
- [ ] workbench.action.debug.start (vcode-node-debug)
- [ ] workbench.action.openGlobalSettings (vscode-go)
- [ ] workbench.action.openWorkspaceSettings (vscode-go)
- [ ] workbench.action.reloadWindow (vscode-go)
- [ ] editor.action.rename (vscode-python, vscode-typescript)
- [ ] revealLine (vscode-python)
- [ ] revealFileInOS (vscode-typescript)
- [ ] workbench.action.reloadWindow (vscode-xml)
- [ ] workbench.action.reportIssues (vscode-typescript)
#API
- [ ] vscode.InputBox (vscode-python)
- [ ] vscode.QuickInput (vscode-python)
  - [ ] dispose
  - [ ] show
- [ ] vscode.QuickInputButton (vscode-python) 
- [ ] vscode.QuickInputButtons (vscode-python) 
- [ ] vscode.QuickPick (vscode-python) 
- [ ] vscode.TextEditor.show (vscode-python) 
- [ ] vscode.env.openExternal (vscode-python) 
- [ ] vscode.window.createInputBox (vscode-python) 
- [ ] vscode.window.createQuickPick (vscode-python) 
- [ ] vscode.CodeActionKind.intersects (vscode-typescript)
- [ ] vscode.DiagnosticTag.intersects (vscode-typescript)
- [ ] vscode.SignatureHelpContext (vscode-typescript)
- [ ] vscode.SignatureHelpTriggerKind (vscode-typescript)
  - [ ] ContentChange (vscode-typescript)
  - [ ] Invoke (vscode-typescript)
  - [ ] TriggerCharacter (vscode-typescript)

**Comment by tsmaeder** [comment]
Collected from https://github.com/eclipse/che/issues/12996.  I haven't looked at the "dynamicCommandCalls" yet. These might reveal more used commands.

**Comment by tsmaeder** [comment]
List now includes dynamic command invocations.

**Comment by benoitf** [comment]
vscode.java is also using vscode.extensions.onDidChange() which is not available.

**Comment by tsmaeder** [comment]
Thanks for detecting that. The bigger question, though: which is that not being picked up by the tool? If it's not reliable, it's a lot less useful.

**Comment by tsmaeder** [comment]
https://github.com/theia-ide/theia-vscodecov/issues/1

**Comment by tsmaeder** [comment]
I'll need to do another pass over the repos, unfortunately. The positives still are real positives that should be fixed.

**Comment by tsmaeder** [comment]
Reran the checks with the newest version of the tool and master of the extensions
