### ISSUE TITLE
IDE2-2019-04-30 (Sprint: 165)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13054]
### Sprint Goals:
1. Implement flow to install a plugin from the IDE - GA
2. High priority fixes
3. Handle devfile in dashboard
4. Devfile contest

Che 7 Beta Epic - https://github.com/eclipse/che/issues/12170
Che 7 GA Epic - https://github.com/eclipse/che/issues/12696

## 1. Implement flow to install a plugin from the IDE
- [x] [Give ability to the user to proceed installation/uninstallation](https://github.com/eclipse/che/issues/13117) [TODO add sub- issues] 5d
  - [x] Display visual feedback when a plugin is getting installed 3d
  - [x] Provide way to see errors if that happens [TODO issue for checking the plugin's structure]
  - [x] Discuss with Mario about plugin installation flow

## 2. High priority fixes
- [x] Handle plugins with no activate function https://github.com/theia-ide/theia/issues/4850 - blocker for L&T 3d
- [x] Add the needed methods for Webview API https://github.com/theia-ide/theia/issues/3896 [in progress] 2d
- [x] Plugins don't start the first time https://github.com/eclipse/che-theia/issues/101 [in progress] 2d
- [x] New Terminal" opens unresponsive terminal window (https://github.com/eclipse/che/issues/13030) [TODO ping Thomas in MM]
- [ ] Add VS code extensions preferences in workspace configuration (https://github.com/eclipse/che/issues/12992) [analyzing]
- [x] Rename container view (https://github.com/eclipse/che/issues/12984) 3d
- [x] Che should hide/collapse the the "Dashboard" menu by default https://github.com/eclipse/che/issues/12822 2d

## 3. Handle devfile in dashboard
- [x] Dashboard: Simplify workspace edition tabs https://github.com/eclipse/che/issues/12909 [PR is under review]
- [ ] [UD] Workspace creation from devfile https://github.com/eclipse/che/issues/13058 [analyzing needed]
- [ ] [UD] Allow user to manage workspace devfile https://github.com/eclipse/che/issues/13067 [analyzing needed]
- [ ] Dashboard: mark with an error old Che 6 workspaces ( https://github.com/eclipse/che/issues/12917) 5d

## 4. Devfile contest
Every team member should write a devfile for some project

## Other  issues:
- [x] Sharing from the IDE https://github.com/eclipse/che/issues/12722 [in progress]
- [ ] Che-theia: progress in status bar when performing any git clone (factory, workspace sync, git clone command) https://github.com/eclipse/che/issues/12564 [TODO check a dependency issue]
- [x] Welcome plug-in shouldn't open welcome page each page load https://github.com/eclipse/che-theia/issues/95 1d [PR]
- [x] Workspace loader does not react on STOPPED event if an error is absent https://github.com/eclipse/che/issues/13042 3d
- [ ] Build and package che-theia plugins during che-theia image build.  https://github.com/eclipse/che-theia/issues/45 [in progress PR] 
- [ ] Rework all che-theia images to RH UBI (universal base image) - [TODO issue] (analyzing)
- [ ] Add ability to disable/remove default plug-ins in Che Theia https://github.com/eclipse/che-theia/issues/159 

## Unplanned tasks
- [ ] UD should show warning if plugin is deprecated https://github.com/eclipse/che/issues/13021

## Pending PR
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [ ] Dashboard: fail build when webpack has errors #12911
- [x] Use cwd for terminal creation https://github.com/eclipse/che-theia/pull/115
- [x] Retrieving launch configurations using Plugin API https://github.com/theia-ide/theia/pull/4743

## Technical debts 
(_some time in sprint is allocated to handle those issues_ )
- [ ] View Container widget improvements https://github.com/theia-ide/theia/issues/4386 
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740
- [ ] UD and workspace-loader should subscribe to output on a specific endpoint provided by Workspace API https://github.com/eclipse/che/issues/11526
- [ ] Add image with debugger to speed up development https://github.com/eclipse/che-machine-exec/issues/12
- [ ] Users inconsistance when run nodejs script https://github.com/eclipse/che-theia/issues/60
- [ ] Wrong behavior with Testing Stack widget https://github.com/eclipse/che/issues/12567

**Total planned = [todo]sp**

### Next sprint proposals
- [ ] Duplication of what is typed in terminal view can happen https://github.com/eclipse/che/issues/13165
- [ ] Make Theia respect Devfile of a field of Workspace https://github.com/eclipse/che/issues/13112
- [ ] Adapt WorkspaceLoader to workspaces created with Devfile https://github.com/eclipse/che/issues/13201
- [ ] Show the progress of installing a plugin  https://github.com/theia-ide/theia/issues/3632
- [ ] Mark plugin logs with plugin name https://github.com/theia-ide/theia/issues/2458
- [x] Make Theia plugin state and workspace state persistent https://github.com/eclipse/che/issues/12260
- [ ] mocking plugin API [TODO issue] 40sp
- [ ] Add ability to import project with sparse checkout feature https://github.com/eclipse/che-theia/issues/33
- [ ] Add plugin validator https://github.com/theia-ide/theia/issues/4945
### Theia bugs 
- [ ] Method not implemented: DocumentDataExt.acceptLanguageId https://github.com/theia-ide/theia/issues/4294
- [ ] FileUri gets loaded in browser https://github.com/theia-ide/theia/issues/4272
- [ ] plugin code gets loaded outside of plugin host process https://github.com/theia-ide/theia/issues/4271
- [ ] vscode.languages.setTextDocumentLanguage is not a function https://github.com/theia-ide/theia/issues/4448
- [ ] plugin formatting providers are not applied  https://github.com/theia-ide/theia/issues/4686
- [ ] Set focus to another editor if current one is closed  https://github.com/theia-ide/theia/issues/4502
- [ ] plugin system breaks user storage abstraction https://github.com/theia-ide/theia/issues/4488

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/18mbwz25UHZNOdvrUX_YL1sVu5VIbyANIdh01V3kcYPQ/edit?usp=sharing)
