### ISSUE TITLE
IDE-2019-04-30 (Sprint: 165) 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#13065]
### Sprint goals

1. Add needed VS Code API for finalizing Kubernetes Plugin Support 
2. Include existing GitHub PullRequest  plugin in Che Theia IDE
3. Che commands should be first class citizens in Theia

### Sprint details:
_**Che 7 GA Epic - #12696**_ 

#### 1. Add needed VS Code API for finalizing Kubernetes Plugin Support
- [x] [views] pass the selected tree item to a command's argument https://github.com/theia-ide/theia/issues/3882
- [ ] [Kubernetes Plugin] Kubernetes: Diff command doesn't open diff view when running in a sidecar #13044
- [x] [Kubernetes Plugin] Show Dependencies command opens extra tab #13037

#### 3. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [ ] [plug-in] VS Code Git extensions https://github.com/theia-ide/theia/issues/4266
- [x] Add possibility to register Argument processor for Commands Plugin Api https://github.com/theia-ide/theia/issues/4576
- [ ] POC: Extend pull request flow to add Factory in the comments (#10282)

#### 4. Che commands should be first class citizens in Theia #12709 
- [ ] Che commands should be of type task or launch #12710

#### Other tasks:
- [x] Track che tasks #12838
- [x] Ability to check whether the webview panel is active and visible https://github.com/theia-ide/theia/issues/4342
- [x] running a task/che-commands is showing error: `Request {taskname} failed with error: Information not found` [#155](https://github.com/eclipse/che-theia/issues/155)
- [x] Target container should be an optional parameter for workspace:inject command [#59](https://github.com/che-incubator/chectl/issues/59)

#### Merge-ready PRs  
- [ ] Introduce SCM Plugin-Api theia-ide/theia#4279

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 11 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
### Retrospective Comments
