### ISSUE TITLE
Languages Sprint 165 (M2)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13074]
April 10-May 1

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 5 | 3 | 3
@tolusha | 12 | 8 | 8
@svor | 12 | 8 | 11
@vrubezhny | 12 | 8 | 8

# Priorities
1. Finish PHP and C# support
2. Stacks, Stacks, Stacks...
3. Quality/Testing

All testing must be done on minishift!

# Candidate Issues

- [ ] PHP Language Support https://github.com/eclipse/che/issues/12772 (8d @vrubezhny)
  - [ ] Che 7 plugin: PHP Debugger #12795
  - [ ] Che 7 plugin: PHP Language Server #12797
- [x] C# LS and Debugger as plug-in https://github.com/eclipse/che/issues/12773 
  - [x] Che 7 plugin: .Net debugger #12793 5d
- [x] Need to implement "files.associations" configuration property https://github.com/theia-ide/theia/issues/4581 @tolusha  (3d)
- [x] Che 7 plugin: vscode-java-debug #12446 @svor  (2d) 
- [x] Django Example (#12945) (1d) @tolusha 
- [ ] C# Stack #13096 (4d)
- [ ] PHP Stack (#12620)
- [x] Go stack #13098 @tolusha 3d
- [x] Update vscode-java to latest #13107 1d @tsmaeder 
- [ ] Che Server Developer Stack #13106 1d @tsmaeder 
- [ ] Implement 'workbench.action.reloadWindow' API #13108 1d (@tsmaeder)
- [x] Track: Handle plugins with no activate function https://github.com/theia-ide/theia/issues/4850 (1d)

Missing API for Language Support Che 7 Plug-Ins #13007

New since yesterday.
    

# From Last Sprint

# Blocked issues 
# Unplanned Issues

# Open PR's

Previous Sprint: https://github.com/eclipse/che/issues/12920
