### ISSUE TITLE
Platform-2019-04-30 (Sprint: 165)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13123]
### Features related to Devfile

- [x] Provide database layer storage and integrity of devfile as part of workspace | https://github.com/eclipse/che/issues/13075 | 3
- [x] Add an ability to use Devfile as workspace configuration as alternative to WorkspaceConfig | https://github.com/eclipse/che/issues/13079 | 13
- [ ] [POC] tasks and launch configuration as part of Devfile | https://github.com/eclipse/che/issues/13057 | 8
- [x] Error when starting workspace, created from devfile | https://github.com/eclipse/che/issues/13040 | 3
- [x] Set memory limit for sidecar plugins on devfile | https://github.com/eclipse/che/issues/12981 | 8
- [ ] Introduce registryUrl field for cheEditor/chePlugin components | https://github.com/eclipse/che/issues/13104 | 13
- [x] Rename `name` field of component to Devfile to `alias` | https://github.com/eclipse/che/issues/13103 | 5

### Features related to Monitoring/Tracing
- [ ] Create documentation for monitoring use-case | https://github.com/eclipse/che/issues/12543 | 5
- [ ] [Metrics] Workspace memory consumption | https://github.com/eclipse/che/issues/13045 | 8

### Unplanned
- [x] Make reference field of Devfile optional if referenceContent field is specified https://github.com/eclipse/che/issues/13190
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 13d |
| Max Shaposhnik | 13d | 
| Michail Kuznyetsov | 13d | 
| Sergii Leshchenko | 13d | 
| Lukas Krejci | 15d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 66  | 32 |
