### ISSUE TITLE
IDE2-2019-05-21 (Sprint: 166)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#13212]
### Sprint Goals:
1. Implement flow to install a plugin from the IDE - GA
2. High priority fixes
3. Handle devfile in dashboard, Theia and workspace loader
4. Devfile contest

**Che 7 GA Epic** - https://github.com/eclipse/che/issues/12696

## 1. Implement flow to install a plugin from the IDE
- [x] Display editors in separate list - 2d
- [x] Dedicated list for the installed plugins - 2d 
- [ ] Provide ability to easily add a VSCode extension - 3d https://github.com/eclipse/che-theia/issues/209

_Postpone:_
- [x] Filtering plugins by name, etc. 
- [ ] Display information about the plugin in editors section ?
- [ ] Display built-in plugins (provided by docker image)
- [ ] Add ability to disable/remove default plug-ins in Che Theia https://github.com/eclipse/che-theia/issues/159 

## 2. High priority fixes
- [x] Add VS code extensions preferences in workspace configuration (https://github.com/eclipse/che/issues/12992) [analyzing] 4d
- [ ] Talk to Florent (Theia binary to sidecar), no synch between Theia version and runtime in sidecar 
- [x] Browser tab with opened WorkspaceLoader hangs when Che Server is unreachable https://github.com/eclipse/che/issues/12063 3d

## 3. Handle devfile in dashboard, Theia and workspace loader
- [ ] [UD] Workspace creation from devfile https://github.com/eclipse/che/issues/13058 [analyzing needed]
- [x] Dashboard: mark with an error old Che 6 workspaces ( https://github.com/eclipse/che/issues/12917) 5d
- [x] Make Theia respect Devfile field of Workspace https://github.com/eclipse/che/issues/13112 [in progress]
- [x] Adapt WorkspaceLoader to workspaces created with Devfile https://github.com/eclipse/che/issues/13201 -  3d

## 4. Devfile contest
Every team member should write a devfile for some project

## Other  issues:
- [x] Build and package che-theia plugins during che-theia image build.  https://github.com/eclipse/che-theia/issues/45 [in progress PR] 
- [ ] Rework all che-theia images to RH UBI (universal base image) - [TODO issue] (analyzing)
- [ ] Che-theia: progress in status bar when performing any git clone (factory, workspace sync, git clone command) https://github.com/eclipse/che/issues/12564 [TODO check a dependency issue]
- [x] Use current directory for terminal in the che-theia https://github.com/eclipse/che/issues/12950
- [x] tasks: output of a command is not rendered correctly https://github.com/eclipse/che-theia/issues/192

## Unplanned tasks
- [ ] Do not ask user in which container run command if it could be figured out from the workspace panel tree https://github.com/eclipse/che-theia/issues/222
- [ ] Fix animation on creating a workspace from a factory #13365

## Pending PR
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [ ] Dashboard: fail build when webpack has errors #12911
- [x] Delete deprecated Theia editor plugin version https://github.com/eclipse/che-plugin-registry/pull/127 (Mykola)
- [ ] Che Plugins View https://github.com/eclipse/che-theia/pull/162 (Vitaliy)

**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
