### ISSUE TITLE
Languages Sprint 166 (M-3)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13227]
May 1-May 21

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 14 | 6 | 5
@tolusha | 14 | 8.5 | 9.5
@svor | 14 | 8.5 | 9
@vrubezhny | 14 | 8.5 | 8d

# Priorities
1. Finish PHP
2. Stacks, Stacks, Stacks...
3. Quality/Testing

All testing must be done on minishift!

# Candidate Issues
- [ ] Typescript LS should NOT open `tsconfig.json` automatically when opening a typescript file https://github.com/eclipse/che/issues/13076 2d @tolusha 
  - [ ] PR https://github.com/theia-ide/theia/pull/5075
  - [ ] CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19755
- [ ] Provide an image with Java 11 for remote plugins #13225
- [ ] How to develop against a different Java version than the one in the Java tooling sidecar https://github.com/eclipse/che/issues/13250 1d timebox @tolusha 
- [ ] Make it possible to debug Theia plugins in sidecars #13249 
- [ ] Missing API for Language Support Che 7 Plug-Ins #13007
- [x] Support diagnostic of 2 LS on same file theia-ide/theia#4929
- [ ] Update vscode-java-debug to latest https://github.com/eclipse/che/issues/13216
- [x] Fix Java Che Plugin Description #13237
- [ ] PHP Language Support https://github.com/eclipse/che/issues/12772 (8d @vrubezhny)
  - [ ] Che 7 plugin: PHP Debugger #12795
  - [ ] Che 7 plugin: PHP Language Server #12797
- [x] C# Stack #13096 4d @svor 
- [ ] PHP Stack (#13307) 5d @svor 
- [ ] Che Server Developer Stack #13106 1d @tsmaeder 
- [x] Implement 'workbench.action.reloadWindow' API #13108 4d (@tsmaeder)
- [ ] Camel Plugin for Che 7 https://github.com/eclipse/che/issues/12584
  - [x] VS Code xml extension not working with error UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'editor.autoClosingBrackets' of undefined  https://github.com/eclipse/che/issues/12536 2d @tolusha 
    - [x] PR: https://github.com/theia-ide/theia/pull/5149
  - [x] "Error: Request 'updateContent' failed" in docker output when there is a validation error on a Camel file https://github.com/theia-ide/theia/issues/4857 2d @tolusha 
  - [x] Find references is not available for Camel direct component #13183 2d @tolusha 
  - [x] Provide Camel stack for Che 7 #13182 @tolusha 
    - [x] PR https://github.com/eclipse/che/pull/13361
- [ ] Test Language Support Plug-ins on Minishift #12941
- [ ] Implement 'workbench.action.debug.restart` (vscode-java-debug) command https://github.com/theia-ide/theia/issues/5102 (@vrubezhny)
    

# From Last Sprint

# Blocked issues 
# Unplanned Issues
- [x] Can not run launch configuration https://github.com/eclipse/che-theia/issues/233
# Open PR's

Previous Sprint: https://github.com/eclipse/che/issues/13074

**Comment by tsmaeder** [comment]
Error registering keybinding differing by "when" #5113 @JPinkney maybe?
