### ISSUE TITLE
IDE-2019-05-21 (Sprint: 166)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#13263]
### Sprint goals

1. Che commands should be first class citizens in Theia 
2. Add needed VS Code API for finalizing Kubernetes Plugin Support 
3. Include existing GitHub PullRequest  plugin in Che Theia IDE

### Sprint details:
_**Che 7 GA Epic - #12696**_ 

#### 1. Che commands should be first class citizens in Theia #12709 
- [ ] User defined Che launch commands should be exported in a launch.json file #12711

#### 2. Add needed VS Code API for finalizing Kubernetes Plugin Support
- [ ] Kubernetes: Debug (Launch)/Debug (Attach)/Remote Debug  
- [ ] [Kubernetes Plugin] Kubernetes: Diff command doesn't open diff view when running in a sidecar #13044
- [x] [Kubernetes Plugin] Show Dependencies command opens extra tab #13037

#### 3. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [ ] [plug-in] VS Code Git extensions https://github.com/theia-ide/theia/issues/4266
- [ ] POC: Extend pull request flow to add Factory in the comments (#10282)
- [ ] [Plugin-Api] Apply 'comment.createCommentController' function https://github.com/theia-ide/theia/issues/5076
- [x] [Plugin-API] Apply window.createQuickPick() function https://github.com/theia-ide/theia/issues/4987

#### Other tasks:
- [x] Track che tasks #12838 

#### Merge-ready PRs  
- [ ] Introduce SCM Plugin-Api theia-ide/theia#4279

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 11 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
### Retrospective Comments
