### ISSUE TITLE
[Metrics] Observability requirements for Hosted Che

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13270]
### Description

There have been some discussions about metrics we would like to be able to observe on hosted Che (e.g. che.openshift.io) based on the issues we had in the past and these are the most relevant ones: 
# Che Server metrics
- [x]  The % of workspaces started successfully
- [x] The % of workspaces stopped successfully
- [x] The % of workspaces started in under N seconds
# Workspace metrics
- [x] [MVP] Collecting Che Workspace metrics in single cluster mode with Prometheus https://github.com/eclipse/che/issues/14888
- [ ] Collecting Che Workspace metrics in multiple cluster mode with help of Prometheus Federation mechanism https://github.com/eclipse/che/issues/14889
- [ ] Test Prometheus federation in simplified mode. https://github.com/eclipse/che/issues/15030
- [ ] Investigate alternative possibilities to reduce Prometheus's permissions required to monitor workspaces https://github.com/eclipse/che/issues/15031
- [ ] The % of workspaces projects cloned successfully
- [ ] The % of workspaces projects cloned under N seconds
- [ ] The % of Language Servers requests that get a successful response
- [ ] The % of Language Servers requests that get a successful response in under N seconds

cc @skabashnyuk @ibuziuk

**Comment by l0rd** [comment]
I have added this issue to epic #10329

**Comment by ibuziuk** [comment]
I believe the first step would still be adding what we already have available on dsaas - https://github.com/redhat-developer/rh-che/issues/1336

**Comment by l0rd** [comment]
@ibuziuk are you talking about the monitoring infrastructure (prometheus, grafana etc...)? This issue is about implementing the prometheus endpoints.

**Comment by ibuziuk** [comment]
@l0rd Of course, this is not a blocker for implementing those endpoints upstream, but until we have a proper setup in downstream we will not be able to take full advantage of those metrics for Hosted Che

**Comment by mkuznyetsov** [comment]
we already have in Grafana "Workspace Detailed" section with heatmaps, which could be used for getting "The % of workspaces started in under N seconds"

we also have "The % of workspaces started successfully" displayed on Grafana, yet we don't have the "The % of workspaces stopped successfully"

**Comment by aditya-konarde** [comment]
/cc @skryzhny can you please provide some feedback on the metrics and provide suggestions here? 

Beyond the classic USE and RED metrics, we can look at some application specific metrics other than the current ones that either: 
- Provide business insights to someone running Eclipse Che (number of workspaces, number of users, number of signups) 
- Provide feedback into development (Workspace start time, average runtime of a workspace, workspace aggregate errors)

I believe we're already well covered looking at the dashboard. But may have scope fro some more :)
