### ISSUE TITLE
IDE2 Backlog

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13280]
### Priority bugs
- [ ] Interaction with Tasks when running multiple ones #13396

### Next sprint proposals
- [ ] Container-plugin: add ability to copy websocket endpoint url #13397
- [ ] Use @eclipse-che/api in User Dashboard #15267
- [ ] Code clean up in User Dashboard #15256
- [ ] Unexpected filtering in plugins view in Che-Theia #14754
- [ ] Mark plugin logs with plugin name https://github.com/theia-ide/theia/issues/2458
- [ ] mocking plugin API [TODO issue] 40sp
- [ ] Show a confirmation dialog when Ctrl+W is pressed in the terminal #13580
- [ ] che plugins view should have proper icons for each plugins/extensions https://github.com/eclipse/che-theia/issues/261 - 3d
- [ ] Install plugin in specific container [ analysing ] https://github.com/eclipse/che-theia/issues/246 -no more than 3-4 d 
- [ ] Uninstall VSCode extensions https://github.com/eclipse/che-theia/issues/245 - 3d
- [ ] Display information about the plugin in editors section ? https://github.com/eclipse/che-theia/issues/247
- [ ] Add ability to disable/remove default plug-ins in Che Theia https://github.com/eclipse/che-theia/issues/159 
- [ ] After restart Eclipse CHE workspace che-theia should not open empty terminals https://github.com/eclipse/che/issues/13167 - 4d
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740 - 5d
- [ ] Show a confirmation dialog when Ctrl+W is pressed in the terminal #13580
- [ ] Che Theia should display a warning if the workspace has deprecated plugin #14423 8d
- [ ] `/projects/.devfile.yaml` synchronized with the current workspace devfile #13983 6d

### Technical debts 
(_some time in sprint is allocated to handle those issues_ )
- [ ] Users inconsistance when run nodejs script https://github.com/eclipse/che-theia/issues/60
- [ ] Container-plugin: add ablity to copy websocket endpoint url https://github.com/eclipse/che/issues/13397

### Theia bugs
- [ ] plugin code gets loaded outside of plugin host process https://github.com/theia-ide/theia/issues/4271
- [ ] plugin formatting providers are not applied  https://github.com/theia-ide/theia/issues/4686
- [ ] Set focus to another editor if current one is closed  https://github.com/theia-ide/theia/issues/4502
- [ ] plugin system breaks user storage abstraction https://github.com/theia-ide/theia/issues/4488
- [ ] Add plugin validator https://github.com/theia-ide/theia/issues/4945

**Comment by sunix** [comment]
could we close that one ? @evidolob
