### ISSUE TITLE
Platform-2019-06-12 (Sprint: 167)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13337]
### Features related to Devfile

- [x] Initial setup of Che Defvile registry | https://github.com/eclipse/che/issues/13353 | 5
- [x]  Deploy and use public che devfile registry on https://che.openshift.io infrastructure | https://github.com/eclipse/che/issues/13355 |  5
- [x] [Devfile] Make specVersion and name more K8s-like | https://github.com/eclipse/che/issues/13336 | 5
- [x] Perform schema and integrity validation on creating a workspace from Devfile | https://github.com/eclipse/che/issues/13315 | 5
- [x] Add VS code extensions preferences in workspace configuration | https://github.com/eclipse/che/issues/12992 | 3
- [ ] `Annotation key is too long` error when starting workspace, created from devfile | https://github.com/eclipse/che/issues/13303 | 5

### Features related to Monitoring/Tracing
- [x] [Metrics] Observability requirements for hosted Che | https://github.com/eclipse/che/issues/13270 | 3

### Other tasks
- [ ] Workspace RAM limit doesn't work with sidecar-based workspaces | https://github.com/eclipse/che/issues/11424 | 13

### Finalize issues started in the previous sprint.

- [x] [POC] tasks and launch configuration as part of Devfile | https://github.com/eclipse/che/issues/13057 | 2
- [x] Introduce registryUrl field for cheEditor/chePlugin components | https://github.com/eclipse/che/issues/13104 | 5
- [x]  Document tracing usecase | https://github.com/eclipse/che/issues/12545 | 3
- [x]  Error trying to start wsagent when loading a devfile https://github.com/eclipse/che/issues/13448

### Unplanned
- [x] GitHub oAuth authorization does not work with Red Hat SSO 7.3 https://github.com/eclipse/che/issues/13380
- [x] Workspace is not starting, when k8s StorageClass has volumeBindingMode=WaitForFirstConsumer https://github.com/eclipse/che/issues/12889
- [x] wsmaster bootstrap fails on k8s using nightly build https://github.com/eclipse/che/issues/13463
- [ ] Deprecate storing of workspaces converted from Devfile https://github.com/eclipse/che/issues/13423

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Lukas Krejci | 15d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 54  | 31 |
