### ISSUE TITLE
IDE2-2019-06-12 (Sprint: 167)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13335]
### Sprint Goals:
1. Implement flow to install a plugin from the IDE - GA
2. High priority fixes
3. Theia bugs
4. Own plugins

**Che 7 GA Epic** - https://github.com/eclipse/che/issues/12696

## 1. Implement flow to install a plugin from the IDE
- [x] Provide ability to easily add a VSCode extension https://github.com/eclipse/che-theia/issues/209 - 3d
- [ ] Display built-in plugins (provided by docker image) https://github.com/eclipse/che-theia/issues/244 - 3d
- [ ] Uninstall VSCode extensions https://github.com/eclipse/che-theia/issues/245 - 2d
- [ ] Install plugin in specific container [ analysing ] https://github.com/eclipse/che-theia/issues/246

_Postpone:_
- [ ] Display information about the plugin in editors section ? https://github.com/eclipse/che-theia/issues/247
- [ ] Add ability to disable/remove default plug-ins in Che Theia https://github.com/eclipse/che-theia/issues/159 

## 2. High priority fixes
- [x] [UD] Workspace creation from devfile #13058 - 3d
- [x] Fix animation on creating a workspace from a factory  https://github.com/eclipse/che/issues/13365 - 1d
- [x] Duplication of what is typed in terminal view can happen https://github.com/eclipse/che/issues/13165 PR
- [x] My workspace view empty if no user defined container https://github.com/eclipse/che-theia/issues/214 - 2d
- [x] Che Task which contains a command with single-quotes doesn't work properly.  https://github.com/eclipse/che/issues/13323 - 3d
- [ ] VSCode-Java does not have Java File Icons https://github.com/eclipse/che/issues/12990 depends on https://github.com/eclipse/che-theia/issues/117
- [ ] Theia remote plug-in runtime in sidecar container improvement https://github.com/eclipse/che/issues/13387

## 3. Theia bugs 
- [x] Method not implemented: DocumentDataExt.acceptLanguageId https://github.com/theia-ide/theia/issues/4294 - 4d
- [x] vscode.languages.setTextDocumentLanguage is not a function https://github.com/theia-ide/theia/issues/4448 - 4d
- [x] FileUri gets loaded in browser https://github.com/theia-ide/theia/issues/4272 - 2d

## 4. Own plugins
- [ ] Implement find text for terminal widget https://github.com/theia-ide/theia/issues/5179 Aleksandr

## Other  issues:
- [ ] Create UBI based images for che-theia https://github.com/eclipse/che-theia/issues/219 - no more 5 d
- [ ] Che-theia: progress in status bar when performing any git clone (factory, workspace sync, git clone command) https://github.com/eclipse/che/issues/12564 [TODO check a dependency issue] PR
- [ ] Apply formatting and linting to the WorkspaceLoader #13281  - 1d
- [ ] workspace-loader doesn't recognize when workspace start fails immediately after start request is sent https://github.com/eclipse/che/issues/13209 - 3d
- [x] Handle incompatible Factories between Che 6 and Che 7 https://github.com/eclipse/che/issues/12918 - 2d
- [ ] che:theia init should have an option to use local sources instead of cloning the che-theia repo https://github.com/eclipse/che-theia/issues/208 - 5d
- [ ] Do not ask user in which container run command if it could be figured out from the workspace panel tree https://github.com/eclipse/che-theia/issues/222
- [x] Fix animation on creating a workspace from a factory #13365
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871

## Pending PR
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [ ] Dashboard: fail build when webpack has errors #12911 
- [x] Che Plugins View https://github.com/eclipse/che-theia/pull/162 (Vitaliy)
- [ ] Progress extension 
https://github.com/theia-ide/theia/pull/5176
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1nvYqbMQJQrxfUx0DZNYbdagqLhNTt23lb7-A8pQ-ql8/edit)
