### ISSUE TITLE
IDE-2019-06-12 (Sprint: 167)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#13343]
### Sprint goals

1. Add needed VS Code API for finalizing Kubernetes Plugin Support 
2. Include existing GitHub PullRequest  plugin in Che Theia IDE
3. Che commands should be first class citizens in Theia
4. Check last released version of VS Code OpenShift Extension in Che Theia
 
### Sprint details:
_**Che 7 GA Epic - #12696**_ 

#### 1. Add needed VS Code API for finalizing Kubernetes Plugin Support
- [ ] [k8s plugin] Kubernetes: Run/Debug commands can't locate a project's Dockerfile #13345
- [ ] [k8s plugin] Kubernetes:Run command should work w/o Docker #13316

#### 3. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [ ] [plug-in] VS Code Git extensions https://github.com/theia-ide/theia/issues/4266
- [ ] POC: Extend pull request flow to add Factory in the comments (#10282)
- [ ] [Plugin-Api] Apply 'comment.createCommentController' function theia-ide/theia#5076

#### 4. Che commands should be first class citizens in Theia #12709 
- [ ] When editing the pre-defined tasks, all tasks should be displayed in the tasks.json file #13392
- [ ] Can not run Configured task https://github.com/theia-ide/theia/issues/5064
- [ ] Recently used tasks section should respect configured tasks https://github.com/theia-ide/theia/issues/5067
- [ ] Contributed Task Configuration question https://github.com/theia-ide/theia/issues/4928
- [ ] Provide curated list of containers to run tasks #13390
- [ ] Notifications on Tasks started/ended are missing context #13394 (PR: [theia#5296](https://github.com/theia-ide/theia/pull/5296))

#### Merge-ready PRs  
- [x] Introduce SCM Plugin-Api theia-ide/theia#4279
- [ ] [Plugin-Api] Add stub implementation of the VsCode comment Plugin-Api  theia-ide/theia#5118
- [x] [Plugin-Api] Add stub implementation of window.registerUriHandler()  theia-ide/theia#5120
- [x] Fix "Converting circular structure to JSON" Error  theia-ide/theia#5121

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 11 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
| **Velocity** | |  |
### Retrospective Comments
