### ISSUE TITLE
Languages Sprint 167 (M-4)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13376]
May 22-June 12

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 4 | 2 | 1
@tolusha | 6 | 4 | 5
@svor | 15 | 10 | 11
@vrubezhny | 15 | 9 | 6
@JPinkney | 15 | 10 | 9

# Priorities
1. Finish PHP
2. Polish Che 7 plugins

@tolusha @tsmaeder Prepare Theia Conf Presentation: 5d calendar time, attend Theia dev conf

All testing must be done on minishift!

# Candidate Issues
- [x] Realign features of YAML Language Server with JSON Language Server https://github.com/redhat-developer/yaml-language-server/issues/142 5d @JPinkney
- [x] Update vscode-java to latest release #13378 1d @svor 
- [x] Provide an image with Java 11 for remote plugins #13225 1d @svor 
- [x] Update vscode-java-debug to latest https://github.com/eclipse/che/issues/13216, https://github.com/theia-ide/theia/issues/5077 3d (timebox) @svor 
- [x] PHP Language Support https://github.com/eclipse/che/issues/12772 (8d @vrubezhny)
  - [x] Che 7 plugin: PHP Debugger #12795
  - [x] Che 7 plugin: PHP Language Server #12797
- [ ] Eclipse Keybindings Extensions has no Effect https://github.com/theia-ide/theia/issues/5113 @JPinkney  (3d)
- [x] Clean up theia-endpoint-runtime directory structure https://github.com/eclipse/che-theia/issues/200 5d  @tolusha 
- [x] PHP Stack (#13307) 3d @svor 
- [ ] Che Server Developer Stack #13106 1d @tsmaeder  
- [x] Implement 'workbench.action.debug.restart` (vscode-java-debug) command https://github.com/theia-ide/theia/issues/5102 (@vrubezhny)
- [ ] Plug-ins leaking CodeLens, etc. https://github.com/theia-ide/theia/issues/4472 3d @svor 
- [ ] No error when extension dependency is not found https://github.com/theia-ide/theia/issues/4504
- [ ] Add section about adding language support https://github.com/eclipse/che-docs/issues/718
- [x] Add section about adding debugger support https://github.com/eclipse/che-docs/issues/719
- [x] Implement editor.action.rename comand https://github.com/theia-ide/theia/issues/5215 (@JPinkney) (0.5d)
- [x] Implement editor.action.formatXXX commands https://github.com/theia-ide/theia/issues/5216 (@JPinkney ) (0.5d)
- [ ] Implement "DeclarationProvider" API VS Code API https://github.com/theia-ide/theia/issues/5213 @vrubezhny 4d
- [ ] Implement editor.action.gotoDeclaration https://github.com/theia-ide/theia/issues/5214 @vrubezhny 2d 
# From Last Sprint

- [ ] Missing API for Language Support Che 7 Plug-Ins #13007

# Blocked issues 
# Unplanned Issues
# Open PR's
- [x] Typescript LS should NOT open `tsconfig.json` automatically when opening a typescript file https://github.com/eclipse/che/issues/13076 2d @tolusha 
  - [x] PR https://github.com/theia-ide/theia/pull/5075
  - [x] CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19755
- [x] VS Code xml extension not working with error UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'editor.autoClosingBrackets' of undefined  https://github.com/eclipse/che/issues/12536 https://github.com/theia-ide/theia/pull/5149
- [x] Keybindings view not updating after installing a plugin that contributes keybindings https://github.com/theia-ide/theia/issues/5205

Previous Sprint: https://github.com/eclipse/che/issues/13227
