### ISSUE TITLE
IDE2-2019-07-03 (Sprint: 168) 

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13478]
### Sprint Goals:
1. High priority fixes and improvement 
2. Implement flow to install a plugin from the IDE - GA
3. Own plugins

**Che 7 GA Epic** - https://github.com/eclipse/che/issues/12696
## 1. High priority fixes and improvement 
- [x] Add new 'user' namespace in Che plugin API https://github.com/eclipse/che/issues/13518 need for Che 7 Git + SSH Flow - 4d
- [ ] Che 6 workspaces warning: improvements https://github.com/eclipse/che/issues/13476 - 2d
- [x] Preview URL not displayed while accessible https://github.com/eclipse/che/issues/13357 - 3d
- [ ] che-theia should have autosave activated by default https://github.com/eclipse/che-theia/issues/216 - 3d
- [ ] Tooltip in workspace panel should be showing the complete command  https://github.com/eclipse/che/issues/13149 - 2d
- [ ] Che workspace panel improvements https://github.com/eclipse/che/issues/13393 - 5d
- [ ] Interaction with Tasks when running multiple ones https://github.com/eclipse/che/issues/13396

## 2. Implement flow to install a plugin from the IDE
- [x] Display built-in plugins (provided by docker image) https://github.com/eclipse/che-theia/issues/244 - PR
- [ ] che plugins view should be available by default in the left side bar https://github.com/eclipse/che-theia/issues/260 - 2d
- [ ] che plugins view should have proper icons for each plugins/extensions https://github.com/eclipse/che-theia/issues/261 - 3d
- [ ] Install plugin in specific container [ analysing ] https://github.com/eclipse/che-theia/issues/246 -no more than 3-4 d 
- [ ] Uninstall VSCode extensions https://github.com/eclipse/che-theia/issues/245 - 3d

_Postpone:_
- [ ] Display information about the plugin in editors section ? https://github.com/eclipse/che-theia/issues/247
- [ ] Add ability to disable/remove default plug-ins in Che Theia https://github.com/eclipse/che-theia/issues/159 

## 3. Own plugins
- [ ] Implement find text for terminal widget https://github.com/theia-ide/theia/issues/5179 Aleksandr

## Other  issues:
- [ ] After restart Eclipse CHE workspace che-theia should not open empty terminals https://github.com/eclipse/che/issues/13167 - 4d
- [ ] Create UBI based images for che-theia https://github.com/eclipse/che-theia/issues/219 - no more 2d
- [x] Apply formatting and linting to the WorkspaceLoader #13281  - PR and CQ
- [x] workspace-loader doesn't recognize when workspace start fails immediately after start request is sent https://github.com/eclipse/che/issues/13209 - 1d
- [ ] Create an issue "Adapt Docker file to use local che-theia folder" https://github.com/eclipse/che-theia/issues/208
- [ ] Refactor plugin lifecycle code https://github.com/theia-ide/theia/issues/3871
- [ ] Deprecations, DoS warnings, incompatibilities, incorrect/unmet peers: Che Dashboard build is very unstable https://github.com/eclipse/che/issues/11740 - 5d

## Unplanned tasks
- [x] Resize panels become broken and freezes when opened Welcome page... 
 https://github.com/eclipse/che-theia/issues/151

## Pending PR
- [ ] Run Che command in selected container if container doesn't specified in configuration https://github.com/eclipse/che-theia/pull/274
- [ ] Progress extension  https://github.com/theia-ide/theia/pull/5176
- [ ] Remote binary https://github.com/eclipse/che-theia/pull/267
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [ ] Dashboard: fail build when webpack has errors #12911 
- [ ] Progress extension 
https://github.com/theia-ide/theia/pull/5176
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
