### ISSUE TITLE
Platform-2019-07-03 (Sprint: 168) 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13480]
### Features related to Devfile
- [x] Support mountSources for non-plugin tools in devfile | https://github.com/eclipse/che/issues/12554 | 8

### Features related to Monitoring/Tracing
- [x] [Metircs] Time of workspace termination | https://github.com/eclipse/che/issues/13500 | 5

### Other tasks
- [ ] `Annotation key is too long` error when starting workspace, created from devfile | https://github.com/eclipse/che/issues/13303 | 8
- [ ] Deprecate storing of workspaces converted from Devfile | https://github.com/eclipse/che/issues/13423 | 5
- [x] Volume created but the secret with the self-signed cert is not | https://github.com/eclipse/che/issues/13433 | 5
- [x] Che 7 stacks should use version "latest" of plugins | https://github.com/eclipse/che/issues/13426 | 3
- [ ] StackService decommissioning | https://github.com/eclipse/che/issues/13459 | 5
- [ ] Dashboard: provide target k8s namespace information | https://github.com/eclipse/che/issues/13484 | 13
- [x] Legacy environment variables cleanup | https://github.com/eclipse/che/issues/12679 | 5
- [ ] Introduce API that would allow Dashboard get info about target K8s namespace for workspace  https://github.com/eclipse/che/issues/13504

### Finalize issues started in the previous sprint.
- [x] [Devfile] Make specVersion and name more K8s-like | https://github.com/eclipse/che/issues/13336 | 2
- [x] Introduce registryUrl field for cheEditor/chePlugin components | https://github.com/eclipse/che/issues/13104 | 2

### Unplanned
- [x] Cannot create workspace from devfile via API when entrypoint is overridden | https://github.com/eclipse/che/issues/13422
- [x] Guidance for a user who wants to create their own workspace using a Devfile https://github.com/eclipse/che/issues/13538 
- [x] Error occurred during creation a workspace from devfile https://github.com/eclipse/che/issues/13533 
- [ ] New devfile based stacks should contain samples https://github.com/eclipse/che/issues/13529
- [ ] PKIX error and impossible to start workspaces on OCP 4.1 https://github.com/eclipse/che/issues/13607

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Lukas Krejci | 15d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 61  | 26 |
#### Retrospective Comments
 - Deprecate storing of workspaces converted from Devfile | https://github.com/eclipse/che/issues/13423  - are almost done only final checkups left.
 - Majority of the tasks that were left caused by the switch of priority at the beginning of the sprint.
   We have mainly focused on  Guidance for a user who wants to create their own workspace using a Devfile https://github.com/eclipse/che/issues/13538 and  New devfile based stacks should contain samples https://github.com/eclipse/che/issues/13529
