### ISSUE TITLE
Dashboard: provide target k8s namespace information 

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13484]
![image](https://user-images.githubusercontent.com/606959/59027345-08a4dd80-8859-11e9-94de-f457a50f658e.png)

When creating a Che workspace from the dashboard a user doesn't have any clue on in which Kubernetes namespace the workspace will be created. And more important the user doesn't know the resources that are available (compute resource quota, storage resource quota and object count quota).

We should at least provide informations about the namespace name and the available memory (the compute-resources quota memory limit that is currently not used).

One interesting thing would be to let the user change/select the namespace.

Storage details may be interesting too.

- [x] **severity/P1** API: List of available k8s namespaces for the workspace creation | https://github.com/eclipse/che/issues/14376
- [x] **severity/P1** API: Ability to specify k8s namespace where a user wants to create/start his workspace | https://github.com/eclipse/che/issues/14379
- [x] **severity/P1** Dashboard: Dashboard: view and change target namespace | #14389 
- [ ] **severity/P1** API: Expose resources information about K8s namespaces #13504
- [ ] **severity/P2** API: Provide a way to test if there are resources name conflicts that may happen during workspace creation/start https://github.com/eclipse/che/issues/14382

cc @slemeur @skabashnyuk @ashumilova

**Comment by l0rd** [comment]
cc @ibuziuk

**Comment by sleshchenko** [comment]
It's blocked by https://github.com/eclipse/che/issues/13504

**Comment by ibuziuk** [comment]
cc: @alexeykazakov

**Comment by sunix** [comment]
@l0rd should we move it to 7.3.0 or later as https://github.com/eclipse/che/issues/13504 is planned for 7.3.0 ?

**Comment by sunix** [comment]
I moved https://github.com/eclipse/che/issues/14389 to 7.3.0

**Comment by skabashnyuk** [comment]
@l0rd Does it make sense to add target k8s namespace to devfile and ability to override this value with the factory. Alexey Kazakov is asking about something like that. WDYT?
