### ISSUE TITLE
Language Team Sprint 168 (M-5)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13509]
June 13-July 2

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 12 | 6 | 5
@tolusha | 7 | 5 | 4
@svor | 12 | 7 | 7
@vrubezhny | 14 | 8 | 2
@JPinkney | 12 | 7 | 6.5 

# Priorities
All testing must be done on minishift!

# Candidate Issues
- [x] Provide a Language Servers troubleshooting document #13485
  - [x] Python Go NodeDebug NodeDebug2 Typescript
  - [x] Camel
  - [x] Java Netcoredebug Omnisharp
  - [x] Intelephense PHP-Debug
  - [x] XML YAML
- [ ] https://github.com/redhat-developer/yaml-language-server/issues/151 @JPinkney 2d
- [x] Update Memory Settings for devfiles #13510
- [x] Update all languages plugins to latest VS Code extensions #13521
  - [x] Python Go NodeDebug NodeDebug2 Typescript
  - [x] Camel
  - [x] Java C# Netcoredebug
  - [x] Intelephense
  - [x] XML YAML
- [x] Make devfile from PHP Stacks #13528 @svor 2d
- [ ] Che Server Developer devfile #13106 1d @tsmaeder  
- [x] vscode-plugin: debug.registerDebugAdapterDescriptorFactory and debug.registerDebugAdapterTrackerFactory are not implemented. https://github.com/theia-ide/theia/issues/4804 @tolusha 2d
- [x] Add section about adding language support https://github.com/eclipse/che-docs/issues/718 @svor 2d
- [ ] Write up documentation form Theia dev conf presentation (@tsmaeder 3d)
- [ ] register monaco commands used by VS Code extensions https://github.com/theia-ide/theia/issues/4247 (@JPinkney  4d)
- [ ] Warning when trying to open Java LS Log file #13428
- [ ] Plug-ins leaking CodeLens, etc. https://github.com/theia-ide/theia/issues/4472 @vrubezhny 3d

# From Last Sprint
- [ ] Eclipse Keybindings Extensions has no Effect https://github.com/theia-ide/theia/issues/5113 @JPinkney  (3d)
- [ ] No error when extension dependency is not found https://github.com/theia-ide/theia/issues/4504
- [ ] Missing API for Language Support Che 7 Plug-Ins #13007

# Blocked issues 
# Unplanned Issues
- [x] Not enough default memory limit for typescript remote plugin #13512
- [ ] https://github.com/theia-ide/theia/issues/5013
# Open PR's
https://github.com/theia-ide/theia/pull/5379

Previous Sprint: https://github.com/eclipse/che/issues/13376
