### ISSUE TITLE
IDE-2019-07-03 (Sprint: 168)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#13524]
### Sprint goals

1. Kubernetes Plugin Support
2. Include existing GitHub PullRequest  plugin in Che Theia IDE
3. Che commands should be first class citizens in Theia
4. Allow Che 7 Git + SSH Flow #13494
 
### Sprint details:
_**Che 7 GA Epic - #12696**_ 

#### 1. Kubernetes Plugin Support
- [ ] [k8s plugin] Kubernetes: Run/Debug commands can't locate a project's Dockerfile #13345

#### 2. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [ ] [plug-in] VS Code Git extensions https://github.com/theia-ide/theia/issues/4266
- [ ] POC: Extend pull request flow to add Factory in the comments (#10282)

#### 3. Che commands should be first class citizens in Theia #12709 
- [ ] When editing the pre-defined tasks, all tasks should be displayed in the tasks.json file #13392
- [ ] Provide curated list of containers to run tasks #13390

##### Wait on merge:
- [x] Notifications on Tasks started/ended are missing context #13394 (PR: [theia#5296](https://github.com/theia-ide/theia/pull/5296))
- [ ] Can not run Configured task https://github.com/theia-ide/theia/issues/5064 (PR [theia#5313]( https://github.com/theia-ide/theia/pull/5313))
- [ ] Recently used tasks section should respect configured tasks https://github.com/theia-ide/theia/issues/5067 (PR [theia#5313]( https://github.com/theia-ide/theia/pull/5313))
- [ ] [k8s plugin] Kubernetes:Run command should work w/o Docker #13316 (PR [vscode-kubernetes-tools#559](https://github.com/Azure/vscode-kubernetes-tools/pull/559))

#### 4. Allow Che 7 Git + SSH Flow #13494
- [ ] 🦄mount the SSH keys as secrets in all workspace containers #13520
- [ ] 🦄Enable the SSH plugin 

#### Merge-ready PRs  
- [ ] [Plugin-Api] Add stub implementation of the VsCode comment Plugin-Api  theia-ide/theia#5118
- [ ] [tasks] Fix execution of Configured tasks theia-ide/theia#5313
- [x] Update message about task start/stop theia-ide/theia#5296
