### ISSUE TITLE
Che registries (plugin+devfile) should be part of Che deployment

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13557]
By default Che plugin and Che devfile registries should be deployed along with the wsmaster. This is mainly needed to make sure that the version of the wsmaster and the version of those registries are always consistent. A user should still be able to use an already deployed registry but the default should be do deploy a new instance (as per keycloak and postgres for multi-user Che).

Sub tasks: 

- [x] Update Che Helm Chart https://github.com/eclipse/che/issues/13633
- [x] Update Che Operator https://github.com/redhat-developer/rh-che/issues/1476
- [x] Add the registries in Che release process (build and tag nightly and release images) https://github.com/eclipse/che/issues/13953

**Comment by l0rd** [comment]
cc @slemeur @nickboldt @rhopp

**Comment by tsmaeder** [comment]
So the idea is to have a registry for "latest", one for "next", etc.?

**Comment by l0rd** [comment]
@tsmaeder `nightly`, `latest`, `7.0.0`, `7.1.0` etc...

**Comment by skabashnyuk** [comment]
AFAIK last time we think about such kind of issue was minimum memory requirements to start che locally. Is this something that is no longer in our list?

**Comment by skabashnyuk** [comment]
@l0rd can you confirm that increased memory requirement ~500m for local development are acceptable and expected.

**Comment by l0rd** [comment]
Do we need 250MB per registry? Can set required memory to 50MB?

>

**Comment by skabashnyuk** [comment]
Don't know yet, we can try. Not sure about 50mb may be 100mb.

**Comment by sparkoo** [comment]
From @metlos's experiments, 16MB is minimum to run registry without performance drop. I've set `memoryLimit: 32Mi`and `memoryRequests: 16Mi` in #13890.
