### ISSUE TITLE
IDE2-2019-07-23 (Sprint: 169)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#13638]
### Sprint Goals:
1. GA bug fix
2. Testing Che 7 GA

**Che 7.0.0 Endgame Plan** #13637
## 1. GA bug fix
- [x] Impossible to get a terminal in a workspace https://github.com/eclipse/che/issues/13584
- [x] Theia doesn't work with self signed certs #13574 - PR
- [x] Preview URL not displayed while accessible #13357
- [ ] Impossible to delete a project #13621 - 1d
- [ ] Che Plugins panel is broken on minishift eclipse/che-theia#296 
- [x] Remove UD "Diagnostics" because it's not working #13525 - 1d
- [ ] Remove stacks menu + page -1d
- [x] Properly display projects defined in devfile and import project on workspace creation - 5d Ann 
- [x] Deleted `projects:` in devfiles.yaml on creating workspaces. #13678 - 1d
- [x] At the launch of the workspace, the IDE "GWT" is loaded instead of "Theia" IDE #13681  - revert original fix

## Pending PR
- [ ] Run Che command in selected container if container doesn't specified in configuration https://github.com/eclipse/che-theia/pull/274
- [ ] Progress extension  https://github.com/theia-ide/theia/pull/5176
- [ ] Remote binary https://github.com/eclipse/che-theia/pull/267
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [ ] Dashboard: fail build when webpack has errors #12911 
- [ ] Progress extension 
https://github.com/theia-ide/theia/pull/5176
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
