### ISSUE TITLE
Languages Sprint 169

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#13679]
July 3-July 23

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 10 | 5 | 5
@tolusha | 9 | 5 | 4.5
@svor | 10 | 6 | 6
@vrubezhny | 0
@JPinkney | 0

# Priorities
All testing must be done on minishift!

# Candidate Issues
- [ ] Review https://github.com/eclipse/che-docs/pull/746 (@tsmaeder)
- [x] Provide a Language Servers troubleshooting document #13485
  - [x] Camel @tsmaeder 0.5d
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic https://github.com/eclipse/che/issues/13427 @tsmaeder 2d
- [x] Some Projects don't work with Java 11 based Java plugin https://github.com/eclipse/che/issues/13547 @svor 
  - [x] Java 8, 11: 2d
  - [ ] 1.5d per version (to be determined)
- [x] Add activationEvents to omnisharp and netcoredbg plugins https://github.com/eclipse/che/issues/13781 (@svor) 0.5d
- [ ] Finish ["Retrieving logs" document](https://docs.google.com/document/d/182PBN5LBNTlbhsqqsb5QHg9t5HNK3rSLrnIMPSGjyN0/edit#heading=h.tyhhnnuon2rs)
  - [ ] Port section on language servers from language server troubleshooting document 0.5d (@tsmaeder)
  - [x] Kubernetes Events 0.5d @tolusha 
  - [x] Che Server Logs 0.5d @tolusha 
  - [x] Theia (IDE) logs 0.5d @tolusha 
- [ ] Timeboxed (2d) [tests with real projects](https://docs.google.com/document/u/1/d/127-nePk6TUmsGX9FeWNmV9VtRnVrehh2iwbdRGhKuzk/edit?usp=drive_web&ouid=106332148868337579848)
  - [x] Golang (@tolusha) 1d
  - [ ] Typescript (@JPinkney)
  - [x] Python (@tolusha)
  - [x] C# (@svor)
  - [ ] Java (@tsmaeder)

# From Last Sprint

# Blocked issues 
# Unplanned Issues

Previous Sprint: https://github.com/eclipse/che/issues/13376
