### ISSUE TITLE
Platform-2019-07-23 (Sprint: 169)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13682]
### Description
- [x] Deprecate storing of workspaces converted from Devfile | https://github.com/eclipse/che/issues/13423 | 2
- [x] Update Che Helm Chart: Che registries (plugin+devfile) should be part of Che https://github.com/eclipse/che/issues/13633 8
- [x] Admin guide for user authentication and authorization | https://github.com/eclipse/che/issues/13668 | 8
- [x] Multi-user deploy fails on minikube | https://github.com/eclipse/che/issues/13625 | 5
- [x] Clarify names of default stacks | https://github.com/eclipse/che/issues/13592 | 3
- [ ] StackService decommissioning | https://github.com/eclipse/che/issues/13459 | 8
- [x] New devfile based stacks should contain samples | https://github.com/eclipse/che/issues/13529 8

### Unplanned
- [x] Update the use of "Machines" in Che https://github.com/eclipse/che/issues/13703
- [x]  `Annotation key is too long` error when starting workspace, created from devfile https://github.com/eclipse/che/issues/13303
-  [ ] Unable to create workspace if URL reference is used for component https://github.com/eclipse/che/issues/13861
- [x] Failed to start Kubernetes runtime of workspace. Cause: Server 'theia' not available https://github.com/eclipse/che/issues/13838
- [ ] Test how https is working on k8s and OpenShift  https://github.com/eclipse/che/issues/13869
- [x] keycloak image init containers shouldn't do post-install stuff https://github.com/eclipse/che/issues/13870
 ## Sprint Analysis
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 14d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 7d | 
| Michal Vala | 14d | 
| Lukas Krejci | 8d | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 42  | 34 |
