### ISSUE TITLE
IDE-2019-07-23 (Sprint: 169)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#13845]
### Sprint goals

1. Include existing GitHub PullRequest  plugin in Che Theia IDE
2. Allow Che 7 Git + SSH Flow #13494
3. Bug fix 

 
### Sprint details:
**_Che 7.0.0 Endgame Plan #13637_**

#### 1. Include existing GitHub PullRequest plugin in Che Theia IDE (#11867)
- [x] [plug-in] VS Code Git extensions https://github.com/theia-ide/theia/issues/4266
- [ ] POC: Extend pull request flow to add Factory in the comments (#10282)

#### 2. Allow Che 7 Git + SSH Flow #13494
- [x] 🦄mount the SSH keys as secrets in all workspace containers #13520 

#### Other tasks:
- [x] When editing the pre-defined tasks, all tasks should be displayed in the tasks.json file #13392

#### Merge-ready PRs  
- [x] [tasks] Fix execution of Configured tasks theia-ide/theia#5313
- [x] Can not run Configured task https://github.com/theia-ide/theia/issues/5064 (PR [theia#5313]( https://github.com/theia-ide/theia/pull/5313))
- [x] Recently used tasks section should respect configured tasks https://github.com/theia-ide/theia/issues/5067 (PR [theia#5313]( https://github.com/theia-ide/theia/pull/5313))
- [ ] [k8s plugin] Kubernetes:Run command should work w/o Docker #13316
