### ISSUE TITLE
Platform-2019-08-13 (Sprint: 170)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13847]
### Description

- [x] Admin guide for user authentication and authorization | https://github.com/eclipse/che/issues/13668 | 3
- [x] `Annotation key is too long` error when starting workspace, created from devfile | https://github.com/eclipse/che/issues/13303 | 2
- [x] **PR ready** StackService decommissioning | https://github.com/eclipse/che/issues/13459 | 5
- [x] Unable to create workspace if URL reference is used for component | https://github.com/eclipse/che/issues/13861 | 5
- [x] Test how https is working on k8s and OpenShift | https://github.com/eclipse/che/issues/13869 | 8
- [x] Eclipse Che Installation in AWS EC2, failure to start a workspace | https://github.com/eclipse/che/issues/13690 | 5
- [x] Deprecate and remove /api/devfile method | https://github.com/eclipse/che/issues/13867 | 5
- [x] Keycloak uses H2 database in Che on Helm Kubernetes deployment | https://github.com/eclipse/che/issues/13919 | 3
- [x] Spark: PoC for single-host/default-host mode for Che Theia | https://github.com/eclipse/che/issues/14002 | 8
- [x] **PR ready**NPE when a devfile command references theia | https://github.com/eclipse/che/issues/13842 | 5
- [x] **PR ready**Workspace creation fails if a workspace with the same name already exist | https://github.com/eclipse/che/issues/13794 | 8
- [x] **PR ready** Unable to accept factory with workspace, which name would collide with existing workspace name | https://github.com/eclipse/che/issues/13683 0
- [x] Retest and unify all devfiles with samples | https://github.com/eclipse/che/issues/13863 | 8

### Finalize issues started in the previous sprint.
- [x] TLS and multi-host are incompatible when using Helm https://github.com/eclipse/che/issues/13986
- [x] When TLS is enabled the default should be multi-host strategy  https://github.com/eclipse/che/issues/13996
- [x] When TLS is enabled single user should be the default  https://github.com/eclipse/che/issues/13997

### Unplanned
- [x] [Keycloak] The body of the email-verification was broken. https://github.com/eclipse/che/issues/13917
- [ ]  PKIX error and impossible to start workspaces on OCP 4.1 | https://github.com/eclipse/che/issues/13607
- [x] Enable email listener in Keycloak  https://github.com/eclipse/che/issues/14060
- [x] Make https://github.com/redhat-developer/devfile/blob/master/devfile_next.png diagram up to date https://github.com/eclipse/che/issues/14123
- [x] Apply the same MemoryLimit in helm chars as it set by che-operator https://github.com/eclipse/che/issues/14100
-  [ ] nodejs-mongo devfile sample issues https://github.com/eclipse/che/issues/14009
- [ ] Impossible to set boolean value for preferences via devfile https://github.com/eclipse/che/issues/14131 
- [x] Test self-signed certificates for Che on Kubernetes/OS deployed with chectl (helm/operator installers) https://github.com/eclipse/che/issues/14035
- [x] Apply the same MemoryLimit in helm chars as it set by che-operator https://github.com/eclipse/che/issues/14100 
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Michal Vala | 15d | 
| Lukas Krejci | 10d | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 65  | 65 |
