### ISSUE TITLE
Deprecate deploy_che.sh in favor of chectl / operatorhub

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13888]
### Is your task related to a problem? Please describe.
There is a `deploy_che.sh` script used to deploy che before chectl CLI was added.
Now that there are operatorhub and `chectl` this script should be deprecated and removed

### Describe the solution you'd like
- Gather all usage of `deploy_che.sh` script and
 - check if `chectl` is allowing the same kind of options
- create issues if it's not the case

### Describe alternatives you've considered
Open to suggestions

### Additional context
`chectl` is supporting a widely range of deployments than `deploy_che.sh`

### Subtasks

- [x] [Add support for using existing keycloak/postgre in chectl · Issue #15496 · eclipse/che](https://github.com/eclipse/che/issues/15496)
- [x] Che operator should support single-user Che https://github.com/eclipse/che/issues/13420
- [x] feat: Allows to override default values https://github.com/che-incubator/chectl/pull/508
- [x] [Extra option --PersistentVolumeName and --HostPathSource to CheCTL · Issue #15157 · eclipse/che](https://github.com/eclipse/che/issues/15157)
- [x] [chectl: add an ability to debug Che Server · Issue #14976 · eclipse/che](https://github.com/eclipse/che/issues/14976)
- [x] [cheimage parameter tag is applied to all images of Che deployment instead of Che server only · Issue #14898 · eclipse/che](https://github.com/eclipse/che/issues/14898)

**Comment by skabashnyuk** [comment]
@benoitf  wdyt can we extend this task to all content of https://github.com/eclipse/che/tree/master/deploy/openshift ? I believe that chectl + che-operator is the replace of this folder.

**Comment by benoitf** [comment]
@skabashnyuk yes IMHO it includes the whole folder

**Comment by skabashnyuk** [comment]
@rhopp @vparfonov  can you please check if these scripts/yamls are used in CI/CD or tests.
@davidfestal wdyt should we create any issue to implement some functionality that exists in /deploy/openshift but not exists in che-operator. For example, now it's including tracing/monitoring but afaik there is no such functionality in che-operator.

**Comment by l0rd** [comment]
@tolusha I have added subtasks here although I think that instead of adding the support for every single che property here we should think about a generic solution. For example using a convention as looking for environment variables starting with `CHE_` and using them as config maps.

**Comment by tolusha** [comment]
@rhopp 
What are minimal requirements to use `chectl` instead of `deploy.sh` for CI jobs ?
