### ISSUE TITLE
Multiple issues with omnisharp plugin

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#13892]
### Describe the bug

While trying to dogfood Che I found multiple issues with the omnisharp plugin[1]. The workspace was created via Devfile[2].

### Problems:
- [x] [Rename symbol doesn't work](https://github.com/eclipse/che/issues/13906)
- [x] [ Format Document doesn't work](https://github.com/eclipse/che/issues/13907)
- [x] [Markdowns are not displayed in the editor](https://github.com/eclipse/che/issues/13908)
- [x] [Code lenses with references are not clickable](https://github.com/eclipse/che/issues/13910)
- [x] [Theia Omnisharp Plugin doesn't detect new projects](https://github.com/eclipse/che/issues/13739)

[1] - https://github.com/redhat-developer/omnisharp-theia-plugin
[2] - https://raw.githubusercontent.com/svor/files/master/asp.net.Dockerfile

**Comment by tsmaeder** [comment]
@svor to me, these look like errors in the language server, correct?

**Comment by svor** [comment]
@tsmaeder I don't think so. In vscode extension all these features work fine, this extension uses the same language server as we do
