### ISSUE TITLE
IDE2-2019-08-13 (Sprint: 170)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13891]
### Sprint Goals:
1. GA bug fix
2. Testing Che 7 GA

**Che 7.0.0 Endgame Plan** #13637
## 1. GA bug fix
- [x] machine-exec endpoint is not secure https://github.com/eclipse/che/issues/13970
- [x] che:theia init should have an option to use local sources instead of cloning the che-theia repo https://github.com/eclipse/che/issues/13738
- [ ] Browser freezes on Theia IDE opening #14039
- [x] Adapt "Stacks" in UD to Che 7 https://github.com/eclipse/che/issues/13811
- [x] mysql commands do not work via devfile commands (Theia Tasks) https://github.com/eclipse/che/issues/13416
- [x] Cannot create workspace with new project on Dashboard #13991
- [x] Workspace isn't accessible right after installing a plugin https://github.com/eclipse/che/issues/13912
- [x] Remove all workspace-related command from Theia File menu https://github.com/eclipse/che/issues/13909
- [x] Open terminal with non-patched images on OCP 4 fails  https://github.com/eclipse/che/issues/13977 P1 only after all blockers
- [x] Generated Hello World plugin build fails #14028
- [x] Update document explaining how to build Theia docker images #14053

## 2. Testing Che 7 GA 
- [ ] Testing Che with usage of Cloud Native Applications. Examples - https://learn.openshift.com/middleware/ 

## Pending PR
- [ ] CHE-13476 improve CHE-6 workspaces warning  https://github.com/eclipse/che/pull/13506
- [ ] Run Che command in selected container if container doesn't specified in configuration https://github.com/eclipse/che-theia/pull/274
- [ ] Progress extension  https://github.com/theia-ide/theia/pull/5176
- [ ] Remote binary https://github.com/eclipse/che-theia/pull/267
- [ ] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [ ] Dashboard: fail build when webpack has errors #12911 
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
