### ISSUE TITLE
QE-2019-08-13 (Sprint: 170)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#13963]
### Issues tied to objectives
- [x] Create Jenkins job to automate installation Che by using OperatorHub UI on OCP 4.x #13929 3sp
- [x]  Create automated UI test for install Eclipse Che by using OperatorHub UI #13878 5sp

### Unplanned 
- [x] Create Jenkins job for checking custom PRs for che-theia repo #13810
- [x] Fix the #13865 issue (Happy Path test is sometimes failing on "Error highlighting" step) #13985
- [x] [happy-path] Somethimes "Happy Path" test fails on validation of autocomplete #14018
- [x] Fix possible future problem with language server initialization check #13955
- [x] [TS_SELENIUM] Implement method for storing screenshots while tests execution #14079
- [ ] Run E2E Happy path tests as PR check on kubernetes infra. #13473
- [x] Run E2E Happy path tests as PR check on eclipse/che repository #14068
- [x] Run E2E Happy path tests as PR check on che-theia repository #13326
- [x] [happy-path] Invalid url after running Pet clinic application during Happy Path scenario #13973
- [x] Run E2E Happy path tests as PR check on eclipse/che repository #14068
- [x] Jenkins job is green but in pull request it displayes in the "Pending status" #14108
- [x] [Happy Path] Sometimes the "Happy path" test fails when click on "Start debug" button #14141
- [x] [TS_SELENIUM] Implement workaround for avoiding the "#13427" ("Java LS "Classpath is incomplete" warning when loading petclinic") #14104
- [x] [TS_SELENIUM] Implement workaround for bug described in the issue #14121 (Can not access to application by route because of service unavailable) #14124
- [x] [TS_SELENIUM] Implement method for storing screenshots while tests execution #14079

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 10 |
| Total | 85 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | NA |  |

**Comment by l0rd** [comment]
@vkuznyetsov can we close this?
