### ISSUE TITLE
IDE-2019-08-13 (Sprint: 170)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#13968]
### Sprint goals

1. Bug fix 
2. Remove GWT @vparfonov
3. resolve all issues releated to Che 7.0.0 Endgame Plan #13637

**_Che 7.0.0 Endgame Plan #13637_**
 
### Sprint details:
Low priority (if no blockers in End Game plan):
- [ ] Preconfigure git user information from Che user's profile/preferences #13874
- [x] Can not create a new pull request from GitHub plugin #13814
- [x] GitHub plugin doesn't work #13789
- [x] Unable to run command because of Unknown actor CheTask error #13562
- [ ] Stop running task #13737
- [ ] Icons aren't displayed on a contributed view container #13750
- [x] Confusing notification when task is complete #14125
- [x] Variables are not resolved for execution of che commands #14031
- [ ] Improve the way of storage runtime info for Che tasks https://github.com/eclipse/che/issues/13722
