### ISSUE TITLE
Languages Sprint 170

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14016]
July 24-Aug 13

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 7 | 3 | 5
@tolusha | 9 | 6 | 6
@svor | 10 | 6 | 0.5
@vrubezhny | 11 | 7 | 9
@JPinkney | 10.5 | 7 | 2

# Priorities
All testing must be done on minishift!

# Candidate Issues

- [ ] Java LS "Classpath is incomplete" warning when loading petclinic https://github.com/eclipse/che/issues/13427 5d @tsmaeder
- [x] Java-MySQL devfile built app does not work #13938 @svor 0.5d
- [ ] [omnisharp-plugin] Code lenses with references are not clickable #13910
  - [ ] PR: https://github.com/eclipse/che-plugin-registry/pull/199
- [ ] Add support for C/C++ #13698 (@tolusha) 6d timeboxed
  - [ ] PR https://github.com/eclipse/che-theia/pull/401
  - [ ] https://github.com/eclipse/che/issues/14131
  - [ ] PR https://github.com/eclipse/che-devfile-registry/pull/73
  - [ ] PR https://github.com/eclipse/che-plugin-registry/pull/197
  - [ ] https://github.com/eclipse/che/issues/13614
- [ ] Investigate Language server metrics #14017
- [ ] Investigate Testing LSP features #14023
- [ ] Investigate Testing DAP features #14025
- [ ] Finish ["Retrieving logs" document](https://docs.google.com/document/d/182PBN5LBNTlbhsqqsb5QHg9t5HNK3rSLrnIMPSGjyN0/edit#heading=h.tyhhnnuon2rs) 
  - [ ] Port section on language servers from language server troubleshooting document @JPinkney 0.5
- [ ] Che 7 plugin: Update PHP Intelephense to v.1.1.1 - 2019-06-27? #13700 (1d @vrubezhny )
- [x] [tree] RETURN should not expand nodes https://github.com/theia-ide/theia/issues/1142 (@vrubezhny 4d)
- [x] [vscode] No error message if vscode.open command is invoked with resource that doesn't exist  https://github.com/theia-ide/theia/issues/5667 (@vrubezhny 4d)
- [ ] [vscode] TreeItem fails to render if it has a command tied to it  https://github.com/theia-ide/theia/issues/5666

https://bugzilla.redhat.com/show_bug.cgi?id=1732740 @JPinkney 1d
https://bugzilla.redhat.com/show_bug.cgi?id=1733091 @JPinkney 0.5d

# From Last Sprint

# Open Pull Requests
- [ ] Review https://github.com/eclipse/che-docs/pull/746 (@tsmaeder)
# Blocked issues 
# Unplanned Issues

Previous Sprint: https://github.com/eclipse/che/issues/13679

**Comment by sunix** [comment]
@tsmaeder how this can be current-sprint and next-sprint at the same time ?
