### ISSUE TITLE
Minimal Firefox Support

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14015]
## Goal
Eclipse Che is validated on Google Chrome, but should support (and be usable) from other web browsers.

The goal of this epic is to analyze and detail the requirements on providing a minimal support for Firefox.

### Related issues
- [x] Activity tracker doesn't work for firefox #15354
- [x] [bright fonts are not set on dark theme on Firefox](https://github.com/eclipse/che/issues/13442)
- [x] [Dashboard menu items are not aligned](https://github.com/eclipse/che/issues/13309)
- [x] [No scrolling possible when creating workspace](https://github.com/eclipse/che/issues/13236)
- [x] [Console font letters get cut](https://github.com/eclipse/che/issues/13317)
- [x] [Terminal is empty on Firefox](https://github.com/eclipse/che/issues/13736)
- [x] Cannot open command palette in Theia when using Firefox #15145

**Comment by AndrienkoAleksandr** [comment]
I lived some comment about minimal supported Firefox version https://github.com/eclipse/che/issues/13442#issuecomment-553986167

**Comment by azatsarynnyy** [comment]
@slemeur I'm not sure that this one is related to the epic
`Deprecate the obsolete versions of OpenShift and Kubernetes plugins #15140`

I'll exclude it. Are you agree?

**Comment by azatsarynnyy** [comment]
Closing it as all the issues are solved.

**Comment by nickboldt** [comment]
To make it easier to know when a feature is implemented, please make sure when you close an issue it's not still in the blacklog, but in the sprint/fixversion/milestone in which it's delivered. 

Assuming based on date that this was done for 7.7.

**Comment by azatsarynnyy** [comment]
Thanks, @nickboldt! I'll take it into account.
