### ISSUE TITLE
IDE2-2019-09-03 (Sprint: 171)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#14140]
### Sprint Goals:
1. Che 7.1 che-theia fixes and improvements
2. Che 7.1 Dashboard fixes

## 1. Che 7.1 che-theia fixes and improvements
- [ ] Theia remote plug-in runtime in sidecar container improvement #13387 - 7d
- [ ] White labelling capabilities for Che 7 #14110 - First part Dashboard and investigating che-theia 5d
- [x] plugin panel: Plugin view shouldn't show all the version of the plugin #13913 5d
- [x] Icons aren't displayed on a contributed view container #13750 6d
- [x] Remove the view "Plugins" since we have "Che Plugins" #13670 PR to merge

## 2. Che 7.1 Dashboard fixes
 - [x] Dashboard plugins list should show one entry for each plugin, with a dropdown to select version. #13566 PR to merge 7.0!!!
- [x] User Dashboard takes only 'globalMemoryLimit' from devfiles meta.yaml and does not take into account memory required for 'jwt-proxy' pod #14001 3d
- [x] Potential security vulnerabilities in Dashboard and Workspace-loader #13924 10d
- [x] Unable to delete worskpace from Organization workspaces list, workspace name is missed #13893 PR to merge
- [x] Impossible to scroll in plugin list on dashboard #14211 2d
- Minimal Firefox Support #14015 7.2
   - [x] Dashboard menu items are not aligned #13309 1d
   - [x] No scrolling possible when creating workspace #13236 related to #14211

## Other  issues:
- [ ] doc: have more contribute flow for each of our components with a devfile, to be updated in CONTRIBUTING.md files of each projects Ws master Chectl Plugin Broker Etc … #14126 to finish 7.0!!! 4d to finish
- [ ] chore: Add a devfile for https://github.com/eclipse/che-docs + vscode asciidoc #14196 5d
- [ ] References to commits are broken in Help -> About dialog #14092 7.2 2d
- [x] Fix security alerts in che-theia repository #14142 3d
- [ ] Button to go back to dashboard in factory screen does not work #13875 7.2 2d
- [ ] Search/Filter in command palette mis behaving #13650 7.2 3d
- [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins. #14119 7.2 10d
- [ ] Replace devfile editor with monaco and YAML LSP #13939 7.x to investigate(maybe for Yevhen)
- [ ] Che keeps failing on minishift #13995 ?

## Pending PR
- [ ] Run Che command in selected container if container doesn't specified in configuration https://github.com/eclipse/che-theia/pull/274
- [x] Progress extension  https://github.com/theia-ide/theia/pull/5176
- [x] Remote binary https://github.com/eclipse/che-theia/pull/267
- [x] [plug-in] [WIP] Plugin api documentation https://github.com/theia-ide/theia/pull/3045
- [ ] Dashboard: fail build when webpack has errors #12911 
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
