### ISSUE TITLE
IDE-2019-09-03 (Sprint: 171) 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14148]
### Sprint details: 
- [x] Adaptation for tasks is required #14098
- [ ] Preconfigure git user information from Che user's profile/preferences #13874 
- [ ] Improve the way of storage runtime info for Che tasks #13722 (need analyze more deeply, during sprint we will try to found solution, implementation in next sprints)
- [x] [openshift plugin] test service related commands #13412
- [ ] [openshift plugin] fix 'Open in Browser' command #13410
- [ ] [openshift plugin] fix 'Log in' command #13405
- [ ] Mark in the task widget title when task is exited. #14132 (need to PM description)

#### Bugs
- [x] GitHub plugin shows an empty panel #14244
- [ ] che task: Cannot run a che command after workspace restart for some containers #13993 (need to PM description, otherwise will be removed from sprint) 
- [ ] Redundant dialog appears on git checkout from status bar #13974
- [x] The My Workspace actions works incorrectly #13956
 

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 12 |  
| Vlad |11 |    
| Roman  |10 | 
| Vitalii  |6|    
| Igor |13 |
