### ISSUE TITLE
Platform-2019-09-03 (Sprint: 171)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14146]
### Description

 - [ ] Test Che6 to Che7 upgrade using che-operator | https://github.com/eclipse/che/issues/14200 | 8
- [x] Do not wait for PV state bound if we got a message "waiting for the first consumer to be created before binding" | https://github.com/eclipse/che/issues/13437 | 8
- [ ] server:start doesn't work if Che has already been deployed | https://github.com/che-incubator/chectl/issues/77 | 5
- [ ] ConsoleLink for Che on OpenShift | https://github.com/eclipse/che/issues/14203 | 8
- [x] helm charts - ingress.class could be extracted to variable (refactoring) | https://github.com/eclipse/che/issues/13927 | 5

### Finalize issues started in the previous sprint.

- [x] Impossible to set boolean value for preferences via devfile | https://github.com/eclipse/che/issues/14131 | 8
- [x] Workspace creation fails if a workspace with the same name already exist | https://github.com/eclipse/che/issues/13794 | 3
- [x] Unable to accept factory with workspace, which name would collide with existing workspace name | https://github.com/eclipse/che/issues/13683 | 3
- [ ] PKIX error and impossible to start workspaces on OCP 4.1 | https://github.com/eclipse/che/issues/13607 | 5
- [ ]  Installer/Bootstrapper decommissioning | https://github.com/eclipse/che/issues/14153 | 5
- [x] Project-template API decomissioning | https://github.com/eclipse/che/issues/13903
- [x] NPE when a devfile command references theia | https://github.com/eclipse/che/issues/13842
- [x] StackService decommissioning | https://github.com/eclipse/che/issues/13459

### Unplanned
- [ ] Support single-host/default-host in multi-user server mode https://github.com/eclipse/che/issues/14189
- [x] Build of "Che Core :: Metrics :: Core" module failed on test "FileStoresMeterTest"  https://github.com/eclipse/che/issues/14202
- [x] Impossible to start workspace https://github.com/eclipse/che/issues/14336

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 11d |
| Max Shaposhnik | 3d | 
| Michail Kuznyetsov | 3d | 
| Sergii Leshchenko | 15d | 
| Michal Vala | 15d | 
| Lukas Krejci | 15d | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 65  | 27 |
