### ISSUE TITLE
Languages Sprint 171

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14221]
Aug 12 - Sep 3

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 13 | 6 | 6
@tolusha | 13 | 8 | 9.5
@svor | 2 | 0 | 0 
@vrubezhny | 13 | 8 | 7.5
@JPinkney | 13 | 8 | 9

# Priorities
All testing must be done on minishift!

# Candidate Issues
- [ ] Fix license headers in ommisharp plugin #14224 0.5d @tsmaeder 
- [x] Test C# theia plugin with multi-root workspace in Theia #14223 0.5d @tsmaeder 
- [x] Investigate Support for multi-root workspaces with PHP plugins #14225 2d @vrubezhny 
- [ ] Workspace folder changes are not sent to the server if they occur during initialisation https://github.com/microsoft/vscode-languageserver-node/issues/451 5d @tsmaeder 
- [x] Go sample can't run files without task #14007 0.5d @tolusha 
- [x] It isn't possible to debug Python Django application #13816 1d @tolusha 
- [x] Theia should not offer to start apps for debugging #14091 3d @tolusha 
- [x] Investigate Testing LSP features #14023 2d @tolusha 
- [ ] Che 7 plugin: Update PHP Intelephense to v.1.1.1 - 2019-06-27? #13700 (0.5d @vrubezhny )
  - [ ] files property https://github.com/theia-ide/theia/issues/5945 (@vrubezhny) 3d
  - [ ] telemetry property: https://github.com/theia-ide/theia/issues/5944 (@vrubezhny) 2d
- [x] Theia can't open files located in a sidecar container https://github.com/eclipse/che/issues/13614 5d (timeboxed spike) @tolusha 
- [ ] Implement Language Server Metrics #14245 5d @JPinkney 
- [x] https://bugzilla.redhat.com/show_bug.cgi?id=1732740 @JPinkney 
- [x] https://bugzilla.redhat.com/show_bug.cgi?id=1733091 @JPinkney 
- [x] https://bugzilla.redhat.com/show_bug.cgi?id=1735685 @JPinkney 
(4d total).

# From Last Sprint

# Open Pull Requests
  - [ ] PR: https://github.com/eclipse/che-plugin-registry/pull/199
  - [ ] PR https://github.com/eclipse/che-devfile-registry/pull/73
  - [x] PR https://github.com/eclipse/che-plugin-registry/pull/197
  - [x] PR https://github.com/eclipse/che-theia/pull/401

https://github.com/theia-ide/theia/pull/5590
https://github.com/theia-ide/theia/pull/5379

# Blocked issues 
# Unplanned Issues
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic https://github.com/eclipse/che/issues/13427 1d
- [ ] Debugging with the python plugin behaves strangely #14219 3d
- [ ] Upgrade Go version to support realworld sample #13803 3d
- [x] https://github.com/eclipse/che-theia/pull/420

Previous Sprint: https://github.com/eclipse/che/issues/14016
