### ISSUE TITLE
IDE-2019-09-24 (Sprint: 172)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14295]
### Sprint goals
1. GitHub Plugin various fixes 
2. Finalize VS Code OpenShift/K8s Plugins porting to the Che Theia 
3. Git + SSH Flow
4. Che Commands/Tasks experience

#### 1. GitHub Plugin
- [x] Github plugin installation fails #14319
- [x] Tree nodes don't expand in the GitHub plugin #13790 
- [x] GitHub plugin doesn't update if a new repository is cloned and selected #14403 
- [x] Redundant dialog appears on git checkout from status bar #13974
#### 2. OpenShift/K8s Plugins
- [x] [openshift plugin] fix 'Log in' command #13405 (continue work on the PR https://github.com/theia-ide/theia/pull/5994)
- [ ] [k8s plugin] Kubernetes: Run command cannot build an image #13702
- [ ] [k8s plugin] Kubernetes: Run command should work w/o Docker #13316
- [ ] [openshift plugin] fix 'Open URL' command #13406
#### 3. Git + SSH Flow (epic issue https://github.com/eclipse/che/issues/13494)
- [x] Preconfigure git user information from Che user's profile/preferences #13874 (finalize)
- [x] Sync changes to local git config with user Che git config #13959 (finalize)
- [x] Can't clone projects from git@github.com #14288
- [x] Provision user name and email into git configuration from user profile when newly workspace is created #14416
- [ ] SSH Create key empty input #14218
- [ ] SSH View public key #14215 
#### 4. Che Commands/Tasks experience
- [ ] Improve the way of storage runtime info for Che tasks #13722 (draft PR https://github.com/eclipse/che-theia/pull/419)
- [ ] Cannot run a che command after workspace restart for some containers #13993

#### Unplanned tasks
- [x] It isn't possible to start workspace once it has been stopped #14436
- [x] ssh: delete key pair not working #14332
- [x] Release Che 6.19.6 #14326

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |8 |    
| Roman  |6 | 
| Vitalii  |6|    
| Igor |14 |
