### ISSUE TITLE
Platform-2019-09-24 (Sprint: 172) 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14342]
### Description
- [ ] Test Che6 to Che7 upgrade using che-operator | https://github.com/eclipse/che/issues/14200 | 8
- [x] Optimize PermissionChecker performance | https://github.com/eclipse/che/issues/13221 | 8
- [x] [Metrics] Develop dashboards for metrics that come from traces | https://github.com/eclipse/che/issues/13502 | 5
- [ ] Provide ability to map component to containerName | https://github.com/eclipse/che/issues/14280 | 8
- [x] Multiuser-OpenShift on OpenShift behind Proxy not starting Workspaces | https://github.com/eclipse/che/issues/14052 | 13
- [x] Support one namespace per user strategy (che.osio like) | https://github.com/eclipse/che/issues/13488 | 8

### Finalize issues started in the previous sprint.
- [ ] PKIX error and impossible to start workspaces on OCP 4.1 | https://github.com/eclipse/che/issues/13607 | 5
- [x] server:start doesn't work if Che has already been deployed | https://github.com/eclipse/che/issues/14465 | 5
- [x] ConsoleLink for Che on OpenShift | https://github.com/eclipse/che/issues/14203 | 5
- [x] Support single-host/default-host in multi-user server mode | https://github.com/eclipse/che/issues/14189 | 3
- [x] Internal server error when I try to add preferences for chePlugin component | https://github.com/eclipse/che/issues/14289 | 5
### Unplanned
- [x] An error occurred while attempting to recover runtime https://github.com/eclipse/che/issues/14526
- [ ] API: List of available k8s namespaces for the workspace creation https://github.com/eclipse/che/issues/14376
- [x]  Potential inconsistency between 'che_workspace_activity' and 'che_k8s_runtime' for STOPPING / STARTING workspaces  https://github.com/eclipse/che/issues/14536
- [x] Unable to cleanup temporary workspace workspaceqe1y1ilmiup489gj https://github.com/eclipse/che/issues/14525
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 13d | 
| Michal Vala | 12d | 
| Lukas Krejci | 15d | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 73  | 52 |
