### ISSUE TITLE
IDE2-2019-09-24 (Sprint: 172)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#14345]
### Sprint Goals:
1. Finalize Che 7.1 fixes and improvements
2. Che 7.2 fixes and improvements

## 1. Finalize Che [7.1.0](https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+label%3Ateam%2Fide2+milestone%3A7.1.0) fixes and improvements

- [ ] Theia remote plug-in runtime in sidecar container improvement #13387 - 7d
- [ ] White labelling capabilities for Che 7 #14110 - First part Dashboard and investigating che-theia 5d
- [x] Icons aren't displayed on a contributed view container #13750 5d
- [x] Potential security vulnerabilities in Dashboard and Workspace-loader #13924 5d

### [P1](https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+label%3Ateam%2Fide2+milestone%3A7.2.0+label%3Aseverity%2FP1+):
- [x] Factory policies.crate=peruser #14355 6d
- [x] Keycloak token not refreshed when asking for workspace status #14314 5d

### [P2](https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+label%3Ateam%2Fide2+milestone%3A7.2.0+label%3Aseverity%2FP2+):
- [x] Tooltip in workspace panel should be showing the complete command #13149 3d
- [x] Search/Filter in command palette mis behaving #13650 3d
- [x] References to commits are broken in Help -> About dialog #14092 2d
- [x] [che-theia] build of docker images should not make GITHUB_TOKEN mandatory #14194 2d
- [x] The list of Editors of a minimal workspace is empty #14340 2d
- [ ] Devfiles: Che doesn't expand projects in zip archives #14206
- [x] Welcome plugin uses absolute paths to reference page elements #14233 2d

### P3
- [ ] UD should show warning if plugin is deprecated #13021 5d

### P2
- [ ] doc: have more contribute flow for each of our components with a devfile, to be updated in CONTRIBUTING.md files of each projects Ws master Chectl Plugin Broker Etc … #14126 to finish 7.0!!! 4d to finish
- [x] chore: Add a devfile for https://github.com/eclipse/che-docs + vscode asciidoc #14196 5d
- [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins. #14119 7.2 10d

### P3
- [ ] Add Kubernetes native Java + Maven sample and describe flow of the application development in Che #14358

## Pending PR
- [x] Run Che command in selected container if container doesn't specified in configuration https://github.com/eclipse/che-theia/pull/274
- [ ] Dashboard: fail build when webpack has errors #12911 
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
