### ISSUE TITLE
Languages Sprint 172

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14368]
Aug Sep. 4 - Sep. 25

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 8 | 4 | 3
@tolusha | 15 | 9 | 6
@svor | 15 | 9 | 9
@vrubezhny | 13 | 8 | 3
@JPinkney | 15 | 9 | 7

# Priorities
All testing must be done on minishift!

# Candidate Issues

- [ ] Implement Language Server Metrics #14245 4d @JPinkney 
- [x] [C#] React to Workspace Folder Changes #14365 3d @svor 
- [x] [C#] Handle Multiple Solutions #14370 3d  @svor 
- [x] Allow injecting maven settings in JDT LS sidecar #14391 2d @tolusha 
- [ ] Replace current nodejs+mongo sample with a better one #14392 3d @svor 
- [ ] Theia can't open files located in a sidecar container #13614 3d @tolusha 
    - [x] Check if overriding `registerDefinitionProvider` helps
- [x] Debugging with the python plugin behaves strangely #14219 3d timeboxed (@tolusha)
- [ ] Add tslint to Typescript language support plugins #14070 1d @vrubezhny 
- [ ] No error message if vscode.open command is invoked with resource that doesn't exist https://github.com/theia-ide/theia/issues/5667 2d @vrubezhny 
- [ ] Upgrade Go version to support realworld sample https://github.com/eclipse/che/issues/13803 @tolusha 
    - [ ] https://github.com/eclipse/che-theia/pull/443
    - [ ] https://github.com/eclipse/che-devfile-registry/pull/96
    - [ ] https://github.com/eclipse/che-plugin-registry/pull/224
- [ ] Add support for preLaunchTask and postDebugTask  https://github.com/theia-ide/theia/issues/3409 @svor 
- [ ] Theia should not offer to start apps for debugging #14091  (3d design timebox) @tsmaeder 

# To be planned

- [ ] Theia tasks are listed in random order https://github.com/eclipse/che/issues/14000
- [ ] NPE in DisconnectRequestHandler.destroyDebugSession(DisconnectRequestHandler.java:28) https://github.com/eclipse/che/issues/13967
- [ ] Refactor plugin system to use DI instead of new operators https://github.com/theia-ide/theia/issues/5761
- [ ] Maven dependencies are download each time the workspace is getting restarted https://github.com/eclipse/che/issues/13603
- [ ] Debug Console doesn't auto scroll https://github.com/theia-ide/theia/issues/5495
- [ ] Copy selected item will cause debug console scroll to the top position https://github.com/theia-ide/theia/issues/5970
- [ ] Add support for Vue.js https://github.com/eclipse/che/issues/13672
- [ ] Custom Debug adapter - debugging does not work if a file is already open #6122 https://github.com/theia-ide/theia/issues/6122
- [ ] WorkspaceService not Concurrency-Safe https://github.com/theia-ide/theia/issues/5820
- [ ] Debug Console doesn't auto scroll https://github.com/theia-ide/theia/issues/5495
- [ ] Copy selected item will cause debug console scroll to the top position https://github.com/theia-ide/theia/issues/5970
- [ ] selected line get lost after scrolling the window https://github.com/theia-ide/theia/issues/5969
- [ ] Keyboard navigation does not work in debug console https://github.com/theia-ide/theia/issues/5493
- [ ] Replace devfile editor with monaco and YAML LSP  https://github.com/eclipse/che/issues/13939
- [ ] Tasks of remote plugins are not redirected to corresponding container https://github.com/eclipse/che/issues/13741

# From Last Sprint

# Open Pull Requests
  - [ ] PR https://github.com/eclipse/che-devfile-registry/pull/73 
Add the devfile to work with c/c++ stack
- [ ] Provided mapping from vscode command ids to internal command ids https://github.com/theia-ide/theia/pull/5590 (3d @JPinkney)
- [x] Python plugin randomly crashes https://github.com/eclipse/che-theia/pull/427 @tolusha 
- [x] Update python tooling image https://github.com/eclipse/che-devfile-registry/pull/93 @tolusha 

Next sprint:
- [ ] Simple LSP test suite for Java #14409
- [ ] Make it possible to map XXX-Providers to Plugins https://github.com/theia-ide/theia/issues/6151
# Blocked issues 
- [ ] add 'filter' toolbar item for the debug console https://github.com/theia-ide/theia/issues/6067

# Unplanned Issues
- [ ] Che 7 plugin: Update PHP Intelephense to v.1.1.1 - 2019-06-27? #13700 (0.5d @vrubezhny )
  - [ ] files property https://github.com/theia-ide/theia/issues/5945 (@vrubezhny) 3d
  - [ ] telemetry property: https://github.com/theia-ide/theia/issues/5944 (@vrubezhny) 2d
=> need advice from @akurinnoy 

Previous Sprint: https://github.com/eclipse/che/issues/14221
