### ISSUE TITLE
Various Docs issues

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14393]
- [x] [Doc] Debug Adapter Protocol reference kind/enhancement #14372 
- [x] [Doc] Language Server Protocol reference kind/enhancement  #14371 
- [ ] [Doc] Providing a custom IDE based on Eclipse Theia and Switching the default editor to another one #14369 
- [ ] [Doc] API reference kind/enhancement #14367 
- [ ] [Doc] Removing user data #14364 
- [x] [Doc] Viewing plug-in broker logs #14363
- [ ] [Doc] Installation guide #14362 
- [ ] [Doc] Configuring your VCS credentials for your workspaces #14361 
- [ ] [Doc] Defining workspaces using the dashboard #14360 
- [x] [Doc] Unify Prerequisites A running instance of Eclipse Che. #14399
- [ ] [Doc] Clarify using a devfile / creating a devfile #14400
