### ISSUE TITLE
[Doc] Documentation templates gardening

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#14415]
Let's take care of existing non-filled templates and keep them in sync with the updated docs outline:

* Topics that have already been documented:  if their original templates have not been used, the unused templates need to be deleted.
* Templates that have no counterpart in current docs outline need to be deleted.
* Topics in the current docs outline that have no corresponding template files in the repository need to have templates created.

As a reminder, here is a copy of current doc outline (with status):

* [x] Overview
  * [x] Introduction to Eclipse Che
    * [x] Getting started with Che
    * [x] Joining the community 
    * [x] What is Eclipse Che
    * [x] Che 7.0 known issues
  * [x] Che quick-starts
    * [x] Installing the chectl management tool
    * [x] Running Che locally
    * [x] Che on Amazon Web Services
    * [x] Che on OpenShift 3
    * [x] Che on OpenShift 4
    * [x] Che on Google Cloud Platform
    * [x] Che on Microsoft Azure
  * [x] Hosted ChE
    * [x] About Hosted Che
    * [x] Registering to Hosted Che
    * [x] Creating a worskpace from the user dashboard
    * [x] Creating a workspace from a template in Hosted Che
    * [x] Importing projects from GitHub in Hosted Che
    * [x] Contributing to GitHub projects in Hosted Che
    * [x] Finding the cluster where the Hosted Che workspace is running
  * [x] Che architecture
    * [x] High-level Che architecture
    * [x] Che workspace controller
    * [x] Che workspaces architecture
    * [x] Types of plug-ins
    * [x] Plug-in registry
    * [x] Plugin brokers
* [ ] End-User Guide
  * [x] Navigating Che using the Dashboard
  * [ ] Che-Theia IDE basics https://github.com/eclipse/che/issues/14359 
    * [ ] Navigating the Che-Theia user interface
    * [ ] Files and projects
    * [ ] Editing code and code assistance
    * [ ] Key bindings
    * [ ] Searching
    * [x] Defining custom commands for Che-Theia
    * [ ] Debugging
    * [ ] Testing
    * [x] Version control
    * [ ] Integrated terminal
    * [ ] Languages
    * [ ] SSH
  * [ ] Using developer workspaces
    * [x] Workspaces overview
    * [ ] Defining workspaces using the dashboard https://github.com/eclipse/che/issues/14360 
      * [ ] Configuring runtimes
      * [ ] Exposing services
      * [ ] Mounting specific volumes into workspaces
      * [ ] Setting environment variables
      * [ ] Configuring projects
    * [x] Configuring a workspace using a devfile
      * [x] Importing a project using a devfile
      * [x] Making a workspace portable using a Devfile
        * [x] Starting a workspace with a devfile
        * [x] Writing a devfile for a project
          * [x] Preparing a minimal devfile
          * [x] Specifying multiple projects in a devfile
        * [x] Devfile reference (Adding components)
          * [x] Adding components to a devfile
            * [x] Component type: cheEditor
            * [x] Component type: chePlugin
            *   [x] Specifying an alternative component registry
              * [x] Specifying a component by linking to its descriptor
              * [x] Specifying container memory limit for components
              * [x] Tuning component configuration
            * [x] Component type: kubernetes
              * [x] Specifying mount sources option
            * [x] Component type: dockerimage
              * [x] Mounting project sources
              * [x] Container Entrypoint
              * [x] Persistent Storage
              * [x] Environment
              * [x] Endpoints
            * [x] Kubernetes and OpenShift resources
          * [x] Adding commands to a devfile
            * [x] Che-specific commands
            * [x] Editor-specific commands
          * [x] Devfile attributes
            * [x] Attribute: editorFree
            * [x] Attribute: persistVolumes (ephemeral mode)
        * [x] Objects supported in Eclipse Che 7
    * [x] Converting a Che 6 workspace to a Che 7 devfile (incomplete)
      * [x] Converting a Che 6 workspace to a basic Che 7 devfile
      * [x] Accessing a Che 6 workspace configuration
    * [x] Creating and configuring a new Che 7 workspace
    * [x] Importing a Kubernetes application into a Che workspace
    * [x] Remotely accessing workspaces
    * [x] Creating a workspace from code sample
    * [x] Creating a workspace by importing source code of a project
    * [ ] Configuring your VCS credentials for your workspaces https://github.com/eclipse/che/issues/14361
  * [x] Customizing developer environments
    * [x] Overview
    * [x] What is a Che-Theia plug-in
       * [x] Features and benefits of Che-Theia plug-ins
       * [x] Che-Theia plug-in concept in detail
         * [x] Client-side and server-side Che-Theia plug-ins
         * [x] Che-Theia plug-in APIs
         * [x] Che-Theia plug-in capabilities
         * [x] VS Code extensions and Eclipse Theia plug-ins
       * [x] Che-Theia plug-in metadata
         * [x] meta.yaml
         * [x] che-plugin.yaml
       * [x] Che-Theia plug-in lifecycle
       * [x] Embedded and remote Che-Theia plug-ins
         * [x] Embedded (or local) plug-ins
         * [x] Remote plug-ins
         * [x] Comparison matrix
    * [x] Using alternative IDEs in Che
    * [x] Using a VS Code extension in Che
      * [x] Importing a VS Code extension in the Che-Theia editor
      * [x] Publishing a VS Code extension into the Che plug-in registry
      * [x] Adding a plug-in registry VS Code extension to a workspace
        * [x] Adding the VS Code extension using the Che Plugins panel
      * [x] Choosing the sidecar image
      * [x] Verifying the VS Code extension API compatibility level
* [x] Administration Guide
    * [ ] Installation Guide https://github.com/eclipse/che/issues/14362
      * [ ] Che installation overview
        * [ ] Target platforms
        * [ ] Deployment architecture diagram
      * [ ] Che installation prerequisites
        * [ ] Storage
        * [ ] Networking
        * [ ] Identity
      * [ ] Installing Che on different Kubernetes distributions
      * [ ] Updating Che
      * [ ] Advanced configuration options
        * [ ] Che configuration reference table
        * [ ] Deploying Che with HTTPS mode
        * [ ] Deploying Che without Keycloak
        * [ ] Configuring Che Persistent Volumes strategy
        * [ ] Configuring Che with and without Keycloak
        * [ ] Configuring private Docker registries
        * [ ] Configuring email notifications
        * [ ] Configuring namespace strategies
        * [ ] Configuring workspace memory settings
        * [ ] Configuring Che with OpenShift OAuth
      * [ ] Troubleshooting Che installation
    * [x] Customizing devfile and plug-in registries
        * [x] Overview
        * [x] Building and running a custom registry image
            * [x] Cloning the registries
                * [x] Cloning the plug-in registry
                * [x] Cloning the devfile registry
            * [x] Modifying the registries
                * [x] Adding a new plug-in
                * [x] Adding a new devfile
            * [x] Building the images of the registries
                * [x] Building the images of the plug-in registry
                * [x] Building the images of the devfile registry
            * [x] Deploying the registries
                * [x] Deploying registries in Kubernetes
                * [x] Deploying registries in OpenShift
        * [x] Including the plug-in binaries in the registry image
        * [x] Editing a devfile and plug-in at runtime
            * [x] Adding a plug-in at runtime
            * [x] Adding a devfile at runtime
    * [x] Retrieving Che logs
        * [x] Overview
        * [x] Viewing Kubernetes events
        * [x] Viewing Che server logs
            * [x] Viewing the Che server logs in the web console
            * [x] Viewing the Che server logs on the command line
        * [x] Viewing external service logs
            * [x] Viewing Keycloak logs
                * [x] Viewing the Keycloak server logs
                * [x] Viewing the Keycloak client logs on Firefox
                * [x] Viewing the Keycloak client logs on Google Chrome
            * [x] Viewing the PostgreSQL server logs
        * [x] Viewing Che workspaces logs
            * [x] Viewing Che-Theia IDE logs
                * [x] Viewing Che-Theia IDE logs on the command line
                * [x] Viewing Che-Theia IDE logs in the web console
            * [x] Viewing logs from language servers and debug adapters
                * [x] Checking important logs
                * [x] Detecting memory problems
                * [x] Logging the client-server traffic for debug adapters
                * [x] Viewing logs for Python
                * [x] Viewing logs for Go
                    * [x] Finding the gopath
                    * [x] Viewing the Debug Console log for Go
                    * [x] Viewing the Go logs output in the Output panel
                * [x] Viewing logs for the NodeDebug NodeDebug2 adapter
                * [x] Viewing logs for Typescript
                    * [x] Enabling the label switched protocol (LSP) tracing
                    * [x] Viewing the Typescript language server log
                    * [x] Viewing the Typescript logs output in the Output panel
                * [x] Viewing logs for Java
                    * [x] Verifying the state of the Eclipse JDT Language Server
                    * [x] Verifying the Eclipse JDT Language Server features
                    * [x] Viewing the Java language server log
                    * [x] Logging the Java language server protocol (LSP) messages
                * [x] Viewing logs for Intelephense
                    * [x] Logging the Intelephense client-server communication
                    * [x] Viewing Intelephense events in the Output panel
                * [x] Viewing logs for PHP-Debug
                * [x] Viewing logs for XML
                    * [x] Verifying the state of the XML language server
                    * [x] Checking XML language server feature flags
                    * [x] Enabling XML Language Server Protocol (LSP) tracing
                    * [x] Viewing the XML language server log
                * [x] Viewing logs for YAML
                    * [x] Verifying the state of the YAML language server
                    * [x] Checking the YAML language server feature flags
                    * [x] Enabling YAML Language Server Protocol (LSP) tracing
                * [x] Viewing logs for Dotnet with Omnisharp-Theia plug-in
                    * [x] Omnisharp-Theia plug-in
                    * [x] Verifying the state of the Omnisharp-Theia plug-in language server
                    * [x] Checking Omnisharp Theia plug-in language server features
                    * [x] Viewing Omnisharp-Theia plug-in logs in the Output panel
                * [x] Viewing logs for Dotnet with NetcoredebugOutput plug-in
                    * [x] NetcoredebugOutput plug-in
                    * [x] Verifying the state of the NetcoredebugOutput plug-in
                    * [x] Viewing NetcoredebugOutput plug-in logs in the Output panel
                * [x] Viewing logs for Camel
                    * [x] Verifying the state of the Camel language server
                    * [x] Viewing Camel logs in the Output panel
            * [ ] Viewing plug-in broker logs https://github.com/eclipse/che/issues/14363 
    * [x] Monitoring Che
        * [x] Enabling Che metrics collections
        * [x] Collecting Che metrics with Prometheus
            * [x] Prometheus terminology
            * [x] Configuring Prometheus
        * [x] Viewing Che metrics on Grafana dashboards
            * [x] Configuring and deploying Grafana
            * [x] Grafana dashboards overview
                * [x] Che server dashboard
                * [x] Che server JVM dashboard
        * [x] Developing Grafana dashboards
        * [x] Extending Che monitoring metrics
    * [x] Tracing Che
        * [x] Tracing API
        * [x] Tracing backend
        * [x] Enabling Che metrics collections
        * [x] Viewing Che traces in Jaeger UI
        * [x] Che tracing codebase overview and extension guide
            * [x] Tagging
    * [x] Securing Che
        * [x] Authenticating users
            * [x] Authenticating to the Che server
                * [x] Authenticating to the Che server using OpenID
                    * [x] Obtaining the token from Keycloak
                * [x] Authenticating to the Che server using other authentication implementations
                * [x] Authenticating to the Che server using OAuth
                * [x] Using Swagger or REST clients to execute queries
            * [x] Authenticating in a Che workspace
                * [x] Creating secure servers
                * [x] Workspace JWT token
                * [x] Machine token validation
        * [x] Authorizing users
            * [x] Che workspace permissions
            * [x] Che organization permissions
            * [x] Che system permissions
            * [x] manageSystem permission
            * [x] monitorSystem permission
            * [x] super-privileged mode
            * [x] Listing Che permissions
            * [x] Assigning Che permissions
            * [x] Sharing Che permissions
    * [ ] Removing user data https://github.com/eclipse/che/issues/14364
    * [ ] API reference https://github.com/eclipse/che/issues/14367 
        * [ ] Access to Swagger
        * [ ] Workspace API
        * [ ] Permissions API
        * [ ] Factory API
        * [ ] Resources API
        * [ ] IDE macros
* [ ] Contributor Guide
    * [x] Developing Che-Theia plug-ins
       * [x] Che-Theia plug-in development flow
       * [x] Bootstrapping Che-Theia plug-in development with Yeoman
       * [x] Developing Che-Theia plug-ins using Che
       * [x] Converting a Visual Studio Code extension to a Che-Theia plug-in
       * [x] Developing a real world Che-Theia plug-in
       * [x] Developing a real world plug-in for Che
    * [x] Testing Che-Theia plug-ins
    * [x] Publishing Che-Theia plug-ins
       * [x] Che-Theia plug-in registries
       * [x] Adding a Che-Theia plug-in to the Che plug-in registry
       * [x] Adding a Che-Theia plug-in into a workspace
       * [x] Sharing your Che-Theia plug-in with a factory
       * [x] Overriding RAM of a Che-Theia plug-in
     * [x] Adding support for a new language
     * [x] Adding support for a new debugger
     * [ ] Providing a custom IDE based on Eclipse Theia https://github.com/eclipse/che/issues/14369 
     * [ ] Switching the default editor to another one https://github.com/eclipse/che/issues/14369 
     * [x] Che extensibility reference
       * [x] Che extension points
       * [x] Che-Theia plug-in API
       * [ ] Language Server Protocol https://github.com/eclipse/che/issues/14371 
       * [ ] Debug Adapter Protocol https://github.com/eclipse/che/issues/14372 
       * [x] Architectural insights about the plugin brokers
