### ISSUE TITLE
Improve vscode che plugins UX and flow in `my workspace` view

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#14565]
### Is your enhancement related to a problem? Please describe.
In this issue I would like to start a discussion on how we should use and present my workspace view. One of the main problem of the view is that we consider that the user would rarely have access to the sidecar container of a plugin which is in my opinion a wrong assumption.
The author of a devfile should be able to tell if a sidecar container should be accessible to the user.
It really makes sense for language plugins: containers usually come with a sidecar container and the user may not want to create/access another container to use the same tools when using the terminal or a che-command.
User may want to access to the sidecar container to use exactly the same version of the compilers and so on from the terminal or a che-command

### Describe the solution you'd like
- [ ] We could keep the default behavior as it is by default, but have a flag in the devfile that tell if a plugin has to be visible for the end user when accessing the terminal or using a task.
- [ ] Nicely display the label of a plugin container: for instance a plugin 'vscode-ansible' would be displayed 'vscode-ansiblez20'

### Describe alternatives you've considered
- [ ] https://github.com/eclipse/che/issues/13587

**Comment by gorkem** [comment]
I am not bothered by the my workspace view behaviour. It just affects the initial state of the tree. However `open terminal` behaviour is the one that I do not like.

I am -1 for the flags on devfile. It should be the user's choice what is displayed on the UI. How about a user preference for showing all containers or not?

+1 on the labels for the plugin container.
