### ISSUE TITLE
QE-2019-09-24 (Sprint: 172)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#14579]
### Issues tied to objectives
- [ ] Prepare e2e test for Vscode GitHub Plugin #13691
- [ ] Decouple Java selenium E2E tests from GWT-code #13827
- [ ] Create pipeline job to build che & run Happy Path on both openshift&kubernetes infra in CentralCI #14232
- [x] Implement temporary workaround for checking codenavigation feature in the HappyPath scenario #14522
- [ ] [TS_SELENIUM] Increase logging of tests steps #13686

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 3 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 10 |
| Total | 53 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | NA |  |
