### ISSUE TITLE
IDE2-2019-10-15 (Sprint: 173)

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#14580]
### Sprint Goals:
1. Finalize Che 7.1.0 and 7.2.0 fixes and improvements
2. Che 7.3 fixes and improvements

### P1
- [ ] Theia remote plug-in runtime in sidecar container improvement #13387 - 5d
- [ ] White labelling capabilities for Che 7 #14110 - First part Dashboard and investigating che-theia 4d
### P2
- [x] UD should show warning if plugin is deprecated #13021 3d

### P3
- [x] Provide a message when a terminal fails to open #13980 5d

### [P1](https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+label%3Ateam%2Fide2+milestone%3A7.3.0+label%3Aseverity%2FP1+):
- [ ] Dashboard: While editing a devfile of a workspace, user is constantly interrupted by the auto save #13982 - Investigate devfile storing -1d
- [ ] Workspace is continuously restarted after start interruption #14567 3d
- [x] Theia plugins extension doesn't work properly #14553 2d
- [ ] (depends on platform team work) Dashboard: view and change target namespace #14389 4d
- [ ] Add keepDir support for Devfiles #13671 -> analyse how workspace multi root would look like (see #14550) and see if we could avoid doing sparse checkout/keepDir 7d
- [x] Plugin runtime crashed unexpectedly #14551 3d
- [ ] Add ability to create a new workspace from the dashboard with a devfile #13591 13d

### [P2](https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+label%3Ateam%2Fide2+milestone%3A7.3.0+label%3Aseverity%2FP2+):
- [ ] Che Theia should display a warning if the workspace has deprecated plugin #14423 8d

### P3
- [ ] `/projects/.devfile.yaml` synchronized with the current workspace devfile #13983 6d
- [ ] Che-theia - My workspace view: if available, show the che commands/task that are available in a plugin side car #13587 1d

### P2
- [ ] doc: have more contribute flow for each of our components with a devfile, to be updated in CONTRIBUTING.md files of each projects Ws master Chectl Plugin Broker Etc … #14126 to finish 7.0!!! 4d to finish
- [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins. #14119 7.2 10d

### P3
- [ ] Add Kubernetes native Java + Maven sample and describe flow of the application development in Che #14358 3d
- [ ] (Suggestion: we take it back) Terminal is empty on Firefox #13736 3d

## To discuss:
- [ ] Persist installed VS Code extensions #13834

## Pending PR
- [ ] Dashboard: fail build when webpack has errors #12911 
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)
- [ ] Show a confirmation dialog when Ctrl+W is pressed in the terminal #13580

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
