### ISSUE TITLE
IDE-2019-10-15 (Sprint: 173)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14586]
### Sprint goals
1. Git + SSH Flow  
2. VS Code plugins
3. UX Improvement 
4. Bugs 
#### 1. Git + SSH Flow  
- [x] Generate SSH keys when the user login for the first time #14411 
#### 2.  VS Code plugins
- [x] Update remote-plugin-openshift-connector to odo 1.0 and oc 4.1 #14287
- [x] Update VS Code OpenShift Connector to v0.1.0 #14605
- [x] [Openshift Connector] OpenShift Connector is not available after first workspace starting #14611
- [ ] [k8s plugin] Kubernetes: Run command should work w/o Docker #13316
- [ ] [openshift plugin] fix 'Open URL' command #13406
#### 3. UX Improvement 
- [ ] Improve login procedure for GitHub PullRequest Plugin #14217
- [ ] Mark in the task widget title when task is exited. #14132
- [ ] Improve error message during git push #14615
- [ ] When user is doing a commit if git info (username and email) are not configured, allow the user to configure it. #14616
- [x] Add message "Git not configured" in status bar if not configured user.name and/or user.email #14617
- [x] Improve the way of storage runtime info for Che tasks #13722 (draft PR eclipse/che-theia#419)
- [ ] Stop running task #13737
#### 4. Bugs
- [ ] che task: Cannot run a che command after workspace restart for some containers #13993
- [ ] Each SSH keypair is mounted as a secret which is created after generation and workspace restart. Need to rework the implementation, so that all SSH keys would use single common secret #14438
- [x] Unable to clone with SSH: unprotected private key file #14398
- [x] [quick open] Quick input validation handler fires on widget start https://github.com/eclipse-theia/theia/issues/6245
- [x] Hanging of request for getting processId for terminal #14659

#### Unplanned tasks
- [x] Can not configure a task from Terminal => Run Task menu https://github.com/eclipse-theia/theia/issues/6212
- [x] No notification showed when task is finished https://github.com/eclipse/che/issues/14724
- [x] Tasks can't be run from the workspace view https://github.com/eclipse/che/issues/14770

#### Merge-ready PRs  
- [ ] Display non-tooling containers and add button to display all containers eclipse/che-theia#357
- [x] Validate SSH keys list before view/delete eclipse/che-theia#448
- [x] Apply SSH generate/create key name validation eclipse/che-theia#444
- [x] Align 'ActionProvider' related entities with VS Code https://github.com/eclipse-theia/theia/pull/6302

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |
