### ISSUE TITLE
QE-2019-10-15 (Sprint: 173)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#14583]
### Sprint goals
- [x] Increase coverage of Che functionality with E2E tests
- [ ] Check che-theia plugins on PR check
 
### Issues tied to objectives
- [ ] Prepare e2e test for Vscode GitHub Plugin #13691 8sp
- [x] [TS_SELENIUM] Increase logging of tests steps #13686 1sp
- [ ] Create Jenkins pipeline to run E2E Happy path tests against che-theia repo #14449 5sp
- [ ] Decouple Java selenium E2E tests from GWT-code #13827 5sp
- [x] Collect server logs if Happy path tests fail on PR check on CRW CI #14625 2sp
- [x] Involve required che-theia images to Happy path tests PR check #14646 2sp
- [ ] Load test Che on real cluster #14629 8sp

### Unplanned 
- [x] [TS_SELENIUM] Implement workaround for issue #14660 (Unexpected list of suggestions when use Java languageserver) in the "HappyPath" test. #14667 1sp
- [x] Add VNC server to the "eclipse/che-e2e" docker image #14341 3sp
- [x] Fix Java selenium E2E tests which check integration with GitHub #14711 2sp
- [x] Plugin runtime crashed unexpectedly when run Happy path tests on minikube on CRW CCI instances #14714 1sp
- [x] [TS_SELENIUM] Create image for the "Happy Path" tests based on the "quay.io/eclipse/che-java11-maven" image #14737 3sp
- [x] E2E Happy path tests failed on reading of build-output.txt #14771 5sp
- [x] Plugin runtime crashed unexpectedly when run Happy path tests on minikube on CRW CCI instances #14714 2sp
- [ ] Happy path tests failed on "Run debug and check application stop in the breakpoint" step #14822 3sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 12 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 5 |
| Total | 77 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 31 | 5 |
