### ISSUE TITLE
Platform-2019-10-15 (Sprint: 173)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14602]
### New Task && Enhancements

- [x] API: List of available k8s namespaces for the workspace creation | https://github.com/eclipse/che/issues/14376 | 8
- [ ] Add previewURL support in Devfile format | https://github.com/eclipse/che/issues/13945 | 5
- [ ] API: Ability to specify k8s namespace where a user wants to create his workspace | https://github.com/eclipse/che/issues/14379 | 13
- [ ] Monitoring & Tracing capability for multiple Thread pools of Che Server | https://github.com/eclipse/che/issues/14601 | 8

### Finalize issues started in the previous sprint.

- [x] Test Che6 to Che7 upgrade using che-operator | https://github.com/eclipse/che/issues/14200 | 0.5
- [x] Provide ability to map component to containerName | https://github.com/eclipse/che/issues/14280 | 2
- [x] Document how to use one namespace per user strategy (che.osio like) | https://github.com/eclipse/che/issues/14624 | 1

### Bugs and technical debt

- [x] Deprecate che-lib Github repository | https://github.com/eclipse/che/issues/14161 3
- [x] Devfile not validated on workspace update | https://github.com/eclipse/che/issues/13526 | 8
- [x] Using IP address instead of .nip.io by setting isHostBased = false doesnt work | https://github.com/eclipse/che/issues/13647 8
- [x] Identify the reason of slow workspace startup | https://github.com/eclipse/che/issues/14600 | 8

### Unplanned
- [x] Stabilize api.workspace.server.hc.ServerCheckerTest https://github.com/eclipse/che/issues/13211
- [x] Explain pitfalls and workarounds of Che6 to Che7 upgrade in a doc  https://github.com/eclipse/che/issues/14738 
- [ ] Change some wsmaster defaults https://github.com/eclipse/che/issues/14614
- [x] Verify Devconsole integration https://github.com/eclipse/che/issues/14745
 - [x] Test UX of an upgrade to Che7 from the running Che6 workspace perspective https://github.com/eclipse/che/issues/14810
- [ ] The default workspaces namespace/project should be `<username>-che` https://github.com/eclipse/che/issues/14795 
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 14d |
| Max Shaposhnik | 14d | 
| Sergii Leshchenko | 14d | 
| Michal Vala | 15d | 
| Lukas Krejci | 15d | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 64.5  | 46,5 |
#### Retrospective Comments
- Organize team technical discussion sessions after the prioritization meeting. POC of some task. That will allow to better split and estimate tasks
