### ISSUE TITLE
Languages Sprint 173

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14640]
Aug Sep. 26 - Oct 15

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 7 | 4 | 3
@tolusha | 13 | 8 | 8.5
@svor | 13 | 8 | 8
@vrubezhny | 14 | 8.5 | 8.5
@JPinkney | 13 | 8 | 9

# Priorities
All testing must be done on minishift!

# Planned Issues
- [ ] Implement Language Server Metrics #14245 0.5d @JPinkney 
- [ ] Theia can't open files located in a sidecar container #13614 0.5d @tolusha 
- [ ] Add tslint to Typescript language support plugins #14070 5d @vrubezhny 
- [ ] No error message if vscode.open command is invoked with resource that doesn't exist https://github.com/theia-ide/theia/issues/5667 2d @vrubezhny 
- [x] Add support for preLaunchTask and postDebugTask  https://github.com/theia-ide/theia/issues/3409 @tolusha 3d
- [ ] Theia should not offer to start apps for debugging #14091  (3d design timebox) @tsmaeder 
- [x] Theia tasks are listed in random order https://github.com/eclipse/che/issues/14000  @svor 3d
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d @vrubezhny 
- [ ] keyboard navigation does not work in debug console https://github.com/eclipse-theia/theia/issues/5493 (1.5 @tolusha )
- [x] [C#]Update Theia Omnisharp plug-in https://github.com/eclipse/che/issues/14613 0.5d (@svor)
- [ ] Add Java Sample Based on Google Cloud Samples @svor 3d #14651
- [ ] After updating Monaco Editor some Keybindings has collision for Java LS #14520 1.5d (@svor)
- [ ] Refactor plugin system to use DI instead of new operators https://github.com/theia-ide/theia/issues/5761 8.5d @JPinkney 
- [x] Update java support to latest #14649 1d @svor 
- [ ] add 'filter' toolbar item for the debug console https://github.com/theia-ide/theia/issues/6067 3.5d (@tolusha)
# To be planned

- [ ] Replace devfile editor with monaco and YAML LSP  https://github.com/eclipse/che/issues/13939
- [ ] Add support for Vue.js https://github.com/eclipse/che/issues/13672

# From Last Sprint

# Open Pull Requests
  - [x] PR https://github.com/eclipse/che-devfile-registry/pull/73 
Add the devfile to work with c/c++ stack
- [ ] Provided mapping from vscode command ids to internal command ids https://github.com/theia-ide/theia/pull/5590 (@JPinkney)
- [ ] Upgrade Go version to support realworld sample https://github.com/eclipse/che/issues/13803 @tolusha 
    - [x] https://github.com/eclipse/che-theia/pull/443
    - [ ] https://github.com/eclipse/che-devfile-registry/pull/96
    - [x] https://github.com/eclipse/che-plugin-registry/pull/224
Next sprint:
# Blocked issues 
- [x] Maven dependencies are download each time the workspace is getting restarted https://github.com/eclipse/che/issues/13603
- [ ] Che 7 plugin: Update PHP Intelephense to v.1.1.1 - 2019-06-27? #13700 (0.5d @vrubezhny )

# Unplanned Issues

- [ ] NPE in DisconnectRequestHandler.destroyDebugSession(DisconnectRequestHandler.java:28) https://github.com/eclipse/che/issues/13967
- [ ] Tasks of remote plugins are not redirected to corresponding container https://github.com/eclipse/che/issues/13741
- [ ] implement `vscode.executeDocumentSymbolProvider` command for `emmet` VS Code extension https://github.com/eclipse-theia/theia/issues/4048
- [ ] WorkspaceService not Concurrency-Safe https://github.com/theia-ide/theia/issues/5820
- [ ] Simple LSP test suite for Java #14409

Previous Sprint: https://github.com/eclipse/che/issues/14368

**Comment by slemeur** [comment]
please close this sprint
