### ISSUE TITLE
TLS by default

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14742]
### Is your enhancement related to a problem?

I don't see any scenario where users would want to use unsecured http communications.

### Describe the solution you'd like

TLS should be activated by default. It should not be something that the user should bother with. 
- [x] [POC] TLS by default  https://github.com/eclipse/che/issues/15313
- [x] Implement TLS by default for helm Che installer  https://github.com/che-incubator/chectl/pull/476
- [x] Implement TLS by default for operator Che installer https://github.com/eclipse/che/issues/16052 
- [x] Dashboard messages should be more accurate when self-signed cert issue happens https://github.com/eclipse/che/issues/15298
- [x] Redesign SelfSigned cert error page https://github.com/eclipse/che/issues/16065
- [x] Dashboard must clearly describe solution when self-signed TLS issues https://github.com/eclipse/che/issues/16245
- [ ] [chectl] Replace "-s/--tls" parameter with "--no-tls" due to installing Eclipse Che with TLS by default https://github.com/eclipse/che/issues/16302

**Comment by sleshchenko** [comment]
I'm afraid we are not able to provide every user normal certificate.
And if we go with a self-signed certificate (in the same way as minikube/minishift) it might bother user since:
1. they need to import CA certificate into the browser
2. add every Che endpoint to exclusion, like after workspace start, open each of workspace endpoint and mark them as trusted, otherwise, Iframes won't be loaded properly even without a clear message.

I don't say that it's not possible, just sharing thoughts that might be not detailed enough.
So, this issue is not only about changing values of the default value of the parameter and about the investigation of how we can handle it and what is UX.

**Comment by davidfestal** [comment]
I'm also a bit worried about the fact that, in the current state of the Che operator, successfully enabling TLS required correctly setting the related `selfsignedcerts` field. And this can be a risky thing, since it has to be consistent with the status of the Openshift router certificate, else it will fail with non-obvious errors.

So providing a TLS-enabled default that will work in all cases is tricky today.

**Comment by l0rd** [comment]
@sleshchenko yes we should support self signed certs of course. That may be tricky but we have already lost a lot of time because we are not testing with TLS enabled locally. We should automate as much as we can and guide user to accept the self signed certs. 

@davidfestal it should not be "risky" otherwise users that enable TLS will always "risk" to have problems. We want to make TLS the default because we want to put those kind of problems in evidence so that we will fix them.

**Comment by mmorhun** [comment]
This issue is required for new webview plugin API implementation to work. Without it webviews are broken.

**Comment by sleshchenko** [comment]
It seems to be completed. @tolusha Could you revise it?

**Comment by tolusha** [comment]
@sleshchenko 
We are going to add a couple of preflight checks

**Comment by tolusha** [comment]
The following issues will be done out of the TLS epic:
https://github.com/eclipse/che/issues/16762
https://github.com/eclipse/che/issues/16764
https://github.com/eclipse/che/issues/15301
