### ISSUE TITLE
IDE2-2019-11-05 (Sprint: 174)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#14819]
### Sprint Goals:
1. CRW 2.0 productization support

## 1. CRW 2.0 productization support

- [x] Theia remote plug-in runtime in sidecar container improvement #13387 - 5d
  - [x] Rework che-theia remote plugin images #14797 - 5d
- [x] White labelling capabilities for Che 7 #14110 
## Other  issues:
- [ ] Add ability to create a new workspace from the dashboard with a devfile #13591 13d
- [ ] Minimal Firefox Support #14015
  - [x] Terminal is empty on Firefox #13736 -4d 
- [ ] Start analyze using local tools connected to Che workspace #15016
- [x] Dashboard: While editing a devfile of a workspace, user is constantly interrupted by the auto save #13982 -1d
- [x] Che-theia - My workspace view: if available, show the che commands/task that are available in a plugin side car #13587 1d
- [x] Uncaught error after terminal widget creation #13830 3d
- [x] Errors in Che Theia container log when start another instance #13630 3d
- [x] Apply ability to select render for terminal #14772 2d

- Sending Ctrl+C to one terminal widget kills all terminals #14887

## Pending PR
- [ ] Dashboard: fail build when webpack has errors #12911 
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
