### ISSUE TITLE
meta.yaml file no found when launching workspace in Che 7.2.0

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#14821]
### Describe the bug
Start a fresh Che server, create workspace "Java maven". During start-up, this error is shown:
Not Found

The requested URL /v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml was not found on this server.

Error: Failed to run the workspace: "Plugins installation process failed. Error: Plugin broking process for workspace workspace0yqp2t5bxfyczq2i failed with error: Failed to download plugin meta: failed to fetch plugin meta.yaml from URL 'https://che-plugin-registry.prod-preview.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml': Downloading https://che-plugin-registry.prod-preview.openshift.io/v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml failed. Status code 404. Response body:

### Che version
7.2.0

### Steps to reproduce

See above

### Expected behavior
Workspace should start

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [X] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
None

### Installation method
   - [X] chectl chectl server:start --cheimage=eclipse/che-server:7.2.0
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [X ] my computer 
       - [ ] Windows
       - [X] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
None

**Comment by benoitf** [comment]
Hello @JonasHelming 

It looks strange that it's pulling files from 'https://che-plugin-registry.prod-preview.openshift.io/' as it's when no plugin registry is deployed.

Using chectl on minikube is deploying a local plugin registry.

What is the version of chectl that you have please ?

**Comment by JonasHelming** [comment]
Hi Florent!
chectl --version
on
chectl/0.0.2 linux-x64 node-v10.4.1

**Comment by benoitf** [comment]
@JonasHelming ok this version is outdated for che 7.2.0

you should either use chectl 7.2.0 to run che 7.2.0 or use the current next version
https://github.com/che-incubator/chectl#installation

**Comment by JonasHelming** [comment]
chectl --version
chectl/0.0.20191009-next.abfbf17 linux-x64 node-v10.16.3

unfortunatelly still the same error

**Comment by JonasHelming** [comment]
I fixed this by deleting my server (server:delete) and starting from scratch using chectl 7.2.0.
Now workspaces start further, but after installing all images, the screen remains black. In the console of the browser, I find the following errors:

![image](https://user-images.githubusercontent.com/1052615/66557784-c0713100-eb52-11e9-9c17-1c8eac59c791.png)

**Comment by JonasHelming** [comment]
@benoitf : Is there a way to ensure enerything is cleared from my machine to start with a clean setup again or do you have any idea about this new error?

**Comment by benoitf** [comment]
@JonasHelming you could delete `che`namespace in minikube or fully destroy minikube instance (`$ minikube destroy` ) and start a new one after that
`minikube start --memory=8192 --cpus=4 --disk-size=50g`

about chectl, if you've latest version it should be fine. You may also give a try to "nightly" instance by updating chectl:  `$ chectl update next` 

then deploy again che with chectl server:start

**Comment by JonasHelming** [comment]
@benoitf 
Still, workspace remains black after starting it. One thing, do not know whether that is important, but to start the che server, I have to specify the platform like
-p=minikube
otherwise I get an error. Any other ideas what I could try? Thanks!

**Comment by JonasHelming** [comment]
ah, and I believe there is no minikube destroy, I used minikube delete

**Comment by benoitf** [comment]
yes sorry `delete`

**Comment by benoitf** [comment]
@jonashelming 

You still have the same issue with fresh install ?

**Comment by benoitf** [comment]
is your minikube up-to-date as well ?

**Comment by JonasHelming** [comment]
After updating minikube, it works again, thank you for the hint!
Maybe you want to add some version checks to the pre flight check of che to at least print a warning when using older versions?
If not, feel free to close this issue.

**Comment by benoitf** [comment]
related issue https://github.com/eclipse/che/issues/14593#issuecomment-535769427
