### ISSUE TITLE
Platform-2019-11-05 (Sprint: 174)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#14835]
### New Task && Enhancements

- [x] [chectl] Add support for updating from Che 6 -> Che 7 | https://github.com/eclipse/che/issues/14793 | 8
- [x] PKIX error and impossible to start workspaces on OCP 4.1 | https://github.com/eclipse/che/issues/13607 | 8
- [x] <workspace.id> placeholder for workspace namespace/project | https://github.com/eclipse/che/issues/14585 | 3
- [x] [MVP] Collecting Che Workspace metrics in single cluster mode with Prometheus | https://github.com/eclipse/che/issues/14888 | 8

### Finalize issues started in the previous sprint.
- [x] Server support for previewurl | https://github.com/eclipse/che/issues/14893 | 8
- [ ] The default workspaces namespace/project should be `<username>-che` | https://github.com/eclipse/che/issues/14795 | 5
- [x] Monitoring & Tracing capability for multiple Thread pools of Che Server | https://github.com/eclipse/che/issues/14601 | 5

### Unplanned
- [ ] Che Server http sessions leak https://github.com/eclipse/che/issues/14599
- [ ] Create MVP version of user-selection of target namespace for a workspace https://github.com/eclipse/che/issues/14908
- [x] Build of Eclipse Che is unstable on Codenvy CI https://github.com/eclipse/che/issues/14955
- [x] Docker infrastructure decommissioning https://github.com/eclipse/che/issues/14356
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 13d |
| Max Shaposhnik | 13d | 
| Sergii Leshchenko | 13d | 
| Michal Vala | 12d | 
| Lukas Krejci | 12d |
| Total | 63 human*day | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 45  | 40 |
#### Retrospective Comments
- More discussions during the planning phase.
