### ISSUE TITLE
Cannot create a workspace from devfile using Che 7.2.0 - Failed to download theia plugin meta

### ISSUE THREAD

**Issue by ssh24** [eclipse-che/che#14847]
### Describe the bug

Cannot create a workspace from a devfile using Che 7.2.0 nightly build. It complains that it failed to download the theia plugin meta.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace from a devfile using Che 7.2.0

### Expected behavior

The workspace should be created as expected.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

<img width="1353" alt="Screen Shot 2019-10-10 at 3 59 18 PM" src="https://user-images.githubusercontent.com/15173354/66602599-7602ab00-eb78-11e9-9075-bc9ff16cc2e8.png">
<img width="1680" alt="Screen Shot 2019-10-10 at 4 07 15 PM" src="https://user-images.githubusercontent.com/15173354/66602600-7602ab00-eb78-11e9-9aff-328c3ced2a6f.png">

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
   - [x] deploy_che.sh

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by skabashnyuk** [comment]
@ssh24  I'me very sorry for UX that you have. The issue that you have caused by an outdated deployment method with deploy_che.sh. We are going to remove this way of deployment https://github.com/eclipse/che/issues/13888 however at this time we blocked by https://github.com/eclipse/che/issues/14069. I can suggest trying https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-4-from-operatorhub/ or this https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-3-using-the-operator/
Can I also ask you to help us understand why you chouse deploy_che.sh instead of other deployment methods explained in documentation?

**Comment by ssh24** [comment]
@skabashnyuk The main reason I used the `deploy_che.sh` script instead of chetctl or other deployment methods is because I still wanted the single user option. As single user is being deprecated, using other deployment options always deploys che with multi-user
