### ISSUE TITLE
IDE-2019-11-05 (Sprint: 174)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#14850]
### Sprint goals
1. Git + SSH Flow  
2. VS Code plugins
3. UX Improvement 
4. Bugs 
### Sprint details:

1. Git + SSH Flow  
- [ ] Support git clone for repos with self-signed SSL certs https://github.com/eclipse/che/issues/14527
- [x] Improve error message during git push/clone #14615
- [x] Verify that starting a workspace from a devfile works flawlessly with SSH git url to the project repositories https://github.com/eclipse/che/issues/14794
- [x] Document how to use private git repos with ssh key workaround #14917

2. VS Code plugins
- [x] [k8s plugin] Kubernetes: Run command cannot build an image https://github.com/eclipse/che/issues/13702
- [ ] Improve login procedure for GitHub PullRequest Plugin https://github.com/eclipse/che/issues/14217
- [x] [openshift plugin] fix 'Open in Browser' command https://github.com/eclipse/che/issues/13410 
- [x] [openshift plugin] fix 'Open URL' command https://github.com/eclipse/che/issues/13406
- [x] [k8s plugin] cannot login to an image registry #15005

3. UX Improvement 
- [x] Stop running task https://github.com/eclipse/che/issues/13737
- [x] Url in the preview panel should be editable https://github.com/eclipse/che/issues/14829
- [ ] Mark in the task widget title when task is exited. https://github.com/eclipse/che/issues/14132
- [x] Theia should accept previewurl links #14892

4. Bugs
- [x] Theia - variable in previewurl is not evaluated after clicking right-bottom notification popup https://github.com/eclipse/che/issues/14820
- [ ] Unable to clone with SSH: unprotected private key file https://github.com/eclipse/che/issues/14398
- [x] che task: Cannot run a che command after workspace restart for some containers https://github.com/eclipse/che/issues/13993
- [x] Each SSH keypair is mounted as a secret which is created after generation and workspace restart. Need to rework the implementation, so that all SSH keys would use single common secret #14438

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |
