### ISSUE TITLE
Languages Sprint 174

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#14855]
Oct 16-Nov. 5

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 10 | 6 | 9.5
@tolusha | 7 | 4 | 4
@svor | 15 | 9 | 8.5
@vrubezhny | 14 | 8.5 | 8
@JPinkney | 15 | 9 | 9.5

# Priorities
All testing must be done on minishift!

# Planned Issues
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic #13427 @tsmaeder 1d
- [ ] Find a yarn-based example (https://github.com/eclipse/che/issues/14720) 2d @vrubezhny 
- [x] Fix licensing issues in CRW examples #14890 1d @tsmaeder 
- [x] Help out with Rework che-theia remote plugin images (https://github.com/eclipse/che/issues/14797)
  - [x] clang 1d @svor 
  - [x] dotnet 1d @svor 
  - [x] go 1d @svor 
- [ ] Implement Language Server Metrics #14245 0.5d @JPinkney 
- [ ] Add tslint to Typescript language support plugins #14070 2.5d @vrubezhny 
- [x] After updating Monaco Editor some Keybindings has collision for Java LS #14520 0.5d (@svor)
- [ ] Refactor plugin system to use DI instead of new operators https://github.com/theia-ide/theia/issues/5761 2.5d @JPinkney 
- [ ] Replace devfile editor with monaco and YAML LSP  https://github.com/eclipse/che/issues/13939 6d @JPinkney 
- [x] Add Java Sample Based on Google Cloud Samples @svor 3d #14651
- [ ] Quarkus Stack:  https://github.com/eclipse/che/issues/14506 2d @svor 
- [ ] No error message if vscode.open command is invoked with resource that doesn't exist https://github.com/theia-ide/theia/issues/5667 2d @vrubezhny 
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d @vrubezhny 
- [x] Theia can't open files located in a sidecar container #13614 0.5d @tolusha 
- [x] add 'filter' toolbar item for the debug console https://github.com/theia-ide/theia/issues/6067 3.5d (@tolusha)
   - [x] https://github.com/eclipse-theia/theia/pull/6486
# To be planned

# From Last Sprint

# Open Pull Requests
Add the devfile to work with c/c++ stack
- [ ] Provided mapping from vscode command ids to internal command ids https://github.com/theia-ide/theia/pull/5590 (@JPinkney)
- [ ] Upgrade Go version to support realworld sample https://github.com/eclipse/che/issues/13803 @tolusha 
    - [ ] https://github.com/eclipse/che-devfile-registry/pull/96
Next sprint:

# Blocked issues 

- [ ] Che 7 plugin: Update PHP Intelephense to v.1.1.1 - 2019-06-27? #13700 (0.5d @vrubezhny )

# Unplanned Issues
- [ ] add 'References' widget https://github.com/eclipse/che/issues/14856 and https://github.com/eclipse-theia/theia/issues/4784
- [ ] Support `integratedTerminal` for debugging https://github.com/eclipse-theia/theia/issues/6103 (vs code api coverage)
- [ ] Simple LSP test suite for Java #14409 7.5 @tsmaeder 

AMQ Stack for CRW 2.1: 
https://issues.jboss.org/browse/CRW-289

Previous Sprint: https://github.com/eclipse/che/issues/14640

**Comment by slemeur** [comment]
please close this sprint issue
