### ISSUE TITLE
Troubleshooting Installation capabilities 

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14882]
## Goal

The goal of this epic is to make the installation of Eclipse Che easier to diagnose.

As an admin of Eclipse Che, I'd like to be able to get diagnostic of my current installation so I can troubleshoot it. 

**Target User:** Admin of Eclipse Che 

**Problem:**
When installing Eclipse Che, there are a lot of opportunities for things to not behave properly. 
Are resources sufficient?
- Is access to the container registry working?
- Are certificates properly configured

When the deployment is failing it is also challenging to get the logs of what was going on. Admin (who is doing the deployment) will need to investigate and use ‘oc’ or ‘kubectl’ and in certain cases the logs are even not accessible once the installation failed.

### Deployment Pre Checks
Chectl should allow to pre-check the target environment for the deployment. It would check the various conditions that are needed for Che to be properly deployed there:
- Resources
- Access to registry
- Various configuration options
 
### Installation logs retrieval
Chectl should allow the admin to get the logs of the installation. It would provide the logs in a convenient manner, they’ll be downloadable and shareable.

## Sub Tasks
- [x] Collect logs during installation of Eclipse Che https://github.com/eclipse/che/issues/15485
- [x] [Doc] Clarify prerequisites for Che install https://github.com/eclipse/che/issues/15680
- [x] Error messages are not clear when chectl failed to start che-server https://github.com/eclipse/che/issues/14665
- [x] 'chectl' should collect/retrieve operator logs https://github.com/eclipse/che/issues/16073
- [x] [chectl] When chectl needs a Che Access token it references non-existing doc https://github.com/eclipse/che/issues/16132

**Comment by nickboldt** [comment]
I would recommend adding a preflight check to chectl/crwctl that verifies the deployment name is not too long for the internet.

* https://tools.ietf.org/html/rfc7230
* https://tools.ietf.org/html/rfc3986

Scenario where a too-long project name gets half way into a deployment but can't open a workspace:
 https://issues.jboss.org/browse/CRW-528 (using project = "codeready-workspaces" results in the server being exposed on route "codeready-codeready-worksapaces.etc.etc.etc" which results in PVC problems and route failures.

**Comment by tolusha** [comment]
I personally see several areas where we can improve troubleshooting:

- gathering logs, they should be available once installation failed. There is the doc [1] which will help to understand which type of logs we can have. Besides that it is necessary to collect the information about environment, installation tool and its version etc.

- logging
Messages should be understandable, contain proposals (if possible) and reference to a documentation (if needed)

- documentation, 
There are several issues which indicates that the doc is outdated (absent) in some of aspects of installation process

- pre-flight checks.
This is a continuous improvement process. It will be helpful to browse existed `chectl` issues [2] to find out what we need to check

[1] https://www.eclipse.org/che/docs/che-7/retrieving-che-logs/
[2] https://github.com/eclipse/che/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarea%2Fchectl

@mmorhun @AndrienkoAleksandr

**Comment by AndrienkoAleksandr** [comment]
> I personally see several areas where we can improve troubleshooting:

+1

**Comment by tolusha** [comment]
I consider this epic is mainly completed.
