### ISSUE TITLE
OpenShift Connector for Eclipse Che

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#14900]
## Goal
The goal of this epic is to finalize the work that has been done on getting the VSCode OpenShift connector extension available to Che users.

### Target User
Developers using Eclipse Che

### Target environments
- Eclipse Che
- Hosted Che

### Context
As a developer using Eclipse Che, I should be able to interact with an OpenShift cluster without using a command-line tool, so that I can easily explore an existing cluster, create new namespace and deploy applications. 

### Problem
Configuring and using the openshift connector plugin in the context of Eclipse Che is hard. 

- In order to get the OpenShift Connector plugin working, the user needs to also enable the Kubernetes Plugin and the YAML Plugin. But as a user, I have no way to understand those dependencies.
- Eclipse Che can be deployed on an OpenShift Cluster. Depending on the configuration the user should already be connected on the cluster.
- The plugin is not part of any test suites. Regressions are easily getting introduced.
- The plugin should be usable on OCP 3.11, OCP 4.x and tested on various environment like Hosted Che, CRC, OSD
- There are certain commands which are not compatible (or not making sense) in the context of Eclipse Che, example: Watch.

As an admin I should also be able to configure the OpenShift Connector to be available by default with all workspaces so that the developers don't have to manage that configuration in their workspaces.

### Solutions

**Inject the user Kubernetes cluster context in the workspace containers**
- Automatically if the user is authenticated using OpenShift OAuth
- Using chectl workspace:start otherwise

**Add test suites for the plugin**
Include a Kubernetes tooling scenario in the happy path test (PR check)
Include an OpenShift connector scenario in the nightly CI

**Validate the plugin on the different targeted platform of Che** 
(OCP 3.11, OCP 4.x and tested on various environment like Hosted Che, CRC, OSD)

**Add admin configuration option to enable the plugin into all workspaces**

**Restarting the workspace should maintain the cluster configuration:** When a user configure access to some clusters, those information are not persisted. If user restarts the workspace the configuration will need to be done once again

## Sub-tasks

- [x] Improve cluster login flow when Che is on non-secure connection https://github.com/eclipse/che/issues/15093
- [ ] [Improve kubeconfig injection with chectl · Issue #14877 · eclipse/che](https://github.com/eclipse/che/issues/14877)
- [x] [Openshift connector and Che: openshift user should be logged automatically with the Openshift user. · Issue #15261 · eclipse/che](https://github.com/eclipse/che/issues/15261)

**Comment by azatsarynnyy** [comment]
> In order to get the OpenShift Connector plugin working, the user needs to also enable the Kubernetes Plugin and the YAML Plugin. But as a user, I have no way to understand those dependencies

That has been improved for almost 5 months ago.
Currently, the user doesn't need to understand those dependencies and he/she even couldn't know about them. The dependent plugins are installed automatically in the same way as in VS Code.
Thanks to Josh's PR https://github.com/eclipse-theia/theia/pull/5379
@slemeur could you please provide some use case when the problem is still reproducible? It would  help to diagnose it.

**Comment by azatsarynnyy** [comment]
> There are certain commands which are not compatible (or not making sense) in the context of Eclipse Che, example: Watch

`Watch` command is very helpful for updating a component on change.
Sorry, I can't understand why some commands are not making sense in Che.
@slemeur could you please clarify?

**Comment by slemeur** [comment]
@azatsarynnyy : In which situation would you prefer to do a `watch` from running the code source in your workspace?

**Comment by azatsarynnyy** [comment]
> isn't it faster to run it as part of the workspace?

if one runs everything inside the workspace, why he/she could require OpenShift plugin then?
I guess I misunderstand something.

**Comment by l0rd** [comment]
Related to https://github.com/eclipse/che/issues/15261 and https://github.com/eclipse/che/issues/15670

**Comment by ericwill** [comment]
All the plugins related items from this epic are complete, only the chectl item(s) remain.

**Comment by tolusha** [comment]
@ericwill 
We will try to take remaining issue in the next sprint.
