### ISSUE TITLE
User-selection of target namespace for a workspace

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#14908]
### Is your task related to a problem? Please describe.
This issue represents a minimal implementation of https://github.com/eclipse/che/issues/14379.

This includes the following steps:

* [x] Introduce a query parameter on `/workspace/devfile` to specify the namespace the workspace should be created in
* [x] store the namespace in the workspace attribute
* [x] Modify the runtime provisioning API to include at least the target namespace (but I see no problem with having the whole workspace object there)
* [x] Modify the logic in `KubernetesNamespaceFactory` and `OpenshiftProjectFactory` to use the namespace propagated to it when creating the namespace.
* [x] Make sure that if the user provides no namespace we use the logic from #14828.
* [x] make the testsuite pass in PR https://github.com/eclipse/che/pull/15040 (#15129)
* [x] make sure new workspaces always use the new namespace config (#15129)
* [x] make sure the operator sets the `...namespace.default` to the same value as the pre-existing `...namespace`/`...project` property during the update of the che server (https://github.com/eclipse/che/issues/15119)
* [x] ~~Add namespace to the devfile model (`metadata.namespace`) (https://github.com/eclipse/che/issues/15120)~~
* [x] decide on the location and format of the overrides - this is already in discussion on the mailing list (also affects other issues like https://github.com/eclipse/che/issues/13617) - *we're going to implement the overrides in the factory API and the namespace selection in the workspace API*
* [x] implement the namespace override on the chosen API endpoint (#15130)
* [x] document the change in the namespace default and the way it can be configured - *already present in https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc*
* [x] document the user-defined selection of the namespace - *currently we only have this feature in the REST API, so the documentation will end up in the generated docs for the REST API.*

### Additional context
This is a minimal version of #14379. We're leaving out the validation of the selected namespace and checking of permissions for namespace creation

**Comment by metlos** [comment]
I think this can be parallelized as follows:

1. Do the "frontend" changes:
    * [ ] Introduce a query parameter on `/workspace/devfile` to specify the namespace the workspace should be created in (the format of the query parameter should take into account the fact that we're essentially overriding a standard k8s object attrbute, so I'd call it `metadata.namespace` - we will probably be adding this attribute into the devfile proper as well once we move out of MVP with this)
    * [ ] store the selected namespace in the workspace config attribute when creating the workspace object
1. Do the backend changes
    * [ ] Modify the runtime provisioning API to include at least the target namespace (but I see no problem with having the whole workspace object there)
    * [ ]  Modify the logic in `KubernetesNamespaceFactory` and `OpenshiftProjectFactory` to use the namespace propagated to it when creating the namespace.

While the backend changes are larger than the frontend ones, I don't unfortunately see an easy way of parallelizing them, because the second depends on the first.

**Comment by metlos** [comment]
We've decided to not merge this MVP into master and instead follow up on it to bring the finished feature into master. That's why I'm reusing this issue for the feature (and am updating the title and description) just to have some continuity of context.

**Comment by metlos** [comment]
#### Progress report

We've spent time mostly on refactoring my original draft, making some substantial simplifications and clarification of the logic involved in namespace creation. All of the proposed changes have now been implemented (under #15129) and the only outstanding thing on that issue is to make the testsuite pass again.

After that, we have to add the query parameter on the workspace creation REST endpoint to specify the namespace (this is already possible through `attributes=infrastructureNamespace:blah` but we want to be more specific and user friendly and have a dedicated query parameter for the namespace selection).

Finally, we need to write documentation about the change of the default namespace (which already happened in 7.4.0) and about the user selection of the namespace - explaining how it is affected by che configuration, cluster permissions and what logic Che server follows when using such namespace.

**Comment by metlos** [comment]
Implemented in PR #15040.
