### ISSUE TITLE
Release Che v7.3.1

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14947]
### Is your task related to a problem? Please describe.

We plan to release Che version 7.3.1 with a few considered critical

### Issues/Commits that should be included in the release 

- [x] PKIX error and impossible to start workspaces on OCP 4.1 https://github.com/eclipse/che/issues/13607
- [x] Theia remote plug-in runtime in sidecar container improvement https://github.com/eclipse/che/issues/13387
- [x] Rework che-theia remote plugin images https://github.com/eclipse/che/issues/14797 Upstream(alpine) images is merged, CRW images in progress, we can release 7.3.1 without them
- [x] Document how to use private git repos with ssh key workaround  #14917
- [x] Improve error message during git push/clone #14615
- [x] Workspace cannot start in airgap mode because the workspace container names are too long #14958 **PR merged** - https://github.com/eclipse/che/pull/14964 / https://github.com/eclipse/che/pull/15004
- [x] "Projects with "type": "zip" are extracted to a subpath, breaking devfiles #14800 **PR merged** - https://github.com/eclipse/che-devfile-registry/pull/127
- [x] Enable branding on the ConsoleLink elements created by the che operator #14809 **PR merged** https://github.com/eclipse/che-operator/pull/101
- [ ] [docs] Document airgap/offline Che deployment process/options #14866 **PR sent / doc team review is required** - https://github.com/eclipse/che-docs/pull/868
- [x] Allow using the Devfile registry in offline mode in the Che Operator #14880 (Optional) **PR merged** - https://github.com/eclipse/che-operator/pull/102
- [x] Branding works incorrectly https://github.com/eclipse/che/issues/14982
- [x] Che Theia Dependency Analytics plugin doesn't work #14942
- [ ] ~~chectl is not compliant with the codeready deployment flavor / stucks at the PostgreSQL pod bootstrap (Post installation checklist)  **WIP**~~ **Not for 7.3.1** #14963

### Release status:

- [x] che-theia @evidolob  `docker.io/eclipse/che-theia:7.3.1`
- [x] che-machine-exec @ibuziuk `quay.io/eclipse/che-machine-exec:7.3.1`
   - [x] https://github.com/eclipse/che-machine-exec/pull/50
- [x]  che-plugin-registry @ibuziuk `quay.io/eclipse/che-plugin-registry:7.3.1`
    - [x] Release PR - https://github.com/eclipse/che-plugin-registry/pull/275
    - [x] Adding `7.3.1` versions of che-theia & machine-exec to nmaster - https://github.com/eclipse/che-plugin-registry/pull/280 
- [x] che-devfile-registry @ibuziuk `quay.io/eclipse/che-devfile-registry:7.3.1`
    - [x] Release PR - https://github.com/eclipse/che-devfile-registry/pull/133
- [x] che @vparfonov 
   - [x] che-parent
   - [x] che-docs 
   - [x] che 
- [x] che operator @davidfestal https://github.com/eclipse/che-operator/pull/113
   - [x] Pending PRs to the community-operators:
      - [x] https://github.com/operator-framework/community-operators/pull/839
      - [x] https://github.com/operator-framework/community-operators/pull/840
- [x] chectl @l0rd

**Comment by ibuziuk** [comment]
@l0rd there is also https://github.com/eclipse/che/issues/14800 which we might also need to consider

**Comment by nickboldt** [comment]
Downstream impact: https://issues.jboss.org/browse/CRW-318

**Comment by ibuziuk** [comment]
Have also added - Workspace cannot start in airgap mode because the workspace container names are too long #14958

**Comment by ibuziuk** [comment]
Adding - chectl is not compliant with the codeready deployment flavor / stucks at the PostgreSQL pod bootstrap (Post installation checklist) #14963

**Comment by nickboldt** [comment]
Can we add Che Theia Dependency Analytics plugin doesn't work https://github.com/eclipse/che/issues/14942 too?

**Comment by ibuziuk** [comment]
@davidfestal going to close this issue once the following PRs are merged:

- operator-framework/community-operators#839
- operator-framework/community-operators#840

**Comment by l0rd** [comment]
7.3.1 has been released. Closing
