### ISSUE TITLE
IDE2-2019-11-26 (Sprint: 175)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#15039]
## Availability
Who | available | x0.6 
-- | -- | -- | 
@evidolob | 15 | 4 | 
@sunix  | ? | ? | 
@AndrienkoAleksandr  | 15 | 9 |
@vitaliy-guliy  | 15 | 9 |
@mmorhun  | 15 | 9 | 
@olexii4   | 7 | 4,2 | 
@akurinnoy   | 15 | 9 |
**Total** | **82** | **44,2** |

### Sprint Goals:
1. CRW 2.0 productization support
2. Che-theia bug fix and enhancement

## 1. CRW 2.0 productization support
- [x] [regression] Whitelabel support in Che 7 requires specific image names, where in Che 6 we could override with json #15015 4h
- [x] che-theia jest test 'use default extensions' is unstable. #14276 PR
- [x] Build of Eclipse Che failed on Dashboard WAR artifact #15082 PR
## 2. Che-theia bug fix and enhancement
- [x] Plugin installation fails from che-theia workspace #15006 3d
- [x] Persist Theia theme Change in user preferences #15104 4d
- [x] Enable "Copy on Selection" for terminal #15106 5d
- [ ] Che Theia IDE is reloaded spontaneously #14933 2d
- [x] Error during loading go stack #14931 2d
- [ ] Default-host - Some resources (css, js, images) in IDE does not work #14883 2d
- [x] Branding JSON for UD includes old CHE-6 links #14763 1d
- [ ] Workspace fails to start/open. Caused by `Unknown error` during websocket connection establishing #14726 3d
- [x] Dashboard must not send keycloak token to plugin and devfile registries #14627 1d
- [x] Sending Ctrl+C to one terminal widget kills all terminals #14887 3d
- [x] Failure to Start Workspace after Changing Name #14762 1d
- [x] Style broken for restart workspace button which appears after installing plugin from Che Theia on Mac OS in Chrome #15045 1d

## Other  issues:
- [x] Add ability to create a new workspace from the dashboard with a devfile #13591 1d
- [ ] Minimal Firefox Support #14015
   - [ ] bright fonts are not set on dark theme on Firefox #13442 2d
- [x] Theia shows two dialogues when previewUrl is defined in command #14802 3d
- [ ] Unexpected filtering in plugins view in Che-Theia #14754 5d
- [ ] Move all Che Theia docker images from DockerHub to the quay.io #14849 5d

## Pending PR
- [x] Dashboard: fail build when webpack has errors #12911 
**Total planned = [todo]sp**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)
