### ISSUE TITLE
IDE-2019-11-26 (Sprint: 175)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#15044]
### Sprint goals
1. Git + SSH Flow  
2. VS Code plugins
3. UX Improvement 
4. Bugs 
### Sprint details:

1. Git + SSH Flow  
- [x] Support git clone for repos with self-signed SSL certs https://github.com/eclipse/che/issues/14527
- [x] When user is doing a commit if git info (git.username and git.email) are not configured, allow the user to configure it. #14616
- [x] SSH Key upload in Che 7 #14911

2. VS Code plugins
- [x] Locate kubernetes tasks under corresponding containers #15042
- [ ] [k8s plugin] buildah push command doesn't work #15035
- [x] [openshift plugin] improve cluster login flow when Che is on non-secure connection #15093
- [x] [Kubernetes Plugin] Kubernetes: Diff command doesn't open diff view when running in a sidecar #13044
- [ ] Theia Editor Key Bindings switching (Default, VI, Emacs) #9244

3. UX Improvement 
- [ ] Mark in the task widget title when task is exited. https://github.com/eclipse/che/issues/14132
- [x] [docs] Document preferences related to preview URL functionality #14999
- [x] 'Open Terminal in specific container' usability #14987
- [ ] Improve UX during ${current.project.path} macros usage #13636
- [x] Provide curated list of containers to run tasks #13390

4. Bugs
- [x] Unable to clone with SSH: unprotected private key file #14398
- [x] Outdated typescript types of @eclipse-che/api #14755
- [x] Che preferences are not displayed after page refreshing #15001

Unplanned
- [x] After launching an application the preview URL widget does not appear #15173
- [x] Che tasks are not available for running #15179
- [x] Task editor should properly handle the che commands syntax #13984
#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |
