### ISSUE TITLE
Workspace diagnosis capabilities in Eclipse Che

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15047]
### Is your task related to a problem? Please describe.

A workspace is a set of microservices and there is a lot of complexity hidden from the end-user. 
When a workspace does not behave as expected, it is very hard to understand what is going on, where to get the information, where to get the logs. It makes the diagnosis of bugs very hard

## Workspace startup
- All logs of the workspace startup should be ~persisted and~ available to the end user.
  - All the containers logs of the workspace should be available.
  - The plugin broker logs
  - The JWT proxy logs
  - ~Che server (when reading the devfile)~
   - ~The language servers, the editor and any plugins logs (note that those logs are generally not available as container logs)~
 - ~Logs should be downloadable, so they can be exported in an issue and shared.~
 - ~We would keep history of the latest 5 startup of the workspace~
 - ~Logs should be available from chectl (to start)~

## Running workspace
- We should have a widget displaying the status of the workspace. This could be an option of the “workspace panel”. 
  - We should display the resource usage in each of the containers
  - We should allow the user to access to the logs of a container (links to command on getting the logs, or links to the openshift console) 
- Chectl should allow to export the logs of a currently running workspace.

## Implementation

- [x] Eclipse Che Server doesn't notify user when OOM happens during workspace start https://github.com/eclipse/che/issues/13511
- [x] Publish plugin broker pod events https://github.com/eclipse/che/issues/14854
- [x] Misleading message form CHE server when a container stopped https://github.com/eclipse/che/issues/14781 
- [x] [POC] Access to the workspace containers logs https://github.com/eclipse/che/issues/15134
- ~[ ] [POC] Access to the workspace lifetime event log https://github.com/eclipse/che/issues/15135~

#### Access to the workspace logs
as a result of https://github.com/eclipse/che/issues/15134
- ~[ ] Write workspace's containers stdout/err log to file #15834~
- ~[ ] Create LogCollector component #15835~
- ~[ ] Archive logs on che-server #15836~
- ~[ ] User can access workspace logs from che-server #15837~
- [x] Workspace start in debug mode -> watch the logs #15983
- [x] [dashboard] - restart workspace in debug mode after startup failure #16050
- [x] Watch plugin broker logs in workspace startup debug mode #16061
- [x] new metrics related to workspace startup log watch #16062
- [x] [dashboard] - make it possible to download all workspace startup logs #16063
- [x] Watch plugin broker logs #16117
- [x] [chectl] - offer to run workspace in debug mode #16119
- [x] Watch mkdir pod logs in workspace startup debug mode #16161

#### Access to the workspace lifetime event log
as a result of https://github.com/eclipse/che/issues/15135 
TBD

**Comment by skabashnyuk** [comment]
@l0rd @slemeur  
1. The description of this epic is more concentrated around logs. Should we invest our time on k8s events https://github.com/eclipse/che/issues/15135 or logs should be our p1? 

2. Can we put resource usage out of the scope of this task? It is very connected to https://github.com/eclipse/che/issues/13484 maybe we should implement it as part of that epic?

**Comment by sparkoo** [comment]
Here's some proposal draft of possible solution:

## 1. archive stdout logs
#### This assumes 2 extra PVs
  `wslPV` - per workspace instance, ws writes logs there directly
  `nslPV` - per namespace, collector pod copy the logs there after ws exits

**Steps**
  1. stdout/err logs of all ws containers to file
  2. mount "wslPV" where stdout logs are stored
  3. watch ws exit event -> start collector pod that will mount `wslPV` and `nslPV`. Copy logs `wslPV -> nslPV` in easily identifiable directory (`wsid_timestamp` ?)

Alternatively, we could send the logs to some other backend than `nslPv`, but this looks as simplest first solution. Still open question.

#### Without the PVs:
**Steps**
  1. same
  2. onExit -> start collector pod, grab all logs and send them to master (some new API). At this point, workspace can't be started.

## 2. access archived logs
On master's request, start logprovider pod in ws namespace. logprovider will mount `nslPV` and provides logs to the master.

**Steps**
  1. Design api between logprovider and master. We should probably send only some metadata first and big log files only on request.
  2. logprovider pod will run on demand. We have to define reliable exit condition so it won't hang.
  3. Design che-server API to provide logs to the user.

## 3. collect file logs
Some components might be logging into files somewhere in the container. We can't know where all the logs are, thus we have to give the option to define the directory where it write the logs. We need to enhance plugin's `meta.yaml` as well as the devfile. Once we have that, we can redirect the logs into `wslPV` and collect them with collector pod as in **1**.

**Steps**
  1. Design `meta.yaml` and `devfile` changes needed to be able to define file logs
  2. Somehow get these logs into `wslPV` or collect them with collector

## extras: things to not forget to at least think about them
  - quotas. It should be easy with dedicated PV in the namespace. Harder if managed by master.
  - what if logs are big (gigs)? collect only last 100M?
  - can we afford to have these new PVs? If not, we 
  - what if ephemeral mode ?

**Comment by sparkoo** [comment]
Here's some proposal draft of possible solution:

## 1. archive stdout logs
  1. stdout/err logs of all ws containers to file on containers. The location has to be on workspace PV and has to be known. 
  2. Watch ws exit event -> start collector pod that will grab all logs and send them to the *backend*.

What is *backend* is open question. At this point, we will send logs to the master's logs endpoint, which does not exist yet.

## 2. access archived logs
  1. Design che-server API to provide logs to the user
  2. Provide the logs on request via the API. This very much depends on chosen storage backend.

## 3. collect file logs
Some components might be logging into files somewhere in the container. We can't know where all the logs are, thus we have to give the option to define the directory, where the component is logging, to be able to collect them later. We need to enhance plugin's `meta.yaml` as well as the devfile. Once we have that, we can collect the logs with collector pod, same as in **1.**.

  1. Design `meta.yaml` and `devfile` changes needed to be able to define file logs dir to collect
  2. Somehow grab these logs with collector

## extras: things to not forget to at least think about them
  - quotas management
  - what if logs are big (gigs)? collect only last 100M?
  - what if ephemeral mode ?
  - what all should be configurable? (number of archived workspace starts, max size of the logs per user, cleanup old logs based on time)

**Comment by sparkoo** [comment]
all issues int the scope of this epic are done, closing
