### ISSUE TITLE
Languages Sprint 175

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15049]
Nov 6-Nov 26

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 10 | 6 | 6.5
@tolusha | 15 | 9 | 9.5
@svor | 13 | 8 | 8
@vrubezhny | 15 | 9 | 9
@JPinkney | 9 | 6 | 8.5

# Priorities
All testing must be done on minishift!

# Planned Issues
- [x] Prepare Enablement Session for CEE Folks #15085 @tsmaeder 4d @svor 4d
- [ ] Fix example: https://issues.jboss.org/browse/CRW-452 1d @svor 
- [ ] Quarkus Stack:  https://github.com/eclipse/che/issues/14506 1d @svor 
- [ ] Multiple issues with vscode-quarkus extension #15118
  - [ ] Welcome page is empty https://github.com/eclipse/che/issues/15113 2d (review PR)
  - [ ] Can't debug Quarkus application https://github.com/eclipse/che/issues/15114
  - [ ] Can't add Quarkus extension to the project https://github.com/eclipse/che/issues/15116 2d @svor 
  - [x] quarkus:dev task was generated incorrectly https://github.com/eclipse/che/issues/15117 2d  @tolusha 
- [x] Support `integratedTerminal` for debugging https://github.com/eclipse-theia/theia/issues/6103 (vs code api coverage) @tolusha 2d
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic #13427 2d @tsmaeder 
- [ ] Simple LSP test suite for Java #14409 7.5 @JPinkney 
- [ ] add 'References' widget https://github.com/eclipse/che/issues/14856 and https://github.com/eclipse-theia/theia/issues/4784 3d @vrubezhny 
- [ ] Consume VS Code built-in extensions in Che-Theia #14759 5d @tolusha 
- [ ] Add preLaunchTask into debug configuration for .Net samples #15025
- [ ] Add an information about cpp into Language support troubleshooting document #14943 0.5 (@tsmaeder )
- [ ] Find a yarn-based example (https://github.com/eclipse/che/issues/14720) 2d @vrubezhny 
- [ ] No error message if vscode.open command is invoked with resource that doesn't exist https://github.com/theia-ide/theia/issues/5667 2d @vrubezhny 
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d @vrubezhny 
- [ ] Che 7 plugin: Update PHP Intelephense to v.1.1.1 - 2019-06-27? #13700 (0.5d @vrubezhny )

# To be planned

# From Last Sprint

# Open Pull Requests
Add the devfile to work with c/c++ stack
- [ ] Provided mapping from vscode command ids to internal command ids https://github.com/theia-ide/theia/pull/5590 (@JPinkney) (approved)
- [ ] Refactor services parts of plugin-ext to use DI https://github.com/eclipse-theia/theia/pull/6358 0.5d (check against che-theia)
- [ ] plugin-ext-metrics extension for creating metrics from language plugins https://github.com/eclipse-theia/theia/pull/6303 (0.5)
- [ ] Upgrade Go version to support realworld sample https://github.com/eclipse/che/issues/13803 @tolusha 0.5
    - [ ] https://github.com/eclipse/che-devfile-registry/pull/96
Next sprint:

# Blocked issues 

- [ ] Add tslint to Typescript language support plugins #14070 2.5d @vrubezhny 

# Unplanned Issues

AMQ Stack for CRW 2.1: 
https://issues.jboss.org/browse/CRW-289

Previous Sprint: https://github.com/eclipse/che/issues/14640
