### ISSUE TITLE
[che-operator] Setup of Tracing/Monitoring stack

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15046]
### Is your task related to a problem? Please describe.

We should provide an ability to configure Tracing/Monitoring in Eclipse Che. 

### Describe the solution you'd like
With the help of che-operator we should be able to:
- [ ] Install Prometheus
- [ ] Install Grafana
- [ ] Install Jaeger
- [ ] Reconfigure Che server and connect it to Prometheus/Jaeger
- [ ] Reconfigure Grafana and connect it to Prometheus
- [ ] Ability to reuse existed Prometheus/Jaeger/Grafana

We need to figure out during implementation is:  are we going to use the operator and wich exactly.
- https://github.com/integr8ly/grafana-operator
- https://github.com/jaegertracing/jaeger-operator
- https://github.com/coreos/prometheus-operator

## Implementation
- [x] [POC] How to configure monitoring/tracing with che CRD #15136
- [ ] Install and setup Monitoring - Prometheus & Grafana
  ~- [x] [che-operator] Install and setup grafana-operator/prometheus-operator #15137~
  - [x] [che-operator] - enable che-server monitoring endpoint #15210
  - [ ] [che-operator] - create ServiceMonitor and GrafanaDashboard when CRDs available and monitoring enabled #15211
  - [ ] [che-operator] - install Prometheus with Prometheus CR #15212
  - [ ] [che-operator] - install Grafana with Grafana CR https://github.com/eclipse/che/issues/15299
  - [ ]  [che-operator] when metrics enabled, create and configure full monitoring stack by default #15302 
 - [ ] Install and setup Tracing - Jaeger
   - [ ] [che-operator] - enable che-server tracing #15213
   - [ ] [che-opeartor] install Jaeger #15214
 - [ ] Jaeger storage #15215

### Describe alternatives you've considered
n/a
### Additional context
n/a

**Comment by sparkoo** [comment]
Overall analysis of monitoring/tracing is summarized in this comment https://github.com/eclipse/che/issues/15136#issuecomment-553937561 I've created several issues and updated description of this epic with proposed implementation steps.

**Comment by skabashnyuk** [comment]
won't fix
