### ISSUE TITLE
E2E test suite for Che 7 - NodeJS version

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15103]
# E2E test suite for Che 7 - NodeJS version

This is the description of an E2E UI testing of Eclipse Che 7 similar to #12728 but for NodeJS applications.

#### Steps

- [ ] Install minikube
- [ ] Pre-pull docker images needed by the workspace:
  - Usual ones
    - `quay.io/eclipse/che-operator:nightly`
    - `centos/postgresql-96-centos7:9.6`
    - `eclipse/che-keycloak:nightly`
    - `eclipse/che-server:nightly`
    - `busybox`
    - `quay.io/eclipse/che-devfile-registry:nightly`
    - `quay.io/eclipse/che-plugin-registry:nightly`
    - `registry.access.redhat.com/ubi8-minimal:8.0-213`
    - `quay.io/eclipse/che-jwtproxy:dbd0578`
    - `eclipse/che-init-plugin-broker:v0.24`
    - `eclipse/che-unified-plugin-broker:v0.24`
    - `docker.io/eclipse/che-theia-endpoint-runtime-binary:next`
    - `docker.io/eclipse/che-machine-exec:next`
    - `docker.io/eclipse/che-theia:next`
  - Specific to the workspace
    - `mariolet/nodejs-sample-backend`
    - `mariolet/nodejs-sample-frontend`
    - `docker.io/eclipse/che-remote-plugin-node:next`
- [ ] Deploy Che: run `chectl server:start --installer=operator --platform=minikube`
- [ ] Create a new Che user and login as that user

#### Success criteria

- Minikube status is running
- Che, Keycloak and Postre are Running
- It's possible to login as a new user and access the dashboard
- Images are pulled

#### Steps

- [ ] 1 - Deploy Guestbook:

```bash
REPO="l0rd/nodejs-sample"
BRANCH="master"
K8S_MANIFEST_DIR="https://raw.githubusercontent.com/${REPO}/${BRANCH}/kubernetes-manifests"
NAMESPACE="nodejs-sample"
kubectl create namespace "${NAMESPACE}"
kubectl apply -n "${NAMESPACE}" -f "${K8S_MANIFEST_DIR}"/mongo.deployment.yaml
kubectl apply -n "${NAMESPACE}" -f "${K8S_MANIFEST_DIR}"/mongo.service.yaml
kubectl apply -n "${NAMESPACE}" -f "${K8S_MANIFEST_DIR}"/guestbook-backend.deployment.prod.yaml
kubectl apply -n "${NAMESPACE}" -f "${K8S_MANIFEST_DIR}"/guestbook-backend.service.yaml
kubectl apply -n "${NAMESPACE}" -f "${K8S_MANIFEST_DIR}"/guestbook-frontend.deployment.prod.yaml
kubectl apply -n "${NAMESPACE}" -f "${K8S_MANIFEST_DIR}"/guestbook-frontend.service.yaml
```

- [ ] 2 - Generate a devfile for the development of that application:

```bash
chectl devfile:generate \
        --namespace="${NAMESPACE}" \
        --language=typescript \
        --git-repo='https://github.com/l0rd/nodejs-sample.git' \
        --plugin='{"type": "chePlugin", "id": "redhat/vscode-yaml/latest"}' > guestbook.devfile.yaml
```

#### Success criteria

- The CRUD application is responding
- A valid devfile is generated

#### Blockers and workarounds

- https://github.com/eclipse/che/issues/14460

#### Steps

- [ ] 1 - Start a workspace using a devfile

```bash
TOKEN=<Che OIDC token>
DEVFILE=https://raw.githubusercontent.com/l0rd/nodejs-sample/master/devfile.yaml
chectl workspace:start --access-token="${TOKEN}" --devfile="${DEVFILE}"
```

#### Success criteria

- Workspace started successfully
- Workspace is started in less than X seconds
- Project is cloned
- Typescript LS and Node debug adapter are initialized correctly
- YAML LS is initialized correctly
- Kubernetes tooling is initialized correctly
- GitHub PR plugin is initialized correctly
- Terminal work

#### Steps

- [ ] 1 - Open a Javscript file, change some code, verify that error highlighting, code completion and code navigation work
- [ ] 2 - Use the "Run frontend" task and and verify that port 8080 is proposed to be exposed and that the application is accessible and has the code change applied at step 1 is taken into account
- [ ] 3 -  Set a breakpoint in the frontend application and select Debug->Start Debugging to verify that the application stops at the breakpoint

#### Success criteria

- Typescript Code completion, error highlighting and code navigation should work successfully
- The provided "Run" task executes successfully and a pop-up ask to open the application URL
- Changes done at step 4.1 should be applied
- NodeJS Debugger should be able to attach successfully when selecting "Start Debugging".
- NodeJS Debugger should be stop at a breakpoint and resume application execution when clicking on resume.

**Comment by l0rd** [comment]
@dmytro-ndp do you think you will be able to work on this or should I close the issue?

**Comment by dmytro-ndp** [comment]
@Katka92: does Hosted Che QE team have resources to automate this test execution?

**Comment by Katka92** [comment]
Hi @dmytro-ndp, I think this issue is for Hosted Che team (mainly @ScrewTSW and @Warfvf), but I'm not sure about the priority. Our goal now is to have green and stable currently existing tests and after that, we plan to cover other test cases. If the priority of this issue is higher, please let me know.
