### ISSUE TITLE
Release Che v7.3.2

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15107]
### Is your task related to a problem? Please describe.

We may need to release Che 7.3.2. This task is to track the list of fixes that should be added to the release:

- [x]  [7.3.1 version uses obsolete version of the plugin-broker (v0.22 instead of v0.24) · Issue #15099 · eclipse/che](https://github.com/eclipse/che/issues/15099)
  - [x] PR - https://github.com/eclipse/che/pull/15178
- [x]  macnine-exec Add absent /tmp folder in the exec image to fix task SIGINT termination https://github.com/eclipse/che-machine-exec/pull/57
- [x] [Dashboard should use default icon for devfiles when actual icon is inaccessible · Issue #15089 · eclipse/che](https://github.com/eclipse/che/issues/15089)
   - [x] Airgap improvements:
     - [x] https://github.com/eclipse/che-plugin-registry/pull/294
     - [x] https://github.com/eclipse/che-devfile-registry/pull/143 
- [x] [Plugin installation fails from che-theia workspace · Issue #15006 · eclipse/che](https://github.com/eclipse/che/issues/15006)
- [x] [The `token-exchange` setup during Keycloak configuration fails on CRW #15152](https://github.com/eclipse/che/issues/15152)
- [ ] [[CRW-466] Get plugins from theia-ide does not work if CRW 2.0 deployed with switched on TLS](https://issues.jboss.org/browse/CRW-466)

## Release status

- [x] che-theia @evidolob `eclipse/che-theia:7.3.2`
- [x] che-machine-exec @ibuziuk `quay.io/eclipse/che-machine-exec:7.3.2` / https://quay.io/repository/eclipse/che-machine-exec?tab=tags&tag=7.3.2
  - [x] https://github.com/eclipse/che-machine-exec/pull/58
- [x] che-plugin-registry @ibuziuk `quay.io/eclipse/che-plugin-registry:7.3.2`
https://quay.io/repository/eclipse/che-plugin-registry?tab=tags&tag=7.3.2
   - [x] https://github.com/eclipse/che-plugin-registry/pull/297
- [x] che-devfile-registry @ibuziuk `quay.io/eclipse/che-devfile-registry:7.3.2`
https://quay.io/repository/eclipse/che-devfile-registry?tab=tags&tag=7.3.2
   - [x] https://github.com/eclipse/che-devfile-registry/pull/145
- [x] che @vparfonov 
   - [x] che-parent
   - [x] che-docs 
   - [x] che 
- [x] che-operator @davidfestal
- [x] chectl @benoitf

**Comment by dmytro-ndp** [comment]
Does it affect CRW 2.0.0?

**Comment by l0rd** [comment]
Yes this is a list of eventual fixes needed for CRW 2.0.0

**Comment by dmytro-ndp** [comment]
Thanks.

**Comment by ibuziuk** [comment]
@l0rd I think we should also include https://github.com/eclipse/che/issues/15006

**Comment by vparfonov** [comment]
what due dates?

**Comment by l0rd** [comment]
@ibuziuk added

@vparfonov we want this to be included in CRW 2.0.0 so we should release at the beginning of next week. Something important to mention is that as far as I am concerned those are not blockers: if we don't have a fix for them by the beginning of next week we can add them in the doc among "Known Issues". In other words: let's do the  7.3.2 release at latest next Tuesday with whatever we have. Does that make sense?

**Comment by ibuziuk** [comment]
@amisevsk I think we probably need to backport - https://github.com/eclipse/che-plugin-registry/pull/282

**Comment by amisevsk** [comment]
Cherry-pick PRs for registries: https://github.com/eclipse/che-plugin-registry/pull/294, https://github.com/eclipse/che-devfile-registry/pull/143

**Comment by evidolob** [comment]
We need https://github.com/eclipse/che/pull/15194 for 7.3.2

**Comment by ibuziuk** [comment]
@evidolob @l0rd Plugin installation fails from che-theia workspace · Issue #15006 · is closed but was it cherry-picked on 7.3.x ?

**Comment by l0rd** [comment]
@ibuziuk the fix required a commit on eclipse/che side https://github.com/eclipse/che/pull/15180. Not sure you tested with that commit as well.

**Comment by ibuziuk** [comment]
Dashboard restart is cherry-picked - https://github.com/eclipse/che/pull/15194 
Just want to make sure that all critical fixes are also backported to 7.3.x

**Comment by ibuziuk** [comment]
The release has been done. Closing
