### ISSUE TITLE
Platform-2019-11-26 (Sprint: 175) 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15115]
### New Task && Enhancements

- [ ] che factory: should be able to override the name, source.repo, source.branch of the workspace that will be created in the url kind/enhancement severity/P2 team/platform | https://github.com/eclipse/che/issues/13617 | 8
- [x] Publish plugin broker pod events | https://github.com/eclipse/che/issues/14854 | 5
- [x] [POC] How to configure monitoring/tracing with che CRD | https://github.com/eclipse/che/issues/15136 | 8
- [x] Support `env` for components of type kubernetes/openshift | https://github.com/eclipse/che/issues/15121 | 5

### Finalize issues started in the previous sprint.

- [x] Che Server http sessions leak | https://github.com/eclipse/che/issues/14599 | 3
- [ ] Finish up the namespace-selection MVP | https://github.com/eclipse/che/issues/15129 | 8

### Bugs and technical debt
- [x] PVCs strategy in Che 7 docs are not up to date | https://github.com/eclipse/che/issues/14654 3
- [x] Set the `che.infra.kubernetes.namespace.default` property on update of che server | https://github.com/eclipse/che/issues/15119 5

### Unplanned
- [x] Che plugin registry use wrong redirect url https://github.com/eclipse/che/issues/15189
- [x] Multiple threads blocked in org.jgroups.protocols.Locking$ClientLock.lock(Locking.java:970) https://github.com/eclipse/che/issues/15231 
- [x] PSQLException: ERROR: insert or update on table "che_workspace_activity" violates foreign key constraint "ws_activity_workspace_id" https://github.com/eclipse/che/issues/15248 
- [x]  [JGRP000029]java.net.ConnectException: Connection refused during che-server update on OpenShift  https://github.com/eclipse/che/issues/15176
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 14d |
| Max Shaposhnik | 14d | 
| Sergii Leshchenko | 14d | 
| Michal Vala | 14d | 
| Lukas Krejci | 14d |
| Total | 70 human*day | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 45 | 29|
