### ISSUE TITLE
Add the vscode-quarkus extension to Che

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15118]
### Describe the bug

While trying[ vscode-quarkus](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus) extension in Che-Theia I found multiple issues:

### Problems:
- [x] [Welcome page is empty](https://github.com/eclipse/che/issues/15113)
- [ ] [Can't debug Quarkus application](https://github.com/eclipse/che/issues/15114)
  - [ ] https://github.com/eclipse-theia/theia/issues/6534
  - [x] https://github.com/eclipse-theia/theia/issues/6567
  - [x] https://github.com/eclipse-theia/theia/pull/6533
- [x] [Can't add Quarkus extension to the project](https://github.com/eclipse/che/issues/15116)
- [x] [quarkus:dev task was generated incorrectly](https://github.com/eclipse/che/issues/15117)
- [x] [tasks.json file is overridden by quarkus extension](https://github.com/eclipse/che/issues/15523)

<details><summary>Che remote plugin with vscode-quarkus extension</summary><p> 

```yaml
apiVersion: v2
publisher: redhat
name: quarkus
version: 1.1.1
type: VS Code extension
displayName: Quarkus Tools
title: Quarkus Tools by Red Hat
description: This plug-in provides support for Quarkus development via a Quarkus language server and a Quarkus jdt.ls extension.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-quarkus
category: Language
firstPublicationDate: "2019-11-05"
spec:
  containers:
    - image: "docker.io/eclipse/che-remote-plugin-runner-java11:next"
      name: vscode-quarkus
      memoryLimit: "1500Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
    - https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/vscode-quarkus-1.1.1-158.vsix

```

**Comment by svor** [comment]
This issue need to be fixed to resolve https://github.com/eclipse/che/issues/14506 and https://github.com/eclipse/che/issues/15085

**Comment by benoitf** [comment]
setting milestone 7.5.0 as it's your sprint @tsmaeder

**Comment by tsmaeder** [comment]
We need a solution for how to mix and match jdt.ls extensions in the same container before we can merge this.

**Comment by tsmaeder** [comment]
Quarkus extension has been merged
