### ISSUE TITLE
Backport Che 6 documentation bits that are still relevant

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#15217]
Che 6 documentation has been unpublished (#14971).

Now it's time to backport the parts that are still relevant to Che 7.

Please help identify the documentation from  Che 6 that is still relevant to Che 7:

- [x] Document support of the private registries #15209
- [x] Stop Workspace settings documentation #15074
- [x] [docs] Cannot find Che configuration options #15191
- [x] PVCs strategy in Che 7 docs are not up to date #14654 -- PR [#901](https://github.com/eclipse/che-docs/pull/901)

**Comment by ibuziuk** [comment]
@rkratky will it be possible to prioritize this work?

**Comment by themr0c** [comment]
I see all issues listed here are closed. Closing this issue.
