### ISSUE TITLE
IDE2-2019-12-17 (Sprint: 176)

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#15241]
## Availability
Who | available | x0.6 
-- | -- | -- | 
@evidolob | 15 | 5 | 
@sunix  | 15 | 7 | 
@AndrienkoAleksandr  | 15 | 9 |
@vitaliy-guliy  | 15 | 9 |
@mmorhun  | 15 | 9 | 
@olexii4   | 15 | 9 | 
@akurinnoy   | 5 | 3 |
**Total** | **85** | **51** |

### Sprint Goals:
1. Che doc
2. Techical depts
3. Dogfooding
4. Firefox Support

## 1. Che doc
- [x] doc: update che7 doc referencing the old workspace definition #15237 6d
- [ ] Align development flow for vscode extensions #14228 4d
- [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins. #14119 5d

## 2. Techical depts
- [x] Move all Che Theia docker images from DockerHub to the quay.io #14849 10d
- [x] Workspace is not restarted after installing a plugin #15253 PR to merge

## 3. Dogfooding
Use Che Bot to provide factory link to PR in che-plugin-registry #15281
- [ ] Better visual feedback for panels  https://github.com/eclipse-theia/theia/issues/6605 10d

## 4. Firefox Support
- [ ] Make Che Theia webviews work in Che #15283 blocker/regression 8d
- [ ] Rework che-theia branding to provide logo icon for plugin webview #15324 regression 5d
- [ ] Minimal Firefox Support #14015
   - [x] bright fonts are not set on dark theme on Firefox #13442 4d

## Other  issues:
- [x] Unexpected filtering in plugins view in Che-Theia #14754 1d to finish
- [ ] Default-host - Some resources (css, js, images) in IDE does not work #14883 2d
- [ ] regression: my workspace view tooltip on Che commands is not showing up anymore #15260
- [x] Workspace fails to start/open. Caused by `Unknown error` during websocket connection establishing #14726 3d

Techical depts:
- [ ] Plugins should have ability to spawn processes #15087 
- [ ] Show a confirmation dialog when Ctrl+W is pressed in the terminal #13580
- [ ] Rename Che Theia Factory Plugin to Workspace Plugin #14653
- [ ] Terminal change title feature should be configurable #15242
- [ ] Refactoring: clean up che-machine-exec model #15243
- [ ] Remove legacy workspace config code from Che Theia #15249

## Pending PR

**Total planned = [todo]d**

## Next Issues
[Backlog](https://github.com/eclipse/che/issues/13280)

### Retrospective Comments
[Restrospective document](https://docs.google.com/drawings/d/1ZHZL7wR3WrklbhrP9kpdsVkJkMsbyB_oe9wIzUq1qGM/edit?usp=sharing)

**Comment by benoitf** [comment]
hi, no room for https://github.com/eclipse/che/issues/15109 ?
