### ISSUE TITLE
Languages Sprint 176

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15269]
Nov 27-Dec 18

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 3 | 2
@tolusha | 14 | 9 | 10
@vrubezhny | 13 | 8.5 | 8.5
@JPinkney | 14 | 9 | 9
@svor | 13 | 8.5 | 8.5

# Planned Issues
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic #13427 2d @tsmaeder 
- [ ] Simple LSP test suite for Java #14409 4d @JPinkney 
- [ ] Consume VS Code built-in extensions in Che-Theia #14759 2d @tolusha 
- [x] Add preLaunchTask into debug configuration for .Net samples #15025 0.5 @svor 
- [x] Update vert.x default sample  https://github.com/eclipse/che/issues/15314 1d @svor 
- [x] Don't use marketplace in node/node2 Che plugins. #15322 1d @svor 
- [ ] Support background tasks eclipse-theia/theia#6534 4d @svor 
- [x] Can't add Quarkus extension to the project https://github.com/eclipse/che/issues/15116 1d @svor 
- [ ] add 'References' widget https://github.com/eclipse/che/issues/14856 and https://github.com/eclipse-theia/theia/issues/4784 3d @vrubezhny 
- [ ] Add an information about cpp into Language support troubleshooting document #14943 0.5 (@tsmaeder )
- [x] Find a yarn-based example (https://github.com/eclipse/che/issues/14720) 2d @vrubezhny 
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d @vrubezhny 
- [ ] Variables View Loses Expansion State when Stepping https://github.com/eclipse-theia/theia/issues/6580 5d @tolusha 
- [x] Importing spring/pet-clinic in the default java-maven stack does not behave properly #13926 1d @svor 
- [ ] Get https://github.com/eclipse-theia/theia/pull/5774 merged (Debugging PR by Anton Kosyakov) 2d @tolusha 
- [ ] Context dependent code completion https://github.com/redhat-developer/yaml-language-server/issues/206 1d
- [ ] Server-side snippet support https://github.com/redhat-developer/yaml-language-server/issues/205 1d
- [ ] Investigate Native-Compiling jdt.ls #13835 (2d timebox)  @JPinkney 

# To be planned

# From Last Sprint

# Open Pull Requests
- [ ] No error message if vscode.open command is invoked with reso… https://github.com/eclipse-theia/theia/pull/6568
- [x] Fix `Task.execution` instantiation eclipse-theia/theia#6533 @tolusha  1d
- [ ] Refactor services parts of plugin-ext to use DI https://github.com/eclipse-theia/theia/pull/6358 @JPinkney 1d (check against che-theia)
- [x] Upgrade Go version to support realworld sample https://github.com/eclipse/che/issues/13803 @tolusha 0.5
    - [x] https://github.com/eclipse/che-devfile-registry/pull/96

# Blocked issues 

# Unplanned Issues
- [ ] Can't debug Quarkus application https://github.com/eclipse/che/issues/15114

CRW issues: 
- [ ] [Airgap] maven could not calculate build plan - settings.xml not used https://github.com/eclipse/che/issues/14857
- [ ] Java Language Server fails in 'Restricted Environment' to download Gradle https://issues.jboss.org/browse/CRW-330

Previous Sprint: https://github.com/eclipse/che/issues/15049
