### ISSUE TITLE
IDE2 - Documentation tasks

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15268]
Tracking Red Hat Che-IDE2 documentation related tasks

- [x] doc: update che7 doc referencing the old workspace definition https://github.com/eclipse/che/issues/15237 (duplicate ? https://github.com/eclipse/che/issues/15249)
- [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins. https://github.com/eclipse/che/issues/14119
- [x] Improve che docs devfile section https://github.com/eclipse/che/issues/13848
- [ ] Document che-theia preferences system #15362
