### ISSUE TITLE
IDE-2019-12-17 (Sprint: 176)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#15278]
### Sprint goals

1. VS Code plugins
2. UX Improvement 
3. Technical debts
4. Bugs

### Sprint details:

1. VS Code plugins
- [x] Upgrade OpenShift Che plugin with the extension v.1.0.2 #15226
- [ ] Upgrade Kubernetes Che plugin with Helm 3 support #15190
- [ ] [k8s plugin] buildah push command doesn't work #15035
- [ ] Improve kubeconfig injection with chectl  #14877
- [ ] Openshift connector and Che: openshift user should be logged automatically with the Openshift user. #15261
- [x] Locate kubernetes tasks under corresponding containers #15042

2. UX Improvement 
- [ ] Mark in the task widget title when task is exited. https://github.com/eclipse/che/issues/14132
- [x] Improve UX during ${current.project.path} macros usage #13636
- [ ] Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side. #15277
- [ ] Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270

3. Technical debts
- [x] Theia Editor Key Bindings switching (~~Default~~, VI, ~~Emacs~~)- VI  #9244
- [ ] Move Che release job from Codenvy CI to the CentOS CI #15294

4. Bugs
- [x] Che tasks are not available for running after page refreshing #15332

- [ ] [che-operator] - enable support git clone for repositories with self-signed SSL certs #15285

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |    
| Roman  |14 | 
| Vitalii  |14|    
| Igor |14 |

**Comment by slemeur** [comment]
Thanks @vparfonov 👍 

On the VSCode OpenShift and K8S plugin, I'd prefer that we prioritize more bugs and UX issues. There is this epic that has been created which list a certain set of tasks:
https://github.com/eclipse/che/issues/14900
It would be nice if you could take the epic and start decomposing all the sub-tasks. (including the one you are currently working on).
This way, we'll have a main epic which will regroup all the enhancement, new features and bugs. And we can prioritize the list and look at doing milestones.

Also please note some bugs that have been reported:
- https://github.com/eclipse/che/issues/15261
- https://github.com/eclipse/che/issues/15273
- https://github.com/eclipse/che/issues/15270
- https://github.com/eclipse/che/issues/15271

**Comment by vparfonov** [comment]
> Thanks @vparfonov 👍
> 
> On the VSCode OpenShift and K8S plugin, I'd prefer that we prioritize more bugs and UX issues. There is this epic that has been created which list a certain set of tasks:
> #14900
> It would be nice if you could take the epic and start decomposing all the sub-tasks. (including the one you are currently working on).
> This way, we'll have a main epic which will regroup all the enhancement, new features and bugs. And we can prioritize the list and look at doing milestones.
> 
> Also please note some bugs that have been reported:
> 
> * #15261
> * #15273
> * #15270
> * #15271

Thanks, for review we will take a look on those issues

**Comment by azatsarynnyy** [comment]
one more https://github.com/eclipse/che/issues/15262
