### ISSUE TITLE
Use plug-ins of extension packs for all default stacks

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15272]
### Description
When using VS Code (or VS Code online) and when I'm working on a Java project the default java pack is proposed https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

It includes vscode-java and the debugger but also a lot of other tools like the java test runner, dependency viewer, maven scaffolding, etc.

This is also true for different technologies
https://marketplace.visualstudio.com/search?target=VSCode&category=Extension%20Packs&sortBy=Installs

There are PHP pack, Python pack, TypeScript, etc.

But in Che, there is mostly only the LSP/Debug extension provided while tons of tools are de-factory really important when working on a project.

### Describe the solution you'd like
I would like to have the same default plug-ins/packs provided when using Che and working for a given technology.

Java Devfile example --> Java Extension Pack being selected.
PHP Devfile example --> PHP Extension pack being selected.
etc.

### dependency tasks:
- [ ] https://github.com/eclipse/che/issues/15373: Merge VS Code Extensions in a single container if they're using the same container definition
- [ ] https://github.com/eclipse/che/issues/15376: [meta.yaml / Che plug-ins]: Add dependencies section
- [ ] https://github.com/eclipse/che/issues/15377 : Add type “Che plugin pack” in plug-in broker

### Check plug-ins are working tasks:
- [ ] https://github.com/eclipse/che/issues/15390: Check VS Code extension pack extensions

**Comment by tsmaeder** [comment]
This is a good idea, but we don't have the notion of "extension packs" for Che plugins. This needs some technical thought.
Also, this sounds largish; should it be included in the roadmap? https://github.com/eclipse/che/wiki/Roadmap

**Comment by benoitf** [comment]
AFAIK it's largish as it's an epic

**Comment by tsmaeder** [comment]
Since the implementation of this is unclear, not sure which team to assign this to. @benoitf  @l0rd  this needs some discussion first.

**Comment by tsmaeder** [comment]
Removed from language backlog, not clear this falls into our responsibilities.

**Comment by benoitf** [comment]
@tsmaeder it's your responsability

It's only about adding more default plug-ins for default stack languages.

**Comment by tsmaeder** [comment]
@benoitf that's not what the title says.

**Comment by benoitf** [comment]
In Eclipse Che, right now if I select Java, java-debug vsix is also brought.
So ChePlugin can bring more than one vsix at a time (which is what an extension pack is doing)

so I could have a ChePlugin with the exact same list of vsix (minor the one that are not free) for a given language

so it's just a matter of bringing more plug-ins to have same experience than on VS Code or Vs Code Online

**Comment by tsmaeder** [comment]
@benoitf no, if I have two extension packs (let's say "Quarkus" and "Spring Boot"), I'll end up with multiple copies of jdt.ls. So this is not simply a matter of adding more VS Code extensions to the Che plugins. If the user installs two of them, stuff is going to break. Having a "extension pack" mechanism is much more involved and is unlikely to even involve the "languages" team.

**Comment by benoitf** [comment]
@tsmaeder if you don't provide extension as separate plug-in it doesn't reproduce your problem.
And AFAIK quarkus is not included in the Java extension pack

**Comment by benoitf** [comment]
I think we should separate issue
This issue/epic is about having one plug-in that is enabling multiple plug-ins at a time (same container)

Not trying to solve the issue about enabling 4 different plug-ins and make them work with the same container or by sharing a common folder for jdt.ls

Or not trying to solve plug-in collision.

Just to have same default tools than VS Code online that enable by default the extension pack for projects. (so need to be sure that these extensions are working well)

**Comment by benoitf** [comment]
I will create specific issues for Languages Team ans list them in  the epic
