### ISSUE TITLE
Platform-2019-12-17 (Sprint: 176)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15341]
### New Task && Enhancements

- [x] Support workspace namespace configuration in che-operator | https://github.com/eclipse/che/issues/15300 | 8
- [x] Support for Environment Variables in Plugins and Editors | https://github.com/eclipse/che/issues/14343 | 5

### Finalize issues started in the previous sprint.

- [x] che factory: should be able to override the name, source.repo, source.branch of the workspace that will be created in the url | https://github.com/eclipse/che/issues/13617 | 5
- [x] Finish up the namespace-selection MVP | https://github.com/eclipse/che/issues/15129 | 5
- [x] [che-operator] - enable che-server monitoring endpoint | https://github.com/eclipse/che/issues/15210 | 5

### Bugs and technical debt

- [x] Document possible issues with unrecoverable events on OpenShift < 4.2 | https://github.com/eclipse/che/issues/15307 | 3
- [x] Misleading message form CHE server when a container stopped | https://github.com/eclipse/che/issues/14781 | 8

### Unplanned
- [ ] [POC] Allow to have multiple endpoints with the same port and protocol for CheEditor  https://github.com/eclipse/che/issues/15410
- [ ] Multiple threads blocked in org.jgroups.protocols.Locking$ClientLock.lock(Locking.java:970)  https://github.com/eclipse/che/issues/15231

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 14d |
| Max Shaposhnik | 14d | 
| Sergii Leshchenko | 7d | 
| Michal Vala | 14d | 
| Lukas Krejci | 14d |
| Total | 63 human*day | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 39 | 39|
