### ISSUE TITLE
Support OpenShift 4.2 Airgap mode (use image digests)

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15350]
### Is your enhancement related to a problem? Please describe.

In order to leverage [OpenShift Airgap mode that is available since 4.2 ](https://blog.openshift.com/openshift-4-2-disconnected-install/)there are some rule that we should follow in the Operator design/behavior. In particular all images should be referred using their digest rather then a tag.

### Describe the solution you'd like

There are a few documents with the recommendations:

- [Disconnected Installation for Operators - Google Docs](https://docs.google.com/document/d/1n4MJgVk8g254s_X6oOgzC1z44RcJur3g2WaMuriv1fg/edit)
- [Your Operator and Disconnected Clusters - Google Docs](https://docs.google.com/document/d/1P4vsuf_yQ8Pl0Fpd1ZQMbHEL2bvtS92hhX1bcEqpdLo/edit?ts=5dc0296a#heading=h.t9cx09pqnm7r)
- [Red Hat Operators - Productization Docs - Part 1 - Google Docs](https://docs.google.com/document/d/12BPNG4I3TCh-hBWLXeiIUQ5e4CmnwJijJEkSXrzL9eg/edit#)
- [Red Hat Operators - Productization Docs - Part 2 - Google Docs](https://docs.google.com/document/d/18XWDIOzEoU2upZqHwMX7cQPfdaZxalz-xzwKYBK1J7Q/edit#heading=h.l0o1gan3vw34)

- [x] [che-operator] Set up image digest on released version of CSV https://github.com/eclipse/che/issues/16228
- [x] Specify and use OLM relatedImages in the operator https://github.com/eclipse/che/issues/14993
- [x] Could we use RELATED_IMAGES_* env vars in registries and operator metadata CSV? https://github.com/eclipse/che/issues/16815

**Comment by nickboldt** [comment]
Slipping to 7.10 as something to prioritize for the quarter after CRW 2.1 is done. cc: @davidfestal @l0rd

**Comment by nickboldt** [comment]
Given no news, assuming slipped to 7.13.

**Comment by nickboldt** [comment]
Not done in 7.14, and won't be done in 7.15 (sprint ends in 2 days) so punting to backlog.
