### ISSUE TITLE
Activity tracker doesn't work for firefox.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#15354]
### Describe the bug
I did acitve development on the firefox, but my workspace was shutdown by activity tracker.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Do work  in the Che workspace  using Filrefox during 1 hour(Or configure Che with less timeout `CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT=3600`).

### Expected behavior
Workspace should alive if user is really active.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
```
2019-11-28 10:01:29,435[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 835]   - Workspace 'admin:che-theia-all' with id 'workspaces7co4xlt42bh4ref' started by user 'admin'
2019-11-28 10:32:03,952[ted-scheduler-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 493]   - Workspace 'admin/che-theia-all' with id 'workspaces7co4xlt42bh4ref' is stopping by user 'activity-checker'
2019-11-28 10:32:08,655[aceSharedPool-3]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 900]   - Workspace 'admin/che-theia-all' with id 'workspaces7co4xlt42bh4ref' is stopped by user 'activity-checker'
2019-11-28 10:32:24,825[nio-8080-exec-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 432]   - Starting workspace 'admin/che-theia-all' with id 'workspaces7co4xlt42bh4ref' by user 'admin'
2019-11-28 10:33:04,139[aceSharedPool-4]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 835]   - Workspace 'admin:che-theia-all' with id 'workspaces7co4xlt42bh4ref' started by user 'admin'
2019-11-28 11:04:04,380[ted-scheduler-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 493]   - Workspace 'admin/che-theia-all' with id 'workspaces7co4xlt42bh4ref' is stopping by user 'activity-checker'
2019-11-28 11:04:06,964[aceSharedPool-5]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 900]   - Workspace 'admin/che-theia-all' with id 'workspaces7co4xlt42bh4ref' is stopped by user 'activity-checker'
```

**Comment by AndrienkoAleksandr** [comment]
P.S. also I used ca with https... So maybe an issue with this staff...

**Comment by skabashnyuk** [comment]
@AndrienkoAleksandr do you see any errors in browser console?

**Comment by AndrienkoAleksandr** [comment]
Issue reproduces with https connection for Che

**Comment by AndrienkoAleksandr** [comment]
> @AndrienkoAleksandr do you see any errors in browser console?

No errors in the browser console. But it should not be, che-theia activity tracker works on the backend to prevent CORS.

**Comment by vzhukovskii** [comment]
Closed, because issue can't be reproduced. If the problem still exists, reopen the issue.
