### ISSUE TITLE
Release 7.5.1

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15372]
### Issues / commits for backporting to 7.5.1
- [x] PVC is not cleaned up when workspace is deleted #15363 (PR #15375)
- [x] Multiple threads blocked in org.jgroups.protocols.Locking$ClientLock.lock(Locking.java:970) #15231 (jgroups update to 4.1.2) (PR https://github.com/eclipse/che-parent/pull/142)
- [x] NullPointerException with factory https://github.com/eclipse/che/issues/15337 (PR https://github.com/eclipse/che/pull/15379)

### Release status
- [x] che-theia @evidolob `eclipse/che-theia:7.5.1`
- [x] che-machine-exec @ibuziuk `quay.io/eclipse/che-machine-exec:7.5.1`
  - [x] https://github.com/eclipse/che-machine-exec/pull/61
- [x] che-plugin-registry @ibuziuk `quay.io/eclipse/che-plugin-registry:7.5.1`
   - [x] https://github.com/eclipse/che-plugin-registry/pull/307
   - [x] Adding `7.5.1` versions of che-theia & machine-exec to master -  https://github.com/eclipse/che-plugin-registry/pull/308
- [x] che-devfile-registry @ibuziuk `quay.io/eclipse/che-devfile-registry:7.5.1`
   - [x] https://github.com/eclipse/che-devfile-registry/pull/154
- [x] che @vparfonov 
   - [x] che-parent
   - [x] ~~che-docs~~ - no changes so don't release it  
   - [x] che 
- [x] che-operator @davidfestal 
   - [x] PRs for the community operators
      - [https://github.com/operator-framework/community-operators/pull/990]  
      - [https://github.com/operator-framework/community-operators/pull/991]
- [ ] chectl @l0rd

**Comment by evidolob** [comment]
@ibuziuk Do we need some commits for `che-theia:7.5.1` ? Or I can just respin `che-theia:7.5.0` with `7.5.1` version?

**Comment by ibuziuk** [comment]
@evidolob I think nothing is expected to be backported from che-theia side. @skabashnyuk wdyt?

**Comment by l0rd** [comment]
@ibuziuk @davidfestal why haven't we releasing the operator?

**Comment by dmytro-ndp** [comment]
There is image quay.io/eclipse/che-operator:7.5.1 available https://quay.io/repository/eclipse/che-operator?tab=tags

But there is no 7.5.1 tag https://github.com/eclipse/che-operator/tags

**Comment by davidfestal** [comment]
My bad. I started the release next week, and for various reasons stopped it... and delayed it until now due to other high-priority tasks. Sorry about that. I'll finish it today.

**Comment by davidfestal** [comment]
I just finished the last steps of the operator release.
Submitted the 2 PR to the `community-operators` GH repo:
- For upstream Kubernetes: https://github.com/operator-framework/community-operators/pull/990
- For OpenShift: https://github.com/operator-framework/community-operators/pull/991

**Comment by ibuziuk** [comment]
@l0rd is it planned to release 7.5.1 of chectl ?

**Comment by l0rd** [comment]
@ibuziuk sorry I had not seen the notification and didn't figure out that the operator has been actually released last week. Considered that we should release 7.6.0 tomorrow I don't think it's worth releasing 7.5.1 of chectl.

**Comment by ibuziuk** [comment]
Closing
