### ISSUE TITLE
Cloud Shell Che Workspace

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15434]
This epic is about the technical work needed to implement a cloud shell component that would be used on OpenShift Console:

![image](https://user-images.githubusercontent.com/606959/70440704-100ca400-1a93-11ea-9a29-3af92d321d12.png)

## Using the DevWorkspace CRD

The cloud shell should use the DevWorkspace CRD that is described in #15425 

![image](https://user-images.githubusercontent.com/606959/70440877-7a254900-1a93-11ea-96c9-3b2c61e6f5a0.png)

## Using a new CheEditor

A Theia based Che workspace is a waste of compute resources if used only to get a terminal. And it takes way too long to bootstrap. So the idea is to implement an alternative `cheEditor` and a cloud shell workspace could be defined using the following devfile:

```yaml
 ---
apiVersion: 1.0.0
components:
- type: cheEditor
  id: redhat/cloud-shell/latest
- type: dockerimage
 image: quay.io/eclipse/openshift-tooling:latest
```

## Other considerations

- Exec denial: exec into the pod should be denied for any user other than the owner 
- Auth: The terminal service should be secured using OpenShift OAuth and RBAC
- Autoscale to zero: After a few minute of inactivity cloud shell pods should be deleted

### Subtasks

- [x] Implementation of the cloud shell editor (deploy team)
  - [x] Find out how we can avoid to have `machine-exec` automatically added to a workspace
  - [x] Build a new image based on the current machine-exec image that serves the static content needed for the terminal widget (HTML + JS scripts)
  - [x] Implement a mechanism that, if there is just one container in the workspace, automatically select it as the machine exec target (no need to communicate with wsmaster)
- [ ] Submit an [OpenShift enhancement PR](https://github.com/openshift/enhancements/pull/182):
  - [ ] Implement an exec denial mechanism PoC and document it
  - [ ] Review the auth mechanism: investigate [kube-rbac-proxy](https://github.com/openshift/kube-rbac-proxy) and [oauth-proxy](https://github.com/openshift/oauth-proxy ), compare it to jwt proxy and document it
  - [ ] Describe the CloudShell Lifecycle including the autoscale to zero mechanism
- [ ] Plan the DevWorkspace work to start with the features needed for the CloudShell implementation
- [x] Adapt [DevWorkspace Controller POC](https://github.com/che-incubator/che-workspace-crd-operator) to satisfy Cloud Shell needs:
  - [x] Introduce Admission Webhook that would allow forbidding using CloudShell by no-creator https://github.com/eclipse/che/issues/16056
  - [x] Revise DevWorkspace CR structure https://github.com/eclipse/che/issues/15783
  - [x] Rework WorkspaceRouting to run container inside workspace pod https://github.com/eclipse/che/issues/15786
  - [x] Make DevWorkspace CR prerequisites(PVC, CheRestAPI) optional https://github.com/eclipse/che/issues/15790
  - [x] CloudShell should provide an option to use users token instead of SA's one https://github.com/eclipse/che/issues/16250
  - [x] Cloud shell must propagate error when it failed to initialize terminal https://github.com/eclipse/che/issues/16249
   - [x] Make workspace controller generating TLS certs for its webhook server https://github.com/eclipse/che/issues/16251
  - [x] Deny to access CloudShell to everybody except creator https://github.com/eclipse/che/issues/16252
  - [x]  Investigate the alternative for plugin-registry for CloudShell run with controller https://github.com/eclipse/che/issues/16313
  - [x] Finalize Workspace Reconcile loop rework https://github.com/eclipse/che/issues/16494
  - [x] ~~Investigate authentication/authorization for CloudShell https://github.com/eclipse/che/issues/15782~~
  - [x] Make workspace operator reuse devworkspace-api https://github.com/eclipse/che/issues/16626
  - [x] Configure OpenShift OAuth to get for cloud-shell user:full rights https://github.com/eclipse/che/issues/16515
  - [x] Initialize kubeconfig with user's token if useBearerToken is configured https://github.com/eclipse/che/issues/16576
  - [ ] Set up OLM installation for WorkspaceOperator https://github.com/eclipse/che/issues/16311
  - [x] MutatingWebhooks are not compatible with 4.5.0-0.ci-x https://github.com/eclipse/che/issues/16587
  - [x] OpenShift OAuth proxy seems to break OpenShift OAuth on the cluster https://github.com/eclipse/che/issues/16553
  - [x] Investigate if OpenShift Console Proxy could be used to avoid user's reauthentication https://github.com/eclipse/che/issues/16633

### Timeline

**2020-03-31 (Che v7.11.0)**
- [ ] Test the proposals for [the open questions in the Cloud Shell OpenShift Enhancement PR](https://github.com/openshift/enhancements/blob/d5c28ebede8257a4c83c927924fae5609c0e9fab/enhancements/openshift-console-cloud-shell.md#open-questions-optional) and prove that they work as expected.

**2020-04-20 (Che v7.12.0)**
- [ ] Solve the problem with the OpenShift OAuth Proxy: how can we avoid to re-authenticate users? Is it possible to use the existing Console Proxy? And avoid the creation of a route per cloud shell?
- [ ] Release the first version of the [che-workspace-operator](https://github.com/che-incubator/che-workspace-operator) based on the [devworkspace-api](https://github.com/che-incubator/devworkspace-api) (there is no need to publish to the Operator Hub yet) and that includes the solution proved to work in the previous iteration.

**2020-05-12 (Che v7.13.0)**
- [ ] Implement the scale-to-zero after a period of inactivity https://github.com/eclipse/che/issues/16683
- [ ] Implement a CloudShell "happy path" e2e test that deploys the operator, creates a cloud-shell devworkspace, inject the user token, use kubectl (or oc) and is scaled to zero after a period of inactivity https://github.com/eclipse/che/issues/16667
- [OPTIONAL] Implement a PoC to include a cloudShell in the dashboard

**2020-06-02 (Che v7.13.0)**
- [ ] Include the build of the [che-workspace-operator](https://github.com/che-incubator/che-workspace-operator) and [devworkspace-api](https://github.com/che-incubator/devworkspace-api) in the CRW build
- [ ] Publish the cloud shell operator on the Operator Hub
- [ ] Include the CloudShell e2e happy path test in the QE team CRW release validation check #16667
- [ ] [OPTIONAL] Add a che property to switch using the DevWorkspace API instead of the Kubernetes infrastructure to create Devfile based Che workspaces. That will allow to start testing the creation of DevWorkspaces using the Che dashboard and other wsmaster clients.

**2020-06-18**
- [ ] OpenShift 4.5 is release with CloudShell support based on DevWorkspace operator.

**Comment by ibuziuk** [comment]
@l0rd according to the description this is an epic, but I'm not sure which team label should be applied

**Comment by davidwindell** [comment]
It would be awesome to be able to do this from the Che dashboard too - so one could quickly make a change to a project without booting the whole IDE up.

**Comment by sleshchenko** [comment]
I believe that the functionality described in that epic is already implemented.
There are only some fixes are done before release and it's needed to productize WebTerminal but there is another epic to track release related tasks and dependencies https://github.com/eclipse/che/issues/17084

I'm closing it let me know if you think it makes sense to keep it open
