### ISSUE TITLE
Langugages Sprint 177

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15478]
Dec 18 - Jan 8

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 3 | 2 |  2
@sunix | 9 | 5.5 | 6
@vrubezhny | 5 | 3.5 | 3.5
@JPinkney | 7 | 4 | 6
@svor | 9 | 5.5 | 7

# Planned Issues
- [ ] Can't debug Quarkus application https://github.com/eclipse/che/issues/15114 4d timebox for investigation of Step 1 @sunix 
- [x] tasks.json file is overridden by quarkus extension #15523 2d @svor 
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic #13427 2d @tsmaeder 
- [ ] Add an information about cpp into Language support troubleshooting document #14943 0.5 (@tsmaeder )
- [x] Add the vscode-quarkus extension to Che #15118 2d @svor
- [ ] Simple LSP test suite for Java #14409 3d @JPinkney 
  - [ ] Propose a PR to che-theia
  - [ ] Document how to write tests
  - [ ] Propose an example workspace with simple, but reasonable Java tests
- [ ] add 'References' widget https://github.com/eclipse/che/issues/14856 and https://github.com/eclipse-theia/theia/issues/4784 3.5d @vrubezhny 
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d 
- [ ] Use a maven sample for the maven stack #15216
- [ ] CallHierarchyService Plugin API https://github.com/eclipse-theia/theia/issues/3765 
- [ ] Investigate Native-Compiling jdt.ls #13835 (2d timebox)  @JPinkney 
- [ ] Plug-ins leaking CodeLens, etc. https://github.com/eclipse-theia/theia/issues/4472
- [ ] Preview is not shown in default project for Python Django stack #15053

try out an document the manual setup of air-gapping for our various built systems, in particular:
- [ ]  npm (assuming all relevant build systems use npm for package mgmt) https://github.com/eclipse/che/issues/15501 3d @JPinkney 
- [ ]  maven #15503 2d @sunix
- [ ] gradle #15510
- [ ] nuget #15511 3d @svor (stretch goal)
- [ ] go packages #15512

# To be planned

# From Last Sprint

# Open Pull Requests
- [ ] No error message if vscode.open command is invoked with reso… https://github.com/eclipse-theia/theia/pull/6568
- [ ] Refactor services parts of plugin-ext to use DI https://github.com/eclipse-theia/theia/pull/6358 @JPinkney 1d (check against che-theia)
- [ ] Consume VS Code built-in extensions in Che-Theia #14759 2d @tolusha 

# Blocked issues 

# Unplanned Issues
- [ ] Context dependent code completion https://github.com/redhat-developer/yaml-language-server/issues/206 1d
- [ ] Server-side snippet support https://github.com/redhat-developer/yaml-language-server/issues/205 1d
- [ ] Support background tasks eclipse-theia/theia#6534  being addressed by https://github.com/ShimonBenYair
- [ ] Sometimes It is necessary to have same HOME for plugin and dev containers #14938

CRW issues: 

Previous Sprint: https://github.com/eclipse/che/issues/15269

**Comment by tsmaeder** [comment]
Work on https://github.com/eclipse/che/issues/15351

**Comment by tsmaeder** [comment]
https://github.com/eclipse-theia/theia/issues/5710
