### ISSUE TITLE
Improve plugin brokers

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15471]
### Is your task related to a problem? Please describe.
The plugin broker refactor (issue https://github.com/eclipse/che/issues/14494, PR https://github.com/eclipse/che-plugin-broker/pull/80) restructures the plugin brokers so that additional improvements can be made. This epic collects the various follow up tasks.

### Subtasks
General:
- [ ] Improve brokers data flow: https://github.com/eclipse/che/issues/15479

Artifacts broker:
- [x] Only download plugin extensions when necessary: https://github.com/eclipse/che/issues/15470

Metadata broker:
- [x] Investigate possibility of converting broker into a service or including it in workspace CRD as library: https://github.com/eclipse/che/issues/15656
