### ISSUE TITLE
QE-2020-01-07 (Sprint: 177)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#15492]
### Sprint goals
- [ ] Increase coverage of Che functionality with E2E tests
 
### Unplanned 
- [x] [Happy Path] Check application readiness before opening the link by the "DialogWindow.waitDialogAndOpenLink" method #15551 1sp
- [x] [TS_SELENIUM] Workaround problem with lose focus during invoking suggestion container inside of the editor #15579 1sp
- [x] [TS_SELENIUM] Update methods for waiting application readiness inside of workspace #15595 1sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 5 |
| Total |  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |

### Reference
