### ISSUE TITLE
Release 7.3.4

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#15502]
## Issues / commits for backporting to 7.3.4
 - [ ] Multiple threads blocked in org.jgroups.protocols.Locking$ClientLock.lock(Locking.java:970) #15231
 - [ ]  Support git clone for repos with self-signed SSL certs https://github.com/eclipse/che/issues/14527
 - [ ] [che-operator] - enable support git clone for repositories with self-signed SSL certs https://github.com/eclipse/che/issues/15285

### Release status
- [ ] che-theia 
- [ ] che-machine-exec 
- [ ] che-plugin-registry `quay.io/eclipse/che-plugin-registry:7.3.4`
   - [ ] 
   - [ ] Adding `7.3.4` versions of che-theia & machine-exec to master 
- [ ] che-devfile-registry `quay.io/eclipse/che-devfile-registry:7.3.4`
   - [ ] 
- [ ] che 
   - [ ] che-parent
   - [ ] che-docs 
   - [ ] che 
- [ ] che-operator 
   - [ ] PRs for the community operators
      - [ ]  
      - [ ]
- [ ] chectl

**Comment by vparfonov** [comment]
@l0rd What due date for this release? I ask because #15285 not ready at the moment

**Comment by l0rd** [comment]
That's should be the base for CRW 2.0.2 that is planned for January 2020
cc @nickboldt

**Comment by dmytro-ndp** [comment]
сс @slemeur

**Comment by nickboldt** [comment]
Downstream: https://issues.redhat.com/browse/CRW-575

**Comment by nickboldt** [comment]
Can we make sure this is released no later than Jan 8?

**Comment by ibuziuk** [comment]
@l0rd @nickboldt can we close that one? I do not think `7.3.4` is going to happen

**Comment by nickboldt** [comment]
Sure - let's close it for now. Can reopen if suddenly need a 2.0.2 release downstream.
