### ISSUE TITLE
Che Deploy Sprint 177

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15515]
Dec 18 - Jan 7

### Goals
- [ ] Familiarization with codebase / TLS
- [ ] POC: TSL by default
- [ ] Collect logs during installation of Eclipse Che

### Availability
| Name  | Availablility |
| ------------- | ------------- |
| Anatolii   | 11d  |
| Mykola   | 11d  |
| Aleksandr  | 11d  |

### Issues
- [ ] [POC] TLS by default  https://github.com/eclipse/che/issues/15313
- [x] Collect logs during installation of Eclipse Che https://github.com/eclipse/che/issues/15485
- [ ] Manage versioning of the `CheCluster` CRD https://github.com/eclipse/che/issues/15389
- [ ] Extra option --PersistentVolumeName and --HostPathSource to CheCTL https://github.com/eclipse/che/issues/15157
- [ ] [che-operator] - serviceaccount permissions for <username>-che as default namespace https://github.com/eclipse/che/issues/15493

### Unplanned
- [x] `chectl workspace:start` command stuck https://github.com/eclipse/che/issues/15578
- [x] Can not start a workspace https://github.com/eclipse/che/issues/15602
- [ ] Fix shell detection when shell is empty value https://github.com/eclipse/che-machine-exec/pull/70
- [ ] Change che-machine-exec according to fast cloud-shell integration(server part) https://github.com/eclipse/che-machine-exec/pull/63

[Planned](https://github.com/eclipse/che/issues?q=is%3Aopen+is%3Aissue+label%3Ateam%2Fdeploy+label%3Asprint%2Fcurrent-sprint) | [In progress](https://github.com/eclipse/che/issues?q=is%3Aopen+is%3Aissue+label%3Ateam%2Fdeploy+label%3Asprint%2Fcurrent-sprint+label%3Astatus%2Fin-progress) | [Done](https://github.com/eclipse/che/issues?q=is%3Aissue+label%3Ateam%2Fdeploy+label%3Asprint%2Fcurrent-sprint+is%3Aclosed) | [Blocker](https://github.com/eclipse/che/issues?q=is%3Aissue+label%3Ateam%2Fdeploy+label%3Aseverity%2Fblocker)
