### ISSUE TITLE
Che Plugins Sprint 177

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#15513]
## Sprint goals
1. Blockers
2. Details
3. Analysis
 
:new: **NEW IN THIS SPRINT** :new: 
- Sections are ranked in order of priority.
- Issues in each section are ranked in order of priority. Pick from the top.
- Blocker issues from the [backlog](https://github.com/eclipse/che/milestone/95) are tracked here as well, for now

### Blockers
* [ ] Improve login procedure for GitHub PullRequest Plugin #14217  

 ### Details
**1. Bugs**
* [x]  [che-operator] - enable support git clone for repositories with self-signed SSL certs #15285
* [ ] Align development flow for vscode extensions #14228
* [ ] Cannot generate VC Code extension using Yeoman Wizard #15443
* [x] regression: my workspace view tooltip on Che commands is not showing up anymore #15260

**2. UX Improvement**
* [ ]  Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side. #15277
* [ ]  Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270
* [x] Rename Che Theia Factory Plugin to Workspace Plugin #14653
* [ ] Terminal change title feature should be configurable #15242 

**3. VS Code plugins**
* [ ]  Upgrade Kubernetes Che plugin with Helm 3 support #15190
* [ ]  [k8s plugin] buildah push command doesn't work #15035 
* [ ]  Openshift connector and Che: openshift user should be logged automatically with the Openshift user. #15261 
* [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins #14119 

**4. Technical debts**
* [ ]  Move Che release job from Codenvy CI to the CentOS CI #15294
* [ ] Use Che Bot to provide factory link to PR in che-plugin-registry #15281 

 
 ## Analysis
 #### Availability
| Name  | Availablility |
| ------------- | ------------- |
| @vitaliy-guliy  | 11  |
| @vinokurig  | 11  |
| @ericwill | 5  |

**Comment by ericwill** [comment]
First of many! :+1: 

@l0rd I don't have permissions yet so it would be good if you could add the appropriate team label

@slemeur this is my first attempt, please let me know if priorities need adjustment or if I missed anything

**Comment by vitaliy-guliy** [comment]
@l0rd @slemeur could you give a look at the issues from the current IDE2 team sprint? https://github.com/eclipse/che/issues/15241 Just to check whether the labels for issues are set properly.

**Comment by vzhukovskii** [comment]
As for https://github.com/eclipse/che/issues/13636 there is a PR, which will be merged soon: https://github.com/eclipse/che-theia/pull/588

**Comment by ericwill** [comment]
Superseded by sprint 178, #15633
