### ISSUE TITLE
Rethink/rework the Che workspace with workspace-roots

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15529]
### Is your enhancement related to a problem? Please describe.

At the moment, a lot of vscode extensions are relying on workspace root to work properly, the ones I have identified:
- openshift-connector
- quarkus-extension
- Go extension 
- k8s extension

It means that we are getting through a lot bugs if we don't handle it properly. Basically, all these extensions are assuming that a project (maybe a subfolder of a git repo or not) is configured as a workspace root.

### Describe the solution you'd like
The goal of this issue is to rethink the way we handle projects and create sub issues to fix all theses problem:

- [ ] Workspace root should have its own folder icon (not seen as a normal folder). (minor)
- [x] Do not consider `/projects` as a workspace root unless if there is no project defined in the devfile. By default, all projects in the `projects` section of the devfile should be a workspace root. https://github.com/eclipse/che/issues/17212
- [ ] projects with `sparseCheckoutDirs` should have sparseCheckoutDirs as a workspace root folders https://github.com/eclipse/che/issues/19370
- [ ] Add ability to defined any subfolders of a git project as workspace roots. https://github.com/eclipse/che/issues/15347
- [x] Implement preferences from plugin meta.yaml that works with new workspace root definition https://github.com/eclipse/che/issues/17975#issuecomment-759481640
- [ ] Bi directional synchronization of workspace root definition with devfile https://github.com/eclipse/che/issues/19368

So we do not show anymore `/projects` as workspace root in the explorer. So, be careful not to break all the behaviors that are related to the current default workspace root `/projects`.

**Comment by tsmaeder** [comment]
@sunix number 3 would be addressed by Java LS "Classpath is incomplete" warning when loading petclinic #13427 (if I ever get to it).

**Comment by tsmaeder** [comment]
Number 4 would likely have to be configured in the devfile.

**Comment by sunix** [comment]
> Number 4 would likely have to be configured in the devfile. For doing it by hand, we would have to write special UI, I guess, since only subpaths would be allowed. Checkout would still always be to /projects, though.

Yes, i have a proposal in https://github.com/eclipse/che/issues/15347
you can also use the command `Add folder to workspace` to add a workspace root

**Comment by benoitf** [comment]
I've added languages as label but it might be as well editor or plug-ins

**Comment by svor** [comment]
A few words about Go extension which uses [gopls (language server for Go)](https://github.com/golang/tools/blob/master/gopls/README.md). If the project uses Go module, it requires you to open the project as your workspace root.  Some improvements should be done in the next v0.5.0 release: https://github.com/golang/go/milestone/138

**Comment by tsmaeder** [comment]
The behaviour for workspace roots is different depending on the workspace, project and language server. I believe we'll have to have some way to configure where to open a workspace root given a project structure. Also think about opening multiple projects inside a monorepo.

**Comment by sunix** [comment]
@tsmaeder the proposal for opening multiple projects inside a monorepo: https://github.com/eclipse/che/issues/15347

**Comment by amisevsk** [comment]
> A few words about Go extension which uses gopls (language server for Go). If the project uses Go module, it requires you to open the project as your workspace root.

The recently-added Scala plugin has the same limitation: https://github.com/eclipse/che-plugin-registry/pull/356

**Comment by azatsarynnyy** [comment]
multi-root mode is already present in Che-Theia
All further enhancements can be made within the separate issues

**Comment by sunix** [comment]
this was an umbrella issue, sub issues like https://github.com/eclipse/che/issues/15347 were not covered

**Comment by l0rd** [comment]
Closing as we are [sunsetting che-theia](https://github.com/eclipse/che/issues/21771)
