### ISSUE TITLE
Editors Sprint 177

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15531]
Dec 18 - Jan 7

### Goals
1. Transfer Che Theia release responsibility from IDE2 team
2. Fix blocker issues for plugin developers
3. Minimal Firefox Support
4. Theia upstream focus

#### Transfer release responsibility to Editors team
- [x] Make a release of Che Theia 7.6.0 https://github.com/eclipse/che/issues/15504

#### Blockers
- [x] Make Che Theia webviews work in Che https://github.com/eclipse/che/issues/15283

#### Minimal Firefox Support Epic https://github.com/eclipse/che/issues/14015
- [x] Activity tracker doesn't work for firefox https://github.com/eclipse/che/issues/15354
- [x] Cannot open command palette in Theia when using Firefox https://github.com/eclipse/che/issues/15145

#### Leftover from the previous sprint https://github.com/eclipse/che/issues/15278
- [ ] Mark in the task widget title when task is exited https://github.com/eclipse/che/issues/14132
- [x] Improve UX during ${current.project.path} macros usage https://github.com/eclipse/che/issues/13636. Need to get the PR https://github.com/eclipse/che-theia/pull/588 merged
- [x] Improve kubeconfig injection with chectl https://github.com/eclipse/che/issues/14877. Need to get the PR https://github.com/che-incubator/chectl/pull/430 merged

#### Theia upstream focus
- PRs review to check the possible impact on Che Theia:
  - https://github.com/eclipse-theia/theia/pull/6680
Created the corresponding issue https://github.com/eclipse/che/issues/15542 to adopt the introduced features in Che Theia
  - https://github.com/eclipse-theia/theia/pull/6780 
  - https://github.com/eclipse-theia/theia/pull/6811
Filed the follow-up issues: https://github.com/eclipse-theia/theia/issues/6821, https://github.com/eclipse-theia/theia/issues/6822
- created https://github.com/eclipse/che/issues/15540 to make Che Theia Tasks compatible with Theia multi-root workspaces

#### Unplanned
- [ ] Che Theia build failing with the latest stable yarn https://github.com/eclipse/che/issues/15552

### Availability
| Name  | Availability | x0.6
| -- | -- | --
| Artem | 10  | 6
| Roman   | 5  | 3
| Vlad   | 12  | 7
