### ISSUE TITLE
Move CI infrastructure to CentOS CI

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#15571]
Move CI infrastructure out of Codenvy to CentOS CI and use quay.io docker registry.

-  [x] Move all Che Theia docker images from DockerHub to the quay.io #14849
- [x] Create 'master', 'nightly', 'release' CI for 'che-machine-exec' plugin and move images to quay.io #14357
- [x] Move Che release job from Codenvy CI to the CentOS CI #15294
- [x] Create 'master', 'nightly', 'release' CI for plugin-broker and move images to quay.io #14378
- [x] Move nightly QE jobs from codenvy CI to Centos CI #15517
- [x] Move Che images form Docker Hub to the quay.io #15569
- [x] Move pre-release test jobs to ci.centos #15701
- [x] Move QE PR check jobs
- [x] Provide RELEASE.md files with the release instructions to all the related repositories #15506 
  - (nearly done, will target 7.9.0 release for completion)
- [x] Move che-theia build PR check to CentOS CI #16054

**Comment by gazarenkov** [comment]
@rhopp @musienko-maxim what's the status of #15517 ?
@artaleks9 what's the status of #15701 ?

**Comment by nickboldt** [comment]
https://github.com/eclipse/che/issues/15506 is nearly done: waiting on doc content from che/che-parent/che-docs release experts, then we can script that and verify it works for 7.9.0.

**Comment by artaleks9** [comment]
#15701
Moving releases jobs:
Java selenium:
     - Move Multiuser stable - in progress
     - Setup jobs to be triggered by push to some "qe" branch - in progress
     - Move Multiuser all - not started 
     - Move Hot update - not started

**Comment by musienko-maxim** [comment]
Moving nightly jobs:

Move Happy path job - done
Move Devfile tests- not started

Move jobs with Java selenium tests:
with Openshift OAuth - not started
Hot update - not started
Multiuser stable - in progress (on the finish line)
Multiuser all - in progress (problem with Github OAuth - changing slaves)

**Comment by SkorikSergey** [comment]
**Moving PR-checks jobs:**

- Move che-pullrequests-test-ocp job - in progress

**Comment by rhopp** [comment]
@musienko-maxim For `Multiuser all - in progress (problem with Github OAuth - changing slaves)` please disable the oauth tests for now and create issue for finding a solution to this. Thx!

**Comment by musienko-maxim** [comment]
@rhopp Thx we'll do it.

**Comment by rhopp** [comment]
We believe all the QE jobs have been migrated.
* Nightly jobs
* PR check jobs
* RC jobs

**Comment by rhopp** [comment]
We believe all the QE jobs have been migrated.
* Nightly jobs
* PR check jobs
* RC jobs

**Comment by rhopp** [comment]
Hi @azatsarynnyy 
As Florent pointed out, there is a PR check for building Che theia in eclipse/che-theia repo.
Can your team (as your team seems like the best fit for owner of this job) make sure this job is moved to CentOS CI? https://ci.codenvycorp.com/view/pr-builds/job/che-theia-pullrequests-build/

**Comment by azatsarynnyy** [comment]
> Can your team (as your team seems like the best fit for owner of this job) make sure this job is moved to CentOS CI?

Hi @rhopp 
Thanks for pointing this out.
Editors Team will work on it next sprint. I've added the issue to the subtasks https://github.com/eclipse/che/issues/16054

**Comment by azatsarynnyy** [comment]
We're done with che-theia build PR check

**Comment by benoitf** [comment]
should we close this issue ?

**Comment by gazarenkov** [comment]
Done
