### ISSUE TITLE
Che Deploy Sprint 178

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15615]
Jan 7 - Jan 28

### Goals
- [ ] Familiarization with codebase / TLS
- [ ] POC: TSL by default

### Availability
| Name  | Availablility |
| ------------- | ------------- |
| Anatolii   | 16d  |
| Mykola   |  11d  |
| Aleksandr  | 15d  |

### Issues
- [ ] [POC] TLS by default  https://github.com/eclipse/che/issues/15313
- [ ] Manage versioning of the `CheCluster` CRD https://github.com/eclipse/che/issues/15389
- [x] Extra option --PersistentVolumeName and --HostPathSource to CheCTL https://github.com/eclipse/che/issues/15157
   - [x] https://github.com/eclipse/che/pull/15677
   - [x] https://github.com/che-incubator/chectl/pull/461
   - [ ] https://github.com/eclipse/che-docs/pull/1039
- [ ] [che-operator] - serviceaccount permissions for <username>-che as default namespace https://github.com/eclipse/che/issues/15493
- [x] If workspace starting failed there is no information about error in the logs https://github.com/eclipse/che/issues/15604

### PRs
- [x] Fix shell detection when shell is empty value https://github.com/eclipse/che-machine-exec/pull/70
- [x] Change che-machine-exec according to fast cloud-shell integration(server part) https://github.com/eclipse/che-machine-exec/pull/63

### Unplanned
- [ ] Add certificate in the correct configuration for HA use case 
https://github.com/eclipse/che/pull/15568/files
- [x] Add `RELEASE.md` https://github.com/eclipse/che-operator/pull/152
- [x] Remove not maintained docker specific code https://github.com/eclipse/che-machine-exec/pull/75
- [x] Release 7.7.1 https://github.com/eclipse/che/issues/15726

[Planned](https://github.com/eclipse/che/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ateam%2Fdeploy+label%3Asprint%2Fcurrent-sprint+) | [In progress](https://github.com/eclipse/che/issues?q=is%3Aopen+is%3Aissue+label%3Ateam%2Fdeploy+label%3Asprint%2Fcurrent-sprint+label%3Astatus%2Fin-progress) | [Done](https://github.com/eclipse/che/issues?q=is%3Aissue+label%3Ateam%2Fdeploy+label%3Asprint%2Fcurrent-sprint+is%3Aclosed) | [Blocker](https://github.com/eclipse/che/issues?q=is%3Aissue+label%3Ateam%2Fdeploy+label%3Aseverity%2Fblocker+label%3Asprint%2Fcurrent-sprint) | [Backlog](https://github.com/eclipse/che/milestone/109)
