### ISSUE TITLE
Editors Sprint 178

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15628]
Jan 8 - Jan 28

### Goals
1. Finalize leftovers from the previous sprint
2. Che Theia 7.7.0 release, provide the release instructions
3. More secure Theia WebViews
4. Give a [talk](https://devconfcz2020a.sched.com/event/YOwk/web-development-with-eclipse-che-on-openshift) at DevConf.CZ 2020
5. Major cleanup of team's backlog
6. Theia upstream focus

### Issues
- [x] Make a release of Che Theia 7.7.0 https://github.com/eclipse/che/issues/15609
- [x] Provide RELEASE.md file with the release instructions for Che Theia https://github.com/eclipse/che/issues/15506
- [ ] Make Theia WebViews more secure https://github.com/eclipse/che/issues/15616
- [ ] Support Codicons in Command Palette https://github.com/eclipse/che/issues/15262
  - requires Monaco upgrade upstream https://github.com/eclipse-theia/theia/issues/6900
- [x] Debug>Start with no debug configurations gives no feedback to the user https://github.com/eclipse/che/issues/14006
- [x] Prepare the slides+demo to DevConf.CZ [talk](https://devconfcz2020a.sched.com/event/YOwk/web-development-with-eclipse-che-on-openshift)
- [ ] Cleanup the [area/che-theia](https://github.com/eclipse/che/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fche-theia) issues

#### Leftover from the previous sprint https://github.com/eclipse/che/issues/15531
- [x] Mark in the task widget title when task is exited https://github.com/eclipse/che/issues/14132
- [x] Che Theia build failing with the latest stable yarn https://github.com/eclipse/che/issues/15552

#### Theia upstream focus
- filed issue - [scm] align scm state markers in the explorer with VS Code https://github.com/eclipse-theia/theia/issues/6904

Within the Codicons support https://github.com/eclipse/che/issues/15262:
- investigating the upstream issue https://github.com/eclipse-theia/theia/issues/5412
- participated in Theia Dev call with Monaco upgrade topic https://github.com/eclipse-theia/theia/wiki/Dev-Meetings#agenda-2020-01-14
- started work on Monaco upgrade https://github.com/eclipse-theia/theia/issues/6900

#### Unplanned
- [x] Che Theia docker build is failed https://github.com/eclipse/che/issues/15695
- [x] Editor tabs are not restored after refreshing browser tab https://github.com/eclipse/che/issues/15317
- [x] Make a release of Che Theia 7.7.1 https://github.com/eclipse/che/issues/15726
- [ ] Consume VS Code built-in extensions in Che-Theia https://github.com/eclipse/che/issues/14759

### Availability
| Name  | Availability | x0.6
| -- | -- | --
| Artem | 12  | 7
| Roman   | 15  | 9
| Vlad   | 15  | 9

---
[Previous Sprint](https://github.com/eclipse/che/issues/15531)
