### ISSUE TITLE
Languages Sprint 178

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15629]
Jan 11-Jan 28

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 8 | 5 | 5
@sunix | 10 | 6 | 6
@vrubezhny | 12 | 7 | 7
@JPinkney | 12 | 7 | 7
@svor | 5 | 3 | 3

# Planned Issues
- [ ] New plugins for CRW 2.1 (https://issues.redhat.com/browse/CRW-544)
Need to find/create images and test with those. Make sure the samples are properly licensed.
  - [ ] vscode-java: java 11 2d @svor 
  - [ ] quarkus java8
  - [ ] quarkus java11
  - [ ] redhat/vscode-camelk/0.0.9 (https://github.com/camel-tooling/vscode-camelk). There is no upstream equivalent for this one.
- [ ] try out an document the manual setup of air-gapping for our various built systems, in particular:
  - [ ]  npm (assuming all relevant build systems use npm for package mgmt) https://github.com/eclipse/che/issues/15501 3d @sunix 
   - [ ]  maven #15503 2d @sunix
   - [ ] gradle #15510
   - [ ] python #15664 1d timebox @svor 
   - [ ] go packages #15512 
- [x] Context dependent code completion https://github.com/redhat-developer/yaml-language-server/issues/206 2d @JPinkney 
- [x] Server-side snippet support https://github.com/redhat-developer/yaml-language-server/issues/205  2d @JPinkney 
- [x] Make auto completion use JSON Schema 7 parser https://github.com/redhat-developer/yaml-language-server/issues/150 3d @JPinkney 
- [x] CallHierarchyService Plugin API https://github.com/eclipse-theia/theia/issues/3765 @tsmaeder 2.5
- [ ] Update Debugger for Java and Language support for Java to latest #15560  1d
- [ ] Upgrade vscode-xml plugin to 0.10.1 #15592
- [ ] Can't debug Quarkus application https://github.com/eclipse/che/issues/15114 1d timebox for investigation of Step 1 @sunix 
- [ ] fixup: Consume VS Code built-in extensions in Che-Theia #14759
- [ ] Add Native Compilation Commands to Quarkus Devfile #15630
- [x] Add an information about cpp into Language support troubleshooting document #14943 0.5 (@tsmaeder )
- [ ] add 'References' widget https://github.com/eclipse/che/issues/14856 and https://github.com/eclipse-theia/theia/issues/4784 7d @vrubezhny @tsmaeder 
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d 
- [ ] Use a maven sample for the maven stack #15216
- [ ] Plug-ins leaking CodeLens, etc. https://github.com/eclipse-theia/theia/issues/4472
- [ ] Preview is not shown in default project for Python Django stack #15053

# To be planned

# From Last Sprint

# Open Pull Requests
- [ ] CallHierarchyService Plugin API #3765 https://github.com/eclipse-theia/theia/pull/6924
- [ ] No error message if vscode.open command is invoked with reso… https://github.com/eclipse-theia/theia/pull/6568
- [ ] Refactor services parts of plugin-ext to use DI https://github.com/eclipse-theia/theia/pull/6358 @JPinkney 1d (check against che-theia)
- [ ] Consume VS Code built-in extensions in Che-Theia #14759 2d @tolusha 

# Blocked issues 
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic #13427 2d @tsmaeder 
=> need working tasks implementation for multi-root workspaces.

# Unplanned Issues
- [ ] Sometimes It is necessary to have same HOME for plugin and dev containers #14938
- [ ] Investigate Native-Compiling jdt.ls #13835 (2d timebox)  @JPinkney 
- [ ] Simple LSP test suite for Java #14409 3d @JPinkney 
  - [ ] Propose an "official" devfile/test plugin with simple, but reasonable Java tests

CRW issues: 

Previous Sprint: https://github.com/eclipse/che/issues/15269
