### ISSUE TITLE
Che Plugins Sprint 178

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#15633]
## Sprint goals
1. Blockers / Cross-team Collaboration
2. Details
3. Analysis
 
**Notes**:
- We have opted for a regular 3 week sprint: January 8 - January 28
- Sections are ranked in order of priority.
- Issues in each section are ranked in order of priority. Pick from the top.
- Blocker issues from the [backlog](https://github.com/eclipse/che/milestone/95) are tracked here as well, for now

### Issues needing cross-team collaboration
* [ ] Improve login procedure for GitHub PullRequest Plugin #14217  

 ### Details
**1. Epic: OpenShift Connector for Eclipse Che #14900**
* [ ]  Openshift connector and Che: openshift user should be logged automatically with the Openshift user. #15261

**2. Backlogged Tasks/Bugs/Improvements**
* [ ]  Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side. #15277
* [ ]  Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270
* [ ] Terminal change title feature should be configurable #15242 
* [x]  Upgrade Kubernetes Che plugin with Helm 3 support #15190
* [ ]  [k8s plugin] buildah push command doesn't work #15035  
* [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins #14119 

**3. Eric's Technical Ramp Up**
* [x] Get Che running locally
* [ ] Learn how to develop fixes for Che (and possibly Che-Theia) within Che
* [x] Look into Git integration and think about workflow for Git + SSH epic #13494
* [x] Take a stab at fixing #15190

**4. Open PRs From Last Sprint**
* [x] Rename Che Theia Factory Plugin to Workspace Plugin #14653
* [x] Align development flow for vscode extensions #14228 
* [x] Cannot generate VC Code extension using Yeoman Wizard #15443

**5. Unplanned Issues/Regressions**
* [x] Cannot clean terminal with keybindings anymore eclipse-theia/theia#6916
 
 ## Analysis
 #### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 14  | 8 |
| @ericwill | 13  | 8 |

**Comment by ericwill** [comment]
Superseded by sprint 179, #15862
