### ISSUE TITLE
QE-2020-01-28 (Sprint: 178)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#15634]
### Unplanned 
- [x] [Happy Path] Add checking of the deployed application readiness in the "Happy Path" scenario. #15574 2sp
- [x] The "PreviewWidget.waitUrl" method has locator not applicable for all stacks #15717 1sp
- [x] TS_SELENIUM] Create method for expanding project tree according to provided path #15753 1sp
- [x] [TS_SELENIUM] Simplify "inversify" modules binding #15804 1sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 5 |
| Total |  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |

### Reference
