### ISSUE TITLE
[Doc] Clarify prerequisites for Che install.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#15680]
### Is your enhancement related to a problem? Please describe.

The recent versions of Che runs on K8s or OpenShift.
And I couldn't find the minimum version information about K8s and OpenShift.
As sometimes K8s API version is obsoleted and removed, clarifying supported versions is important to users. (refs comment in #15278 )

Previously, the similar issue was raised as #9576.  But the link to the doc was broken.
So it should be discussed again, IMO.

### Describe the solution you'd like

Prerequisites (supported versions of K8s / OpenShift) are shown on `eclipse/che/README.md` or somewhere.
 
### Describe alternatives you've considered

Just in case deploying with Helm, supported K8s version information can be embedded to `Chart.yaml`.

### Subtasks

- [x] Find out what's the minimum Kubernetes version supported: v1.9.11
- [x]  Find out what's the minimum OpenShift version supported: v3.11
- [x]  Find out what's the minimum helm version supported: v2.15.2
- [x] Mention the minimum versions in the installation requirements section of Che documentation
- Add a chectl preflight check step that verifies that the platform version is supported:
  - [x] Check the version when `--platform=k8s`
  - [x] Check the version when `--platform=openshift`

**Comment by l0rd** [comment]
Makes sense @monaka thanks for raising it. @tolusha I am adding that to `team/deploy` as that's something that should be check at installation time when using `chectl` (I have added that as a subtask). Anyway I think that the minimum versions are kubernetes 1.9 and OpenShift 3.8 but it should be verified.

**Comment by tolusha** [comment]
@l0rd 
It make sense to take in a new sprint

**Comment by l0rd** [comment]
I have added a task to check `helm` version as well because I just figure out on my local laptop that installation fails with `helm` v2.12.3

**Comment by tolusha** [comment]
@l0rd 
Is there any strategy to find out the minimal version of supported components
I can try to install different versions, but is there any better approach?

**Comment by tolusha** [comment]
Accordingly to the doc
- Openshift v3.11 [1]
- Kubernetes v1.9 [2]

[1] https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-3-using-the-operator/
[2] https://www.eclipse.org/che/docs/pages/che-7/overview/proc_using-minikube-to-set-up-kubernetes.html


[1] https://www.eclipse.org/che/docs/che-7/installing-che-on-openshift-3-using-the-operator/

**Comment by l0rd** [comment]
@tolusha no I don't think we have another option. We need to install different versions and test.

**Comment by dmytro-ndp** [comment]
@tolusha, @l0rd: on PR check jobs we are normally installing Eclipse Che on minikube 1.1.1 by using helm of v2.13.0-rc.2+gb0d4c9e version.
WDYT about setting [helm minimal version to 2.13](https://github.com/che-incubator/chectl/blob/master/src/api/version.ts#L17)?
