### ISSUE TITLE
Languages Sprint 179

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15796]
Jan 11-Feb 18

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 6 | 4 | 4
@sunix | 10 | 6 | 3 |
@vrubezhny | 13 | 8 | 8
@JPinkney | 12 | 7 | 6.5
@svor | 13 | 8 | 8

# Planned Issues
- [x] CRW 2.1 devfiles https://issues.redhat.com/browse/CRW-402
  - [x] Add a Quarkus sample in out-of-the-box devfiles https://issues.redhat.com/browse/CRW-586 
    PR here: https://github.com/redhat-developer/codeready-workspaces/pull/223 1d @svor 
  - [x] Add a camel-k sample in out-of-the-box devfiles https://issues.redhat.com/browse/CRW-609 
- [ ] Java Language Server fails in 'Restricted Environment' to download Gradle https://issues.redhat.com/browse/CRW-330 1d @svor 
- [x] Update golang stack/sidecar to include golangci-lint (remove gometalint) https://issues.redhat.com/browse/CRW-585 1d @svor 
- [ ] Hat CodeReady Workspaces / Eclipse Che Support for EAP 7.3 https://issues.redhat.com/browse/CRW-340 1d @svor including testing updated image with devfiles.
- [ ] Document and QE Usage of Dependencies Repositories in Offline Scenario https://issues.redhat.com/browse/CRW-529 
  - [ ]  npm (assuming all relevant build systems use npm for package mgmt) https://github.com/eclipse/che/issues/15501 3d @sunix 
   - [ ] gradle #15510 3d @svor 
   - [ ] python #15664 
   - [x] go packages #15512 2d timebox @JPinkney 
- [ ] Update Debugger for Java and Language support for Java to latest #15560 1d @tsmaeder 
- [x] Add netcoredb plugin to CRW 2 https://issues.redhat.com/browse/CRW-520 1d to test plugin works with 3.0 @svor 
- [x] Task prepare database fails on Java with MySQL #15852 1d @JPinkney 
- [x] Tasks fails for NodeJS Angular #15853 0.5d @JPinkney 
- [ ] Implement Airgapped Configuration Mechanism #15518 3d timebox for design @tsmaeder 
- [ ] Improve naming of the default stacks https://issues.redhat.com/browse/CRW-521 
- [ ] Check extensions of VS Code extension pack are running smoothly #15390 1d
       Task: test extensions for Java extensions pack work together in one sidecar.
- [x] Upgrade vscode-xml plugin to 0.10.1 #15592
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d 
- [ ] Use a maven sample for the maven stack #15216
- [ ] Plug-ins leaking CodeLens, etc. https://github.com/eclipse-theia/theia/issues/4472
- [ ] Preview is not shown in default project for Python Django stack #15053
- [ ] Simple LSP test suite for Java #14409, https://github.com/eclipse/che/issues/15797 3d @JPinkney 
  - [x] Propose an "official" devfile/test plugin with simple, but reasonable Java tests 2d @JPinkney 
  - [x] Have a conversation with @rhopp on how to set up a PR-Check running said test suite 1d
  - [ ] Run it as a CI test when committing to a relevant folder in che-plugin-registry 
- [ ] add 'References' widget #14856 and eclipse-theia/theia#4784 4d
  - [ ] add to theia examples 1d
  - [ ] add to che-theia 
# To be planned

# From Last Sprint

# Open Pull Requests
- [ ] No error message if vscode.open command is invoked with reso… https://github.com/eclipse-theia/theia/pull/6568 3d @vrubezhny 
- [ ] Refactor services parts of plugin-ext to use DI https://github.com/eclipse-theia/theia/pull/6358 @JPinkney 

# Blocked issues 
- [ ] Java LS "Classpath is incomplete" warning when loading petclinic #13427 2d @tsmaeder 
=> need working tasks implementation for multi-root workspaces.
- [ ] (https://issues.redhat.com/browse/CRW-412) CRW 2.1 Improved code samples for default devfiles

# Unplanned Issues
- [ ] Sometimes It is necessary to have same HOME for plugin and dev containers #14938
- [ ] Investigate Native-Compiling jdt.ls #13835 (2d timebox)  @JPinkney 

CRW issues: 

Previous Sprint: https://github.com/eclipse/che/issues/15629
