### ISSUE TITLE
Che Deploy Sprint 179

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#15839]
Jan 29 - Feb 18

### Availability
| Name  | Availablility |
| ------------- | ------------- |
| Anatolii   | 15d  |
| Mykola   |  15d  |
| Aleksandr  | 15d  |

### Issues
- [ ] [POC] TLS by default  https://github.com/eclipse/che/issues/15313
  - [x] Remove redundunt self-signed-cert secret 
  - [x] Add cert-manager readiness check
  - [x] Stabilize job awaiter
  - [x] Stabilize secrets awaiter to wait for all data fields to be filled in the secret object
  - [x] Final testing of the flow on minikube
  - [ ] https://github.com/che-incubator/chectl/pull/476
- [ ] [che-operator] - serviceaccount permissions for <username>-che as default namespace https://github.com/eclipse/che/issues/15493
  - [ ] https://github.com/eclipse/che-operator/pull/156/files
  - [x] ~~https://github.com/che-incubator/chectl/pull/469~~
- [x] [Doc] Clarify prerequisites for Che install https://github.com/eclipse/che/issues/15680
  - [x] https://github.com/che-incubator/chectl/pull/500
  - [x] https://github.com/eclipse/che-docs/pull/1081
- [x] chectl: add an ability to debug Che Server https://github.com/eclipse/che/issues/14976
  - [x] https://github.com/eclipse/che-operator/pull/160
  - [x] https://github.com/che-incubator/chectl/pull/477
- [x] cheimage parameter tag is applied to all images of Che deployment instead of Che server only https://github.com/eclipse/che/issues/14898
- [x] Remove image refs in `defaults.go` and replace by env vars? https://github.com/eclipse/che/issues/15874
- [x] Allow OLM installation through CatalogSource and related docker image https://github.com/eclipse/che/issues/15802
- [ ] Enable chectl to install Che through OLM when appropriate https://github.com/eclipse/che/issues/15279

### PRs
- [ ] Add certificate in the correct configuration for HA use case 
https://github.com/eclipse/che/pull/15568/files
- [x] Install Eclipse Che uses storage classes https://github.com/eclipse/che-docs/pull/1039
- [ ] [WIP] Improve configmap with helm https://github.com/eclipse/che/pull/15825
- [x] Merge pending PRs https://github.com/che-incubator/chectl/pulls

## Unplanned
- [x] Don't wait keycloak pod if externalIdentityProvider is set https://github.com/che-incubator/chectl/pull/514
- [x] chectl inject should support oc CLI  https://github.com/eclipse/che/issues/15987
- [x] feat: Allows to override default values https://github.com/che-incubator/chectl/pull/508
- [x] Use watch utility to monitor newly created pods https://github.com/eclipse/che/issues/15986
  - [x] https://github.com/che-incubator/chectl/pull/505
- [x] Fix CR to use `quay.io/eclipse/che-keycloak:nightly` https://github.com/eclipse/che-operator/pull/159
- [x] Add Cloud shell terminal like Che editor https://github.com/eclipse/che-plugin-registry/pull/326
- [x] `che-operator` release https://github.com/eclipse/che-operator/pull/163
- [x] https://github.com/operator-framework/community-operators/pull/1181
- [x] https://github.com/operator-framework/community-operators/pull/1182
- [x] Improve test scripts to test che-operator installed via OLM locally https://github.com/eclipse/che-operator/pull/167

 [In progress](https://github.com/eclipse/che/issues?utf8=%E2%9C%93&q=label%3Ateam%2Fdeploy+label%3Astatus%2Fin-progress+)  | [Backlog](https://github.com/eclipse/che/milestone/109) | [Previous Sprint](https://github.com/eclipse/che/issues/15615)
