### ISSUE TITLE
QE-2020-02-18 (Sprint: 179)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#15857]
### Issues tied to objectives
- [x] Move QE jobs from codenvy CI to Centos CI #15517 8sp
- [x] Move pre-release test jobs to ci.centos #15701 8sp

### Unplanned 
- [x] [ TS_SELENIUM ] Simplify locator of the "Notification center" #15903 1sp
- [x] [TS_SELENIUM] The logical mistake in the "Editor.ts" pageobject leads to "StaleElementReference" error #15940 1sp
- [x] [TS_SELENIUM] Create pageobject for interaction with terminal #15995 2sp
- [x] [TS_SELENIUM] Update code owners list of the "e2e" project #16004 1sp
- [x] E2E tests failed on "Language server validation" step #16017 1sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 5 |
| Total |  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |

### Reference
