### ISSUE TITLE
Platform-2020-02-18 (Sprint: 179)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#15869]
## Tasks
Dashboard https://github.com/eclipse/che/projects/15

- [x] Improve isolation of Che theia and che-machine-exec components | https://github.com/eclipse/che/issues/15651 | 8
- [x] Write workspace's containers stdout/err log to file | https://github.com/eclipse/che/issues/15834 | 8
- [ ] Possible to set CPU limits as well on the plugin containers | https://github.com/eclipse/che/issues/13709 | 8
- [ ] Provide an ability to override CPU limits of plugin/editor containers in devfile | https://github.com/eclipse/che/issues/15306 | 8
- [x] Access to the workspace that is in the recovering queue may lead it to an unpredictable state | https://github.com/eclipse/che/issues/15801 | 5

#### Availability

| Name | Available | 
| :-- | --: | 
| Michal Vala | 13,5d | 
| Lukas Krejci | 10d |
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 14d | 
| Total | 52,5 human*day | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 37 |21|
#### Retrospective Comments
 - There were delays between original input that comes from the original brief https://github.com/eclipse/che/issues/15047 and architects pov. We have to change the implementation scope during the sprint.
