### ISSUE TITLE
Che Plugins Sprint 179

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#15862]
## Sprint goals
1. Continue integration with OpenShift
2. Improve Git/GitHub flow
3. Bug fixing
4. Cherkasy face-to-face meeting

**Notes**:
- Sections are ranked in order of priority.
- Issues in each section are ranked in order of priority. Pick from the top.

### Blockers / Unplanned Issues / Regressions
* [ ] Add an ability to add public key certificate to Java trust store #16002

### Epics
**Epic: OpenShift Connector for Eclipse Che #14900**
* [ ] Openshift connector and Che: openshift user should be logged automatically with the Openshift user. #15261
    * [ ] Make it possible to get OpenShift oauth token from theia IDE container #15670
* [ ] Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270

**Epic: Git + SSH flow #13494**
* [ ] Improve login procedure for GitHub PullRequest Plugin #14217
    * [ ] [Plugin-Api] Apply window.registerUriHandler() function eclipse-theia/theia#5119

### Bugs
* [ ] Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side. #15277
* [ ] [k8s plugin] buildah push command doesn't work #15035  
* [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins #14119 

### Open PRs From Last Sprint
* [x] Terminal change title feature should be configurable #15242

### Other
* [x] Add Vale vscode plugin to the plugin registry #15856
* [x] Cherkasy face-to-face meeting Feb 3 - 6

 ## Analysis
 #### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 11  | 6 |
| @vinokurig  | 11  | 6 |
| @ericwill | 9  | 5 |

**Comment by ericwill** [comment]
Superseded by sprint 180, #16083
