### ISSUE TITLE
Editors Sprint 179

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#15902]
Jan 29 - Feb 18

### Goals
1. Monaco upgrade in Theia
2. Bugfixes that have major UI/UX impact
3. Major cleanup of team's backlog
4. Finalize leftovers from the previous sprint
5. Theia upstream focus

### Issues
- [ ] Monaco upgrade in Theia https://github.com/eclipse-theia/theia/issues/6900
  - [x] upgrade [vscode-ws-jsonrpc](https://github.com/TypeFox/vscode-ws-jsonrpc) to the `5.0.0` version of `vscode-jsonrpc` https://github.com/TypeFox/vscode-ws-jsonrpc/issues/17
  - [ ] upgrade [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to the latest Monaco version https://github.com/TypeFox/monaco-languageclient/issues/194
  - [ ] upgrade [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to the latest LSP version https://github.com/TypeFox/monaco-languageclient/issues/196
  - [ ] revert the hotfix for IME support https://github.com/eclipse-theia/theia/pull/6673 and check whether IME support is fixed in newer Monaco
- [x] Cleanup the backlog

|   | area/che-theia | team/editors
| -- | -- | --
| Before   | 77  | 88
| Wrong label | 18  | 27
| Closed issues as cannot reproduce/already fixed   | 7  | 11
| After   | 52  | 45

#### UI/UX bugfixes
- [ ] Rework che-theia branding to provide logo icon for plugin webview https://github.com/eclipse/che/issues/15324
- [ ] Theia hotkeys aren't handled when a WebView is in focus https://github.com/eclipse/che/issues/15763
- [x] Theia Color theme switching works improperly https://github.com/eclipse/che/issues/15764
- [ ] Show a confirmation dialog when Ctrl+W is pressed in the terminal https://github.com/eclipse/che/issues/13580

#### Leftover from the previous sprint https://github.com/eclipse/che/issues/15628
- [x] Consume VS Code built-in extensions in Che-Theia https://github.com/eclipse/che/issues/14759
- [x] Make Theia WebViews more secure https://github.com/eclipse/che/issues/15616 (merge the PRs)
- [ ] Support Codicons in Command Palette https://github.com/eclipse/che/issues/15262

#### Theia upstream focus
PRs proposed:
- [DRAFT] Create terminal widget immediately at running task https://github.com/eclipse-theia/theia/pull/7108
- [DRAFT] Bump monaco version https://github.com/TypeFox/monaco-languageclient/pull/199
- [DRAFT] Upgrade to LSP 6.0.0 and Monaco 0.19.3 https://github.com/eclipse-theia/theia/pull/7149

PRs reviewed:
- https://github.com/eclipse-theia/theia/pull/7110#pullrequestreview-357346440
- https://github.com/eclipse-theia/theia/pull/7144#pullrequestreview-358060133
- https://github.com/eclipse-theia/theia/pull/6957
- https://github.com/eclipse-theia/theia/pull/7163

Participating in the issues:
- https://github.com/eclipse-theia/theia/issues/7125#issuecomment-584594478
- https://github.com/eclipse-theia/theia/issues/7129#issuecomment-584622939

#### Unplanned
- [x] Che Theia build is failed https://github.com/eclipse/che/issues/15917
- [x] che in che development is broken https://github.com/eclipse/che/issues/15932
- [x] helping Prod Team running K8s plugin with CRW on OpenShift
- [x] helping Platform Team to investigate the idling issue https://github.com/eclipse/che/issues/15991
- [x] investigating a problem with Che Theia terminal https://github.com/eclipse/che/issues/15969
- [x] release of Che Theia 7.9.0 https://github.com/eclipse/che/issues/16008
- [ ] PR check CI job migration https://github.com/eclipse/che/issues/16054

### Availability
| Name  | Availability | x0.6
| -- | -- | --
| Artem | 13  | 8
| Roman   | 15  | 9
| Vlad   | 14  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/15628)
