### ISSUE TITLE
Che Plugins Dependencies Resolution

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15966]
### Is your enhancement related to a problem

We allow vs code extensions to run in their own, remote from theia, container.
As a consequence vs code extensions aren't able to "see" extensions that are running in other containers. That has all sort of problems when 2 che plugins reference the same vs code extension (that get loaded twice) or when one vs code extension needs to call another extension at runtime (that get downloaded from the marketplace and in the wrong container...).

A comprehensive description of these problems is described in [this google doc](https://docs.google.com/document/d/1NuoLFNooScyaU1_iOeJSt6BLmL_-KMAj_eNoA6g2wJs/edit#heading=h.o5ikxl3kofux).

Discussion document:
https://docs.google.com/presentation/d/1T1v8jfHArOnT_KjFaKwSYYyPB7dhs6tjOoJtmDaRUVw/edit#slide=id.g6ea84496cc_0_224

### Describe the solution you'd like

As a **short term** solution we envision to:

- [x] disable automatic extension dependency resolution in che-theia
- [x] warn users if an extension is downloaded twice https://github.com/eclipse/che-plugin-broker/pull/93

And the **long term** solution is about: 

- [x] rework theia endpoint to let extensions "see" remote extensions (list, get, call)
- [x] support running in the same container plugins that reference the same image https://github.com/eclipse/che/issues/15373
- [ ] support specifying che-plugins as dependencies of other che-plugins https://github.com/eclipse/che/issues/15376
- [ ] re-enable automatic extensions dependency resolution but with the ability to specify an alternative marketplace
