### ISSUE TITLE
Che to perform git clone of projects to reduce errors and for easier integration with editors

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15973]
### Cloning projects lifecycle.

Today, the clone operation is done when user is opening the workspace in Eclipse Theia.

So it means, that we delay the clone operation at the end, when a client is connected.

It's mostly due to handle the 'private' projects where authentication is required and then user is prompted with github oAuth for example.

That said, there are several drawbacks to do this at the final step.
- clone is only performed for Eclipse Theia (if you're using Jupyter, Eclipse IDE, etc editors the project is never cloned)
- it takes time. Let say the workspace is created, during the time that Theia is loaded, the project could have been already cloned.
- language servers may be initialized too early.
- in case of #15960 sync PV storage, you need to know if some files have restored or not when the IDE is loading to not clone again. But if clone has already happened it's the same loading sequence.

Workspace startup can be faster if it's done earlier.

### Private repositories and handling
We could clone in init container, etc but it may work only for public repositories.
Workspace loader could handle as well the clone operation for private projects as it's used by all editors.
Init containers could handle also the clone operation if we've stored previously some tokens.

## How are we going to address it?

- [x] [Projects clone should happen before other components are started](https://github.com/devfile/devworkspace-operator/issues/205)
- [ ] User should be able to manage his Git credentials and SSH Keys from the dashboard (c.f. [User Preferences-Adding External Accounts](https://github.com/eclipse/che/issues/17954))
- [ ] Workspace loader should fail to start the workspace if the user does NOT have the privileges to clone the repository (c.f. devfile resolver)
- [ ] Workspace loader should look for a devfile in the project repository before creating the DevWorkspace CR (devfile resolver)
- [ ] Workspace loader should authenticate user against GitHub, GitLab and Bitbucket to in projects retrieve devfile

**Comment by ibuziuk** [comment]
@benoitf which team is expected to work on this epic?

**Comment by benoitf** [comment]
For now it's unassigned let's assign to devex

**Comment by l0rd** [comment]
When working on an implementation we should think about something that will work with devworkspace operator and devfile 2.0 too.

**Comment by l0rd** [comment]
I am removing this as part of "DevWorkspace Integration - STEP3" milestone as we are going to include https://github.com/eclipse/che/issues/20432 instead.
