### ISSUE TITLE
QE-2020-03-10 (Sprint: 180)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#16058]
### Issues tied to objectives
- [x] Move QE jobs from codenvy CI to Centos CI #15517 

### Unplanned 
- [x] Use 80.0 Chrome driver in typescript selenium tests #16090 2sp
- [x] Add possibility to change the bindings in downstream #15881 1sp
- [x] [TS_SELENIUM] Move "@eclipse-che/api" from "devDependencies" to "dependencies" in the "e2e" project #16172 1sp
- [x] Create "Get Started" page object in E2E typescript selenium tests #16208 1sp
- [x] [TS_SELENIUM] Rework a "Terminal.getText" method for avoiding fails #16256 1sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 5 |
| Total |  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |

### Reference
