### ISSUE TITLE
Languages Sprint 180

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#16069]
Feb. 19 - Mar 10

# Availability
Who | available | x0.6 | planned
-- | -- | -- | --| 
@tsmaeder | 7 | 4 | 4
@sunix | 13 | 8 | 8.5
@vrubezhny | 14 | 8.5 | 8
@JPinkney | 14 | 8.5 | 10
@svor | 13 | 8 | 9.5

# Planned Issues
- [x] LS not working for Java Maven #16051 1.5d @svor 
- [ ] Document and QE Usage of Dependencies Repositories in Offline Scenario https://issues.redhat.com/browse/CRW-529 
  - [ ]  npm (assuming all relevant build systems use npm for package mgmt) https://github.com/eclipse/che/issues/15501 3d @sunix 
   - [x] gradle #15510 3d @svor 
   - [x] python #15664 5d @svor 
- [ ] Add a camel-k sample in out-of-the-box devfiles https://issues.redhat.com/browse/CRW-609 2.5d @sunix 
- [ ] Set up PR Check for Java Che 7 plugins #15797 5d @JPinkney 
- [ ] Task `install dependencies` failing in PHP Symfony #15854 1d @JPinkney 
- [x] Build in Java with SpringBoot and MySQL failing https://github.com/eclipse/che/issues/15911 1d @JPinkney 
- [x] Add Gradle 6 support #15723 1d @svor 
- [ ] Collect Air-Gapping Documentation #16074 2d @tsmaeder 
- [ ] CRW 2.1 Improved code samples for default devfiles https://issues.redhat.com/browse/CRW-412
  - [ ] Java Gradle 1.5 @sunix 
  - [ ] Java Maven 1.5 @sunix 
  - [ ] NodeJS 1.5 @JPinkney 
  - [ ] Golang 1.5
  - [ ] .Net 1.5 @svor 
- [ ] How to develop against a different Java version than the one in the Java tooling sidecar #13250
- [ ] Use a maven sample for the maven stack #15216
- [ ] Hat CodeReady Workspaces / Eclipse Che Support for EAP 7.3 https://issues.redhat.com/browse/CRW-340 1d @svor including testing updated image with devfiles.
- [ ] Implement Airgapped Configuration Mechanism #15518 2d timebox for design @tsmaeder 
- [ ] Improve naming of the default stacks https://issues.redhat.com/browse/CRW-521 
- [ ] Check extensions of VS Code extension pack are running smoothly #15390 
       Task: test extensions for Java extensions pack work together in one sidecar. 1d
- [ ] Created file/folder should be selected https://github.com/eclipse-theia/theia/issues/6190 1.5d 
- [ ] Plug-ins leaking CodeLens, etc. https://github.com/eclipse-theia/theia/issues/4472 3d @vrubezhny 
- [ ] Preview is not shown in default project for Python Django stack #15053
- [ ] add 'References' widget #14856 and eclipse-theia/theia#4784 
  - [ ] add to che-theia 1d @vrubezhny 
# To be planned

# From Last Sprint

# Open Pull Requests
- [ ] No error message if vscode.open command is invoked with reso… https://github.com/eclipse-theia/theia/pull/6568 3d @vrubezhny 
- [ ] Refactor services parts of plugin-ext to use DI https://github.com/eclipse-theia/theia/pull/6358 @JPinkney
- [ ] Implementation of testing api for testing vscode extensions language features #597 https://github.com/eclipse/che-theia/pull/597 2d
- [ ] Find All references` doesn't exist for typescript plugin https://github.com/eclipse-theia/theia/pull/7055 1d
# Blocked issues 

# Unplanned Issues
- [ ] Sometimes It is necessary to have same HOME for plugin and dev containers #14938
- [ ] Java Language Server fails in 'Restricted Environment' to download Gradle https://issues.redhat.com/browse/CRW-330 (done: documentation provided)
CRW issues: 

Previous Sprint: https://github.com/eclipse/che/issues/15796

**Comment by benoitf** [comment]
Hi, FYI the date of the sprint is not matching the date of this sprint
![image](https://user-images.githubusercontent.com/436777/74915279-408e8980-53c4-11ea-8473-bd15bcad3461.png)

And link to previous sprint is also invalid (it's the previous/previous aka 178)
