### ISSUE TITLE
Platform-2020-03-10 (Sprint: 180)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#16078]
## Tasks
Dashboard https://github.com/eclipse/che/projects/18

- [x] Possible to set CPU limits as well on the plugin containers | https://github.com/eclipse/che/issues/13709 | 5
- [x] Provide an ability to override CPU limits of plugin/editor containers in devfile | https://github.com/eclipse/che/issues/15306 | 8
- [x] Workspace start in debug mode -> watch the logs | https://github.com/eclipse/che/issues/15983 | 5
- [x] it's not possible to start workspace in Single-User Che anymore | https://github.com/eclipse/che/issues/16053 | 13

#### Availability

| Name | Available | 
| :-- | --: | 
| Michal Vala | 12d | 
| Lukas Krejci | 11d |
| Sergii Kabashniuk | 14*0.5d |
| Max Shaposhnik | 13d | 
| Total | 43 human*day | 

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 32 |32|

#### Retrospective Comments
- The maven module hierarchy is not very clear. Action item: think about some high-level diagrams or documents that explain basics.
- Docs. Sometimes docs pr merged before the code pr. Documentation can be in the version before when it actually appears in the code. Action item: to talk about that with the docs team. Clarify expectations and roles.
