### ISSUE TITLE
Che Plugins Sprint 180

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16083]
## Sprint goals
1. Continue integration with OpenShift
2. Improve Git/GitHub flow
3. Bug fixing
4. Maintenance / Automation / Technical Debt

**Notes**:
- Sections are ranked in order of priority.
- Issues in each section are ranked in order of priority. Pick from the top.

### Epics
**Epic: OpenShift Connector for Eclipse Che #14900**
* [ ] Openshift connector and Che: openshift user should be logged automatically with the Openshift user. #15261
* [ ] Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270

**Epic: Git + SSH flow #13494**
* [ ] Improve login procedure for GitHub PullRequest Plugin #14217
    * [ ] [Plugin-Api] Apply window.registerUriHandler() function eclipse-theia/theia#5119

### Bugs
* [ ] Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side. #15277
    * [ ] Investigate on che-theia and benchmark timing
    * [ ] Use results of investigation to discuss architectural design of running tasks
* [x] [k8s plugin] buildah push command doesn't work #15035  
    * [x] Investigate why building doesn't work, and fix it
    * [x] Get push working
* [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins #14119 
    * [ ] Land on solution for che-dockerfiles layout and start implementing it

### Open PRs From Last Sprint
* [x] Make it possible to get OpenShift oauth token from theia IDE container #15670
    * [x] Apply creation of the OpenShift oAuth client by che-operatot https://github.com/eclipse/che/pull/15963#issuecomment-591500848
    * [x] Add an ability to add public key certificate to Java trust store #16002
      * [x] Apply che-server-redeploy watcher to the certificates config-map https://github.com/eclipse/che-operator/pull/171#discussion_r384577253

### Maintenance / Automation / Technical Debt
* [x] Provide script to automatically file issues for outdated plugins #16215
* [ ] Integrate dependabot into more che-dockerfiles repos
* [ ] Upgrade forked vscode-git to the latest version #16041
   * [x] Build vscode-git from upstream using automated Jenkins job
   * [ ] Test plugin inside Che to verify it works before updating

 ## Analysis
 #### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 14  | 8 |
| @ericwill | 14  | 8 |

**Comment by ericwill** [comment]
Superseded by sprint 181, #16336
