### ISSUE TITLE
Editors Sprint 180

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16086]
Feb 19 - Mar 10

## Goals
1. Fix P1s that have major UI/UX impact
2. Finalize work stared in the previous sprint
3. Theia upstream focus
4. Release Che Theia 7.10.0

### UI/UX bugfixes
- [ ] Support Codicons in Command Palette https://github.com/eclipse/che/issues/15262
- [x] Show a confirmation dialog when Ctrl+W is pressed in the terminal https://github.com/eclipse/che/issues/13580
- [x] Rework che-theia branding to provide logo icon for plugin webview https://github.com/eclipse/che/issues/15324
- [x] About dialog is broken https://github.com/eclipse/che/issues/15962
- [ ] Theia hotkeys aren't handled when a WebView is in focus https://github.com/eclipse/che/issues/15763
- [x] Update Che Theia CSS styling to respect the VS Code theming approach https://github.com/eclipse/che/issues/16079

### Other issues
- [x] PR check CI job migration https://github.com/eclipse/che/issues/16054
- [x] Add timestamps to Theia logs https://issues.redhat.com/browse/CRW-614
- [x] Release Che Theia 7.10.0 https://github.com/eclipse/che/issues/16298

### Theia upstream focus
- [ ] Monaco upgrade https://github.com/eclipse-theia/theia/issues/6900
  - [ ] upgrade [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to the latest Monaco version https://github.com/TypeFox/monaco-languageclient/issues/194
  - [ ] upgrade [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) to the latest LSP version https://github.com/TypeFox/monaco-languageclient/issues/196
  - [ ] revert the hotfix for IME support https://github.com/eclipse-theia/theia/pull/6673 and check whether IME support is fixed in newer Monaco

#### PRs proposed:
- https://github.com/eclipse-theia/theia/pull/7216

#### PRs reviewed:
- https://github.com/eclipse-theia/theia/pull/7136
- https://github.com/eclipse-theia/theia/pull/6650
- https://github.com/eclipse-theia/theia/pull/7181
- https://github.com/eclipse-theia/theia/pull/7179
- https://github.com/eclipse-theia/theia/pull/7242

### Unplanned
- Helping Plugins Team to figure out with Buildah inside K8s plugin https://github.com/eclipse/che/issues/15035
- [x] Release Che Theia 7.9.1 https://github.com/eclipse/che/issues/16129
- [x] Replace deprecated extensions with VS Code builtins https://github.com/eclipse/che/issues/16133
- helping Nick to figure out with the failed CRW build https://issues.redhat.com/browse/CRW-659
- figuring out a root cause of https://issues.redhat.com/browse/CRW-657
- [x] Adapt che-theia for theia changes to prevent a failed build https://github.com/eclipse/che/issues/16149

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Artem | 14  | 8
| Roman   | 13  | 8
| Vlad   | 12  | 7

---
[Previous Sprint](https://github.com/eclipse/che/issues/15902)
