### ISSUE TITLE
Che 7.9.1 Release

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16129]
### List of pending issues / PRs

- [x] [theia] About dialog is broken #15962 - https://issues.redhat.com/browse/CRW-674 -> https://github.com/eclipse/che-theia/commit/13070ca81030fbcc7f6678eeb6c66d8f49b5b62c
- [x] [controller] Fix the get starting page title #16136 - blocks ["Getting Started with Eclipse Che" on CRW getting started page CRW-654](https://issues.redhat.com/browse/CRW-654)
- [x] Rework che-theia branding to provide logo icon for plugin webview #15324
- [x] Activate terminal search 635 - https://github.com/eclipse/che-theia/pull/635 - blocks [Unable to do any actions in the terminal inside of workspace CRW-657](https://issues.redhat.com/browse/CRW-657)
- [x] Devfile not found when factory constructed with .git suffix https://github.com/eclipse/che/issues/16109  https://issues.redhat.com/browse/CRW-645 https://github.com/eclipse/che/pull/16123
- [x] Incorrect icon used for mainframe basic stack: https://github.com/eclipse/che/issues/16164, PR https://github.com/eclipse/che-devfile-registry/pull/202
- [x] "Add Workspace" button is missing after overriding UD product.json #16174 / https://github.com/eclipse/che/pull/16175
- [x] [Hosted Che] permission denied while creating volume path during workspace startup against 7.9.0-SNAPSHOT version #16112.  https://github.com/eclipse/che-jwtproxy/pull/19 https://github.com/eclipse/che-jwtproxy/pull/18 https://github.com/eclipse/che/pull/16128
- [x] [CRW] bring the rhel dockerfile of jwtproxy in line with upstream https://github.com/eclipse/che-jwtproxy/pull/21
- [x] Apply OpenShift OAuth provider #15963
- [x] Workspace stop time increased sufficiently after the 7.9.0 update #16200  https://github.com/eclipse/che/pull/16207
- [x]  [che-server] Json PRC performance has the tendency to degrade  https://github.com/eclipse/che/issues/16145 https://github.com/eclipse/che/pull/16148
- [x] [Hosted che] Not able to run workspace via devfile link ('f?url' parameter) #16218 / https://github.com/eclipse/che/pull/16223
- [x] LS for default PHP stacks not working #16196
- [ ] *(add blockers to 7.9.2: https://github.com/eclipse/che/issues/16229)*

### Release status

In parallel, the following releases can be done:

* che-theia,
* che-machine-exec,
* che-devfile registry, then che-plugin-registry (once che-theia and machine-exec are done)
* che-parent, then che-docs, then che as Release Candidate for QE

Then in series:

* che-parent, then che-docs, then che as Release
* che-operator, then chectl

- [x] che-theia  _*(1eaecd5cbf93468a74988ddcd347402fcbf14cbe)*_
- [x] che-machine-exec
- [x] che-plugin-registry _(depends on che-theia, che-machine-exec)_
- [x] che-devfile-registry
- [x] che-parent
- [x] che-docs _(depends on parent)_
- [x] che _(depends on docs and parent)_
- [x] che-operator _(depends on all of the above)_
  - ~~[ ] Kubernetes community operator PR~~
  - ~~[ ] OpenShift community operator PR~~
- [x] chectl _(depends on all of the above)_

| Owner | Process | Script | CI | Artifact(s) |
| --- | --- | --- | --- | --- |
| @azatsarynnyy| [che-theia](https://github.com/eclipse/che-theia/blob/master/RELEASE.md) | [***MANUAL***](https://github.com/eclipse/che-theia/blob/master/RELEASE.md) | [centos](https://ci.centos.org/job/devtools-che-theia-che-release/) | [`quay.io/eclipse/che-theia`](https://quay.io/eclipse/che-theia) |
| @nickboldt| [che-machine-exec](https://github.com/eclipse/che-machine-exec/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-machine-exec/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-machine-exec-release/) | [`quay.io/eclipse/che-machine-exec`](https://quay.io/eclipse/che-machine-exec)| 
| @nickboldt| [che-devfile-registry](https://github.com/eclipse/che-devfile-registry/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-devfile-registry/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-devfile-registry-release/) | [`quay.io/eclipse/che-devfile-registry`](https://quay.io/eclipse/che-devfile-registry)| 
| @nickboldt / @ericwill| [che-plugin-registry](https://github.com/eclipse/che-plugin-registry/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-plugin-registry/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-plugin-registry-release/) | [`quay.io/eclipse/che-plugin-registry`](https://quay.io/eclipse/che-plugin-registry)| 
| @vparfonov / @mkuznyetsov| [che-parent](https://github.com/eclipse/che/blob/master/RELEASE.md) | [***MANUAL***](https://github.com/eclipse/che/blob/master/RELEASE.md) | [centos](https://ci.centos.org/job/devtools-che-parent-che-release/) | [che-parent](https://search.maven.org/search?q=a:che-parent), [che.depmgt](https://search.maven.org/artifact/org.eclipse.che.depmgt/maven-depmgt-pom) |
| @vparfonov / @mkuznyetsov| [che-docs](https://github.com/eclipse/che/blob/master/RELEASE.md) | [***MANUAL***](https://github.com/eclipse/che/blob/master/RELEASE.md) | [centos](https://ci.centos.org/job/devtools-che-docs-che-release/) | [che-docs](https://search.maven.org/search?q=a:che-docs)
| @vparfonov / @mkuznyetsov| [che](https://github.com/eclipse/che/blob/master/RELEASE.md) | [***MANUAL***](https://github.com/eclipse/che/blob/master/RELEASE.md) | [centos](https://ci.centos.org/job/devtools-che-che-release/) | [che.core](https://search.maven.org/search?q=che.core), [`quay.io/eclipse/che-server`](https://quay.io/eclipse/che-server) |
| @tolusha| [che-operator](https://github.com/eclipse/che-operator/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-operator/blob/master/make-release.sh) | ? | [`quay.io/eclipse/che-operator`](https://quay.io/eclipse/che-operator)| 
| @tolusha| [chectl](https://github.com/che-incubator/chectl/blob/master/RELEASE.md) | [make-release.sh](https://github.com/che-incubator/chectl/blob/master/make-release.sh) | [travis](https://travis-ci.org/che-incubator/chectl) | [chectl releases](https://github.com/che-incubator/chectl/releases)

**Comment by nickboldt** [comment]
@azatsarynnyy please merge/cherrypick https://github.com/eclipse/che-theia/pull/628 into 7.9.x branch so it's part of 7.9.1 release. Fixing it in master & not backporting will not get it into this release. :)

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy please merge/cherrypick [eclipse/che-theia#628](https://github.com/eclipse/che-theia/pull/628) into 7.9.x branch so it's part of 7.9.1 release. Fixing it in master & not backporting will not get it into this release. :)

Thanks @nickboldt !
I just misunderstood the list :slightly_smiling_face:

**Comment by ibuziuk** [comment]
Folks, I want to add also - https://github.com/eclipse/che/issues/16174 to 7.9.1 list

**Comment by azatsarynnyy** [comment]
che-theia has been released

**Comment by nickboldt** [comment]
Can we unrelease (untag) 7.9.1 to add fix for https://github.com/eclipse/che/issues/15962 ? 

We should coordinate when to start the release so all components release in order when we're ready.

**Comment by azatsarynnyy** [comment]
we're working on #15962 
so, let's untag 7.9.1
Thanks!

**Comment by ibuziuk** [comment]
Issues that should be considered to be included in `7.9.1`:
- Workspace stop time increased sufficiently after the 7.9.0 update #16200
- LS for default PHP stacks not working #16196

**Comment by nickboldt** [comment]
7.9.1 tags removed from 3 repos in quay and upstream GH repo. 

Onward to 7.9.1!

**Comment by nickboldt** [comment]
FYI we're going to start the Che 7.9.1 release tomorrow Wed morning @ 0900 EST / 1500 CEST / 1600 EEST, beginning with che-theia as usual. 

If everything above is not included by that time, items will slip to 7.9.2, scheduled after 7.10

**Comment by nickboldt** [comment]
I've removed the 4 incomplete issue and moved them to https://github.com/eclipse/che/issues/16229 for 7.9.2 followup release.

Meanwhile these are done:

* che-theia
* che-machine-exec
* che-devfile-registry
* che-plugin-registry (thanks, @ericwill )

Waiting on @vparfonov for the next 3 releases...

**Comment by ibuziuk** [comment]
che-parent, che-doc, che `7.9.1` have been released - artifacts are available on central

**Comment by nickboldt** [comment]
I don't see Che 7.9.1 on https://quay.io/repository/eclipse/che-server?tag=latest&tab=tags and also not in https://search.maven.org/search?q=che.core

**Comment by vparfonov** [comment]
> I don't see Che 7.9.1 on https://quay.io/repository/eclipse/che-server?tag=7.9.1&tab=tags
> 
> But che-docs, che-parent, and https://search.maven.org/search?q=che.core are done.

Images pushed

**Comment by tolusha** [comment]
`che-operator` released without community operator PRs
`chectl` released
