### ISSUE TITLE
Che Deploy Sprint #181

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16237]
Mar 11 - Mar 31

### Team
| Name  |  |
| ------------- | ------------- |
| Anatolii   |   |
| Mykola   |    |
| Aleksandr  |   |

### Issues
- [x] Eclipse Che pod bootstrap timeout on chectl install, when using Che operator with TLS and unsigned certificate on non-OpenShift kube https://github.com/eclipse/che/issues/16280
  - [x] https://github.com/eclipse/che-operator/pull/191
  - [x] https://github.com/che-incubator/chectl/pull/576
  - [x] https://github.com/eclipse/che-operator/pull/194
  - [x] https://github.com/eclipse/che-docs/pull/1137
- [x] Assessing the current status of repositories where deploy team is responsible for
  - [x] https://github.com/che-incubator/chectl/pull/583
  - [x] https://github.com/che-incubator/chectl/pull/585
  - [x] https://github.com/eclipse/che-machine-exec/pull/86
- [x] Store credentials into secrets instead of plain text of CheCluster CR fields https://github.com/eclipse/che/issues/16243
  - [x] https://github.com/eclipse/che-operator/pull/198
- [x] [che-operator] Set up image digest on released version of CSV https://github.com/eclipse/che/issues/16228
  - [x] https://github.com/eclipse/che-operator/pull/202
- [ ] Create a job to download images into cluster nodes for offline mode https://github.com/eclipse/che/issues/16221
- [x] chectl workspace:list command presents TypeError: Expected property `task` to be of type `function`, got `undefined` https://github.com/eclipse/che/issues/15071
  - [x] https://github.com/che-incubator/chectl/pull/574
- [x] Add workspace:delete command to delete user's workspace https://github.com/eclipse/che/issues/16236
  - [x] https://github.com/che-incubator/chectl/pull/586
- [ ] [chectl] Be more specific in the help about the --domain option https://github.com/eclipse/che/issues/14404
- [x] CloudShell should provide an option to use users token instead of SA's one 
 https://github.com/eclipse/che/issues/16250
  - [x] https://github.com/eclipse/che-go-jsonrpc/pull/3
  - [x] https://github.com/eclipse/che-machine-exec/pull/85
- [ ] Enable chectl to install Che through OLM when appropriate https://github.com/eclipse/che/issues/15279
- [x] Provide decent error message when the operator is missing cluster permissions https://github.com/eclipse/che/issues/15345
  - [x] https://github.com/eclipse/che-operator/pull/208
- [ ] Refactor the operator `reconcile` method to make it non-blocking https://github.com/eclipse/che/issues/15127
  - [ ] https://github.com/eclipse/che-operator/pull/212
- [x] [che-operator] Duplicate Dockerfile to `build` directory https://github.com/eclipse/che/issues/16206 
  - [x] https://github.com/eclipse/che-operator/pull/204
- [x] chectl: deprecate an ability to start workspace with workspace config https://github.com/eclipse/che/issues/15061
  - [x] https://github.com/che-incubator/chectl/pull/578
- [x] [chectl] chectl workspace verb `start` is misleading https://github.com/eclipse/che/issues/14344
  - [x] https://github.com/che-incubator/chectl/pull/592
- [x] release 7.9.2
- [x] release 7.10.0

### PRs to merge
- [x] https://github.com/che-incubator/chectl/pulls
- [ ] [che-operator] - serviceaccount permissions for <username>-che as default namespace https://github.com/eclipse/che/issues/15493
  - [ ] https://github.com/eclipse/che-operator/pull/156/files
- [x] Che operator should support single-user Che https://github.com/eclipse/che/issues/13420
  - [x] https://github.com/eclipse/che-operator/pull/185
  - [x] https://github.com/che-incubator/chectl/pull/573

## Unplanned
- [x] Fix import of zip project in case the archive is hosted on the same cluster which uses self-signed certificate https://github.com/eclipse/che-theia/pull/672
- [x] [che-operator] Port changes from 7.9.x to 7.10.0 https://github.com/eclipse/che-operator/pull/201
- [x] Added basic TLS configuration checks
- [x] How to run Che on Openshift 3.11 in a local network https://github.com/eclipse/che/issues/16417

 [Previous Sprint](https://github.com/eclipse/che/issues/16049)
