### ISSUE TITLE
Minimal Safari Support

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#16306]
### Is your task related to a problem? Please describe.
Eclipse Che is validated on Google Chrome and there is also minimal Firefox support - https://github.com/eclipse/che/issues/14015. However, it would be also great to provide support for other web browsers.

The goal of this epic is to analyze and detail the requirements for providing minimal support for Safari - https://www.apple.com/safari/

Related issues:

- [x] Authorization token is missed error after login on Safari Version 12.0 (14606.1.36.1.9) #11817
- [ ] Can't load Theia IDE on Safari because since CORS error happened https://github.com/eclipse/che/issues/16335
- [ ] Cookies are not sent to Theia server to non-root path on Safari https://github.com/eclipse/che/issues/16350
- [ ] Failed to request branding data by URL https://github.com/eclipse/che/issues/19696
