### ISSUE TITLE
Editors Sprint 181

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16312]
Mar 11 - Mar 31

## Goals
1. Finalize Theia WebView support
2. Restore publishing npm packages during CI build
3. Fix Che Theia issues critical for dogfooding
4. Che Theia build compatible with the latest yarn
5. Theia upstream focus
6. Che Theia release

## Tasks
- [ ] Theia hotkeys aren't handled when a WebView is in focus https://github.com/eclipse/che/issues/15763
- [x] Publish npm packages on npmjs.org during CI build https://github.com/eclipse/che/issues/15887
- [x] Che Theia 7.9.2 release https://github.com/eclipse/che/issues/16229
- [x] Che Theia 7.11.0 release https://github.com/eclipse/che/issues/16478

#### Dogfooding
- [x] Che Theia doesn't inform Che Master about activity in a Workspace when https with the self-signed cert is used https://github.com/eclipse/che/issues/15991
- [x] Update Che Dogfooding Scoreboard spreadsheet with the current state for assessing the current status

#### Che Theia build compatible with the latest yarn
- [x] Invalid bin entry for `theia:plugin` in `@theia/plugin-packager` https://github.com/eclipse/theia-plugin-packager/issues/8
- [x] Yarn 1.21.1 support in build che related projects https://github.com/eclipse/che/issues/15771

#### Other issues
- [ ] Improve `che:theia production` command to correctly repack Theia dependencies https://github.com/eclipse/che/issues/15748
- [x] Improve Che Theia release script https://github.com/eclipse/che/issues/16301
- [x] Support Codicons in Command Palette https://github.com/eclipse/che/issues/15262 (depends on Monaco upgrade)

#### Monaco upgrade
- [x] Merged the PR https://github.com/eclipse-theia/theia/pull/7149 (Upgrade to LSP 6.0.0 and Monaco 0.19.3) that finalizes upgrade to the latest Monaco https://github.com/eclipse-theia/theia/issues/6900

Other issues also fixed by Monaco upgrade:
- [x] Scrolling in Editor is Slow in Firefox https://github.com/eclipse-theia/theia/issues/7039
- [x] Support Octicons in the quick pick items https://github.com/eclipse-theia/theia/issues/5412

- Discussion about the ways of improving Monaco upgrade process https://github.com/eclipse-theia/theia/issues/7457

#### PRs reviewed:
- https://github.com/eclipse-theia/theia/pull/7260#pullrequestreview-373175001
- https://github.com/eclipse-theia/theia/pull/7303#pullrequestreview-372672233
- https://github.com/eclipse-theia/theia/pull/7392#pullrequestreview-380520169
- https://github.com/eclipse-theia/theia/pull/7265

#### Participating in the issues:
- opened https://github.com/eclipse-theia/theia/issues/7323
- opened https://github.com/eclipse-theia/theia/issues/7395
- opened https://github.com/eclipse-theia/theia/issues/7429
- opened https://github.com/eclipse-theia/theia/issues/7368
- opened https://github.com/microsoft/vscode/issues/93303

### Unplanned/Blockers
- [x] Che Theia white-labeling capabilities don't work in the previous Chrome versions https://github.com/eclipse/che/issues/16392
- [x] Adapt changes in che-theia to respect changes in upstream theia https://github.com/eclipse/che/issues/16393
- [x] Che Theia remote plugins aren't started https://github.com/eclipse/che/issues/16412
- [x] Che Theia can't reach Che plugin registry behind the proxy with TLS support https://github.com/eclipse/che/issues/16482, [CRW-720](https://issues.redhat.com/browse/CRW-720?focusedCommentId=14010285&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14010285)
- [x] Che Theia build is broken due to upstream Theia changes https://github.com/eclipse/che/issues/16469

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 13  | 8
| Roman   | 13  | 8
| Artem | 14  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/16086)
