### ISSUE TITLE
Plugins Sprint 181

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16336]
## Sprint goals
1. Welcome new members into the team
2. Continue to support our epics
    * OpenShift and GitHub integration
    * Plugin stacks automation
    * Integrate previous Languages team work into our sprint
    * Important CRW issues
3. Bugs
4. Maintenance / Automation / Technical Debt

### Blockers / Unplanned Issues / Regressions
* [x] Theia cannot reach the API server with both TLS and proxy enabled #16356

### Epics
**Epic: OpenShift Connector for Eclipse Che #14900**
* [ ] Configure OpenShift oAuth client for the OpenShift oAuth provider by operator https://github.com/eclipse/che/issues/16199
* [ ] Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270

**Epic: Git + SSH flow #13494**
* [ ] Improve login procedure for GitHub PullRequest Plugin #14217 @vinokurig
    * [ ] [Plugin-Api] Apply window.registerUriHandler() function eclipse-theia/theia#5119 @vinokurig

**Epic: Document Airgap Scenarios #15351**
* [ ] Collect Air-Gapping Documentation #16074 @tsmaeder
* [ ] Implement Airgapped Configuration Mechanism #15518 timebox for design @tsmaeder

**Epic: Rethink/rework the Che workspace with workspace-roots #15529**
* [ ] Support Che tasks for multi-root workspaces #15540 @tsmaeder 

**Epic: Check extensions of VS Code extension pack are running smoothly #15390**
* [ ] Check individual extensions to make sure they work in Che @ericwill 
    * [x] Check Python extensions -- make sure workspace starts/runs
    * [ ] Build Python sidecar container with deps to test functionality

### CRW
* [ ] CRW 2.1 devfiles [CRW-402](https://issues.redhat.com/browse/CRW-402)
    * [ ] Improve naming of the default stacks [CRW-521](https://issues.redhat.com/browse/CRW-521)
    * [ ] CRW 2.1 Improved code samples for default devfiles [CRW-412](https://issues.redhat.com/browse/CRW-412) @svor
      * [x] Java Gradle 1.5
      * [x] Java Maven 1.5
      * [x] NodeJS 1.5
      * [ ] Golang 1.5
      * [ ] .Net 1.5
* [x] Failed to install dependencies in the "Cake PHP" workspace [CRW-762](https://issues.redhat.com/browse/CRW-762) @svor
* [x] The "npm: debug" preinstalled command doesn't work in the "NodeJS MongoDB" devfile [CRW-725](https://issues.redhat.com/browse/CRW-725) @svor
* [x]  Can't start debug session in the "Java EAP Maven" devfile [CRW-724](https://issues.redhat.com/browse/CRW-724) @svor 
* [x] The "NodeJs ConfigMap" devfile failed to start [CRW-746](https://issues.redhat.com/browse/CRW-746)
* [x]  No command for running and debugging sample in the default "Cake PHP" devfile [CRW-723](https://issues.redhat.com/browse/CRW-723) @svor 
* [x] Theia cannot reach the API server with both TLS and proxy enabled [CRW-720](https://issues.redhat.com/browse/CRW-720)
* [x] Embeded sample in the ".NET" devfile exposes wrong URL [CRW-717](https://issues.redhat.com/browse/CRW-717) @svor
* [x] The "PHP" language server doesn't work in the workspace based on "Cake PHP" devfile [CRW-702](https://issues.redhat.com/browse/CRW-702) @svor 
* [x] Replace "Java EE" with "Jakarta EE" in kitchensink example [CRW-696](https://issues.redhat.com/browse/CRW-696) @svor
* [x] Java language server failed to start [CRW-691](https://issues.redhat.com/browse/CRW-691) @svor 
* [x] Debug can't catch Java application with Quarkus Dev mode intermediately [CRW-685](https://issues.redhat.com/browse/CRW-685)
* [x] Add a camel-k sample in out-of-the-box devfiles [CRW-609](https://issues.redhat.com/browse/CRW-609) @svor
    * [x] Investigate the issue further
* [ ] Red Hat CodeReady Workspaces / Eclipse Che Support for EAP 7.3 [CRW-340](https://issues.redhat.com/browse/CRW-340) @svor
    * [ ] Including testing updated image with devfiles.

### Bugs
* [x] Task install dependencies failing in PHP Symfony #15854 @ericwill 
* [x] Go devfile LS Not working without updating Go language server plugin to the experimental version. #16113 @ericwill 
* [ ] Allow multiple plugin registries to be added to che #16258 
* [ ] Created file/folder should be selected eclipse-theia/theia#6190
* [ ] Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side. #15277 @vitaliy-guliy
    * [x] Investigate on che-theia and benchmark timing
    * [ ] Use results of investigation to discuss architectural design of running tasks
* [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins #14119 @ericwill
    * [x] Land on solution for che-dockerfiles layout and start implementing it

### Open PRs From Last Sprint
* [ ] Openshift connector and Che: openshift user should be logged automatically with the Openshift user. #15261 @vinokurig
    * [ ] Respond to and implement feedback from sprint review
* [x] Update icon for Kubernetes plugin https://github.com/eclipse/che-plugin-registry/pull/422 @vitaliy-guliy

### Maintenance / Automation / Technical Debt / Reviews
* [x] Integrate dependabot into more che-dockerfiles repos @ericwill
* [ ] Upgrade forked vscode-git to the latest version #16041 @ericwill
    * [x] theia git extension [publish branch] "permission denied" in askpass.sh #16084 
    * [ ] Check update and build extension properly (no repository found issue)

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 14  | 8 |
| @ericwill | 14  | 8 |
| @tsmaeder | 14 | 8 |
| @svor | 14 | 8 |

**Comment by ericwill** [comment]
Superseded by sprint 182, #16513
