### ISSUE TITLE
Che Deploy Sprint #182

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16455]
Apr 1 - Apr 21

### Team
| Name  |  |
| ------------- | ------------- |
| Anatolii   |   |
| Mykola   |    |
| Aleksandr  |   |

### Issues
- [x] .7.9.3 Release https://github.com/eclipse/che/issues/16620 
- [x] .release 7.11.0 https://github.com/eclipse/che/issues/16478
  - [x] https://github.com/eclipse/che-operator/pull/215
  - [x] https://github.com/operator-framework/community-operators/pull/1513
  - [x] https://github.com/operator-framework/community-operators/pull/1514
  - [x] https://github.com/che-incubator/chectl/pull/626
- [ ] .Implement TLS by default for operator Che installer https://github.com/eclipse/che/issues/16052
  - [ ] https://github.com/eclipse/che-operator/pull/220
  - [x] https://github.com/eclipse/che-operator/pull/221
- [x] .Create a job to download images into cluster nodes for offline mode https://github.com/eclipse/che/issues/16221
  - [x] https://github.com/che-incubator/chectl/commit/979759796ae0759de4edd311f0fb146a1c263c4a
- [x] .Cloud shell must propagate error when it failed to initialize terminal  https://github.com/eclipse/che/issues/16249
  - [x] https://github.com/eclipse/che-machine-exec/pull/89
- [x] .Prepare devfile for `che-operator` repository https://github.com/eclipse/che/issues/16454
  - [x] https://github.com/eclipse/che-operator/pull/222
- [x] .[chectl] Be more specific in the help about the --domain option https://github.com/eclipse/che/issues/14404
  - [x] https://github.com/che-incubator/chectl/pull/613
  - [x] https://github.com/che-incubator/chectl/pull/615
- [x] .`chectl update next` does not work as expected https://github.com/eclipse/che/issues/16423
  - [x] https://github.com/che-incubator/chectl/pull/620
  - [x] https://github.com/che-incubator/chectl/pull/623
- [x] .chectl releases aren't properly sorted https://github.com/eclipse/che/issues/16374
  - [x] https://github.com/che-incubator/chectl/pull/614
- [x] .[release process] Ensure operator yamls and test defaults are updated for each release https://github.com/eclipse/che/issues/16371 
- [x] .Chrome browser doesn't accept generated by instructions from Che docs self-signed certificate https://github.com/eclipse/che/issues/16366
  - [x] https://github.com/eclipse/che-docs/pull/1175
- [x] .[chectl] - offer to run workspace in debug mode https://github.com/eclipse/che/issues/16119
  - [x] https://github.com/che-incubator/chectl/pull/621
- [ ] ~~[Chectl] support exported kubeconfigs when installing~~ https://github.com/eclipse/che/issues/15741
  - [x] https://github.com/che-incubator/chectl/pull/647
- [x] .chectl must duplicate required manual actions after deploying 
 https://github.com/eclipse/che/issues/16277
  - [x] https://github.com/che-incubator/chectl/pull/619
- [x] .chectl workspace:inject no more finding default workspace pod https://github.com/eclipse/che/issues/16019
  - [x] https://github.com/che-incubator/chectl/pull/639

### PRs to merge
- [x] https://github.com/che-incubator/chectl/pulls
- [ ] Add method to determine if operation under k8s resource is permitted  https://github.com/eclipse/che-operator/pull/209
- [x] ~~Test route url fix https://github.com/eclipse/che-operator/pull/66~~
- [ ] Fix starting multiple che instances in the same cluster https://github.com/che-incubator/chectl/pull/598
- [x] .Refactor the operator `reconcile` method to make it non-blocking https://github.com/eclipse/che/issues/15127
  - [x] https://github.com/eclipse/che-operator/pull/212
- [ ] .Enable chectl to install Che through OLM when appropriate https://github.com/eclipse/che/issues/15279
  - [ ] https://github.com/che-incubator/chectl/pull/611

## Unplanned
- [x] Reusing domain on server:update https://github.com/che-incubator/chectl/pull/632

 [Previous Sprint](https://github.com/eclipse/che/issues/16237)
