### ISSUE TITLE
Automate Che Release Process

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16499]
### Is your enhancement related to a problem? Please describe.

Starting with Che 7.12, we plan to release all the pieces of a Che release via a single script/job.

### Describe the solution you'd like

on push of an updated VERSION file to the release branch of https://github.com/eclipse/che-release, a cico job will be triggered on CentOS CI.

This job will release all the pieces of Che currently orchestrated by a handful of humans in an issue such as https://github.com/eclipse/che/issues/16478

When done, an email announcing the release will be sent to che-dev@ list.

### Related issues / subtasks

* Che server and dependencies
- [x] Automate pushing Che releases to Maven Central #16043

* Plugin registry
- [x] When doing maintenance releases, ensure that new plugins are added to both .x and master branches #16476
- [x] Ensure new orchestration script includes plugin-registry specific steps in https://github.com/eclipse/che-plugin-registry/blob/master/make-release.sh#L59-L76

* Missing automation steps (che-theia, che-operator)
- [x] convert https://github.com/eclipse/che-theia/blob/master/RELEASE.md into a non-interactive script https://github.com/eclipse/che/issues/16523
- [x] Script generation of che-operator PRs for operatorhub #16500

**Comment by azatsarynnyy** [comment]
added the link to https://github.com/eclipse/che/issues/16523

**Comment by nickboldt** [comment]
mostly done so resolving. 
- [ ] Verify that plugin images referenced in the plugin registry actually exist in Quay #16501 (moved to link under #17101 )
