### ISSUE TITLE
Plugins Sprint 182

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16513]
## Sprint goals
1. Continue to support our epics
    * OpenShift and GitHub integration
    * Supporting multiple plugin registries
    * Tasks in multi-root workspaces
    * Important CRW issues
    * Che dogfooding
2. Bugs
3. Maintenance / Automation / Technical Debt

### Epics
**Epic: OpenShift Connector for Eclipse Che #14900**
* [x] Openshift connector and Che: openshift user should be logged automatically with the Openshift user. #15261 @vinokurig 
    * [x] Apply web application that can make authentication requests with user token #16488
    * [x] Add an ability to update request headers #30
/che/pull/16383
* [x] Configure OpenShift oAuth client for the OpenShift oAuth provider by operator https://github.com/eclipse/che/issues/16199
* [ ] Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270

**Epic: Git + SSH flow #13494**
* [ ] Improve login procedure for GitHub PullRequest Plugin #14217 @vinokurig 
    * [ ] [Plugin-Api] Apply window.registerUriHandler() function eclipse-theia/theia#5119

**Epic: Document Airgap Scenarios #15351**
* [x] Collect Air-Gapping Documentation #16074
* [x] Implement Airgapped Configuration Mechanism #15518 timebox for design

**Epic: Rethink/rework the Che workspace with workspace-roots #15529**
* [ ] Support Che tasks for multi-root workspaces #15540 @tsmaeder 
    * [x] Support User Level Tasks eclipse-theia/theia#7446

**Epic: Check extensions of VS Code extension pack are running smoothly #15390**
* [ ] Check individual extensions to make sure they work in Che
    * [ ] Installing Java Test Runner Support for Java #14871 @ericwill 
    * [ ] Build Python sidecar container with deps to test functionality

**Epic: Che Dogfooding**
* [ ] Plugins projects @vitaliy-guliy 
    * [ ] che-plugin-registry
    * [ ] che-theia plugins
    * [x] Kubernetes tooling
    * [ ] OpenShift connector

### CRW
* [x] CRW 2.2 Improved code samples for default devfiles [CRW-740](https://issues.redhat.com/browse/CRW-740) @svor 
    * [x] Improve naming of the default stacks [CRW-521](https://issues.redhat.com/browse/CRW-521)
    * [x] Golang 1.5
    * [ ] .Net 1.5
    * [x] C++
    * [x] PHP
* [x] Debug configuration doesn't appear in the Go workspace [CRW-764](https://issues.redhat.com/browse/CRW-764) @svor 
* [ ] No debug configuration in the "Node JS Config Map" devfile [CRW-791](https://issues.redhat.com/browse/CRW-791)
* [ ] Debugging of the current file failed to start in the "Go" devfile [CRW-779](https://issues.redhat.com/browse/CRW-779)
* [ ] Error highlighting doesn't work in the "Go" devfile [CRW-778](https://issues.redhat.com/browse/CRW-778)

### Bugs
* [ ] Importing devfile with private repo fails #16401 @svor 
* [x] Allow multiple plugin registries to be added to che #16258  @ericwill 
    * [x] Investigate the issue
    * [x] Leave comment for other contributors to pick up the work more easily
* [ ] Use digests instead of tags to reference images #16047 @vitaliy-guliy 
    * [ ] che-dockerfiles as proof of concept
    * [ ] che-plugin-registry proof of concept
* [ ] Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side. #15277
    * [x] Discuss architectural changes needed to fix the issue @vitaliy-guliy 
* [ ] Created file/folder should be selected eclipse-theia/theia#6190
* [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins #14119

### Unplanned
* [x] Theia Plugin Manager does not work properly with a minimal devfile #16519 @vitaliy-guliy 
* [x] Git clone using private key with password is not working #16517 @vinokurig 
* [x] Upgrade vscode-xml to 0.11.0 #16615

### Maintenance / Automation / Technical Debt / Reviews
* [ ] Upgrade forked vscode-git to the latest version #16041
    * [ ] Check update and build extension properly (no repository found issue)
* [ ] Re-layout che-dockerfiles repos to agreed upon structure @ericwill 
* [ ] Integrate dependabot automation into che-dockerfiles repos once layout has changed @ericwill 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 13  | 8 |
| @ericwill | 12  | 7 |
| @tsmaeder | 11.5 | 7 |
| @svor | 13 | 8 |

**Comment by ericwill** [comment]
Superseded by sprint 183, #16717
