### ISSUE TITLE
Editors Sprint 182

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16521]
Apr 1 - Apr 21

## Goals
1. Improve Tasks UX
2. Theia Plugin API
3. Dogfooding
4. Che Theia release automation
5. Theia upstream focus
6. Bugs

#### Improve Task UX
- [x] Adapt tasks to upstream changes (output isn't displayed for some tasks) https://github.com/eclipse/che/issues/16331
- [ ] Create a terminal widget immediately at running task https://github.com/eclipse-theia/theia/pull/7108 - Update and finalize the PR
- [ ] Experiment how creating a terminal widget asynchronously may help to solve the instant feedback issue https://github.com/eclipse/che/issues/15277

#### Theia Plugin API
- [x] Implement SelectionRange API https://github.com/eclipse-theia/theia/issues/6623

#### Dogfooding
- [ ] Create Che Devfile for Eclipse Theia https://github.com/eclipse/che/issues/16522

#### Che Theia release automation
- [x] Make Che Theia release script non-interactive to use it within the [automated Che release process](https://github.com/eclipse/che/issues/16499) https://github.com/eclipse/che/issues/16523

#### Bugs
- [x] Search behaves differently than it used to (and compared to VS code) https://github.com/eclipse-theia/theia/issues/7460
- [x] Plugins view is empty in Che Theia https://github.com/eclipse/che/issues/16452
- [x] Theia hotkeys aren't handled when a WebView is in focus https://github.com/eclipse/che/issues/15763

#### PRs reviewed:
```
https://github.com/eclipse-theia/theia/pull/7481#pullrequestreview-386675869
https://github.com/eclipse-theia/theia/pull/7452#pullrequestreview-387113500
https://github.com/eclipse-theia/theia/pull/7454#pullrequestreview-386124160
https://github.com/eclipse-theia/theia/pull/7485#pullrequestreview-386315214
https://github.com/eclipse-theia/theia/pull/7506#pullrequestreview-388340435
https://github.com/eclipse-theia/theia/pull/7508
https://github.com/eclipse-theia/theia/pull/7548#pullrequestreview-392925449
https://github.com/eclipse-theia/theia/pull/7574#pullrequestreview-394641821
https://github.com/eclipse-theia/theia/pull/7592#pullrequestreview-394758976
```

#### Participating in the issues:
```
https://github.com/eclipse-theia/theia/issues/7462
https://github.com/eclipse-theia/theia/issues/7612
https://github.com/eclipse-theia/theia/issues/7611
```

### Unplanned/Blockers
- [x] Upgrade some versions for che-theia https://github.com/eclipse/che/issues/16552
- [x] Adapt Che Theia to the latest Theia https://github.com/eclipse/che/issues/16611
- [x] Che Theia 7.9.3 release https://github.com/eclipse/che/issues/16620

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 12  | 7
| Roman   | 12  | 7
| Artem | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/16312)
