### ISSUE TITLE
Dashboard Next

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#16628]
This epic is about implementing the required functionality of Dashboard Next.

### Dashboard UI/UX

- [x] Develop layout of Dashboard Next https://github.com/eclipse/che/issues/16643

#### Get Started Tab https://github.com/eclipse/che/issues/16709

- [x] Support of multiple devfiles registries
- [x] Temporary storage toggle
- [x] Filter samples by name, description

#### Custom Workspace Tab https://github.com/eclipse/che/issues/16693

- [x] Create workspace by URL to a devfile 
- [x] Create workspace by devfile content
- [x] Temporary storage toggle
- [x] Kubernetes namespace selector

### Workspace Details Page
- [x] Implement Overview of the Workspace Details page https://github.com/eclipse/che/issues/16645
- [x] Implement Devfile tab on the Workspace Details https://github.com/eclipse/che/issues/17971
- [x] Add Actions for the WorkspaceDetails page https://github.com/eclipse/che/issues/18013

### Factory flow

- [x] Create workspace with url on dashboard `f?url=(github repo or direct URL to devfile yaml content)` https://github.com/eclipse/che/issues/16644

### SelfSigned TLS error pages

- [x] Error page when failed to load keycloak https://github.com/eclipse/che/issues/18098

### Recent workspaces

- [x] Limited list of recently opened workspaces(sorting by the runtime and last update) https://github.com/eclipse/che/issues/17452

### Workspaces list 
- [x] Redesign the workspace list https://github.com/eclipse/che/issues/16646

### Build/Deploy

- [x] Implement an ability to run dashboard-next along with Che Server https://github.com/eclipse/che/issues/16688
- [x] setup repository in `che-incubator`
- [x] setup CI jobs to build artifacts

### Other

- [x] revise dependencies and create CQs https://github.com/eclipse/che/issues/17024
- [x] add license headers https://github.com/che-incubator/che-dashboard-next/pull/25
- [x] Set up release for Dashboard Next | https://github.com/eclipse/che/issues/17647
- [x] Start promoting dashboard next https://github.com/eclipse/che/issues/18348
- [x] Copy chectl login command on the Dashboard Next #18533
- [x] Prototype Container Registries on the Dashboard Next #18526

### QE
- [x] Provide unit tests for testing roadmap stage 0 #18414

### Documentations
- [x] List docs articles which references Dashboard UI #18392
- [x] Adapt documentation to Dashboard Next https://github.com/eclipse/che/issues/18518

### Start workspace

- [x] Ability to start a workspace in debug mode with "debug=true" `{CHE host}/dashboard/#/ide/admin/angular-test?debug=true` https://github.com/che-incubator/che-dashboard-next/pull/89

### SelfSigned TLS error pages

- [ ] Warning banner when failed to load plugins/devfiles list https://github.com/eclipse/che/issues/18099

### Workspace Details
- [ ] Implement Plugins/Editor tabs on the Workspace Details
- [ ] Implement Projects tab on the Workpace Details

### User preferences

- [x] Configure credentials for private docker registries (was a part of Administration menu item) https://github.com/eclipse/che/issues/18526

### Other
- [ ] An ability to patch devfile with factory URL https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#overriding-devfile-values-using-factory-parameters_configuring-a-workspace-using-a-devfile
- [x] An ability to configure workspacePod labels and annotations https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#allowing-users-to-define-workspace-deployment-labels-and-annotations_configuring-a-workspace-using-a-devfile
- [x] Moving che-dashboard-next into eclipse organization as a separate project https://github.com/eclipse/che/issues/17655

**Comment by sleshchenko** [comment]
I'm happy to close this epic as done since new Dashboard is promoted into Eclipse Che
