### ISSUE TITLE
Che Deploy Sprint #183

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16623]
Apr 22 - May 12

### Team
| Name  |  |
| ------------- | ------------- |
| Anatolii   |   |
| Mykola   |    |
| Aleksandr  |   |

### Issues
- [x] 7.12.0 Release https://github.com/eclipse/che/issues/16690 
  - [x] https://github.com/eclipse/che-operator/pull/228 https://github.com/che-incubator/chectl/pull/667 https://github.com/operator-framework/community-operators/pull/1641 https://github.com/operator-framework/community-operators/pull/1642
- [x] 7.12.1 Release https://github.com/eclipse/che/issues/16743
  - [x] https://github.com/eclipse/che-operator/pull/234 https://github.com/che-incubator/chectl/pull/682/ https://github.com/operator-framework/community-operators/pull/1666 https://github.com/operator-framework/community-operators/pull/1665
- [ ] 7.12.2 https://github.com/eclipse/che/issues/16820
  - [x] https://github.com/eclipse/che-operator/pull/241/ https://github.com/eclipse/che-operator/pull/243 https://github.com/che-incubator/chectl/pull/691
  - [ ] https://github.com/operator-framework/community-operators/pull/1685
  - [x] https://github.com/operator-framework/community-operators/pull/1686
- [x] .Implement automated generation of TLS secrets required for Che installation https://github.com/eclipse/che/issues/16546
  - [x] https://github.com/eclipse/che-operator/pull/220
  - [x] https://github.com/che-incubator/chectl/pull/679
- [x] .Enable chectl to install Che through OLM when appropriate https://github.com/eclipse/che/issues/15279
  - [x] https://github.com/che-incubator/chectl/pull/611
- [x] .chectl: add a command to export CA for already deployed Che https://github.com/eclipse/che/issues/16278
  - [x] https://github.com/che-incubator/chectl/pull/669
- [ ] Add offline flag to chectl server:start https://github.com/eclipse/che/issues/14699
- [x] Can not start a terminal https://github.com/eclipse/che/issues/16601
  - [x] https://github.com/eclipse/che-theia/pull/729
  - [x] https://github.com/eclipse/che-machine-exec/pull/96
- [x] ~~Helm on k8s infrastructure https://github.com/eclipse/che/issues/16545~~
- [x] ~~[chectl] Check if real user exists before deploying Eclipse Che on OpenShift cluste https://github.com/eclipse/che/issues/16629~~
- [ ] [chectl] Add `server:login` command https://github.com/eclipse/che/issues/16415
- [ ] [chectl] generate passwords for initial users https://github.com/eclipse/che/issues/14082
  - [x] https://github.com/che-incubator/chectl/pull/684
  - [x] https://github.com/che-incubator/chectl/pull/686
  - [x] https://github.com/eclipse/che/pull/16849
  - [x] https://github.com/eclipse/che-operator/pull/240
  - [ ] https://github.com/che-incubator/chectl/pull/690
- [x] .[chectl] add a command to open Che Dashboard https://github.com/eclipse/che/issues/15003
  - [x] https://github.com/che-incubator/chectl/pull/656
- [ ] [chectl] Add new server:status command https://github.com/eclipse/che/issues/14476
- [x] .[chectl] operator should be a default way to deploy Eclipse Che instead of helm https://github.com/eclipse/che/issues/16648

### CRW
- [ ] https://issues.redhat.com/browse/CRW-765
- [ ] https://issues.redhat.com/browse/CRW-640
- [ ] https://issues.redhat.com/browse/CRW-336
- [ ] https://issues.redhat.com/browse/CRW-732

### TODOs
- [x] Improve error message: `Error: Error: "che-tls" secret is found but it is invalid.`. Add steps to solve the problem.
- [x] Add link to https://www.eclipse.org/che/docs/che-7/installing-che-in-tls-mode-with-self-signed-certificates/#using-che-with-tls_installing-che-in-tls-mode-with-self-signed-certificates
- [ ] Configure bots to open workspace to review PR (chectl, che-operator, machine-exec repositories)

### PRs to merge
- [x] ~~https://github.com/che-incubator/chectl/pulls~~
- [ ] Add method to determine if operation under k8s resource is permitted  https://github.com/eclipse/che-operator/pull/209
- [ ] Fix starting multiple che instances in the same cluster https://github.com/che-incubator/chectl/pull/598
- [x] chectl e2e tests https://github.com/che-incubator/chectl/pull/678
- [ ] CHE-15493: <username>-che as default namespace https://github.com/eclipse/che-operator/pull/166

## Unplanned

- [x] Setup Che in TLS mode docs page has invalid links https://github.com/eclipse/che/issues/16682
- [x] https://github.com/che-incubator/chectl/pull/665
- [x] Update the bug template https://github.com/eclipse/che/pull/16774
- [x] Include operator image in the release process https://github.com/eclipse/che-operator/pull/238/
- [x] ~~left overs https://github.com/eclipse/che-operator/pull/230~~
- [x] Add flag to skip k8s health check https://github.com/che-incubator/chectl/pull/685/

 [Previous Sprint](https://github.com/eclipse/che/issues/16455)
