### ISSUE TITLE
Support building Che on linux on Z (s390x) and Power (ppc64le)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#16655]
Epic issue to collect all subtasks / needs for empowering Che 7.x to build on s390x and ppc64le.

Please add issues below.

- [ ] [Enhancement] Extending Eclipse Che CI infrastructure support to s390x #16287
- [ ] Ensure Che image publishing is multiarch #17124
- [x] [plugin registry support for s390x #428](https://github.com/eclipse/che-plugin-registry/pull/428)
- [x] [devfile registry suport for s390x #214](https://github.com/eclipse/che-devfile-registry/pull/214)
- [x] [feat(alpine): Change parent image to be alpine based as well #226](https://github.com/eclipse/che-devfile-registry/pull/226)
- [ ] ...

**Comment by shahidhs-ibm** [comment]
@nickboldt In order to extend support to s390x, we will need to find suitable replacement for `openjdk:8u242-jre-slim` docker image located at [https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile#L8](https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile#L8)
Following are some images which support multi-arch and can act as replacement:
- adoptopenjdk:8u232-b09-jre-hotspot
- registry.redhat.io/openjdk/openjdk-8-rhel8:latest
- openjdk:8-jre-alpine

 Kindly suggest. We have tested the above images and they work for Intel and s390x architectures. We'll create the PR after confirmation.

**Comment by benoitf** [comment]
I like openjdk:8-jre-alpine because it is really multi-arch aware
But I know @skabashnyuk is working on moving to java11 so we should switch to something working for java11 as well.

**Comment by shahidhs-ibm** [comment]
From the online resources what I learned is that OpenJDK11 on Alpine is not officially supported and there are no plans for same in future. 
Ref. [https://github.com/docker-library/openjdk/issues/403#issuecomment-614751026](https://github.com/docker-library/openjdk/issues/403#issuecomment-614751026) 
[https://github.com/docker-library/openjdk/issues/211#issuecomment-428711975](https://github.com/docker-library/openjdk/issues/211#issuecomment-428711975)

@benoitf @nickboldt WDYT? Should we keep support for OpenJDK8 till this activity is complete?

**Comment by shahidhs-ibm** [comment]
@nickboldt your input? Shall we proceed with creating the PR as per the [comment](https://github.com/eclipse/che/issues/16655#issuecomment-618452117) from Florent (openjdk:8-jre-alpine image)?

**Comment by skabashnyuk** [comment]
@shahidhs-ibm what you can suggest as java11 alternative for `Z (s390x) and Power (ppc64le)
`?

**Comment by shahidhs-ibm** [comment]
@skabashnyuk We found [openjdk:11.0.3-jre-slim](https://hub.docker.com/_/openjdk?tab=tags&page=1&name=11.0.3-jre-slim) which can serve the purpose. Also this image is Debian based which is similar to one which we are currently using for OpenJDK8. We have tested this image on `s390x` and have no issues so far. Also this image is multi-arch so should work for `ppc64le` as well.

@benoitf @nickboldt We're bit confused now on PR to raise. Should we create one with `openjdk:11.0.3-jre-slim` or with `openjdk:8-jre-alpine` as per the earlier discussion? We believe that answer to this will be based on your preferences, priority and timelines. What will you suggest?

**Comment by nickboldt** [comment]
@shahidhs-ibm To be consistent w/ other Z and P images supported by RH, we might want to consider using openj9 instead of openjdk images.

**Comment by skabashnyuk** [comment]
> we might want to consider using openj9 instead of openjdk images

@nickboldt can we start thinking about that after 7.15 and Java 11 migration?

**Comment by ghatwala** [comment]
Agree @nickboldt  - seems `openj9 ` is preferred JVM for Z/P - https://projects.eclipse.org/projects/technology.openj9 .

**Comment by ghatwala** [comment]
@nickboldt  - for `openj9` . Were u referring to adoptopenjdk's -  `OpenJDK + Eclipse OpenJ9 binaries built by AdoptOpenJDK`  present here - https://hub.docker.com/_/adoptopenjdk to be used here ?

**Comment by Prabhav-Thali** [comment]
@nickboldt @benoitf @skabashnyuk 
Since [PR#16649](https://github.com/eclipse/che/pull/16649) was merged, we observed that java11 image used for che-server does not have multi-arch support. Can it be replaced with multiarch support image?

**Comment by Prabhav-Thali** [comment]
> Since [PR#16649](https://github.com/eclipse/che/pull/16649) was merged, we observed that java11 image used for che-server does not have multi-arch support. Can it be replaced with multiarch support image?

@nickboldt @benoitf @skabashnyuk any update?

**Comment by skabashnyuk** [comment]
You right.
![Знімок екрана 2020-07-14 о 14 04 11](https://user-images.githubusercontent.com/1614429/87418779-f7d9a600-c5da-11ea-955c-7e26cc9d599d.png)
Should try to evaluate ` 11-jre-slim-stretch`?

**Comment by Prabhav-Thali** [comment]
@skabashnyuk Any plans to test this image in near future? Please let us know if you need any assistance from our side.

**Comment by bivasda1** [comment]
@nickboldt @benoitf @skabashnyuk I have tested **openjdk11:ubuntu-jre-nightly(multiarch)** with che-server  on ppc64le arch.It's working fine.
Please let us know can we proceed with this base image.

**Comment by skabashnyuk** [comment]
Can you make a pr so we can run all the tests? 
CC @l0rd @benoitf @nickboldt

**Comment by skabashnyuk** [comment]
I've tried to use  `11-jre-slim-stretch`  and the good news is che server is able to start and is able to start new workspaces.
However, I saw sam warnings that have to be studied before making a final decision.

```
15-Jul-2020 09:49:17.249 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
15-Jul-2020 09:49:17.253 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
15-Jul-2020 09:49:17.253 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
15-Jul-2020 09:49:17.253 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
```
and 
```
2020-07-15 09:50:40,575[775-kl65b-46538]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@3a9238bc] for cluster [EclipseLinkCommandChannel], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
2020-07-15 09:50:42,162[775-kl65b-57266]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@4fc29fb5] for cluster [WorkspaceLocks], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
2020-07-15 09:50:45,793[775-kl65b-56100]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@45bd7ff8] for cluster [WorkspaceStateCache], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
2020-07-15 09:51:05,483[775-kl65b-57266]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@4fc29fb5] for cluster [WorkspaceLocks], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
2020-07-15 09:51:07,751[775-kl65b-46538]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@3a9238bc] for cluster [EclipseLinkCommandChannel], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
2020-07-15 09:51:20,169[775-kl65b-56100]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@45bd7ff8] for cluster [WorkspaceStateCache], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
2020-07-15 09:51:21,641[775-kl65b-29001]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@1e243bf5] for cluster [RemoteSubscriptionChannel], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
2020-07-15 09:51:29,668[775-kl65b-57266]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@4fc29fb5] for cluster [WorkspaceLocks], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]

```

@bivasda1  @Prabhav-Thali can you take a look?

**Comment by Prabhav-Thali** [comment]
@skabashnyuk Yes, I'll test the same on s390x and provide an update.

**Comment by ghatwala** [comment]
@bivasda1  - can you please try this on ppc64le using `11-jre-slim-stretch`

**Comment by bivasda1** [comment]
@ghatwala Yes,I am testing and provide you an update

**Comment by Prabhav-Thali** [comment]
@skabashnyuk After using `openjdk:11-jre-slim-stretch ` as base image for che-server on s390x, che-server pod was up and warnings were not seen in pod logs except the ones mentioned below:
```
2020-07-16 08:36:18,384[nio-8080-exec-9]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 141]  - Web socket session error
2020-07-16 08:36:18,385[nio-8080-exec-9]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 129]  - Closing unidentified session
2020-07-16 09:36:18,361[nio-8080-exec-8]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 141]  - Web socket session error
2020-07-16 09:36:18,362[nio-8080-exec-8]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 129]  - Closing unidentified session
2020-07-16 09:48:39,324[nio-8080-exec-4]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 129]  - Closing unidentified session
2020-07-16 09:48:39,325[nio-8080-exec-6]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 129]  - Closing unidentified session
2020-07-16 11:50:25,341[nio-8080-exec-1]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 141]  - Web socket session error
2020-07-16 11:50:25,342[nio-8080-exec-1]  [WARN ] [a.c.w.i.BasicWebSocketEndpoint 129]  - Closing unidentified session
```

**Env details :**
**platform**: minikube 1.7.2 (with k8s v1.16.1)
**installer:** helm v3.1.1

**Comment by skabashnyuk** [comment]
> After using openjdk:11-jre-slim-stretch as base image for che-server on s390x, che-server pod was up and warnings were not seen in pod logs except the ones mentioned below

Yeh. And that is the problem. I'm a bit scared that it might cause problems after an upgrade for existing users. It would be nice to find the cause of the issue. Can you help with that?

**Comment by Prabhav-Thali** [comment]
@skabashnyuk Sure. Will work to investigate the root cause.

**Comment by bivasda1** [comment]
> I've tried to use `11-jre-slim-stretch` and the good news is che server is able to start and is able to start new workspaces.
> However, I saw some warnings that have to be studied before making a final decision.
> 
> ```
> 15-Jul-2020 09:49:17.249 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
> 15-Jul-2020 09:49:17.253 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
> 15-Jul-2020 09:49:17.253 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
> 15-Jul-2020 09:49:17.253 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@5ff8d1f7 locale: en
> ```
> 
> and
> 
> ```
> 2020-07-15 09:50:40,575[775-kl65b-46538]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@3a9238bc] for cluster [EclipseLinkCommandChannel], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> 2020-07-15 09:50:42,162[775-kl65b-57266]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@4fc29fb5] for cluster [WorkspaceLocks], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> 2020-07-15 09:50:45,793[775-kl65b-56100]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@45bd7ff8] for cluster [WorkspaceStateCache], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> 2020-07-15 09:51:05,483[775-kl65b-57266]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@4fc29fb5] for cluster [WorkspaceLocks], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> 2020-07-15 09:51:07,751[775-kl65b-46538]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@3a9238bc] for cluster [EclipseLinkCommandChannel], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> 2020-07-15 09:51:20,169[775-kl65b-56100]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@45bd7ff8] for cluster [WorkspaceStateCache], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> 2020-07-15 09:51:21,641[775-kl65b-29001]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@1e243bf5] for cluster [RemoteSubscriptionChannel], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> 2020-07-15 09:51:29,668[775-kl65b-57266]  [WARN ] [o.j.p.kubernetes.KUBE_PING 115]      - failed getting JSON response from Kubernetes Client[masterUrl=https://172.30.0.1:443/api/v1, headers={Authorization=#MASKED:880#}, connectTimeout=5000, readTimeout=30000, operationAttempts=3, operationSleep=1000, streamProvider=org.jgroups.protocols.kubernetes.stream.TokenStreamProvider@4fc29fb5] for cluster [WorkspaceLocks], namespace [che], labels [app=che,component=che]; encountered [java.lang.Exception: 3 attempt(s) with a 1000ms sleep to execute [OpenStream] failed. Last failure was [javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request]]
> ```
> 
> @bivasda1 @Prabhav-Thali can you take a look?

@skabashnyuk Even we have got same warnings on ppc64le and investigating the root cause.Not getting warnings immediately, after few hours it is showing.Is it similar at you end?

**Platform**:OCP4.3
**Installer**: Operator

**Comment by skabashnyuk** [comment]
>@skabashnyuk Even we have got same warnings on ppc64le and investigating the root cause.Not getting warnings immediately, after few hours it is showing.Is it similar at you end?

I'm sorry I don't understand your message. Did you able to find the root cause?

**Comment by bivasda1** [comment]
> > @skabashnyuk Even we have got same warnings on ppc64le and investigating the root cause.Not getting warnings immediately, after few hours it is showing.Is it similar at you end?
> 
> I'm sorry I don't understand your message. Did you able to find the root cause?

@skabashnyuk Still we are trying to find out the root cause.Have u got those warnings immediate after deployment of che-server?

**Comment by skabashnyuk** [comment]
>@skabashnyuk Still we are trying to find out the root cause.Have u got those warnings immediate after deployment of che-server?

yes

**Comment by bivasda1** [comment]
@skabashnyuk I am not getting warnings now  and also able to login to che-server.Please find the below attached che-server logs.
[che-server logs.txt](https://github.com/eclipse/che/files/4946375/che-server.logs.txt).

**Comment by skabashnyuk** [comment]
You do have this 
```
20-Jul-2020 07:49:36.280 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@1ca5752f locale: en
20-Jul-2020 07:49:36.281 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@1ca5752f locale: en
20-Jul-2020 07:49:36.281 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@1ca5752f locale: en
```

if you wait a minute or two (5 maximum) do you see  something like this?

```
failed getting JSON response from Kubernetes Client[masterUrl=https://17
```

**Comment by bivasda1** [comment]
@skabashnyuk  

> if you wait a minute or two (5 maximum) do you see something like this?
> 
> ```
> failed getting JSON response from Kubernetes Client[masterUrl=https://17
> ```

@skabashnyuk  I have deployed 1 hour back.still not getting this warning,checking above mentioned warning.

**Comment by Prabhav-Thali** [comment]
@skabashnyuk  With the warnings I have mentioned in my comment, I don't see it affecting any functionality on dashboard. Also, found a similar issue [#11571](https://github.com/eclipse/che/issues/11571). It looks like these warnings existed since JDK8 and not caused due to JDK11 upgrade. Also on intel, observed that these warnings occur with current java11 image (openjdk:11-jre-slim) in Dockerfile. 

So is it safe to ignore these warnings? Or should we check for any other alternate docker image?

**Comment by bivasda1** [comment]
> You do have this
> 
> ```
> 20-Jul-2020 07:49:36.280 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@1ca5752f locale: en
> 20-Jul-2020 07:49:36.281 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@1ca5752f locale: en
> 20-Jul-2020 07:49:36.281 CONFIG [localhost-startStop-1] sun.util.locale.provider.LocaleServiceProviderPool.config A locale sensitive service provider returned null for a localized objects,  which should not happen.  provider: sun.util.cldr.CLDRCalendarDataProviderImpl@1ca5752f locale: en
> ```
> 
> if you wait a minute or two (5 maximum) do you see something like this?
> 
> ```
> failed getting JSON response from Kubernetes Client[masterUrl=https://17
> ```

@skabashnyuk Now I am not getting these warnings in ppc64le. Few Waring's are there that should not affect to the functionality of che-server
**The Procedure Reproduced:** 
openjdk:11-jre-slim-stretch base image initially used **JAVA_DEBIAN_VERSION=11.0.3+1-1~bpo9+1** ,we have upgrade the java version to **11.0.6+10-1~bpo9+1**.We have build locally and used as base image to che-server
**Dockerfile:** https://github.com/docker-library/openjdk/blob/178c542fbb93a8f8a42e331b73a1214c9d8ba81d/11/jre/Dockerfile
Please find the below attache logs of che-server.

**Comment by skabashnyuk** [comment]
>Few Waring's are there that should not affect to the functionality of che-server

I believe we should not consider these warnings as not important. Have you able to identify the cause?

**Comment by bivasda1** [comment]
> > Few Waring's are there that should not affect to the functionality of che-server
> 
> I believe we should not consider these warnings as not important. Have you able to identify the cause?
@skabashnyuk I have tested with JAVA_DEBIAN_VERSION=11.0.6+1-1~ bpo9+1 as base (https://packages.debian.org/stretch-backports/java/openjdk-11-jre) and I am not getting any warnings with this particular version.
With JAVA_DEBIAN_VERSION=11.0.3+1-1~ bpo9+1 as base (https://packages.debian.org/stretch-backports/java/openjdk-11-jre-dcevm) I am getting those warnings.
I am still trying to figure out, if something got changed in these versions related to the warnings.

**Comment by bivasda1** [comment]
@skabashnyuk @gerrith3 @Prabhav-Thali 
The openjdk:11-jre-slim-stretch image was built one and half years ago.
It uses openjdk-11-jdk-headless-11.0.3+1-1~bpo9+1.

![Dockerfile_oenjdk](https://user-images.githubusercontent.com/61448925/91527468-76886980-e923-11ea-9f2f-39dfe603214c.png)

Dockerfile path of above docker image: https://github.com/docker-library/openjdk/blob/178c542fbb93a8f8a42e331b73a1214c9d8ba81d/11/jre/slim/Dockerfile
When we tried to recreate the image using below Dockerfile, we got an error.

<img width="940" alt="11 0 3" src="https://user-images.githubusercontent.com/61448925/91527865-3675b680-e924-11ea-9218-bc9e80a1b895.PNG">

This happened because, java version 11.0.3+1-1~ bpo9+1 is no longer available and has been replaced by version 11.0.6_10-1~ bpo9+1
Replacing the value 11.0.3+1-1~ bpo9+1 with 11.0.6+10-1~ bpo9+1,  in the above mentioned Dockerfile, we were able to re-create the openjdk:11-jre-slim-stretch image.
Now, using this freshly created openjdk:11-jre-slim-stretch image (having openjdk-11-jdk- headless-11.0.6+10-1~ bpo9+1), we created che-server image.
When we tested this new che-server image, we are not getting any warnings as observed earlier with older openjdk:11-jre-slim-stretch image.
Attached is the server log.
[che-server log-.txt](https://github.com/eclipse/che/files/5140341/che-server.log-.txt)

Hence we feel that if we have openjdk:11-jre-slim-stretch image available based on latest Java package, then we can create a multi-arch che-server image without any warnings.

**Comment by Prabhav-Thali** [comment]
@bivasda1 I have tested the changes on s390x. No warnings were observed after the deployment of che-server. Also, observed an additional change to be incorporated in [Dockerfile](https://github.com/docker-library/openjdk/blob/178c542fbb93a8f8a42e331b73a1214c9d8ba81d/11/jre/slim/Dockerfile) (which seems to be architecture specific) as mentioned below : 
```
- FROM debian:stretch-slim
+ FROM s390x/debian:stretch-slim
```

@skabashnyuk any update?

**Comment by skabashnyuk** [comment]
@Prabhav-Thali I'm sorry I didn't understand the question to me.

**Comment by Prabhav-Thali** [comment]
@skabashnyuk any further update on jdk11 base image change?

**Comment by skabashnyuk** [comment]
@Prabhav-Thali I have none at this moment. I didn't understand from @bivasda1 explanation the reason of errors with `11-jre-slim-stretch`

**Comment by skabashnyuk** [comment]
@Prabhav-Thali @bivasda1 can you please check if  ``s390x/openjdk:11-jre-slim`` is working for you  https://hub.docker.com/layers/s390x/openjdk/11-jre-slim/images/sha256-2f0660a19ac1b4c9f47677d3840624d7ffb0aded45fc170f7bd9576f052db579?context=explore. IF yes we could add extra parameter to adjust `FROM ` here https://github.com/eclipse/che/blob/master/dockerfiles/che/Dockerfile#L22

**Comment by ghatwala** [comment]
@skabashnyuk  - we need ppc64le , so @bivasda1 can you please check https://hub.docker.com/layers/ppc64le/openjdk/11-jre-slim/images/sha256-57f30fee83b9117237ffd893fb23380c4bcacf4a69e0303300182b4b7416aba9?context=explore works ?

**Comment by Prabhav-Thali** [comment]
@skabashnyuk observing same warnings in browser console and che pod logs as I had mentioned in this [comment](https://github.com/eclipse/che/issues/16655#issuecomment-659549710). 

**Env details** :
**platform**: minikube 1.7.2 (with k8s v1.16.1)
**installer**: helm v3.1.1
 
> With the warnings I have mentioned in my comment, I don't see it affecting any functionality on dashboard. Also, found a similar issue #11571. It looks like these warnings existed since JDK8 and not caused due to JDK11 upgrade.

@skabashnyuk Could you please confirm this at your end?

**Comment by skabashnyuk** [comment]
@Prabhav-Thali https://github.com/eclipse/che/issues/16655#issuecomment-659549710 that is acceptable. Overall functionality is working?

**Comment by Prabhav-Thali** [comment]
@skabashnyuk  As currently we don't have language specific images available for s390x, we were not able to test workspace creation. However the rest functionality looks ok to me and can say its working.

**Comment by skabashnyuk** [comment]
I'm talking about using that image for che-server, not for workspaces.

**Comment by Prabhav-Thali** [comment]
@skabashnyuk we tested s390x/openjdk:11-jre-slim image for che-server and warnings were seen in pod logs. However, no functionality loss is observed.

**Comment by benoitf** [comment]
I've opened https://github.com/eclipse/che/pull/17866 to discuss the usage of `adoptopenjdk/openjdk11:jre` with multi-arch

**Comment by benoitf** [comment]
Usage of adoptopenjdk/openjdk11 has been merged so it should fix the multi-arch build of che-server image
