### ISSUE TITLE
[WIP] Indispensable VS Code Extensions

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16663]
This is an ordered list of the VS Code Extensions that we should support:

- [x] [SonarLint - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode)
- [x] [Tekton Pipelines - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-tekton-pipelines) - #15752 
- [ ] [Bitbucket Pull Requests - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=RamiroBerrelleza.bitbucket-pull-requests)
- [x] [Jira and Bitbucket (Official) - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode)
- [ ] [Veracode for VS Code - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1464889.veracode-greenlight-for-vs-code)
- [ ] [JFrog - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-vscode-extension)
- [ ] [Sonatype Nexus IQ Extension for VSCode - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=SonatypeCommunity.vscode-iq-plugin)
- [ ] [Katalium - Selenium and TestNG made easy - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=katalon-llc.katalium)
- [ ] [Debugger for AWS Lambda - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=thundra.thundra-debugger)
- [x] Support for Ruby and RoR with Che Theia #15606

**Comment by ericwill** [comment]
Edited the list as we have SonarLint already.

**Comment by pdaverh** [comment]
In the above list, JIRA and Bitbucket plug-in has the highest downloads. It may be good to prioritize it, after Tekton.

**Comment by l0rd** [comment]
@pdaverh ok. I have ordered the list accordingly.

**Comment by ericwill** [comment]
We've also had requests from the community for Ruby on Rails (RoR) support -- I've added it to the list.

**Comment by gorkem** [comment]
**No new plugins** until #15819 is completed unless they are to be maintained by their own  communities.

**Comment by ericwill** [comment]
> **No new plugins** until #15819 is completed unless they are to be maintained by their own communities.

Looks like I have my work cut out for me then. :+1:

**Comment by pdaverh** [comment]
We are getting requests to update the ms-python plug-in in Che to the latest release. Would it be possible to prioritize it for the next sprint? Thanks!
https://github.com/eclipse/che/issues/16183

**Comment by gorkem** [comment]
> We are getting requests to update the ms-python plug-in in Che to the latest release. Would it be possible to prioritize it for the next sprint? Thanks!

@ericwill automate! automate! automate! :)

**Comment by ibuziuk** [comment]
Closing as obsolete - https://github.com/eclipse-che/che/issues/21771
