### ISSUE TITLE
Add resource limits/requests to the devfiles and plugins in the registries

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16685]
### Is your enhancement related to a problem? Please describe.

If no limits are set the Che default will be inferred. That may result in workspace not able to be scheduled in the Kubernetes cluster.

### Describe the solution you'd like

Look for CPU/memory request and limits for each plugins and explicitely specify them. The same for containers components in devfiles.

### Additional context

 - [x] Specify che-theia CPU limit ([issue](https://github.com/eclipse/che/issues/18565) / [PR](https://github.com/eclipse/che-plugin-registry/issues/716))
 - [x] Specify jwt-proxy CPU limit ([issue](#18483))
 - [x] Specify che-theia-plugins CPU limits ([PR](https://github.com/eclipse-che/che-plugin-registry/pull/774))
 - [x] Specify che-machine-exec and remote-runtime-injector CPU limits ([PR](https://github.com/eclipse-che/che-plugin-registry/pull/956))
 - [x] Specify che-theia-plugins memory requests in che-theia-plugin.yaml ([PR](https://github.com/eclipse-che/che-plugin-registry/pull/1020))
 - [x] Add a che-plugin-registry PR check to avoid editros or plugins without mem/cpu requests and limits ([PR](https://github.com/eclipse-che/che-plugin-registry/pull/1022))
 - [ ] ~~Evaluate target namespace `ResourceQuota` and `LimitRange` to evaluate and applyg the best mem/cpu requests and limits~~ will be solved in the context of [this epic](https://github.com/eclipse/che/issues/20509)

**Comment by gattytto** [comment]
I can relate to this as I get "heap overflow" when trying to run/debug the haskell sample in che osio

**Comment by ibuziuk** [comment]
@ericwill @l0rd could you please discuss this issue during the prioritization? I believe it would be great to have it in the `7.24.0`

**Comment by gattytto** [comment]
haskell tryout is [here](https://github.com/gattytto/chenamespacesinminikube) including devfile

**Comment by l0rd** [comment]
Discussed yesterday: @azatsarynnyy should create a specific issue for Theia: profiling and setting of request/limits in meta.yaml. Whereas @ericwill team will start profiling strategic plugins (i.e. those that we deliver on CRW).

**Comment by gattytto** [comment]
[this](https://github.com/eclipse/che/issues/18540) can be a problem

**Comment by vitaliy-guliy** [comment]
```
      cpuLimit: 500m
      cpuRequest: 30m
```
Those limitations will be applied to all the plugins as the first iteration.
It seems 500 millicores is pretty enough and does not significantly affect the plugins.

**Comment by svor** [comment]
Some plugins are described in che-theia.yaml:
- [che-machine-exec](https://github.com/eclipse-che/che-plugin-registry/blob/master/che-editors.yaml#L110)
- [remote-runtime-injector](https://github.com/eclipse-che/che-plugin-registry/blob/master/che-editors.yaml#L130)

need to add resources limits/requests into them as well

**Comment by ibuziuk** [comment]
@vitaliy-guliy @ericwill @svor folks, could you please clarify what is missing in this epic? Are we already specify limits & requests for every devfile & plugin in our registries?

**Comment by svor** [comment]
@ibuziuk We still have 3 subtasks to be done, you can see that in the description

**Comment by ibuziuk** [comment]
@svor right, there are some bullet points in the description but looks like there are no related issues for sub-tasks. is it planned to be addressed in the next sprint according to the label?

**Comment by svor** [comment]
@l0rd do you want us to take this epic into the next sprint and finish it?

**Comment by ibuziuk** [comment]
just for the record, default CPU limits might be applied on workspaces.openshift.com infra in the future. So, we need to make sure that all our devfiles & plugins specify the limits & requests explicitly. Otherwise, the default might be applied, which could lead to the performance issues during the workspace usage.

**Comment by l0rd** [comment]
@svor yes for "Specify che-theia-plugins memory requests in che-theia-plugin.yaml" and "Add a che-plugin-registry PR check to avoid editors or plugins without mem/cpu requests and limits".

The last one has lower priority and needs a dedicated epic (I will create it).

**Comment by svor** [comment]
> @svor yes for "Specify che-theia-plugins memory requests in che-theia-plugin.yaml" and "Add a che-plugin-registry PR check to avoid editors or plugins without mem/cpu requests and limits".

OK, we'll take it into the next sprint

**Comment by sunix** [comment]
@vitaliy-guliy could we adjust the memory limit for the machine exec plugin? 
![Selection_429](https://user-images.githubusercontent.com/650571/127316677-233f3884-2823-487b-aa53-b55518258420.png)

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy could we adjust the memory limit for the machine exec plugin?

Sure, I will try to to give it 128Mb of RAM, as we already set that value for `eclipse/che-machine-exec` container here https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L115

**Comment by svor** [comment]
> @svor yes for "Specify che-theia-plugins memory requests in che-theia-plugin.yaml" and "Add a che-plugin-registry PR check to avoid editors or plugins without mem/cpu requests and limits".
> 
> The last one has lower priority and needs a dedicated epic (I will create it).

@l0rd  "Specify che-theia-plugins memory requests in che-theia-plugin.yaml" and "Add a che-plugin-registry PR check to avoid editors or plugins without mem/cpu requests and limits" subtasks are done.

**Comment by l0rd** [comment]
@svor I would like to close this epic and open a different one dedicated to the last subtask "Evaluate target namespace ResourceQuota and LimitRange to evaluate and applyg the best mem/cpu requests and limits" with a label `roadmap/6-months`. What do you think?

**Comment by svor** [comment]
@l0rd sounds good to me, that was the plan:

> @svor yes for "Specify che-theia-plugins memory requests in che-theia-plugin.yaml" and "Add a che-plugin-registry PR check to avoid editors or plugins without mem/cpu requests and limits".
> 
> The last one has lower priority and needs a dedicated epic (I will create it).
