### ISSUE TITLE
Plugins Sprint 183

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16717]
## Sprint goals
1. Continue to support our epics
    * CRW 2.2
    * Tasks in multi-root workspaces
    * Tags -> digests conversion
2. Bugs
3. Maintenance / Automation / Technical Debt

### Epics
**Epic: Git + SSH flow #13494**
* [ ] Improve login procedure for GitHub PullRequest Plugin #14217
    * [ ] Resume work once window.registerUriHandler() functionality (https://github.com/eclipse-theia/theia/issues/5119) is added to theia

**Epic: Rethink/rework the Che workspace with workspace-roots #15529**
* [ ] Support Che tasks for multi-root workspaces #15540 @tsmaeder 
    * [x] Work on feedback from theia PR

**Epic: Check extensions of VS Code extension pack are running smoothly #15390**
* [ ] Check individual extensions to make sure they work in Che
    * [ ] Installing Java Test Runner Support for Java #14871
    * [ ] Build Python sidecar container with deps to test functionality

**Epic: Che Dogfooding**
* [ ] Plugins projects @vitaliy-guliy 
    * [ ] che-plugin-registry
    * [ ] Test existing Kubernetes plugin flow on different deployments
    * [ ] Investigate whether is possible to use `buildkit` tool to build docker images inside a running container #16539

**Epic: Java Tooling/Versioning Issue**
* [ ] Investigate options and put them in the proposal doc 

### CRW
* [ ] Airgap/Proxy issues
    * [ ] Document and QE Usage of Dependencies Repositories in Offline Scenario [CRW-529](https://issues.redhat.com/browse/CRW-529)
    * [x] CRW 2.0 and cluster-wide proxy [CRW-732](https://issues.redhat.com/browse/CRW-732)
    * [x] [Airgap] maven could not calculate build plan - settings.xml not used #14857
    * [x] Implement Airgapped Configuration Mechanism #15518
    * [x] Improve Java workspace usage with customizeable settings.xml [CRW-610](https://issues.redhat.com/browse/CRW-610)
    * [x] Document Airgap Scenarios #15351
* [x] No debug configuration in the "Node JS Config Map" devfile [CRW-791](https://issues.redhat.com/browse/CRW-791) @svor 
* [x] Debugging of the current file failed to start in the "Go" devfile [CRW-779](https://issues.redhat.com/browse/CRW-779) @svor 
* [ ] Error highlighting doesn't work in the "Go" devfile [CRW-778](https://issues.redhat.com/browse/CRW-778) @svor 
* [x] Kubernetes Tools plugin requires vscode-yaml vsix file, but plugin does not provide it [CRW-835](https://issues.redhat.com/browse/CRW-835) @ericwill 

### Bugs
* [x] Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270 @vinokurig 
* [ ] "Run tasks" calls same Task Provider repeatedly. #7496 @tsmaeder 
* [x] Importing devfile with private repo fails #16401 @svor 
* [ ] Use digests instead of tags to reference images #16047 @vitaliy-guliy 
* [ ] sonarlint plugin doesn't work  (#16589) @ericwill 
* [ ] Created file/folder should be selected eclipse-theia/theia#6190 @vinokurig 
* [ ] doc: Fix existing doc to promote che plugins and packaging with vscode extension rather than Theia plugins #14119

### Unplanned
* [x]  'node-debug' broken due to removal of legacy 'node-debug2' #16728 @ericwill 
* [x] Use Java 11 for quarkus stack as Java 8 is deprecated #16790 @ericwill 

### Open PRs From Last Sprint
* [ ] Support User Level Tasks eclipse-theia/theia#7446
* [x] Git clone using private key with password is not working #16517

### Maintenance / Automation / Technical Debt / Reviews
* [ ] Indispensable VS Code Extensions #16663
    *  [ ] Tekton Pipelines - Visual Studio Marketplace - #15752 @ericwill 
    * [ ] [JFrog](https://marketplace.visualstudio.com/items?itemName=JFrog.jfrog-vscode-extension)
* [ ] Check for plugin updates and update as many as possible
    * [ ] vscode-java 0.60
        * [ ] Implement stabilized workspace VS Code APIs eclipse-theia/theia#7171
    * [ ] Python (update the extension in Che)
        * [ ] Support Jupyter Notebooks Natively in Che via Python Plugin #16723
* [ ] Upgrade forked vscode-git to the latest version #16041 @vinokurig 
    * [x] Check update and build extension properly (no repository found issue)
    * [ ] Implement Timeline API eclipse-theia/theia#7577
* [ ] Upgrade the vscode github-pr-plugin version in the che-plugin registry https://github.com/eclipse/che/issues/16741 @vinokurig 
    * [ ] Depends on vscode-git being updated
* [x] Re-layout che-dockerfiles repos to agreed upon structure @ericwill 
    * [x] Finish docker build action
    * [x] Convert sidecar repos to use new layout
    * [ ] Second iteration of build action: make it more efficient, use buildx for multi-arch
* [ ] Integrate dependabot automation into che-dockerfiles repos once layout has changed @ericwill 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 13  | 8 |
| @ericwill | 12  | 7 |
| @tsmaeder | 13 | 8 |
| @svor | 13 | 8 |

**Comment by ericwill** [comment]
See new issue #16918
