### ISSUE TITLE
Editors Sprint 183

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16733]
Apr 22 - May 12

## Goals
1. Theia Plugin APIs
2. Tasks UX
3. Dogfooding
4. Release automation
5. Theia upstream focus

#### Theia Plugin API
- [x] Implement VS Code Built-in Commands https://github.com/eclipse-theia/theia/issues/4050
  - `workbench.action.openRecent`

#### Improve Task UX
- [ ] Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side https://github.com/eclipse/che/issues/15277
  - [ ] Separate creating task terminal and running process logic https://github.com/eclipse/che/issues/16674
  - [ ] Status marker for vs code tasks is not displayed https://github.com/eclipse/che/issues/16672
  - [ ] Display an animated icon for a terminal tab while a task is running https://github.com/eclipse/che/issues/15742

#### Dogfooding
- [x] Create Che Devfile for Eclipse Theia https://github.com/eclipse/che/issues/16522
- [x] Cannot start hosted plugin https://github.com/eclipse/che/issues/16604

#### Release automation
- [x] Che Theia release script should get upstream Theia version from yarn.lock https://github.com/eclipse/che/issues/16691

#### Other collaboration on the PRs/issues in upstream Theia
```
reviewed https://github.com/eclipse-theia/theia/pull/7636 Fix for hosted plugin
reviewed https://github.com/eclipse-theia/theia/pull/7505 Tree mode for SCM view
reviewed https://github.com/eclipse-theia/theia/pull/7670 Tasks dependency resolution
reviewed https://github.com/eclipse-theia/theia/pull/7676 Defer plugin contributions
contributed https://github.com/eclipse-theia/theia/pull/7658 Add devfile to develop Theia in Che
contributed https://github.com/eclipse-theia/theia/pull/7696 Run Task related refactoring
contributed https://github.com/eclipse-theia/theia/pull/7765 Give more flexibility for tasks related sub classes
reviewed https://github.com/eclipse-theia/theia/pull/6921 git and gitlens vscode extensions support
reviewed https://github.com/eclipse-theia/theia/pull/7296 theia.commands.registerCommand API
filed https://github.com/eclipse-theia/theia/issues/7802 Impossible to run a task w/o a problem matcher specified
```

### Unplanned/Blockers
- [x] crw-theia patches for che-theia 7.9.x no longer work w/ che-theia 7.12.x https://github.com/eclipse/che/issues/16822
- [x] Move all 'build' stuff from make-release.sh to build.sh https://github.com/eclipse/che/issues/16654

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 11  | 7
| Roman   | 11  | 7
| Artem | 12  | 7

---
[Previous Sprint](https://github.com/eclipse/che/issues/16521)
