### ISSUE TITLE
Che 7.12.1 Release

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16743]
### List of pending issues / PRs

* [x] [16476 - push new plugins into master branch for 7.y.z releases](https://github.com/eclipse/che-plugin-registry/pull/453)  #16476
* [x] 'node-debug' broken due to removal of legacy 'node-debug2' #16728
* [x] Many stacks broken because of endpoint name having a dash #16748
* [x] [chectl] there are nightly tags in yamls of chectl:7.12.0 tarball #16769
* [x] Do not provision the stop workspace role if there is no oauth identity provider configured. https://github.com/eclipse/che/pull/16803
* [x] Che 7.12.x release templates contain nightly tags of images #16770

### Release status

In parallel, the following releases can be done:

* che-theia,
* che-machine-exec,
* che-devfile registry, then che-plugin-registry (once che-theia and machine-exec are done)
* che-parent, then che-docs, then che as Release Candidate for QE

Then in series:

* che-parent, then che-docs, then che as Release
* che-operator, then chectl

- [x] che-theia
- [x] che-machine-exec
- [x] che-plugin-registry _(depends on che-theia, che-machine-exec)_
- [x] che-devfile-registry
- [x] che-parent
- [x] che-docs _(depends on parent)_
- [x] che _(depends on docs and parent)_
- [x] che-operator _(depends on all of the above)_
  - [x] https://github.com/operator-framework/community-operators/pull/1666
  - [x] https://github.com/operator-framework/community-operators/pull/1665
- [x] chectl _(depends on all of the above)_

| Owner | Process | Script | CI | Artifact(s) |
| --- | --- | --- | --- | --- |
| @azatsarynnyy / @nickboldt | [che-theia](https://github.com/eclipse/che-theia/blob/master/RELEASE.md) | [***MANUAL***](https://github.com/eclipse/che-theia/blob/master/RELEASE.md) | [centos](https://ci.centos.org/job/devtools-che-theia-che-release/) | [`eclipse/che-theia`](https://quay.io/eclipse/che-theia) |
| @nickboldt / @ericwill | [che-machine-exec](https://github.com/eclipse/che-machine-exec/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-machine-exec/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-machine-exec-release/) | [`eclipse/che-machine-exec`](https://quay.io/eclipse/che-machine-exec)| 
| @nickboldt / @ericwill | [che-plugin-registry](https://github.com/eclipse/che-plugin-registry/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-plugin-registry/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-plugin-registry-release/) | [`eclipse/che-plugin-registry`](https://quay.io/eclipse/che-plugin-registry)| 
| @nickboldt / @ericwill | [che-devfile-registry](https://github.com/eclipse/che-devfile-registry/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-devfile-registry/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-devfile-registry-release/) | [`eclipse/che-devfile-registry`](https://quay.io/eclipse/che-devfile-registry)| 
| @mkuznyetsov / @vparfonov | [che-parent](https://github.com/eclipse/che/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-parent/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-parent-che-release/) | [che-parent](https://search.maven.org/search?q=a:che-parent),<br/> [che.depmgt](https://search.maven.org/artifact/org.eclipse.che.depmgt/maven-depmgt-pom) |
| @mkuznyetsov / @vparfonov | [che-docs](https://github.com/eclipse/che/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-docs/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-docs-che-release/) | [che-docs](https://search.maven.org/search?q=a:che-docs)
| @mkuznyetsov / @vparfonov | [che](https://github.com/eclipse/che/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che/blob/master/make-release.sh) | [centos](https://ci.centos.org/job/devtools-che-che-release/) | [che.core](https://search.maven.org/search?q=che.core),<br/> [`eclipse/che-server`](https://quay.io/eclipse/che-server),<br/>[`eclipse/che-endpoint-watcher`](quay.io/eclipse/che-endpoint-watcher),<br/> [`eclipse/che-keycloak`](quay.io/eclipse/che-keycloak),<br/> [`eclipse/che-postgres`](quay.io/eclipse/che-postgres),<br/> [`eclipse/che-dev`](quay.io/eclipse/che-dev), [`eclipse/che-server`](quay.io/eclipse/che-server),<br/> [`eclipse/che-dashboard-dev`](quay.io/eclipse/che-dashboard-dev),<br/> [`eclipse/che-e2e`](quay.io/eclipse/che-e2e) |
| @tolusha| [che-operator](https://github.com/eclipse/che-operator/blob/master/RELEASE.md) | [make-release.sh](https://github.com/eclipse/che-operator/blob/master/make-release.sh) | ? | [`eclipse/che-operator`](https://quay.io/eclipse/che-operator)| 
| @tolusha| [chectl](https://github.com/che-incubator/chectl/blob/master/RELEASE.md) | [make-release.sh](https://github.com/che-incubator/chectl/blob/master/make-release.sh) | [travis](https://travis-ci.org/che-incubator/chectl) | [chectl releases](https://github.com/che-incubator/chectl/releases)

**Comment by tolusha** [comment]
this issue isn't critical at all and doesn't block anything.
both chectl and olm installs a correct version che
https://github.com/eclipse/che/issues/16769

**Comment by sunix** [comment]
I cherry-picked the 2 changesets related to #16748
https://github.com/eclipse/che-devfile-registry/commits/7.12.x

**Comment by nickboldt** [comment]
I believe we have theia, machineexec, registries and che server updated to 7.12.1 now.

**Comment by mkuznyetsov** [comment]
che server maven artifacts and images have been released

**Comment by tolusha** [comment]
che-operator, chectl are released
che-operator updates was tested on OpenShift 4.3

Corresponding PRs:
https://github.com/eclipse/che-operator/pull/234
https://github.com/che-incubator/chectl/pull/682/

Todo:
- community operator PRs
- che-operator update tests on minikube

**Comment by nickboldt** [comment]
PRs for che-op and chectl merged.

**Comment by dmytro-ndp** [comment]
Results of E2E tests been run against _Multiuser Eclipse Che 7.12.1_ without TLS support on **minikube** installed by **operator**:
- E2E _Java Maven_, _Java Vert.x_ and _Python Django_ E2E selenium tests had passed:  https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/1670
- E2E Happy path tests had failed on "_Validation of workspace build and run_" step (an issue https://github.com/eclipse/che/issues/16828).

**Comment by tolusha** [comment]
Tested on minikube
community operator PRs created

**Comment by tolusha** [comment]
Community operator PRs merged.
