### ISSUE TITLE
Jupyter Notebooks native support through latest Python VS Code extension

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16818]
### Is your enhancement related to a problem? Please describe.

Latest python extension includes [jupyter support](https://code.visualstudio.com/docs/python/jupyter-support). I have tried it out but loading a jupyter notebook failed.

![image](https://user-images.githubusercontent.com/606959/80770537-d840ee80-8b50-11ea-812e-e7b486ea110a.png)

To try it out on che.osio --> [![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://gist.githubusercontent.com/l0rd/7190c65773a23f393a839598b22f3c1a/raw/ded49ccffa023c243a1c6e26f292696cc02ff504/devfile.yaml)

### Describe the solution you'd like

This is the devfile I have been using:

```yaml
devfile.yaml
---
apiVersion: 1.0.0
metadata:
  name: python-workspace
projects:
  - name: jupyter-hello-world1
    source:
      location: 'https://github.com/chasbecker/TextAnalysis.git'
      type: git
components:
  - type: chePlugin
    alias: ms-python/python/latest
    reference: https://gist.github.com/l0rd/7190c65773a23f393a839598b22f3c1a/raw/meta.yaml
    memoryLimit: 512Mi
  - type: cheEditor
    alias: che-theia
    reference: https://gist.github.com/l0rd/7190c65773a23f393a839598b22f3c1a/raw/theia.yaml
    memoryLimit: 512Mi
  - type: chePlugin
    alias: machine-exec
    id: eclipse/che-machine-exec-plugin/latest
```

vscode python meta.yaml

```yaml
vscode-python-meta.yaml
---
apiVersion: v2
publisher: ms-python
name: python
version: 2020.4.76186
type: VS Code extension
displayName: Python
title: Python extension
description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting,
  refactoring, unit tests, snippets, and more.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/Microsoft/vscode-python
category: Language
firstPublicationDate: '2020-04-27'
spec:
  containers:
  - image: "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
    name: vscode-python
    memoryLimit: '512Mi'
  extensions:
  - https://github.com/microsoft/vscode-python/releases/download/2020.2.62710/ms-python-release.vsix
```

### Describe alternatives you've considered

I have also tried to add python in che-theia container:

```dockerfile
FROM quay.io/eclipse/che-theia:7.12.0

USER root

RUN apk add --no-cache python3

# make some useful symlinks that are expected to exist
RUN cd /usr/bin \
	&& ln -s idle3 idle \
	&& ln -s pydoc3 pydoc \
	&& ln -s python3 python \
	&& ln -s python3-config python-config

USER theia
```

But it didn't help

### Sub-tasks
- [x] `vscode.workspace.fs` API https://github.com/eclipse-theia/theia/pull/7908
- [x] Adapt Che Theia to the new Theia FS API https://github.com/eclipse/che/issues/17357
- [x] Che Theia Web View doesn't work properly when a plugin is running in its own sidecar https://github.com/eclipse/che/issues/16870
- [x] Adapt `vscode.workspace.fs` Plug-in API to Che-Theia's remote plugin system https://github.com/eclipse/che/issues/19110

**Comment by ericwill** [comment]
I was working on upgrading the Python plugin today (it's almost a year out of date) as part of #16723. Thanks for doing some more investigation, once I get the Python extension upgraded (there are some bugs at the moment) it will be quite helpful.

**Comment by JPinkney** [comment]
Just wanted to note,  we might be missing some plugin api: https://github.com/eclipse-theia/theia/issues/3186#issuecomment-610356821 for the newest version of the python plugin. There seems to be a few other Jupyter issues on the theia repo as well: https://github.com/eclipse-theia/theia/issues?q=is%3Aissue+is%3Aopen+Jupyter

**Comment by ericwill** [comment]
> Just wanted to note, we might be missing some plugin api: [eclipse-theia/theia#3186 (comment)](https://github.com/eclipse-theia/theia/issues/3186#issuecomment-610356821) for the newest version of the python plugin. There seems to be a few other Jupyter issues on the theia repo as well: https://github.com/eclipse-theia/theia/issues?q=is%3Aissue+is%3Aopen+Jupyter

Yes, jupyter issues aside the latest python extension also complains about Python not being installed, even though it's present in the container and running python code still works. Lots of weirdness going on there.

**Comment by azatsarynnyy** [comment]
> Yes, jupyter issues aside the latest python extension also complains about Python not being installed, even though it's present in the container and running python code still works.

It looks like a known issue https://github.com/Microsoft/vscode-python/issues/11870

**Comment by azatsarynnyy** [comment]
The missing parts of upstream Theia are tracked here:
- https://github.com/eclipse-theia/theia/issues/8022
- https://github.com/eclipse-theia/theia/issues/3186#issuecomment-610356821

**Comment by azatsarynnyy** [comment]
Editors Team will work on adding [CustomEditor API](https://code.visualstudio.com/api/extension-guides/custom-editors) support (https://github.com/eclipse-theia/theia/issues/6636)
as Python extension [relies on it](https://github.com/microsoft/vscode-python/blob/e7136b1448d27e9a607ca0d8242d4272b48aabdb/src/client/datascience/interactive-ipynb/nativeEditorProvider.ts#L35) for rendering Jupyter Notebooks.

**Comment by azatsarynnyy** [comment]
Several updates:

1. After a more detailed investigation, it turned out that Python VS Code extension needs support for CustomEditor Plugin API only as an [experimental feature](https://github.com/microsoft/vscode-python/pull/12188/files#diff-b1e7b24833976c9e40041d298ee03890R201) that is not used by default. So, it's not a blocker for Jupyter Notebooks support.

2. There's WIP PR https://github.com/eclipse-theia/theia/pull/7908 (FS Plugin API) in Theia upstream that fixes running Jupyter Notebooks in vanilla Theia. Che Theia isn't compatible with these changes and needs to be adapted https://github.com/eclipse/che/issues/17357.
I fixed the compilation errors in Che Theia (https://github.com/eclipse/che-theia/pull/798) and tried to build Che Theia based on Theia from upstream Theia WIP PR branch, but it doesn't fix this issue - `... is not a valid file name`

So, we will postpone work on CustomEditor Plugin API and start investigating why new FS Plugin API fixes Jupyter Notebooks support in vanilla Theia but not in Che Theia.

**Comment by azatsarynnyy** [comment]
After adapting Che Theia to the latest Theia FS Plugin API https://github.com/eclipse/che-theia/pull/823 there's some progress with the Jupyter Notebooks support :tada: 

It looks like working well when the Python VS Code extension is running in the Theia container

![image](https://user-images.githubusercontent.com/1636395/94439523-337f1780-01a9-11eb-89fb-8eb176f8a734.png)

But it doesn't when it's running in a separate sidecar. I think it requires adapting the WebView API to work remotely https://github.com/eclipse/che/issues/16870
So, it will be the next step.

**Comment by azatsarynnyy** [comment]
I'm converting it into an epic since multiple steps are required.
See the sub-tasks in the description.

**Comment by sub-mod** [comment]
Just saw this [Introducing the Jupyter Extension for VS Code](https://devblogs.microsoft.com/python/introducing-the-jupyter-extension-for-vs-code/) from microsoft and I wanted to check if it changes anything for us or if there is anything new which might break for us ?

**Comment by azatsarynnyy** [comment]
Thanks @sub-mod for the link!

They split [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) by extracting Jupyter related functionality into a [separate extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter).
For Che, it means both extensions have to be packed into a single Che Plug-in. So, actually, nothing should be changed for us :slightly_smiling_face: 
We continue adapting Che Theia to support loading WebView from a sidecar.

What will really require extra effort is adding VS Code compatible [Native Notebook API](https://github.com/microsoft/vscode/blob/11341a0d371907da488568fa09d8eadc52054a1c/src/vs/vscode.proposed.d.ts#L1487) into upstream Theia.
It's not required yet. But I saw they're experimenting with it in Jupyter extension, so we'll need the support of it as well in order to use the future versions.

**Comment by cccs-eric** [comment]
I am looking for a solution to run Jupyter Notebooks in Che.  I have seen multiple issues regarding this and I would like to know if there is an ETA.  I have created a custom Che plugin with the new Jupyter extension and I get the dreaded CustomEditor API error:
```
Activating extension 'Jupyter' failed: TypeError: s.window.registerCustomEditorProvider is not a function
```  

I also noticed errors about some unsupported activation events:
```
Unsupported activation events: onNotebook:jupyter-notebook, onCustomEditor:jupyter.notebook.ipynb, please open an issue: https://github.com/eclipse-theia/theia/issues/new
Unsupported activation events: onCOmmand:python.datascience.export, onNotebookEditor:jupyter-notebook, please open an issue: https://github.com/eclipse-theia/theia/issues/new
```
The second event `onCOmmand:python.datascience.export` got fixed in the mspython extension by this [commit](https://github.com/microsoft/vscode-python/commit/4b2b333264a3015eaf212c29d05d30a279978ed3).

So I am stuck right now not being able to run notebooks.  Is there a known solution to run notebooks, or do I have to wait for the `CustomEditor` API and an update to Che's python plugin?

**Comment by azatsarynnyy** [comment]
Hello @cccs-eric 
most likely, in the latest versions of Python extension, they've changed something related to CustomEditor API usage.
It was opt-in AFAIK.
I suggest to try some previous version, that was before extracting Jupyter functionality to a separate extension, e.g. https://github.com/microsoft/vscode-python/releases/tag/2020.8.106424
Note, ATM it should be working when running Python extension in Che Theia sidecar only. To be able to run it in a separate container we're currently working on https://github.com/eclipse/che/issues/16870

FYI: Folks from SAP should be currently working on CustomEditor API in upstream Theia https://github.com/eclipse-theia/theia/issues/6636

**Comment by cccs-eric** [comment]
Thanks for the feedback @azatsarynnyy .  I will try what you suggested.  This might be a lack of knowledge on my side, but I see Che supports the code-server editor version 3.6.2 and that version is based on VSCode 1.50.  Would it work if I use that editor since it is at version 1.50, it should support the latest APIs?  Is there a reason I should stay away from the Code-server editor if Theia is too far behind?

**Comment by azatsarynnyy** [comment]
@cccs-eric you can try it with code-server. I'm not sure how it works as I have no experience with code-server

**Comment by sub-mod** [comment]
@azatsarynnyy Just checking if there is more work to be done for this issue in #18845 ?

**Comment by azatsarynnyy** [comment]
@sub-mod we've finished with a Webview related part https://github.com/eclipse/che/issues/16870, but it seems Jupyter functionality doesn't work as expected. We plan to look at it in more detail.

**Comment by cccs-eric** [comment]
@azatsarynnyy Thanks for the update, we are looking forward to get this extension (Jupyter) working in Che.  Please keep us in the loop 😃

**Comment by azatsarynnyy** [comment]
After examination of the Python extension's sources, I've noticed some interesting details regarding the Plug-in FS API usage.
The extension works with the file system via `vscode.workspace.fs` API that actually knows nothing about the remote plug-ins running in the dedicated sidecars.

When I run the extension in the Che-Theia container, it's able to get the required files and renders the Notebooks correctly.
![image](https://user-images.githubusercontent.com/1636395/108495764-dac42e80-72b1-11eb-85a9-fedcc11942dd.png)

But when I run the extension in a separate sidecar, `vscode.workspace.fs` API still tries to look for the requested resource in Che-Theia container, where the requested resources don't exist of course.

So, the next step here is to adapt `vscode.workspace.fs` Plug-in API to Che-Theia's remote plugin system.
I've filed the issue for that work - https://github.com/eclipse/che/issues/19110 and updated the sub-tasks.

**Comment by azatsarynnyy** [comment]
We've finished the adaptation of `vscode.workspace.fs` Plug-in API to Che-Theia's remote plugin system.
See https://github.com/eclipse/che-theia/pull/1045
The next step is to update Python Che Plug-in and to include all the required external dependencies into the image.
cc @ericwill

**Comment by themr0c** [comment]
Release notes: https://issues.redhat.com/browse/CRW-1877
