### ISSUE TITLE
Improve operator-based deployment when kubeadmin is the only user

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16834]
### Is your enhancement related to a problem? Please describe.

The UX when deploying Che using the operator on a just-created OpenShift cluster is not satisfying:

1. We cannot link `kubeadmin` as a valid OAuth user
2. Deployment fails because no OAuth identity provider exist
3. Even after adding an OAuth provider the deployment fails until a user logs in

### Describe the solution you'd like

To address the 3 points above we should:

- [x] Verify if `kubeadmin` can be a regular OAuth user with latest Keycloak and OpenShift #16835
- [x] Fallback to native Keycloak users if using OpenShift OAuth is not possible #16836
- [x] Check if an OAuth identity provider exist instead of looking for OpenShift users #16837

**Comment by alexeykazakov** [comment]
Is it fixed?

**Comment by l0rd** [comment]
@alexeykazakov the UX has been improved (deployment is successful even if kubeadmin is the only user and we look for identity providers instead of users) but we still depend on keycloak and it doesn't consider kubeadmin a valid user https://github.com/openshift/origin/issues/24950.

**Comment by nickboldt** [comment]
Appears to be fixed in [master](https://github.com/che-incubator/chectl/pull/692) but I don't see a fix in 7.9.x, so not yet fixed in CRW 2.1.2

https://github.com/che-incubator/chectl/commits/7.9.x
