### ISSUE TITLE
Support maven configuration injection in workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16832]
### Is your enhancement related to a problem? Please describe.

This is an epic that tracks the different tasks related to mounting and using maven configurations (`settings.xml`) into a workspace that needs such configuration.

These are the subtasks:

- [x] Document the current workaround (manually adding settings.xml in `/projects` folder) #15503
- [x] Allow volumes to be added to any devfile component. #13318 #15122
- [x] Update [doc](https://www.eclipse.org/che/docs/che-7/using-maven-artifact-repositories/#defining-repositories-in-settings-xml_using-maven-artifact-repositories): mount a `maven-settings` volume instead of using `/projects`  
- [x] Automatically inject settings.xml as a secret in workspaces that need it #14680
- [x] Update the documentation for settings.xml and add a doc to support use cases as in #16857

**Comment by skabashnyuk** [comment]
@l0rd can you explain what is the relation between this epic and this question https://github.com/eclipse/che/issues/16197? What is your expectation?

**Comment by l0rd** [comment]
@skabashnyuk I think I misread #16197 as it doesn't really apply to maven settings. I have created #16857 instead.

**Comment by nickboldt** [comment]
4 weeks later... this N&N is not yet news. :( slip to backlog.
