### ISSUE TITLE
Che Deploy Sprint #184

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#16867]
May 13 - June 2

### Team
| Name  |  |
| ------------- | ------------- |
| Anatolii   |   |
| Mykola   |    |
| Aleksandr  |   |

### CRW
- [x] https://issues.redhat.com/browse/CRW-765  
  - [x] https://github.com/eclipse/che-operator/pull/283
- [x] https://issues.redhat.com/browse/CRW-336 https://issues.redhat.com/browse/CRW-640 
  - [x] https://github.com/eclipse/che-operator/pull/267
- [ ]  https://issues.redhat.com/browse/CRW-732 
  - [ ] https://github.com/eclipse/che-operator/pull/272

### Issues
- [x] Release 7.13.0 https://github.com/eclipse/che/issues/16933
  - [x] https://github.com/eclipse/che-operator/pull/264 https://github.com/eclipse/che-operator/pull/265 https://github.com/che-incubator/chectl/pull/711
- [x] Release 7.13.1 https://github.com/eclipse/che/issues/16950
  - [x] https://github.com/eclipse/che-operator/pull/270 https://github.com/eclipse/che-operator/pull/271 https://github.com/che-incubator/chectl/pull/727 https://github.com/operator-framework/community-operators/pull/1768 https://github.com/operator-framework/community-operators/pull/1767
- [x] Release 7.13.2 https://github.com/eclipse/che/issues/17021
   - [x] https://github.com/che-incubator/chectl/pull/733 https://github.com/eclipse/che-operator/pull/279 https://github.com/eclipse/che-operator/pull/278  https://github.com/operator-framework/community-operators/pull/1803
   - [x]  https://github.com/operator-framework/community-operators/pull/1804
- [x] In the Operator Go code, remove remaining default values that require overriding in downstream https://github.com/eclipse/che/issues/16868
  - [x] https://github.com/eclipse/che-operator/pull/247
- [x] Make the new `olm` chectl installer easier to use downstream https://github.com/eclipse/che/issues/16862
  - [x] https://github.com/che-incubator/chectl/pull/724
- [x] Make the new OLM `chectl` installer the default form of operator installer on OpenShift 4.x https://github.com/eclipse/che/issues/16861
  - [x] https://github.com/che-incubator/chectl/pull/693
  - [x] https://github.com/che-incubator/chectl/pull/701
- [x] `CheCluster` custom resource completion and docs are not available anymore on OpenShift 4.3 https://github.com/eclipse/che/issues/16860
- [ ] Specify and use OLM relatedImages in the operator https://github.com/eclipse/che/issues/14993 https://github.com/eclipse/che/issues/16815
  - [ ] https://github.com/eclipse/che-operator/pull/274#event-3368388239
- [x] Fallback to native Keycloak users if using OpenShift OAuth is not possible https://github.com/eclipse/che/issues/16836 https://github.com/eclipse/che/issues/16837
  - [x] https://github.com/eclipse/che-operator/pull/248/
  - [x] https://github.com/che-incubator/chectl/pull/692/
- [ ] [TLS] Deprecate `--self-signed-cert` flag https://github.com/eclipse/che/issues/16764
  - [ ] https://github.com/eclipse/che/pull/17044/
  - [ ] https://github.com/eclipse/che-operator/pull/285
  - [ ] https://github.com/che-incubator/chectl/pull/734
- [x] [doc] Fix deploy instruction https://github.com/eclipse/che/issues/16794 https://github.com/eclipse/che/issues/16792
  - [x] https://github.com/eclipse/che-docs/pull/1280
- [x] [chectl] Installation failed for macOS  https://github.com/eclipse/che/issues/16801
- [x] [chectl] Failed to check running status if previous deployment is not cleaned up yet https://github.com/eclipse/che/issues/14595 
  - [x] https://github.com/che-incubator/chectl/pull/730
- [ ] Add offline flag to chectl server:start https://github.com/eclipse/che/issues/14699
- [ ] Che-server fails to bootstrap on Kubernetes (kubeadm setup) https://github.com/eclipse/che/issues/16767
- [ ] Verifying that chectl can deploy multiuser Che without cluster admin privileges https://github.com/eclipse/che/issues/14662

### PRs to merge
- [x] https://github.com/operator-framework/community-operators/pull/1685
- [x] [chectl] generate passwords for initial users https://github.com/eclipse/che/issues/14082
  - [x] https://github.com/che-incubator/chectl/pull/690
- [x] https://github.com/eclipse/che-operator/pull/266
- [x] Chore(deps-dev): Adding s390x support to chectl  https://github.com/che-incubator/chectl/pull/699
- [x] Added support for ppc64le https://github.com/eclipse/che-operator/pull/255/

## Unplanned
- [x] [chectl] Failed to deploy Eclipse Che using olm installer: Catalog Source not found https://github.com/eclipse/che/issues/16913
  - [x] https://github.com/che-incubator/chectl/pull/700
- [x] Deployment fails because che-operator SA cannot get resource oauth https://github.com/eclipse/che/issues/16959
  - [x] https://github.com/che-incubator/chectl/pull/708
- [x] Che install failing with the latest chectl version on OpenShift 4.3.18 cluster https://github.com/eclipse/che/issues/16966
  - [x] https://github.com/che-incubator/chectl/pull/725
- [x] Possible Bug: → Get pods by selector "app.kubernetes.io/name=cert-manager" returned a pod without a status.condition of type "Ready" https://github.com/eclipse/che/issues/17001
  - [x] https://github.com/che-incubator/chectl/pull/729/

### Next sprint
- [ ] https://issues.redhat.com/browse/CRW-923
- [ ] https://issues.redhat.com/browse/CRW-913
- [ ] https://issues.redhat.com/browse/CRW-864 https://github.com/eclipse/che/issues/16906
- [ ] Configure bots to open workspace to review PR (chectl, che-operator, machine-exec repositories)

 [Previous Sprint](https://github.com/eclipse/che/issues/16623)
