### ISSUE TITLE
Plugins Sprint 184

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#16918]
## Sprint goals
1. Bugs (upstream and CRW)
2. Maintenance / Automation / Technical Debt

### Epics

**Epic: Separate vscode-java version from development target #16851** @tsmaeder 
* [x] Investigate options and put them in the proposal doc 

### CRW
* [x] Update doc: mount a maven-settings volume instead of using /projects (#16832) @svor 
* [ ] Indispensable VS Code Extensions #16663 
    * [ ] [Tekton Pipelines - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-tekton-pipelines) - #15752 @ericwill 
    * [ ] [Bitbucket Pull Requests - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=RamiroBerrelleza.bitbucket-pull-requests) @vitaliy-guliy
    * [ ] [Jira and Bitbucket (Official) - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode) @vitaliy-guliy
* [ ] Investigate using EAP 7.3.1 image as is without manipulation for CRW 2.x [CRW-871](https://issues.redhat.com/browse/CRW-871) @svor 
* [x] Investigate moving from mongodb 3.4 to 3.6 [CRW-884](https://issues.redhat.com/browse/CRW-884) @ericwill 
    * [x] Upgrade mongodb from 3.4 to 3.6 #16952
* [x] Python Stack Image doesn't allow me to install pylint [CRW-886](https://issues.redhat.com/browse/CRW-886) @svor 
* [ ] Remove unneeded runtimes from stack images [CRW-919](https://issues.redhat.com/browse/CRW-919) @ericwill 
* [x] sshpass breaks CRW Theia build [CRW-920](https://issues.redhat.com/browse/CRW-920) @vinokurig

### Bugs
* [ ] "Run tasks" calls same Task Provider repeatedly. eclipse-theia/theia#7496 @tsmaeder 
* [x] Che Deployment on GCP - Debugging Failing to Run #16805 @svor 
* [ ] Error highlighting broken in several default stack #15919 @ericwill 
* [ ] Use digests instead of tags to reference images #16047 @vitaliy-guliy 
    * [ ] Update the PR
    * [ ] PR check using GitHub actions to automatically ensure no PR contributes tags
* [ ] sonarlint plugin doesn't work  (#16589) @ericwill 

### Open PRs From Last Sprint
* [x] Support User Level Tasks eclipse-theia/theia#7446
* [ ] Support Che tasks for multi-root workspaces #15540
* [x] Created file/folder should be selected eclipse-theia/theia#6190

### Maintenance / Automation / Technical Debt / Testing
* [x] Add CPU limits to the devfiles and plugins in the registries #16685 @vitaliy-guliy 
    * Holding off until more thorough testing can be done on AWS and OpenShift
* [ ] Set up PR Check for Java Che 7 plugins #15797 @svor 
* [ ] Check for plugin updates and update as many as possible
    * [ ] vscode-java -> 0.61 @vinokurig 
    * [x] vim needs to be updated to v1.14.5 #16176
    * [x] vscode-openshift-connector -> v0.1.5 #16178 @ericwill 
    * [x] php -> v1.3.11 #16180 @ericwill 
    * [x] vscode-kubernetes-tooling -> v1.2.0
    * [ ] Upgrade forked vscode-git to the latest version #16041 @vinokurig 
        * [ ] Implement Timeline API eclipse-theia/theia#7577
    * [ ] Upgrade the vscode github-pr-plugin version in the che-plugin registry https://github.com/eclipse/che/issues/16741 @vinokurig 
        * [ ] Depends on vscode-git being updated
* [x] gitlens (vs code extension) is not compatible with che due to api not available #16341 @ericwill 
    * [x] Check theia API compatibility and add gitlens support
* [x] Re-layout che-dockerfiles repos to agreed upon structure @ericwill 
    * [x] Second iteration of build action: make it more efficient, use buildx for multi-arch
* [x] Integrate dependabot automation into che-dockerfiles repos once layout has changed @ericwill 
    * [x] che-sidecar-openshift-connector
    * [x] che-sidecar-kubernetes-tooling 
* [x] Deprecate old plugins in the registry #17000 
    * [x] Mark plugins as deprecated so they can be removed in three sprints

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 10  | 6 |
| @vinokurig  | 15  | 9 |
| @ericwill | 14  | 9 |
| @tsmaeder | 13  | 8 |
| @svor | 10  | 6 |

**Comment by ericwill** [comment]
Superseded by sprint 185, #17083
