### ISSUE TITLE
Editors Sprint 184

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16915]
May 13 - Jun 2

## Goals
1. Multi cursor co-editing capability
2. Theia Plugin API
3. Improve Theia Task UX (finalize the PRs)
4. Bugs
5. Theia upstream focus

#### Multi cursor co-editing capability
- [ ] Investigate multi cursor co-editing capability for Che Theia https://github.com/eclipse/che/issues/16907

#### Theia Plugin API
- Implement VS Code Built-in Commands https://github.com/eclipse-theia/theia/issues/4050
  - [x] `workbench.action.openRecent` PR https://github.com/eclipse-theia/theia/pull/7812
To support vscode-didact extension https://github.com/eclipse/che/issues/16940:
    - [x] `explorer.newFolder` PR https://github.com/eclipse-theia/theia/pull/7843
    - [ ] `workbench.view.explorer`
    - [x] `workbench.action.terminal.sendSequence` PR https://github.com/eclipse-theia/theia/pull/7906
    - [x] `workbench.action.terminal.kill` PR https://github.com/eclipse-theia/theia/pull/7906
    - [x] `copyFilePath` PR https://github.com/eclipse-theia/theia/pull/7934

- [ ] Upgrade Theia to Monaco 0.20.0 https://github.com/eclipse-theia/theia/issues/7697 to unblock further work on `SemanticTokenProvider` Plugin API

#### Improve Theia Task UX (finalize the PRs)
- [x] Create instant feedback when a task is clicked without waiting for the task to actually spawn server-side https://github.com/eclipse/che/issues/15277
  - [x] Separate creating task terminal and running process logic https://github.com/eclipse/che/issues/16674
  - [x] Status marker for vs code tasks is not displayed https://github.com/eclipse/che/issues/16672
  - [x] Display an animated icon for a terminal tab while a task is running https://github.com/eclipse/che/issues/15742

  ##### Related bugs
    - [x] Attach Task is not working for Che tasks https://github.com/eclipse/che/issues/16854
    - [x] Run Last Task is not working for Che tasks https://github.com/eclipse/che/issues/16853
    - [x] The appropriate terminal tab doesn't open after launching predefined command in the associated workspace https://issues.redhat.com/browse/CRW-444

#### Bugs
- [x] 'Run' / 'Debug' codelens does not work https://github.com/eclipse/che/issues/16856

- [x] Che Theia WebSocket improvement analysis https://github.com/eclipse/che/issues/16900

#### Other collaboration on the PRs/issues in upstream Theia
```
reviewed https://github.com/eclipse-theia/theia/pull/7804 always accept items on type callback
proposed https://github.com/eclipse-theia/theia/pull/7812 workbench.action.openRecent built-in command
reviewed https://github.com/eclipse-theia/theia/pull/7839 Ctrl-c (terminate) not working in Terminals
proposed/reviewed https://github.com/eclipse-theia/theia/pull/7843 Bind command for explorer.newFolder
filed https://github.com/eclipse-theia/theia/issues/7853 TypeError: Converting circular structure to JSON
reviewed https://github.com/TypeFox/monaco-languageclient/pull/207
filed https://github.com/eclipse-theia/theia/issues/7899 Variable:List All command is not working
proposed/reviewed https://github.com/eclipse-theia/theia/pull/7906 Bind commands for terminal.sendSequence and terminal.kill
filed https://github.com/eclipse-theia/theia/issues/7932 Variables are not resolved for user level tasks
filed https://github.com/eclipse-theia/theia/issues/7931 Align TaskScope with API object
filed https://github.com/eclipse-theia/theia/issues/7933 Apply Task Template at configure user level tasks
reviewed https://github.com/eclipse-theia/theia/pull/7929 Include global tasks in "Configure Tasks"
reviewed https://github.com/eclipse-theia/theia/pull/7928 Allow updating user-level task
proposed/reviewed https://github.com/eclipse-theia/theia/pull/7934 Add command Copy Path and bind handler for native VS Code command
```

### Unplanned/Blockers
- [x] Che-Theia failed with error 'Refused a WebSocket connection' https://github.com/eclipse/che/issues/17047
- [x] reviewing/testing https://github.com/eclipse/che-theia/pull/739 and all the related upstream Theia PRs

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 14  | 8
| Roman   | 14  | 8
| Artem | 15  | 9

---
[Previous Sprint](https://github.com/eclipse/che/issues/16733)
