### ISSUE TITLE
Docker launcher related improvements

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#1697]
This issue is to track some improvements related to running Che inside a Docker container. These improvements are needed to make Che running inside a Docker container the default. I will update this issue with the correspondent PRs and status:
- [x] 1. Simpler Docker command (PR #1683)
- [x] 2. Lighter docker image (PR #1682)
- [x] 3. Let volumes be configurable
- [x] 4. Run Che server as root
- [x] 5. Add Che CLI to wrap launcher #1969 

Details and rationals of these improvements can be found [here](https://gist.github.com/l0rd/02e224f812dac52e6802bf716f598e94)

**Comment by l0rd** [comment]
#### Simpler Docker command Checklist (PR #1683)
- [x] move `set -e` to the bottom
- [x] remove trap
- [x] $0 to ${0}
- [x] start and restart fails when che is not running
- [x] check if container has started successfully
- [x] use docker 1.6 client inside docker container and / or allow multiple clients at same time
- [x] create a Dockerfiles folders and put there Dockerfile related stuff
- [x] Infer image version and run the server with the same version
- [x] Add restart policy to che-server
- [x] Test if the right network interface is retrieved with docker toolbox
- [x] Add log "Che server has been started. Run docker logs -f che to see Che server logs" and the dashboard URL. Or a message that says that the server hasn't started.
- [x] Add comments to each Dockerfile with instructions on the docker build command
- [x] Support the following variables
  - `CHE_DOCKER_HOST_IP`, default = find_docker_host_ip() method
  - `CHE_PORT`, default = 8080
  - `CHE_VERSION`, default = latest
  - `CHE_RESTART_POLICY`, default = ???
- [x] Update CI systems to build all Docker images as part of nightly and tagging cycle #1842
- [x] Change "Starts Che server in new console" to "Starts Che server"
- [x] Remove client connect output from che.sh of server?
- [x] Fix `CHE_HOSTNAME` on Docker for Windows
- [x] Fix Che server Dockerfile to use Docker 1.6
- [x] Find way to distinguish between Docker for Mac vs. Windows #1744 
- [x] Author new Usage: Docker Launcher page
- [x] Provide helpful output to user when doing docker pull of image (looks like hang right now)
- [x] Enable custom variable to allow for local binaries
- [x] Change DOCKER_HOST_IP to be CHE_HOST_IP with default = DOCKER_HOST_IP
- [x] Document CHE_LOG_LEVELS
- [x] Add Copyright headers

**Comment by l0rd** [comment]
#### Let volumes be configurables Checklist
- [ ] Use volumes-from when wsagents are started (#2598)
- [ ] Use 3 data containers for the 3 volumes
- [ ] Check for env variables for the folders paths
- [ ] In launcher.bat verify that, when provided, the volumes paths are writable
- [ ] Special inner syntax for Windows changing volume location - requires custom variables
- [ ] Support the following env variables
  - `CHE_HOST_LOCATION`, default = ${che.home}
  - `CHE_WORKSPACES_LOCATION`, default = ${CHE_HOST_LOCATION}/workspaces
  - `CHE_STORAGE_LOCATION`, default = ${CHE_HOST_LOCATION}/storage
  - `CHE_PROJECTS_LOCATION`, default = ${CHE_HOST_LOCATION}/projects
  - `CHE_TERMINAL_MOUNT_LOCATION`, default = ${CHE_HOST_LOCATION}/lib/
  - `CHE_AGENT_ZIP_LOCATION`, default = {CHE_HOST_LOCATION}/lib/ws-agent.zip
  - `CHE_PROPERTIES_LOCATION`, default = null

**Comment by TylerJewell** [comment]
@l0rd - do you want us to start crossing off the issues that are now finished that are committed into the PR, or wait for the merge?  I'd like to do the former, and therefore I think a lot of these issues are crossed off.

Second, would you like me to identify any usability / bugs into the checklist here, or as a comment to the PR thread?

**Comment by l0rd** [comment]
@TylerJewell Ok for crossing off the issues after the merge. And I think that the usability bugs relative the the ongoing PR should be reported on the specific PR.

**Comment by TylerJewell** [comment]
@l0rd - given the most recent improvements with the refactoring of the che-server, we can remove some of these items, we can check off others, and rewrite yet others.  Let's sit down and update this epic, and / or repackage it to cover the latest list of items we are tracking.

**Comment by TylerJewell** [comment]
Based upon the refactoring of the che-server, we probably can refactor the volumes-from list of tasks to the following:
- [x] We do not need volumes-from for the ws-agent, because we will support downloading over HTTP from the Che master.
- [ ] We will need a volume data container to reflect to the new CHE_DATA variable and single data folder mount of the refactored che-server.  We have already baked in the CHE_DATA variables into the che-launcher improvements.
- [ ] In che-launcher, verify that the CHE_DATA path is writable.
- [x] Special inner syntax for Windows - this has already been incorporated.
- [x] We no longer need to add support for the list of environment variables as the new improvements all map to CHE_DATA.

**Comment by TylerJewell** [comment]
@l0rd - going to close this as it's turned into a big uber-epic, and most of the issues were handled by other tasks along the way.  If we have some mini EPICs that we should open, we can track those and create new ones just for that list of improvements.

**Comment by l0rd** [comment]
@TylerJewell +1
