### ISSUE TITLE
Revise che server devfile

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17032]
### Is your task related to a problem? Please describe.
Che server in che development

### Describe the solution you'd like
Revise che server devfile

- we need to revise components and limits that were used
- create commands to build && test && deploy
- Update development workflow documentation

TODO:
 - [x] base devfile for che-server #17228
 - [ ] commands to build and test
 - [ ] build and run che-server image

**Comment by gazarenkov** [comment]
@skabashnyuk still actual?
