### ISSUE TITLE
Che Deploy Sprint #185

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17051]
June 3 - June 23

### Team
| Name  |  |
| ------------- | ------------- |
| Anatolii   |   |
| Mykola   |    |
| Aleksandr  |   |

### Issues
- [x] Che 7.14.1 Release https://github.com/eclipse/che/issues/17066
  - [x] https://github.com/operator-framework/community-operators/pull/1829 https://github.com/operator-framework/community-operators/pull/1830
- [ ] Specify and use OLM relatedImages in the operator https://github.com/eclipse/che/issues/14993 https://github.com/eclipse/che/issues/16815
  - [ ] https://github.com/eclipse/che-operator/pull/274
  - [ ] https://github.com/eclipse/che-devfile-registry/pull/244
  - [ ] https://github.com/eclipse/che-plugin-registry/pull/485
  - [x] https://github.com/eclipse/che-plugin-registry/pull/494
  - [x] https://github.com/eclipse/che-devfile-registry/pull/248
  - [x] https://github.com/eclipse/che-plugin-registry/pull/493
- [ ] Switch to the new Operator Bundle Format https://github.com/eclipse/che/issues/16928
- [x] [TLS] Deprecate `--self-signed-cert` flag https://github.com/eclipse/che/issues/16764
  - [x] https://github.com/eclipse/che/pull/17044/
  - [x] https://github.com/eclipse/che-operator/pull/301
  - [x] https://github.com/che-incubator/chectl/pull/734
- [x] che-operator release enhancements for 1.14 https://github.com/eclipse/che/issues/17048
  - [x] https://github.com/eclipse/che-operator/pull/300
- [ ] [TLS] Document using self-signed TLS mode in Che https://github.com/eclipse/che/issues/15301
- [ ] Document how to install CRW on AWS https://issues.redhat.com/browse/CRW-923
- [ ]  Cluster wide proxy https://issues.redhat.com/browse/CRW-732 
  - [ ] https://github.com/eclipse/che-operator/pull/272
- [x] Deploying CRW on OpenShift 4.5 https://issues.redhat.com/browse/CRW-913
- [x] CRW 2.1 upgrade fails, "self signed certificate in certificate chain" https://issues.redhat.com/browse/CRW-864 
- [ ] Revise using of rejectUnauthorized https://github.com/eclipse/che/issues/16906
- [ ] Verifying that chectl can deploy multiuser Che without cluster admin privileges https://github.com/eclipse/che/issues/14662
- [ ] chectl should use current namespace if no namespace is specified 
 https://github.com/eclipse/che/issues/16958
- [ ] Devfile and Plugin Registries define its own domain even when default/single mode is configured https://github.com/eclipse/che/issues/14564
- [ ] Test devfiles
- [ ] Configure bots to open workspace to review PR

### Unplanned

- [x] Remove che-tls-secret-creator image for CRW https://issues.redhat.com/browse/CRW-977 
- [x] Che Operator snips proxy URL incorrectly https://issues.redhat.com/browse/CRW-979
- [x] Installation of CRW with OS OAuth support by crwctl failed because operator was unable to get openshift oauth https://issues.redhat.com/browse/CRW-967
- [x] crwctl olm mode deploys CRW 2.1.1, not 2.2.0 https://issues.redhat.com/browse/CRW-976
- [x] chectl server:start with Minikube 1.9+ is failling https://github.com/eclipse/che/issues/17142
- [ ] quay.io operator bundle links to old operator image https://issues.redhat.com/browse/CRW-991

 [Previous Sprint](https://github.com/eclipse/che/issues/16867)
