### ISSUE TITLE
Failed to load 'devfile' registry URL and 'devfiles' meta list in CHE 'single-host' on k8s

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#17076]
### Describe the bug
* If CHE is installed on k8s with using **_single-host_** strategy there absent templates to create workspace on dashboard. After opening dashboard there are apperead two error messages: **_Failed to load the devfile registry URL_** and **_Failed to load devfiles meta list_**.
* Even if to load _devfile_, workspace doesn't start (I used the _[happy-path-workspace.yaml](https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/happy-path-workspace.yaml)_) 

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Prepare _your-cr.yaml_ with setted _single-host_ value:
```
spec:
  server:
    cheImage: ''
    cheImageTag: ''
    selfSignedCert: true
  auth:
    updateAdminPassword: false
  k8s:
    ingressDomain: '\$(minikube ip).nip.io'
    ingressStrategy: 'single-host'
```
2. Install CHE using _chectl_:
```
chectl server:start --platform=minikube --che-operator-cr-patch-yaml=<your-cr.yaml>
```
3. Open _Get Started_ page on dashboard

### Expected behavior
Should be present samples to create workspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (
```
[ashmaraiev@localhost ~]$ minikube version
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1

[ashmaraiev@localhost ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![che-single-host-devfile-meta-data](https://user-images.githubusercontent.com/5408906/83559138-befadb80-a51c-11ea-9033-fddc0dcca617.png)
![che-single-host-network](https://user-images.githubusercontent.com/5408906/83559141-c02c0880-a51c-11ea-8417-2e77ea0aa65d.png)

**An attempt to run ws by loading devfile:**
![che-single-host-start-ws](https://user-images.githubusercontent.com/5408906/83562053-96291500-a521-11ea-85a1-7eea2af69f7e.png)

### Installation method
   - [x] chectl
     * `[ashmaraiev@localhost ~]$ chectl server:start --platform=minikube --che-operator-cr-patch-yaml=/home/ashmaraiev/CHE_PROJECTS/che-single-host-cr.yaml
`
     * `[ashmaraiev@localhost ~]$ chectl version
chectl/0.0.20200527-next.07f741a linux-x64 node-v10.20.1`

   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by sleshchenko** [comment]
I have the feeling that the wrong registries URLs are configured or they are not available at all. There is no much we can do with it on dashboard side, it's why I put `area/install` here

**Comment by l0rd** [comment]
I am closing this issue as I think it's a duplicated of https://github.com/eclipse/che/issues/14564 (and deploy team has it on its current sprint backlog cc @tolusha). 

@artaleks9 feel free to re-open if that's not the case.
