### ISSUE TITLE
Plugins Sprint 185

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#17083]
## Sprint goals
1. Bugs (upstream and CRW)
2. Maintenance / Automation / Technical Debt

### Epics

**Epic: Separate vscode-java version from development target #16851** @tsmaeder 
* [x] Implement proof-of-concept

### CRW
* [x] Investigate using EAP 7.3.1 image as is without manipulation for CRW 2.x [CRW-871](https://issues.redhat.com/browse/CRW-871) @svor 
* [x] New EAP 7.3.1 / microprofile devfile [CRW-876](https://issues.redhat.com/browse/CRW-876) @svor 
* [x] Remove unneeded runtimes from stack images [CRW-919](https://issues.redhat.com/browse/CRW-919) 
* [x] mongodb example doesn't run [CRW-968](https://issues.redhat.com/browse/CRW-968)
* [x] nodejs-configmap deploy task doesn't work [CRW-980](https://issues.redhat.com/browse/CRW-980)
* [x] EAP devfile doesn't compile (7.2.0 vs. 7.3.0?) [CRW-982](https://issues.redhat.com/browse/CRW-982)
* [x] Failed to start debug session for the "NodeJS MongoDb" devfile [CRW-997](https://issues.redhat.com/browse/CRW-997)
* [x] Failed to build default sample in the workspace based on "Java Maven" devfile [CRW-1005](https://issues.redhat.com/browse/CRW-1005)

### Bugs
* [ ] Project cloning fails in proxy environment #17017 @svor 
* [ ] Error highlighting broken in several default stack #15919 @ericwill 
* [ ] [Hosted Che] OpenShift Connector plugin does not work properly #16890 @vinokurig 
* [ ] "Run tasks" calls same Task Provider repeatedly. eclipse-theia/theia#7496 @tsmaeder 
* [ ] Use digests instead of tags to reference images #16047 @vitaliy-guliy 
    * [ ] Update the PR to convert only base images in the devfile registry, for now

### Open PRs From Last Sprint
* [x] Support Che tasks for multi-root workspaces #15540
* [ ] Tekton extension PRs:
    * [ ] Initial contribution of sidecar image for TekTon tooling [PR](https://github.com/che-dockerfiles/che-sidecar-tekton/pull/2)
    * [ ] Add vscode-tekton to the plugin registry [PR](https://github.com/eclipse/che-plugin-registry/pull/473)

### Maintenance / Automation / Technical Debt / Testing
* [ ] Indispensable VS Code Extensions #16663 
    * [ ] [Jira and Bitbucket (Official) - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode) @vitaliy-guliy 
        * [ ] Jira & Bitbucket extension cannot display Settings page (webview based) #17081
* [ ] Automatically generate meta.yaml given a vsx repo+branch+dockerfile #17029 @ericwill 
    * [x] Align plugin folders with their repository names #17100
    * [ ] extensions.json support with automated GitHub action that builds/updates plugins
* [ ] Set up PR Check for Java Che 7 plugins #15797
* [ ] Check for plugin updates and update as many as possible
    * [ ] vscode-java -> 0.61 #17025 @tsmaeder 
    * [ ] Upgrade forked vscode-git to the latest version #16041 @vinokurig 
        * [ ] Implement Timeline API eclipse-theia/theia#7577
        * [ ] [Plugin API] Apply workspace.registerResourceLabelFormatter function eclipse-theia/theia#7946
    * [ ] Upgrade the vscode github-pr-plugin version in the che-plugin registry https://github.com/eclipse/che/issues/16741
        * [ ] Depends on vscode-git being updated
* [ ] Convert sidecar repositories to multi-arch @ericwill 
    * [ ] che-sidecar-java
    * [ ] che-sidecar-go
    * [ ] che-sidecar-python
    * [x] che-sidecar-camelk
    * [ ] Any others as IBM needs them
* [ ] Dependabot update automation for buildx converted repos @ericwill 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 7  | 4 |
| @ericwill | 13  | 8 |
| @tsmaeder | 13  | 8 |
| @svor | 13  | 8 |

**Comment by ericwill** [comment]
Superseded by sprint 185, #17233
