### ISSUE TITLE
Editors Sprint 185

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17086]
Jun 3 - Jun 23

## Goals
1. Multi cursor co-editing capability
2. Better support for VS Code extensions
3. Che Theia UX enhancements
4. Theia upstream focus

#### Multi cursor co-editing capability
- [x] Investigate multi cursor co-editing capability for Che Theia https://github.com/eclipse/che/issues/16907

#### Better support for VS Code extensions
- Implement VS Code Built-in Commands https://github.com/eclipse-theia/theia/issues/4050
  - [x] `workbench.view.explorer`
- [ ] Theia WebView support for remote plugins https://github.com/eclipse/che/issues/16870
- [ ] Finalize Monaco upgrade in upstream Theia https://github.com/eclipse-theia/theia/issues/7697

#### Che Theia UX enhancements
- [ ] Open Che Workspace from Che Theia https://github.com/eclipse/che/issues/17034

#### Collaboration in upstream Theia
[PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-06-03..2020-06-23+is%3Apr) | [PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-06-03..2020-06-23+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-06-03..2020-06-23+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-06-03..2020-06-23)

### Unplanned/Blockers
- [x] stabilized Che Theia build:
  - fixed incompatibility with the latest Theia https://github.com/eclipse/che-theia/pull/768
  - temporarily disabled non-stable Cypress test https://github.com/eclipse/che-theia/pull/765
  - related patches for 7.14 release https://github.com/eclipse/che-theia/pull/769
- [ ] Make Che Theia Cypress tests stable https://github.com/eclipse/che/issues/17095
- [x]  Make Che Theia release script support macOS https://github.com/eclipse/che-theia/pull/764
- [x] Che Theia release script fails to fetch Theia next version from npmjs.org https://github.com/eclipse/che/issues/17181
- [x] Che Theia release script sets different Theia versions for z-releases https://github.com/eclipse/che/issues/17188

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 12  | 7
| Roman   | 12  | 7
| Artem | 10  | 6

---
[Previous Sprint](https://github.com/eclipse/che/issues/16915)
