### ISSUE TITLE
Preparation for Openshift Command Line Terminal release

### ISSUE THREAD

**Issue by JPinkney** [eclipse-che/che#17084]
### Is your task related to a problem? Please describe.

This issue tracks everything that still needs to be done before we can release Openshift Command Line Terminal:

- [x] Create a git repo under redhat-developers where the Openshift CLT csv's can live
- [x] [OpenShift Command Line Terminal image tools](https://github.com/eclipse/che/issues/16938)
- [x] [Make workspace operator reuse devworkspace-api](https://github.com/eclipse/che/issues/16626)
- [x] [Create logo for Che Workspace Operator/Openshift Terminal](https://github.com/eclipse/che/issues/17043)
- [x] Airgap mode for web-terminal https://issues.redhat.com/projects/WTO/issues/WTO-4
- [x] Decrease timeframe when CRD is registered and webhooks are not created https://github.com/eclipse/che/issues/17200

### The components to release
They are placed in the order they should be released:
1. WebTerminal Tooling
2. WebTerminal Exec
3. WebTerminal Controller (depends on 1. and 2. since the released images are supposed to appear in default configuration and internal plugin registry)
4. WebTerminal Operator
