### ISSUE TITLE
Improve Che Release process: more automation

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17101]
Some enhancements we can do for the Che release in 7.x:

- [x] Add repo branching/tagging to che-docs repository #17596

- [y] WONTDO stop release if any child processes fail (eg., don't release machine exec if theia dies)
  - https://gist.github.com/nickboldt/248bfd3e89c03042507ba46e0dac71da

- [ ] Verify that plugin images referenced in the plugin registry actually exist in Quay #16501

- [ ] stop release if required artifacts are not found (eg., plugin-registry 7.14.2 container not available in quay, so don't start releasing che server)

- [x] (che-operator) git diff w/ exclude option would not work on Centos CI (probably because of old 1.8 version of Git).

- [x] (che-operator) rework https://github.com/eclipse/che-operator/blob/master/olm/push-olm-files-to-quay.sh to utilize special bot accounts that are available on Centos CI (rework wasn't needed afterall, just enabling newly added secrets from Vault ) 

- [ ] include che-operator, che-operator PR generation, and chectl in overall release script
  - [x] replace manual testing of deployment on minikube w/ centos ci automated test
  - [ ] replace manual testing of deployment on openshift w/ PR validation check that triggers CRW QE Jenkins automated e2e test to deploy on OCP 4.4, 3.11, 4.5, 4.3

- [x] push to Maven Central directly (no final human check step) - https://github.com/eclipse/che/issues/16043
  - [x] re-enable release-time build tests/checks to avoid building against snapshots
  - [x] block pushing to maven central if code refers to SNAPSHOT versions

- [x] implement option to release Che Server with or without parent via parameter
- [ ] add more documentation covering functionality of specific usecases (e.g. skipping/rebuilding particular items from release )
```
$➔ count=$(grep -R "SNAPSHOT" * | grep pom.xml | wc -l); if [[ $count -gt 0 ]]; then echo "[ERROR] Found $count files which use a SNAPSHOT version. Cannot proceed with release."; exit 1; fi
[ERROR] Found 303 files which use a SNAPSHOT version. Cannot proceed with release.
```

- [ ] instead of creating GH issues to manage weekly 7.y.z releases, release job should generate an email and send to che-dev@ with new build announcement

- [ ] Should Che releases be GH releases (and thus update the 'latest release' metadata) ? #17177

- [ ] When Che 7.y.0 releases are done, send reminder to TLs to clean milestones of any outstanding unresolved issues #17579

- [ ] generate branches in https://github.com/eclipse/che-jwtproxy/tree/7.18.x and https://github.com/che-incubator/kubernetes-image-puller/tree/7.18.x so we're not using master branch in downstream

**Comment by skabashnyuk** [comment]
@nickboldt wdyt about id to use jboss-parent instead of che-parent?

**Comment by nickboldt** [comment]
> wdyt about idea to use jboss-parent instead of che-parent?

If that will work for Che builds, then sure. I would be surprised if jboss-parent works for us OOTB. Feel free to try it and see!

(But also given the Che parent is only updated a few times a month, is it that big a deal to maintain it? https://github.com/eclipse/che-parent//commits )

**Comment by nickboldt** [comment]
Followup in https://github.com/eclipse/che/issues/17748
