### ISSUE TITLE
Workspace related commands should be consistent with Che

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17106]
### Is your enhancement related to a problem? Please describe.
Che Theia provides a set of commands that are related to Theia Workspace which is similar to VS Code Workspace.
![image](https://user-images.githubusercontent.com/1636395/83914697-688ad880-a77a-11ea-98f6-b1fe9c11f5a2.png)

While the experienced VS Code users are pretty familiar with this Workspace concept, it differs from Che Workspace. That may confuse the existing Che users as the behavior of these commands is inconsistent with Che Workspace.

At the same time, it makes sense to have these Workspace commands providing functionality related to Che Workspaces.

### Describe the solution you'd like
Replace Theia Workspace commands with Che Workspace commands.
- [x] `Open Workspace...` - lists all Che Workspaces to open any https://github.com/eclipse/che/issues/17237
- [x] `Open Recent Workspace...` - lists 3-5 recent Che Workspaces to open any https://github.com/eclipse/che/issues/17034
- [x] `Close Workspace` - closes dev environment (Che Theia) and navigates to Dashboard https://github.com/eclipse/che/issues/17238
- [x] `Save Workspace As...` - exports Che Workspace definition to Devfile https://github.com/eclipse/che/issues/17239

### Describe alternatives you've considered
Find a good name replacement for Theia Workspaces related commands to resume them.

cc @benoitf @l0rd

**Comment by azatsarynnyy** [comment]
I was thinking about a good replacement for Theia's `Workspace` term, e.g.:
- `Workspace Roots`
- `Root Folders`
- `Root Folders Layout`
- etc.

I'd like to use `Workspace Roots`.
So, to keep the existing commands I propose to rename them as follows:
- `Open Workspace Roots...`
- `Open Recent Workspace Roots...`
- `Save Workspace Roots As...`
- `Close Workspace Roots`

@benoitf @l0rd WDYT?

**Comment by azatsarynnyy** [comment]
linked with the separate issues

**Comment by l0rd** [comment]
> I was thinking about a good replacement for Theia's `Workspace` term, e.g.:
> 
> * `Workspace Roots`
> * `Root Folders`
> * `Root Folders Layout`
> * etc.
> 
> I'd like to use `Workspace Roots`.
> So, to keep the existing commands I propose to rename them as follows:
> 
> * `Open Workspace Roots...`
> * `Open Recent Workspace Roots...`
> * `Save Workspace Roots As...`
> * `Close Workspace Roots`
> 
> @benoitf @l0rd WDYT?

I like the proposal @azatsarynnyy

**Comment by sunix** [comment]
+1 for workspace roots
it would be consistent to that proposal: https://github.com/eclipse/che/issues/15347

**Comment by azatsarynnyy** [comment]
All sub-tasks have been done.

**Comment by sunix** [comment]
>  Save Workspace As... - exports Che Workspace definition to Devfile #17239

why not just `Export workspace definition to Devfile` rather than `Save Workspace As ...` which is not clear ..
