### ISSUE TITLE
DevWorkspace Operator Images, Repos and API groups

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17122]
### Is your enhancement related to a problem

We need to consolidate the different repos, APIs groups, k8s resources and container names that are used in the devworkspace and web terminal operators.

### Describe the solution you'd like

**Create the following gh repositories**

- [x] devfile/devworkspace-operator: go code of the controller and OLM files, that's currently named `che-incubator/che-workspace-operator`
    - [x] Move `che-incubator/che-workspace-operator` to this new repo
- [x] [rh-developer/web-terminal-operator](https://github.com/redhat-developer/web-terminal-operator): OLM files for the Web terminal RH product
- [x] [rh-developer/web-terminal-tooling](https://github.com/redhat-developer/web-terminal-tooling): https://github.com/eclipse/che/issues/16938 (it's currently rh-developer/cloud-tools)
- [x] [rh-developer/web-terminal-exec](https://github.com/redhat-developer/web-terminal-exec): synced repo with `eclipse/che-machine-exec`

**k8s resources naming**

- [x] API [group naming](https://github.com/eclipse/che/issues/17121):
    - [x] workspace.devfile.io/v1alpha1/DevWorkspace
    - [x] controller.devfile.io/v1alpha1/Component - https://github.com/devfile/devworkspace-operator/pull/103
    - [x] controller.devfile.io/v1alpha1/WorkspaceRouting - https://github.com/devfile/devworkspace-operator/pull/103
- [x] Rename annotations/labels to use `controller.devfile.io` - https://github.com/che-incubator/che-workspace-operator/pull/101
- [x] Rename annotations webhooks  to use `controller.devfile.io` - https://github.com/che-incubator/che-workspace-operator/pull/101

**Container Images**

- [x] Validate that brew built images are suitable for nightly testing even without a subscription. - > It's not suitable. There is https://quay.io/organization/wto to mirror containers built-in brew
- [ ] CI to push build results of `devfile/devworkspace-operator` to
  - [x] quay.io/devfile/devworkspace-controller (`Dockerfile`) - GitHub Action
  - [ ] quay.io/web-terminal/operator (`Dockerfile.rhel`) - rh brew ([RCMAUTO-2894](https://projects.engineering.redhat.com/projects/RCMAUTO/issues/RCMAUTO-2894))
- [x] CI to push build results of `rh-developer/web-terminal-operator` to `quay.io/web-terminal/operator-metadata` - rh brew ([RCMAUTO-2894](https://projects.engineering.redhat.com/projects/RCMAUTO/issues/RCMAUTO-2894))
- [ ] CI to push build results of `rh-developer/web-terminal-tooling` to `quay.io/web-terminal/tooling` - rh brew ([RCMAUTO-2892](https://projects.engineering.redhat.com/projects/RCMAUTO/issues/RCMAUTO-2892))
- [ ] CI to push build results of `rh-developer/web-terminal-exec` to `quay.io/web-terminal/exec` - rh brew ([RCMAUTO-2893](https://projects.engineering.redhat.com/projects/RCMAUTO/issues/RCMAUTO-2893))

**Comment by sleshchenko** [comment]
At this point, we already moved to agreed apiGroup and have all repos created. Closing it and Automation is going to appear as result of the following epic: Automate Web Terminal release process https://issues.redhat.com/browse/WTO-22
