### ISSUE TITLE
Failed to load 'devfile' registry URL and 'devfiles' meta list in CHE 'single-host' on k8s

### ISSUE THREAD

**Issue by sneely333** [eclipse-che/che#17149]
Hi,
I installed che on a microk8s system using a valid wildcard cert and single host. I am running into the same behavior reported in ticket #17076 regarding getting errors that the devfile registry url and dev files meta list failed to load in gui and also not being able to launch a workspace.

The description on ticket 17076, describes it perfectly
"If CHE is installed on k8s with using single-host strategy there absent templates to create workspace on dashboard. After opening dashboard there are apperead two error messages: Failed to load the devfile registry URL and Failed to load devfiles meta list.
Even if to load devfile, workspace doesn't start."
The issue 17076 was closed and issue 14564 was referenced.  None of the issues or symptoms in 14564 exist in my configuration so I believe this may have a separate root cause.  (14564 appears to be closed also)

### Che version
-  [x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. install microk8s and related modules:
sudo snap install microk8s --classic; sudo snap alias microk8s.kubectl kubectl; for i in ingress storage dns registry; do microk8s.enable $i; done
2.kubectl proxy --accept-hosts=. --address=127.0.0.1 --port 8080 & after installing a valid ssl cert as che-tls
2. install che on microk8s via "./chectl server:start -n che --domain=myhost.com --platform=k8s --installer=operator --che-operator-cr-patch-yaml=values.yaml 

cat values.yaml:
ApiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  k8s:
    ingressStrategy: single-host

2. Log in to interface via admin (or set up user and do the same)
3. See error
### Expected behavior
I expect no errors and being able to launch a workspace.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x ] other: microk8s
### Installation method
   - [ x] chectl
     * chectl/7.13.2 linux-x64 node-v10.20.1
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
 I do not see any errors in the pods themselves except when I try to launch a workspace. 
The error in the che pod at that time is:
 Unable to perform '[mkdir, -m, 777, -p, /tmp/job_mount/workspaceoie7w3lctep8f6sx/che-logs-che-plugin-broker/]' command for the workspace 'workspaceoie7w3lctep8f6sx' cause: 'Waiting for pod 'mkdir-workspaceoie7w3lctep8f6sx' reached timeout'
2020-06-12 02:49:31,437[aceSharedPool-4]  [WARN ] [.i.k.KubernetesInternalRuntime 265]  - Failed to start Kubernetes runtime of workspace workspaceoie7w3lctep8f6sx. Cause: Plugins installation process failed. Error: Plugin brokering process for workspace workspaceoie7w3lctep8f6sx failed with error: Failed to download plugin meta: failed to unmarshal downloaded meta.yaml for plugin 'eclipse/che-machine-exec-plugin/7.13.2': yaml: line 8: mapping values are not allowed in this context

Any suggestions would be appreciated

**Comment by tolusha** [comment]
Fixed by https://github.com/eclipse/che-operator/pull/341

**Comment by sneely333** [comment]
Hi, This is reported as closed but I installed the latest release today (7.19.2) an experienced the exact same problem.  
Is there something that I need to manually change in the helm charts to get single-host to work?
Thanks
Susan

**Comment by sneely333** [comment]
@tolusha - I am experiencing the same identical issue in 7.19.2.  Should I open up a new issue or can this one be re-opened?

**Comment by tolusha** [comment]
@sneely333 

I've just checked with the following CR patch on minikube using chectl 7.19.2 (use `chectl update stable` to update to the latest stable version)

`chectl server:start --platform minikube --che-operator-cr-patch-yaml patch.yaml`
```
spec:
  k8s:
    ingressStrategy: single-host
```

Anyway, feel free to open another issue and provide details to reproduce. 
Thank you.
