### ISSUE TITLE
Simpler user experience for working with terminals with an ‘all-in-one’ approach

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17209]
### Is your task related to a problem? Please describe.
Today, we can open terminals in each container from the workspace view.
But from UX perspective, it may be hard to understand that if I need `mvn` tool I need to use a specific container, then to use `git` it may be provided by another container, etc.

### Alternative n.1: command proxy 

Ideally, I should only have to open a single terminal allowing me to use tools provided by different containers.

First, user should not connect/see terminals of the sidecar containers by default as it' is mostly 'internal' stuff.
For example, if user need `mvn` command, probably it requires a 'user container' providing the `mvn` command line tool which the expected version.
And the same for each tool: `git`, `mvn`, `python`,  `go`, `oc`, `kubectl`, etc.

There could be a 'all-in-one' image with latest version of each `common` tool but it's somehow against container pattern where each image is bringing what is needed.

On another hand, it would be nice if when a container is added, it could add/register a cli that could be available in some/all terminals.

For example, if `che` container is added, `che` command could be shared and then available from other containers.

We could also have 'proxy command' in every terminal redirecting i/o to the correct binary in its own sidecar.

### Alternative n.2: two containers (editor + all-in-one)

In this alternative we are running the editor in a dedicated container and the plugins/extensions in the tooling container that is supposed to have all the extensions prerequisites:

- [x] Make it possible to run an extension in any devfile component rather then in its own sidecar
- [ ] Build a universal tooling image that has all the prerequisites to run Che samples with the extensions that we support

### Alternative n.3: one all-in-one container (for IntelliJ and, eventually, VS Code)

Run everything, even the editor in the all-in-one container:

- [ ] Make it possible to run the editor in any devfile component rather then in its own sidecar
  - [ ] Investigate the different approches:
	  - [ ] editor can be injected as we currently do for the che-theia remote endpoint
	  - [ ] editor can be provided in a folder mounted in the component
	  - [ ] editor can be provided with Katalogos
	  - [ ] component image can be rebuild to include the editor

**Comment by benoitf** [comment]
I did one POC there https://github.com/benoitf/che-remote-call

**Comment by sympatheticmoose** [comment]
To me what would be ideal is if we can combine this with the image used by the Web Terminal. So we have a (customizable) developer tooling image which would be shared across Web Terminal and Che/CodeReady Workspaces for a more unified experience. 

We'll need to figure out how this fits with plans around a shared devfile registry... as an all-in-one container probably doesn't fit with odo use and language-specific containers. Maybe its just a new devfile which references this all-in-one container image, and this is what gets used whenever someone uses a factory/starts a workspace with no devfile, whereas if someone starts a workspace from a devfile which references a language-specific container image.

**Comment by l0rd** [comment]
After discussion at latest dw cabal we decided to remove this issue from the scope of milestone "DevWorkspace Integration - STEP3".
