### ISSUE TITLE
Che Deploy Sprint #186

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#17220]
### Timeframe

| June 24    |  July 14    |
| ------------- | ------------- | 

### Team
| Name  |  
| ------------- | 
| Anatolii   |  
| Mykola   |   
| Aleksandr  |  

### Issues 

- [x] Specify and use OLM relatedImages in the operator https://github.com/eclipse/che/issues/14993 https://github.com/eclipse/che/issues/16815
  - [x] https://github.com/eclipse/che-operator/pull/274
  - [x] https://github.com/eclipse/che-devfile-registry/pull/244
  - [x] https://github.com/eclipse/che-plugin-registry/pull/485
- [ ] Switch to the new Operator Bundle Format https://github.com/eclipse/che/issues/16928
- [x] [TLS] Document using self-signed TLS mode in Che https://github.com/eclipse/che/issues/15301
  - [x] https://github.com/eclipse/che-docs/pull/1331
- [x]  Cluster wide proxy https://issues.redhat.com/browse/CRW-732 
  - [x] https://github.com/eclipse/che-operator/pull/272
- [ ] ~~chectl should use current namespace if no namespace is specified  https://github.com/eclipse/che/issues/16958~~
- [ ] Devfile and Plugin Registries define its own domain even when default/single mode is configured https://github.com/eclipse/che/issues/14564
- [x] quay.io operator bundle links to old operator image https://issues.redhat.com/browse/CRW-991
- [x] RH SSO deployment error 'password auth failed for user "keycloak"' when installing CRW 2.2.0.RC1 on OCP 4.5 with --os-oauth https://issues.redhat.com/browse/CRW-987

### Unplanned
- [x] Docs review

 [Previous Sprint](https://github.com/eclipse/che/issues/17051)
