### ISSUE TITLE
Plugins Sprint 186

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#17233]
## Sprint goals
1. Bugs (upstream and CRW)
2. Maintenance / Automation / Technical Debt

### CRW
* [x] CRW 2.2 docs verification
* [ ] New EAP 7.3.1 / XP 1.0 / microprofile devfile [CRW-876](https://issues.redhat.com/browse/CRW-876)
* [x] Can't execute commands inside CRW 2.2.0 workspace on OSD 4.3 [CRW-1006](https://issues.redhat.com/browse/CRW-1006)
* [x] The 'deploy to Openshift' command doesn't work in the "Red Hat Fuse" workspace [CRW-1024](https://issues.redhat.com/browse/CRW-1024)

### Bugs
* [x] Project cloning fails in proxy environment #17017 @svor 
* [x] Error highlighting broken in several default stack #15919 @tsmaeder 
* [x] [Hosted Che] OpenShift Connector plugin does not work properly #16890 @vinokurig 
* [x] sonarlint plugin doesn't work #16589 @tsmaeder 
* [x] .NET Core 3.1 shows lots of Problems #17045 @svor 
* [x] Use digests instead of tags to reference images #16047 @vitaliy-guliy 
    * Work has been postponed due to new requirements which need to be discussed

### Open PRs From Last Sprint
* [ ] "Run tasks" calls same Task Provider repeatedly. eclipse-theia/theia#7496
* [ ] Tekton extension PRs:
    * [ ] Initial contribution of sidecar image for TekTon tooling [PR](https://github.com/che-dockerfiles/che-sidecar-tekton/pull/2)
    * [ ] Add vscode-tekton to the plugin registry [PR](https://github.com/eclipse/che-plugin-registry/pull/473)

### Maintenance / Automation / Technical Debt / Testing
* [x] [Jira and Bitbucket (Official) - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode)
    * [x] Jira & Bitbucket extension cannot display Settings page (webview based) #17081 @vitaliy-guliy 
* [x] Che Plugin Registry VSX Daily Check #17014 @ericwill 
    * [x] Merge report generation script
    * [x] Create GH action and publish to `gh-pages` branch
* [x] Automatically generate meta.yaml given a vsx repo+branch+dockerfile #17029 @ericwill 
    * Work postponed until a vsix hosting solution can be found
* [ ] Set up PR Check for Java Che 7 plugins #15797 @svor 
* [ ] Check for plugin updates and update as many as possible
    * [ ] Upgrade forked vscode-git to the latest version #16041 @vinokurig 
        * [ ] Implement Timeline API eclipse-theia/theia#7577
    * [ ] Upgrade the vscode github-pr-plugin version in the che-plugin registry https://github.com/eclipse/che/issues/16741 @vinokurig 
        * [ ] Depends on vscode-git being updated
* [x] Update go plugin @vitaliy-guliy 
* [x] go needs to be updated to the latest version #16182
    * [x] Put old version of che-sidecar-go on 1.12.9 branch, latest sidecar image lives on master
    * [x] Update [che-golang-1.12 image](https://github.com/eclipse/che-devfile-registry/blob/master/arbitrary-users-patch/base_images) to latest
    * [x] Update the go image to use the upstream golang image as a base

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 10  | 6 |
| @ericwill | 14  | 8 |
| @tsmaeder | 14  | 8 |
| @svor | 13  | 8 |

**Comment by ericwill** [comment]
Superseded by sprint 187, #17418
