### ISSUE TITLE
Editors Sprint 186

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17240]
June 24 - July 14

## Goals
1. Finalize Monaco upgrade
2. Jupyter Notebooks support
3. Workspace related commands consistent with Che
4. Multi-root Workspaces
5. Dogfooding
6. Docs review
7. Theia upstream focus

- [ ] Finalize Monaco upgrade in upstream Theia https://github.com/eclipse-theia/theia/issues/7697
- [x] Make Che Theia Cypress tests stable https://github.com/eclipse/che/issues/17095

#### Jupyter Notebooks support
- [ ] CustomEditor Theia Plugin API https://github.com/eclipse-theia/theia/issues/6636

#### Workspace related commands consistent with Che https://github.com/eclipse/che/issues/17106
- [x] Impossible to get workspace list with machine token https://github.com/eclipse/che/issues/17246
- [x] Message handler to start workspace by id in dashboard https://github.com/eclipse/che/issues/17361
- [x] Open recent Che Workspace from Che Theia https://github.com/eclipse/che/issues/17034
- [ ] Open Workspace from Che Theia https://github.com/eclipse/che/issues/17237
- [ ] Export Che Workspace definition to Devfile from Che Theia https://github.com/eclipse/che/issues/17239
- [ ] Stop Workspace from Che Theia https://github.com/eclipse/che/issues/17238

#### Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212

#### Dogfooding
- [x] che-theia-all.devfile.yaml fails when running build https://github.com/eclipse/che/issues/16413

#### Docs review
- [x] Review Che Theia End-User Guide https://github.com/eclipse/che/issues/17236

#### Collaboration in upstream Theia
[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-06-24..2020-07-14+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-06-24..2020-07-14+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-06-24..2020-07-14+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-06-24..2020-07-14)

### Unplanned/Blockers
- [x] Che Theia build is failed https://github.com/eclipse/che/issues/17235
- [x] Che Theia GitHub Workflow should respect the build parameters provided in a PR's branch https://github.com/eclipse/che/issues/17305
- [x] Adapt Che Theia to upstream Theia with removed JSON extension https://github.com/eclipse/che/issues/17319
- [x] Investigate why Che Theia build fails on CI https://github.com/eclipse/che/issues/17332
#### CRW
- [x] Connection Timeout when running tasks in Che-Theia behind a proxy https://issues.redhat.com/browse/CRW-1042
- [x] Can't execute commands inside CRW 2.2.0 workspace on OCP/OSD 4.x on AWS https://issues.redhat.com/browse/CRW-1006
- [x] Che task doesn't finish execution in CRW IDE deployed to OCP on AWS https://issues.redhat.com/browse/CRW-1053
- [x] Proxy support for Task Plugin should be backported to Che Theia 7.15.x https://github.com/eclipse/che/issues/17292

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 13  | 8
| Roman   | 13  | 8
| Artem | 14  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/17086)
