### ISSUE TITLE
Che Deploy Sprint #187

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17379]
### Timeframe

| July 15    |  August 4    |
| ------------- | ------------- | 

### Team
| Name  |  
| ------------- | 
| Anatolii   |  
| Mykola   |   
| Aleksandr  |  

### Issues 

- [ ] Workspace startup fails when OCP 4 cluster-proxy has Institutional CA https://issues.redhat.com/browse/CRW-1054
- [x] CRW 2.2 OCP topology view not working as expected https://issues.redhat.com/browse/CRW-1078
- [x] As the admin, I want to deploy Eclipse Che via the operatorhub with external DB (RDS) and internal keycloak https://github.com/eclipse/che/issues/17274 
  - [x] https://github.com/eclipse/che-operator/pull/371
  - [x] https://github.com/eclipse/che-docs/pull/1430
- [x] Clarify behaviour of chectl/crwctl 's default installer mode in inline docs https://github.com/eclipse/che/issues/17165
- [x] Devfile and Plugin Registries define its own domain even when default/single mode is configured https://github.com/eclipse/che/issues/14564
  - [x] https://github.com/eclipse/che/pull/17392
  - [x] https://github.com/eclipse/che-operator/pull/341
- [ ] Switch to the new Operator Bundle Format https://github.com/eclipse/che/issues/16928

 [Previous Sprint](https://github.com/eclipse/che/issues/17220)
