### ISSUE TITLE
Editors Sprint 187

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17383]
Jul 15 - Aug 4

## Goals
1. CodeReady Workspaces bugs
2. Jupyter Notebooks support (FS API)
3. Workspace related commands consistent with Che
4. Theia upstream focus

#### CodeReady Workspaces bugs
- [x] Tasks are not properly killed and remain in the "Terminate Task" list forever [CRW#827](https://issues.redhat.com/browse/CRW-827)

#### Jupyter Notebooks support https://github.com/eclipse/che/issues/16818
- [ ] Adapt Che Theia to the new Theia FS API https://github.com/eclipse/che/issues/17357 (WIP PR https://github.com/eclipse/che-theia/pull/798)

#### Workspace related commands consistent with Che https://github.com/eclipse/che/issues/17106
- [x] Open Workspace from Che Theia https://github.com/eclipse/che/issues/17237
- [x] Export Che Workspace definition to Devfile from Che Theia https://github.com/eclipse/che/issues/17239
- [x] Stop Workspace from Che Theia https://github.com/eclipse/che/issues/17238 (PR: https://github.com/eclipse/che-theia/pull/806)

#### Collaboration in upstream Theia
[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-07-15..2020-08-04+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-07-15..2020-08-04+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-07-15..2020-08-04+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-07-15..2020-08-04)

- [ ] Upgrade embedded editor to Monaco 0.20.0 https://github.com/eclipse-theia/theia/issues/7697 (WIP PR https://github.com/eclipse-theia/theia/pull/8010)
- [x] Remove `@theia/languages` dependency in Che Theia https://github.com/eclipse/che/issues/17342

### Unplanned/Blockers
- [x] HTML LS can't start https://github.com/eclipse/che/issues/17381
- [ ] Workspace components have to use provided custom certificates https://github.com/eclipse/che/issues/17440
- [ ] Adapt Che Theia to upstream changes https://github.com/eclipse/che/issues/17550

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 10  | 6
| Roman   | 14  | 8
| Artem | 3  | 2

---
[Previous Sprint](https://github.com/eclipse/che/issues/17240)
