### ISSUE TITLE
QE-2020-08-04 (Sprint: 187)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#17380]
### Unplanned 
- [x] [QE_TASK] Change default value of the "TS_SELENIUM_VALUE_TLS_SUPPORT" environment variable #17503 1sp
- [x] After clicking to the "Clear all" button of the notification center notifications still present #17521 1sp
- [x] Clean up ending slash in TS_SELENIUM_BASE_URL when run E2E typescript selenium tests #17533 1sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 15 |
| Maxim Musienko | 15 |
| Dmytro Nochevnov | 15 |
| Igor Ohrimenko | 15 |
| Sergey Skorik | 15 |
|Radim Hopp | 5 |
| Total |  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |

### Reference
