### ISSUE TITLE
Measure time for components during workspace startup

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#17393]
### Is your task related to a problem? Please describe.
This issue is based on https://github.com/redhat-developer/che-functional-tests/issues/468. There is a test in place that can measure workspace startup time https://github.com/che-incubator/che-test-harness. The goal is to extend that test to have better granularity.

_Coppied:_
- [ ] **STEP1** Evaluate the global time for Che workspaces bootstrap 
- [ ] **STEP2** Evaluate the elapsed time for all the phases of the workspaces bootstrap: 
  - [ ] Plugin broker start
  - [ ] Plugin broker processing
  - [ ] Marked as starting
  - [ ] Pull eclipse/che-dev:nightly
  - [ ] Pull wsskeleton/che-machine-exec
  - [ ] Pull wsskeleton/che-hello
  - [ ] Pull eclipse/che-theia:plugin-id-nightly
  - [ ] Workspace containers all running
  - [ ] Theia start
  - [ ] Start completed
- [ ] **STEP3** Evaluate the elapsed time to clone a project
- [ ] **STEP4** Evaluate the elapsed time to build a project
- [ ] **STEP5** Use last 7 days timing results to evaluate the delta with current build (using a weighted average of last 7 days)

**Comment by amisevsk** [comment]
I may be out of date on this as I haven't looked too deeply in a little while, but I would suggest revising the **STEP2** substeps to be something like:

- [ ] **STEP2** Evaluate the elapsed time for all the phases of the workspaces bootstrap: 
  - [ ] Marked as starting
  - [ ] Plugin metadata broker start
  - [ ] Plugin metadata broker processing
  - [ ] Create workspace pod
  - [ ] Pull eclipse/che-plugin-artifacts-broker
  - [ ] Plugin artifacts broker processing (this occurs in an init container and is the "download vsixes" step; it is slower on *first* start for persistent workspaces)
  - [ ] Pull eclipse/che-dev:nightly
  - [ ] Pull wsskeleton/che-machine-exec
  - [ ] Pull wsskeleton/che-hello
  - [ ] Pull eclipse/che-theia:plugin-id-nightly
  - [ ] Workspace containers all running
  - [ ] Theia start
  - [ ] Start completed

In particular, I believe hosted Che has encountered relatively minor slowdowns in the plugin artifacts broker phase, if e.g. the CDN serving vsixes is slow.

**Comment by Katka92** [comment]
Thak you for your input!
