### ISSUE TITLE
Plugins Sprint 187

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#17418]
## Sprint goals
1. Bugs (upstream and CRW)
2. Maintenance / Automation / Technical Debt

### CRW
* [ ] CRW 2.3 Improved default devfiles [CRW-1046](https://issues.redhat.com/browse/CRW-1046) @svor 
    * [x] New EAP 7.3.1 / microprofile devfile [CRW-876](https://issues.redhat.com/browse/CRW-876)
    * [x] Remind users to first oc login in all devfiles that support openshift deployment [CRW-1028](https://issues.redhat.com/browse/CRW-1028)
* [x] Start of CRW 2.0.0 "java-eap-maven" workspace has failed after update to CRW 2.1.1 for OCP cluster admin user on OCP 3.11 [CRW-829](https://issues.redhat.com/browse/CRW-829) @svor 
* [x] Failed to launch an embedded application of the "Java EAP Maven" stack in the debug mode [CRW-617](https://issues.redhat.com/browse/CRW-617) @svor 
* [x] OpenShift connector plugin doesn't work out of the box [CRW-807](https://issues.redhat.com/browse/CRW-807) @vinokurig 
* [x] Fix naming of Camel devfile [CRW-1049](https://issues.redhat.com/browse/CRW-1049) @svor 
* [x] Verify if the devfile example is suitable for CRW [CRW-2003](https://issues.redhat.com/browse/RHDEVDOCS-2003) @svor 

### Bugs
* [x] Openshift connector and Che: the extension is not keeping the state after workspace restart. #15270 @vinokurig 
* [x] Helm binary is missing when using OpenShift Connector extension #16130 @ericwill 
* [x] Docker LS not working in Quarkus stack #17123 @vitaliy-guliy 
* [x] Golang stop-outyet command throws out status code 143 #17005 @vitaliy-guliy 
    * [x] Go tasks not terminating #16141
* [ ] in Java, the code snippets `try_catch`, `main` and maybe more are not working #16502 @tsmaeder 
* [ ] [Plugin Registry] [airgap] Each plugin should display proper icon #14510 @vitaliy-guliy 
* [ ] Workspace panel is not getting update with newly added task #13666 @tsmaeder 
* [ ] Installing Java Test Runner Support for Java #14871 @tsmaeder 
* [x] Upgrade Go version to support realworld sample #13803 @vitaliy-guliy 
* [x] An error appears when starting a workspace with the OpenShift-connector plugin #17471 @vinokurig 
* [x] Openshift autologin should help the user if the browser blocking popups #16930 @vinokurig 

### Open PRs From Last Sprint
* [ ] Tekton extension PRs:
    * [x] Initial contribution of sidecar image for TekTon tooling [PR](https://github.com/che-dockerfiles/che-sidecar-tekton/pull/2)
    * [ ] Add vscode-tekton to the plugin registry [PR](https://github.com/eclipse/che-plugin-registry/pull/473)
* [x] Describe running and debugging plugins in sidecars eclipse/che-theia#803

### Maintenance / Automation / Technical Debt / Testing
* [ ] Che Plugin Registry VSX Daily Check #17014 @ericwill 
    * [x] Add support for checking theia built-ins
    * [ ] Add support for checking sidecar image versions and preventing mismatches
* [ ] Set up PR Check for Java Che 7 plugins #15797 @svor 
* [ ] Check for plugin updates and update as many as possible
    * [x] vscode-xml -> 0.13.0
    * [ ] Upgrade forked vscode-git to the latest version #16041 @vinokurig 
        * [ ] Implement Timeline API eclipse-theia/theia#7577
    * [ ] Upgrade the vscode github-pr-plugin version in the che-plugin registry https://github.com/eclipse/che/issues/16741
        * [ ] Depends on vscode-git being updated
* [ ] [Plugin-Api] Apply authentication API eclipse-theia/theia#7661
* [ ] [Plugin API] Apply workspace.registerResourceLabelFormatter function eclipse-theia/theia#7946 @vinokurig 
* [x] Remove deprecated plugins from sprint 184 #17000 @ericwill 
* [x] Drop Java 8 support in the Quarkus plugins #16790 @ericwill 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 12  | 7 |
| @vinokurig  | 15  | 8 |
| @ericwill | 13  | 8 |
| @tsmaeder | 15  | 8 |
| @svor | 7  | 4 |

**Comment by ericwill** [comment]
Superseded #17532
