### ISSUE TITLE
[dashboard] Rework the grids and related behavior

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1742]
This epic will handle all the changes needed for redesigning grids in dashboard, reviewing related actions to have one consistent behavior.
- [ ] create common grid component
- [ ] rework all lists of workspaces, users, projects, registries, GH repositories, factories, samples
- [ ] improve search component
- [ ] add list control buttons at the top

**Comment by ashumilova** [comment]
PR for tracking https://github.com/eclipse/che/pull/1680

**Comment by TylerJewell** [comment]
Added formal epic tracking with all listed issues and details #1762
