### ISSUE TITLE
Simplify transition between dashboard and IDE

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1743]
This epic contains issues to improve and simplify the loading screens of dashboard and IDE, the transition between dashboard and IDE, proper restarting workspace runtime in IDE, handling the error and empty states in dashboard and IDE.
- [x] Loading flow when loading IDE is flickering  #1752
- [x] Automatically open the IDE after creating a project #1753
- [x] Create a new loader to replace the vertical bars #1754
- [x] Add syntax coloration to machine outputs when starting a workspace #1755
- [x] Add ability to download workspace starting outputs #1756
- [x] Provide more space to the console when workspace is booting #1757
- [x] Display loading steps when booting workspace from the IDE #1758
- [x] Remove current workspace runtime loader #1759
- [x] Improve loader when snapshotting #1760
- [x] Improve wizard to restart workspace #1761 
- [x] Soften lines for dark them #2142 
- [x] Gray out menu items while the workspace is starting or stopped #2286
