### ISSUE TITLE
Eradicate problematic language

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#17454]
### Is your task related to a problem? Please describe.
Get rid of any problematic language in Eclipse Che and its components

it might include name like Workspace Master, master maven artifacts and master branch in github repositories.

Idea is to remove all problematic language but to not break everything, probably we'll need to do it in several steps, from most visible items to less visible items.

It should include
- [x] : Define the list of terms to avoid
  - [ ] : pick up new name for wsmaster](https://github.com/eclipse/che/issues/17602)

- [ ] : PR check to enforce we are not adding terms again
- [ ] : Fix documentation
- [ ] : Fix issue / area labels
- [ ] : Fix branch names
- [ ] : Fix maven artifacts
- [ ] : Fix CI jobs
- [ ] : Fix codebase

external reference: https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

**Comment by nickboldt** [comment]
I think there are 4 main changes to do:

** master branch -> main branch, trunk, primary branch, prime branch, active branch, etc.
** master/slave -> parent/child, primary/secondary, server/worker, principal/copy, etc. (eg., wsmaster -> wsserver?)
** blacklist/whitelist -> denylist/allowlist
** he/she -> they (avoid using male pronouns only in docs)

More external references for terms to replace and with what to replace them (apologies, some internal to RH):

* https://tools.ietf.org/id/draft-knodel-terminology-00.html#rfc.section.1.3
* https://developers.google.com/style/inclusive-documentation
* https://docs.google.com/document/d/1kXlUhEC8DZQLbH_1xjKohU6j_vqUaIjzX9jv3iT-Cls/edit#
* https://mojo.redhat.com/docs/DOC-1225118

**Comment by themr0c** [comment]
For the docs part see:  https://issues.redhat.com/browse/RHDEVDOCS-2273

**Comment by themr0c** [comment]
In the documentation:

```for word in blacklist master slave whitelist ; do echo -n "$word: " ; grep -ire "$word" modules/ | wc -l ; done```

- blacklist: 0
- master: 80
- slave: 0
- whitelist: 0

occurrences breakdown:
- master branch in git repositories (most occurrences)
- wsmaster, CHE_INFRA_KUBERNETES_MASTER__URL
- kubernetes master node: (in context: kubespray, ec3 openshift 3)
- CA File Master Plus plug-in for Zowe CLI

**Comment by nickboldt** [comment]
I believe all Che repos have moved to a main branch. Closing this but if anyone finds more examples to fix, please reopen and link them here.
