### ISSUE TITLE
Che Deploy Sprint #188

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17520]
### Timeframe

|  August 5    |  August 25    |
| ------------- | ------------- | 

### Team
| Name  |  
| ------------- | 
| Anatolii   |  
| Mykola   |   
| Aleksandr  |  
| Flavius  |  

### CRW issues 

- [ ] Workspace startup fails when OCP 4 cluster-proxy has Institutional CA https://issues.redhat.com/browse/CRW-1054
  - [x] Provision custom CA certificates into every container of the workspace pod https://github.com/eclipse/che/issues/17407
  - [x] https://github.com/eclipse/che/pull/17630
  - [x] Plugin broker should respect cluster CA certificates https://github.com/eclipse/che/issues/17552
  - [x] https://github.com/eclipse/che-plugin-broker/pull/109
  - [x] https://github.com/eclipse/che-operator/pull/409/
  - [x] https://github.com/eclipse/che-operator/pull/415
  - [ ] Workspace components have to use provided custom certificates https://github.com/eclipse/che/issues/17440 
- [x] .Possibility to customize cheHost https://issues.redhat.com/browse/CRW-1022 https://github.com/eclipse/che/issues/16670
  - [x] https://github.com/eclipse/che-docs/pull/1442
  - [x] https://github.com/eclipse/che-operator/pull/380
  - [x] https://github.com/eclipse/che-docs/pull/1449
  - [x] https://github.com/che-incubator/chectl/pull/811
- [x] .Operator needs to be arch-aware and be able to deploy jdk or j9 images as required https://issues.redhat.com/browse/CRW-1131
  - [x] https://github.com/eclipse/che-operator/pull/398
- [ ] Airgap installation not working - built catalog doesn't appear in OperatorHub https://issues.redhat.com/browse/CRW-1013
- [ ] [OCP 3.11] Unable to install CRW 2.2 in disconnected environment https://issues.redhat.com/browse/CRW-1071
- [ ] Possibility to define label(s) for route to work with router sharding https://issues.redhat.com/browse/CRW-1034

---
### Eclipse Che issues 
- [ ] Do not allow users to change username when logging for the first time https://github.com/eclipse/che/issues/17265
- [ ] chectl "next" channel with OLM installer should install nightly Che https://github.com/eclipse/che/issues/17183
- [x] .When deploying on OpenShift we should setup OpenShift OAuth by default https://github.com/eclipse/che/issues/17488
  - [x] https://github.com/eclipse/che-operator/pull/391
  - [x] https://github.com/che-incubator/chectl/pull/809
- [x] [WON'T FIX] Use OpenShift service serving certificates instead of tls-secret-creator https://github.com/eclipse/che/issues/17174
- [x] chectl must make sure that objects(like che-operator clusterrole) are up-to-date https://github.com/eclipse/che/issues/14419
  - [x] https://github.com/che-incubator/chectl/pull/815
- [x] .Improve che operator CI jobs https://github.com/eclipse/che/issues/17514
  - [x] https://github.com/eclipse/che-operator/pull/382
  - [x] https://github.com/eclipse/che-operator/pull/381
  - [x] https://github.com/openshift/release/pull/10664
- [ ] Namespace stuck in the 'Terminating' state forever when Eclipse Che is uninstalled on OSD v4 and there is no way to fully remove it https://github.com/eclipse/che/issues/17132
---
### Unplanned
- [x] .[operator] Automatic updates are broken since 7.15.1  https://github.com/eclipse/che/issues/17556
  - [x] https://github.com/eclipse/che-operator/pull/383
  - [x] https://github.com/eclipse/che-operator/pull/385
- [x] .Add quay.io/eclipse/che-sidecar-workspace-data-sync:latest to digestExcludeList https://github.com/eclipse/che-operator/pull/387
- [x] .Add quay.io/eclipse/che-machine-exec:nightly to digestExcludeList https://github.com/eclipse/che-operator/pull/393 
- [x] .Che operator olm files are mangled since 7.16.0 https://github.com/eclipse/che/issues/17480
  - [x] https://github.com/eclipse/che-operator/pull/390
- [x] .Fix testing changes using olm on minikube https://github.com/eclipse/che-operator/pull/400
---
### Help provided
- [x] .Che 7.17.0 - empty theia with TLS enable and proxy set https://github.com/eclipse/che/issues/17600
- [x] .Che server pod fails to connect to keycloak with self-signed TLS cert https://github.com/eclipse/che/issues/17597
- [x] .pod has unbound immediate PersistentVolumeClaims https://github.com/eclipse/che/issues/17625

 [Previous Sprint](https://github.com/eclipse/che/issues/17379)
