### ISSUE TITLE
Plugins Sprint 188

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#17532]
## Sprint goals
1. Bugs (upstream and CRW)
2. Maintenance / Automation / Technical Debt

### CRW
Any critical/urgent CRW issues as they arise.

### Bugs
* [x] Openshift Connector plugin tries to authenticate via oAuth when it is not enabled. #17633 @ericwill / @vinokurig 
* [ ] in Java, the code snippets `try_catch`, `main` and maybe more are not working #16502 @tsmaeder 
* [ ] Installing Java Test Runner Support for Java #14871 @tsmaeder 
* [x] Code formatting is not working with quarkus-java11 plugin #17560 @vitaliy-guliy 
    * [ ] [preferences] Add ability to set default formatter eclipse-theia/theia#8354
* [ ] PHP autocomplete doesn't work with latest Intelephense #17493 @ericwill 
* [x] Dev image quay.io/eclipse/che-java11-maven:7.16.0 does not contain any terminal editors #17518 @ericwill 
* [x] Project tree become unavailable after deleting an OpenshiftConnector component #16360 @vinokurig 
* [ ] Cannot start any workspaces after creating an ssh key pair with a colon in the name #15665 @vitaliy-guliy 
* [ ] Getting Started NodeJS+Yarn fails to run #17453 @svor 
    * [ ] Explore idea of having disk space usage plugin
    * [ ] Workspace Resource Monitor Plugin #17205
* [ ] Che offline using an untrusted TLS cert doesn't load zip samples from internal devfile registry #16473 @vitaliy-guliy 

### Open PRs From Last Sprint
* [x] [Plugin Registry] [airgap] Each plugin should display proper icon #14510

#### Theia API
* [ ] Implement Timeline API eclipse-theia/theia#7577 @vinokurig 
* [ ] [Plugin-Api] Apply authentication API eclipse-theia/theia#7661 @vinokurig 
* [x] [Plugin API] Apply workspace.registerResourceLabelFormatter function eclipse-theia/theia#7946 @vinokurig 
#### Automation / Tests
* [x] Che Plugin Registry VSX Daily Check #17014 @ericwill 
    * [x] Add support for checking sidecar image versions and preventing mismatches
* [ ] Set up PR Check for Java Che 7 plugins #15797 @svor 
    * [ ] Simple LSP test suite for Java #14409
#### Maintenance
* [x] Change layout of che-dockerfiles repositories #15949 @ericwill 
    * [x] che-sidecar-node
    * [x] che-sidecar-dotnet
    * [x] che-sidecar-java
    * [x] che-sidecar-python
    * [x] che-sidecar-scala
    * [x] che-sidecar-dependency-analytics
* [x] Kubernetes plugin wants `minikube` to be installed in the container #17501 @ericwill 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 13  | 8 |
| @ericwill | 14 | 8 |
| @tsmaeder | 14 | 8 |
| @svor | 13 | 8 |

**Comment by ericwill** [comment]
Superseded by #17678
