### ISSUE TITLE
Editors Sprint 188

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17573]
Aug 5 - Aug 25

## Goals
1. CodeReady Workspaces bugs
2. Jupyter Notebooks support (FS API)
3. Workspace related commands consistent with Che
4. Finalize Monaco upgrade
5. Theia upstream focus

#### CodeReady Workspaces bugs
- [ ] Workspace components have to use provided custom certificates https://github.com/eclipse/che/issues/17440
  - needed for "Workspace startup fails when OCP 4 cluster-proxy has Institutional CA" [CRW#1054]
  - WIP PRs: https://github.com/eclipse/che-workspace-client/pull/34, https://github.com/eclipse/che-theia/pull/824(https://issues.redhat.com/browse/CRW-1054)
- [ ] CRW 2.1 in FIPS enabled cluster [CRW#1018](https://issues.redhat.com/browse/CRW-1018)
- [ ] Files in .Trash-xxxxx conflict with debugger breakpoint display [CRW#1129](https://issues.redhat.com/browse/CRW-1129)

#### Jupyter Notebooks support https://github.com/eclipse/che/issues/16818
- [ ] Adapt Che Theia to the new Theia FS API https://github.com/eclipse/che/issues/17357 (WIP PR https://github.com/eclipse/che-theia/pull/798)
  - [ ] check that it also fixes "Adapt Che Theia to upstream changes" https://github.com/eclipse/che/issues/17550

#### Workspace related commands consistent with Che https://github.com/eclipse/che/issues/17106
- [x] Export Che Workspace definition to Devfile from Che Theia https://github.com/eclipse/che/issues/17239

#### Finalize Monaco upgrade
- [x] Upgrade embedded editor to Monaco 0.20.0 https://github.com/eclipse-theia/theia/issues/7697 (address the review comments on the PR https://github.com/eclipse-theia/theia/pull/8010)
- [ ] merge "Sort for quick open entries respecting highlight information" https://github.com/eclipse-theia/theia/pull/8185
  - [ ] waiting for approving CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22443

#### Collaboration in upstream Theia
[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-08-05..2020-08-25+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-08-05..2020-08-25+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-08-05..2020-08-25+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-08-05..2020-08-25)

### Unplanned/Blockers
- [x] Missing version pins in package.json / yarn.lock for che-theia builds https://github.com/eclipse/che/issues/17612
- [x] Che Theia npmjs dependencies shouldn't be upgraded when doing z-stream releases other than x.y.0 https://github.com/eclipse/che/issues/17635

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 12  | 7
| Roman   | 6  | 4
| Artem | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/17383)
