### ISSUE TITLE
When Che 7.y.0 releases are done, send reminder to TLs to clean milestones of any outstanding unresolved issues

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17579]
We need some GH automation to ping TLs via mattermost that will tell them:

* link to current milestone, eg., https://github.com/eclipse/che/milestone/121 (4 unresolved issues) or https://github.com/eclipse/che/milestone/122 (10 unresolved issues)
* instructions re: their options:
- [ ] resolve issue, or
- [ ] move to backlog for no longer scheduled work, or 
- [ ] move to next milestone for WIP

Once that's in place, we could also enable GH automation to automatically close milestones when they are devoid of unresolved issues.

**Comment by nickboldt** [comment]
Related to this topic, it seems that the 7.19 and 7.20 milestones still have unresolved issues in them, so we could also send nag-reminders at weekly intervals until the milestones are properly cleaned up. 

Best case: sending mail to individuals, so they know it's an action for them directly
Worst case: sending mail to che-dev list, shaming people into proper behaviour

**Comment by nickboldt** [comment]
WIP PR for this https://github.com/eclipse/che-release/pull/16

**Comment by nickboldt** [comment]
to send MM notifications, see https://github.com/eclipse/che-release/actions/workflows/release-send-mattermost-announcement.yml or https://github.com/eclipse/che/issues/18906
