### ISSUE TITLE
Rework the grids and lists views in the user dashboard

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1762]
This epic will handle all the changes needed for redesigning grids in dashboard, reviewing related actions to have one consistent behavior.
- [x] Create grids component #1763 
- [x] Add actions for workspace item in workspace list #1764
- [x] Proper handling of workspace list hover and click states #1765
- [x] Apply the new component to users list and workspace members list #1779
- [x] Apply the new component to workspace's projects list #1780
- [x] Apply the new component to factories list https://github.com/codenvy/codenvy/issues/494
- [x] Apply the new component to docker registries list #2010
- [x] Simplify boxes design on Dashboard page #2158 
- [x] Revamps list's header #2179

**Comment by TylerJewell** [comment]
PR for tracking: #1680

**Comment by slemeur** [comment]
Adding reference to #2179

**Comment by ashumilova** [comment]
Resolved
