### ISSUE TITLE
Che Deploy Sprint #189

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17661]
### Timeframe

|  August 26    |  September 15    |
| ------------- | ------------- | 

### Team
| Name  |  
| ------------- | 
| Anatolii   |  
| Mykola   |   
| Aleksandr  |  
| Flavius  |  

### CRW issues 
- [x] .Workspace startup fails when OCP 4 cluster-proxy has Institutional CA https://issues.redhat.com/browse/CRW-1054
  - [x] https://github.com/eclipse/che-theia/pull/824
  - [x] https://github.com/eclipse/che-operator/pull/424
  - [x] https://github.com/eclipse/che-theia/pull/844
  - [x] https://github.com/eclipse/che-operator/pull/426
  - [x] Tests Eclipse Che 7.18.1 changes
- [ ] Upgrade from 2.2 to 2.3 breaks CRW https://issues.redhat.com/browse/CRW-1181
- [x] .CRW 2.2 can not be deployed on Openshift 3.11 on quicklab https://issues.redhat.com/browse/CRW-1148 
- [x] .Unable to upgrade CRW 2.2 to version 2.3 in OCP 3.11 disconnected environment https://issues.redhat.com/browse/CRW-1175
  - [x] https://github.com/che-incubator/chectl/pull/827
  - [x] https://github.com/eclipse/che-docs/pull/1494
- [ ] [OCP 3.11] Unable to install CRW 2.2 in disconnected environment https://issues.redhat.com/browse/CRW-1071
- [x] .Airgap installation not working - built catalog doesn't appear in OperatorHub https://issues.redhat.com/browse/CRW-1013
- [ ] "crwctl workspace:inject" doesn't support workspace of CRW with OS OAuth support 
https://issues.redhat.com/browse/CRW-803 
  - [ ] https://github.com/che-incubator/chectl/pull/849
  - [x] https://github.com/eclipse/che-docs/pull/1498
  - [x] https://github.com/che-incubator/chectl/pull/832
- [x] .Failed to shutdown CodeReady Workspaces server by command "crwctl server:stop" https://issues.redhat.com/browse/CRW-519  https://github.com/eclipse/che/issues/17534
  - [x] https://github.com/che-incubator/chectl/pull/822
- [x] .rework crwctl server:delete command to fix: 
  - [x] https://issues.redhat.com/browse/CRW-714
  - [x] https://github.com/eclipse/che/issues/17784  
    - [x] https://github.com/che-incubator/chectl/pull/842
    - [x] https://github.com/che-incubator/chectl/pull/846
  - [x] .https://issues.redhat.com/browse/CRW-1039  https://issues.redhat.com/browse/CRW-467   https://github.com/eclipse/che/issues/16000
    - [x] https://github.com/che-incubator/chectl/pull/828 
- [x] .Warning about nonexistent identity providers in operator container points to old documentation https://issues.redhat.com/browse/CRW-1015 
  - [x] https://github.com/eclipse/che-operator/pull/416
  - [x] https://github.com/che-incubator/chectl/pull/821
- [x] .crwctl logs cannot be found after error https://issues.redhat.com/browse/CRW-859
  - [x] https://github.com/che-incubator/chectl/pull/836
- [x] .Improve crwctl downstreamed doc - remove k8s and kube items, clarify multiuser mode, etc. https://issues.redhat.com/browse/CRW-1174
  - [x] https://github.com/redhat-developer/codeready-workspaces-chectl/pull/44
---
### Eclipse Che issues 
- [ ] Cannot login into Che using Openshif OAuth when proxy with authentication is used https://github.com/eclipse/che/issues/17681
- [x] .Option CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: che-ws-<username> does not work properly https://github.com/eclipse/che/issues/17631
  - [x] https://github.com/eclipse/che-operator/pull/421
  - [x] https://github.com/eclipse/che-operator/pull/425
- [ ] We should use services hostname instead of ingresses for inter-components communications https://github.com/eclipse/che/issues/17644 
- [x] .chectl "next" channel with OLM installer should install nightly Che https://github.com/eclipse/che/issues/17183
  - [x] https://github.com/eclipse/che-operator/pull/423
  - [x] https://github.com/che-incubator/chectl/pull/845
  - [x] https://github.com/eclipse/che-operator/pull/435
- [x] .chectl must make sure that objects(like che-operator clusterrole) are up-to-date https://github.com/eclipse/che/issues/14419
  - [x] https://github.com/che-incubator/chectl/pull/815
- [x] .[technical-debt] Refactor operator to pass `deploy.Context` into functions instead of numerous arguments https://github.com/eclipse/che/issues/17589
  - [x] https://github.com/eclipse/che-operator/pull/420

---
### PR to merge
- [x] .https://github.com/che-incubator/chectl/pull/794
- [x] .https://github.com/che-incubator/chectl/pull/807
- [x] .https://github.com/che-incubator/chectl/pull/764
- [x] .https://github.com/eclipse/che-operator/pull/417
- [x] .https://github.com/che-incubator/chectl/pull/837
- [x] .https://github.com/che-incubator/chectl/pull/847
---
### Unplanned
- [x] .Helm installer is broken https://github.com/eclipse/che/issues/17766
  - [x] https://github.com/eclipse/che/pull/17773
  - [x] https://github.com/che-incubator/chectl/pull/839/
- [x] .Do not allow users to change username when logging for the first time https://github.com/eclipse/che/issues/17265
  - [x] https://github.com/eclipse/che/pull/17780/
---
### Help provided
- [x] .Unable to start Che on Microsoft Azure (AKS) - Exception while retrieving OpenId configuration from endpoint https://github.com/eclipse/che/issues/17760

---
 [Previous Sprint](https://github.com/eclipse/che/issues/17520)
