### ISSUE TITLE
Workspace creation/edit view recasting and extending with new item

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#1767]
This epic will improve “workspace edit / creation” view with making them identical and extending with following items: project creation section, managing agents section, managing exposed ports section.
- [x] Add "+" button next to "Recent workspaces" #1768
- [x] Make workspace creation and edit screens identical #1769
- [x] New layout for forms in UD #1770
- [x] Add Ports section in the workspace configuration #1771
- [x] Add Environment variables in the workspace configuration #1772
- [x] Add section in workspace to handle the stack  improvement #1773
- [x] Add section in workspace to handle the agents #1774 
- [x] Allow changing RAM size after workspace created #1918
- [x] Workspace environment page enhancement https://github.com/eclipse/che/issues/2451
