### ISSUE TITLE
Editors Sprint 189

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17707]
Aug 26 - Sep 15

## Goals
1. Bugfixes
2. CRW in FIPS enabled cluster
3. Jupyter Notebooks support (FS API)
4. Multi-root Workspaces
5. Theia upstream focus

#### CRW in FIPS enabled cluster
- [x] CRW in FIPS enabled cluster [CRW#1018](https://issues.redhat.com/browse/CRW-1018)
  - [x] Theia should work on a FIPS-compliant system https://github.com/eclipse-theia/theia/issues/8378

#### Bugs/enhancements
- [ ] Che is always asking if changes made should be overwritten https://github.com/eclipse/che/issues/16751
  - PR https://github.com/eclipse/che-theia/pull/862
- [ ] Theia terminal must report the error if request to machine-exec fails https://github.com/eclipse/che/issues/17663
- [x] Files in .Trash-xxxxx conflict with debugger breakpoint display [CRW#1129](https://issues.redhat.com/browse/CRW-1129)

#### Jupyter Notebooks support https://github.com/eclipse/che/issues/16818
- [ ] Adapt Che Theia to the new Theia FS API https://github.com/eclipse/che/issues/17357 (WIP PR https://github.com/eclipse/che-theia/pull/823)
  - check that it also fixes "_Adapt Che Theia to upstream changes_" https://github.com/eclipse/che/issues/17550

#### Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212

#### Pending merge PRs
- [ ] Sort for quick open entries respecting highlight information https://github.com/eclipse-theia/theia/pull/8185
  - waiting for the CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22443
- [x] Workspace components have to use provided custom certificates https://github.com/eclipse/che/issues/17440
  - needed for "_Workspace startup fails when OCP 4 cluster-proxy has Institutional CA_" [CRW#1054](https://issues.redhat.com/browse/CRW-1054)
  - [x] https://github.com/eclipse/che-theia/pull/824
  - [x] https://github.com/eclipse/che-workspace-client/pull/36
  - [x] https://github.com/eclipse/che-theia/pull/844

#### Collaboration in upstream Theia
[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-08-26..2020-09-15+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-08-26..2020-09-15+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-08-26..2020-09-15+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-08-26..2020-09-15)

### Unplanned/Blockers
- [x] Investigating _CRW fails to start workspace, "Error: Failed to run the workspace: "Server 'theia' in container 'theia-xyz' not available."_ [CRW#1186](https://issues.redhat.com/browse/CRW-1186)

## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 14  | 8
| Roman   | 11  | 7
| Artem | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/17573)
