### ISSUE TITLE
Improve Che Release Process Part 3

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17748]
Follows up from #17101

Process automation:

- [x]  include che-operator, che-operator PR generation, and chectl in overall release script
- [x] Move Che release workflow from Centos CI #17857 (mostly done, continued in #19007)
- [x] generated PRs for plugin registry should remove all but the latest plugins (instead of including multiple copies of machine-exec and theia) #18596

- [x] generate branches in https://github.com/eclipse/che-jwtproxy #17743
- [x] generate branches in https://github.com/che-incubator/kubernetes-image-puller #17742

-----

Runtime & PR testing:

- [x]  Verify that plugin images referenced in the plugin registry actually exist in Quay #16501

- [x]  stop release if required artifacts are not found (eg., plugin-registry 7.14.2 container not available in quay, so don't start releasing che server)

- [x] fail during release, if snapshot versions found, eg., 
> ```
> $➔ count=$(grep -R "SNAPSHOT" * | grep pom.xml | wc -l); if [[ $count -gt 0 ]]; then echo "[ERROR] Found $count files which use a SNAPSHOT version. Cannot proceed with release."; exit 1; fi
> [ERROR] Found 303 files which use a SNAPSHOT version. Cannot proceed with release.
> ```

- [x]  replace manual testing of deployment on openshift w/ PR validation check that triggers CRW QE Jenkins automated e2e test to deploy on OCP 4.4, 3.11, 4.5, 4.3 #17747

-----

Doc:
- [x]  add more documentation covering functionality of specific usecases (e.g. skipping/rebuilding particular items from release )
--> see items 5-6 on https://github.com/eclipse/che-release/blob/master/README.md#phase-1---automated-build-steps

- [x] Remove VERSION file in che-docs; keep antora-playbook.yml up to date instead #18864

**Comment by nickboldt** [comment]
Slipping this to 7.26 and we'll ACTUALLY complete it this time :D

**Comment by nickboldt** [comment]
Continued in https://github.com/eclipse/che/issues/19007
