### ISSUE TITLE
Basic support IntelliJ IDEA as a Che editor

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17790]
### Is your enhancement related to a problem? Please describe.

Che-theia is the default editor. We support alternative editors such as dirigible, desktop eclipse and code-server. But not IntelliJ.

### Describe the solution you'd like

Add support for IntelliJ as an editor. IntelliJ would run in the browser. IntelliJ community edition should be used. These are the subtasks:

- [x] publish the sidecar image of the intellij community + vnc
- [x] publish a Red Hat based sidecar(fedora) image of the intellij community + vnc
- [x] UBI-based Dockerfile for IntelliJ IDEA Che editor
  - [x] initial investigation https://github.com/eclipse/che/issues/18031
  - [x] CRW-compatible image [CRW#1239](https://issues.redhat.com/browse/CRW-1239)
- [x] add the editor in the plugin registry https://github.com/eclipse/che/issues/17979
- [ ] document how to use it and extend it: [RHDEVDOCS#2161](https://issues.redhat.com/browse/RHDEVDOCS-2161)
    - How to create a workspace that uses intellij as editor
    - How to customize it:
        - Inject a license key
        - Configure a [Floating License Server](https://www.jetbrains.com/license-server/#:~:text=What%20is%20Floating%20License%20Server,hour%20and%20obtain%20license%20information) using `JETBRAINS_LICENSE_SERVER` env variable
        - Use a different version of intelliJ
    - Current limitations
- [x] persistent settings across workspace restart https://github.com/eclipse/che/issues/17968
- [x] idle timeout che/intellij plug-in (to avoid it gets idled, no need to track activity) https://github.com/eclipse/che/issues/17953
- [ ] clone projects on boot https://github.com/eclipse/che/issues/15973
- [x] implement and run an end to end test https://github.com/eclipse/che/issues/18035
- [x] handling `Enter` key in built-in terminal (solution provided in https://github.com/eclipse/che/issues/17790#issuecomment-698854133) or have preliminary preference set up on workspace startup https://github.com/eclipse/che/issues/17986

### What is NOT included in this issue

A fully supported editor should also:
- describe the IDE configuration in a devfile (commands, plugins, runtime services)
- automatically inject users configs in the IDE (such as proxy, git, kubernetes settings)
- airgap support

But these features are not in this issue scope. We will create dedicated issues for that.

### Describe alternatives you've considered

- **[CURRENT CHOICE]** Running a VNC client in the browser (such as [novnc](https://github.com/novnc/noVNC))
- Using https://www.webswing.org/
- Running an X11 client in the browser (such as [xpra-htlm5](https://xpra.org/trac/wiki/Clients/HTML5))

### Additional context

This is a feature provided by [coder enterprise](https://enterprise.coder.com/docs/multi-editor) (this is the [dockerfile](https://github.com/cdr/enterprise-images/blob/master/intellij/Dockerfile.centos)).

@benoitf has provided PoC that uses webswing and that can be tried out with the following [devfile](https://gist.githubusercontent.com/benoitf/3f165378614f9c0d1716747aa52a9626/raw/78fdc768019c8748aa5e5098476533f5e3f6fa68/che-intellij-webswing-devfile.yaml) or using docker locally `docker run --rm -it -p 8080:8080 quay.io/fbenoit/webswing-intellij:20200904`.

![image](https://user-images.githubusercontent.com/606959/92235054-5b81a080-eeb3-11ea-942f-3ab36383e8d8.png)

**Comment by jeffmaury** [comment]
Please note that IntelliJ Community does not require a license

**Comment by jeffmaury** [comment]
Adding GTK broadway as an alternative (this is used by Desktop Eclipse)

**Comment by benoitf** [comment]
@jeffmaury broadway is for GTK/AWT but inteliij is not using AWT/gtk

**Comment by benoitf** [comment]
Here is with novnc:
https://che.openshift.io/f?url=https://gist.githubusercontent.com/benoitf/1b85a426971790687f5b057ff205dbea/raw/c6ea1b2a75c3e3c16ea217eef37965cb68606e47/devfile.yaml

![image](https://user-images.githubusercontent.com/436777/92362796-d257ad00-f0f0-11ea-869d-329f927dc322.png)

**Comment by benoitf** [comment]
xpra: 

http://che.openshift.io/f/?url=https://gist.githubusercontent.com/benoitf/6ccdb0ee11658c5efb794ca1b161bfb0/raw/f8cea506db476614ea9b94b898cac359df926fda/devile-intellj-xpra.yaml

![image](https://user-images.githubusercontent.com/436777/92376257-9f1e1980-f102-11ea-99ab-d879e41d4d93.png)

**Comment by azatsarynnyy** [comment]
latest novnc attempt by Florent http://che.openshift.io/f?url=https://gist.githubusercontent.com/benoitf/3c69b0290e6b6901dd20a505e1024267/raw/7f6523f7ec8a5bcbdbbc82eb4800fe565cb74c9f/gistfile1.txt

**Comment by benoitf** [comment]
source code of POC are there
- https://github.com/benoitf/che-intellij-editor-vnc
- https://github.com/benoitf/che-intellij-editor-xpra
- https://github.com/benoitf/che-intellij-editor-webswing

(with VNC I was able to use browser resizing and maximize widgets using a lightweight wm (here it's fluxbox) where I can hide toolbar/workspaces, etc by default)

**Comment by benoitf** [comment]
I've moved vnc POC to https://github.com/che-incubator/che-editor-intellij-community

**Comment by l0rd** [comment]
I have added a few more requirements in the description:
- It should be possible to minimize the sidebar as it's possible for Theia.
- We should provide documentation about how to use the ultimate edition.
- We should test that it works properly with a [Floating License Server](https://www.jetbrains.com/license-server/#:~:text=What%20is%20Floating%20License%20Server,hour%20and%20obtain%20license%20information.).

**Comment by benoitf** [comment]
I would say order should be
1. publish image of the intellij community + vnc
2. Add plugin in the registry
3. Add devfile using this plug-in
4. a) probably need to have a 'base image' that ppl can extend to their own use
4. b) example of devfile with JETBRAINS_LICENSE_SERVER and ultimate edition
5. persistent settings across workspace restart
6. idle timeout che/intellij plug-in
7. clone projects on boot or do https://github.com/eclipse/che/issues/15973
8. terminal/containers intellij/che plug-in
9. minimize sidebar (workaround if not done is to open the ide in a new full window. I did that there: https://github.com/benoitf/che-intellij-editor-webswing/blob/master/index.html#L25-L30)
10. execute devfile tasks

**Comment by nickboldt** [comment]
What are the deliverables here? new container image(s)? new plugin(s)? new devfile(s)?

If any of the above, what are the dependencies, and how are they built? What licenses apply re: redistribution, attribution, etc.? is crypto involved? Are there any security concerns?

This smells like an Epic, which would need some subtasks under it re: the above items.

**Comment by vzhukovskii** [comment]
Intellij Idea's configuration directory is described in the following doc: https://www.jetbrains.com/help/idea/tuning-the-ide.html?_ga=2.152130681.1731799723.1600938923-801667806.1600783588#config-directory

**Comment by benoitf** [comment]
@vzhukovskii note that `$HOME/.local` and `$HOME/.java` are used as well but not documented !

**Comment by vzhukovskii** [comment]
@benoitf thanks for the pointing! Will take a note about these directories.

**Comment by l0rd** [comment]
@benoitf @vzhukovskii I have updated the description with the ordered list provided by @benoitf above with a few changes:
- added ubi based image (to make productization easier)
- added end to end test
- removed 9, 10 and 11 that IMO are nice to have

**Comment by vzhukovskii** [comment]
@l0rd thanks! At this moment there is a work on implementing simple activity tracker, because this is a kinda blocker for user experience. Issue for that will post in this comment soon.

To make the work coherent, I'll create a dedicate issues for each subtask, because this looks like an epic.

**Comment by vzhukovskii** [comment]
Another thing, that needs to be resolved is handling `Enter` key in the built-in terminal. At this moment it's also kinda blocker. There's a workaround to copy `\n` from the editor and paste to the terminal, but it's really slows down the any interaction with the terminal.

**Comment by benoitf** [comment]
Disabling 
![image](https://user-images.githubusercontent.com/436777/94256827-a7f85300-ff2a-11ea-91a7-1793a46ef539.png)

in settings make it work
![terminal-intellij](https://user-images.githubusercontent.com/436777/94256865-b5154200-ff2a-11ea-9ce4-1036655c1d65.gif)

**Comment by vzhukovskii** [comment]
Then this option needs to be disabled by default in settings all the time

**Comment by vzhukovskii** [comment]
I think, we can add additional item into description, to have a preliminary IDE configuration and set up specific options like https://github.com/eclipse/che/issues/17790#issuecomment-698854133. Because when workspace opens at first time, user has to configure this option to operate with terminal.

**Comment by azatsarynnyy** [comment]
I've added the issue for a UBI-based Dockerfile as it's a requirement for including it to CRW.
https://github.com/eclipse/che/issues/18031

**Comment by nickboldt** [comment]
Two subtasks not yet complete, so move to 7.22 milestone:

- [ ] document how to use it and extend it: [RHDEVDOCS#2161](https://issues.redhat.com/browse/RHDEVDOCS-2161)
    - How to create a workspace that uses intellij as editor
    - How to customize it:
        - Inject a license key
        - Configure a [Floating License Server](https://www.jetbrains.com/license-server/#:~:text=What%20is%20Floating%20License%20Server,hour%20and%20obtain%20license%20information) using `JETBRAINS_LICENSE_SERVER` env variable
        - Use a different version of intelliJ
    - Current limitations

- [ ] clone projects on boot https://github.com/eclipse/che/issues/15973

**Comment by azatsarynnyy** [comment]
The basic support is done :tada:
If this will be our priority in the future, then all further enhancements will be tracked with separate issues.

**Comment by maxandersen** [comment]
how does one try out this feature ?

**Comment by benoitf** [comment]
you may find additional information there https://github.com/che-incubator/jetbrains-editor-images#run-jetbrains-ide-in-eclipse-che

short link to try on Hosted Che by Red Hat: https://workspaces.openshift.com#https://github.com/che-incubator/jetbrains-editor-images/raw/main/devfiles/latest/che-idea/latest.yaml
