### ISSUE TITLE
Che Deploy Sprint #190

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#17800]
### Timeframe

|  September 16    |  October 6    |
| ------------- | ------------- | 

### Team
| Name  |  
| ------------- | 
| Anatolii   |  
| Mykola   |   
| Aleksandr  |  
| Flavius  |  

### CRW issues 
- [x] Possibility to define label(s) for route to work with router sharding https://issues.redhat.com/browse/CRW-1034
  - [x] https://github.com/eclipse/che-operator/pull/449
  - [x] https://github.com/eclipse/che-docs/pull/1610
  - [x] https://github.com/eclipse/che-operator/pull/477
- [x] "crwctl workspace:inject" doesn't support workspace of CRW with OS OAuth support 
https://issues.redhat.com/browse/CRW-803 
    - [x] https://github.com/che-incubator/chectl/pull/849
---
### Eclipse Che issues 
- [ ] We should use services hostname instead of ingresses for inter-components communications https://github.com/eclipse/che/issues/17644 
  - [ ] https://github.com/eclipse/che-operator/pull/468
  - [ ] https://github.com/eclipse/che-theia/pull/865
  - [ ] https://github.com/eclipse/che/pull/17945
- [x] Java `http.nonProxyHosts` system variable contains incorrect wildcard domains https://github.com/eclipse/che/issues/17831
    - [x] https://github.com/eclipse/che-operator/pull/440
    - [x] https://github.com/eclipse/che-operator/pull/476
- [x] Ensure identity provider for downstream CRW projects should contain theme with username validation https://github.com/eclipse/che/issues/17827
  - [x] https://github.com/eclipse/che-operator/pull/444
- [x] 'Plugins' list is absent in IDE in CHE 'single-host' on k8s https://github.com/eclipse/che/issues/17749 
  - [x] https://github.com/eclipse/che-theia/pull/869
- [ ] [chectl] Add `server:login` command https://github.com/eclipse/che/issues/16415
- [x] [chectl] Add new `server:status` command https://github.com/eclipse/che/issues/14476
  - [x] https://github.com/che-incubator/chectl/pull/870
- [x] Che self-signed certificate secret created by Che operator contains more than one key on Openshift infrastructure https://github.com/eclipse/che/issues/16773
  - [x] https://github.com/che-incubator/chectl/pull/859
- [x] Disable self registration of users by default https://github.com/eclipse/che/issues/14083
  - [x] https://github.com/eclipse/che/pull/17893
  - [x] https://github.com/eclipse/che-operator/pull/448
- [x] Migrate che-operator minikube and minishift tests from ci.centos.org to github actions https://github.com/eclipse/che/issues/17803 
  - [x] https://github.com/eclipse/che-operator/pull/451
- [x] Migrate chectl e2e tests from ci.centos.org to github actions https://github.com/eclipse/che/issues/17801
  - [x] https://github.com/che-incubator/chectl/pull/851
- [ ] Ensure we don't miss certificate chain of trust even if `self-signed-certificate` secret isn't created  https://github.com/eclipse/che/issues/17826
---
### PR to merge
 - [x] https://github.com/che-incubator/chectl/pull/848
 - [x] https://github.com/eclipse/che-operator/pull/474
---
### Unplanned
- [x] chectl throwing error on deploying Eclipse Che https://github.com/eclipse/che/issues/17919
  - [x] https://github.com/che-incubator/chectl/pull/879
- [x] Build a catalog source image only if there is a new nightly bundle image https://github.com/eclipse/che/issues/17907
  - [x] https://github.com/eclipse/che-operator/pull/478
- [x] Che operator release generates wrong version in CSV https://github.com/eclipse/che/issues/17922
  - [x] https://github.com/eclipse/che-operator/pull/455
- [x] 'CheCluster.org.eclipse.che "eclipse-che" is invalid: []: Invalid value" deployment error https://github.com/eclipse/che/issues/17888 
  - [x] https://github.com/eclipse/che-operator/pull/447
  - [x] https://github.com/che-incubator/chectl/pull/857
- [x] Che installation fails on Minikube 1.13.1 https://github.com/eclipse/che/issues/17952
  - [x] https://github.com/eclipse/che-docs/pull/1613
  - [x] https://github.com/che-incubator/chectl/pull/881
- [x] Migrate che-machine-exec tasks to the github actions  https://github.com/eclipse/che/issues/17875
  - [x] https://github.com/eclipse/che-machine-exec/pull/116
- [x] Implement tests for single host in Openshift CI https://github.com/eclipse/che/issues/17944
  - [x] https://github.com/eclipse/che-operator/pull/481
---
### Help provided

---
 [Previous Sprint](https://github.com/eclipse/che/issues/17661)
