### ISSUE TITLE
Editors Sprint 190

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#17897]
Sep 16 - Oct 6

## Goals
1. IntelliJ IDEA as a Che editor
2. Bugfixes
3. Jupyter Notebooks support
4. Multi-root Workspaces
5. Theia upstream focus
---
#### IntelliJ IDEA as a Che editor https://github.com/eclipse/che/issues/17790
  - [x] Create an activity tracker for the Intellij Idea https://github.com/eclipse/che/issues/17953
  - [x] Storing Intellij Idea preferences between workspace restart https://github.com/eclipse/che/issues/17968
  - [x] Preliminary preferences for Intellij Idea https://github.com/eclipse/che/issues/17986
  - [ ] UBI-based Dockerfile for IntelliJ IDEA Che editor https://github.com/eclipse/che/issues/18031
---
#### Bugs/enhancements
- [x] Che is always asking if changes made should be overwritten https://github.com/eclipse/che/issues/16751
- [ ] Theia terminal must report the error if request to machine-exec fails https://github.com/eclipse/che/issues/17663
---
#### Jupyter Notebooks support https://github.com/eclipse/che/issues/16818
- [x] Adapt Che Theia to the new Theia FS API https://github.com/eclipse/che/issues/17357 (PR https://github.com/eclipse/che-theia/pull/823)
  - [x] Adapt Che Theia to upstream changes https://github.com/eclipse/che/issues/17550
  - [x] Stabilize some happy path tests at update to the latest Theia https://github.com/eclipse/che/pull/17933
- [ ] Theia Web View for remote plugins https://github.com/eclipse/che/issues/16870
##### Theia Plugin APIs
- [ ] CustomEditor API https://github.com/eclipse-theia/theia/issues/6636
---
#### Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212
---
#### Help provided to other teams
- [x] CRW 2.4 Docs review https://github.com/eclipse/che/issues/17896
- [ ] workspace welcome page fails to load in single-host https://github.com/eclipse/che/issues/17694
---
#### Pending merge PRs
- [ ] Sort for quick open entries respecting highlight information https://github.com/eclipse-theia/theia/pull/8185
  - [ ] waiting for the CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22443
---
#### Collaboration in upstream Theia
- [ ] Automated GitHub Milestones for Pull Requests https://github.com/eclipse-theia/theia/issues/8453

[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-09-16..2020-10-06+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-09-16..2020-10-06+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-09-16..2020-10-06+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-09-16..2020-10-06)

---
### Unplanned/Blockers
- [x] Icons for tabs are not displayed https://github.com/eclipse/che/issues/17978
---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 15  | 9
| Roman   | 15  | 9
| Artem | 15  | 9

---
[Previous Sprint](https://github.com/eclipse/che/issues/17707)
