### ISSUE TITLE
JPA Dao implementation

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#1790]
Today to store information we using in memory storages which is backed as json files
during application suspend-startup. This approach is not scalable enough. To make
it more scalable, fault tolerant and  concurrent  we decided to move all our persistent storages to JPA based implementation. Potentially  we will replace our in-memory implementation with JPA based. As JPA implementation we will take EclipseLink and h2 database.

See more 
https://www.eclipse.org/eclipselink/
http://www.h2database.com/html/main.html
- [x] UserService structural refactoring #1846 
- [x] Create/Use TCK for UserDao #1847 
- [x] Implement UserDao based on JPA #1811
- [x] FactoryService structural refactoring #1812
- [x] Implementation of workspace service storage on JPA #1813
- [x] RecipeDao implementation on JPA #1815
- [x] StackDao  implementation on JPA #1795  
- [x] SnapshotDao implementation on JPA #1797
- [x] Investigate strategies for cascade entities removing  #1803 
- [x] Create JPA based SshDao implementation  #1810
- [x] Integrate JPA components/tools with Che Infrastructure #1807
- [x] Don't store username as Workspace#namespace #1950 
- [x] Migrate local json-based storage to jpa #2016 
- [x] User password stores/updates without encoding  https://github.com/eclipse/che/issues/2136
- [x] Merge model changes to JPA branch https://github.com/eclipse/che/issues/2280

**Comment by bmicklea** [comment]
Added 5.0.0-M2 milestone to all issues completed at this stage.

**Comment by skabashnyuk** [comment]
Study how to make changes in model after migration to single database #2110
moved out of scope of this issue
