### ISSUE TITLE
Improving new user flow (with a focus on Quarkus)

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17985]
### Is your enhancement related to a problem? Please describe.

If someone looks for Che on Google these are some of the UX problems that will be found:

che.eclipse.org issues:
- [ ] "Start working with Che" section in the website is not clear [#17964](https://github.com/eclipse/che/issues/17964)
- [x] Replace Thorntail stack with Quarkus on Eclipse Che website [#17961](https://github.com/eclipse/che/issues/17961)

Hosted Che issues:
- [x] Hosted Che sso redirect page has a bad CSS [#17965](https://github.com/eclipse/che/issues/17965)
- [ ] Switching to persistent storage on che.osio we should warn about the filesystem issues #17990
- [ ] When switching from ephemeral to persistent storage I am not expecting to lose my files #17991

Devfile Registry issues:
- [x] What's "Quarkus command mode" stack? [#17966](https://github.com/eclipse/che/issues/17966)

Quarkus Plugin issues:
- [x] Extension welcome page gets shown again and again #17994
- [ ] Quarkus getting started page is not written for Che #18005

Che Theia issues:
- [x] File Explorer should be opened at workspace startup [#17969](https://github.com/eclipse/che/issues/17969)
- [x] Theia "Debug" menu item should be "Run" menu item [#17967](https://github.com/eclipse/che/issues/17967)
- [x] Disable tasks output scanning message [#17970](https://github.com/eclipse/che/issues/17970)
- [x] Port redirect option "No" is missing [#17972](https://github.com/eclipse/che/issues/17972)
- [x] Hide port redirect message for non public endpoints #17993
- [ ] When clicking on Run nothing happens #18004 
- [ ] Default path is / and not /projects/ #18006
- [ ] My workspace view should be opened at workspace startup

**Comment by tsmaeder** [comment]
@l0rd the link behind "When clicking on Run nothing happens" points to this issue, not the correct one.

**Comment by tsmaeder** [comment]
Same for "Extension welcome page gets shown again and again"

**Comment by benoitf** [comment]
issues are being created

**Comment by sleshchenko** [comment]
updated the description to make it clear where is a real link and where is stub to avoid confusion

**Comment by sunix** [comment]
I added `My workspace view should be opened at workspace startup` WDYT ? @l0rd

**Comment by l0rd** [comment]
> I added `My workspace view should be opened at workspace startup` WDYT ? @l0rd
> Most of the new users are quite lost in a Che workspace. It is important that these users visually see the containers and the ability to open a terminal or run a task visually at start up. So it is straight forward to start a build, or run the app, etc ...

No I don't think that My workspace view is something that makes things clearer for a new user. 

I understand that for those that are not used to VS Code and the command palette it may be hard to find the list of tasks. But we should spend our energies to help users getting into the command palette instead of implementing an "old style" alternative to it.

The same applies to the terminal: when a user starts a quarkus stack he will expect that running maven is as simple as selecting an existing task or opening a terminal and type `mvn`. If we give the user the choice of choosing a container where commands will be executed we will lose him.

I am also against providing the details of the IDE services (plugins). Except for advanced users, accessing directly those containers is source of confusions and should be avoided.

The endpoints links are the only thing that I would keep. But current UX should be reviewed: the endpoints status is not shown and, if the application isn't running (at workspace startup for example), clicking on an endpoint shows some error pages.

**Comment by tsmaeder** [comment]
> The same applies to the terminal: when a user starts a quarkus stack he will expect that running maven is as simple as selecting an existing task or opening a terminal and type mvn. If we give the user the choice of multiple containers we will lose him.

I disagree here: we can try and make the different containers disappear in the UI, but this will be a leaky abstraction: eventually, the user _will_ have to deal with the fact that the workspace consists of multiple different containers and will be even more confused. It's better to be explicit with non-reducible complexity.

**Comment by l0rd** [comment]
> the user will have to deal with the fact that the workspace consists of multiple different containers

Maybe. I am probably missing some advanced use case. But the new user that opens a Che workspace for the first time, selecting one of our getting started, should NOT deal with the fact that the workspace consists of multiple different containers.

**Comment by tsmaeder** [comment]
@l0rd this "remote commands" and "hide the containers" effort seems to be part of a bigger effort: is there an Epic (or could you open one) so that we know what's coming down the line and can discuss it?

**Comment by l0rd** [comment]
@tsmaeder I agree. We currently have https://github.com/eclipse/che/issues/17209

**Comment by sunix** [comment]
Discovering Che, new users have to see the difference from a traditional IDE.
There is one thing that user may use the command palette and not the `my workspace` view. This is the choice of the developer. My workspace view has the advantage that it is visually accessible. Knowing that you have available predefined tasks to run a build not something that you can guess right away.
My point is that knowing that you have predefined Che task that you can run from the command palette is an advanced usage. We have to show the users that these tasks exist at the very beginning. New user will finally open a terminal (and choose the container?) and try to type his the commands ...
