### ISSUE TITLE
Default path is / and not /projects/ in "Create Quarkus project" wizard

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18006]
### Describe the bug

Quarkus plugin welcome page has "Create Quarkus project" button. 

![image](https://user-images.githubusercontent.com/606959/94751336-9549a800-0388-11eb-812c-bffaf100965f.png)

When clicked, the user has to provide some project details. The last question is about the target folder

![image](https://user-images.githubusercontent.com/606959/94751245-5287d000-0388-11eb-840b-13f7c6e04b53.png)

The problem is that the default target folder is the root folder (`/`) that is not visible from the IDE. 

### Che version

che.osio

### Steps to reproduce

1. Open che.openshift.io
2. Select "Quarkus Tools" among the Getting started samples
3. Wait for the workspace to start
4. Open a java file and wait for the "Quarkus Tools for Eclipse Che" welcome page to show up
5. Click on the "Create Quarkus project" button

### Expected behavior

The default target of the Quarkus sample project should be folder '/projects/'. 

### Sub-tasks
- [x] Better UX when generating a Quarkus project https://github.com/redhat-developer/vscode-quarkus/issues/309
- [x] `workspace.workspaceFolders` API should return undefined when no folder is open https://github.com/eclipse-theia/theia/issues/8640
- [ ] Upgrade Che Quarkus Plugin to Quarkus VS Code extension 1.8.0 once it's released

**Comment by nickboldt** [comment]
Presumably the devfile in question is https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml

**Comment by azatsarynnyy** [comment]
It has to be fixed upstream, in `vscode-quarkus`.
Currently, it [opens the dialog](https://github.com/redhat-developer/vscode-quarkus/blob/4c4f56ff55b5912e5f77ee6a861e0683eab24731/src/wizards/generateProject/generationWizard.ts#L198) without providing an [initial directory](https://github.com/eclipse-theia/theia/blob/eb1136b1180e63312b01636f5ff65dce24245441/packages/plugin/src/theia.d.ts#L2648-L2651).

The proposed solution should suit both environments: VS Code and Che.
The first thing we should try is [`workspace.workspaceFolders` API](https://github.com/eclipse-theia/theia/blob/eb1136b1180e63312b01636f5ff65dce24245441/packages/plugin/src/theia.d.ts#L4928-L4934).

**Comment by azatsarynnyy** [comment]
upstream issue https://github.com/redhat-developer/vscode-quarkus/issues/309 and related PR https://github.com/redhat-developer/vscode-quarkus/pull/310

**Comment by azatsarynnyy** [comment]
Theia upstream issue https://github.com/eclipse-theia/theia/issues/8640 and related PR https://github.com/eclipse-theia/theia/pull/8641

**Comment by azatsarynnyy** [comment]
I've fixed both upstream issues:
- in Quarkus VS Code extension - https://github.com/redhat-developer/vscode-quarkus/issues/309
- in Theia - https://github.com/eclipse-theia/theia/issues/8640

Theia [patch](https://github.com/redhat-developer/vscode-quarkus/pull/310) will go into Che 7.21
To apply Quarkus VS Code extension [patch](https://github.com/eclipse-theia/theia/pull/8641) to Che Quarkus Plugin, we need to:
1/ wait for the next extension's release, most likely it will be 1.8.0
2/ upgrade Che Quarkus Plugin to the next extension's version

All Editors related work is done. I'll keep the issue open for Plugins team to finalize it when the next version of Quarkus VS Code extension is released. cc @ericwill 
Feel free to close it and open a separate one for an upgrade if needed.

**Comment by azatsarynnyy** [comment]
I've updated the description with the required sub-tasks.

**Comment by ericwill** [comment]
> I've fixed both upstream issues:
> 
>     * in Quarkus VS Code extension - [redhat-developer/vscode-quarkus#309](https://github.com/redhat-developer/vscode-quarkus/issues/309)
> 
>     * in Theia - [eclipse-theia/theia#8640](https://github.com/eclipse-theia/theia/issues/8640)
> 
> 
> Theia [patch](https://github.com/redhat-developer/vscode-quarkus/pull/310) will go into Che 7.21
> To apply Quarkus VS Code extension [patch](https://github.com/eclipse-theia/theia/pull/8641) to Che Quarkus Plugin, we need to:
> 1/ wait for the next extension's release, most likely it will be 1.8.0
> 2/ upgrade Che Quarkus Plugin to the next extension's version
> 
> All Editors related work is done. I'll keep the issue open for Plugins team to finalize it when the next version of Quarkus VS Code extension is released. cc @ericwill
> Feel free to close it and open a separate one for an upgrade if needed.

I'll reset the milestone on this one for 7.24.

**Comment by azatsarynnyy** [comment]
reset the milestone to 7.26, as still waiting for Quarkus Tools release

**Comment by azatsarynnyy** [comment]
I'm moving it 7.x as it depends on the release of quarkus extension.
The last version was released [half a year ago](https://github.com/redhat-developer/vscode-quarkus/releases) BTW.

**Comment by ericwill** [comment]
> I'm moving it 7.x as it depends on the release of quarkus extension.
> The last version was released [half a year ago](https://github.com/redhat-developer/vscode-quarkus/releases) BTW.

We have the latest Quarkus plugin in upstream now: https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml#L210-L233

**Comment by azatsarynnyy** [comment]
yes, but it was released on Sep 21, 2020
and my fix was merged on Oct 15, 2020

**Comment by ericwill** [comment]
> yes, but it was released on Sep 21, 2020
> and my fix was merged on Oct 15, 2020

Understood :+1:

**Comment by azatsarynnyy** [comment]
VS Code Quarkus has been released https://github.com/redhat-developer/vscode-quarkus/releases
So, it's time to upgrade Che Quarkus Plugin. cc @svor
