### ISSUE TITLE
Che Deploy Sprint #191

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18011]
### Timeframe

|  October 7 |  October 27    |
| ------------- | ------------- | 

### Team
| Name  |  |
| ------------- |  ------------- |  
| Anatolii   | 13d |
| Mykola   | 12d | 
| Aleksandr  | 12d |  
| Flavius  |  6d |

- Oct. 14 Holiday
- Oct. 15 Hack 'n' Hustle
- Oct. 16 (or Oct. 18) Recharge Day
- 7 Oct. - 19 Oct. vacation (Flavius)

### CRW issues 
- [ ] OpenShift 4.3 with external Keycloak/RH-SSO https://issues.redhat.com/browse/CRW-405
---
### Eclipse Che issues 
- [ ] We should use services hostname instead of ingresses for inter-components communications https://github.com/eclipse/che/issues/17644 
  - [ ] https://github.com/eclipse/che-operator/pull/468
  - [ ] https://github.com/eclipse/che-theia/pull/865
  - [ ] https://github.com/eclipse/che/pull/17945
- [x] .[chectl] Add `server:login` command https://github.com/eclipse/che/issues/16415
  - [x] https://github.com/che-incubator/chectl/pull/910
  - [x] https://github.com/eclipse/che-operator/pull/503
- [x] .Automatically propagate certificates from ca-certs configmap into the components https://github.com/eclipse/che/issues/17918
  - [x] https://github.com/eclipse/che-operator/pull/487
  - [x] https://github.com/eclipse/che-operator/pull/493
- [ ] Stop using `self-signed-certificate` secret to store certificate chain of trust in favor of `ca-certs` config map https://github.com/eclipse/che/issues/17825 
  - [ ] Implement additional CA bundle propogation for non-OpenShift 4 infrastructures https://github.com/eclipse/che/issues/17634 
- [x] .chectl must detect issues while deploying Eclipse Che https://github.com/eclipse/che/issues/17937  https://github.com/eclipse/che/issues/17942 
  - [x] https://github.com/che-incubator/chectl/pull/908/
- [x] .Add server:deploy as alias to server:start command https://github.com/eclipse/che/issues/18057
  - [x] https://github.com/che-incubator/chectl/pull/909
  - [x] https://github.com/eclipse/che-docs/pull/1624
  - [x] https://github.com/eclipse/che-operator/pull/486/
  - [x] https://github.com/che-incubator/chectl/pull/941
- [x] .Please provide enhancements for end-of-installation script messaging https://github.com/eclipse/che/issues/18019
  - [x] https://github.com/che-incubator/chectl/pull/913
  - [x] https://github.com/redhat-developer/codeready-workspaces-chectl/pull/46
- [x] .IG - Please ensure users can run more than one workspace https://issues.redhat.com/browse/RHDEVDOCS-1956 
  - [x] https://github.com/eclipse/che-docs/pull/1628
---
- [x] .chectl: server:update should provide an ability to update Che Server configuration https://github.com/eclipse/che/issues/14974 
  - [x] https://github.com/che-incubator/chectl/pull/923
- [x] .Limit Keycloak's redirect url to certain urls https://github.com/eclipse/che/issues/17902
  - [x] https://github.com/eclipse/che-operator/pull/491
- [ ] AG - [Admin guide] S5.2 improvements: https://issues.redhat.com/browse/RHDEVDOCS-2228
- [x] .AG - Remove machineexec-rhel8 from suggested images to prepull https://issues.redhat.com/browse/RHDEVDOCS-2227 
- [x] .IG - Link to crwctl install doc 404's https://issues.redhat.com/browse/RHDEVDOCS-2156
---
- [ ] Unable to install Che on docker-desktop using helm3 on windows 10 using chectl https://github.com/eclipse/che/issues/17956
- [ ] We need to cover test case in the e2e tests when che-operator oauth is enabled  https://github.com/eclipse/che/issues/17939 
- [x] [che-operator] As a developer, I do not want to manually generate / update a dozen of files for every PR https://github.com/eclipse/che/issues/17338
  - [x] https://github.com/eclipse/che-operator/pull/498
- [x] `--che-operator-image` is ignored with `--installer olm` is used https://github.com/eclipse/che/issues/17936 
  - [x] https://github.com/che-incubator/chectl/pull/942/
- [x] .[chectl] Downloaded release binaries uses outdated version https://github.com/eclipse/che/issues/17823
  - [x] https://github.com/che-incubator/chectl/pull/930
---
### PR to merge
- [ ] https://github.com/che-incubator/chectl/pull/948
- [x] https://github.com/che-incubator/chectl/pull/929
- [x] https://github.com/che-incubator/chectl/pull/931
- [x] https://github.com/che-incubator/chectl/pull/943
- [ ] https://github.com/che-incubator/chectl/pull/951
---
### Unplanned
- [x] [chectl] [ux] Reorder/relabel successful deployment messages  https://github.com/eclipse/che/issues/18122
  - [x] https://github.com/che-incubator/chectl/pull/938
- [x] .Fix debugger for openshift cluster. https://github.com/eclipse/che-operator/pull/488 
- [x] After updating to che-operator 7.20.x sources, crw-operator build fails due to che_controller_test.go tests https://issues.redhat.com/browse/CRW-1297 
  - [x] https://github.com/eclipse/che-operator/pull/499
---
### Help provided
---
 [Previous Sprint](https://github.com/eclipse/che/issues/17800)
