### ISSUE TITLE
Plugins Sprint 191

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18016]
### CRW
* [x] Cannot terminate running Thorntail or SpringBoot tasks (crw 2.4 on OCP 4.4/Z @ PSI) [CRW-1242](https://issues.redhat.com/browse/CRW-1242) @svor 
    * Issue re-assigned to IBM team
* [x] Add Support for latest OpenShift Connector plugin [CRW-1220](https://issues.redhat.com/browse/CRW-1220) @ericwill 
* [x] Update to odo 2.0 in plugin-openshift-rhel8 and related plugins in registry [CRW-1259](https://issues.redhat.com/browse/CRW-1259) @ericwill 
* [ ] Customizing the devfile and plug-in registries documentation overly hard to read and understand [RHDEVDOCS-1762](https://issues.redhat.com/browse/RHDEVDOCS-1762) @tsmaeder 
* [x] Downstream-specific examples for "6. Using artifact repositories in a restricted environment" for downstream [RHDEVDOCS-2014](https://issues.redhat.com/browse/RHDEVDOCS-2014) @tsmaeder 
Opened two upstream PR's and delegated downstreaming to @themr0c Done from our side.
  * https://github.com/eclipse/che-docs/pull/1647
  * https://github.com/eclipse/che-docs/pull/1649

### Bugs
* [ ] Workspace Resource Monitor Plugin #17205 @svor 
* [x] new welcome page every time when I refresh my workspace #16352 @vitaliy-guliy 
* [x] Quarkus welcome page gets shown again and again #17994 @vitaliy-guliy 
    * Depends on Editors team fix for next sprint
* [x] What's "Quarkus command mode" stack? #17966 @ericwill 
* [ ] Error highlighting broken in several default stack #15919 @tsmaeder 
* [x] Git commit hot key doesn't work #18067 @vinokurig 

### Unplanned
* [x] Apply GitHub RemoteSourceProvider #18101 @vinokurig 

### Open PRs From Last Sprint
* [x] Improve login procedure for GitHub PullRequest Plugin #14217 @vinokurig 
    * [x] Align the GitHub authentication plugin with the latest vscode GitHub PR plugin #17684
* [x] Add environmentVariableCollection to PluginContext eclipse-theia/theia#8405 @vinokurig 
    * Needed to upgrade to the latest vscode-git, PR is open but needs to be reviewed

#### Theia API
* [ ] Using GIT plugin generates an error on the console eclipse-theia/theia#7953 @vinokurig 

#### Automation / Tests
* [x] Automate updating of sidecar images #17641 @ericwill 
    * [x] Experiment with a GH action che-dockerfiles that opens a PR on the che-plugin-registry
    * Discuss sidecar repo role with Florent/Mario
        * Result: we are moving the sidecars to the plugin registry
* [x] Move devfile and plugin registry jobs to GitHub action #18072 @ericwill 
    * [x] che-devfile-registry nightly build job
    * [x] che-plugin-registry nightly build job 

#### Maintenance
* [ ] Plugin Updates
    * [x] vscode-java 0.63.0 -> 0.69.0 #18170 @svor 
        * Update java built-in extension
        * Migrate `redhat/java` plugin to Java 11
    * [x] python needs to be updated to 2020.9.111407 #16183 @tsmaeder 
    * [ ] sonarlint-vscode 1.16 -> 1.17 @ericwill 
    * [x] OpenShift connector 0.1.5 -> 0.2.0 @ericwill 
    * [ ] Switch to newer version of builtin plugins #17524 @vitaliy-guliy 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 5  | 3 |
| @ericwill | 13 | 8 |
| @tsmaeder | 14 | 8 |
| @svor | 11 | 7 |

**Comment by ericwill** [comment]
Superseded by #18179
