### ISSUE TITLE
Editors Sprint 191

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18077]
Oct 7 - Oct 27

## Goals
1. IntelliJ IDEA as a Che editor
2. Multi-root Workspaces
3. Improving new user flow (with a focus on Quarkus)
4. Theia upstream focus
---
#### IntelliJ IDEA as a Che editor https://github.com/eclipse/che/issues/17790
  - [x] UBI-based Dockerfile for IntelliJ IDEA Che editor (investigation) https://github.com/eclipse/che/issues/18031
  - [ ] Documentation on how to integrate other web-based IDEs (on the example of IntelliJ Che Editor) [RHDEVDOCS#2161](https://issues.redhat.com/browse/RHDEVDOCS-2161)

#### Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212

#### Improving new user flow (with a focus on Quarkus) https://github.com/eclipse/che/issues/17985
- [x] File Explorer should be opened at workspace startup https://github.com/eclipse/che/issues/17969
- [x] Default path is / and not /projects/ in "Create Quarkus project" wizard https://github.com/eclipse/che/issues/18006
  - [x] [vscode-quarkus] Better UX when generating a Quarkus project: issue https://github.com/redhat-developer/vscode-quarkus/issues/309 + PR https://github.com/redhat-developer/vscode-quarkus/pull/310
  - [x] [Theia] workspace.workspaceFolders API should return undefined when no folder is open: issue https://github.com/eclipse-theia/theia/issues/8640 + PR https://github.com/eclipse-theia/theia/pull/8641
- [x] Disable tasks output scanning message https://github.com/eclipse/che/issues/17970
- [x] Theia "Debug" menu item should be "Run" menu item https://github.com/eclipse/che/issues/17967
  - [x] Rename Debug main menu according to VS Code https://github.com/eclipse-theia/theia/pull/8653
- [x] Remove File - Share command https://github.com/eclipse/che/issues/17287
  - https://issues.redhat.com/browse/CRW-1041

#### Collaboration in upstream Theia
- [x] Automated GitHub Milestones for Pull Requests https://github.com/eclipse-theia/theia/issues/8453

[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-10-07..2020-10-27+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-10-07..2020-10-27+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-10-07..2020-10-27+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-10-07..2020-10-27)

### Unplanned/Blockers
- [x] Fix publishing to npmjs https://github.com/eclipse/che-theia/pull/879
- [x] IDE hangs from time to time https://github.com/eclipse/che/issues/18151
- [x] 'Plugins' list is absent in IDE in CHE https://github.com/eclipse/che/issues/18211 [CRW#1300](https://issues.redhat.com/browse/CRW-1300)
---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 13  | 8
| Roman   | 10  | 6
| Artem | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/17897)
