### ISSUE TITLE
Plugins Sprint 192

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18179]
## Sprint 192 (October 28th 2020 to November 17th 2020)
This sprint will result in the release of Che 7.22.

### Epics
* [x] Provide experimental "portable JDK" devfile #17924 @tsmaeder 
    * Work deferred another sprint as platform team still needs to fix some items
* [ ] Allow Che 7 Git + SSH Flow #13494
    * [ ] Check for credentials (SSH) before trying to clone git repositories @svor 

### CRW
* [ ] Update documentation of artifact repositories using untrusted TLS certificates [RHDEVDOCS-2311](https://issues.redhat.com/browse/RHDEVDOCS-2311) @ericwill / @tsmaeder 
    * [ ] Update documentation of artifact repositories using untrusted TLS certificates #18131
* [ ] Consider adding VS Code GitHub Pull Request plug-in to CRW 2.6 [CRW-1226](https://issues.redhat.com/browse/CRW-1226) @vinokurig 
* [ ] Failed to start debug session for the "Python" devfile [CRW-1235](https://issues.redhat.com/browse/CRW-1235) @svor 
    * [ ] Update ms-python plugin to latest release [CRW-962](https://issues.redhat.com/browse/CRW-962) @ericwill 
* [ ] Please provide EsLint support for CRW [CRW-1357](https://issues.redhat.com/browse/CRW-1357)
    * [ ] Add eslint to Typescript language support plugins #14070 @vitaliy-guliy 

### Bugs
* [ ] Workspace Resource Monitor Plugin #17205 @svor 
* [ ] Error highlighting broken in several default stack #15919 @tsmaeder 
* [ ] new welcome page every time when I refresh my workspace #16352 @vitaliy-guliy 
    * [x] Unable to restore Theia state when webview and several editor tabs are opened eclipse-theia/theia#8621
    * [ ] Remove webview serializer eclipse/che-theia#878
* [x] All java devfiles don't have the debug port as endpoint with 'public=false' attribute #18138 @vitaliy-guliy 
* [x] Can not open a new Pull Request from the vscode GitHub PR plugin #18227 @vinokurig 
* [x] Add a name validation check when creating a new SSH key pair #18229 @vinokurig 

### Unplanned
* [x] XML support is not working in 0.13.0 vscode-xml built by vsix.Jenkinsfile [CRW-1337](https://issues.redhat.com/browse/CRW-1337) @ericwill 
    * [x] XML support broken #18247

#### Theia API
* [ ] Apply CommentController plugin API eclipse-theia/theia#8492 @vinokurig 

#### Automation / Tests
* [x] move sidecars definitions into plugin-registry #18217 @ericwill 
* [ ] migrate vscode-extensions.json to a che-plugins file #18215 @ericwill 
* [ ] Create a che-editors file to store all editors plugin definitions #18214 @ericwill 

#### Maintenance
* Plugin Updates
    * [x] Switch to newer version of builtin plugins #17524 @vitaliy-guliy 
        * [x] Investigate Docker LS issue/plugin https://github.com/eclipse/che/issues/17123
    * [x] ~~Investigate updating built-in extensions in upstream theia~~ @vitaliy-guliy  
    * [ ] Include default vscode extensions to Che-Theia #18282 @vitaliy-guliy 
* Docs
    * [ ] Review che-theia CONTRIBUTING.md for accuracy and fix as needed @vitaliy-guliy 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 15  | 9 |
| @vinokurig  | 15  | 9 |
| @ericwill | 14 | 8 |
| @tsmaeder | 10 | 6 |
| @svor | 13 | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Update documentation of artifact repositories using untrusted TLS certificates [RHDEVDOCS-2311](https://issues.redhat.com/browse/RHDEVDOCS-2311) |
| 2  | move sidecars definitions into plugin-registry #18217  |
| 3 | migrate vscode-extensions.json to a che-plugins file #18215 |
| 4 | Create a che-editors file to store all editors plugin definitions #18214 |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Provide experimental "portable JDK" devfile #17924 |
| 2  | Error highlighting broken in several default stack #15919 |
| 3 | Update documentation of artifact repositories using untrusted TLS certificates [RHDEVDOCS-2311](https://issues.redhat.com/browse/RHDEVDOCS-2311) |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Workspace Resource Monitor Plugin #17205 |
| 2  | Check for credentials (SSH) before trying to clone git repositories |
| 3 | Failed to start debug session for the "Python" devfile [CRW-1235](https://issues.redhat.com/browse/CRW-1235) |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Consider adding VS Code GitHub Pull Request plug-in to CRW 2.6 [CRW-1226](https://issues.redhat.com/browse/CRW-1226) |
| 2  | Can not open a new Pull Request from the vscode GitHub PR plugin #18227  |
| 3 | Add a name validation check when creating a new SSH key pair #18229 |
| 4 | Apply CommentController plugin API eclipse-theia/theia#8492 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1  |  new welcome page every time when I refresh my workspace #16352 |
| 2  | All java devfiles don't have the debug port as endpoint with 'public=false' attribute #18138  |
| 3 | Switch to newer version of builtin plugins #17524 |
| 4 | Investigate updating built-in extensions in upstream theia |
| 5 | Add eslint to Typescript language support plugins #14070 |
| 6 | Include default vscode extensions to Che-Theia #18282 |
| 7 | Review che-theia CONTRIBUTING.md for accuracy and fix as needed |
