### ISSUE TITLE
Che Deploy Sprint #192

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18192]
### Timeframe

|  October 28 |  November 17    |
| ------------- | ------------- | 

### Team
| Name  |  |
| ------------- |  ------------- |  
| Anatolii   | 15d |
| Mykola   | 14d | 
| Aleksandr  | 14d |  
| Flavius  |  14d |

- Nov. 6 Hack 'n' Hustle

---
### Eclipse Che issues 
- [ ] [ux] [crwctl] Support CLI method for deploying CRW 2.6 on OCP 4.x (part 2)  https://issues.redhat.com/browse/CRW-1288
  - [ ] [chectl] Telemetry: what commands and what k8s targets are people using? https://github.com/eclipse/che/issues/18069
  - [x] .Add new flags to chectl server:start (or server:deploy) to support more OperatorHub UI options https://github.com/eclipse/che/issues/18071
    - [x] https://github.com/che-incubator/chectl/pull/966
    - [x] https://github.com/che-incubator/chectl/pull/985
    - [x] https://github.com/redhat-developer/codeready-workspaces-chectl/pull/48
- [ ] Support level 3 of the operator framework capability levels https://github.com/eclipse/che/issues/18043
- [ ] We should use services hostname instead of ingresses for inter-components communications https://github.com/eclipse/che/issues/17644 
  - [ ] https://github.com/eclipse/che-operator/pull/468
  - [ ] https://github.com/eclipse/che-operator/pull/507
  - [ ] https://github.com/eclipse/che-theia/pull/865
  - [ ] https://github.com/eclipse/che/pull/17945
  - [ ] https://github.com/eclipse/che/pull/18225
- [ ] Stop using `self-signed-certificate` secret to store certificate chain of trust in favor of `ca-certs` config map https://github.com/eclipse/che/issues/17825 
- [ ] Implement additional CA bundle propogation for non-OpenShift 4 infrastructures https://github.com/eclipse/che/issues/17634 
- [x] .There is no need to add the self signed CA in single host mode  https://github.com/eclipse/che/issues/18082
  - [x] https://github.com/che-incubator/chectl/pull/950
- [x] .On Kubernetes we generate an untrusted SSL cert even when the default is a valid one https://github.com/eclipse/che/issues/18079 
  - [x] https://github.com/eclipse/che-operator/pull/508
  - [x]  https://github.com/eclipse/che/pull/18259
---
- [x] .[chectl] Add github action to test deploying Eclipse Che using helm installer https://github.com/eclipse/che/issues/18074
  - [x] https://github.com/che-incubator/chectl/pull/970
  - [x] https://github.com/eclipse/che/pull/18275
  - [x] https://github.com/che-incubator/chectl/pull/972
- [ ] We need to cover test case in the e2e tests when che-operator oauth is enabled https://github.com/eclipse/che/issues/17939
---
### PR to merge
- [x] .failure to deploy che when using the external Db https://github.com/eclipse/che/issues/18124
  - [x] https://github.com/eclipse/che-docs/pull/1656
- [ ] https://github.com/eclipse/che-docs/pull/1687
- [x] .chectl improvements https://github.com/che-incubator/chectl/pull/948
- [x] .Fix displaying error message https://github.com/che-incubator/chectl/pull/951
---
### Unplanned
  - [x] .Update minishift nightly tests  https://github.com/eclipse/che-operator/pull/524
  - [x] .Revert add bundle commit github action. We can't use it for protected master branch. https://github.com/eclipse/che-operator/pull/523
  - [x] .Fix to test updating stable versions Eclipse Che on minishift  https://github.com/eclipse/che-operator/pull/521
  - [x] .Unable to deploy Eclipse Che nightly >7.21.0 on OpenShift 4.6 using olm installer (chectl times out waiting for subscription to be ready on fresh OCP 4.6) https://github.com/eclipse/che/issues/18105
    - [x] https://github.com/che-incubator/chectl/pull/980/
    - [x] https://github.com/eclipse/che-operator/pull/522
    - [x] https://github.com/che-incubator/chectl/pull/983
  - [x] .Improve error detecting https://github.com/che-incubator/chectl/pull/973
  - [x] .Fix displaying keycloak credentials https://github.com/che-incubator/chectl/pull/969
  - [x] .https://github.com/eclipse/che-operator/pull/509/
  - [x] .Fix storage provisioner patch in chectl https://github.com/eclipse/che/issues/18228
    - [x] https://github.com/che-incubator/chectl/pull/960 
- [x] Adopt updating nightly bundle to the new operator-sdk version https://github.com/eclipse/che/issues/18349
  - [x] https://github.com/eclipse/che-operator/pull/533
- [x] Unable to shutdown server or login with chectl on windows 10 home https://github.com/eclipse/che/issues/18355
  - [x] https://github.com/che-incubator/chectl/pull/988
---
 [Previous Sprint](https://github.com/eclipse/che/issues/18011)
