### ISSUE TITLE
Create a workspace from a URL to a git repository in GitLab using a factory link

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18205]
Support Gitlab epic
- [x] Gitlab public repo support in factory URL https://github.com/eclipse/che/issues/19169
- [x] Gitlab private repo support in factory URL using personal access tokens https://github.com/eclipse/che/issues/19170
- [x] Gitlab private repo support using OAuth 2 flow https://github.com/eclipse/che/issues/19171

Subtasks that will be handled separately:
- Auto detect project type if no devfile.yaml. Maybe related to https://github.com/eclipse/che/issues/15868 and https://github.com/quarkusio/quarkus/issues/8951
- Add CRW/Che button to Gitlab. Could get inspiration from https://gitlab.com/gitlab-org/gitlab/-/merge_requests/37985
- Support Gitlab PR flow with a VSCode ext https://marketplace.visualstudio.com/items?itemName=gitlab.gitlab-workflow

**Comment by l0rd** [comment]
Closing this epic as the main functionality is here. The remaining tasks will be addressed separately.

**Comment by sunix** [comment]
@l0rd ok so would we file issues for the remaining tasks?

**Comment by l0rd** [comment]
@sunix sorry I thought we already had issues for the subtasks. I think that @sympatheticmoose wanted in particular that we prioritize the CRW/Che button one although that should be an epic and include GitHub, Gitlab and Bitbucket.

**Comment by themr0c** [comment]
Release notes:https://issues.redhat.com/browse/CRW-1822
