### ISSUE TITLE
IDE (client) - workspace agent (server) event transport service

### ISSUE THREAD

**Issue by dkulieshov** [eclipse-che/che#1824]
### Overview

There is a need in a handy mechanics so we could transfer arbitrary information (events, data, etc.) from server side (i.e. workspace agent) to client (i.e. IDE web application) and backward.
### Description

Most likely it would require to implement services both on client and server sides. The idea is to make a transparent service that should listen to events and transfer appropriate data through the transport bus (e.g. `web sockets`) using predefined transport protocol. 

Here are a few examples of such events:
- Client
  - file opened in an editor
  - file directory is expanded in a project explorer
  - project properties are modified
- Server
  - file is modified
  - directory is removed
  - git operation is performed

It is also worth noting that services should not strictly define the way that data is transferred. The best way is to use some transport agnostic protocol to be able to extend or change the service. So we should consider means for convenient change of transport bus (e.g. from `web sockets` to `REST`). 

As a transport protocol most suitable seems to be `Json` `RPC` protocol or something similar. It is `Json` based so it would make it easy to implement and to use. 
### Technical aspects
- Bidirectional web socket conversation
  - Client-server data transfer protocol that are applicable in our application are asymmetric in a way that server cannot start conversation on demand but only a client
  - Web sockets are also asymmetric but there are ways how to overcome this limitation by using workarounds that only web socket protocol provides.
  - Bidirectional behavior requires us to implement both sides for requests and responses processing. Those implementations differs because of the nature of client and server.
- Several agents support
  - There are several use cases when there can be a few IDE's opened and connected to a single server (workspace agent)
    - Several tabs in a single browser
    - Several browsers
    - Several users of a single workspace
  - That requires specific management approach for data transfer (via `web socket`).
  - This will require both server side and client side modifications
  - This will not require any work related to UI 
- High level data transfer protocol (`Json` `RPC`)
  - Transport agnosticism - in order to be able to use `REST` and `web socket` depending on our needs
  - Conformance to the specification
- Effective client side and server side event handling
  - We have a good client side event handling but it does not support new data transfer approach
  - We have `VFS` event handling system implemented so we just need a proper event detector implementation
### Technical tasks
- [x] Client-side service to track client state #1830 
- [x] Detector of VFS high level events related to client side state #1832 
### User stories
- [x] File editor real time content update #1910
- [x] File explorer real time content update #1911
- [x] Git checkout operation notification #1912

**Comment by dkulieshov** [comment]
After some initial work and analysis I believe the ETA of this epic should be about 3 weeks: 
- Technical scenarios - 2 weeks
- End user scenarios - 1 week
