### ISSUE TITLE
Editors Sprint 192

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18257]
Oct 28 - Nov 17

## Goals
1. Bugfixing
2. Multi-root Workspaces
3. Docs update: how to integrate other IDEs into Che/CRW
4. Theia upstream focus
---
#### Bugs
- [x] Autosave is moving the editor cursor while typing https://github.com/eclipse/che/issues/18096, https://github.com/eclipse/che/issues/16194, https://github.com/eclipse/che/issues/17023
- [ ] Welcome page fails to load in single-host https://github.com/eclipse/che/issues/17694, [CRW#1336](https://issues.redhat.com/browse/CRW-1336)
- [ ] Che Theia Web View doesn't work properly when a plugin is running in its own sidecar https://github.com/eclipse/che/issues/16870

#### Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212
  - WIP PR https://github.com/eclipse/che-theia/pull/778
  - [x] Align location field of ProgressOptions with VS Code https://github.com/eclipse-theia/theia/issues/8703
  - PR https://github.com/eclipse-theia/theia/pull/8700

#### Docs update
- [ ] Finalize the documentation on how to integrate other web-based IDEs (on the example of IntelliJ Che Editor) [RHDEVDOCS#2161](https://issues.redhat.com/browse/RHDEVDOCS-2161)
  - PR https://github.com/eclipse/che-docs/pull/1683

#### Collaboration in upstream Theia

[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-10-28..2020-11-17+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-10-28..2020-11-17+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-10-28..2020-11-17+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-10-28..2020-11-17)

### Unplanned/Blockers
- [x] Che loading is stuck on activating github-auth-plugin in Firefox 82.0.1 on Hosted Che https://github.com/eclipse/che/issues/18231
- [x] Che-Theia editor failed to start https://github.com/eclipse/che/issues/18255
- [x] Adapt Che Theia to upstream Theia changes https://github.com/eclipse/che/issues/18263
- [x] Adapt Che Theia to the latest changes in che-workspace-client lib https://github.com/eclipse/che/issues/18278
- IntelliJ-based Che editor enhancements:
   - [x] Workspace activity checker doesn't work for workspace based on "Intellij IDE" editor https://github.com/eclipse/che/issues/18171, [CRW#1310](https://issues.redhat.com/browse/CRW-1310)
   - [x] Disable window minimization for custom desktop based editors https://github.com/eclipse/che/issues/18321
   - [x] Install necessary libraries for support markdown plugin in JetBrains related products https://github.com/eclipse/che/issues/18336, https://github.com/eclipse/che/issues/18329
   - [x] Fullscreen error in IntelliJ 2020.2.2 in Che https://github.com/eclipse/che/issues/18330
   - [x] The "Intellij" workspace doesn't persist preferences [CRW#1364](https://issues.redhat.com/browse/CRW-1364)
   - [x] Unable to start two workspaces with a specified service endpoint https://github.com/eclipse/che/issues/18347

---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 14  | 8
| Roman   | 14  | 8
| Artem | 15  | 9

---
[Previous Sprint](https://github.com/eclipse/che/issues/18077)
