### ISSUE TITLE
Environment Provider and Agent SPI

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#1829]
**Overview**
This epic introduces usage of multi-machine environment definition syntax.

**Tasks**
- [x] Separate environment runtime management from workspace runtime management #1864 
- [x] Change Workspace environment model #1818
- [x] Make Che with multi-machine environments backward compatible #1820
- [x] Machine Agent specification and implementation #1823

**Impl Plan and Dependencies:**
2 goes after 1
3 can be done after 2
