### ISSUE TITLE
Plugins Sprint 193

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18354]
## Sprint 193 (November 17th 2020 to December 8th 2020)
This sprint will result in the release of Che 7.23.

### Epics
* [ ] Allow Che 7 Git + SSH Flow #13494
    * [ ] Check for credentials (SSH) before trying to clone git repositories: https://github.com/eclipse/che/issues/13494#issuecomment-694387267 @vitaliy-guliy 

### CRW
* [ ] Update documentation of artifact repositories using untrusted TLS certificates [RHDEVDOCS-2311](https://issues.redhat.com/browse/RHDEVDOCS-2311) @ericwill / @tsmaeder 
    * [ ] Update documentation of artifact repositories using untrusted TLS certificates #18131
* [ ] Consider adding VS Code GitHub Pull Request plug-in to CRW 2.6 [CRW-1226](https://issues.redhat.com/browse/CRW-1226) @vinokurig 
* [x] [3.11] Building a component failed with Openshift Connector Plugin [CRW-1352](https://issues.redhat.com/browse/CRW-1352) @vinokurig 
* [x] [4.6] Unable to find a running pod matching selector during starting of a component [CRW-1355](https://issues.redhat.com/browse/CRW-1355) @vinokurig 
* [ ] Failed to start debug session for the "Python" devfile [CRW-1235](https://issues.redhat.com/browse/CRW-1235) @ericwill 
    * [ ] Update ms-python plugin to latest release [CRW-962](https://issues.redhat.com/browse/CRW-962)
* [ ] XML support is not working in 0.13.0 vscode-xml built by vsix.Jenkinsfile [CRW-1337](https://issues.redhat.com/browse/CRW-1337) @ericwill 
* [ ] VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) @tsmaeder 
    * [ ] Java code snippets 'try_catch' and 'main' are not working #16502
    * [ ] Snippets don't work when Plugin Host is not colocated with Back End eclipse-theia/theia#8460
* [x] Please provide EsLint support for CRW [CRW-1357](https://issues.redhat.com/browse/CRW-1357) @vitaliy-guliy 
    * [x] Add eslint to Typescript language support plugins #14070

### Bugs
* [ ] Workspace Resource Monitor Plugin #17205 @svor 
* [ ] Error highlighting broken in several default stack #15919 @tsmaeder 
    * [ ] typescript needs to be updated to 1.50.1 #16186
* [x] switch from ephemeral to persistant workspace lets the database being ephemeral #18322 @vitaliy-guliy 
* [ ] [UX] When clicking "Run" nothing happens unless a java file is open / extension is loaded #18004 @sunix 
* [x] Project in "web-nodejs-with-db-sample" devfile sample is not compatible with node. #15649 @sunix 
* [ ] Asciidoc export to pdf fails #16370 @sunix 

### Unplanned
* [ ] Rework che-theia build process to not use source linking #16852 @tsmaeder 

#### Theia API
* [ ] Apply CommentController plugin API eclipse-theia/theia#8492 @vinokurig 

#### Automation / Tests
* [ ] Move devfile and plugin registry jobs to GitHub action #18072 @ericwill 
    * Migrate release jobs
    * Remove PR checks, and nightly build jobs
* [x] migrate vscode-extensions.json to a che-plugins file #18215 @ericwill 
* [ ] Create a che-editors file to store all editors plugin definitions #18214 @ericwill 
* [x] Create repo in redhat-developer to host Dockerfiles that build the vsix's we need @ericwill 
    * [x] Clean up code and clean up tagging system   
* [ ] Ability to run tests of a vscode extension on top of che-theia #18219 @svor 

#### Maintenance
* [ ] Check extensions of VS Code extension pack are running smoothly #15390 @sunix 
* [ ] The rust getting started sample should use the vscode extension #17069 @sunix 
* Plugin Updates
    * [ ] Include default vscode extensions to Che-Theia #18282 @vitaliy-guliy 
* Docs
    * [ ] Review che-theia CONTRIBUTING.md for accuracy and fix as needed @vitaliy-guliy 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 15  | 9 |
| @ericwill | 15 | 9 |
| @tsmaeder | 15 | 9 |
| @svor | 15 | 9 |
| @sunix | 15 | 9 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Update documentation of artifact repositories using untrusted TLS certificates [RHDEVDOCS-2311](https://issues.redhat.com/browse/RHDEVDOCS-2311) |
| 2 | Update ms-python plugin to latest release [CRW-962](https://issues.redhat.com/browse/CRW-962) |
| 3  | Create repo in redhat-developer to host Dockerfiles that build the vsix's we need  |
| 4 | Move devfile and plugin registry jobs to GitHub action #18072 |
| 5 | migrate vscode-extensions.json to a che-plugins file #18215 |
| 6 | Create a che-editors file to store all editors plugin definitions #18214 |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  typescript needs to be updated to 1.50.1 #16186 |
| 2 | Update documentation of artifact repositories using untrusted TLS certificates [RHDEVDOCS-2311](https://issues.redhat.com/browse/RHDEVDOCS-2311) |
| 3 | VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Workspace Resource Monitor Plugin #17205 |
| 2  | Ability to run tests of a vscode extension on top of che-theia #18219 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Consider adding VS Code GitHub Pull Request plug-in to CRW 2.6 [CRW-1226](https://issues.redhat.com/browse/CRW-1226) |
| 2  | [3.11] Building a component failed with Openshift Connector Plugin [CRW-1352](https://issues.redhat.com/browse/CRW-1352)  |
| 3 | [4.6] Unable to find a running pod matching selector during starting of a component [CRW-1355](https://issues.redhat.com/browse/CRW-1355) |
| 4 | Apply CommentController plugin API eclipse-theia/theia#8492 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1  | Add eslint to Typescript language support plugins #14070 |
| 2  | switch from ephemeral to persistant workspace lets the database being ephemeral #18322  |
| 3 |  Include default vscode extensions to Che-Theia #18282 |
| 4 | Check for credentials (SSH) before trying to clone git repositories: https://github.com/eclipse/che/issues/13494#issuecomment-694387267 |
| 5 | Review che-theia CONTRIBUTING.md for accuracy and fix as needed |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1  | Project in "web-nodejs-with-db-sample" devfile sample is not compatible with node. #15649 |
| 2  | The rust getting started sample should use the vscode extension #17069  |
| 3 | Asciidoc export to pdf fails #16370 |
| 4 | Check extensions of VS Code extension pack are running smoothly #15390 |
| 5 | [UX] When clicking "Run" nothing happens unless a java file is open / extension is loaded #18004 |

**Comment by ericwill** [comment]
Superseded by #18529
