### ISSUE TITLE
Use Docker in swarm mode for bringing up containers at scale

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#1836]
We want to run Che on Docker in swarm mode by default out of the box. This means that we need to move Che onto Docker 1.12, verify all of the usage, and then support ability to launch workspaces on Docker Swarm nodes. We will need instructions for how user can add / remove additional swarm nodes used by Che.

Sub-tasks:
- [ ] Investigate how to use images built from Dockerfiles with docker in swarm mode #2009 
- [ ] Investigate how to use Docker Swarm mode in Docker 1.12 #2228 
- [ ] Investigate what should be done to run che-server/che-launcher in docker with swarm mode #2254

**Comment by TylerJewell** [comment]
@garagatyi - can you link together other swarm issues into this epic with a single checklist please?

**Comment by garagatyi** [comment]
Do you mean Swarm mode in Docker 1.12? If so then body of that issue contains the list.
