### ISSUE TITLE
Che Deploy Sprint #193

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18375]
### Timeframe

|  November 18 | December 8    |
| ------------- | ------------- | 

### Team
| Name  |  |
| ------------- |  ------------- |  
| Anatolii   |  |
| Mykola   |  | 
| Aleksandr  |  |  
| Flavius  |   |

- Nov. 27 Hack 'n' Hustle
- Dec 7 Spain Holiday
- Dec 8 Spain Holiday

CRW 2.6 is based on Eclipse Che 7.24.x

---
### Eclipse Che issues 
- [x] .[EUG] Rework section 'Creating a workspace using chectl and a local devfile' https://issues.redhat.com/browse/RHDEVDOCS-2302 
  - [x] https://github.com/eclipse/che-docs/pull/1698
- [x] .AG - [Admin guide] S5.2 improvements: note need to have oauth provider installed first; remove note about single-user mode (not supported) https://issues.redhat.com/browse/RHDEVDOCS-2228
  - [x] https://github.com/eclipse/che-docs/pull/1702
- [x] .EUG - Configuring OpenShift OAuth https://issues.redhat.com/browse/RHDEVDOCS-2180
- [ ] [ux] [crwctl] Support CLI method for deploying CRW 2.6 on OCP 4.x (part 2)  https://issues.redhat.com/browse/CRW-1288
  - [ ] [chectl] Telemetry: what commands and what k8s targets are people using? https://github.com/eclipse/che/issues/18069
    - [ ] https://github.com/che-incubator/chectl/pull/992/
  - [x] .Add a new chectl command server:deploy and change server:start behavior https://github.com/eclipse/che/issues/18015
    - [x] https://github.com/che-incubator/chectl/pull/990
- [ ] `keytool` imports the only one certificate from the file https://github.com/eclipse/che/issues/18339
  - [ ] https://github.com/eclipse/che/pull/18504
  - [ ] https://github.com/eclipse/che-operator/pull/560
- [ ] Identity Provider configuration broken https://issues.redhat.com/browse/CRW-1361
  - [ ] https://github.com/eclipse/che-operator/pull/551
- [ ] Unable to limit Users to specific groups with RHSSO & RH IdM https://issues.redhat.com/browse/CRW-1177
- [x] .We should use services hostname instead of ingresses for inter-components communications https://github.com/eclipse/che/issues/17644 
  - [x] https://github.com/eclipse/che-operator/pull/468
  - [x] https://github.com/eclipse/che-operator/pull/507
  - [x] https://github.com/eclipse/che-theia/pull/865
  - [x] https://github.com/eclipse/che/pull/17945
  - [x] https://github.com/eclipse/che/pull/18225
  - [x] https://github.com/eclipse/che-docs/pull/1704
- [x] .Implement additional CA bundle propogation for non-OpenShift 4 infrastructures https://github.com/eclipse/che/issues/17634
  - [x] https://github.com/eclipse/che-operator/pull/531 
  - [x] https://github.com/eclipse/che/pull/18377
  - [x] https://github.com/eclipse/che/pull/18519
- [ ] Please provide more flexibility at installation time https://github.com/eclipse/che/issues/18018
  - [ ] https://github.com/eclipse/che-docs/pull/1719
- [x] .[chectl] [che-operator] Make REAMDE.md files up to date https://github.com/eclipse/che/issues/18295
  - [x] https://github.com/eclipse/che-operator/pull/553/
- [ ] travis-ci and chectl https://github.com/eclipse/che/issues/18260
- [ ] Add e2e tests for chectl olm installer in Openshift 4.6 and OCP nightly https://github.com/eclipse/che/issues/18293 
  - [x] https://github.com/che-incubator/chectl/pull/998
  - [ ] https://github.com/openshift/release/pull/13775
  - [x] https://github.com/openshift/release/pull/13771
  - [ ] https://github.com/openshift/release/pull/14073
  - [x] https://github.com/che-incubator/chectl/pull/1001
  - [ ] https://github.com/eclipse/che-operator/pull/564/
  - [x] https://github.com/eclipse/che-operator/pull/557
---
### PR to merge
- [x] https://github.com/eclipse/che-docs/pull/1687
---
### Unplanned
- [x] .[chectl] credentials of user for dashboard are not displayed when installing che on docker-desktop 
https://github.com/eclipse/che/issues/18416 
  - [x] https://github.com/che-incubator/chectl/pull/1012
- [x] .chectl server:start on docker-desktop as platform fails by default https://github.com/eclipse/che/issues/18413
  - [x] https://github.com/che-incubator/chectl/pull/1012
- [x] .[helm] Failed to deploy Eclipse Che using helm v3.4.1 https://github.com/eclipse/che/issues/18396
  - [x] https://github.com/che-incubator/chectl/pull
- [x] .Introduce chectl context https://github.com/che-incubator/chectl/pull/1009
- [x] .Need to port `che-username-readonly` keycloak theme to the CRW https://issues.redhat.com/browse/CRW-1379
  - [x] https://github.com/eclipse/che-operator/pull/540
  - [x] https://github.com/eclipse/che-operator/pull/554
- [x] .Creating workspaces using chectl in single-user mode requires authentication https://github.com/eclipse/che/issues/18406
  - [x] https://github.com/che-incubator/chectl/pull/996
- [x] .Externailize dependency on operator-sdk so it's not hardcoded in 4 scripts https://github.com/eclipse/che/issues/18419
  - [x] https://github.com/eclipse/che-operator/pull/545
- [x] .Fix actual state csv check https://github.com/eclipse/che-operator/pull/552
- [x] .[chectl] default timeouts don't work in 'chectl server:deploy' command on minikube https://github.com/eclipse/che/issues/18464
  - [x] https://github.com/che-incubator/chectl/pull/1006
---
 [Previous Sprint](https://github.com/eclipse/che/issues/18192)
