### ISSUE TITLE
Split view for editor

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#1837]
"Side-by-side editors to simplify working on larger applications."
split vertically/horizontally, for instance when right clicking the editor tab it should be possible to split editor vertically or horizontally.
- [x] Sync content of the file for all opened tabs of this file #1838
- [x] Correct processing some operations for editor #1839
- [x] Adapt Editor agent to manage multi parts #1840
- [x] Improved tabbed editor design #1841
