### ISSUE TITLE
Create a workspace from a URL to a git repository in Bitbucket using a factory link

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18385]
### Is your task related to a problem? Please describe.
The goal of this task is to allow to store devfile in public or private Bitbucket
on-prem server and use them with Che factory.

Minimal version `Atlassian Bitbucket v5.15.2`

Potentially it should be possible to extend this functionality on Bitbucket SAAS.

### Describe the solution you'd like

https://github.com/eclipse/che/issues/18226#issuecomment-727887994

### Describe alternatives you've considered
n/a

### Additional context
https://github.com/eclipse/che/issues/17829

### Implementation
 - [x] Study possible ways to get devfile content from private Bitbucket repository during factory resolving process  https://github.com/eclipse/che/issues/18226
- [x] Basic factory flow with bitbucket URL-s https://github.com/eclipse/che/issues/18397
- [x] Using Bitbucket personal access token as k8s secret during factory resolution https://github.com/eclipse/che/issues/18386
- [x] Obtain and persist Bitbucket personal access token as k8s secret https://github.com/eclipse/che/issues/18388
- [x] Make Bitbucket's sensitive configuration file-based #18710
- [x] Clarify factory resolution process for private Bitbucket repositories  https://github.com/eclipse/che/issues/18389 
- [x] Support OAuth flow for private repo factories on Dashboard https://github.com/eclipse/che/issues/18976
- [x] [che-operator] Configure OAuth1 and OAuth2 integrations with K8s Secrets https://github.com/eclipse/che/issues/18932
- [x]  Improve workflow when a user denies Bitbucket access for Che | #19274
- [x] The default devfile is resolved from private bitbucket repo after access token is revoked | #19273

**Comment by l0rd** [comment]
@skabashnyuk closing as it looks everything as been fixed, please reopen if there is something left
