### ISSUE TITLE
The "che-dashboard-next" testing roadmap

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#18391]
# 0 stage
(responsibility of the "dashboard-next" team)

- [x] **1)** Coverage by component tests should be more than 50% (Current coverage is `~ 48%`) https://github.com/eclipse/che/issues/18414

# 1-st stage
(responsibility of the "Che QE" team)

- [x]  **1)** Rework existing che devfiles tests for using new dashboard. Keep changes in separate branch for been ready to switching dashboard. (https://github.com/eclipse/che/issues/16911)

- [x] **2)** Rework the "Happy Path" test for using new dashboard. Keep changes in separate branch for been ready to switching dashboard. (https://github.com/eclipse/che/pull/18428)

- [x] **3)** Review other tests from the "che/tests/e2e" folder and update them if they depend to the new dashboard. Keep changes in separate branch for been ready to switching dashboard. _(When the dashboard is applied by default and will be accessible by the  "<che_url>/dashboard" URL, tests should work as expected. Pageobjects already reworked.)_

- [x] **4)** Create a smoke test for validation workspace creation from the dashboard (basically may be used 1 devfile test ). Done https://github.com/eclipse/che/pull/18428

- [x] **5)** Implement the "quality gate" using a smoke test for the "dashboard next" repo (run test for each PR and for changes inside PR ) https://github.com/eclipse/che/issues/18454

# 2-nd stage 
(responsibility of the "Che QE" and  "dashboard-next" teams)

- [ ] **1)** Add to "quality gate" running of the existing component tests and coverage measuring.

- [ ] **2)** Create the "e2e" test for covering the most critical functionality (1 userstory)

- [ ] **3)** Apply created test for the "quality gate" instead of "smoke" test

- [ ] **4)** Create integration tests for covering other important functionality

- [ ] **5)** Add created integrational tests to the "quality gate"

Related issue: https://github.com/eclipse/che/issues/18348

**Comment by Ohrimenko1988** [comment]
Current coverage by component tests is something close to 10%
![Screenshot from 2020-11-18 11-37-20](https://user-images.githubusercontent.com/22724619/99513322-2c97a880-2993-11eb-87f1-c75e4bfc44aa.png)
@l0rd @rhopp @dmytro-ndp @olexii4 @akurinnoy @sleshchenko WDYT ?

**Comment by psrna** [comment]
Thanks for preparing the plan, Ihor. It looks solid. However I suggest to highlight ownership of the respective stages to make it clear who is responsible for what, e.g. stage 0 is owned by dashboard.next engineering team., stage 1 Che QE team etc.

For promoting dashboard.next to be the default, I consider completion of stage 0 & 1 as a requirement. Otherwise we will be creating technical debt.

**Comment by Ohrimenko1988** [comment]
> Thanks for preparing the plan, Ihor. It looks solid. However I suggest to highlight ownership of the respective stages to make it clear who is responsible for what, e.g. stage 0 is owned by dashboard.next engineering team., stage 1 Che QE team etc.
> 
> For promoting dashboard.next to be the default, I consider completion of stage 0 & 1 as a requirement. Otherwise we will be creating technical debt.

Done.

**Comment by Ohrimenko1988** [comment]
Current coverage by unit tests is `~ 30%`
![Screenshot from 2020-11-24 11-43-32](https://user-images.githubusercontent.com/22724619/100077080-96f49100-2e4a-11eb-9b8f-6577ffcebddd.png)

**Comment by gazarenkov** [comment]
Hi @psrna 

First of all I highly appreciate the initiative of making test unit coverage analysis recommendations, I strongly believe it is a really good goal toward improving product quality.
I am curious whether we have the same requirement (50% of code should be covered with test units as a *strong, phase 0 prerequisite*) for all the components or it is a privilege of the Dashboard.next only? :)

**Comment by psrna** [comment]
Hi @gazarenkov 

thank you for bringing up this topic.

I believe that we should treat all components the same. Dashboard.next should not be unique. And you probably correctly identified that we have a lot of technical debt in other components as well.

But for dashboard.next I think we should do it right rather then burning technical debt later. We might argue about the coverage number. However the number itself is not important. What is important, is that we are DONE if we do have sufficient test coverage that gives us confidence in the quality. Component level tests are the foundations and the biggest part of the testing pyramid. Compared to the Integration tests, they have the benefits of being cheap in terms of execution time and stability and tremendously help preventing bugs. 

Would you agree that we don't have the required confidence with the current level of component tests?

**Comment by gazarenkov** [comment]
@psrna 
>Would you agree that we don't have the required confidence with the current level of component tests?

I would agree that we do not pay enough attention to the unit test coverage analysis. It is even difficult to know what is the current coverage level in general... Do we have the actual numbers for all the components somewhere?

**Comment by psrna** [comment]
@gazarenkov, 

I agree with your statement and I don't think we have a consolidated coverage report for all the components. I'll bring it up as a goal/topic to discuss in the next internal call.

**Comment by sleshchenko** [comment]
The current test coverage is a bit less than 50%
![Screenshot_20201231_103803](https://user-images.githubusercontent.com/5887312/103402106-53312d80-4b54-11eb-8334-7b9d8a4fd43d.png)
But as we agreed on Che Internal Call, the number is not the goal.
Code coverage in existing components is going to be improved along the way, new components should be provided along with proper test coverage.
So, 0 stage is complete

**Comment by nickboldt** [comment]
Slip to 7.26 since not completed for 7.25

**Comment by sleshchenko** [comment]
The stage 1 is done in 7.26. Removing milestone since there is no concrete timeframe for stage 2 at this point.
