### ISSUE TITLE
Editors Sprint 193

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18403]
Nov 18 - Dec 8

## Goals
1. Bugfixing
2. Multi-root Workspaces
3. Docs update
4. Better UX when Che Theia is offline
5. Theia upstream focus
---
#### Bugs
- [x] Welcome page fails to load in single-host https://github.com/eclipse/che/issues/17694, [CRW#1336](https://issues.redhat.com/browse/CRW-1336)
- [ ] Che Theia Web View doesn't work properly when a plugin is running in its own sidecar https://github.com/eclipse/che/issues/16870
  - [ ] Implement simple file system provider to fetch files from containerized plugin https://github.com/eclipse/che/issues/18405
- [ ] In some cases, Debug views are collapsed https://github.com/eclipse/che/issues/18034

#### Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212
  - WIP PR https://github.com/eclipse/che-theia/pull/778
  - [ ] Change config storage paths from /home/theia/home/theia to the corresponding paths https://github.com/eclipse/che/issues/18548

#### Docs update
- [ ] How to integrate other web-based IDEs (on the example of IntelliJ Che Editor) [RHDEVDOCS#2161](https://issues.redhat.com/browse/RHDEVDOCS-2161)
  - PR is being reviewed https://github.com/eclipse/che-docs/pull/1683

#### Better UX when Che Theia is offline
- [ ] Che Theia should notify/disable actions + inform the user how to restart the workspace when it's stopped https://github.com/eclipse/che/issues/18302

#### Collaboration in upstream Theia
- [ ] Support `workbench.action.files.openFileFolder` built-in command https://github.com/eclipse-theia/theia/issues/8750

[PRs reviewed](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+reviewed-by%3ARomanNikitenko+reviewed-by%3Aazatsarynnyy+reviewed-by%3Avzhukovskii+created%3A2020-11-18..2020-12-08+is%3Apr) | [PRs opened](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-11-18..2020-12-08+is%3Apr) | [Issues reported](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+author%3ARomanNikitenko+author%3Aazatsarynnyy+author%3Avzhukovskii+created%3A2020-11-18..2020-12-08+is%3Aissue) | [Other participation](https://github.com/search?q=repo%3Aeclipse-theia%2Ftheia+commenter%3ARomanNikitenko+commenter%3Aazatsarynnyy+commenter%3Avzhukovskii+created%3A2020-11-18..2020-12-08)

### Unplanned/Blockers
- [ ] Move Che Theia nightly/main builds from ci.centos.org to GitHub Actions https://github.com/eclipse/che/issues/18407
- [x] It's not obvious to users that default directory for project in the workspace based on the "Intellij" IDE doesn't persist https://github.com/eclipse/che/issues/18270, [CRW#1343](https://issues.redhat.com/browse/CRW-1343)
- [x] Backport WebVIew realted [patch](https://github.com/eclipse/che-theia/pull/936) to 7.20.x for CRW 2.5.1 [CRW#1393](https://issues.redhat.com/browse/CRW-1393)
- [x] Adapt Che Theia to upstream changes https://github.com/eclipse/che/issues/18456
- [x] Document the differences of Che Theia WebView behavior in single-/multi-host modes https://github.com/eclipse/che/issues/18496
- [ ] Adapt telemetry functionality in Che Theia to single-host https://github.com/eclipse/che/issues/18503

---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 14  | 8
| Roman   | 14  | 8
| Artem | 15  | 9

---
[Previous Sprint](https://github.com/eclipse/che/issues/18257)
