### ISSUE TITLE
[new UD] Provide unit tests for testing roadmap stage 0

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#18414]
Test coverage in new UD is low, there is lack of unit tests for React components and containers, Redux stores and selectors. 

In order to done [the testing roadmap](https://github.com/eclipse/che/issues/18391) stage 0 we need to provide unit tests for those React components and other files, that allows us to quicker get the test coverage above 50%.

React components (including nested) to test:

- [x] [src/Layout](https://github.com/che-incubator/che-dashboard-next/tree/master/src/Layout)
![Screenshot_20201231_102510](https://user-images.githubusercontent.com/5887312/103401679-7a86fb00-4b52-11eb-93c1-aa80b03e0e46.png)
- [x] [src/components/DevfileEditor](https://github.com/che-incubator/che-dashboard-next/tree/master/src/components/DevfileEditor) -> PR: https://github.com/che-incubator/che-dashboard-next/pull/78
- [x] [src/components/LogsTab](https://github.com/che-incubator/che-dashboard-next/tree/master/src/components/LogsTab)
- [x] [src/components/Workspace](https://github.com/che-incubator/che-dashboard-next/tree/master/src/components/Workspace)
![Screenshot_20201231_102543](https://user-images.githubusercontent.com/5887312/103401690-8ecaf800-4b52-11eb-8a75-cf3fcf61bed9.png)
- [x] [src/containers/FactoryLoader.tsx](https://github.com/che-incubator/che-dashboard-next/tree/master/src/containers)
![Screenshot_20201231_102603](https://user-images.githubusercontent.com/5887312/103401726-bfab2d00-4b52-11eb-84e9-2b7872493c70.png)
- [x] [src/containers/WorkspaceDetails.tsx](https://github.com/che-incubator/che-dashboard-next/tree/master/src/containers)
![Screenshot_20201231_102621](https://user-images.githubusercontent.com/5887312/103401730-c5087780-4b52-11eb-8a0b-d893d0c9591a.png)
- [x] [src/containers/WorkspacesList.tsx](https://github.com/che-incubator/che-dashboard-next/tree/master/src/containers)
![Screenshot_20201231_102740](https://user-images.githubusercontent.com/5887312/103401747-d3ef2a00-4b52-11eb-9028-0c7123d8e944.png)
- [x] [src/pages/GetStarted/CustomWorkspaceTab](https://github.com/che-incubator/che-dashboard-next/tree/master/src/pages/GetStarted/CustomWorkspaceTab) -> PR: https://github.com/che-incubator/che-dashboard-next/pull/83
- [ ] [src/pages/WorkspaceDetails/DevfileTab](https://github.com/che-incubator/che-dashboard-next/tree/master/src/pages/WorkspaceDetails/DevfileTab)
![Screenshot_20201231_102801](https://user-images.githubusercontent.com/5887312/103401754-e36e7300-4b52-11eb-94f5-25586765a093.png)
- [ ] [src/pages/WorkspaceDetails/OverviewTab](https://github.com/che-incubator/che-dashboard-next/tree/master/src/pages/WorkspaceDetails/OverviewTab)
![Screenshot_20201231_102836](https://user-images.githubusercontent.com/5887312/103401767-f5501600-4b52-11eb-80a0-ad0285cb1031.png)

<details>
<summary>Files filtered by the lowest coverage</summary>

![Screenshot_20201231_102957](https://user-images.githubusercontent.com/5887312/103401854-4cee8180-4b53-11eb-95ca-b466ea8cff1e.png)

</details>

**Comment by sleshchenko** [comment]
The code coverage is improved significantly. Detailed info is filled into the PR description, the summary is
![Screenshot_20201231_103303](https://user-images.githubusercontent.com/5887312/103401907-94750d80-4b53-11eb-90d3-cb7bb80ada1c.png)
