### ISSUE TITLE
Che Controller Sprint #193

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18412]
## Dashboard Next
- [ ] Provide unit tests for testing roadmap stage 0 #18414
- [x] Add Actions for the WorkspaceDetails page #18013
- [ ] Workspaces list #16646
- [x] Show proper error page when failed to load keycloak settings due self-signed TLS #18098
- [x] List docs articles which references Dashboard UI https://github.com/eclipse/che/issues/18392

## DevWorkspace Operator

- [x] Implement conversion webhooks for devfile/api versions for OpenShift https://github.com/devfile/devworkspace-operator/issues/189
- [ ] Investigate Volume component https://github.com/devfile/devworkspace-operator/issues/185
- [x] DevWorkspace Routing TLS (K8s - certmanager, openShift - just the default cert) + unique hosts https://github.com/devfile/devworkspace-operator/issues/200
- [x] Verify if mkdir container can be safely removed https://github.com/devfile/devworkspace-operator/issues/198

## Web Terminal 1.2

- [x] Finalize: an ability to use Terminal by Cluster Admins [WTO-16](https://issues.redhat.com/browse/WTO-16). PR https://github.com/openshift/console/pull/7145
- [x] Finalize: OpenShift Console should clearly say that workspace is stopped by inactivity [WTO-47](https://issues.redhat.com/browse/WTO-47). PR https://github.com/openshift/console/pull/7199
- [x] Figure out GA process https://issues.redhat.com/browse/WTO-61
- [ ] 100% Release Automation with CPaas [WTO-62](https://issues.redhat.com/browse/WTO-62)

## Unplanned
- [x] Progress of workspace starting doesn't display on the dashboard-next https://github.com/eclipse/che/issues/18477
