### ISSUE TITLE
[che-plugins] php-web-simple workspace failed to start because "v3/plugins/felixfbecker/vscode-php-debug/latest/meta.yaml" not found

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18493]
### Describe the bug
php-web-simple workspace failed to start because of absence of **v3/plugins/felixfbecker/vscode-php-debug/latest/meta.yaml**:
![screenshot-Wait_for_workspace_readiness (4)](https://user-images.githubusercontent.com/1197777/100715100-6028f880-33bf-11eb-9fce-b96e56ea0f70.png)

Reference to plugin in devfile: https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-web-simple/devfile.yaml#L18

Actually, there is no **v3/plugins/felixfbecker/vscode-php-debug/** in repo https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/felixfbecker/

Corresponding commits: 
- https://github.com/eclipse/che-plugin-registry/commit/8a7341676ae60f2ef82942f722a3206ea7c99921
- https://github.com/eclipse/che-devfile-registry/commit/06a6b1684bcfefd19e1945dc0da0f87dedddf3cf

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Install nightly Eclipse Che
2. Try to start php-web-simple workspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by ericwill** [comment]
Fixed by eclipse/che-devfile-registry#310
