### ISSUE TITLE
Che Controller Sprint 194

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18534]
## Dashboard 
- [x] No information about the root cause when using factories with invalid devfile https://github.com/eclipse/che/issues/18164

## Dashboard Next
- [ ] Workspaces list #16646
- [x] Copy chectl login command on the Dashboard Next https://github.com/eclipse/che/issues/18533
- [ ] Prototype Container Registries on the Dashboard Next https://github.com/eclipse/che/issues/18526
- [x] Dashboard Next workspace loader does not respect workspace failure https://github.com/eclipse/che/issues/18547
- [ ] It's not possible to refresh Keycloak token https://github.com/eclipse/che/issues/18311
- [x] Dashboard Next does not propagate properly workspace creation/deletion failure reason https://github.com/eclipse/che/issues/18554
- [ ] Adapt documentation to Dashboard Next https://github.com/eclipse/che/issues/18518

## Devfile 2.0
- [ ] ~~Investigate devfile flattening + devworkspace startup workflow https://github.com/devfile/devworkspace-operator/issues/227~~

## Faster Workspace Start 
- [x] Investigate how reducing containers number influences workspace-startup time https://github.com/devfile/devworkspace-operator/issues/218

## DevWorkspace Dogfooding
- [ ] Contribute the flattened devfile 2.0 with needed plugins and tools https://github.com/devfile/devworkspace-operator/issues/217

## WTO
- [ ] Develop a web terminal plugin version https://issues.redhat.com/browse/WTO-65
- [ ] set up e2e test for Web Terminal Operator https://issues.redhat.com/browse/WTO-26
- [ ] Occasionally you will get: "Error Loading OpenShift command line terminal: Could not retrieve $KUBECONFIG" when trying to open a terminal https://issues.redhat.com/browse/WTO-63
- [ ] Occasionally you will need to press enter to get a prompt inside of the web-terminal https://issues.redhat.com/browse/WTO-43

## Unplanned
- [x] Enable external solvers of WorkspaceRouting objects in devworkspace operator https://github.com/eclipse/che/issues/18520
- [x] Dashboard Next Add Make a wish, Documentation, FAQ, Community, About https://github.com/eclipse/che/issues/18567
- [ ] Dashboard Next landing page should depend on the number of workspaces https://github.com/eclipse/che/issues/18609
- [x] Fix the Dashboard next tab title https://github.com/eclipse/che/issues/18581
- [ ] Dashboard Next should propose user to restart a workspace in debug mode if it's failed https://github.com/eclipse/che/issues/18640
