### ISSUE TITLE
Che Deploy Sprint #194

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18542]
#### Timeframe
Dec. 9 - Dec. 29

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays:
- Dec. 18 Hack 'n' Hustle
- Dec. 25 Ukraine/Spain Holiday
- Dec. 28-31 PTO Aleksandr
- Dec. 18-31 PTO Flavius

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x

---
### CRW issues 
- [ ] Unable to limit Users to specific groups with RHSSO & RH IdM https://issues.redhat.com/browse/CRW-1177
- [ ] CodeReady Workspace is using test route to fetch CA certifcates instead of defined cheHost
https://issues.redhat.com/browse/CRW-1403
- [x] .[AG] Document how to set up Keycloak / RH SSO readonly theme
https://issues.redhat.com/browse/RHDEVDOCS-2453
  - [x] https://github.com/eclipse/che-docs/pull/1723
- [x] .Add release notes about internal cluster svc names usage in communication
https://issues.redhat.com/browse/RHDEVDOCS-2442
- [x] Identity Provider configuration broken https://issues.redhat.com/browse/CRW-1361
  - [x] https://github.com/eclipse/che-operator/pull/551
  - [x] https://github.com/che-incubator/chectl/pull/1038
- [ ] [ux] [crwctl] Support CLI method for deploying CRW 2.6 on OCP 4.x (part 2)  https://issues.redhat.com/browse/CRW-1288
  - [ ] [chectl] Telemetry: what commands and what k8s targets are people using? https://github.com/eclipse/che/issues/18069
    - [ ] https://github.com/che-incubator/chectl/pull/992/
- [ ] The CLI installation process is not documented for OCP v4.x clusters
https://issues.redhat.com/browse/RHDEVDOCS-2419
---
### Eclipse Che issues 
- [x] .[Hosted Che] Failed to rollout 7.23.0-SNAPSHOT - Jwks endpoint url not found in keycloak https://github.com/eclipse/che/issues/18553
  - [x] https://github.com/eclipse/che/pull/18563
  - [x] https://github.com/eclipse/che/pull/18631
- [x] .Improve chectl helm installer to fix cheWorkspacesNamespace che-ws-<username> problem https://github.com/eclipse/che/issues/18459
  - [x] https://github.com/che-incubator/chectl/pull/1026
- [x] .Chectl does not respect dashboard deployment https://github.com/eclipse/che/issues/18421
  - [x] https://github.com/che-incubator/chectl/pull/1024
- [ ] Create a valid user if no one exist when deploying on OpenShift https://github.com/eclipse/che/issues/18152
- [x] Kube.ts: ClusterIssuer Detection https://github.com/eclipse/che/issues/18450
  - [x] https://github.com/che-incubator/chectl/pull/1037
- [ ] Automate the setup of github identity provider with internal keycloak https://github.com/eclipse/che/issues/18238
  - [ ] https://github.com/eclipse/che-operator/pull/589
- [x] .chectl server:update requires chectl to be updated first https://github.com/eclipse/che/issues/18514
  - [x] https://github.com/che-incubator/chectl/pull/1022
  - [x] https://github.com/eclipse/che-docs/pull/1729
- [x] .`keytool` imports the only one certificate from the file https://github.com/eclipse/che/issues/18339
  - [x] https://github.com/eclipse/che/pull/18504
  - [x] https://github.com/eclipse/che-operator/pull/560
  - [x]  https://github.com/eclipse/che/pull/18601
- [x] .Please provide more flexibility at installation time https://github.com/eclipse/che/issues/18018
  - [x] https://github.com/eclipse/che-docs/pull/1719
- [x] travis-ci and chectl https://github.com/eclipse/che/issues/18260
  - [x] https://github.com/che-incubator/chectl/pull/1033
- [ ] Add e2e tests for chectl olm installer in Openshift 4.6 and OCP nightly https://github.com/eclipse/che/issues/18293 
  - [x] https://github.com/openshift/release/pull/13775
  - [x] https://github.com/openshift/release/pull/14073
  - [x] https://github.com/eclipse/che-operator/pull/564/
- [ ] create workspace failed when customize the hostname https://github.com/eclipse/che/issues/18344
---
### PR to merge
- [x] .Update che-operator dependencies https://github.com/che-incubator/chectl/pull/1023
- [x] .Replace postgres image https://github.com/eclipse/che-operator/pull/569
---
### Unplanned
- [x] Use test operator image in the CSV. https://github.com/eclipse/che-operator/pull/594
- [x] [chectl] chectl/0.0.20201221-next.06243fa failed to update eclipse-che CR on minikube https://github.com/eclipse/che/issues/18682
  - [x] https://github.com/eclipse/che-operator/pull/590
- [x] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference) https://github.com/eclipse/che/issues/18474 
  - [x] https://github.com/eclipse/che-operator/pull/587#event-4129508271
- [x] Helm installer is broken https://github.com/eclipse/che/issues/18648
  - [x] https://github.com/eclipse/che/pull/18651
  - [x] https://github.com/eclipse/che/pull/18652
- [x] [docs] OpenShift 3 quickstart instructions for having multiple deployments doesn't do anything https://github.com/eclipse/che/issues/17689
  - [x] https://github.com/eclipse/che-docs/pull/1744
- [x] Fix GitHub PR plugin https://github.com/eclipse/che-theia/pull/953
- [x] .Che dashboard workspace is not loading on the UI https://github.com/eclipse/che/issues/18499
  - [x] Add missing internal API urls https://github.com/eclipse/che/pull/18574
  - [x] Update dependency https://github.com/che-incubator/chectl/pull/1025 
---
 [Previous Sprint](https://github.com/eclipse/che/issues/18375)
