### ISSUE TITLE
Editors Sprint 194/195

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18568]
Sprint 194: Dec 9 - Dec 29
Sprint 195: Dec 30 - Jan 19

---
- [x] Profile Che-Theia to determine the correct `memory`/`cpu` resources https://github.com/eclipse/che/issues/18565
- [ ] Panels are collapsed in Che-Theia, after refreshing the page https://github.com/eclipse/che/issues/18564
- [ ] Investigate if we can avoid using ServiceWorker in Che-Theia https://github.com/eclipse/che/issues/18566
- [ ] Move Che Theia nightly/main builds from ci.centos.org to GitHub Actions https://github.com/eclipse/che/issues/18407

#### Theia Plug-in APIs
- [ ] Support `workbench.action.files.openFileFolder` built-in command https://github.com/eclipse-theia/theia/issues/8750

---
#### 1. Webview Plug-in API for remote Plug-ins
- [x] Che Theia Web View doesn't work properly when a plugin is running in its own sidecar https://github.com/eclipse/che/issues/16870
- [x] Implement simple file system provider to fetch files from containerized plugin https://github.com/eclipse/che/issues/18405
##### PRs to merge:
- [x] https://github.com/eclipse-theia/theia/pull/8832
- [x] https://github.com/eclipse-theia/theia/pull/8833
- [x] https://github.com/eclipse/che-theia/pull/946
- [x] https://github.com/eclipse/che-theia/pull/947

#### 2. Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212
- [ ] Change config storage paths from /home/theia/home/theia to the corresponding paths https://github.com/eclipse/che/issues/18548
##### PRs to merge:
- [ ] https://github.com/eclipse/che-theia/pull/778

#### 3. Adaptation to Che single-host mode
- [x] Adapt telemetry functionality in Che Theia to single-host https://github.com/eclipse/che/issues/18503
##### PRs to merge:
- [x] https://github.com/eclipse/che-theia/pull/945

#### 4. CRW docs update
- [x] How to integrate other web-based IDEs (on the example of IntelliJ Che Editor) [RHDEVDOCS#2161](https://issues.redhat.com/browse/RHDEVDOCS-2161)
##### PRs to merge:
- [x] https://github.com/eclipse/che-docs/pull/1683
- [x] https://github.com/eclipse/che-docs/pull/1758

---
### Unplanned/Blockers
- [x] Adapt Che-Theia to uptream changes https://github.com/eclipse/che/issues/18618
- [ ] crw-theia compilation failure [CRW#1499](https://issues.redhat.com/browse/CRW-1499)
---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 13  | 8
| Roman   | 11  | 7
| Artem | 14  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/18403)
