### ISSUE TITLE
Code coverage status of Che repositories

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#18621]
## What
Different repositories are in different shape as per testing (unit tests mostly) goes. The problem is, that even though some of the owners/contributors of some of the repositories might know the state, it's generally not easy to obtain this information. And for some repositories this information does not exist at all. Goal of this issue is to analyze current status of testing & code coverage in all the repositories, that makes Che.

We are aware, that code coverage is "just a number" and that components with low coverage could be in good shape as well as components with great coverage could be in bad shape.

The goal of this issue is not to make a sudden strong push for every component to have very high coverage. It's more to analyze current status and create action items, if this analysis shows it's required.

## How
We would like to do this in steps:
1. Every team will make sure that code coverage analysis is in place in all their repos and will post current code coverage levels in here for initial analysis (to decide, whether further investment is needed here - will be decided on case-by-case basis)
    -  If code coverage analysis does not make sense for some repos, that's valid output of this step as well.
2. Teams will create automation, that will report current code coverage percentage.
    - As different repos are written in different languages and will most probably be using different tools for reporting this, we need to agree on single way of reporting this number, so it could then be scraped automatically monitored. First proposed solution was to use https://shields.io/category/coverage and place the badge into root Readme.md of the repo. (if anybody have a better idea, feel free to propose it)
3. We (most probably QE) will create dashboard which will be scraping data provided by step 2. and monitor trends.

## Step 1 tracking
Please update with current code coverage percentage. I understand that for quite some repositories it wouldn't make even sense to report any number. In such cases please fill `not-applicable`, preferably with short description why. This list of repositories was automatically generated using https://raw.githubusercontent.com/eclipse/che/master/.repositories.yaml
- [x] [che server](https://github.com/eclipse/che) - https://github.com/eclipse/che/issues/18507 current 53,5%
- [x] [che-theia](https://github.com/eclipse/che-theia) - current 30%
- [x] [chectl](https://github.com/che-incubator/chectl) - current 9.65%
- [ ] [dashboard](https://github.com/eclipse/che-dashboard) - current ??%
- [ ] [devfile-registry](https://github.com/eclipse/che-devfile-registry) - current ??%
- [ ] [docs](https://github.com/eclipse/che-docs) - current ??%
- [x] [machine-exec](https://github.com/eclipse/che-machine-exec) - current 95.9%
- [x] [operator](https://github.com/eclipse/che-operator) - current 23.3%
- [x] [plugin-broker](https://github.com/eclipse/che-plugin-broker) - current 66.7%
- [x] [plugin-registry](https://github.com/eclipse/che-plugin-registry) - current 91%
- [ ] [website](https://github.com/eclipse/che-website) - current ??%
- [ ] [workspace-client](https://github.com/eclipse/che-workspace-client) - current ??%
- [ ] ~~[workspace-loader](https://github.com/eclipse/che-workspace-loader)~~ is going to be deprecated soon
- [ ] [che-sidecar-bazel](https://github.com/che-dockerfiles/che-sidecar-bazel) - current ??%
- [ ] [che-sidecar-protobuf](https://github.com/che-dockerfiles/che-sidecar-protobuf) - current ??%
- [ ] [che-sidecar-tekton](https://github.com/che-dockerfiles/che-sidecar-tekton) - current ??%
- [ ] [che-sidecar-kubernetes-tooling](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling) - current ??%
- [ ] [che-sidecar-openshift-connector](https://github.com/che-dockerfiles/che-sidecar-openshift-connector) - current ??%
- [ ] [che-container-tools](https://github.com/che-dockerfiles/che-container-tools) - current ??%
- [ ] [che-sidecar-python](https://github.com/che-dockerfiles/che-sidecar-python) - current ??%
- [ ] [che-custom-nodejs-deasync](https://github.com/che-dockerfiles/che-custom-nodejs-deasync) - current ??%
- [ ] [che-sidecar-go](https://github.com/che-dockerfiles/che-sidecar-go) - current ??%
- [ ] [che-sidecar-sonarlint](https://github.com/che-dockerfiles/che-sidecar-sonarlint) - current ??%
- [ ] [che-sidecar-dotnet](https://github.com/che-dockerfiles/che-sidecar-dotnet) - current ??%
- [ ] [che-sidecar-shellcheck](https://github.com/che-dockerfiles/che-sidecar-shellcheck) - current ??%
- [ ] [che-sidecar-camelk](https://github.com/che-dockerfiles/che-sidecar-camelk) - current ??%
- [ ] [che-sidecar-vale](https://github.com/che-dockerfiles/che-sidecar-vale) - current ??%
- [ ] [che-cert-manager-ca-cert-generator-image](https://github.com/che-dockerfiles/che-cert-manager-ca-cert-generator-image) - current ??%
- [ ] [che-buildkit-base](https://github.com/che-dockerfiles/che-buildkit-base) - current ??%
- [ ] [che-sidecar-scala](https://github.com/che-dockerfiles/che-sidecar-scala) - current ??%
- [ ] [che-buildah-base](https://github.com/che-dockerfiles/che-buildah-base) - current ??%
- [ ] [che-docker-registry-image-copier](https://github.com/che-dockerfiles/che-docker-registry-image-copier) - current ??%
- [ ] [che-php-base](https://github.com/che-dockerfiles/che-php-base) - current ??%
- [ ] [che-tls-secret-creator](https://github.com/che-dockerfiles/che-tls-secret-creator) - current ??%
- [ ] [build-action](https://github.com/che-dockerfiles/build-action) - current ??%
- [ ] [che-sidecar-podman](https://github.com/che-dockerfiles/che-sidecar-podman) - current ??%
- [ ] [che-sidecar-clang](https://github.com/che-dockerfiles/che-sidecar-clang) - current ??%
- [ ] [che-sidecar-php](https://github.com/che-dockerfiles/che-sidecar-php) - current ??%
- [ ] [che-sidecar-java](https://github.com/che-dockerfiles/che-sidecar-java) - current ??%
- [ ] [che-sidecar-dependency-analytics](https://github.com/che-dockerfiles/che-sidecar-dependency-analytics) - current ??%
- [ ] [che-sidecar-node](https://github.com/che-dockerfiles/che-sidecar-node) - current ??%
- [ ] [che-dashboard-next](https://github.com/che-incubator/che-dashboard-next) - current ??%
- [ ] [che-theia-openshift-auth](https://github.com/che-incubator/che-theia-openshift-auth) - current ??%
- [ ] [configbump](https://github.com/che-incubator/configbump) - current ??%
- [ ] [workspace-data-sync](https://github.com/che-incubator/workspace-data-sync) - current ??%
- [ ] [che-workspace-telemetry-client](https://github.com/che-incubator/che-workspace-telemetry-client) - current ??%
- [ ] [kubernetes-image-puller](https://github.com/che-incubator/kubernetes-image-puller) - current ??%

## Step 2 tracking
Here plese check the checkbox, when you have automated reporting of current state done according to description of step 2. If you'll track this work as an issue, please link the issue here.
- [ ] [che](https://github.com/eclipse/che)
- [x] [che-theia](https://github.com/eclipse/che-theia) - https://github.com/eclipse/che/issues/18844
- [x] [chectl](https://github.com/che-incubator/chectl) https://github.com/eclipse/che/issues/18626
- [ ] [dashboard](https://github.com/eclipse/che-dashboard)
- [ ] [devfile-registry](https://github.com/eclipse/che-devfile-registry)
- [ ] [docs](https://github.com/eclipse/che-docs)
- [x] [machine-exec](https://github.com/eclipse/che-machine-exec) https://github.com/eclipse/che/issues/18626
- [x] [operator](https://github.com/eclipse/che-operator) https://github.com/eclipse/che/issues/18626
- [x] [plugin-broker](https://github.com/eclipse/che-plugin-broker)
- [x] [plugin-registry](https://github.com/eclipse/che-plugin-registry)
- [ ] [website](https://github.com/eclipse/che-website)
- [ ] [workspace-client](https://github.com/eclipse/che-workspace-client)
- [ ] ~~[workspace-loader](https://github.com/eclipse/che-workspace-loader)~~ is going to be deprecated soon
- [ ] [che-sidecar-bazel](https://github.com/che-dockerfiles/che-sidecar-bazel)
- [ ] [che-sidecar-protobuf](https://github.com/che-dockerfiles/che-sidecar-protobuf)
- [ ] [che-sidecar-tekton](https://github.com/che-dockerfiles/che-sidecar-tekton)
- [ ] [che-sidecar-kubernetes-tooling](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling)
- [ ] [che-sidecar-openshift-connector](https://github.com/che-dockerfiles/che-sidecar-openshift-connector)
- [ ] [che-container-tools](https://github.com/che-dockerfiles/che-container-tools)
- [ ] [che-sidecar-python](https://github.com/che-dockerfiles/che-sidecar-python)
- [ ] [che-custom-nodejs-deasync](https://github.com/che-dockerfiles/che-custom-nodejs-deasync)
- [ ] [che-sidecar-go](https://github.com/che-dockerfiles/che-sidecar-go)
- [ ] [che-sidecar-sonarlint](https://github.com/che-dockerfiles/che-sidecar-sonarlint)
- [ ] [che-sidecar-dotnet](https://github.com/che-dockerfiles/che-sidecar-dotnet)
- [ ] [che-sidecar-shellcheck](https://github.com/che-dockerfiles/che-sidecar-shellcheck)
- [ ] [che-sidecar-camelk](https://github.com/che-dockerfiles/che-sidecar-camelk)
- [ ] [che-sidecar-vale](https://github.com/che-dockerfiles/che-sidecar-vale)
- [ ] [che-cert-manager-ca-cert-generator-image](https://github.com/che-dockerfiles/che-cert-manager-ca-cert-generator-image)
- [ ] [che-buildkit-base](https://github.com/che-dockerfiles/che-buildkit-base)
- [ ] [che-sidecar-scala](https://github.com/che-dockerfiles/che-sidecar-scala)
- [ ] [che-buildah-base](https://github.com/che-dockerfiles/che-buildah-base)
- [ ] [che-docker-registry-image-copier](https://github.com/che-dockerfiles/che-docker-registry-image-copier)
- [ ] [che-php-base](https://github.com/che-dockerfiles/che-php-base)
- [ ] [che-tls-secret-creator](https://github.com/che-dockerfiles/che-tls-secret-creator)
- [ ] [build-action](https://github.com/che-dockerfiles/build-action)
- [ ] [che-sidecar-podman](https://github.com/che-dockerfiles/che-sidecar-podman)
- [ ] [che-sidecar-clang](https://github.com/che-dockerfiles/che-sidecar-clang)
- [ ] [che-sidecar-php](https://github.com/che-dockerfiles/che-sidecar-php)
- [ ] [che-sidecar-java](https://github.com/che-dockerfiles/che-sidecar-java)
- [ ] [che-sidecar-dependency-analytics](https://github.com/che-dockerfiles/che-sidecar-dependency-analytics)
- [ ] [che-sidecar-node](https://github.com/che-dockerfiles/che-sidecar-node)
- [ ] [che-dashboard-next](https://github.com/che-incubator/che-dashboard-next)
- [ ] [che-theia-openshift-auth](https://github.com/che-incubator/che-theia-openshift-auth)
- [ ] [configbump](https://github.com/che-incubator/configbump)
- [ ] [workspace-data-sync](https://github.com/che-incubator/workspace-data-sync)
- [ ] [che-workspace-telemetry-client](https://github.com/che-incubator/che-workspace-telemetry-client)
- [ ] [kubernetes-image-puller](https://github.com/che-incubator/kubernetes-image-puller)

**Comment by azatsarynnyy** [comment]
I'm setting P2. Feel free to reprioritize it if needed.

**Comment by ericwill** [comment]
>     * [ ]  [che-sidecar-bazel](https://github.com/che-dockerfiles/che-sidecar-bazel)
> 
>     * [ ]  [che-sidecar-protobuf](https://github.com/che-dockerfiles/che-sidecar-protobuf)
> 
>     * [ ]  [che-sidecar-tekton](https://github.com/che-dockerfiles/che-sidecar-tekton)
> 
>     * [ ]  [che-sidecar-kubernetes-tooling](https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling)
> 
>     * [ ]  [che-sidecar-openshift-connector](https://github.com/che-dockerfiles/che-sidecar-openshift-connector)
> 
>     * [ ]  [che-sidecar-python](https://github.com/che-dockerfiles/che-sidecar-python)
> 
>     * [ ]  [che-sidecar-go](https://github.com/che-dockerfiles/che-sidecar-go)
> 
>     * [ ]  [che-sidecar-sonarlint](https://github.com/che-dockerfiles/che-sidecar-sonarlint)
> 
>     * [ ]  [che-sidecar-dotnet](https://github.com/che-dockerfiles/che-sidecar-dotnet)
> 
>     * [ ]  [che-sidecar-shellcheck](https://github.com/che-dockerfiles/che-sidecar-shellcheck)
> 
>     * [ ]  [che-sidecar-camelk](https://github.com/che-dockerfiles/che-sidecar-camelk)
> 
>     * [ ]  [che-sidecar-vale](https://github.com/che-dockerfiles/che-sidecar-vale)
> 
>     * [ ]  [che-buildkit-base](https://github.com/che-dockerfiles/che-buildkit-base)
> 
>     * [ ]  [che-sidecar-scala](https://github.com/che-dockerfiles/che-sidecar-scala)
> 
>     * [ ]  [che-buildah-base](https://github.com/che-dockerfiles/che-buildah-base)
>
>     * [ ]  [che-sidecar-podman](https://github.com/che-dockerfiles/che-sidecar-podman)
> 
>     * [ ]  [che-sidecar-clang](https://github.com/che-dockerfiles/che-sidecar-clang)
> 
>     * [ ]  [che-sidecar-php](https://github.com/che-dockerfiles/che-sidecar-php)
> 
>     * [ ]  [che-sidecar-java](https://github.com/che-dockerfiles/che-sidecar-java)
> 
>     * [ ]  [che-sidecar-dependency-analytics](https://github.com/che-dockerfiles/che-sidecar-dependency-analytics)
> 
>     * [ ]  [che-sidecar-node](https://github.com/che-dockerfiles/che-sidecar-node)

These are all part of the plugin registry now, they don't need to be listed here.


>     * [ ]  [devfile-registry](https://github.com/eclipse/che-devfile-registry)

This repo doesn't have any unit tests as it's mostly bash scripts and Dockerfiles.
