### ISSUE TITLE
Consuming Devfiles at the root of a git repository should be our first use case

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18666]
### Is your enhancement related to a problem? Please describe.

Starting a workspace using a factory link and with a devfile at the root of the repository is the most used scenario but is not the main supported and tested one. The main supported and tested is the scenario where the devfile is published out of the git repository, in the devfile registry for example. 

### Describe the solution you'd like

- [ ] Add v2 devfiles in the samples git repositories (whenever possible) #19341
- [ ] The devfile registry should only be a registry of parent devfiles
- [ ] Update the happy path tests to use a devfile within a repository
- [ ] Improve UX of common scenarios:
  - [ ] Password protected git repositories
  - [ ] Prompt user if git remotes (fork) and branch in devfile project do not match the factory link

### Additional context

This work should be included in the context of [che workspaces that use the DevWorkspace operator](https://github.com/eclipse/che/issues/17307), so that's not for v1 devfiles.

**Comment by l0rd** [comment]
Closing as this is already tracked in https://github.com/eclipse/che/issues/19341
