### ISSUE TITLE
Che Controller Sprint 195

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18706]
## Dashboard 
N/A

## Dashboard Next
- [ ] Dashboard next does not need its own loader https://github.com/eclipse/che/issues/18734
- [x] Workspaces list #16646
- [ ] Prototype Container Registries on the Dashboard Next https://github.com/eclipse/che/issues/18526
- [x] It's not possible to refresh Keycloak token https://github.com/eclipse/che/issues/18311
- [x] Adapt documentation to Dashboard Next https://github.com/eclipse/che/issues/18518
- [x] Dashboard Next should propose user to restart a workspace in debug mode if it's failed https://github.com/eclipse/che/issues/18640
- [x] Move che-dashboard-next into eclipse organization https://github.com/eclipse/che/issues/17655
- [x] Promote Dashboard Next https://github.com/eclipse/che/issues/18348
- [ ] Dashboard next should propagate override parameters to factory https://github.com/eclipse/che/issues/18708
- [x] Dashboard Next landing page should depend on the number of workspaces https://github.com/eclipse/che/issues/18609
- [ ] Show warning banner when websockets are not available https://github.com/eclipse/che/issues/18490

## DevWorkspace
- [ ] Implement Volume component https://github.com/devfile/devworkspace-operator/issues/185

## WTO
N/A
