### ISSUE TITLE
Milestone Summary 4.6.0

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#1870]
## Milestone Overview
- [x] New docker image launcher for Che [#1683]
- [x] New lighter image for Che based upon alpine [#1682]

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **July 29**
- GitHub release complete (QA verified) milestone: **August 2**
- Eclipse signed release complete (IP verified) milestone: **target August 3**
- Release shipped milestone: **target August 11**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
- [x] Release review information sent to Eclipse PMC (only if release will be shipped)
- [x] IP logs and information sent to Eclipse Foundation (only if release will be shipped)
- [x] Contribution questionnaires (CQ) approved for all new libraries (only if release will be shipped)
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release note blog / email completed
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live
#### Eclipse signed release complete (IP verified) milestone
- [x] Release signed by Eclipse Foundation
- [x] Release information updated on Eclipse.org
- [x] Release uploaded to Eclipse.org servers
- [x] Release updated on Bitnami
- [x] Release updated on codenvy.com (Eclipse Che free cloud offering)
- [x] Public Factories on codenvy.com QA'ed
#### Release shipped milestone
- [x] Release blog live on che.eclipse.org
- [x] Marketing email / social notifications
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Epics and Issues
- [x] Add docker image to grab the ip used by docker: https://github.com/eclipse/che/pull/1891
- [x] che-launcher infer Che version and self destruct itself: https://github.com/eclipse/che/pull/1881
- [x] CHE-1535: Reveal resources after move and copy operation: https://github.com/eclipse/che/pull/1877
- [x] Add new parameters to build docker image method: https://github.com/eclipse/che/pull/1872
- [x] Fix new alpine based Dockerfile for Boot2Docker: https://github.com/eclipse/che/pull/1723
- [x] Use a docker launcher image to simplify start/stop/update/restart commands: https://github.com/eclipse/che/pull/1683
- [x] Save machine config with 'dev' instead of 'isDev' field: https://github.com/eclipse/che/pull/1679
- [x] CHE-1248 remove workspace information from EnvironmentContext: https://github.com/eclipse/che/pull/1658
- [x] Update according to changes in everrest: https://github.com/eclipse/che/pull/1625
- [x] Add instructions in new Che launcher how to get Che server logs: https://github.com/eclipse/che/issues/1951
- [x] Automatically open the IDE after creating a project: https://github.com/eclipse/che/pull/1863
- [x] Parameterized Vagrantfile: Make Virtualbox Machine name configurable: https://github.com/eclipse/che/issues/1965
- [x] [Dashboard] fix bug in project template selection: https://github.com/eclipse/che/pull/1737
- [x] Add CI mechanisms for new Che Docker images: https://github.com/eclipse/che/issues/1842
- [x] Release and ship Che 4.6.0 #2012
#### Bugs
- [x]  Stop of Che container in new Che launcher is broken: https://github.com/eclipse/che/issues/1949
- [x] Launcher: fixed Path problems, splitted in 3 files and added tests: https://github.com/eclipse/che/pull/1898
- [x] IDE resources caching from UD is broken: https://github.com/eclipse/che/issues/1909
- [x] [Chefile] Allow to continue to start the script even if there is a chown failure: https://github.com/eclipse/che/pull/1917
- [x] Cannot export a workspace from the Dashboard: https://github.com/eclipse/che/issues/1903
- [x] Copy and paste not working in the terminal: https://github.com/eclipse/che/issues/1899
- [x] Cloning a VSTS repo feature does not work: https://github.com/eclipse/che/issues/1893
- [x] Wrong behavior after configure folder with name 'java' as source: https://github.com/eclipse/che/issues/1814
- [x] Launcher: fixed Path problems, splitted in 3 files and added tests: https://github.com/eclipse/che/pull/1914
- [x] Fix the ENV about configuration folder to set when using docker image: https://github.com/eclipse/che/pull/1896
- [x] Downgrade docker installed in Che image: https://github.com/eclipse/che/pull/1833
- [x] Restoring a project state after stopping a workspace does not work: https://github.com/eclipse/che/issues/1919
- [x] Unexpected errors in the browser console after restarting a workspace: https://github.com/eclipse/che/issues/1902
- [x] Opened files list in the editor area does not work properly: https://github.com/eclipse/che/issues/1850
- [x] Change value of "java.output.folder" attribute: https://github.com/eclipse/che/issues/1843
- [x] After closing the Project wizard widget by ESC select path form still opened: https://github.com/eclipse/che/issues/1825
- [x] Delete multi-module projects in some case holding failure: https://github.com/eclipse/che/issues/1819
- [x] Tree of 'changes to be performed' in the refactoring 'Rename' window does not work correctly: https://github.com/eclipse/che/issues/1786
- [x] Preview URL may be lost after refreshing page: https://github.com/eclipse/che/issues/1785
- [x] Remove closed file from the editor's popup list: https://github.com/eclipse/che/pull/1867
- [x] Synchronize project instead of parent directory: https://github.com/eclipse/che/pull/1954
- [x] Che docker launcher incorrectly stops Che server - doesn't respect shut down process. #1949
- [x] Che docker launcher fails if firewalld is activated: https://github.com/eclipse/che/issues/1924
- [x] Not able to run Che as a Docker Container on OSX: https://github.com/eclipse/che/issues/1976
- [x] If use the dashboard for import project from zip archive, the root folder of the archive don't skip: https://github.com/eclipse/che/issues/1852
- [x] Che ignores user response when asks whether it should restore workspace or not: https://github.com/eclipse/che/issues/1849

**Comment by bmicklea** [comment]
Moved to GitHub Wiki:
https://github.com/eclipse/che/wiki/Milestone-4.6.0-Overview

**Comment by bmicklea** [comment]
This release has been delayed due to issues with our CI system. We will be updating the release as soon as the issues are fixed.
