### ISSUE TITLE
Che Deploy Sprint #195

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18700]
#### Timeframe
Dec. 30 - Jan. 19

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays:
- Dec. 28-31 PTO Aleksandr
- Dec. 18-31 PTO Flavius
- Jan. 1 Ukraine/Spain Holiday
- Jan. 6 Spain Holiday
- Jan. 7 Ukraine Holiday
- Jan. 8 Hack 'n' Hustle

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x

---
### CRW issues 
- [ ] Deploying registries in OpenShift - All templates for deployment must be reworked https://issues.redhat.com/browse/RHDEVDOCS-2483
  - [x] https://github.com/eclipse/che-devfile-registry/pull/322
  - [x] https://github.com/eclipse/che-plugin-registry/pull/792
- [x] .Please implement a health endpoint for the CRW Operator https://issues.redhat.com/browse/CRW-683
  - [x] https://github.com/eclipse/che-operator/pull/610
- [x] .Ensure that all deployments created by che-operator have readiness and liveness probes https://issues.redhat.com/browse/CRW-916 
    - [x] https://github.com/eclipse/che-operator/pull/598
- [x] .Please analyse oddities in CRW 2.5 / OCP 3.11 / No OLM install https://issues.redhat.com/browse/CRW-1458
  - [x] https://github.com/eclipse/che-operator/pull/623
- [x] .[chectl] Telemetry: what commands and what k8s targets are people using? https://github.com/eclipse/che/issues/18069
  - [x] https://github.com/che-incubator/chectl/pull/1052
  - [x] https://github.com/eclipse/che-operator/pull/606
  - [x] https://github.com/eclipse/che-operator/pull/611
  - [x] https://github.com/redhat-developer/codeready-workspaces-chectl/pull/52
---
### Eclipse Che issues 
- [ ] [che-operator] - serviceaccount permissions for <username>-che as default namespace https://github.com/eclipse/che/issues/15493
  - [x] https://github.com/eclipse/che-operator/pull/605  
  - [ ] https://github.com/eclipse/che-operator/pull/166
- [ ] Switch to the new Operator Bundle Format https://github.com/eclipse/che/issues/16928
- [ ] [chectl] Deploying Eclipse Che should not depend on a specific version of chectl https://github.com/eclipse/che/issues/18022
- [ ] [che-operator] Provides the ability to create backups https://github.com/eclipse/che/issues/18703
- [x] .Allow Map of configMap to Keycloak Deployment https://github.com/eclipse/che/issues/18607
  - [x] https://github.com/eclipse/che-operator/pull/595
  - [x] https://github.com/eclipse/che-docs/pull/1779
- [x] .chectl: Add new helm installer argument to enable/disable using internal network https://github.com/eclipse/che/issues/18579
  - [x] https://github.com/eclipse/che/pull/18707
  - [x] https://github.com/eclipse/che-docs/pull/1772
- [ ] Make Che Theia work when ca.cert doesn't contain complete certificate chain of trust https://github.com/eclipse/che/issues/17938
- [x] .Automate the setup of github identity provider with internal keycloak https://github.com/eclipse/che/issues/18238
  - [x] https://github.com/eclipse/che-operator/pull/589
  - [x] https://github.com/eclipse/che-docs/pull/1773
- [ ] Create a valid user if no one exist when deploying on OpenShift https://github.com/eclipse/che/issues/18152
  - [ ] https://github.com/eclipse/che-operator/pull/597
- [ ] Container or pods should specify resource limits https://github.com/eclipse/che/issues/18356
  - [ ] https://github.com/eclipse/che-operator/pull/612
- [ ] Define Required Metadata Labels on deployment definitions https://github.com/eclipse/che/issues/18357
  - [ ] https://github.com/eclipse/che-operator/pull/603
  - [ ] https://github.com/eclipse/che/pull/18774/
  - [ ] https://github.com/eclipse/che-plugin-registry/pull/793
  - [ ] https://github.com/eclipse/che-devfile-registry/pull/324
- [x] .Containers must be dropping all capabilities, and only adding the ones they need. https://github.com/eclipse/che/issues/18359
   - [x] https://github.com/eclipse/che-operator/pull/622
- [ ] Pods must define architecture-based node affinity https://github.com/eclipse/che/issues/18361
- [ ] Each pod should declare it's securityContext https://github.com/eclipse/che/issues/18362
- [ ] Add e2e tests for chectl olm installer in Openshift 4.6 and OCP nightly https://github.com/eclipse/che/issues/18293 
  - [x] https://github.com/eclipse/che-operator/pull/604  
- [x] .chectl release tags are not compliant with other repositories https://github.com/eclipse/che/issues/17604
  - [x] https://github.com/che-incubator/chectl/pull/1051
- [ ] We need to cover test case in the e2e tests when che-operator oauth is enabled https://github.com/eclipse/che/issues/17939
  - [ ] https://github.com/eclipse/che-operator/pull/620
- [x] .Create a github action which check chectl README.md automatically https://github.com/eclipse/che/issues/18294
  - [x] https://github.com/che-incubator/chectl/pull/1055
- [x] .Automate code coverage reporting https://github.com/eclipse/che/issues/18626
  - [x] https://github.com/che-incubator/chectl/pull/1063
  - [x] https://github.com/eclipse/che-operator/pull/626
  - [x] https://github.com/eclipse/che-machine-exec/pull/122
---
### Unplanned
- [x] Apply new attribute for {prod-namespace} and clear all old and bad occurrences of the hardcoded versions of this attribute https://issues.redhat.com/browse/RHDEVDOCS-2522
  - [x] https://github.com/eclipse/che-docs/pull/1796
- [x] Authentication flow doesn't work https://github.com/eclipse/che/issues/18791
  - [x] https://github.com/eclipse/che/pull/18815
  - [x] https://github.com/eclipse/che/pull/18819
- [x] .https://issues.redhat.com/browse/CRW-1476 "crwctl server:delete" has different default namespace compare to "crwctl server:deploy" command
  - [x] https://github.com/che-incubator/chectl/pull/1060
  - [x] https://github.com/redhat-developer/codeready-workspaces-chectl/pull/54
- [x] .Improve che-operator tests by starting workspace from a devfile with plugins
https://github.com/eclipse/che/issues/18767
  - [x] https://github.com/che-incubator/chectl/pull/1064
  - [x] https://github.com/eclipse/che-operator/pull/629
- [x] .Add PR template https://github.com/eclipse/che-operator/pull/625
- [x] .Failed to push latest operator image https://github.com/eclipse/che/issues/18768
  - [x] https://github.com/eclipse/che-operator/pull/617
- [x] .test failures building CRW 2.6 operator, synced from Che 7.24.x branch https://github.com/eclipse/che/issues/18766
  - [x] https://github.com/eclipse/che-operator/pull/621
- [x] .Fix devfile https://github.com/che-incubator/chectl/pull/1058
- [x] .Fix devfile https://github.com/eclipse/che-operator/pull/616
- [x] .Fix devfile https://github.com/eclipse/che-machine-exec/pull/121
- [x] .[chectl]- Not able to to deploy Eclipse Che using operator installer https://github.com/eclipse/che/issues/18754
  - [x] https://github.com/che-incubator/chectl/pull/1056
- [x] .Fix typo in keycloak deployment https://github.com/che-incubator/chectl/pull/1050 
- [x] .Improve tlsSecretName description https://github.com/eclipse/che-operator/pull/600
- [x] .Remove operator-local.yaml https://github.com/eclipse/che-operator/pull/599
---
 [Previous Sprint](https://github.com/eclipse/che/issues/18542)
