### ISSUE TITLE
Che Platform Sprint 195

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18712]
### Bitbucket Server
 - [x]  Using Bitbucket personal access token as k8s secret during factory resolution | https://github.com/eclipse/che/issues/18386
 - [ ]  Obtain and persist Bitbucket personal access token as k8s secret | https://github.com/eclipse/che/issues/18388
 - [ ] Ensure that userid provided as a parameter to `oauth/1.0/authenticate` is similar to the current userid | https://github.com/eclipse/che/issues/18475

### Multi cluster support
 - [x]  [Spike] Intro in Multi cluster support | https://github.com/eclipse/che/issues/18711

### Support Singlehost deployment in Devworkspaces
 - [x] [devworkspace] Manage Traefik as the devworkspace gateway | https://github.com/eclipse/che/issues/18677

### Bugs/Technical debt
 - [x] Exception when importing devfile with kubernetes component including a Deployment with environment variables referencing secrets | https://github.com/eclipse/che/issues/18508
