### ISSUE TITLE
Che Deploy Sprint #196

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18801]
#### Timeframe
Jan. 20 - Feb.  9

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays / events:
- Jan. 29 Hack 'n' Hustle
- Feb. 5  Day of learning 

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x

---
### CRW issues 
- [ ] Deploying registries in OpenShift - All templates for deployment must be reworked https://issues.redhat.com/browse/RHDEVDOCS-2483
  - [ ] https://github.com/eclipse/che/pull/18774/
  - [ ] https://github.com/eclipse/che-plugin-registry/pull/793
  - [ ] https://github.com/eclipse/che-devfile-registry/pull/324
- [ ] IG - CheCluster Custom Resource documentation missing server. workspaceNamespaceDefault attribute https://issues.redhat.com/browse/RHDEVDOCS-2216
  - [ ] https://github.com/eclipse/che-docs/pull/1803
  - [x] https://github.com/eclipse/che-operator/pull/651
- [ ] Add procedure how to log in into Identity Provider https://issues.redhat.com/browse/RHDEVDOCS-2471
- [ ] Installation with router sharding not working https://issues.redhat.com/browse/CRW-1466
---
### Eclipse Che issues 
- [x] .[che-operator] - serviceaccount permissions for <username>-che as default namespace https://github.com/eclipse/che/issues/15493
  - [x] https://github.com/eclipse/che-operator/pull/166
  - [x] https://github.com/che-incubator/chectl/pull/1087
  - [ ] https://github.com/redhat-developer/codeready-workspaces-operator/pull/42
- [ ] Create a valid user if no one exist when deploying on OpenShift https://github.com/eclipse/che/issues/18152
  - [ ] https://github.com/eclipse/che-operator/pull/597
- [ ] Improve Eclipse Che deploy / update flow https://github.com/eclipse/che/issues/18022
  - [ ] https://github.com/che-incubator/chectl/pull/1082
- [ ] Switch to the new Operator Bundle Format https://github.com/eclipse/che/issues/16928
- [ ] [che-operator] Provides the ability to create backups https://github.com/eclipse/che/issues/18703
- [ ] chectl with workspace-engine=dev-workspace doesn't work https://github.com/eclipse/che/issues/18842
- [x] .Container or pods should specify resource limits https://github.com/eclipse/che/issues/18356
  - [x] https://github.com/eclipse/che-operator/pull/612
- [x] .Define Required Metadata Labels on deployment definitions https://github.com/eclipse/che/issues/18357
  - [x] https://github.com/eclipse/che-operator/pull/603
 - [ ] chectl auth:login fails without correct kubecontext https://github.com/eclipse/che/issues/18684
   - [ ] https://github.com/che-incubator/chectl/pull/1085/files
- [ ] Add e2e tests for chectl olm installer in Openshift 4.6 and OCP nightly https://github.com/eclipse/che/issues/18293 
- [x] .che operator nightly bundle check fails for release pr's https://github.com/eclipse/che/issues/18644
  - [x] https://github.com/eclipse/che-operator/pull/639/
- [x] .Build stable version of Eclipse Che operator on different platforms https://github.com/eclipse/che/issues/18809
  - [x] https://github.com/eclipse/che-operator/pull/634 
- [x] .Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim https://github.com/eclipse/che/issues/18276
  - [x] https://github.com/che-incubator/chectl/pull/1072/
- [ ] We need to cover test case in the e2e tests when che-operator oauth is enabled https://github.com/eclipse/che/issues/17939
---
### Unplanned
- [x] .CodeReady Workspaces cannot be installed with default settings in proxied environment by operatorhub in Openshift 4.6 https://issues.redhat.com/browse/CRW-1565
  - [x] https://github.com/eclipse/che-operator/pull/659
- [x] .How do I deploy Che to docker-desktop's Kubernetes? https://github.com/eclipse/che/issues/18913
  - [x] https://github.com/che-incubator/chectl/pull/1077
- [x] .CRW 2.6 cannot be installed with external SSO https://issues.redhat.com/browse/CRW-1532
  - [x] https://github.com/eclipse/che-operator/pull/650
  - [x] https://github.com/eclipse/che-operator/pull/652
- [x] .CodeReady cannot be installed with default settings in proxied/disconnected environment https://issues.redhat.com/browse/CRW-1520
  - [x] https://github.com/eclipse/che-operator/pull/646
  - [x] https://github.com/eclipse/che-operator/pull/649
- [x] .rh-sso pod terminated while importing ceritificates https://issues.redhat.com/browse/CRW-1523
  - [x] https://github.com/eclipse/che-operator/pull/647
  - [x] https://github.com/eclipse/che-operator/pull/648
- [x] .Installation CRW 2.6 using 'crwctl' (olm-installer) is failed via error of pulling 'codeready-operator' https://issues.redhat.com/browse/CRW-1512
  - [x] https://github.com/che-incubator/chectl/pull/1074
  - [x] https://github.com/che-incubator/chectl/pull/1073
- [x] .Add happy path tests for release branches https://github.com/che-incubator/chectl/pull/1069
- [x] .Change telemetry command line message https://github.com/che-incubator/chectl/pull/1067
- [x] .chectl/0.0.20210115-next.dc032a1 failed to start nightly Eclipse Che on minikube by timeout when deploy Keycloak  https://github.com/eclipse/che/issues/18828
  - [x] https://github.com/eclipse/che-operator/pull/635
---
 [Previous Sprint](https://github.com/eclipse/che/issues/18700)
