### ISSUE TITLE
Plugins Sprint 196

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18808]
## Sprint 196 (January 20th 2021 - Feburary 9th 2021)
This sprint will result in the release of Che 7.26.

### Epics
* Allow Che 7 Git + SSH Flow #13494 
    * [ ] Check for credentials (SSH) before trying to clone git repositories: https://github.com/eclipse/che/issues/13494#issuecomment-694387267 @vitaliy-guliy 

### CRW
* [ ] VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) @tsmaeder 
    * [ ] Java code snippets 'try_catch' and 'main' are not working #16502
    * [ ] Snippets don't work when Plugin Host is not colocated with Back End eclipse-theia/theia#8460
* [ ] Update the typescript plugin to the latest version [CRW-1434](https://issues.redhat.com/browse/CRW-1434) @tsmaeder 
* [x] remove unneeded node / update to node 12 in sidecars [CRW-1421](https://issues.redhat.com/browse/CRW-1421) @svor 

### Bugs
* [ ] Clean log output from Resources Monitor Plugin #18841 @svor 
* [x] Add resource limits/requests to the devfiles and plugins in the registries #16685 @vitaliy-guliy 
    * Investigate limits/requests for the devfile registry
* [x] Missing options in source control: git #18742 @vinokurig 
* [x] Github PR plugin: restarting a workspace is asking again to sign in #18782 @vinokurig 
* [ ] Syntax highlighting behaving strangely in several Java devfiles #18448 @svor 
* [x] Python-Simple devfile is still using python 3.7 #18794 @ericwill 
* [ ] Using GIT plugin generates an error on the console eclipse-theia/theia#7953 @vinokurig 
* [x] problems with Java tests runner. #18119 @sunix 
* [x] Allow to build custom registries using OpenShift Build #18798 @ericwill 
    * Investigate using buildah to build the registries instead of docker
* [ ] github pr plugin: fork creation is hanging when creating a pull request #18664 @vinokurig 

### Docs
* [ ] Impact of new plugin model on the documentation #18793 @ericwill 
* [ ] Errors in the custom registry build documentation [RHDEVDOCS-2513](https://issues.redhat.com/browse/RHDEVDOCS-2513) @ericwill 
* [x] Document plugin registry publishing on surge in CONTRIBUTE.md #18731 @ericwill 

### Unplanned
* [x] Che-theia image build is broken #18960
* [x] Check if the GitHub oAuth is available when asking to sign in the Pull Requests plugin #18237

### Open PRs From Last Sprint
* [ ] Refactor RPCProtocol eclipse-theia/theia#8972

#### Automation / Tests
* [ ] Ability to run tests of a vscode extension on top of che-theia #18219 @svor 
* [x] Add PR check to ensure sidecar executable files are have correct permissions #18737 @ericwill 
* [x] Ensure plug-in registry has valid data when building image #18747 @sunix 
* [x] Re-work old vscode-extensions.json PR checks to use che-theia-plugins.yaml #18729 @ericwill 
* [ ] A single dogfooding devfile for che-theia #18763 @sunix 

#### Maintenance
* [x] Code coverage status of Che repositories #18621 @sunix 
    * [x] Provide a code coverage report for the devfile and plugin registries #18851
* [ ] Please produce a plugin for Mermaid #18750 @vitaliy-guliy 
* Plugin Updates
    * [ ] Update netcoredbg plugin #18462 @svor 
    * [ ] Update sonarlint-vscode to 1.17.0 eclipse/che-plugin-registry#609 @sunix 
* [x] Rework che-theia build process to not use source linking #16852 @tsmaeder 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 15  | 9 |
| @vinokurig  | 15  | 9 |
| @ericwill | 15 | 9 |
| @tsmaeder | 15 | 9 |
| @svor | 15 | 9 |
| @sunix | 15 | 9 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Allow to build custom registries using OpenShift Build #18798 |
| 2 | Re-work old vscode-extensions.json PR checks to use che-theia-plugins.yaml |
| 3  | Add PR check to ensure sidecar executable files are have correct permissions #18737  |
| 4 | Errors in the custom registry build documentation [RHDEVDOCS-2513](https://issues.redhat.com/browse/RHDEVDOCS-2513) |
| 5 | Upstream docs |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) |
| 2 | Update the typescript plugin to the latest version [CRW-1434](https://issues.redhat.com/browse/CRW-1434) |
| 3 | Rework che-theia build process to not use source linking #16852 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1  | remove unneeded node / update to node 12 in sidecars CRW-1421 |
| 2  | Syntax highlighting behaving strangely in several Java devfiles #18448 |
| 3 | Ability to run tests of a vscode extension on top of che-theia #18219 |
| 4 | Clean log output from Resources Monitor Plugin #18841 |
| 5 | Update netcoredbg plugin #18462 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Github PR plugin: restarting a workspace is asking again to sign in #18782 |
| 2  | Missing options in source control: git #18742  |
| 3 | github pr plugin: fork creation is hanging when creating a pull request #18664 |
| 4 | Using GIT plugin generates an error on the console eclipse-theia/theia#7953 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Add resource limits/requests to the devfiles and plugins in the registries #16685 |
| 2 | Check for credentials (SSH) before trying to clone git repositories: https://github.com/eclipse/che/issues/13494#issuecomment-694387267 |
| 3 | Please produce a plugin for Mermaid #18750 |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | problems with Java tests runner. #18119 |
| 2 | Ensure plug-in registry has valid data when building image #18747  |
| 3 | Code coverage status of Che repositories #18621 |
| 4 | A single dogfooding devfile for che-theia #18763 |
| 5 | Update sonarlint-vscode to 1.17.0 eclipse/che-plugin-registry#609 |

**Comment by ericwill** [comment]
Superseded by #18987
