### ISSUE TITLE
[Cross-Project Epic] Generate PRs for updating base images in Che images (rhel.Dockerfile or Dockerfile)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#18831]
### Is your enhancement related to a problem? Please describe.

Today, we periodically submit by hand PRs to update base images in Che dockerfiles, eg.,

* https://github.com/eclipse/che-operator/pull/181/files
* https://github.com/eclipse/che-devfile-registry/pull/242/files#diff-d62ecfc7db2707ad7af6609a692e3b0237d5b063661a2fac1dd115b2a63ea1c8R15

### Describe the solution you'd like

Create a GH action that runs weekly in the che-release repo, which will submit PRs against all the eclipse/che* and che-incubator/* repos which contain RHEL- or UBI-based Dockerfiles / rhel.Dockerfiles

Script to run is:

* check out code from repos; foreach repo:
* fetch https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/crw-2.6-rhel-8/product/updateBaseImages.sh
* run script, which if permissions are set correctly should generate a PR

* for some repos, it's possible that this update needs to be applied in other places - not just in Dockerfiles. For example eclipse/che -> che.properties file needs to be kept current too. See https://github.com/eclipse/che/pull/19195/files#diff-deca31b9cca47d5b0356dd75fc0fd0c8cb980f3aa029da27b475bdbb37353eb0L409

* collect the list of PR URLs into an email, and send to prod team for tracking, as they need to be merged ASAP and applied downstream too

### Describe alternatives you've considered

We could also set :latest tag in Dockerfiles' base image references but then we can't know which image was used to build a given version. 

### Additional context

By keeping the upstream images current with the latest CVE fixes, we'll make downstream syncs easier/faster/better.

Also once PRs are merged, they can be used to trigger respins of nightly images so we see if regressions occur between UBI or golang tooling image versions, or when a new version appears (eg., break early when UBI golang image is updated from 1.13 -> 1.14).

**Comment by nickboldt** [comment]
@benoitf mentioned on the Che call today that there's now a https://dependabot.com/docker/ option that we could enable. Unclear if this provides support for dockerfile fragments (eg., in che-theia) and non-standard Dockerfile filenames (eg., apache.Dockerfile, rhel.Dockerfile, ubi.Dockerfile), or would allow us to keep che.properties up to date too.

**Comment by nickboldt** [comment]
```
updater | INFO <job_118922825> Checking if ubi8/go-toolset 1.14.12-17.1618436992 needs updating
  proxy | 2021/05/06 15:45:20 [062] GET https://registry.redhat.io:443/v2/ubi8/go-toolset/tags/list
  proxy | 2021/05/06 15:45:20 [062] 401 https://registry.redhat.io:443/v2/ubi8/go-toolset/tags/list
  proxy | 2021/05/06 15:45:20 [064] GET https://registry.redhat.io:443/auth/realms/rhcc/protocol/redhat-docker-v2/auth?service=docker-registry&scope=repository%3Aubi8%2Fgo-toolset%3Apull
  proxy | 2021/05/06 15:45:20 [064] 401 https://registry.redhat.io:443/auth/realms/rhcc/protocol/redhat-docker-v2/auth?service=docker-registry&scope=repository%3Aubi8%2Fgo-toolset%3Apull
updater | INFO <job_118922825> Handled error whilst updating ubi8/go-toolset: private_source_authentication_failure {:source=>"registry.redhat.io"}
```

-- https://github.com/eclipse-che/che-machine-exec/network/updates/118922825

**Comment by nickboldt** [comment]
After moving from reg.rh.io to reg.access.rh.com via this commit https://github.com/eclipse-che/che-machine-exec/commit/74915c3a2f9aff44fddbd5a36a1f442b76d99e04 on https://github.com/eclipse/che/issues/19593...

```
updater | INFO <job_119029084> Checking if ubi8/go-toolset 1.14.12-17.1618436992 needs updating
  proxy | 2021/05/06 17:01:40 [044] GET https://registry.access.redhat.com:443/v2/ubi8/go-toolset/tags/list
  proxy | 2021/05/06 17:01:41 [044] 302 https://registry.access.redhat.com:443/v2/ubi8/go-toolset/tags/list
  proxy | 2021/05/06 17:01:41 [046] GET https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-go-toolset/tags/list
  proxy | 2021/05/06 17:01:41 [046] 200 https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-go-toolset/tags/list
  proxy | 2021/05/06 17:01:41 [048] HEAD https://registry.access.redhat.com:443/v2/ubi8/go-toolset/manifests/latest
  proxy | 2021/05/06 17:01:41 [048] 302 https://registry.access.redhat.com:443/v2/ubi8/go-toolset/manifests/latest
  proxy | 2021/05/06 17:01:41 [050] HEAD https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-go-toolset/manifests/list/latest
  proxy | 2021/05/06 17:01:41 [050] 200 https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-go-toolset/manifests/list/latest
updater | INFO <job_119029084> Latest version is 1.14.12-17.1618436992
updater | INFO <job_119029084> No update needed for ubi8/go-toolset 1.14.12-17.1618436992
```

So that worked.

On to the rest of the repos!

**Comment by nickboldt** [comment]
Dependabot check for dwo has failed to pull new images. See https://github.com/devfile/devworkspace-operator/network/updates/133666506

```
updater | INFO <job_133666506> Checking if libpod/golang 1.13 needs updating
  proxy | 2021/05/12 06:17:01 [014] GET https://quay.io:443/v2/libpod/golang/tags/list
  proxy | 2021/05/12 06:17:04 [014] 200 https://quay.io:443/v2/libpod/golang/tags/list
updater | INFO <job_133666506> Latest version is 1.13
updater | INFO <job_133666506> No update needed for libpod/golang 1.13
updater | INFO <job_133666506> Checking if devtools/go-toolset-rhel7 1.13.15-4 needs updating
  proxy | 2021/05/12 06:17:04 [016] GET https://registry.access.redhat.com:443/v2/devtools/go-toolset-rhel7/tags/list
  proxy | 2021/05/12 06:17:04 [016] 302 https://registry.access.redhat.com:443/v2/devtools/go-toolset-rhel7/tags/list
  proxy | 2021/05/12 06:17:04 [018] GET https://registry.access.redhat.com:443/webassets/docker/content/dist/rhel/server/7/7Server/multiarch/devtools/1/containers/registry/redhat-devtools-go-toolset-rhel7/tags/list
  proxy | 2021/05/12 06:17:04 [018] 200 https://registry.access.redhat.com:443/webassets/docker/content/dist/rhel/server/7/7Server/multiarch/devtools/1/containers/registry/redhat-devtools-go-toolset-rhel7/tags/list
  proxy | 2021/05/12 06:17:04 [020] HEAD https://registry.access.redhat.com:443/v2/devtools/go-toolset-rhel7/manifests/latest
  proxy | 2021/05/12 06:17:05 [020] 302 https://registry.access.redhat.com:443/v2/devtools/go-toolset-rhel7/manifests/latest
  proxy | 2021/05/12 06:17:05 [022] HEAD https://registry.access.redhat.com:443/webassets/docker/content/dist/rhel/server/7/7Server/multiarch/devtools/1/containers/registry/redhat-devtools-go-toolset-rhel7/manifests/list/latest
  proxy | 2021/05/12 06:17:05 [022] 200 https://registry.access.redhat.com:443/webassets/docker/content/dist/rhel/server/7/7Server/multiarch/devtools/1/containers/registry/redhat-devtools-go-toolset-rhel7/manifests/list/latest
updater | INFO <job_133666506> Latest version is 1.13.15-4
updater | INFO <job_133666506> No update needed for devtools/go-toolset-rhel7 1.13.15-4
updater | INFO <job_133666506> Checking if ubi8-minimal 8.3-298 needs updating
  proxy | 2021/05/12 06:17:05 [024] GET https://registry.access.redhat.com:443/v2/ubi8-minimal/tags/list
  proxy | 2021/05/12 06:17:05 [024] 302 https://registry.access.redhat.com:443/v2/ubi8-minimal/tags/list
  proxy | 2021/05/12 06:17:05 [026] GET https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-minimal/tags/list
  proxy | 2021/05/12 06:17:05 [026] 200 https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-minimal/tags/list
  proxy | 2021/05/12 06:17:05 [028] HEAD https://registry.access.redhat.com:443/v2/ubi8-minimal/manifests/latest
  proxy | 2021/05/12 06:17:05 [028] 302 https://registry.access.redhat.com:443/v2/ubi8-minimal/manifests/latest
  proxy | 2021/05/12 06:17:05 [030] HEAD https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-minimal/manifests/list/latest
  proxy | 2021/05/12 06:17:05 [030] 200 https://registry.access.redhat.com:443/webassets/docker/content/dist/containers/rhel8/multiarch/appstream/containers/redhat-ubi8-minimal/manifests/list/latest
updater | INFO <job_133666506> Latest version is 8.3-298
updater | INFO <job_133666506> No update needed for ubi8-minimal 8.3-298
```

Yet latest images for ubi8-minimal and devtools/go-toolset-rhel7 are 8.3-298.1618432845 and 1.14.12-4.1615820747

**Comment by nickboldt** [comment]
Done:

- [x] che-devfile-registry - https://github.com/eclipse-che/che-devfile-registry/pull/401
 
Projects to enable w/ updateBaseImages script via GH action:

- [ ] [eclipse-che/che-machine-exec](https://github.com/eclipse-che/che-machine-exec/blob/main/.github/dependabot.yml)
- [ ] [eclipse-che/che-dashboard](https://github.com/eclipse-che/che-dashboard/blob/main/.github/dependabot.yml)
- [ ] [devfile/devworkspace-operator](https://github.com/devfile/devworkspace-operator/blob/main/.github/dependabot.yml)
- [ ] eclipse-che/che-operator
- [ ] eclipse-che/che-theia
- [ ] eclipse-che/che-plugin-registry
- [ ] eclipse-che/che-workspace-client (?)
- [ ] eclipse/che (server)
- [ ] eclipse/che-docs (?)
- [ ] eclipse/che-release (?)
- [ ] eclipse/che-jwtproxy
- [ ] eclipse/che-plugin-broker
- [ ] eclipse/che-workspace-loader
- [ ] che-incubator/devworkspace-che-operator

**Comment by mkuznyetsov** [comment]
updated the previous comment with the [new workflow](https://github.com/eclipse-che/che-release/actions/workflows/update-base-images.yml) that handles updates in all project

Also see related open PRs to remove unneeded workflows

**Comment by nickboldt** [comment]
Looks like we have a few more places to run this script:
* https://github.com/che-incubator/configbump/tree/main/build/dockerfiles
* https://github.com/che-incubator/jetbrains-editor-images/blob/main/Dockerfile
* https://github.com/che-dockerfiles/che-backup-server-rest/blob/main/Dockerfile

**Comment by nickboldt** [comment]
jetbrains-editor-images has failed to run the update:
* https://github.com/eclipse-che/che-release/runs/3326759431?check_suite_focus=true [PR for dashboard created and merged]
* https://github.com/eclipse-che/che-release/runs/3333507480?check_suite_focus=true [jetbrains editor check failed - permissions issue?]

**Comment by nickboldt** [comment]
I added the che-incubator bot token to the jetbrains-editor-images repo, but still getting this error trying to update base images:

```
# Checking /home/runner/work/che-release/che-release/Dockerfile ...
+ ubi8-minimal:8.4-208
- ubi8-minimal:8.4-205.1626828526
++ /home/runner/work/che-release/che-release/Dockerfile 
[main 6dafb75] chore: Update from ubi8-minimal:8.4-205.1626828526 to ubi8-minimal:8.4-208
 1 file changed, 2 insertions(+), 2 deletions(-)
Switched to branch 'pr-update-base-images-1629035126'
Already up to date.
remote: Permission to che-incubator/jetbrains-editor-images.git denied to che-incubator-bot.
fatal: unable to access 'https://github.com/che-incubator/jetbrains-editor-images/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```
-- https://github.com/eclipse-che/che-release/runs/3333577462?check_suite_focus=true

I bet the `che-incubator-bot` isn't a committer on the project yet. @benoitf or @azatsarynnyy  can you add it?

**Comment by nickboldt** [comment]
https://github.com/eclipse-che/che-release/runs/3341467350?check_suite_focus=true ran, created PR, and then failed anyway. But at least we're able to generate PRs.
