### ISSUE TITLE
Support devfile v2 factory link

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18846]
### Is your enhancement related to a problem? Please describe.

If a github repository has a devfile.yaml that uses v2 of the devfile spec we are not able to start the workspace.

### Describe the solution you'd like

Support factory link that points to a git repo of petclinic with a devfile 2.0 that has just maven and mysql components (**no che-theia plugins**). Theia and machine exec are implicitly added by Che. Subtasks:

- [x] [Update che-server endpoint that returns devfiles from the GitHub URL to support Devfile 2.0](https://github.com/eclipse/che/issues/18838) **platform team**
  - [x] Analyse if we need to add 2.0 Java model support in che-server -> no
  - [x] Validate the devfile 2.0 syntax (not the content) -> not working now, We need to update justify lib https://github.com/eclipse/che/issues/18901 then it should be as simple as put the schema in https://github.com/eclipse/che/issues/18948
- [x] Transform a Devfile 2.0 in a DevWorkspace CR **controller and platform team**
   - [x] [Review how the che server could return the default namespace of a user (resolve che-\<placeholder\>)](https://github.com/eclipse/che/issues/18839) **platform team**
   - [x] Create the user namespaces where the CR should be created (if it doesn't exist yet) **controller team**
   - [x] Specify the routing class when starting a Che workspace **controller team**
- [x] Add the default ~~ /implicit ~~ (are not supported for milestone 1) Che components to the DevWorkspace CR (theia and machine exec)
   - [x] [che-server] Provide default editor and plugins on REST API  **platform team** https://github.com/eclipse/che/issues/18986
- [x] [Improvements to devfile v2 factory flow support](https://github.com/eclipse/che/issues/19147) https://github.com/eclipse/che/issues/19147
   - [x] Namespace should be created if it does not exist
   - [x] Specify the routing class che
   - [x] Default editors and plugins should be propagated to the DevWorkspace CR namespace, we should not rely on the DevWorkspaceTemplate registry

Bugs:
- [x] DevWorkspaces with Che routing is not started due: ExposedEndpoint.Attributes should handle free-form JSON as values https://github.com/devfile/devworkspace-operator/issues/302

**Comment by sleshchenko** [comment]
It's implemented in someway, there are still some points which needs to be addressed on Dashboard side, and they can be tracked in https://github.com/eclipse/che/issues/19147

**Comment by l0rd** [comment]
I have actually reopened this epic and made it clear that #19147 is a subtask of it. I am doing it because in the milestone we only track issues at the epic level.

**Comment by sleshchenko** [comment]
The last PR is merged on dashboard side, the main workflow should work.
