### ISSUE TITLE
Che Platform Sprint 196

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18840]
### Bitbucket Server

- [ ] Obtain and persist Bitbucket personal access token as k8s secret | https://github.com/eclipse/che/issues/18388
- [ ] Clarify factory resolution process for private Bitbucket repositories | https://github.com/eclipse/che/issues/18389

### Devworkspaces
 - [x]  [Rest API] Support factory link that points to a git repo of petclinic with a devfile 2.0 | eclipse/che#18838
 - [x]   [devworkspace] Implement singlehost workspace routing solver for devworkspaces | eclipse/che#18678
 - [x]   Review how the che server could return the default namespace of a user (resolve che-) , a good candidate would be api/workspace/settings (platform team). | eclipse/che#18839
