### ISSUE TITLE
Editors Sprint 196

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18845]
Jan 20 - Feb 9

---
- [x] Panels are collapsed in Che-Theia, after refreshing the page https://github.com/eclipse/che/issues/18564
- [ ] Che-Theia shows `Offline` mode, mistakenly https://github.com/eclipse/che/issues/18723
- [x] Move Che-Theia nightly/main builds from ci.centos.org to GitHub Actions https://github.com/eclipse/che/issues/18407
- [ ] Investigate if we can avoid using ServiceWorker in Che-Theia https://github.com/eclipse/che/issues/18566
- [ ] Che-Theia code coverage reporting https://github.com/eclipse/che/issues/18844
- [ ] Identify what is missing in Che-Theia for Jupyter support https://github.com/eclipse/che/issues/16818

#### Multi-root Workspaces
- [ ] Multi-root Che Theia Workspaces, by default https://github.com/eclipse/che/issues/17212
- [ ] Change config storage paths from /home/theia/home/theia to the corresponding paths https://github.com/eclipse/che/issues/18548
###### PRs to merge:
- [ ] https://github.com/eclipse/che-theia/pull/778

---
### Unplanned/Blockers
- [x] Upgrade `axios` in Che-Theia (fix the known vulnerability) https://github.com/eclipse/che/issues/18916
- [x] Investigated https://issues.redhat.com/browse/CRW-1552
- [x] Investigated https://issues.redhat.com/browse/CRW-1343
- [x] Investigated the issues with HappyPath tests on Che-Theia
- [x] Fixed the broken Che-Theia built-in plug-ins https://github.com/eclipse/che-theia/pull/975
- [x] Che-Theia's Markdown built-in is failed to start https://github.com/eclipse/che/issues/18954
- [x] Java Maven sample on minikube is not starting https://github.com/eclipse/che/issues/18955

---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 13  | 8
| Roman   | 13  | 8
| Artem | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/18568)
