### ISSUE TITLE
Che Controller Sprint 196

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18869]
This issue collect work item Controller Team plan for Sprint 196 (20 Jan - 9 Feb).

### Finalizing from the prev sprint
- [x] [dashboard-next] show warning banner when websockets are not available https://github.com/eclipse/che/issues/18490
- [x] Dashboard next does not need its own loader https://github.com/eclipse/che/issues/18734
- [x] Prototype Container Registries on the Dashboard Next https://github.com/eclipse/che/issues/18526

### Feature gap
- [x] Implement cheCDN resources prefetching in Dashboard Next https://github.com/eclipse/che/issues/18728
- [x] Dashboard next should propagate override parameters to factory https://github.com/eclipse/che/issues/18708
- [x] Account details https://github.com/eclipse/che/issues/18685

### Requested features/improvements

- [x] Simplify the factory URL link https://github.com/eclipse/che/issues/18165
- [x] As an admin, I would like to have a possibility to add information / warning header to the User Dasboard https://github.com/eclipse/che/issues/18769

### DevWorkspace on Dashboard

- [ ] Begin implementing basic DevWorkspace functionality into new dashboard https://github.com/eclipse/che/issues/18858

### DevWorkspace Operator
- [x] Investigate support for async storage in controller https://github.com/devfile/devworkspace-operator/issues/247
- [x] Implement plugin/parent flattening for DevWorkspaces https://github.com/devfile/devworkspace-operator/issues/249
- [ ] [devfile/api] Extending Volume components to support more features github.com/devfile/api/issues/310
- [x] Begin publishing flattened, ready-to-deploy yaml templates of the controller https://github.com/devfile/devworkspace-operator/issues/250

### Unplanned
- [x] The token is not refreshed when receiving activity event https://github.com/eclipse/che/issues/18946
- [x] Dashboard does not configure credentials to registry which name is not URL like https://github.com/eclipse/che/issues/18959
- [x] Dashboard next deployment is broken, at least on minikube https://github.com/eclipse/che/issues/18964
