### ISSUE TITLE
Updates to the Devfile 2 model to support Che workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18878]
### Is your enhancement related to a problem? Please describe.

There are some features of workspaces that could be specified using a Devfile v1 that it's not possible to specify using Devfile v2 yet. 

### Describe the solution you'd like

- [x] [Support ephemeral](https://github.com/devfile/api/issues/310) **controller team**
```
spec:
  components:
    - name: my-ephemeral-volume 
      volume:
        ephemeral: false # Volume my-ephemeral-volume will be mounted as emptyDir
```
- [x] asynchronous storage **controller team**
- [x] Support secret and configmap injection (to review if we want to support [current injection mechanism](https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/)) **controller team**
  ^ 
  we don't need to have it on devfile model, we're going to implement it in the same way as currently Che does, match secrets and configmaps with their labels/annotations.

**Comment by sleshchenko** [comment]
This issue is just about model changes and it can be closed I believe.
@amisevsk Could you please provide what is the devfile settings for async storage? Is it going to be the same as we used to have on devfile v1 level to switch all persisted volumes to async
```
attributes:
  ephemeral: true
  async: true
```
?

**Comment by amisevsk** [comment]
The current attributes are confusing, since we initially had `ephemeral: true` and so had to add `async: true` on top to keep backward compatibility. Starting over, I think the (probably label, not attribute) should be something like `storageType: [common|ephemeral|async]`, with `common` being default if undefined.

**Comment by l0rd** [comment]
> The current attributes are confusing, since we initially had `ephemeral: true` and so had to add `async: true` on top to keep backward compatibility. Starting over, I think the (probably label, not attribute) should be something like `storageType: [common|ephemeral|async]`, with `common` being default if undefined.

@amisevsk it makes sense. When you say "label, not attribute" you are thinking of to the `DevWorkspace` `metatdata.labels`?

**Comment by amisevsk** [comment]
> When you say "label, not attribute" you are thinking of to the `DevWorkspace` `metatdata.labels`?

Yes, for now at least. We may revisit this once https://github.com/devfile/api/pull/352 is merged, since that would add top-level attributes to DevWorkspaces.

**Comment by l0rd** [comment]
@amisevsk we just added `ephemeral: [true|false]` as a field of volumes in the devfile spec. Shouldn't we replace that with `storageType: [common|ephemeral|async]`?

**Comment by amisevsk** [comment]
@l0rd No, I don't think so. I view the ephemeral field on volumes as serving a separate purpose -- it allows you to share data between containers without requiring persistent storage. The idea would be to have the overall workspace have `[common|ephemeral|async]` storage, but you can mark individual volumes in the devfile as ephemeral if you just want shared disk between images (a great example of this is the remote runtimes volume, which we want to be ephemeral even in an async/common workspace).

Having a per-volume setting for storageType becomes very tricky, as there could be conflicts (e.g. one volume uses common and one uses async, which would mean mounting the common PV in two places). 

For `storageType: ephemeral`, setting `ephemeral: true` on volumes would have no effect, but for common/async it's needed.

**Comment by l0rd** [comment]
@amisevsk makes sense. So that would not require a change in the devfile v2 model spec and I am closing this issue then. I have opened an issue for the `storageType` annotation.
