### ISSUE TITLE
User dashboard initial support for the DevWorkspace operator

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18875]
### Is your enhancement related to a problem? Please describe.

Che user dashboard should allow viewing and managing workspaces created by the DevWorkspace operator.

### Describe the solution you'd like

Using a typescript library (reusable by Che Theia and chectl) the Dashboard should show:

- Workspace list
- Workspace status
- Workspace startup progress

In the case of a workspace based on the DevWorkspace operator a user should be able to edit it using:

- devfile v2 editor

**The support for workspaces plugins/editor configuration is out of the scope of this issue**

Subtasks:

- [ ] [Provides high-level library for managing DevWorkspace objects for clients](https://github.com/eclipse/che/issues/18402)
- [ ] [Begin implementing basic DevWorkspace functionality into new dashboard](https://github.com/eclipse/che/issues/18858)
- [ ] [Dashboard should add a routing class when creating a DevWorkspace](https://github.com/eclipse/che/issues/18886)

**Comment by l0rd** [comment]
duplicate of https://github.com/eclipse/che/issues/18858
