### ISSUE TITLE
Documentation updates to support DevWorkspace engine

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18887]
### Is your enhancement related to a problem? Please describe.

Starting with 7.27 [we plan to support workspaces based on the devworkspace operator and devfile v2 spec](https://github.com/eclipse/che/issues/17307). The documentation should reflect that.

### Describe the solution you'd like

Devfile v2 and v1 will be both supported so that's **NOT** about replacing v1 doc with v2 but adding new v2 doc:

- [ ] [Che architecture section](https://www.eclipse.org/che/docs/che-7/overview/che-architecture/) should be updated
- [ ] All the sections in [Using developers workspaces](https://www.eclipse.org/che/docs/che-7/end-user-guide/workspaces-overview/ ) should be updated
- [x] In [Advanced configuration](https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration/) we should add an article where we document how to configure Che to support DevWorkpace based workspaces [PR](https://github.com/eclipse/che-docs/pull/1895)
- [ ] DevWorkspace operator troubleshooting (CRD, controller pod, logs)
- [ ] [Provide clear public information relating to the devfile v2 and DevWorkspace efforts within the project](https://github.com/eclipse/che/issues/19941)

**Comment by boczkowska** [comment]
Docs Jira issue: https://issues.redhat.com/browse/RHDEVDOCS-2555

**Comment by MichalMaler** [comment]
I asked @l0rd Mario yesterday about the possibility to compose a draft for the new Che architecture that reflects devWorkspace changes. He agreed with content writing in googledoc, I will provide the review and text application.

**Comment by nickboldt** [comment]
When will this issue be complete?

**Comment by l0rd** [comment]
That's not completed yet. Let's move it to 7.43

**Comment by l0rd** [comment]
I am closing this issue as doc updates are tracked in this epic https://github.com/eclipse/che/issues/21264
