### ISSUE TITLE
Push SHA tags for each nightly/next tag (was Start nightly Che workspaces is broken)

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#18931]
### Describe the bug
Unable to start new workspace.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create new workspace using chectl.
2. Try to start new workspace.
3. See that workspace fails to start with error:
```
Failed to pull image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:f07e6...ba2": 
rpc error: code = Unknown desc = Error response from daemon: manifest for 
quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:f0....a2 not found: 
manifest unknown: manifest unknown'
```

### Expected behavior
Workspace should be executed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
```
unknown, workspaceu5fo1hivysjwxhfe.cpp-dev-7845cb785b-ncnsw
2021-02-01 07:49:17,507[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 257]  - Failed to start Kubernetes runtime of workspace workspaceu5fo1hivysjwxhfe.
org.eclipse.che.api.workspace.server.spi.InfrastructureException: Unrecoverable event occurred: 'Failed', 'Failed to pull image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:f07e63102eff29069524734d10dab480e34fdace006c284e6e91c5bbb3104ba2": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:f07e63102eff29069524734d10dab480e34fdace006c284e6e91c5bbb3104ba2 not found: manifest unknown: manifest unknown', 'workspaceu5fo1hivysjwxhfe.cpp-dev-7845cb785b-ncnsw'
	at org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime.handleUnrecoverableEvent(KubernetesInternalRuntime.java:1019)
	at org.eclipse.che.workspace.infrastructure.kubernetes.util.UnrecoverablePodEventListener.handle(UnrecoverablePodEventListener.java:44)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.lambda$eventReceived$0(KubernetesDeployments.java:585)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(Unknown Source)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.eventReceived(KubernetesDeployments.java:585)
	at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$4.eventReceived(KubernetesDeployments.java:550)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:237)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-02-01 07:49:18,151[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 995]   - Workspace 'admin:cpp-w4qb6' with id 'workspaceu5fo1hivysjwxhfe' start failed
Logs from Feb 1, 
```

**Comment by benoitf** [comment]
I think it's fixed

**Comment by azatsarynnyy** [comment]
Looks like it caused by the wrong image hash in Plug-in Registry.

**Comment by benoitf** [comment]
digests referenced by the current registry are valid
https://che-plugin-registry-main.surge.sh/v3/external_images.txt

quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:77bed604b46d12a4d7c0819272ec6dbce88ff18209e21d75d824af833f131ed8

quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:4a063336fb4bfb323c4533cd71fc2d08be063a089f201e050ad82554d673c914

```
$ docker pull quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:77bed604b46d12a4d7c0819272ec6dbce88ff18209e21d75d824af833f131ed8                                                 Digest: sha256:77bed604b46d12a4d7c0819272ec6dbce88ff18209e21d75d824af833f131ed8
Status: Image is up to date for quay.io/eclipse/che-theia-endpoint-runtime-binary

$ docker pull quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:4a063336fb4bfb323c4533cd71fc2d08be063a089f201e050ad82554d673c914                                                
Digest: sha256:4a063336fb4bfb323c4533cd71fc2d08be063a089f201e050ad82554d673c914
Status: Image is up to date for quay.io/eclipse/che-theia-endpoint-runtime-binary
```

**Comment by sleshchenko** [comment]
So, I should get the new registry after I executed `kc rollout restart deployment plugin-registry` but I don't. 
I face this issue for a long time, is there is no changes in pod configuration, new pod is not run even if new container is available. Seems we need a dedicated issue for that on operator side (maybe it's actual for helm chart as well). If it's not expected behavior which would be strange.


To workaround this issue I should
```
kubectl patch deployment/plugin-registry \
        --patch "{\"spec\":{\"replicas\":0}}
kubectl patch deployment/plugin-registry \
        --patch "{\"spec\":{\"replicas\":1}}
```
and the issue with broken che-theia-endpoint-runtime-binary disappeared after that.

**Comment by nickboldt** [comment]
Suggested solution:

* for all nightly/next/CI releases, ensure that in addition to a floating tag, we also have a static tag (based on the sha of the commit)

Thus instead of building/tagging a single image, 

```
docker buildx build --tag nightly
```

we need something like this to produce & push two tags for each release:

```
docker buildx build --tag nightly --tag SHA
```

**Comment by azatsarynnyy** [comment]
I've just faced the same, but with `che-machine-exec` image:
![image](https://user-images.githubusercontent.com/1636395/106748081-62ad0600-662d-11eb-9fbc-b2ed9f9ca6af.png)

**Comment by nickboldt** [comment]
Actions here:
* publish nightly machine exec images using SHA tags IN ADDITION to the nightly/next tags, so that SHAs will persist in Quay after the nightly/mnext tag is moved to a new value.
* publish nightly theia images using SHA tags IN ADDITION to the nightly/next tags, so that SHAs will persist in Quay after the nightly/mnext tag is moved to a new value.

**Comment by nickboldt** [comment]
New machine exec action that fires on push to master branch:

https://github.com/eclipse/che-machine-exec/runs/1823247094?check_suite_focus=true

**Comment by nickboldt** [comment]
New nightly/sha-tagged machine exec:

![image](https://user-images.githubusercontent.com/227597/106769838-66c82c00-660b-11eb-9ee1-c17bf40f470d.png)

**Comment by azatsarynnyy** [comment]
Cool! Thanks @nickboldt !

**Comment by nickboldt** [comment]
Next up... getting a fresh che-theia build... https://github.com/eclipse/che-theia/pull/972

**Comment by dmytro-ndp** [comment]
@azatsarynnyy, @nickboldt the problem has been reproduced again with today's nightly Eclipse Che deployed by using chectl next:
![screenshot-Wait_for_workspace_readiness (6)](https://user-images.githubusercontent.com/1197777/106870945-6185e280-66da-11eb-891f-798f39ef2d21.png)

**Comment by benoitf** [comment]
@dmytro-ndp I think the rolling tags in che-theia was not applied. THere is no such tag yet.
It should be fixed again as I triggered a new plugin registry job

**Comment by dmytro-ndp** [comment]
@benoitf, @nickboldt, @azatsarynnyy: the problem hasn't been reproduced after re-triggering plugin registry build.

**Comment by nickboldt** [comment]
Theia :next now includes a matching sha tag:

![image](https://user-images.githubusercontent.com/227597/107240481-f436c200-69f7-11eb-8804-62e2377df261.png)

**Comment by nickboldt** [comment]
(383M image was UBI based; subsequent builds are alpine only for now.)
