### ISSUE TITLE
Improve configurability for third party tools

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#1894]
It is currently challenging for third party tool providers to integrate with Che because most configuration is done in `che.properties` file. This requires the vendors to get a custom che.properties file, configure che to use that custom property file, and then manage changes between versions.

This epics is a series of improvements to support 12 factor app philosophy. The tasks are ordered in terms of implementation priority.
- [x] Have che-launcher Docker launcher discover all `CHE_` variables. #2013 
- [x] Create a mechanism to configure Che with configs from different sources #2014
- [x] Simplify names of all che.properties to be more user friendly #2015

**Comment by garagatyi** [comment]
> che.workspace.http_proxy=
> che.workspace.https_proxy=
> che.workspace.no_proxy=

these are related not only to workspaces, but for che server too

---

> che.workspace.projects.storage=/projects
> che.workspace.storage=${che.home}/workspaces

Please note (and probably comment in this example) that these props are mutually exclusive. **che.workspace.projects.storage** takes precedence if configured.

---

> che.machine.java_opts

I think it is related to ws-agent only, not the whole runtime. @riuvshin can you comment on that?

---

> che.workspace.ssh_connection_timeout_ms

it is connected to ssh machine implementation. Please respect that fact in property name.

---

> che.workspace.terminal_linux_amd64
> che.workspace.terminal_linux_arm7

These are connected to agent. Please respect that fact.

---

> TODO: is this per machine, or for the entire environment?

per machine

---

> che.docker.registry=${CHE_REGISTRY_HOST}:5000
> che.docker.always_pull_image=true
> che.docker.privilege=false
> che.docker.registry_for_snapshots=false
> che.docker.namespace=NULL
> che.docker.unused_containers_cleanup_min=60
> che.docker.ip
> che.docker.swap=-1

these properties are connected with machine implementation. Whereas next properties are not connected. 

> che.docker.api
> che.docker.tcp_connection_timeout_ms
> che.docker.tcp_connection_read_timeout_ms
> docker.registry.auth.*

Please respect that fact in properties names. Other plugins also can use docker, so properties should not overlap.

**Comment by TylerJewell** [comment]
@garagatyi 

```
che.workspace.http_proxy=
che.workspace.https_proxy=
che.workspace.no_proxy=
```

For these options, how are they set for the Che server as well?  The JVM has already started, so the -D proxy options would not be set.  Or did you mean to imply that these items are set into the JVM startup parameters of the agent?

@garagatyi - I appreciate your point that many of the items are connected to a single, particular type of machine implementation. But the properties as a result become confusing to the end user. It seems that there were two ways to address the properties for machines.
1. Have simplified names - where anything that is for a particular machine, is really just part of che.workspace.*.
1. Have fully qualified names - where the properties would be `che.workspace.environment.machine["docker"].<property>`. While this would be more technically accurate, it's unnecessarily confusing for the end user.

So, in the naming of the properties above, I have offered simplifications that make sense. So while I understand that che.docker.registry and che.docker.api are technically connected to different abstractions in the product, the end user will not make such a distinction, and introducing complexity in the property names becomes unhelpful.

**Comment by benoitf** [comment]
I'm using `machine.server.extra.volume` property, what will be the new name ?
https://github.com/eclipse/che/blob/fd8c5f8ce66938e221e93a01cfd36c4b99aab555/plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/provider/ExtraVolumeProvider.java#L30

**Comment by TylerJewell** [comment]
That property, `machine.server.extra.volume` is not in the current template, so it needs to be added. I would add it as `che.workspace.volume`.  What does this property do?

**Comment by benoitf** [comment]
it allows to mount an extra volume in workspace agent
`machine.server.extra.volume=/my/host-system/folder:/folder-inside-agent`

**Comment by TylerJewell** [comment]
How does the _agent_ mount the volume?  Do you mean that it allows for the workspace container to mount an extra volume?

**Comment by benoitf** [comment]
yes
it adds a -v parameter when launching docker agent machine

**Comment by TylerJewell** [comment]
So, will add the parameter, `che.workspace.volume` as the parameter.

**Comment by garagatyi** [comment]
I think I was mistaken when said about proxy properties, sorry.

**Comment by TylerJewell** [comment]
Ok, no problem!

**Comment by garagatyi** [comment]
Closing since all sub tasks are completed
