### ISSUE TITLE
Add support for chefile configuration

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#1895]
Here is the idea:

_Like for docker or vagrant, we should be able to add a chefile in a directory and then Eclipse Che should be able to create a local folder with all configuration inside this folder._

If I modify locally a file, it will be modified inside che, and if I edit my files inside Eclipse Che it will update the changes on the computer filesystem.

The content of chefile should be scriptable, allowing to use comments and operations/ functions like if () else , for loop, etc (basic scripting operations)

here are list of requirements of chefile
- defines location of che server, connection details, workspace name
- allows user to add commands
- Use context to populate the workspace - files in current directory as project.  (.workspace.json, .workspace.dockerfile, .workspace.composefile as override params.)
- Allows Chefile to use other files instead of .workspace.json.  For example, repo could be checked out and it would have a Dockerfile in the root directory.  Chefile could be told to use this.
- should allow location of workspace to be created - either locally, or remotely.

Command are
`che dir init`
`che dir up`
`che dir down`
`che dir status`

Sample Chefile

```
# This file can be generated by using `che dir init`
# Defines public IP for Che (ip should be IP of docker host)
che.server.ip = localhost

#Defines port number on which Eclipse Che will listen
che.server.port = 8080

# define ENV property that will be propagated to the che-launcher (and che-server)
# example
# che.server.properties['CHE_VERSION']='4.7'
#che.server.properties['http_proxy']='http://localhost:1234'

# Defines name of the workspace
workspace.name = “happy”

# Defines memory of this workspace
workspace.ram = 2048

# Commands
workspace.commands[0].name = "my-first-command"
workspace.commands[0].type = "mvn"
workspace.commands[0].commandLine = "mvn clean install -f ${current.project.path}"
workspace.commands[0].attributes.previewUrl = "http://${server.port.8080}/${current.project.relpath}"

# type can be omitted as it defaults to custom
workspace.commands[1].name = "my-second-command"
workspace.commands[1].commandLine = "echo hello world"

# post loading actions
# referencing a workspace command
workspace.postload.actions[0].name="my-second-command"
#or by defining on-the-fly a one-line command
workspace.postload.actions[1].script=`echo 'this is a post-loading command' \
                                           && while true; do \
                                           echo $(date); sleep 1; \
                                           done`

```

JavaScript syntax is authorized in the Chefile
example

```
var date = new Date();
let es6Date = new Date();

let myMap = new Map();
myMap.set("my-name", "my-custom-workspace");
myMap.set("my-ram", 2048);

console.log('first date is', date);
console.log('another date is', es6Date);

console.log("map is", myMap);

workspace.name=getWorkspaceName();
workspace.ram=myMap.get("my-ram");

console.log('first command of workspace is', workspace.commands[0].commandLine);

function getWorkspaceName() {
   return myMap.get("my-name");
}

```

list of subtasks
- [x] Provide codenvy/che-ip to be able to know on which ip the Che is booted (https://github.com/eclipse/che/pull/1891)
- [x] Introduce codenvy/che-test and codenvy/che-file docker images (https://github.com/eclipse/che/pull/1986)
- [x] Allow chown warnings for booting docker image (https://github.com/eclipse/che/pull/1917)
- [x] If no .che configuration files, provide one automatically
- [x] Implement che dir down (calls che-launcher:stop)
- [x] Test che up / down cycle
- [x] allow to add commands to workspace
- [x] review formatting of commands in chefile
- [x] review how to add maven & other attribute-driven pt --> I would need another project type like "configure" + attribute that would be the wanted project-type, then when opening IDE we could ask these attributes
- [x] configure project as blank instead of 'not configured'
- [x] respect CHE_VERSION environment variable *\* had it set to CHE_VERSION=nightly and then inside the che-file container, it tried to use codenvy/che-ip:latest image, not codenvy/che-ip:nightly.
- [x] externalize strings of the logger to be configurable with external file
- [x] handle comments in Chefile (when writing and handle # as allowed comments)
- [x] allow for che.properties overrides in Chefile - see new syntax
- [x] add che dir status syntax
- [x] use uuid for container names to avoid the use of same names when launching several Che in different directories : requires https://github.com/eclipse/che/pull/2119
- [x] execute a command after ws load
- [x] allow to execute a script as post-load action
- [ ] add support for chefile <> factory json compatibility, so that chefiles can be used as factories
- [ ] Get rid of custom che.properties (used for che.user.workspaces.storage and for machine.server.extra.volume) by only using ENV variable to che-launcher

Test scenario - we should be able to git clone the Che repository and then build it + run it with a set of commands. This will require activating privileged mode with a property override.

Current development branch and readme:
https://github.com/eclipse/che/blob/che-files/dockerfiles/che-file/README.md

branch is named `che-files`

docker image is named `codenvy/che-file`

**Comment by TylerJewell** [comment]
@benoitf - I added a sub-task around detecting certain scenarios on windows with boot2docker.
