### ISSUE TITLE
Plugins Sprint 197

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#18987]
## Sprint 197 (February 10th 2021 - March 2nd 2021)
This sprint will result in the release of Che 7.27.

### Epics
* Allow Che 7 Git + SSH Flow #13494 @vitaliy-guliy 
    * [x] Check for credentials (SSH) before trying to clone git repositories: https://github.com/eclipse/che/issues/13494#issuecomment-694387267

### CRW
* [x] Empty plugin list in CRW behind the proxy [CRW-1542](https://issues.redhat.com/browse/CRW-1542) @vinokurig 
* [x] Debugging of the current file failed to start in the "CakePhp" devfile [CRW-1522](https://issues.redhat.com/browse/CRW-1522) @svor 
* [x] ("Quarkus" workspace) Debug stops at the breakpoint only if breakpoint set up during debug session [CRW-1543](https://issues.redhat.com/browse/CRW-1543) @svor 
* [x] Investigate adding Lombok to Che @sunix 
    * [x] Please provide Lombok plugin for CRW [CRW-1420](https://issues.redhat.com/browse/CRW-1420)
    * [x] Investigate if Che-theia is providing the right path for vscode.extensions.getExtension(extensionId)..extensionPath #18632
* [x] Adding a check in plugin registry to check for valid registry urls/names [CRW-1449](https://issues.redhat.com/browse/CRW-1449) @vinokurig 
* [ ] VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) @tsmaeder 
    * [ ] Java code snippets 'try_catch' and 'main' are not working #16502
    * [ ] Snippets don't work when Plugin Host is not colocated with Back End eclipse-theia/theia#8460
    * _Retrospective: PR is open but some regressions were caught during testing, which required more work/time_
* [ ] Update the typescript plugin to the latest version [CRW-1434](https://issues.redhat.com/browse/CRW-1434) @tsmaeder 
    * [ ] vscode-typescript-language-features does not include `typescript-vscode-sh-plugin` eclipse-theia/vscode-builtin-extensions#38
    * _Retrospective: work is still in progress_
* [x] Use 3rd party icons in CRW plugin registry instead of invisible ones @vitaliy-guliy 
    * [x] After switching to auto-generated plugin registry, the plugin icons were reset to default icon #18908
* [x] Remove obsolete Dockerfiles from CRW registries repos; update README / build.sh to default to --rhel (rhel.Dockerfile) [CRW-1498](https://issues.redhat.com/browse/CRW-1498) @ericwill 
* [x] Ensure deployment templates from upstream registries are downstreamed to CRW registries [CRW-1567](https://issues.redhat.com/browse/CRW-1567) @ericwill 
    * Full syncing of the upstream and downstream registries will happen next sprint

### Bugs
* [ ] "Circular struture" errors when accepting "current change" #18921 @tsmaeder 
    * _Retrospective: didn't get to this item_
* [ ] Unable to run task when using custom TLS certificate #18957 @sunix 
    * _Retrospective: work is still in progress_
* [x] Syntax highlighting behaving strangely in several Java devfiles #18448 @sunix  
* [x] shellcheck binary not found in the shellcheck extension #18924 @ericwill 
* [ ] github pr plugin: fork creation is hanging when creating a pull request #18664 @vinokurig 
    * _Retrospective: this item has required significant investigation and is still in progress_

### Enhancements
* [x] Please produce a plugin for Mermaid #18750 @vitaliy-guliy 
* [x] [che-theia] - open http preview in separate browser tab #18002 @vitaliy-guliy 

### Docs
* [ ] Impact of new plugin model on the documentation #18793 @ericwill
    * _Retrospective: work has started, but progress is halted for now until the re-write of the upstream articles is merged_

### QE
* [x] Provide a list of current upstream and downstream test cases/scenarios:
    * What's being tested
    * How it's being tested (automated or manual)
* [x] Run upstream test suites and file issues for any items that need to be fixed
* [x] Start testing CRW as early as possible

### Unplanned
* [x] The "redhat/vscode-yaml" plugin doesn't work [CRW-1603](https://issues.redhat.com/browse/CRW-1603) @svor 

### Open PRs From Last Sprint
* [ ] Using GIT plugin generates an error on the console eclipse-theia/theia#7953 
    * _Retrospective: PR is open upstream and is undergoing discussion and review by theia devs_
* [ ] Errors in the custom registry build documentation [RHDEVDOCS-2513](https://issues.redhat.com/browse/RHDEVDOCS-2513) 
    * _Retrospective: work has started, but progress is halted for now until the re-write of the upstream articles is merged_

#### Automation / Tests
* [ ] Ability to run tests of a vscode extension on top of che-theia #18219 @svor
    * _Retrospective: work is still in progress, this is a complex task so the work will span multiple sprints_

#### Dogfooding, Developer Experience, or UX Improvements
* [ ] Rework che-theia build process to not use source linking #16852 @tsmaeder
    * _Retrospective: work is still in progress, this is a low priority task_
* [ ] A single dogfooding devfile for che-theia #18763 @sunix 
    * [ ] Clean up che-theia build: rely on multistage build as much as possible. #18969
    * _Retrospective: work is still in progress, this is a low priority task_

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 14  | 8 |
| @ericwill | 13 | 8 |
| @tsmaeder | 14 | 8 |
| @svor | 14 | 8 |
| @sunix | 13 | 8 |
| @Ohrimenko1988 | 13 | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Errors in the custom registry build documentation [RHDEVDOCS-2513](https://issues.redhat.com/browse/RHDEVDOCS-2513) |
| 2 | Remove obsolete Dockerfiles from CRW registries repos; update README / build.sh to default to --rhel (rhel.Dockerfile) [CRW-1498](https://issues.redhat.com/browse/CRW-1498) |
| 3  | Ensure deployment templates from upstream registries are downstreamed to CRW registries [CRW-1567](https://issues.redhat.com/browse/CRW-1567)  |
| 4 | Upstream docs |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) |
| 2 | Update the typescript plugin to the latest version [CRW-1434](https://issues.redhat.com/browse/CRW-1434) |
| 3 | "Circular struture" errors when accepting "current change" #18921 |
| 4 | Rework che-theia build process to not use source linking #16852 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1  | ("Quarkus" workspace) Debug stops at the breakpoint only if breakpoint set up during debug session [CRW-1543](https://issues.redhat.com/browse/CRW-1543) |
| 2  | Debugging of the current file failed to start in the "CakePhp" devfile [CRW-1522](https://issues.redhat.com/browse/CRW-1522) |
| 3 | Ability to run tests of a vscode extension on top of che-theia #18219 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1  |  Adding a check in plugin registry to check for valid registry urls/names [CRW-1449](https://issues.redhat.com/browse/CRW-1449) |
| 2  | Adding a check in plugin registry to check for valid registry urls/names [CRW-1449](https://issues.redhat.com/browse/CRW-1449)  |
| 3 | github pr plugin: fork creation is hanging when creating a pull request #18664 |
| 4 | Using GIT plugin generates an error on the console eclipse-theia/theia#7953 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Check for credentials (SSH) before trying to clone git repositories: https://github.com/eclipse/che/issues/13494#issuecomment-694387267 |
| 2 | Use 3rd party icons in CRW plugin registry instead of invisible ones |
| 3 | Please produce a plugin for Mermaid #18750 |
| 4 | [che-theia] - open http preview in separate browser tab #18002 |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Syntax highlighting behaving strangely in several Java devfiles #18448 |
| 2 | Investigate adding Lombok to Che |
| 3 | Unable to run task when using custom TLS certificate #18957 |
| 4 | A single dogfooding devfile for che-theia #18763 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Provide a list of current upstream and downstream test cases/scenarios |
| 2 | Run upstream test suites and file issues for any items that need to be fixed |
| 3 | Start testing CRW as early as possible |

**Comment by benoitf** [comment]
maintenance section looks like more exploring stuff or technical debt issues than maintenance.

**Comment by ericwill** [comment]
Superseded by #19159
