### ISSUE TITLE
Che Controller Sprint 197

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18991]
This issue collect work items of Controller Team for Sprint 197 (10 Feb - 2 Mar)

#### Dashboard side
- [x] Basic DevWorkspace functionality into new dashboard https://github.com/eclipse/che/issues/18858
- [x] Support devfile v2 factory link https://github.com/eclipse/che/issues/19147

#### Operator side
- [ ] Implement the mechanism to configure dockercfg secret as imagePullSecrets for devworkspace https://github.com/devfile/devworkspace-operator/issues/264
- [x] Extending Volume components to support more features (ephemeral only) https://github.com/devfile/api/issues/310
- [ ] Implement support for async storage in controller https://github.com/devfile/devworkspace-operator/issues/267

### New dashboard finalization
- [x] Dashboard should display a clear error page when initialization process is failed https://github.com/eclipse/che/issues/18758
- [x] Dashboard next should support factory policies.create=peruser https://github.com/eclipse/che/issues/18961

### Factory from private git registries
- [ ] Support OAuth flow for private repo factories on Dashboard https://github.com/eclipse/che/issues/18976
:notebook: Is expected for CRW 2.8

### Web Terminal Operator
- [x] Web Terminal Tooling depends on injecting kubeconfig into the first available container https://github.com/devfile/devworkspace-operator/issues/258
- [x] Create WTO 1.2 blog post [WTO-71](https://issues.redhat.com/browse/WTO-71)
- [x] Update tooling binaries which corresponds to OpenShift 4.7 [WTO-59](https://issues.redhat.com/browse/WTO-59)

### Unplanned

- [x] Add support for plugins referenced by URI or in external registries https://github.com/devfile/devworkspace-operator/pull/269
- [x] Initialize devworkspace client https://github.com/eclipse/che/issues/19071

#### Dashboard stabilization
- [x] Dashboard should propagate runtime logs https://github.com/eclipse/che/issues/19028
- [x] Devfile editor does not propose autocompletes until first letter is filled https://github.com/eclipse/che/issues/19021
- [x] Dashboard buidx build of next tag is not stable at all https://github.com/eclipse/che/issues/19049
- [x] Refreshing "Create custom workspace" page sometimes does not populate existing workspaces https://github.com/eclipse/che/issues/19020
- [x] Dashboard next getting started page problems in single host mode https://github.com/eclipse/che/issues/18084
- [x] Start in backgroud action tries to use expired token https://github.com/eclipse/che/issues/19058
- [x] UD bulk remove displays wrong workspaces list https://github.com/eclipse/che/issues/19057
- [x] Singleuser: Operations with workspaces don't work https://github.com/eclipse/che/issues/19038

#### Other

- [ ] Deprecate workspace-loader https://github.com/eclipse/che/issues/18785
- [ ] Fix the check on OpenShift Console to show terminal button https://issues.redhat.com/browse/WTO-20
