### ISSUE TITLE
Che Deploy Sprint #197

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#18992]
#### Timeframe
Feb. 10 - Mar.  2

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays / events:
- Feb. 19 Hack 'n' Hustle
- Feb 26 Recharging day

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x

---
### CRW issues 
- [x] .Deploying registries in OpenShift - All templates for deployment must be reworked https://issues.redhat.com/browse/RHDEVDOCS-2483
  - [x] https://github.com/eclipse/che-plugin-registry/pull/793
  - [x] https://github.com/eclipse/che-devfile-registry/pull/324
  - [x] https://github.com/redhat-developer/codeready-workspaces/pull/429
  - [x] https://github.com/redhat-developer/codeready-workspaces/pull/437
- [x] .IG - CheCluster Custom Resource documentation missing server. workspaceNamespaceDefault attribute https://issues.redhat.com/browse/RHDEVDOCS-2216
  - [x] https://github.com/eclipse/che-docs/pull/1803
  - [x] https://github.com/eclipse/che-operator/pull/667
  - [x] https://github.com/eclipse/che-operator/pull/671
- [ ] Installation with router sharding not working https://issues.redhat.com/browse/CRW-1466
  - [x] https://github.com/eclipse/che-operator/pull/666
- [x] .Certificates are not correctly added to the Java TrustStore https://issues.redhat.com/browse/CRW-1538
  - [x] https://github.com/eclipse/che-docs/pull/1861
- [x] .'crwctl auth:login' failed to login to CRW with OAuth support https://issues.redhat.com/browse/CRW-1509
  - [x] https://github.com/eclipse/che/pull/19096
  - [x] https://github.com/eclipse/che/pull/19108
---
### Eclipse Che issues 
- [x] .Create a valid user if no one exist when deploying on OpenShift https://github.com/eclipse/che/issues/18152
  - [x] https://github.com/eclipse/che-operator/pull/597
  - [x] https://github.com/eclipse/che-docs/pull/1851
  - [x] https://github.com/che-incubator/chectl/pull/1099
- [x] .[chectl] Deploying Eclipse Che should not depend on a specific version of chectl https://github.com/eclipse/che/issues/18022
  - [x] https://github.com/che-incubator/chectl/pull/1095
  - [x] https://github.com/che-incubator/chectl/pull/1082
  - [x] https://github.com/che-incubator/chectl/pull/1091
  - [x] https://github.com/redhat-developer/codeready-workspaces-chectl/pull/56
- [x] .[che-operator] Configure OAuth1 and OAuth2 integrations with K8s Secrets https://github.com/eclipse/che/issues/18932
  - [x] https://github.com/eclipse/che-operator/pull/677
  - [x] https://github.com/eclipse/che-docs/pull/1859
- [x] .chectl with workspace-engine=dev-workspace doesn't work https://github.com/eclipse/che/issues/18842 https://github.com/eclipse/che/issues/18962
  - [x] https://github.com/che-incubator/chectl/pull/1100
  - [x] https://github.com/eclipse/che/pull/19075
- [ ] Switch to the new Operator Bundle Format https://github.com/eclipse/che/issues/16928
  - [ ] https://github.com/eclipse/che-operator/pull/690
  - [ ] TODO OpenShift CI
  - [ ] TODO remove leftovers
  - [ ] TODO chectl
- [ ] [che-operator] Provides the ability to create backups https://github.com/eclipse/che/issues/18703
- [ ] Align chectl telemetry with red hat devtools requirements https://github.com/eclipse/che/issues/18861
- [x] .chectl auth:login fails without correct kubecontext https://github.com/eclipse/che/issues/18684
  - [x] https://github.com/che-incubator/chectl/pull/1085/files
- [x] .parameter devfileRegistryPullPolicy is not handled https://github.com/eclipse/che/issues/18847
- [ ] Add e2e tests for chectl olm installer in Openshift 4.6 and OCP nightly https://github.com/eclipse/che/issues/18293 
- [x] .We need to cover test case in the e2e tests when che-operator oauth is enabled https://github.com/eclipse/che/issues/17939
  - [x] https://github.com/eclipse/che-operator/pull/670
  - [x] https://github.com/eclipse/che-operator/pull/675
---
### PR to merge 
- [x] .https://github.com/redhat-developer/codeready-workspaces-operator/pull/42 
---
### Unplanned
- [ ] Che operator should be able to install DevWorkspace operator https://github.com/eclipse/che/issues/19121
  - [ ] https://github.com/eclipse/che-operator/pull/689
- [x] Add test flow for chectl server:update command https://github.com/eclipse/che/issues/19013
  - [x] https://github.com/che-incubator/chectl/pull/1117
- [x] .Use --version flag to deploy and update Eclipse Che https://github.com/eclipse/che-operator/pull/683
- [x] .Installation fails when checluster k8s.tlsSecretName is empty https://github.com/eclipse/che/issues/19052
  - [x] https://github.com/eclipse/che-operator/pull/674
- [x] .unable to deploy che with server:deploy command https://github.com/eclipse/che/issues/19033
  - [x] https://github.com/che-incubator/chectl/pull/1093
- [x] .[chectl] 'chectl server:deploy' command failed on "Create ServiceAccount che-operator" step https://github.com/eclipse/che/issues/19019
  - [x] https://github.com/che-incubator/chectl/pull/1090
---
 [Previous Sprint](https://github.com/eclipse/che/issues/18801)
