### ISSUE TITLE
Improve Che Release Process Part 4

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19007]
Follows up from #17748 

- [x]  Move Che release workflow from Centos CI #17857

- [x]  Implement proper tag recreation option for release scripts #18879

Notifications / workflow:

- [x] Create GH action to check at intervals for the presence of the latest che-server artifacts in Maven Central (and Quay) #18832

- [x]  Should Che releases be GH releases (and thus update the 'latest release' metadata) ? #17177

 - [x] Announce releases - https://github.com/eclipse/che-release/pull/16 #17579

 - [ ] Orchestrate inter-build triggers - https://github.com/eclipse/che/issues/19127

**Comment by nickboldt** [comment]
Releases are now being announced in mattermost. https://mattermost.eclipse.org/eclipse/channels/eclipse-che-releases

**Comment by nickboldt** [comment]
everything is done here except https://github.com/eclipse/che/issues/19127 so might as well close.
