### ISSUE TITLE
Che Platform Sprint 197

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19029]
#### Timeframe
Feb. 10 - Mar.  2

#### Team
| Name  | 
| ------------- |
| @sparkoo   | 
| @metlos   |  
| @mshaposhnik   |
| @xbaran4   |   
| @skabashnyuk  |  

#### Holidays / events:
- Feb 19th Hack 'n' Hustle
- Feb 26th Recharge day

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x

---

### Bitbucket Server

- [x] Obtain and persist Bitbucket personal access token as k8s secret | https://github.com/eclipse/che/issues/18388
- [x] Clarify factory resolution process for private Bitbucket repositories | https://github.com/eclipse/che/issues/18389

### Devworkspaces
- [x]  chectl should deploy che-devworkspace-operator (along with devworkspace-operator) when the engine is devworkspace | https://github.com/eclipse/che/issues/19001
- [x] Devfile v2 validation on /factory/resolve | https://github.com/eclipse/che/issues/18948
- [x] [che-server] Provide devfile v2 schema on REST API | https://github.com/eclipse/che/issues/19023
### Bugs/Technical debt
- [x] Setting tlsSecretName before I deploy Che results in workspaces not starting | https://github.com/eclipse/che/issues/18810
- [x] Installation with router sharding not working | https://issues.redhat.com/browse/CRW-1466
- [x] Unable to start workspace with public SSH key stored on an alias with unexpected characters | https://github.com/eclipse/che/issues/19024
