### ISSUE TITLE
Editors Sprint 197

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19040]
Feb 10 - Mar 2

---
- [x] Che-Theia shows `Offline` mode, mistakenly https://github.com/eclipse/che/issues/18723
- [x] Che-Theia code coverage reporting https://github.com/eclipse/che/issues/18844
- [x] Identify what is missing in Che-Theia for Jupyter support https://github.com/eclipse/che/issues/16818

#### CRW Docs
- [ ] Providing a custom IDE based on Eclipse Theia and Switching the default editor to another one [RHDEVDOCS-1278](https://issues.redhat.com/browse/RHDEVDOCS-1278)
   - the PR https://github.com/eclipse/che-docs/pull/1875 has been provided and waiting for a review

#### Multi-root Workspaces
- [x] Multi-root Che Theia Workspaces https://github.com/eclipse/che/issues/17212
    - [x] Change config storage paths from /home/theia/home/theia to the corresponding paths https://github.com/eclipse/che/issues/18548
###### PRs to merge:
- [x] https://github.com/eclipse/che-theia/pull/778

---
### Unplanned/Blockers
- [x] Unable to Open With --> Preview for HTML files [CRW-1596](https://issues.redhat.com/browse/CRW-1596)
- [x] Helped Prod Team with investigation of [CRW-1475](https://issues.redhat.com/browse/CRW-1475)
- [ ] Report realistic code coverage for che-theia repo https://github.com/eclipse/che/issues/19130
   - WIP PR https://github.com/eclipse/che-theia/pull/1007
---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 13  | 8
| Roman   | 13  | 8
| Artem | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/18845)
