### ISSUE TITLE
Merge DevWorkspace Che operator in Che operator 

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19145]
### Is your enhancement related to a problem? Please describe.

In the `DevWorkspace` configuration Che operator will install both `DevWorkspace` operator ([issue](https://github.com/eclipse/che/issues/19121)) and `DevWorkspace Che` operator ([issue](https://github.com/eclipse/che/issues/19142)). Those are currently 2 independent operators: they can be installed even without Che. But although it makes sense for `DevWorkspaec` operator, `DevWorkspace Che` is highly coupled to Che, it does only make sense when Che is deployed.

### Describe the solution you'd like
`DevWorkspace Che` controller and CRDs should be included in Che operator.

### Sub tasks
- [x] DWO, DWCO and CO should use CRD of the same versions https://github.com/eclipse/che/issues/19472
- [x] Run DWCO and CO in a single container but in different pods https://github.com/eclipse/che/issues/19402
- [x] Update operator-sdk to the latest version https://github.com/eclipse/che/issues/19466
- [x] Merge DWCO and CO in a single codebase https://github.com/eclipse/che/issues/19408

**Comment by tolusha** [comment]
@metlos  suggested to merge DevWorkspace Che operator codebase into a Che Operator
@l0rd WDYT?

**Comment by l0rd** [comment]
@tolusha I am +1 for that

**Comment by nickboldt** [comment]
I'm +1 too, especially if it can be prioritied for 7.28.0 (or 7.28.x backport).

**Comment by tolusha** [comment]
@l0rd 
We decided to split the task into 2 steps.
On first step [1] we run DWCO in a separate pod.
On the second [2] we merge codebase and run DWCO in the same pod.

[1] Run DWCO and CO in a single container but in different pods https://github.com/eclipse/che/issues/19402
[2] Merge DWCO and CO in a single codebase https://github.com/eclipse/che/issues/19408

/cc @sparkoo @metlos @skabashnyuk

**Comment by l0rd** [comment]
@tolusha it makes sense

**Comment by tolusha** [comment]
This issue is started to be an umbrella for sub-tasks.
I've removed it from the current sprint and added another one [1] which is possible to complete. 

[1] https://github.com/eclipse/che/issues/19402
