### ISSUE TITLE
Editors Sprint 198

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19146]
Mar 3 - Mar 23

---
#### Jupyter Notebooks https://github.com/eclipse/che/issues/16818
- [x] Adapt `vscode.workspace.fs` Plug-in API to Che-Theia's remote plugin model https://github.com/eclipse/che/issues/19110

#### Multi-root workspaces as a default project layout in Che-Theia https://github.com/eclipse/che/issues/19199
- [x] Multi-root workspaces should be default when using Dev Workspaces / devfile v2 https://github.com/eclipse/che/issues/19191

#### UX
- [x] Have CRW detect 'X-frame-options' value 'deny', warn the user [CRW-1319](https://issues.redhat.com/browse/CRW-1319)

#### Docs
- [x] Document how to include an upstream Theia patch into Che-Theia release https://github.com/eclipse/che/issues/19141, [RHDEVDOCS#2741](https://issues.redhat.com/browse/RHDEVDOCS-2741)
- [x] Providing a custom IDE based on Eclipse Theia [RHDEVDOCS-1278](https://issues.redhat.com/browse/RHDEVDOCS-1278)

#### CI/tests
- [x] Report realistic code coverage for che-theia repo https://github.com/eclipse/che/issues/19130
- [x] Remove `ci.centos.org (build)` PR status check on Che-Theia repo https://github.com/eclipse/che/issues/19100

#### Theia APIs
- [x] Support `workbench.action.files.openFileFolder` built-in command https://github.com/eclipse-theia/theia/issues/8750
- [ ] Implement `vscode.ExtensionContext.storageUri` API https://github.com/eclipse-theia/theia/issues/8883

---
### Unplanned/Blockers
- [x] Fix publishing to npmjs https://github.com/eclipse/che-theia/pull/1016
- [x] Align TaskScope with VS Code API https://github.com/eclipse/che/issues/19338

---
## Availability
| Name  | Availability | x0.6
| -- | -- | --
| Vlad   | 13  | 8
| Roman   | 13  | 8
| Artem | 13  | 8

---
[Previous Sprint](https://github.com/eclipse/che/issues/19040)
