### ISSUE TITLE
Che Deploy Sprint #198

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19155]
#### Timeframe
Mar. 3 - Mar.  23

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays / events:
- Mar. 8 International Women's Day Ukraine
- Mar. 12 Hack 'n' Hustle
- Mar. 18 Holiday in Spain

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x

---
### CRW issues 
- [x] Installation with router sharding not working https://issues.redhat.com/browse/CRW-1466
  - [x] https://github.com/eclipse/che-docs/pull/1887
- [x] .[DDF] The tlsSupport property is documented as deprecated but still shown set to "true" in the CheCluster CRD yaml. https://issues.redhat.com/browse/CRW-1613  
  - [x] https://github.com/eclipse/che-operator/pull/696
- [ ] Mismatch between CRW keycloak and Openshift OAuth causing unknown error during login https://issues.redhat.com/browse/CRW-1426
- [x] .CRW 2.7.0.RC-02-26 without OS OAuth support failed to start the workspace https://issues.redhat.com/browse/CRW-1622
- [x] .Compilation failure in crw operator https://issues.redhat.com/browse/CRW-1627
  - [x] https://github.com/eclipse/che-operator/pull/693
  - [x] https://github.com/eclipse/che-operator/pull/694

---
### Eclipse Che issues 
- [x] .Align chectl telemetry with red hat devtools requirements https://github.com/eclipse/che/issues/18861
  - [x] https://github.com/che-incubator/chectl/pull/1119
- [x] .Che operator should be able to install DevWorkspace operator https://github.com/eclipse/che/issues/19121
  - [x] https://github.com/eclipse/che-operator/pull/689
  - [x] https://github.com/che-incubator/chectl/pull/1125
  - [x] https://github.com/eclipse/che-docs/pull/1895
  - [x] https://github.com/eclipse/che-operator/pull/713
- [x] .Switch to the new Operator Bundle Format https://github.com/eclipse/che/issues/16928
  - [x] https://github.com/eclipse/che-operator/pull/690
  - [x] https://github.com/openshift/release/pull/16626
  - [x] https://github.com/eclipse/che-operator/pull/709
  - [x] https://github.com/eclipse/che-operator/pull/710
  - [x] https://github.com/eclipse/che-operator/pull/711
  - [x] https://github.com/eclipse-che/che-operator/pull/725
- [ ] Merge DevWorkspace Che operator in Che operator https://github.com/eclipse/che/issues/19145
- [x] .Migrate che-operator, che-machine-exec to 'eclipse-che' organization https://github.com/eclipse/che/issues/18995
  - [x] https://github.com/eclipse/che-machine-exec/pull/136
  - [x] https://bugs.eclipse.org/bugs/show_bug.cgi?id=571912
  - [x] https://github.com/eclipse-che/che-machine-exec/pull/137
  - [x] https://bugs.eclipse.org/bugs/show_bug.cgi?id=571958
  - [x] https://github.com/openshift/release/pull/16845
  - [x] https://github.com/eclipse-che/che-operator/pull/727
  - [x] https://github.com/eclipse/che/pull/19353
- [ ] [che-operator] Provides the ability to create backups/restore https://github.com/eclipse/che/issues/18703
- [x] .Ensure chectl binaries archives are working https://github.com/eclipse/che/issues/19026
  - [x] https://github.com/che-incubator/chectl/pull/1120
- [ ] Theia terminal extension must propagate error from che-machine-exec https://github.com/eclipse/che/issues/16593
  - [x] https://github.com/eclipse/che-theia/pull/1036
- [x] .Add e2e tests for chectl olm installer in Openshift 4.6 and OCP nightly https://github.com/eclipse/che/issues/18293 
  - [x] https://github.com/openshift/release/pull/16933
  - [x] https://github.com/eclipse-che/che-operator/pull/722
  - [x] https://github.com/openshift/release/pull/16940
- [x] .Deploy Eclipse Che behind proxy using Openshift CI in che operator tests https://github.com/eclipse/che/issues/19006
  - [x] https://github.com/openshift/release/pull/16497
  - [x] https://github.com/eclipse/che-operator/pull/705
- [x] Strange interaction with chectl https://github.com/eclipse/che/issues/19128
  - [x] https://github.com/che-incubator/chectl/pull/1122
- [ ] [che-operator] garbage collect cluster-scoped objects https://github.com/eclipse/che/issues/18501
  - [x] https://github.com/eclipse/che-operator/pull/708
- [x] .Make Che Theia work when ca.cert doesn't contain complete certificate chain of trust https://github.com/eclipse/che/issues/17938
  - [x] https://github.com/eclipse-che/che-operator/pull/718
  - [x] https://github.com/eclipse/che-theia/pull/1038
  - [x] https://github.com/eclipse/che-docs/pull/1922
---
### Unplanned
- [ ] Use eclipse-che namespace as default namespace for login https://github.com/che-incubator/chectl/pull/1139
- [x] .Migrate machine exec and operator to new GH organization https://issues.redhat.com/browse/CRW-1661
  - [x] https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/380
- [x] .No such file error when deploying Che with DevWorkspace operator https://github.com/eclipse/che/issues/19315
  - [x] Fix dwo CRD file name https://github.com/che-incubator/chectl/pull/1137
- [x] .Install stable che, when flag olm-channel has stable value https://github.com/che-incubator/chectl/pull/1132
- [x] .Fix chectl tests and fix devworkspace CRD name https://github.com/eclipse-che/che-operator/pull/721
- [x] .devworkspace-che-role is forbidden when deploying Che with DevWorkspace operator https://github.com/eclipse/che/issues/19283
  - [x] https://github.com/eclipse/che-operator/pull/717
- [x] .compilation failure in crw operator https://issues.redhat.com/browse/CRW-1655
  - [x] https://github.com/eclipse/che-operator/pull/714
- [x] .chectl next channel is broken https://github.com/eclipse/che/issues/19277
- [x] .Che operator enable to reconcile CheCluster due KubernetesImagetPuller CRD lack https://github.com/eclipse/che/issues/19207
  - [x] https://github.com/eclipse/che-operator/pull/700
- [x] .chectl e2e tests aren't stable https://github.com/eclipse/che/issues/19213
  - [x] https://github.com/che-incubator/chectl/pull/1127
- [x] .Fix nightly bundle check action https://github.com/eclipse/che-operator/pull/706
- [x] .Adopt minikube related GitHub actions https://github.com/eclipse/che-operator/pull/695
---
 [Previous Sprint](https://github.com/eclipse/che/issues/18992)
