### ISSUE TITLE
Plugins Sprint 198

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19159]
## Sprint 198 (March 3rd 2021 - March 23rd 2021)
This sprint will result in the release of Che 7.28.

### Epics
* [ ] Upgrade the golang plugin #19154 @svor 
    * [ ] vscode.Uri.joinPath is not a function eclipse-theia/theia#8752
    * _Retrospective: work on this item is blocked by upstream theia API, which is blocked by the pending monaco upgrade._
* [x] Review devfiles and switch to multi-root workspaces, where applicable @tsmaeder / @sunix 

### CRW
* [x] sonarlint not working on workspaces.openshift.com [CRW-1604](https://issues.redhat.com/browse/CRW-1604) @vinokurig 
    * [x] Upgrade the sonarlint plugin #19156
* [x] VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) @tsmaeder 
    * [x] Java code snippets 'try_catch' and 'main' are not working #16502
    * [x] ~~Snippets don't work when Plugin Host is not colocated with Back End eclipse-theia/theia#8460~~
        * Not handled as part of this issue anymore
* [x] Update the typescript plugin to the latest version [CRW-1434](https://issues.redhat.com/browse/CRW-1434) @tsmaeder 
    * [x] vscode-typescript-language-features does not include `typescript-vscode-sh-plugin` eclipse-theia/vscode-builtin-extensions#38
* [x] No text in terminal tab [CRW-1570](https://issues.redhat.com/browse/CRW-1570) @svor 
* [x] Please provide Lombok plugin for CRW [CRW-1420](https://issues.redhat.com/browse/CRW-1420) @sunix 
    * [x] Implement upstream solution in downstream: https://github.com/redhat-developer/codeready-workspaces-images
    * [x] Add documentation for how to enable Lombok support
    * [x] Discuss possibility of having a separate Lombok devfile
* [x] Unable to checkout repository to a different branch [CRW-1591](https://issues.redhat.com/browse/CRW-1591) @vinokurig 
    * [x] Can not checkout to another branch via the status bar action #19030
* [ ] Sync & transform upstream Che registries into CRW registries [CRW-1567](https://issues.redhat.com/browse/CRW-1567) @ericwill 
    * _Retrospective: blocked because nightly CRW builds are needed._

### Bugs
* [x] Unable to run task when using custom TLS certificate #18957 @sunix 
* [ ] SSH Upload Private Key does not work as expected #19109 @vitaliy-guliy 
* [ ] Cloning by `Git Clone` command should be consistent with cloning by workpsace plugin #19133 @vitaliy-guliy
* [x] Can not clone zip project on Minikube #19120 @vitaliy-guliy
* [ ] github pr plugin: fork creation is hanging when creating a pull request #18664 @vinokurig 
    * [ ] Update the vscode GitHub Pull-Requests plugin to latest. #18661
        * [ ] Apply FileDecoration provider API https://github.com/eclipse-theia/theia/pull/8911
        * _Retrospective: this item is blocked by the pending monaco upgrade._

### Docs
* [ ] Impact of new plugin model on the documentation #18793 @ericwill 
* [ ] Errors in the custom registry build documentation [RHDEVDOCS-2513](https://issues.redhat.com/browse/RHDEVDOCS-2513) @ericwill 
* [x] Che docs devfile is broken #18580 @ericwill 

### QE
* [x] CRW 2.7 release testing @Ohrimenko1988 
* [x] Create tests for the vale plugin #19162 @Ohrimenko1988
* [x] Create tests for the shellcheck plugin #19163 @Ohrimenko1988
* [x] Create tests for the "yaml" plugin #19177 @Ohrimenko1988
* [x] Create tests for the "xml" plugin #19178 @Ohrimenko1988
* [ ] Create nightly CI job for launching all plugins tests #19179 @Ohrimenko1988

### Devfile 2.0
* [ ] Che editors should be defined using Devfile v2 syntax #19034 @ericwill 
* [ ] Try Che with new workspace engine

### Unplanned
* [x] [Devsandbox] Activating extension 'GitHub Pull Requests and Issues' failed: No authentication provider 'github' is currently registered [CRW-1446](https://issues.redhat.com/browse/CRW-1446) @vinokurig 

### Open PRs From Last Sprint
* [x] Using GIT plugin generates an error on the console eclipse-theia/theia#7953 @vinokurig 

#### Automation / Tests
* [ ] Ability to run tests of a vscode extension on top of che-theia #18219 @svor 
    * [ ] [plugins] Cannot read property 'getExtension' of vscode.extensions #19172
* [x] Improve vscode-extensions builder to work independently of extension.json changes #19134 @ericwill 

#### Maintenance
* [x] Upgrade the Java stack #19099 @sunix 
* [ ] [vscode] window.showQuickPick canPickMany is not supported eclipse-theia/theia#5673 @vinokurig 

#### Dogfooding, Developer Experience, or UX Improvements
* [ ] Rework che-theia build process to not use source linking #16852 @tsmaeder 
* [ ] A single dogfooding devfile for che-theia #18763 @sunix 
    * [ ] Clean up che-theia build: rely on multistage build as much as possible. #18969

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 14  | 8 |
| @ericwill | 15 | 9 |
| @tsmaeder | 15 | 9 |
| @svor | 13 | 8 |
| @sunix | 15 | 9 |
| @Ohrimenko1988 | 14 | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Ensure deployment templates from upstream registries are downstreamed to CRW registries [CRW-1567](https://issues.redhat.com/browse/CRW-1567) |
| 2 | Che editors should be defined using Devfile v2 syntax #19034 |
| 3  |  Errors in the custom registry build documentation [RHDEVDOCS-2513](https://issues.redhat.com/browse/RHDEVDOCS-2513) |
| 4 | Impact of new plugin model on the documentation #18793 |
| 5 | Improve vscode-extensions builder to work independently of extension.json changes #19134 |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  VS Code extensions providing code snippets APIs make not usable in CRW [CRW-1294](https://issues.redhat.com/browse/CRW-1294) |
| 2 | Update the typescript plugin to the latest version [CRW-1434](https://issues.redhat.com/browse/CRW-1434) |
| 3 | Rework che-theia build process to not use source linking #16852 |
| 4 | Review devfiles and switch to multi-root workspaces, where applicable |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1  | No text in terminal tab [CRW-1570](https://issues.redhat.com/browse/CRW-1570) |
| 2  | Ability to run tests of a vscode extension on top of che-theia #18219 |
| 3 | Upgrade the golang plugin #19154 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1  |  github pr plugin: fork creation is hanging when creating a pull request #18664 |
| 2 | Unable to checkout repository to a different branch [CRW-1591](https://issues.redhat.com/browse/CRW-1591) |
| 3  | sonarlint not working on workspaces.openshift.com [CRW-604](https://issues.redhat.com/browse/CRW-1604)  |
| 4 | [vscode] window.showQuickPick canPickMany is not supported eclipse-theia/theia#5673 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Can not clone zip project on Minikube #19120 |
| 2 | SSH Upload Private Key does not work as expected #19109 |
| 3 | Cloning by `Git Clone` command should be consistent with cloning by workpsace plugin #19133 |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Unable to run task when using custom TLS certificate #18957 |
| 2 | Please provide Lombok plugin for CRW [CRW-1420](https://issues.redhat.com/browse/CRW-1420) |
| 3 | Upgrade the Java stack #19099 |
| 4 | Review devfiles and switch to multi-root workspaces, where applicable |
| 5 | A single dogfooding devfile for che-theia #18763 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW 2.7 release testing |
| 2 | Create tests for the shellcheck plugin #19163 |
| 3 | Create tests for the vale plugin #19162 |
| 4 | Create tests for the "yaml" plugin #19177  |
| 5 | Create tests for the "xml" plugin #19178 |
| 6 | Create nightly CI job for launching all plugins tests #19179 |
