### ISSUE TITLE
Simplify authentication and authorization with a more flexible and lightweight approach

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19182]
### Is your task related to a problem? Please describe.

We would like to revise the way how we do authentication and authorization in Eclipse Che.

Requirments
- Remove Keycalok dependency in general.
- On OpenShift, use OpenShift OAuth directly (do not require Keycloak or any OIDC provider)
- Every Che user should be authenticated as a Kubernetes user
- Do not deploy a component if we do not need it (OpenShift)
- Get rid of postgres for Keycloak
- Support any OIDC provider

Problems that we currently have with Keycloak:
 - Users removal (that need to be done twice on OpenShift install)
 - User registration (credentials are asked twice)
 - kubeadmin is not a valid user

### Describe the solution you'd like
Something like OAuth2 proxy looks like the ideal solution
 - We would delegate authentication to a single component (reverse proxy) that would intercept every request and authenticate them
 - It’s not OpenID, there is no guarantee to have user id and email
 - There may be some issues with Traefik

Dex, rbac-proxy and OpenShift OAuth need to be evaluated as well

### Implementation
 - [x] https://github.com/eclipse/che/issues/19192
 - [x] https://github.com/eclipse/che/issues/19196
 - [x] #19229
 - [x] OAuth2 proxy+ traefik
 - [x] #19297
 - [x] #19357
 - [x] #19358
 - [x]  https://github.com/eclipse/che/issues/19704
 - [x] https://github.com/eclipse/che/issues/19705
 - [x] https://github.com/eclipse/che/issues/19706
 - [x] #20009
 - [x] #20070
 - [x] https://github.com/eclipse/che/issues/20203
 - [x] https://github.com/eclipse/che/issues/20071
 - [x] https://github.com/eclipse/che/issues/19707
 - [x] https://github.com/eclipse/che/issues/20190
 - [ ] ~~https://github.com/eclipse/che/issues/19550~~
 - [x] https://github.com/eclipse/che/issues/19366
 - [x] ~~https://github.com/eclipse/che/issues/20362~~
 - [x] https://github.com/eclipse/che/issues/20633
 - [x] https://github.com/eclipse/che/issues/20635
 - [x] https://github.com/eclipse/che/issues/20677
 - [x] https://github.com/eclipse/che/issues/20847

### Additional context
 - https://github.com/eclipse/che/issues/18617

**Comment by skabashnyuk** [comment]
@skabashnyuk 
kube-rbac-proxy could help us. For example https://github.com/brancz/kube-rbac-proxy/tree/master/examples/oidc

@metlos according to @davidfestal  kube-rbac-proxy does "almost but not quite" do what we need... But it certainly should be a good starting point

@davidfestal Yeah, I was mainly thinking of a mix of 1. kube-rbac-proxy and 2. oauth2-proxy.
2. for integrating the UI flow (to grab the user token to then check thanks 2
1. for TokenReview and using RBAC control

**Comment by skabashnyuk** [comment]
First jumboard we have after internall call with platform team
<img width="1421" alt="Знімок екрана 2021-03-02 о 12 18 58" src="https://user-images.githubusercontent.com/1614429/109634419-e20cf700-7b51-11eb-80dd-eb45994d8549.png">
https://jamboard.google.com/d/1ez2a0m---FGkSc9Ydabd76fP6m9II_RW8CvY1sXnERQ/edit?usp=sharing

**Comment by skabashnyuk** [comment]
Second jumboard


https://jamboard.google.com/d/1_MfiHuzb5Dq6_54x2jcF9emGdMW0VUaUbiLZKEw9baE/viewer
<img width="1367" alt="Знімок екрана 2021-03-02 о 12 35 53" src="https://user-images.githubusercontent.com/1614429/109636223-fe119800-7b53-11eb-9a82-f3c750883599.png">

**Comment by sparkoo** [comment]
We have these entrypoints to Che, that has to be authenticated (considering single-host deployment with devworkspaces)
 - proxy to kubernetes API (via traefik)
 - single-host workspace endpoints (via traefik, but currently not same instance as ^)
 - subdomain workspace endpoints (completely separate routes/ingresses)

**Comment by sparkoo** [comment]
We've prepared POC on minikube for "single-host" routes. See https://github.com/che-incubator/che-auth-playground/tree/master/kubernetes for the setup:
![Kubernetes POC diagram](https://raw.githubusercontent.com/che-incubator/che-auth-playground/master/kubernetes/diagram.png)

There are some issues/unanswered questions:
 - kube-rbac-proxy "eats" the authorization header with bearer token. I've created an issue(https://github.com/brancz/kube-rbac-proxy/issues/114) and proposed the PR(https://github.com/brancz/kube-rbac-proxy/pull/115) to bypass that. Waiting for the mainainers
 - like this, each exposed port in workspace will need it's own kube-rbac-proxy instance. I think there's ~7 ports exposed in empty workspace, that would mean 7 extra containers for only empty workspace and +1 for every additional endpoint. I believe we could optimize by having only single entrypoint protected with kube-rbac-proxy and reverse-proxy behind to route to correct internal ports. Like this we would have 2 extra containers per workspace (now we have 1 - jwtproxy).
 - for subdomain routes (a.k.a. multi-host), we would either need oauth2-proxy in front of every endpoint or we will reuse current gateway to routing these as well. That would mean to create Ingress/Route in 'che' namespace and configure the traefik so it can route based by subdomains.
 - on Openshift, the only difference should be to replace oauth2-proxy with it's openshift fork (https://github.com/openshift/oauth-proxy) and leave out the Dex. Currently it's only my assumption and we need to test it https://github.com/eclipse/che/issues/19358

**Comment by sparkoo** [comment]
### Status update
#### Step 1 - Foundations
We've starting working on implementation. We're now focusing only on OpenShift with DevWorkspaces.
1. Che-server **In review** - _New che authentication support #19784_
2. Installation with che-operator **Planned next** - [che-auth] - make it possible to deploy Che with new auth #19705
3. Authorization header component **Planned next** -  [che-auth] - oauth-proxy can't put token into Authorization header #19704

After these 3 (Che 32?) we'll have an option to install Che on OpenShift without Keycloak and any OpenShift user will be able to login to Che and use DevWorkspaces (no devfile v1 support).

#### Step 2 - Workspace authentication (subpath)
We will then focus on workspace authentication. At first, we'll secure subpath endpoints ([che-auth] - secure workspace subpath endpoints in new auth gateway #19707). 

##### ❗ Concern/complication
There is one concern about this! For new authentication, we need to change the deployment of the che-gateway. Currently it's "only" routing the traffic, but with new auth it will be responsible also for authentication and authorization. 

We now have 2 che-gateways (Traefik):
  1. installed by che-operator inside `eclipse-che` namespace 
    - routing to che-server + other components like plugin/devfile registries 
    - workspaces with devfile v1
  2. installed by devworkspace-che-operator inside `devworkspace-che` namespace 
    - routing to devworkspaces

Eech gateway has it's own Route -> devworkspaces have different hostname than che-server or devfile v1 workspace. We're currently in the process of merging these 2 operators together and having only one gateway and one Route. Ideally, we would implement workspace authentication AFTER this merger is done. Otherwise we would have to implement same functionality twice (in che-operator and devworkspace-che) and it might get complicated due to different hostname and cookies path (not verified).

#### Future
  - Subdomain routes
  - Devfile v1 support
  - Kubernetes support (Dex as identity provider)

**Comment by benoitf** [comment]
moving issue to 7.42 milestone as this issue is part of the endgame

**Comment by sparkoo** [comment]
scope of this epic is complete and all issues are close. I'm closing this. Following issues/improvements will be solved in dedicated issues.
