### ISSUE TITLE
Che Controller Sprint 198

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19183]
This issue collect work items of Controller Team for Sprint 198 (3 Mar - 23 Mar)

### Finalize from the previous sprint
- [x] Implement support for async storage in controller https://github.com/devfile/devworkspace-operator/issues/267
- [x] Support factory flow for devfile v2 https://github.com/eclipse/che/issues/19147
- [x] Implement the mechanism to configure dockercfg secret as imagePullSecrets for devworkspace https://github.com/devfile/devworkspace-operator/issues/264

### Factory from private git registries
- [x] Support OAuth flow for private repo factories on Dashboard https://github.com/eclipse/che/issues/18976
:notebook: Is expected for CRW 2.8

### New dashboard finalization
- [ ] The new dashboard click party https://github.com/eclipse/che/issues/19238
- [x] Deprecate workspace-loader https://github.com/eclipse/che/issues/18785
- [x] preferred_type is not respected by dashboard (Get started only) https://github.com/eclipse/che/issues/19069
- [x] Not clear warning is displayed on Get Started & Create Custom Workspace when no more workspaces are allowed to start https://github.com/eclipse/che/issues/18589
- [x] Dashboard should propagate logs for already starting workspace https://github.com/eclipse/che/issues/19070
- [x] The action 'Open in verbose mode' is not disabled in the case with the running workspace https://github.com/eclipse/che/issues/19234
- [x] Dashboard is not handling anymore 'restart-workspace' event https://github.com/eclipse/che/issues/19174
- [x] Token is expired during workpace start process https://github.com/eclipse/che/issues/19045

### Dashboard 
- [ ] Improve devworkspaces support https://github.com/eclipse/che/issues/19184

### DevWorkspace Operator
- [x] workspace routings objects name https://github.com/devfile/devworkspace-operator/issues/161
- [x] expose component status https://github.com/devfile/devworkspace-operator/issues/261
- [x] Get rid of Che Rest API sidecar https://github.com/devfile/devworkspace-operator/issues/288
- [x] PVC clean up job is not stable https://github.com/devfile/devworkspace-operator/issues/301
- [x] Investigate: Che should propagate SelfSigned certificates and proxy settings to devworkspaces https://github.com/eclipse/che/issues/19189
- [x] Every time devworkspace operator is restarted, a new serviceaccount token is created https://github.com/devfile/devworkspace-operator/issues/199
- [x] Separate workspace routing into a separate library https://github.com/devfile/devworkspace-operator/issues/298

### DevWorkspace Client Library
- [ ] Usage of inversify inside devworkspace-client https://github.com/eclipse/che/issues/19149
- [x] Decide what features devworkspace-che-client should have https://github.com/eclipse/che/issues/19219
- [ ] provides and publish types for different languages https://github.com/devfile/api/issues/353

## Web Terminal Operator
- [ ] Fix the check on OpenShift Console to show terminal button https://issues.redhat.com/browse/WTO-20
- [x] Utilize CPaaS midstream automation https://issues.redhat.com/browse/WTO-74

## Technical debt
- [x] Migrate workpace-client build to github https://github.com/eclipse/che/issues/19076

## Unplanned
- [ ] Stop workspace doesn't work properly https://github.com/eclipse/che/issues/19307
- [x] Create Custom Workspace page crashes on click into select template edit after editing the devfile https://github.com/eclipse/che/issues/19250
- [x] Add readiness and liveness probe for controller and webhook server https://github.com/devfile/devworkspace-operator/issues/236
- [x] Dashboard should clearly indicate stopping workspace state https://github.com/eclipse/che/issues/19292
- [x] Sometimes workspace status is not updated after workspace is stopped https://github.com/eclipse/che/issues/19348
