### ISSUE TITLE
Multi-root as a default project layout in Che-Theia for simpler multi projects workspaces

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19199]
The goal of this epic is to gather and track the work towards setting the multi-root workspaces as a default project layout in Che-Theia.

### Additional context
https://www.eclipse.org/lists/che-dev/msg04068.html

##### Che 7.27
- [x] Multi-root mode is optional, can be enabled with a feature toggle in a Devfile. https://github.com/eclipse/che/issues/17212

##### Che 7.28
- [x] Multi-root is a default mode when the DevWorkspace engine is used. https://github.com/eclipse/che/issues/19191

##### Che 7.29
- [x] Multi-root is a default mode for all workspaces. It can be disabled with the feature toggle in a Devfile. https://github.com/eclipse/che/issues/19389
- [x] Adapt the HappyPath tests to the multi-root mode. https://github.com/eclipse/che/issues/19390
- [x] Enable the multi-root mode for the Devfiles in the Che Devfile Registry https://github.com/eclipse/che/issues/19375
- [x] Check single-to-multi root mode migration in Che-Theia https://github.com/eclipse/che/issues/19445
- [x] Explorer is empty after switching to `che-theia:next` https://github.com/eclipse/che/issues/19551

##### Che 7.31
- [x] Enable the multi-root mode for Go devfile https://github.com/eclipse/che/issues/19476

##### Che 7.33
- [x] Add /projects as default project when opening the IDE without any projects in the devfile https://github.com/eclipse/che/issues/19645

**Comment by RomanNikitenko** [comment]
There are issues related to the multi-root mode:
- Export launch configurations from devfile to workspace config file [#18866](https://github.com/eclipse/che/issues/18866)
- Multi-root: workspace folders auto detection [#19101](https://github.com/eclipse/che/issues/19101)
- allow to customize/provide different projects to be added in workspace root. Could be useful for a maven project to see only sub-folders/modules

If some of them looks pretty critical - we could add them to the epic.

**Comment by RomanNikitenko** [comment]
Another issue was created related to multi-root mode: https://github.com/eclipse/che/issues/19370

**Comment by RomanNikitenko** [comment]
There is a discussion in comments of the issue https://github.com/eclipse/che/issues/17975 about settings for plugins + multi-root

**Comment by azatsarynnyy** [comment]
added https://github.com/eclipse/che/issues/19445 as it's important to check before 7.29 release

**Comment by azatsarynnyy** [comment]
added https://github.com/eclipse/che/issues/19551 to fix in 7.29

**Comment by azatsarynnyy** [comment]
added https://github.com/eclipse/che/issues/19476 that needs to be fixed before [removing the temporary feature toggle](https://github.com/eclipse/che/issues/19594)

**Comment by benoitf** [comment]
hello, here is another issue I'm facing with multi-root: https://github.com/eclipse/che/issues/19645

**Comment by azatsarynnyy** [comment]
> hello, here is another issue I'm facing with multi-root: #19645

Thanks! It should be fixed in 7.32, most likely. I've updated the sub-tasks list accordingly.
Also, I've moved https://github.com/eclipse/che/issues/19594 to 7.32 as there's a couple of issues that should be fixed first.

**Comment by RomanNikitenko** [comment]
I detected one more issue: https://github.com/eclipse/che/issues/19730

**Comment by l0rd** [comment]
@azatsarynnyy I don't think we need #19594 to be in this epic (i.e. we can close the epic once #19645 is solved)

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy I don't think we need #19594 to be in this epic (i.e. we can close the epic once #19645 is solved)

@l0rd I agree, removed

**Comment by azatsarynnyy** [comment]
All sub-tasks are done. So, I'm closing the epic.
