### ISSUE TITLE
Che Platform Sprint 198

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19197]
#### Timeframe
Mar. 3 - Mar.  23

#### Team
| Name  | 
| ------------- |
| @sparkoo   | 
| @metlos   |  
| @mshaposhnik   |
| @xbaran4   |   
| @skabashnyuk  |  

#### Holidays / events:
- Mar 12th Hack 'n' Hustle
- Mar 8th International Women's Day (day off in Ukraine)

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x

---

###  Gitlab

- [x] Gitlab public repo support in factory URL | https://github.com/eclipse/che/issues/19169
- [ ] Gitlab private repo support in factory URL using personal access tokens | https://github.com/eclipse/che/issues/19170

### Devworkspaces

- [x] [devworkspace-che] Honor endpoints declaring their support for singlehost | https://github.com/eclipse/che/issues/19008
- [x]  Che Operator should be able to install the Devworkspace che operator | https://github.com/eclipse/che/issues/19142
- [x] Che Server should tell Dashboard if DevWorkspaces are supported or not | https://github.com/eclipse/che/issues/19160

### Authentication and authorization in Eclipse Che 

- [x] Create test application for authentication/authorization prototyping | https://github.com/eclipse/che/issues/19192
- [x] Minikube + OIDC+DEX+rbac | https://github.com/eclipse/che/issues/19196

### Docs/Tehnocal debt/bugs
- [x] [che-docs] config properties without inline doc has wrong description | https://github.com/eclipse/che/issues/18572
- [x] Remove implementation details from Admin Guide | https://github.com/eclipse/che/issues/17266

### Unplenned 
 - [x] [devworkspace-che] Build consolidation https://github.com/eclipse/che/issues/19286
 - [ ] [Che auth] - setup kube-rbac-proxy with demo app   https://github.com/eclipse/che/issues/19297
 - [ ] Document how to use private container registries in Che https://github.com/eclipse/che/issues/19104
