### ISSUE TITLE
Enable community devfiles and plugins in Dev Sandbox

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19271]
### Is your enhancement related to a problem? Please describe.

Currently there is no way to offer community devfiles and plugins in Dev Sandbox without shipping those devfiles/plugins with CRW directly. Of course that's not really an option, because the maintenance burden is too high and it would be a big duplication of work.

### Describe the solution you'd like

Instead, we can provide an upstream offering of devfiles and plugins by adding metadata to devfiles (such as tags like `upstream` or `community`), as well as `registryUrl` fields within those devfiles that point to a published version of the upstream che-plugin-registry. The `registryUrl` fields would ensure that the upstream/community devfiles are only using upstream plugins, and thus avoiding conflicts with downstream plugins that have the same `id`.

New functionality in the dashboard would enable filtering on the `Getting Started` page, so that Dev Sandbox users could toggle between upstream/community devfiles, and more stable Red Hat supported ones.

Eventually we can also extend this system to filter out devfiles based on other metadata sets, such as:
* devfiles which are only available on certain architectures (part of #19239)
* devfiles which are not airgap friendly
* devfiles which target a certain language/area of interest

### Describe alternatives you've considered

N/A

### Additional context
Here is a list of the upstream issues which need to completed, in order, for this epic:
* [x] Publish a versioned che-plugin-registry release to surge.sh #19268
* [x] Add registryUrls in the devfile registry #19269

There is also a downstream ticket for this epic: https://issues.redhat.com/browse/CRW-1437

**Comment by gattytto** [comment]
I like this because it can be as cutting edge as possible, for instance: use the chectl fetching method to get the latest url from a file in some other fixed url. Use a ddns-like process to populate the file with the dependabot pr-test builds if they are succesfull.

**Comment by deboer-tim** [comment]
Other tools (e.g. odo, ODC) will eventually have the same need, so I would prefer to solve this in a common place (e.g. via the devfile registry library) or with common patterns. A similar requirement is an enterprise wanting to add their own registry without removing the default registry.

IMHO the pattern for this should be as simple as adding a second registry URL as you do in odo today, and the registry name (e.g. Community) can be shown in the UI and gives you something to filter by.

I agree architecture or other filtering can be done via tags, but since that issue exists even with a single registry I would handle it as two separate issues.

**Comment by ericwill** [comment]
I believe we have rudimentary support for this: https://github.com/eclipse/che/issues/13961

From the PR:
This PR allows multiple devfile registries to be specified as a space separated list, for example in values.yml we can have:
```yaml
che: 
  workspace: 
    devfileRegistryUrl: "https://che-devfile-registry.openshift.io/ https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/"
```
The registry location is then stored so that the devfile can be read from the correct location.

**Comment by ibuziuk** [comment]
@ericwill do we have multiple-registries feature documented in the official docs, also wondering if it will work for the single-host setup

**Comment by ibuziuk** [comment]
cc: @sleshchenko @akurinnoy my understanding that https://github.com/eclipse-che/che-dashboard/pull/5 is UD specific feature, right?

**Comment by ibuziuk** [comment]
We are ready to roll out the initial support of the community devfiles to workspaces.openshift.com:

Doc PR - https://github.com/eclipse/che-docs/pull/1986
Follow up issues for improving the overall flow and UX

 - https://github.com/eclipse/che/issues/19781
 - https://github.com/eclipse/che/issues/19633

**Comment by ibuziuk** [comment]
@ericwill looks like there is a problem with workspace restarts based on the community devfiles - https://github.com/eclipse/che/issues/19829
Please take a look

**Comment by l0rd** [comment]
I am closing this epic since we have community devfiles and plugin on Devsandbox. Removing the 2 remaining issues from the description:

* [ ] Add metadata to devfiles #18473
* [ ] Filter out devfiles from the dashboard based on metadata tags #19270

**Comment by ericwill** [comment]
> I am closing this epic since we have community devfiles and plugin on Devsandbox. Removing the 2 remaining issues from the description:
> 
>     * [ ]  Add metadata to devfiles #18473
> 
>     * [ ]  Filter out devfiles from the dashboard based on metadata tags #19270

Why? What we have now is the bare minimum and from a usability POV it's not great. One of the main points of this epic was to introduce the filtering system as well.
