### ISSUE TITLE
Editors Sprint 199

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19319]
Mar 24 - Apr 13

---
#### First-class support for IntelliJ-based Che Editor
- [x] Investigate if Projector-based IntelliJ Che editor provides some benefits comparing to openVNC we have now https://github.com/eclipse/che/issues/18619

#### Multi-root workspaces as a default project layout in Che-Theia https://github.com/eclipse/che/issues/19199
- [x] Multi-root is a default mode for all workspaces https://github.com/eclipse/che/issues/19389
- [x] Adapt the HappyPath tests to the multi-root mode https://github.com/eclipse/che/issues/19390
- [ ] Launch configurations are not available for running https://github.com/eclipse-theia/theia/issues/8987
- [ ] Export launch configurations from devfile to workspace config file https://github.com/eclipse/che/issues/18866

#### DevWorkspace
- [ ] Che-Theia should detect and apply local devfile changes https://github.com/eclipse/che/issues/18670

#### Theia APIs
- [x] Implement `vscode.ExtensionContext.storageUri` API https://github.com/eclipse-theia/theia/issues/8883

#### Other tasks
- [x] Migrate Che-Theia to eclipse-che GitHub organization https://github.com/eclipse/che/issues/19391
- [x] Dashboard-next click party https://github.com/eclipse/che/issues/19238
---
### Unplanned/Blockers
- [x] Check single-to-multi root mode migration in Che-Theia https://github.com/eclipse/che/issues/19445
- [x] Error launching task in IDE: Error starting process (ENOENT) https://github.com/eclipse/che/issues/19528
- [x] Explorer is empty after switching to `che-theia:next` https://github.com/eclipse/che/issues/19551

---
## Team
| Name  |
| -- |
| @vzhukovs |
| @RomanNikitenko |
| @azatsarynnyy |

---
[Previous Sprint](https://github.com/eclipse/che/issues/19146)
