### ISSUE TITLE
Plugins Sprint 199

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19331]
## Sprint 199 (March 24th 2021 - April 13th 2021)
This sprint will result in the release of Che 7.29.

### Epics
* [ ] Investigate the ability of adding of public key to Bitbucket and GitLab #19186 @vitaliy-guliy 
* [ ] Enable community devfiles and plugins in Dev Sandbox #19271
    * [ ] Add registryUrls in the devfile registry #19269 @ericwill 
    * [x] Publish a versioned che-plugin-registry release to surge.sh #19268 @ericwill 

### CRW
* [x] Please provide Lombok support for CRW [CRW-1420](https://issues.redhat.com/browse/CRW-1420) @sunix 
    * [x] Add downstream devfile
* [x] ("Quarkus" workspace) Debug stops at the breakpoint only if breakpoint set up during debug session [CRW-1543](https://issues.redhat.com/browse/CRW-1543) @svor 
* [x] Add resource limits/requests to the devfiles and plugins in the registries [CRW-1637](https://issues.redhat.com/browse/CRW-1637) @vitaliy-guliy 
* [ ] Resource Monitor plugin cannot get access to workspace pod [CRW-1649](https://issues.redhat.com/browse/CRW-1649) @svor 
    * [ ] Resources Monitor Plugin doesn't have enough permissions to read Pod information on Hosted Che #18812
* [x] The "Install dependencies" command fails in the "PHP-DI" workspace [CRW-1335](https://issues.redhat.com/browse/CRW-1335) @sunix 
* [ ] Support upstream plugin update automation in CRW [CRW-1648](https://issues.redhat.com/browse/CRW-1648) @ericwill 

### Bugs
* [ ] SonarLint plugin issue with SonarQube Connected Mode #17980 @vinokurig 
* [x] Command "Generate JWT auth secret key" failing in PHP Laravel with MySQL devfile #18441 @vinokurig 
* [ ] Cloning by `Git Clone` command should be consistent with cloning by workpsace plugin #19133 @vitaliy-guliy 
* [ ] Git cloning fails in a proxy environment #19242 @vitaliy-guliy 
* [x] Quarkus CLI run native fails with missing binary #18982 @sunix 
* [x] `PluginContext.globalStorage" broken in self-hosting context. #18056 @tsmaeder 
* [x] "Circular struture" errors when accepting "current change" #18921 @tsmaeder 
* [ ] The "shellcheck" plugin doesn't work #19376 @tsmaeder 

### Enhancements
* [x] FR: Set extension settings from plugins meta.yaml #17975 @sunix 
    * [x] Add settings to `che-theia-plugins.yaml`
    * [x] Remove any entrypoint hacks that currently exist
    * [x] Investigate settings from devfiles and see which ones can be enabled by default in the plugin registry
* [x] Explicitly enable/disable multi-root in devfiles of che-devfile-registry #19375 @sunix 

### QE
* [x] Create nightly CI job for launching all plugins tests #19179 @Ohrimenko1988 
* [x] Create PR check for the "che-plugin-registry" repository using the openshift CI #19320 @Ohrimenko1988
* [x] Create E2E test for checking the "Java11" plugin #19437 @Ohrimenko1988 
* [x] Create E2E test for checking the "python" plugin #19439 @Ohrimenko1988 
* [x] Create E2E test for checking the "typescript" plugin #19438 @Ohrimenko1988 

### Devfile 2.0
* [ ] Try Che with new workspace engine
* [ ] Che editors should be defined using Devfile v2 syntax #19034 @vinokurig 

### Unplanned
* [x] Workspace panel actions are not working #19441
* [ ] Plugins list is empty in CRW deployed in proxied environment [CRW-1710](https://issues.redhat.com/browse/CRW-1710) @vinokurig 

### Open PRs From Last Sprint
* [x] Document upstream plugin registry changes eclipse/che-docs#1917
* [x] SSH Upload Private Key does not work as expected #19109

#### Automation / Tests
* [ ] Ability to run tests of a vscode extension on top of che-theia #18219 @svor 
    * [ ] [plugins] Cannot read property 'getExtension' of vscode.extensions #19172
* [x] Improve vscode-extensions builder to work independently of extension.json changes #19134 @ericwill 
* [ ]  Enable telemetry support in the che-plugin-registry #19361  @vinokurig 

#### Maintenance
* [x] vale plug-in: update vale to the latest version #19289 @vinokurig 
* [x] Migrate the che-plugin-registry to the eclipse-che organization #19387 @ericwill 
* [x] Migrate che-devfile-registry to the eclipse-che organization #19388 @ericwill 

#### Dogfooding, Developer Experience, or UX Improvements
* [ ] Try free-omnisharp-vscode extension as an alternative of omnisharp-theia-plugin and netcoredbg-theia-plugin #19306 @svor 
* [ ] Rework che-theia build process to not use source linking #16852 @tsmaeder 
* [x] Dashboard-next click party

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 15  | 8 |
| @vinokurig  | 15  | 8 |
| @ericwill | 12 | 9 |
| @tsmaeder | 13 | 9 |
| @svor | 13 | 8 |
| @sunix | 13 | 9 |
| @Ohrimenko1988 | 15 | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Support upstream plugin update automation in CRW [CRW-1648](https://issues.redhat.com/browse/CRW-1648) |
| 2 | Add registryUrls in the devfile registry #19269 |
| 3 |  Publish a versioned che-plugin-registry release to surge.sh #19268 |
| 4 | Investigate migrating to eclipse-che organization |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1  |  "Circular struture" errors when accepting "current change" #18921 |
| 2 | Rework che-theia build process to not use source linking #16852 |
| 3 | The "shellcheck" plugin doesn't work #19376 | 
| 4 | `PluginContext.globalStorage" broken in self-hosting context. #18056 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1  | ("Quarkus" workspace) Debug stops at the breakpoint only if breakpoint set up during debug session [CRW-1543](https://issues.redhat.com/browse/CRW-1543) |
| 2  | Resources Monitor Plugin doesn't have enough permissions to read Pod information on Hosted Che #18812 |
| 3 | Ability to run tests of a vscode extension on top of che-theia #18219 |
| 4 | Try free-omnisharp-vscode extension as an alternative of omnisharp-theia-plugin and netcoredbg-theia-plugin #19306 | 

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Che editors should be defined using Devfile v2 syntax #19034 |
| 2 | SonarLint plugin issue with SonarQube Connected Mode #17980 |
| 3 | Command "Generate JWT auth secret key" failing in PHP Laravel with MySQL devfile #18441 |
| 4  | vale plug-in: update vale to the latest version #19289  |
| 5 |  Enable telemetry support in the che-plugin-registry #19361 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Cloning by `Git Clone` command should be consistent with cloning by workpsace plugin #19133 |
| 2 | Git cloning fails in a proxy environment #19242 |
| 3 | Add resource limits/requests to the devfiles and plugins in the registries [CRW-1637](https://issues.redhat.com/browse/CRW-1637) |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Explicitly enable/disable multi-root in devfiles of che-devfile-registry #19375 |
| 2 | FR: Set extension settings from plugins meta.yaml #17975 |
| 3 | The "Install dependencies" command fails in the "PHP-DI" workspace [CRW-1335](https://issues.redhat.com/browse/CRW-1335) |
| 4 | Quarkus CLI run native fails with missing binary #18982 |
| 5 | Please provide Lombok support for CRW [CRW-1420](https://issues.redhat.com/browse/CRW-1420) |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Create nightly CI job for launching all plugins tests #19179 |
| 2 | Create PR check for the "che-plugin-registry" repository using the openshift CI #19320 |
| 3 | Create E2E test for checking the "Java11" plugin #19437 |
| 4 | Create E2E test for checking the "python" plugin #19439 |
| 5 | Create E2E test for checking the "typescript" plugin #19438 |

**Comment by ericwill** [comment]
Superseded by #19548
