### ISSUE TITLE
Create v2 devfiles for Getting Started samples

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19341]
### Is your enhancement related to a problem? Please describe.

One of the sub-epics of [Run Che workspaces using the DevWorkspace operator](https://github.com/eclipse/che/issues/17307) is to switch our samples from a v1 to v2 based devfiles. 

### Describe the solution you'd like

- Add v2 devfiles in our samples git repositories
- Implement a new "project samples" registry, alternative to the devfile registry
- Add a installation parameter to switch between devfile and sample registry as the source of the getting started samples
- Adapt tests to use devfile v2 based Getting Started samples

Related to https://github.com/eclipse/che/issues/18666

### Further details

A simple devfile v2 is the one available [here](https://github.com/l0rd/spring-petclinic/blob/devfile2/devfile.yaml). 
We should use `schemaVersion: 2.1.0`  rather than `schemaVersion: 2.0.0` ([che-server support for it](https://github.com/eclipse/che/issues/19304))
and the [full updated reference is here](https://docs.devfile.io/devfile/2.1.0/user-guide/api-reference.html). 

### Subtasks

- [x] Add v2.1 devfiles, .che/che-theia-plugins.yaml, .che/che-editor in our samples git repositories (Florent's note: I think we should use .vscode/extension.json for almost all devfiles)
    - [x] done for one example there: https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
- [x] Create a sample registry (metadata) https://github.com/eclipse/che/issues/19906
	- devfile registry update to include this new service
	- dashboard update to support it
- [x] If devworkspace is deployed, dashboard should use the sample registry https://github.com/eclipse/che/issues/19923
- [ ] Adapt QE tests https://github.com/eclipse/che/issues/20913

**Comment by l0rd** [comment]
Moving it out of scope of STEP 2 of the devworkspace work as we won't be able to create all the samples devfiles. That will be postponed to STEP 3 and we need to discuss if we need to update the devfile samples.

**Comment by svor** [comment]
| Status  | Name | Sample |
| ------------- | ------------- | ------------- |
| :heavy_check_mark:  | quarkus | https://github.com/quarkusio/quarkus-quickstarts |
| :heavy_check_mark:  | java-web-spring | https://github.com/che-samples/java-spring-petclinic |
| :heavy_check_mark:  | nodejs-mongo | https://github.com/che-samples/nodejs-mongodb-sample |
| :heavy_check_mark:  | nodejs | https://github.com/che-samples/web-nodejs-sample |
| :heavy_check_mark:  | python | https://github.com/che-samples/python-hello-world |
| :heavy_check_mark:  | python-django | https://github.com/che-samples/django-realworld-example-app |
| :running:  | go | https://github.com/che-samples/golang-example, https://github.com/che-samples/golang-echo-example |
| :running:  | java-mongo | https://github.com/che-samples/java-guestbook |
|   | apache-camel-k |  |
|   | apache-camel-springboot |  |
|   | bash |  |
|   | che4z |  |
|   | cpp |  |
|   | dotnet |  |
|   | dotnet-asp.net |  |
|   | java-gradle |  |
|   | java-maven |  |
|   | java-mysql |  |
|   | java-web-vertx |  |
|   | nodejs-angular |  |
|   | nodejs-react |  |
|   | nodejs-yarn |  |
|   | php-laravel |  |
|   | php-mysql |  |
|   | php-symfony |  |
|   | php-web-simple |  |
|   | quarkus-command-mode |  |
|   | rust |  |
|   | scala-sbt |  |

**Comment by max-cx** [comment]
Hi, a question to the assignee of this issue:

Will the outcome require any changes to the relevant content of the _Installation Guide_ or _Administration Guide_ or _End-user Guide_?

Yes/No?

**Comment by svor** [comment]
I'm going to close this issue. The following tasks were created:
- Migrate che4z devfile #20950 
- Migrate E2E devfile tests from v1 to v2 #20913
