### ISSUE TITLE
Che Deploy Sprint #199

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19364]
#### Timeframe
Mar. 24 - Apr.  13

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays / events:
- Apr. 1-2 Good Friday Holiday in Spain
- Apr. 2 Hack 'n' Hustle

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x

---
### Eclipse Che issues 
- [ ] Run DWCO and CO in a different containers https://github.com/eclipse/che/issues/19402
  - [ ] https://github.com/eclipse-che/che-operator/pull/745
- [ ] [che-operator] Provides the ability to create backups/restore https://github.com/eclipse/che/issues/18703
- [ ] Theia terminal extension must propagate error from che-machine-exec https://github.com/eclipse/che/issues/16593
- [x] .[che-operator] garbage collect cluster-scoped objects https://github.com/eclipse/che/issues/18501
  - [x] https://github.com/che-incubator/chectl/pull/1148
- [x] .chectl update test fails in release PR https://github.com/eclipse/che/issues/19212
  - [x] https://github.com/che-incubator/chectl/pull/1147
- [x] .server:delete shouldn't fail if some resource doesn't exist https://github.com/eclipse/che/issues/19241
  - [x] https://github.com/che-incubator/chectl/pull/1161
- [x] .[che-operator] Check if a new nightly bundle version is greater then a latest one https://github.com/eclipse/che/issues/19288
  - [x] https://github.com/eclipse-che/che-operator/pull/750
- [x] .Increase default size of the persistent volume claim for workspaces https://github.com/eclipse/che/issues/19314
  - [x] https://github.com/eclipse-che/che-operator/pull/739
- [x] .Change default of chectl/che-operator in case of DevWorkspace https://github.com/eclipse/che/issues/19218
  - [x] https://github.com/eclipse-che/che-operator/pull/731
  - [x] https://github.com/che-incubator/chectl/pull/1165
  - [x] https://github.com/eclipse-che/che-operator/pull/766
  - [x] https://github.com/eclipse-che/che-operator/pull/765
- [x] .Download links for chectl is broken sometimes https://github.com/eclipse/che/issues/19321
  - [x] https://github.com/che-incubator/chectl/pull/1162
- [ ] Deploying Eclipse Che on v6-only kubernetes cluster https://github.com/eclipse/che/issues/19279
- [ ] Allow localhost as redirect URL for keycloak authentication https://github.com/eclipse/che/issues/19158
---
### PR to merge
- [ ] update to traefik 2.3.2 and use copy from quay (not dockerhub) to avoid rate limiting https://github.com/eclipse/che/issues/19431
  - [ ] https://github.com/eclipse/che/pull/19553
  - [ ] https://github.com/eclipse-che/che-operator/pull/767
- [x] .We need apply code format check for che-operator https://github.com/eclipse/che/issues/18042
    - [x] https://github.com/eclipse-che/che-operator/pull/762
- [x] .Operator displays successful upgrade but is not upgraded; too many characters in name https://github.com/eclipse/che/issues/19506
  - [x] https://github.com/eclipse-che/che-operator/pull/756
- [x] .chectl server:deploy raise error https://github.com/eclipse/che/issues/19165
  - [x] https://github.com/che-incubator/chectl/pull/1166
- [x] Install olm 0.17 version instead off minikube olm addon https://github.com/eclipse-che/che-operator/pull/744
- [x] Use eclipse-che namespace as default namespace for login https://github.com/che-incubator/chectl/pull/1139
- [x] Code clean up part 1 https://github.com/eclipse-che/che-operator/pull/730
- [x] Code clean up part 2 https://github.com/eclipse-che/che-operator/pull/736
- [x] Code clean up part 3 https://github.com/eclipse-che/che-operator/pull/753
- [ ] Code clean up part 4 https://github.com/eclipse-che/che-operator/pull/761
---
### Unplanned
---
 [Previous Sprint](https://github.com/eclipse/che/issues/19155)
