### ISSUE TITLE
Che Controller Sprint 199

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19374]
This issue collect work items of Controller Team for Sprint 198 (24 Mar - 13 Apr).

The previous sprint https://github.com/eclipse/che/issues/19183

## Finalize from the previous sprint
- [x] Improve WebTerminal Operator detection made by OpenShift Console [WTO-20](https://issues.redhat.com/browse/WTO-20)
- [x] Finalize workspace -> devworkspace renaming https://github.com/devfile/devworkspace-operator/issues/321
- [x] provides and publish types for different languages [devfile/api#353](https://github.com/devfile/api/issues/353)
- [x] The new dashboard click party [eclipse/che#19238](https://github.com/eclipse/che/issues/19238)
- [x] Adapt + port flatten library to devfile/api side [devfile/devworkspace-operator#334](https://github.com/devfile/devworkspace-operator/issues/334)

## DevWorkspace Operator
- [x] Trying to stop a DevWorkspace make it restart https://github.com/eclipse/che/issues/19369
- [ ] Projects clone should happen before other components are started https://github.com/devfile/devworkspace-operator/issues/205
- [x] DevWorkspace should have a dedicated phase for terminating https://github.com/devfile/devworkspace-operator/issues/333
- [ ] Get rid of CHE_API and CHE_API_EXTERNAL https://github.com/devfile/devworkspace-operator/issues/344
- [x] Support setting condition status to 'false' https://github.com/devfile/devworkspace-operator/issues/337

## DevWorkspace TS Client
- [x] Usage of inversify inside devworkspace-client [eclipse/che#19149](https://github.com/eclipse/che/issues/19149)
- [x] Wrong error is reported when DevWorkspace did not get IDE url quickly [eclipse/che#19325](https://github.com/eclipse/che/issues/19325)
- [x] DevWorkspace Client should expand / explain error message if present, rather than top level (unhelpful) error 409 [eclipse/che#19323](https://github.com/eclipse/che/issues/19323)
- [x] DevWorkspaceTemplates are left on the cluster after devworkspace is removed [eclipse/che#19328](https://github.com/eclipse/che/issues/19328)
- [x] Refactor devworkspace client where Che and DevWorkspace logic are separate interfaces [eclipse/che#19382](https://github.com/eclipse/che/issues/19382)

### DevWorkspace Support
- [x] [UD] improve devworkspaces support [eclipse/che#19184](https://github.com/eclipse/che/issues/19184)
- [ ] Finalizing devworkspaces should be displayed finalization is done (don't vanish until it's actually gone) [eclipse/che#19324](https://github.com/eclipse/che/issues/19324)
- [ ] Feature request: Devfile v2 editor in Dashboard [eclipse/che#19330](https://github.com/eclipse/che/issues/19330)
- [ ] Dashboard should better expose workspace startup phase [eclipse/che#19327](https://github.com/eclipse/che/issues/19327)

### Other improvements
- [x] [UD] should have a simple way to stop a workspace [eclipse/che#19072](https://github.com/eclipse/che/issues/19072)
- [x] Restyle left-nav bar and masthead [eclipse/che#18980](https://github.com/eclipse/che/issues/18980)
- [ ] Move dashboard out of che server container [eclipse/che#17802](https://github.com/eclipse/che/issues/17802)

## WTO
- [ ] Develop a plan regards web terminal plugin version [WTO-65](https://issues.redhat.com/browse/WTO-65)
- [x] Unable to open a terminal when K8s component needs to update terminal's pod [WTO-75](https://issues.redhat.com/browse/WTO-75)

## Unplanned

- [x] Nightly single user Che is broken [eclipse/che#19403](https://github.com/eclipse/che/issues/19403)
- [x] Clean up workspace resources when a workspace fails https://github.com/devfile/devworkspace-operator/issues/338
- [ ] DevWorkspace should be failed when its pod has CrashLoopBackOff status https://github.com/devfile/devworkspace-operator/issues/353
- [x] Fix the name of the Get Started Page button in the Che Dashboard https://github.com/eclipse/che/issues/19412
- [x] Several stoped workspaces created if you click several times in samples workspace https://github.com/eclipse/che/issues/19248
- [x] Dashboard devfile editor: Autocompletion for plugin's id doesn't work https://github.com/eclipse/che/issues/19423
