### ISSUE TITLE
Che Platform Sprint 199

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19383]
#### Timeframe
Mar. 24 - Apr.  13

#### Team
| Name  | 
| ------------- |
| @sparkoo   | 
| @metlos   |  
| @mshaposhnik   |
| @xbaran4   |   
| @skabashnyuk  |  

#### Holidays / events:
- Apr. 2 Hack 'n' Hustle/ Good Friday (Cz day off)
- Apr 5 Easter Monday (Cz day off)

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x

---

###  GitLab

- [x] Gitlab private repo support in factory URL using personal access tokens | https://github.com/eclipse/che/issues/19170
- [ ] Gitlab private repo support using OAuth 2 flow | https://github.com/eclipse/che/issues/19171

###  Bitbucket
- [ ] Improve workflow when a user denies Bitbucket access for Che | https://github.com/eclipse/che/issues/19274
- [ ] The default devfile is resolved from private bitbucket repo after access token is revoked | https://github.com/eclipse/che/issues/19273

### Devworkspaces

- [x] Che Server should include JSON schema for devfile 2.1.0-alpha | https://github.com/eclipse/che/issues/19304
- [x] [devworkspace-che] Http endpoints handled incorrectly under gateway https://github.com/eclipse/che/issues/19393
- [ ] [devworkspace-che] Support custom certificates for gateway and workspace endpoints https://github.com/eclipse/che/issues/19394

### Authentication and authorization in Eclipse Che 

- [x] End to end deployement kube+OIDC+dex+oauth2_proxy+rbac_proxy+demo app | https://github.com/eclipse/che/issues/19357

### Docs/Tehnocal debt/bugs
- [x] Document how to use private container registries in Che | https://github.com/eclipse/che/issues/19104
- [x] Deprecate namespace strategies other than "per user" | https://github.com/eclipse/che/issues/19365

### Unplanned
 -  [ ]  [che-auth] Setup full che-like auth flow on Openshift https://github.com/eclipse/che/issues/19358
