### ISSUE TITLE
Migrate Che-Theia to `eclipse-che` GitHub organization

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19391]
### Is your task related to a problem? Please describe.
We've noticed that running the GitHub Workflows on Che-Theia repository takes a much longer time last few weeks. Most likely, it's due to a [shared queue](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits) for `eclipse` organization on GitHub.

### Describe the solution you'd like
Migrate [Che-Theia repository](https://github.com/eclipse/che-theia) from `eclipse` GitHub organization to `eclipse-che` org.

### Sub-tasks
- [x] Add a request to
   - https://bugs.eclipse.org/bugs/show_bug.cgi?id=571958
- [x] invite Che-Theia contributors who have the expired invitation to the new organization
   - https://bugs.eclipse.org/bugs/show_bug.cgi?id=570816
- [x] Notify people on che-dev ML
- [x] Notify QE team to setup the Happy Path PR check to a new repository
- [x] Notify Prod team to update some release scripts
- [x] Update the repository location in https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml
   - https://github.com/eclipse/che-plugin-registry/pull/906
- [x] Replace `eclipse` organization occurrences with `eclipse-che` in Che-Theia sources
   - https://github.com/eclipse-che/che-theia/pull/1054
   - https://github.com/eclipse-che/che-theia/pull/1057
- [x] Update https://github.com/eclipse/che/blob/master/.repositories.yaml
   - https://github.com/eclipse/che/pull/19432

**Comment by flacatus** [comment]
Hi @azatsarynnyy !
Deploy team already migrate repos to new organization. Please use our bugzilla to migrate to avoid creating separate Bugzilla issues for each repo migration.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=571958

**Comment by azatsarynnyy** [comment]
Thank you @flacatus for the bugzilla link!

**Comment by azatsarynnyy** [comment]
All the sub-tasks are done \o/
