### ISSUE TITLE
Use CheCluster v2alpha1 as devworkspace che configuration

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#19448]
We need to use conversion webhooks and start storing a v2alpha1 version of the `CheCluster` that would have the old che7 configuration stashed under `spec.che7` and devworkspace config properties directly under spec. This way, the che operator and devworkspace che operator could react to this new version and one would just read the spec from under che7 and continue normally as we do at the moment and the other would read the dw configuration and apply it to devworkspaces.

Disallowing more instances of CheCluster is a matter of checking the cluster state during reconciliation.

This needs to be implemented in the following order:
- [ ] Define `v2alpha1` of `CheCluster` (#19449)
- [ ] Start using `CheCluster` `v2alpha1` in DWCO (#19450)
- [ ] Implement a conversion webhook to convert `CheCluster` `v1` into `CheCluster` `v2alpha1` (#19451)
- [ ] Start handling `CheCluster` `v2alpha1` in the che-operator (#19453)
- [ ] Use `v2alpha1` as the storage version of `CheCluster`

**Comment by metlos** [comment]
This is superseded by #19845. Once we get to the point where we need to define the new CR version, we can revisit this issue or create a new one.
