### ISSUE TITLE
Che Deploy Sprint #200

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19539]
#### Timeframe
Apr. 14 -  May.  4

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays / events:
- Apr. 23 Hack 'n' Hustle
- May 3,4 Ukraine Holidays
- Apr 12-19 @AndrienkoAleksandr vacation

#### CRW releases
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x

---
### CRW issues
- [x] .Switch to apiextensions.k8s.io/v1 CRD version https://github.com/eclipse/che/issues/19460
- [x] .Drop support for OCP 4.5 & v1beta1 API / switch to 4.6+ & v1 API https://issues.redhat.com/browse/CRW-1720
  - [x] https://github.com/che-incubator/chectl/pull/1177
  - [x] https://github.com/che-incubator/chectl/pull/1183
  - [x] https://github.com/che-incubator/devworkspace-che-operator/pull/40
  - [x] https://github.com/eclipse-che/che-operator/pull/788
  - [x] https://github.com/che-incubator/chectl/pull/1185
  - [x] https://github.com/eclipse-che/che-operator/pull/768
  - [x] https://github.com/eclipse/che-docs/pull/1961
---
### Eclipse Che issues 
- [ ] [che-operator] Provides the ability to create backups/restore https://github.com/eclipse/che/issues/18703
- [ ] Run DWCO and CO in single pod but different containers https://github.com/eclipse/che/issues/19402
  - [ ] https://github.com/eclipse-che/che-operator/pull/745
  - [x] https://github.com/che-incubator/chectl/pull/1197
- [ ] Update operator-sdk to the latest version https://github.com/eclipse/che/issues/19466
- [x] .Failed to update che-operator on OCP 4.8 https://github.com/eclipse/che/issues/19436
  - [x] https://github.com/eclipse-che/che-operator/pull/776
- [x] .Failed to deploy DWO https://github.com/eclipse/che/issues/19569
  - [x] https://github.com/eclipse-che/che-operator/pull/789
- [x] .Che on OpenShift is not able to label namespace due to lack of permissions https://github.com/eclipse/che/issues/19401 https://github.com/eclipse/che/issues/18544 
  - [x] https://github.com/eclipse-che/che-operator/pull/772
- [x] .Put OpenShift initial user credentials for HTPasswd identity provider in openshift-config namespace https://github.com/eclipse/che/issues/19380
  - [x] https://github.com/eclipse-che/che-operator/pull/769
  - [x] https://github.com/che-incubator/chectl/pull/1184
  - [x] https://github.com/eclipse/che-docs/pull/1964
- [x] .Rework cheHostTLSSecret usage https://github.com/eclipse/che/issues/19381
- [ ] Update go-client libs for che-machine-exec https://github.com/eclipse/che/issues/17874
- [ ] Theia terminal extension must propagate error from che-machine-exec https://github.com/eclipse/che/issues/16593
- [x] .Switch che-operator and che-machine-exec from master to main branch https://github.com/eclipse/che/issues/19410
  - [x] https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863
  - [x] https://github.com/eclipse-che/che-operator/pull/784
  - [x] https://github.com/che-incubator/chectl/pull/1181
  - [x] https://github.com/eclipse-che/che-machine-exec/pull/150
  - [x] https://github.com/openshift/release/pull/17773
  - [x] https://github.com/openshift/release/pull/17793
  - [x] https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/474
- [ ] Create tests to run Eclipse Che in OCP Disconnected Environment https://github.com/eclipse/che/issues/19534
- [x] .chectl Minishift e2e tests failed https://github.com/eclipse/che/issues/19454
  - [x] https://github.com/eclipse-che/che-operator/pull/794
  - [x] https://github.com/che-incubator/chectl/pull/1194
- [ ] ~~Add ability to provide content for patching che-operator / helm charts deployments directly in the command line https://github.com/eclipse/che/issues/18324~~
- [x] .update to traefik 2.3.2 and use copy from quay (not dockerhub) to avoid rate limiting https://github.com/eclipse/che/issues/19431
  - [x] https://github.com/eclipse/che/pull/19553
  - [x] https://github.com/eclipse-che/che-operator/pull/767
- [x] .Don't fail on version comparison https://github.com/eclipse/che/issues/19562
  - [x] https://github.com/che-incubator/chectl/pull/1175

---
### Unplanned
- [x] Chectl should respect dashboard deployment https://github.com/eclipse/che/issues/19605
  - [x] https://github.com/che-incubator/chectl/pull/1201
  - [x] https://github.com/eclipse-che/che-operator/pull/805
- [x] 7.29.0 InstallPlan failure using community operatorhub installplan and external keycloak https://github.com/eclipse/che/issues/19670
  - [x] https://github.com/eclipse-che/che-operator/pull/800
- [x] .Happy path test on CRW CI failed on Start Che because chectl:next doesn't support minikube
https://github.com/eclipse/che/issues/19648
  - [x] https://github.com/che-incubator/chectl/pull/1193
- [x] .Refactor workflows https://github.com/eclipse-che/che-operator/pull/792
- [x] .Installs stable olm v0.17.0 for tests in GitHub actions https://github.com/che-incubator/chectl/pull/1187
- [x] .Make happy path tests to use latest templates from PR https://github.com/eclipse-che/che-operator/pull/791
- [x] .Run dashboard as separate deployment https://github.com/eclipse-che/che-operator/pull/684
- [x] .Use minikube 1.18.1 in github actions 
  - [x] https://github.com/eclipse-che/che-operator/pull/780
  - [x] https://github.com/che-incubator/chectl/pull/1180
- [x] .Backport dwo installation removal after delegate in che operator https://github.com/che-incubator/chectl/pull/1176
- [x] .Fix creating che ingress with correct host https://github.com/eclipse-che/che-operator/pull/771
- [x] .Remove dependency on minishift and devfile api  https://github.com/che-incubator/chectl/pull/1172
- [x] .Code clean up part 4 https://github.com/eclipse-che/che-operator/pull/761
---
Previous sprint https://github.com/eclipse/che/issues/19364
