### ISSUE TITLE
Plugins Sprint 200

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19548]
## Sprint 200 (April 14th 2021 - May 4th 2021)
This sprint will result in the release of Che 7.30.

### Epics
* [ ] Enable community devfiles and plugins in Dev Sandbox #19271
    * [x] Add registryUrls in the devfile registry #19269 @ericwill 
    * [ ] Add metadata to devfiles #18473 @sunix 

### CRW
* [ ] Support upstream plugin update automation in CRW [CRW-1648](https://issues.redhat.com/browse/CRW-1648) @ericwill 
* [ ] Resource Monitor plugin cannot get access to workspace pod [CRW-1649](https://issues.redhat.com/browse/CRW-1649) @svor 
* [ ] Update kitchensink-example in EAP Maven stack [CRW-1709](https://issues.redhat.com/browse/CRW-1709) @svor 
* [x] Remove globalMemoryLimit attribute in devfiles' meta.yaml [CRW-1703](https://issues.redhat.com/browse/CRW-1703) @vitaliy-guliy 
    * [x] Remove or update globalMemoryLimit in devfiles' meta.yaml #19464
* [ ] Update vscode-java to 0.75.0 [CRW-1699](https://issues.redhat.com/browse/CRW-1699) @sunix 
* [x] Update vscode-yaml to 0.14.0 [CRW-1698](https://issues.redhat.com/browse/CRW-1698) @ericwill 
* [ ] Update the vscode-quarkus extension to 1.7.0 [CRW-1697](https://issues.redhat.com/browse/CRW-1697) @sunix 
* [x] Deprecate asciidoctor-vscode [CRW-1701](https://issues.redhat.com/browse/CRW-1701) @ericwill 

### Bugs
* [ ] Resources Monitor Plugin doesn't have enough permissions to read Pod information on Hosted Che #18812 @svor
* [x] Che-plugin-registry don't take into account CHE_SIDECAR_CONTAINERS_REGISTRY_URL #19492 @sunix 
* [ ] In hosted-instance-log: "TypeError: Cannot read property 'path' of undefined" from vscode-builtin-json-language-feature #19485 @tsmaeder 
* [x] Adapt che tasks to upstream changes #19541 @tsmaeder 
    * [x] Cannot execute npm Task eclipse-theia/theia#9335
* [ ] Git cloning fails in a proxy environment #19242 @vitaliy-guliy 
* [ ] SonarLint plugin issue with SonarQube Connected Mode #17980 @vinokurig 
* [ ] Projects in the devfile registry should be owned by the Che team. #19359 @sunix / @vitaliy-guliy 
* [ ] devfile-registry: python-django app cannot preview #19459 @vitaliy-guliy 
* [x] The "shellcheck" plugin doesn't work #19376 @tsmaeder 
* [x] Multiroot workspace: project must appear in the project explorer when it was cloned by a command in terminal #19544 @vitaliy-guliy 

### Enhancements
* [ ] Implement the Secrets API eclipse-theia/theia#9348 @vinokurig 
* [ ] Enable the multi-root mode for Go devfile #19476 @sunix 
* [ ] Investigate the ability of adding of public key to Bitbucket and GitLab #19186 @vitaliy-guliy 
* [ ] Enable telemetry support in Eclipse Che #19361 @vinokurig 
* [x] Move the che-plugin-registry to pnp/yarn v2 #19581 @ericwill 
    

### QE
* [ ] Rework the "che-plugin-registry" image build using multistage dockerfile #19554 @Ohrimenko1988 
* [ ] Create automated test for the GitHub PR plugin #19513 @Ohrimenko1988 
* [x] CRW 2.8 release testing @Ohrimenko1988 

### Unplanned
* [x] Cannot install plugin from plugins list [CRW-1746](https://issues.redhat.com/browse/CRW-1746) @svor 
     * [x] Upstream issue: Cannot install any plugin from Plugins view #19623
* [x] sonarlint not working on workspaces.openshift.com https://issues.redhat.com/browse/CRW-1604

### Open PRs From Last Sprint
* [x] Auto detect projects in multiroot workspace eclipse-che/che-theia#1076
* [x] Specify che-editors.yaml in devfile v2 format eclipse-che/che-plugin-registry#914
* [x] Make Git:clone consistent with cloning of projects by workspace plugin eclipse-che/che-theia#1068

#### Automation / Tests
* [ ] Ability to run tests of a vscode extension on top of che-theia #18219 @svor 
    * [ ] [plugins] Cannot read property 'getExtension' of vscode.extensions #19172

#### Maintenance
* [ ] Upgrade VS Code xml from 0.14 to 0.15 #19494 @ericwill 
* [ ] Upgrade VS Code yaml from 0.14.0 to 0.17.0 #19493 @ericwill 

#### Dogfooding, Developer Experience, or UX Improvements
* [ ] Rework che-theia build process to not use source linking #16852 @tsmaeder 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 13  | 8 |
| @ericwill | 15  | 9 |
| @tsmaeder | 14  | 8 |
| @svor | 10  | 6 |
| @sunix | 9  | 5 |
| @Ohrimenko1988 | 13  | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Add registryUrls in the devfile registry #19269 |
| 2 | Downstream plugin registry automation [CRW-1498](https://issues.redhat.com/browse/CRW-1498) |
| 3  | Downstream plugin updates (vscode-yaml, asciidoctor, etc.)  |
| 4 | Upstream plugin updates (vscode-yaml, vscode-xml) |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Adapt che tasks to upstream changes #19541 |
| 2 | The "shellcheck" plugin doesn't work #19376 |
| 3 | In hosted-instance-log: "TypeError: Cannot read property 'path' of undefined" from vscode-builtin-json-language-feature #19485 |
| 4 | Rework che-theia build process to not use source linking #16852 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Cannot install plugin from plugins list [CRW-1746](https://issues.redhat.com/browse/CRW-1746) |
| 2 | Resources Monitor Plugin doesn't have enough permissions to read Pod information on Hosted Che #18812 |
| 3 | [plugins] Cannot read property 'getExtension' of vscode.extensions #19172 |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Add metadata to devfiles #18473 |
| 2 | Che-plugin-registry don't take into account CHE_SIDECAR_CONTAINERS_REGISTRY_URL #19492 |
| 3 | Projects in the devfile registry should be owned by the Che team. #19359 |
| 4 | Enable the multi-root mode for Go devfile #19476 |
| 5 | Downstream plugin updates (see CRW section) |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Enable telemetry support in Eclipse Che #19361 |
| 2 | Implement the Secrets API eclipse-theia/theia#9348  |
| 3 | SonarLint plugin issue with SonarQube Connected Mode #17980 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Remove globalMemoryLimit attribute in devfiles' meta.yaml [CRW-1703](https://issues.redhat.com/browse/CRW-1703) |
| 2 | Git cloning fails in a proxy environment #19242 |
| 3 | Projects in the devfile registry should be owned by the Che team. #19359 |
| 4 | devfile-registry: python-django app cannot preview #19459 |
| 5 | Investigate the ability of adding of public key to Bitbucket and GitLab #19186 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW 2.8 release testing |
| 2 | Improvements for the che-plugin-registry PR checks |
| 3 | Create automated test for the GitHub PR plugin #19513 |
| 4 | Rework the "che-plugin-registry" image build using multistage dockerfile #19554 |

**Comment by ericwill** [comment]
Superseded by  #19719
