### ISSUE TITLE
Editors Sprint 200

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19559]
Apr 14 - May 4

---
#### First-class support for IntelliJ IDEA Che Editor
- Introduce a Projector-based IDEA Che editor https://github.com/eclipse/che/issues/19596
   - [x] WebSocket unexpected closing problem on DevSandbox during initializing Projector Client https://github.com/eclipse/che/issues/19577
   - [x] IntelliJ IDEA Che Editor must be secure https://github.com/eclipse/che/issues/18934
   - [ ] IDEA Che editor window must be maximized https://github.com/eclipse/che/issues/19595

#### Multi-root workspaces as a default project layout in Che-Theia https://github.com/eclipse/che/issues/19199
- [ ] Multi-root is the only mode, no feature toggle anymore https://github.com/eclipse/che/issues/19594
- [ ] Export launch configurations from devfile to workspace config file https://github.com/eclipse/che/issues/18866
   - [ ] Launch configurations are not available for running https://github.com/eclipse-theia/theia/issues/8987
   - [ ] Workspace-scoped launch configurations of multi-root workspace are associated with folders https://github.com/eclipse-theia/theia/issues/8985

#### DevWorkspace
- [ ] Che-Theia should detect and apply local devfile changes https://github.com/eclipse/che/issues/18670

---
#### Other collaboration on the PRs/issues in upstream Theia
```
issue filed https://github.com/eclipse-theia/theia/issues/9411
issue filed https://github.com/eclipse-theia/theia/issues/9365
issue filed https://github.com/eclipse-theia/theia/issues/9351
issue filed https://github.com/eclipse-theia/theia/issues/9341
PR reviewed https://github.com/eclipse-theia/theia/pull/9377
PR reviewed https://github.com/eclipse-theia/theia/pull/9373
PR reviewed https://github.com/eclipse-theia/theia/pull/9372
PR reviewed https://github.com/eclipse-theia/theia/pull/9336
PR reviewed https://github.com/eclipse-theia/theia/pull/9340
PR sent https://github.com/eclipse-theia/theia/pull/9415
PR sent https://github.com/eclipse-theia/theia/pull/9380
PR sent https://github.com/eclipse-theia/theia/pull/9374
```

---
## Team
| Name  |
| -- |
| @vzhukovs |
| @RomanNikitenko |
| @azatsarynnyy |

---
[Previous Sprint](https://github.com/eclipse/che/issues/19319)
