### ISSUE TITLE
Che Controller Sprint 200

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19583]
This issue collects work items of Controller Team for Sprint 200 (14 Apr - 4 May).

The previous sprint https://github.com/eclipse/che/issues/19374

## Finalize from the previous sprint
- [x] Projects clone should happen before other components are started https://github.com/devfile/devworkspace-operator/issues/205
- [x] Get rid of CHE_API and CHE_API_EXTERNAL https://github.com/devfile/devworkspace-operator/issues/344
- [x] Feature request: Devfile v2 editor in Dashboard [eclipse/che#19330](https://github.com/eclipse/che/issues/19330)
- [x] Develop a plan regards web terminal plugin version [WTO-65](https://issues.redhat.com/browse/WTO-65)
- [x] DevWorkspace should be failed when its pod has CrashLoopBackOff status https://github.com/devfile/devworkspace-operator/issues/353

### DevWorkspace Operator
- [x] Investigate how Che, CRW, WTO can depends on DWO https://github.com/devfile/devworkspace-operator/issues/379
- [x] Propagate errors from provisioning components and/or workspaceRoutings to condition https://github.com/eclipse/che/issues/17455
- [x] DevWorkspace controller is OOMKilled with just one DevWorkspace existing https://github.com/devfile/devworkspace-operator/issues/313
- [x] Improve DWO versioning https://github.com/devfile/devworkspace-operator/issues/377
- [x] DevWorkspace controller should not care about DWR base host https://github.com/devfile/devworkspace-operator/issues/373

### Dashboard
- [ ] Finalizing devworkspaces should be displayed finalization is done (don't vanish until it's actually gone) [eclipse/che#19324](https://github.com/eclipse/che/issues/19324)
- [x] Singleuser: Failed to create new workspace from the devfile: cannot read property "send" of undefined	https://github.com/eclipse/che/issues/19499
- [x] Avoid re-rendering the Workspace Details page https://github.com/eclipse/che/issues/19601
- [x] Dashboard do not show OAuth login page on Gitlab OAuth2 "authentication needed" response. https://github.com/eclipse/che/issues/19512
- [ ] Create backend for dashboard https://github.com/eclipse/che/issues/19116
- [x] Dashboard should reuse Che Server functionality for devfile v1 overrides https://github.com/eclipse/che/issues/19424
- [x] Dashboard fails to load js resources after update https://github.com/eclipse/che/issues/19504
- [ ] [UD] Show a proper error page when Che API is not available https://github.com/eclipse/che/issues/18092
- [ ] Dashboard should report issues which happens on preLoad https://github.com/eclipse/che/issues/19564
- [x] Migrate che workspace client and che dashboard to eclipse-che org https://github.com/eclipse/che/issues/19614
- [x] Migrate dashboard to yarn 2 https://github.com/eclipse/che/issues/19613

### Web Terminal
- [x] Bugfix release 1.2.1 https://issues.redhat.com/browse/WTO-88
- [x] The mount volume is not writtable https://issues.redhat.com/browse/WTO-89
- [x] Develop a plan regards web terminal plugin version https://issues.redhat.com/browse/WTO-65

## Unplanned
- [x] Fail to find the target workspace https://github.com/eclipse/che/issues/19603
- [x] Devfile editor tab wrong behaviour https://github.com/eclipse/che/issues/19589
- [ ] Productize new container crw-dashboard-rhel8 https://issues.redhat.com/browse/CRW-1728
- [x] Che Dashboard route is rejected and dashboard container is unused https://github.com/eclipse/che/issues/19721
- [x] Dashboard should handle error codes from oauth flow https://github.com/eclipse/che/issues/19722

The full automated backlog can be found at https://docs.google.com/spreadsheets/d/15GkuWX0m06PkFXe7p2fhvHVJrwSgO-ifK61ffjg7Wcs/edit#gid=559612723
