### ISSUE TITLE
Introduce a Projector-based IDEA Che editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19596]
### Is your task related to a problem? Please describe.
During the [initial investigation](https://github.com/eclipse/che/issues/18619), we've prepared [a PR with a POC](https://github.com/che-incubator/jetbrains-editor-images/pull/21) of running IntelliJ IDEA as a Che editor based on a [Projector technolodgy](https://jetbrains.github.io/projector-client/mkdocs/latest/).
We need to fix all the missing gaps in the mentioned PR to finalize it and add make it available to use through Che Plug-in Registry.

#### Sub-tasks
- [x] WebSocket unexpected closing problem on DevSandbox during initializing Projector Client https://github.com/eclipse/che/issues/19577
- [x] IntelliJ IDEA editor must be secure https://github.com/eclipse/che/issues/18934
- [x] IDEA Che editor window must be maximized https://github.com/eclipse/che/issues/19595
- [x] Clipboard of IDEA Che Editor should share the content with the local system clipboard https://github.com/eclipse/che/issues/19669
- [x] IDEA Che Editor can't render some Markdown files https://github.com/eclipse/che/issues/19702
- [x] Setup release management for JetBrains Che Editor Images https://github.com/eclipse/che/issues/19698
- [x] Update che-docs according to latest changes in JetBrains Editor Images https://github.com/eclipse/che/issues/19654

**Comment by azatsarynnyy** [comment]
WIP PR https://github.com/che-incubator/jetbrains-editor-images/pull/21

**Comment by azatsarynnyy** [comment]
added the clipboard issue https://github.com/eclipse/che/issues/19669

**Comment by azatsarynnyy** [comment]
added https://github.com/eclipse/che/issues/19654 to the sub-tasks list to update the docs accordingly

**Comment by azatsarynnyy** [comment]
one more - https://github.com/eclipse/che/issues/19702 - related to markdown rendering

**Comment by azatsarynnyy** [comment]
added https://github.com/eclipse/che/issues/19698 to set up the release management in the repo https://github.com/che-incubator/jetbrains-editor-images

**Comment by azatsarynnyy** [comment]
The last issue (clipboard-related) from this epic has been fixed upstream. So, everything is done.
The next steps will be tracked in separate issues.
