### ISSUE TITLE
Che Platform Sprint 200

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19591]
#### Timeframe
Apr.  14 - May 4

#### Team
| Name  | 
| ------------- |
| @sparkoo   | 
| @metlos   |  
| @mshaposhnik   |
| @xbaran4   |   
| @skabashnyuk  |  

#### Holidays / events:
- Apr. 23 Hack 'n' Hustle
- May 3,4 Ukraine Holidays

#### CRW releases
CRW 2.5 is based on Eclipse Che 7.20.x
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x

---

###  GitLab

- [x] Gitlab private repo support using OAuth 2 flow | https://github.com/eclipse/che/issues/19171

###  Bitbucket
- [x] Improve workflow when a user denies Bitbucket access for Che | https://github.com/eclipse/che/issues/19274
- [x] The default devfile is resolved from private bitbucket repo after access token is revoked | https://github.com/eclipse/che/issues/19273

### Devworkspaces
- [x] [devworkspace-che] Support custom certificates for gateway and workspace endpoints https://github.com/eclipse/che/issues/19394
- [ ] Define CheCluster v2alpha1 | https://github.com/eclipse/che/issues/19449

### Authentication and authorization in Eclipse Che 
- [x] [che-auth] - new auth on Openshift with OAuth and devworkspaces | https://github.com/eclipse/che/issues/19576

### Docs/Tehnocal debt/bugs
- [x] [doc] Not able to configure "per user" project strategy because users didn't had enough privileges. | https://github.com/eclipse/che/issues/19572
- [x] factory resolver misses volume component from devfile 2.0 | https://github.com/eclipse/che/issues/19563

### Unplanned

- [x] che-server failed to start https://github.com/eclipse/che/issues/19599
- [x] Failing unit test KubernetesNamespaceFactoryTest when building Che serve https://github.com/eclipse/che/issues/19641
- [x] Vulnerability found in che-server image https://github.com/eclipse/che/issues/19650 
- [x] Secret and deployment name normalization required when using SCM username in PersonalAccessToken management https://github.com/eclipse/che/issues/19700
