### ISSUE TITLE
Support Multi-Arch Che (amd64, arm64, s390x, ppc64le)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19687]
### Is your task related to a problem? Please describe.

Today, Che is an **amd64** deployment, though some nightly and released images are multiarch (eg., [che-dashboard](https://quay.io/repository/eclipse/che-dashboard?tag=latest&tab=tags)). However, there are 34 images involved in a Che deployment (including 17 side car images) so setting up CI and release process for ALL images is not there yet, and this is a non-trivial task.

### Describe the solution you'd like

* [ ] 1. Ensure all base images needed are multi-arch, [including the sidecars](https://github.com/eclipse-che/che-devfile-registry/blob/master/arbitrary-users-patch/base_images)
  * [ ] Where the base image is not multi-arch, and will never be as such, a mechanism must exist to remove devfiles and sidecars from the deployment so that workspace loading doesn't break when a devfile references an image for which the arch doesn't exist. See https://github.com/eclipse/che/issues/19025
  * This filtering functionality already exists in CRW but has not been ported upstream into the Che registries. See 
    * https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/build/scripts/write_image_digests.sh
    * https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/build/scripts/write_image_digests.sh

* [ ] 2. Ensure operator knows how to swap in arch-specific images (if applicable). In CRW, this is required when an openj9 variant is needed ons390x or ppc64le, in place of an openjdk image, either because there is no openjdk version for s390x or ppc64le, or simply for performance reasons (openj9 performs better). This is implemented in the Che operator already, but may not be  implemented in the registries. 
  * https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-devfile-registry/build/scripts/swap_images.sh
  * https://github.com/redhat-developer/codeready-workspaces/blob/crw-2-rhel-8/dependencies/che-plugin-registry/build/scripts/swap_images.sh

* [ ] 3. Build single images with podman/docker build for arm64 and amd64; use unique tags like :7.32.0-amd64
  * Could also use buildx here, eg., https://github.com/eclipse-che/che-dashboard/blob/main/.github/workflows/ci-multiarch.yaml#L45-L46

* [ ] 4. Build single images with travis for s390x and ppc64le; use unique tags like :7.32.0-s390x
  * AI: https://github.com/eclipse/che/issues/19688

* [ ] 5. Assemble individually tagged images into multiarch manifests using skopeo copy or docker manifest; use shared tags like :7.32.0
  * See https://github.com/eclipse-che/che-dashboard/blob/main/.github/workflows/ci-multiarch.yaml#L91-L115
  * AI: https://github.com/eclipse/che/issues/19689
  * AI: confirm that something like `CACHE_IMAGE_FULL: docker.io/cheincubator/che-dashboard:cache` will work for collecting images into a single manifest, eg., https://github.com/eclipse-che/che-dashboard/blob/main/.github/workflows/ci-multiarch.yaml#L62-L71

### ** Related issues:**

* https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+multi-arch
* https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+multiarch
* https://github.com/eclipse/che/issues?q=is%3Aissue+is%3Aopen+s390x

### **Working example (buildx only, no travis):**

For a working example of creating multi-arch images/tags, then a combined manifest, see:

* https://github.com/eclipse-che/che-dashboard/blob/main/.github/workflows/ci-multiarch.yaml
* https://github.com/eclipse-che/che-dashboard/blob/main/.github/workflows/release.yml
* https://quay.io/repository/eclipse/che-dashboard?tag=latest&tab=tags

Note that the above solution for multi-arch build (qemu + buildx) only works for small images like che-dashboard. 

For other, larger builds, s390x build fails... which is why Travis has been suggested as the way forward to introduce support for s390x and ppc64le. 

### **Images involved in a Che deployment:**

- Configbump + Traefik
- Operator + Operator-metadata
- Jwtproxy
- Plugin broker artifacts + Plugin broker metadata
- Dashboard
- Server
- Devfile registry, plus 17 sidecars
- Machine exec
- Theia, theia-dev, theia-endpoint
- Plugin registry
- Devworkspace controller (DWO)
- Devworkspace che operator (DWCO)
