### ISSUE TITLE
Editors Sprint 201

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19691]
May 5 - May 25

---
#### Projector-based IDEA Che editor https://github.com/eclipse/che/issues/19596
- [x] IDEA Che editor window must be maximized https://github.com/eclipse/che/issues/19595
- [ ] Clipboard of IDEA Che Editor should share the content with the local system clipboard https://github.com/eclipse/che/issues/19669
- [x] IDEA Che Editor can't render some Markdown files https://github.com/eclipse/che/issues/19702

#### Multi-root workspaces as a default project layout in Che-Theia
- [ ] Export launch configurations from devfile to workspace config file https://github.com/eclipse/che/issues/18866
   - [ ] Launch configurations are not available for running https://github.com/eclipse-theia/theia/issues/8987
   - [ ] Workspace-scoped launch configurations of multi-root workspace are associated with folders https://github.com/eclipse-theia/theia/issues/8985

#### DevWorkspace
- [ ] Che-Theia should detect and apply local devfile changes https://github.com/eclipse/che/issues/18670

#### Other collaboration on the PRs/issues in upstream Theia
- [ ] TaskResolver should respect VS Code documentation https://github.com/eclipse-theia/theia/issues/9411
- help with the Monaco upgrade testing and reviewing https://github.com/eclipse-theia/theia/pull/9154, https://github.com/eclipse-theia/theia/issues/8969
---
### Unplanned/Blockers
- [x] .theia folder doesn't have configuration files on power [CRW-1758](https://issues.redhat.com/browse/CRW-1758)
   - [x] Remove file watchers related workaround https://github.com/eclipse/che/issues/19457
- [ ] Adapt Che-Theia to upstream changes https://github.com/eclipse/che/issues/19804

---
## Team
| Name  | Availability | x0.6
| -- | -- | --
| @vzhukovs    | 12  | 7
| @RomanNikitenko | 9  | 5
| @azatsarynnyy | 9  | 5

May 5-7 - Artem and Roman have PTO
May 14 - H&H Day
May 10 - UA holiday
May 21 - Day of Learning

---
[Previous Sprint](https://github.com/eclipse/che/issues/19559)
