### ISSUE TITLE
Che Deploy Sprint #201

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19708]
#### Timeframe
 May.  4 - May 25

#### Team
| Name  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays / events:
- May 10 Ukraine Holidays
- May 14 Hack 'n' Hustle

#### CRW releases
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x
CRW 2.10 is based on Eclipse Che 7.32.x

---
### CRW issues
---
### Eclipse Che issues 
- [ ] [che-operator] Provides the ability to create backups/restore https://github.com/eclipse/che/issues/18703
  - [x] https://github.com/che-dockerfiles/che-backup-server-rest/pull/1
  - [ ] https://github.com/che-incubator/chectl/pull/1253
- [ ] Theia terminal extension must propagate error from che-machine-exec https://github.com/eclipse/che/issues/16593
  - [ ] https://github.com/eclipse-che/che-machine-exec/pull/148
- [ ] Update go-client libs for che-machine-exec https://github.com/eclipse/che/issues/17874
  - [ ] https://github.com/eclipse-che/che-machine-exec/pull/148
- [ ] Update operator-sdk to the latest version https://github.com/eclipse/che/issues/19466
- [x] Failed to make identity provider oauth callback: javax.net.ssl.SSLException: Connection reset https://github.com/eclipse/che/issues/19653
  - [x] https://github.com/eclipse-che/che-operator/pull/835
- [ ] Update keycloak from 6.0.1 to the latest version https://github.com/eclipse/che/issues/19585
- [x] .Keycloak should private API url to communicate with OpenShift 4.x to bypass proxy https://github.com/eclipse/che/issues/19668
  - [x] https://github.com/eclipse-che/che-operator/pull/814
  - [x] https://github.com/eclipse-che/che-operator/pull/829
- [x] .[che-operator] Do not allow to upgrade che 7.31 or later to upgrade installation that configured with namespace strategies other than "per user" https://github.com/eclipse/che/issues/19537
  - [x] https://github.com/eclipse-che/che-operator/pull/818
- [x] .Expose DWO and DWCO images in CSV as RELATED_IMAGE_* env vars (like all the other images deployed by the Che Operator) https://github.com/eclipse/che/issues/19667
  - [x] https://github.com/eclipse-che/che-operator/pull/815
- [x] .Che Operator does not update DWO and DWCO resources https://github.com/eclipse/che/issues/19664
  - [x] https://github.com/eclipse-che/che-operator/pull/832
- [ ] Consistent proxy configuration for all tools used by chectl needed https://github.com/eclipse/che/issues/19622
- [x] .Create tests to run Eclipse Che in OCP Disconnected Environment https://github.com/eclipse/che/issues/19534
  - [x] https://github.com/eclipse-che/che-operator/pull/812
- [ ] Run DWCO and CO in single pod but different containers https://github.com/eclipse/che/issues/19402
  - [ ] https://github.com/eclipse-che/che-operator/pull/745
- [x] .Run Openshift CI in chectl release branches as che-operator repo https://github.com/eclipse/che/issues/19677
  - [x] https://github.com/openshift/release/pull/18251
---
### Unplanned
- [x] .Refactor server provisioning https://github.com/eclipse-che/che-operator/pull/813
- [x] .Failed to start workspace in GitHub action https://github.com/eclipse/che/issues/19765
  - [x] https://github.com/eclipse-che/che-operator/pull/833
- [x] .Deploy Eclipse Che nightly with chectl failed on minikube and openshift https://github.com/eclipse/che/issues/19773
  - [x] .https://github.com/che-incubator/chectl/pull/1236
- [x] .When installing on OCP 3.11, don't suggest to use OLM install mode (since that's not a viable option) https://github.com/eclipse/che/issues/19777
  - [x] https://github.com/che-incubator/chectl/pull/1239
- [x] .Create test in Openshift CI to test update from latest stable Che version to nightly https://github.com/eclipse/che/issues/19803
  - [x] https://github.com/openshift/release/pull/18587
  - [x] https://github.com/eclipse-che/che-operator/pull/834
  - [x] https://github.com/eclipse-che/che-operator/pull/836
- [ ] Installation CRW 2.9 using 'crwctl' is failed via absent component 'codeready-dashboard' https://issues.redhat.com/browse/CRW-1829
  - [x] https://github.com/eclipse-che/che-operator/pull/839
  - [x] https://github.com/eclipse-che/che-operator/pull/840
---
Previous sprint https://github.com/eclipse/che/issues/19539
