### ISSUE TITLE
Plugins Sprint 201

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19719]
## Sprint 201 (May 5th 2021 - May 25th 2021)
This sprint will result in the release of Che 7.31.

### CRW
* [x] Support upstream plugin update automation in CRW [CRW-1648](https://issues.redhat.com/browse/CRW-1648) @ericwill 
* [x] Resource Monitor plugin cannot get access to workspace pod [CRW-1649](https://issues.redhat.com/browse/CRW-1649) @svor 
    * [x] Resources Monitor Plugin doesn't have enough permissions to read Pod information on Hosted Che #18812 
* [ ] Update vscode-java to 0.75.0 [CRW-1699](https://issues.redhat.com/browse/CRW-1699) @sunix 
* [ ] Update the vscode-quarkus extension to 1.7.0 [CRW-1697](https://issues.redhat.com/browse/CRW-1697) @sunix 
* [x] Add resources limits/requests to che-machine-exec and remote-runtime-injector plugins [CRW-1764](https://issues.redhat.com/browse/CRW-1764) @vitaliy-guliy 
* [ ] The "Install dependencies" command fails in the "PHP-DI" workspace [CRW-1335](https://issues.redhat.com/browse/CRW-1335) @sunix 
* [ ] Debugging not working in Quarkus and Gradle workspaces [CRW-1638](https://issues.redhat.com/browse/CRW-1638) @svor 
* [ ] Workspace does not reload after plugin installation [CRW-1761](https://issues.redhat.com/browse/CRW-1761) @svor 
* [ ] CRW commands are not ended properly sometimes (60%) [CRW-1782](https://issues.redhat.com/browse/CRW-1782) @svor 

### Bugs
* [ ] Avoid untrusted binary popups in vscode-java when using Lombok #19690 @sunix 
* [ ] SonarLint plugin issue with SonarQube Connected Mode #17980 @vinokurig 
    * [ ] Plugins can't communicate properly if they are located in different sidecars #19686
* [x] Projects in the devfile registry should be owned by the Che team. #19359 @vitaliy-guliy 
* [x] devfile-registry: python-django app cannot preview #19459 @vitaliy-guliy 

### Enhancements
* [ ] Implement the Secrets API eclipse-theia/theia#9348 @vinokurig 
* [ ] Jupyter Notebooks native support through latest Python VS Code extension #16818 @sunix 
* [ ] Help theia community member(s) with the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) @tsmaeder 
* [x] Investigate the ability of adding of public key to Bitbucket and GitLab #19186 @vitaliy-guliy 
* [x] ~~[devfile registry]: decouple oci image lifecycle #19695~~ @ericwill
    * Moved to next sprint due to devfile 2.0 clarification/work needed
    

### QE
* [ ] Rework the "che-plugin-registry" image build using multistage dockerfile #19554 @Ohrimenko1988 
* [x] Create automated test for the GitHub PR plugin #19513 @Ohrimenko1988 
* [x] Automate testing Plugins view from the IDE #19639 @Ohrimenko1988 

### Unplanned
* [x] Java plugin fails to initialize (permission denied, mkdir '/home/theia') [CRW-1793](https://issues.redhat.com/browse/CRW-1793)
* [x] Nightly CRW tries to use eclipse/che-theia/next, but only eclipse/che-theia/latest is available [CRW-1792](https://issues.redhat.com/browse/CRW-1792)

### Open PRs From Last Sprint
* [ ] linkless build eclipse-che/che-theia#955
* [x] In hosted-instance-log: "TypeError: Cannot read property 'path' of undefined" from vscode-builtin-json-language-feature #19485
* [ ] Git cloning fails in a proxy environment #19242

#### Maintenance
* [x] Update Che PHP base image to latest release + update composer #19675 @ericwill 
* [x] Remove JAR download from vscode-xml vsix build #19662 @ericwill 
* [ ] Review CustomExecution Lifecycle eclipse-theia/theia#9418 @tsmaeder 
* [ ] Update vscode-openshift-tools to the latest version #19597 @vinokurig 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 13  | 8 |
| @ericwill | 13  | 8 |
| @tsmaeder | 11.5  | 7 |
| @svor | 14  | 8 |
| @sunix | 12.5  | 7 |
| @Ohrimenko1988 | 14  | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Downstream plugin registry automation [CRW-1648](https://issues.redhat.com/browse/CRW-1648) |
| 2  | [devfile registry]: decouple oci image lifecycle #19695  |
| 3 | Update Che PHP base image to latest release + update composer #19675 |
| 4 | Remove JAR download from vscode-xml vsix build #19662 |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Help theia community member(s) with the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) |
| 2 | PR's from last sprint |
| 3 | Review CustomExecution Lifecycle eclipse-theia/theia#9418 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW commands are not ended properly sometimes (60%) [CRW-1782] |
| 2 | Debugging not working in Quarkus and Gradle workspaces [CRW-1638](https://issues.redhat.com/browse/CRW-1638)  |
| 3 | Resources Monitor Plugin doesn't have enough permissions to read Pod information on Hosted Che #18812 |
| 4 | Workspace does not reload after plugin installation [CRW-1761](https://issues.redhat.com/browse/CRW-1761) |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Jupyter Notebooks native support through latest Python VS Code extension #16818 |
| 2 | Avoid untrusted binary popups in vscode-java when using Lombok #19690 |
| 3 | Update vscode-java to 0.75.0 [CRW-1699](https://issues.redhat.com/browse/CRW-1699) |
| 4 | Update the vscode-quarkus extension to 1.7.0 [CRW-1697](https://issues.redhat.com/browse/CRW-1697) |
| 5 | The "Install dependencies" command fails in the "PHP-DI" workspace [CRW-1335](https://issues.redhat.com/browse/CRW-1335) |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Implement the Secrets API eclipse-theia/theia#9348 |
| 2 | SonarLint plugin issue with SonarQube Connected Mode #17980 |
| 3 | Update vscode-openshift-tools to the latest version #19597 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Projects in the devfile registry should be owned by the Che team. #19359 |
| 2 | devfile-registry: python-django app cannot preview #19459 |
| 3 | Add resources limits/requests to che-machine-exec and remote-runtime-injector plugins [CRW-1764](https://issues.redhat.com/browse/CRW-1764) |
| 4 | Investigate the ability of adding of public key to Bitbucket and GitLab #19186 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Automate testing Plugins view from the IDE #19639 |
| 2 | Improvements for the che-plugin-registry PR checks |
| 3 | Create automated test for the GitHub PR plugin #19513 |
| 4 | Rework the "che-plugin-registry" image build using multistage dockerfile #19554 |

**Comment by ericwill** [comment]
Superseded by #19840
