### ISSUE TITLE
Che Controller Sprint 201

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19734]
This issue collects work items of Controller Team for Sprint 201 (5 May - 25 May).

The previous sprint https://github.com/eclipse/che/issues/19583

## Finalize from the previous sprint
- [x] Finalizing devworkspaces should be displayed finalization is done (don't vanish until it's actually gone) [eclipse/che#19324](https://github.com/eclipse/che/issues/19324)
- [x] Productize new container crw-dashboard-rhel8 https://issues.redhat.com/browse/CRW-1728
- [x] DevWorkspace controller should not care about DWR base host https://github.com/devfile/devworkspace-operator/issues/373
- [x] Provide a mechanism to automount configmap/secret into devworkspaces	https://github.com/devfile/devworkspace-operator/issues/384

## DevWorkspace
- [ ] Prototype DevWorkspace as dependency for WTO and CRW https://github.com/devfile/devworkspace-operator/issues/407
- [ ] Move storage type setting to devfile attributes https://github.com/devfile/devworkspace-operator/issues/392
- [x] Adapt to ideUrl -> mainUrl renaming https://github.com/devfile/devworkspace-operator/issues/399
- [x] Cannot start failed workspaces https://github.com/devfile/devworkspace-operator/issues/413

## Dashboard
- [x] Dashboard should report issues which happen on preLoad	https://github.com/eclipse/che/issues/19564
- [x] Redesign Get Started page & Introduce Import from git https://github.com/eclipse/che/issues/18975
- [x] If metadata.name is changed for an existing devfile, an SQL error is shown and changes cannot be saved; Discard Changes does not refresh editor https://issues.redhat.com/browse/CRW-1717
- [ ] [UD] Create backend for dashboard	https://github.com/eclipse/che/issues/19116
- [ ] Dashboard should be able to group samples in dedicated groups https://github.com/eclipse/che/issues/19633
- [ ] [UD] Support factory create policies for devWorkspaces	https://github.com/eclipse/che/issues/19711

## Unplanned

- [x] CRW docs reference "Plugins tab" that no longer exist https://issues.redhat.com/browse/RHDEVDOCS-2994
- [x] Failed to start a devworkspace via factory URL https://github.com/eclipse/che/issues/19788
- [x] DevWorkspace IDE is not opened after devworkspace is started with factory URL https://github.com/eclipse/che/issues/19800
- [x] Tasks are not working for DevWorkspaces https://github.com/eclipse/che/issues/19810

The full automated backlog can be found at https://docs.google.com/spreadsheets/d/15GkuWX0m06PkFXe7p2fhvHVJrwSgO-ifK61ffjg7Wcs/edit#gid=559612723
