### ISSUE TITLE
Che Platform Sprint 201

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19750]
#### Timeframe
May 5 - May 25

#### Team
| Name  | 
| ------------- |
| @sparkoo   | 
| @metlos   |  
| @mshaposhnik   |
| @xbaran4   |   
| @skabashnyuk  |  

#### Holidays / events:
- May 10 Ukraine Holidays
- May 14 Hack 'n' Hustle

#### CRW releases
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x
CRW 2.10 is based on Eclipse Che 7.32.x

---

### New features
- [ ] Allow resolver API to resolve other files than [.]devfile.yaml | https://github.com/eclipse/che/issues/19540

### Devworkspaces
- [x] Define CheCluster v2alpha1 | https://github.com/eclipse/che/issues/19449
- [x] Start using CheCluster v2alpha1 in DWCO | https://github.com/eclipse/che/issues/19450
- [x] Adapt DevWorkspace Che operator to routingSuffix removal from DevWorkspaceRouting CR | https://github.com/eclipse/che/issues/19631

### Authentication and authorization in Eclipse Che 
- [ ]  [che-auth] - implement new auth for devworkspaces on Openshift in che-server | https://github.com/eclipse/che/issues/19703

### Docs/Tehnocal debt/bugs
- [ ]  Consider creating user namespaces with che-server's SA even when OpenShift OAuth is enabled | https://github.com/eclipse/che/issues/19717
- [x]  Remove the code that support namespace strategies other than "per user" | https://github.com/eclipse/che/issues/19536

### Unplanned
- [ ] Private bitbucket factory acceptance fails if there is no k8s namespace yet https://github.com/eclipse/che/issues/19236
- [x] Migrate maven projects involved in building Che server to new eclipse-che org https://github.com/eclipse/che/issues/19754
- [x] Sometimes devworkspace-che deployment fails because of docker.io '...pull rate limit' for traefik image https://github.com/eclipse/che/issues/19814  
- [x] Fix broken external links in documentation https://github.com/eclipse/che/issues/19841
- [ ] Add an ability to use kubernetes API proxy on Kubernetes | https://github.com/eclipse/che/issues/19813
- [x] Provide some project info when resolving devfile v.2 https://github.com/eclipse/che/issues/19816

</google-sheets-html-origin>
