### ISSUE TITLE
[Cross-Project Epic] Migrate rhel.Dockerfiles in all che repos to use ubi8 + install go-toolset RPMs (go-toolset container deprecated as of RHEL 8.4)

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19762]
### Is your task related to a problem? Please describe.

These containers on which we depend for go builds of various Che components:

* https://catalog.redhat.com/software/containers/devtools/go-toolset-rhel7/5c4fc4b8bed8bd162b6dbedc and
* https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1

Have an EOL notice on them which reads:

```
End of life notice: The Go Toolset container image will be retired in May 2021 with the RHEL 8.4 release. 
The Go Toolset is available in the ubi8 repo for building ubi8 based containers.
```

Having spoken to the go-toolset image owners, Tilmann Scheller has confirmed this means that as of RHEL 8.4, there will be **no more updates to the go-toolset images in RHEC**. 

For the latest updates/fixes/CVEs, we have to **use RPM installs instead**.

### Describe the solution you'd like

* wait for RHEL 8.4 to be released in May 2021

* update rhel.Dockerfile and other rhel-based Dockerfiles (eg., [KIP, go toolset ubi8 1.14](https://github.com/che-incubator/kubernetes-image-puller/blob/master/docker/Dockerfile#L13) or [Che operator, go-toolset-rhel7 1.13](https://github.com/eclipse-che/che-operator/blob/main/Dockerfile#L16)) to:
  * use ubi8-minimal:8.4 base image
  * install go-toolset from RPM (using RHEL 8.4 appstream repo)

* for projects that are still tied to go 1.13 or 1.14, update to the latest 1.15 as 1.13 is EOL/unsupported; note also that
* 1.15.7 is available via RPM install in UBI 8.4 based containers (see per https://github.com/eclipse-che/che-operator/pull/848#issuecomment-849676238). 

### Describe alternatives you've considered

Keep using deprecated base images until they become riddled with CVEs and can't be updated/used any more. 

### Additional context

Affected projects/dockerfiles (and their current version of golang being used):

- [x] 1.14 che-jwtproxy/build/dockerfiles/rhel.Dockerfile - PR in https://github.com/eclipse/che-jwtproxy/pull/39
- [x] 1.14 che-machine-exec/build/dockerfiles/rhel.Dockerfile https://github.com/eclipse/che/issues/19764 - updated to 1.15.7 for Che 7.32 - https://github.com/eclipse-che/che-machine-exec/pull/164
- [x] 1.13 che-operator/Dockerfile https://github.com/eclipse/che/issues/19764 - updated to 1.15.7 for Che 7.32 - https://github.com/eclipse-che/che-operator/pull/848
- [ ] 1.14 che-plugin-broker/build/artifacts/rhel.Dockerfile
- [ ] 1.14 che-plugin-broker/build/metadata/rhel.Dockerfile
- [ ] 1.13 che-workspace-operator/build/rhel.Dockerfile
- [ ] 1.13 configbump/build/dockerfiles/rhel.Dockerfile
- [ ] 1.13 devworkspace-che-operator/build/dockerfiles/Dockerfile
- [ ] 1.13 devworkspace-operator/build/rhel.Dockerfile - https://github.com/devfile/devworkspace-operator/pull/452
- [ ] 1.13 devworkspace-operator/project-clone/Dockerfile - https://github.com/devfile/devworkspace-operator/pull/452
- [ ] 1.14 kubernetes-image-puller/docker/Dockerfile
- [ ] 1.13 kubernetes-image-puller-operator/build/Dockerfile
- [ ] 1.12 rhche-kubernetes-image-puller/docker/rhel.Dockerfile

**Comment by tolusha** [comment]
@nickboldt 
Planned for operator/machine-exec https://github.com/eclipse/che/issues/19764

**Comment by nickboldt** [comment]
Thanks! does that include an update from go 1.13 to latest?

**Comment by tolusha** [comment]
@nickboldt 
I will check if it possible to update to 1.14. There were a problem with multi-platform build

> install go-toolset from RPM (using RHEL 8.4 appstream repo)

What about downloading go from https://golang.org/dl/ ?

**Comment by nickboldt** [comment]
Ideally we'd use an RPM ... https://rpmfind.net/linux/rpm2html/search.php?query=golang .... or build from sources. Using 3rd party binaries is to be avoided in Red Hat products.

**Comment by nickboldt** [comment]
Turns out we could use go-toolset images tagged w/ 1.15, but moving to UBI is still better ultimately.

![image](https://user-images.githubusercontent.com/227597/120655615-dd0d5b80-c450-11eb-8cc5-c54c05b089dd.png)

**Comment by nickboldt** [comment]
Done or n/a:

- [x] 1.13 che-workspace-operator/build/rhel.Dockerfile --> redirects to devworkspace-operator, so not applicable
- [x] 1.14 che-machine-exec/build/dockerfiles/rhel.Dockerfile https://github.com/eclipse/che/issues/19764 - updated to 1.15.7 for Che 7.32 - https://github.com/eclipse-che/che-machine-exec/pull/164
- [x] 1.13 che-operator/Dockerfile https://github.com/eclipse/che/issues/19764 - updated to 1.15.7 for Che 7.32 - https://github.com/eclipse-che/che-operator/pull/848
- [x] 1.12 rhche-kubernetes-image-puller/docker/rhel.Dockerfile - archived project

In progress:

- [ ] 1.14 che-jwtproxy/build/dockerfiles/rhel.Dockerfile - PR in https://github.com/eclipse/che-jwtproxy/pull/39
- [ ] 1.13 devworkspace-operator/build/rhel.Dockerfile - https://github.com/devfile/devworkspace-operator/pull/452
- [ ] 1.13 devworkspace-operator/project-clone/Dockerfile - https://github.com/devfile/devworkspace-operator/pull/452

TODO:

- [ ] 1.13 configbump/build/dockerfiles/rhel.Dockerfile
- [ ] 1.14 che-plugin-broker/build/artifacts/rhel.Dockerfile
- [ ] 1.14 che-plugin-broker/build/metadata/rhel.Dockerfile
- [ ] 1.13 devworkspace-che-operator/build/dockerfiles/Dockerfile
- [ ] 1.14 kubernetes-image-puller/docker/Dockerfile
- [ ] 1.13 kubernetes-image-puller-operator/build/Dockerfile

**Comment by nickboldt** [comment]
Note that the EOL notice has been removed and the new ubi8 go-toolset image will be supported.

So we can do this now:

```
# https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/ubi8/go-toolset
FROM registry.access.redhat.com/ubi8/go-toolset:1.15.7-11 as builder
ENV GOPATH=/go/
```

and then where possible, use the ubi8-micro image for the runtime:

```
# https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/ubi8-micro
FROM registry.access.redhat.com/ubi8-micro:8.4-72
```

**Comment by nickboldt** [comment]
Still to do:

- [ ]  1.13 configbump/build/dockerfiles/rhel.Dockerfile
- [ ]  1.14 che-plugin-broker/build/artifacts/rhel.Dockerfile
- [ ]  1.14 che-plugin-broker/build/metadata/rhel.Dockerfile
- [ ]  1.13 devworkspace-che-operator/build/dockerfiles/Dockerfile
- [ ]  1.14 kubernetes-image-puller/docker/Dockerfile
- [ ]  1.13 kubernetes-image-puller-operator/build/Dockerfile

**Comment by nickboldt** [comment]
https://github.com/eclipse/che/issues/19762#

backports for golang updates - DONE:

- [x] configbump - main - 1.15
- [x] dwo - 0.6.x - 1.15
- [x] dwco - 7.32.x - 1.15
- [x] image puller - 7.32.x - 1.15
- [x] image puller operator - master - 1.15 (not used downstream)
- [x] jwtproxy - 7.32.x - 1.15
- [x] machineexc - 7.32.x - 1.15
- [x] operator - 7.32.x - 1.15
- [x] pluginbrokers - v3.4.x - 1.15

jenkins jobs updated to remove golang overrides

- [x] configbump 
- [x] dwo 
- [x] dwco
- [x] image puller 
- [x] jwtproxy 
- [x] machineexc
- [x] operator 
- [x] pluginbrokers

**Comment by nickboldt** [comment]
Seems brew reallllly doesn't want to let us install the golang module rpm, so we have to switch to the go-toolset base image:

- [ ] https://github.com/eclipse-che/che-machine-exec/pull/169 (for main branch, already merged in 7.32.x)
- [ ] https://github.com/eclipse-che/che-operator/pull/876  (for main branch, already merged in 7.32.x)

**Comment by nickboldt** [comment]
FYI, using the ubi8-micro doesn't work in brew for two reasons:

a) the internally available container name is ubi8/ubi-micro, so need to use that if we want to find the base image
b) some internal process needs to run /bin/rpm on the built container, which fails as ubi8-micro has no package manager installed.
