### ISSUE TITLE
Editors Sprint 202

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19831]
May 26 - Jun 15

---
#### Projector-based IDEA Che editor https://github.com/eclipse/che/issues/19596
- [ ] Clipboard of IDEA Che Editor should share the content with the local system clipboard https://github.com/eclipse/che/issues/19669
- [ ] Update che-docs according to latest changes in JetBrains Editor Images https://github.com/eclipse/che/issues/19654
- [ ] Setup release management for JetBrains Editor Images https://github.com/eclipse/che/issues/19698
- [x] Connect to Projector Server running in Che from a desktop client https://github.com/eclipse/che/issues/19574

#### Multi-root workspaces as a default project layout in Che-Theia
- [ ] Export launch configurations from devfile to workspace config file https://github.com/eclipse/che/issues/18866
   - [ ] Launch configurations are not available for running https://github.com/eclipse-theia/theia/issues/8987
   - [ ] Workspace-scoped launch configurations of the multi-root workspace are associated with folders https://github.com/eclipse-theia/theia/issues/8985
- [ ] Add `/projects` as a default project when opening the IDE without any projects in the devfile https://github.com/eclipse/che/issues/19645
- [ ] Multi-root is the only mode in Che-Theia, no feature toggle anymore https://github.com/eclipse/che/issues/19594

#### DevWorkspace
- [ ] Che-Theia should detect and apply local devfile changes https://github.com/eclipse/che/issues/18670

#### Other collaboration on the PRs/issues in upstream Theia
- help with the Monaco upgrade testing and reviewing https://github.com/eclipse-theia/theia/pull/9154, https://github.com/eclipse-theia/theia/issues/8969

#### Other issues
- [x] Adapt Che-Theia to upstream changes (Webpack) https://github.com/eclipse/che/issues/19804
- [ ] Adapt Che-Theia to upstream changes (Tasks) https://github.com/eclipse/che/issues/19866
- [x] Skip the unnecessary PR checks in Che-Theia repo https://github.com/eclipse/che/issues/19850
---
### Unplanned/Blockers
- [x] Investigated CRW theia build fails to compile [CRW#1860](https://issues.redhat.com/browse/CRW-1860)
- Help IBM folks with "Eclipse Che reloading intermittently" https://github.com/eclipse/che/issues/19796
---
## Team
| Name  | Availability | x0.6
| -- | -- | --
| @vzhukovs    | 13  | 8
| @RomanNikitenko | 13  | 8
| @azatsarynnyy | 13  | 8

May 28 - Recharge Day
June 4 - H'n'H Day

---
[Previous Sprint](https://github.com/eclipse/che/issues/19691)
