### ISSUE TITLE
Plugins Sprint 202

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19840]
## Sprint 202 (May 26th 2021 - June 15th 2021)
This sprint will result in the release of Che 7.32.

### CRW
* [x] Update vscode-java to 0.75.0 [CRW-1699](https://issues.redhat.com/browse/CRW-1699) @sunix 
* [x] Update the vscode-quarkus extension to 1.7.0 [CRW-1697](https://issues.redhat.com/browse/CRW-1697) @sunix 
* [x] CRW commands are not ended properly sometimes (60%) [CRW-1782](https://issues.redhat.com/browse/CRW-1782) @svor 
* [ ] Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733) @vinokurig 
    * [ ] Update vscode-openshift-tools to the latest version #19597
* [x] Getting Started tiles use old JBoss logo [CRW-1798](https://issues.redhat.com/browse/CRW-1798) @svor 
* [x] Update kitchensink-example in EAP Maven stack [CRW-1709](https://issues.redhat.com/browse/CRW-1709) @svor 
* [x] [CRW single-host] 'Plugins' list displays default icons [CRW-1840](https://issues.redhat.com/browse/CRW-1840) @vitaliy-guliy 
    * [ ] [devfile-registry] Links (index.json, devfile.yaml) are not correct in Single Host mode #19140
* [x] Handle any fixes needed for the downstream plugin registry build process @ericwill 

### Bugs
* [x] Avoid untrusted binary popups in vscode-java when using Lombok #19690 @sunix 
* [ ] Plugins can't communicate properly if they are located in different sidecars #19686 @vinokurig 
* [ ] Unable to load workspace with frontend che theia plugin #19778 @vitaliy-guliy 
* [x] github.io plugin-registry is not serving meta.yaml content when the full path is omitted #19820 @sunix 
* [ ] Tasks not focus when started from the 'My Workspace view' #19805 @tsmaeder 

### Enhancements
* [ ] Help theia community member(s) with the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) @tsmaeder 
* [ ] Investigate the ability of adding of public key to Bitbucket and GitLab #19186 @vitaliy-guliy 
* [x] Publish a latest/main devfile registry to GitHub pages #19779 @ericwill 
* [x] ~~Adapt the Secrets plugin API to use kubernetes secrets #19837~~ @vinokurig 
    * _Blocked waiting on che-theia being unpinned and using latest theia again_
    

### QE
* [ ] Rework the "che-plugin-registry" image build using multistage dockerfile #19554 @Ohrimenko1988 
* [x] Create automated test for the GitHub PR plugin #19513 @Ohrimenko1988
* [ ] CRW 2.9 release testing @Ohrimenko1988

### Unplanned
* [x] Plugins view must display proper icons if plugins were installed from third-party registry (registryUrl: ...) #19898 @vinokurig 

### Open PRs From Last Sprint
* [x] linkless build eclipse-che/che-theia#955
* [x] Git cloning fails in a proxy environment eclipse-che/che-theia/#1093
* [x] Apply Secrets plugin API eclipse-theia/theia/#9463

#### Automation / Tests
* [ ] [plugins] Cannot read property 'getExtension' of vscode.extensions #19172 @svor 

#### Maintenance
* [ ] Review CustomExecution Lifecycle eclipse-theia/theia#9418 @tsmaeder 
  * https://github.com/eclipse-theia/theia/pull/9559
* [ ] Update Che docs with latest che-theia-plugins.yaml fields #19780 @ericwill 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 14  | 8 |
| @vinokurig  | 14  | 8 |
| @ericwill | 12  | 9 |
| @tsmaeder | 13  | 8 |
| @svor | 14  | 6 |
| @sunix | 14  | 5 |
| @Ohrimenko1988 | 14  | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 | Handle any fixes needed for the downstream plugin registry build process |
| 2 | Update Che docs with latest che-theia-plugins.yaml fields #19780 |
| 3 | Publish a latest/main devfile registry to GitHub pages #19779  |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Help theia community member(s) with the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) |
| 2 | Tasks not focus when started from the 'My Workspace view' #19805 |
| 3 | Review CustomExecution Lifecycle eclipse-theia/theia#9418 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW commands are not ended properly sometimes (60%) [CRW-1782](https://issues.redhat.com/browse/CRW-1782) |
| 2 | Update kitchensink-example in EAP Maven stack [CRW-1709](https://issues.redhat.com/browse/CRW-1709) |
| 3 | Getting Started tiles use old JBoss logo [CRW-1798](https://issues.redhat.com/browse/CRW-1798) |
| 4 | [plugins] Cannot read property 'getExtension' of vscode.extensions #19172 |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Avoid untrusted binary popups in vscode-java when using Lombok #19690 |
| 2 | github.io plugin-registry is not serving meta.yaml content when the full path is omitted #19820 |
| 3 | Update vscode-java to 0.75.0 [CRW-1699](https://issues.redhat.com/browse/CRW-1699) |
| 4 | Update the vscode-quarkus extension to 1.7.0 [CRW-1697](https://issues.redhat.com/browse/CRW-1697) |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733) |
| 2 | Plugins can't communicate properly if they are located in different sidecars #19686  |
| 3 | Secrets API in theia PR |
| 4 | Adapt the Secrets plugin API to use kubernetes secrets #19837 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | [CRW single-host] 'Plugins' list displays default icons [CRW-1840](https://issues.redhat.com/browse/CRW-1840) |
| 2 | Unable to load workspace with frontend che theia plugin #19778 |
| 3 | Investigate the ability of adding of public key to Bitbucket and GitLab #19186 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW 2.9 release testing |
| 2 | Create automated test for the GitHub PR plugin #19513 |
| 3 | Rework the "che-plugin-registry" image build using multistage dockerfile #19554 |
