### ISSUE TITLE
Make CheCluster CR usable for devworkspaces

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#19845]
A lot of information in the `CheCluster` CR can be applied also to devworkspaces. Before we jump and define the next version of `CheCluster` an intermediate and easy step would be to try and reuse as much information that already exists in the `CheCluster` custom resource for running the devworkspaces.

In the end, this will help us with migration as well, because once we define the new CR for configuration Devworkspaces with Che, we will have a clear picture of what information from the pre-existing `CheCluster` resources to use and how to convert it.

Also, having just one custom resource governing both che-operator and devworkspace-che will help us in merging them together.

- [x] Define how to map `CheCluster` configuration options to the properties needed by DWCO #19846
- [x] Start using `CheCluster` in DWCO #19847
- [x] Merge DWCO into che-operator #19408
