### ISSUE TITLE
Che Deploy Sprint #202

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#19855]
#### Timeframe
 May 26 - Jun 15

#### Team
| GitHub account  | 
| ------------- |
| @tolusha |  
| @mmorhun  | 
| @AndrienkoAleksandr  |  
| @flacatus  |   

#### Holidays / events:
- May 28 Recharge Day
- May 27, May 31 Flavius PTO

#### CRW releases
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x
CRW 2.10 is based on Eclipse Che 7.32.x

---
### CRW issues
- [x] Installation CRW 2.9 using 'crwctl' is failed via absent component 'codeready-dashboard' https://issues.redhat.com/browse/CRW-1829
---
### Eclipse Che issues 
- [x] .Theia terminal extension must propagate error from che-machine-exec https://github.com/eclipse/che/issues/16593
  - [x] https://github.com/eclipse-che/che-machine-exec/pull/148
- [x] .Update go-client libs for che-machine-exec https://github.com/eclipse/che/issues/17874
  - [x] https://github.com/eclipse-che/che-machine-exec/pull/148
- [ ] Run DWCO and CO in single pod but different containers https://github.com/eclipse/che/issues/19402
  - [ ] https://github.com/eclipse-che/che-operator/pull/745
- [ ] Update operator-sdk to the latest version https://github.com/eclipse/che/issues/19466
  - [ ] https://github.com/eclipse-che/che-operator/pull/826
- [x] .chectl server:delete does not delete CheManager https://github.com/eclipse/che/issues/19758
  - [x] Remove completelly Devworkspace Che-operator when server:delete is executed https://github.com/che-incubator/chectl/pull/1261
- [x] .[che-operator] [che-machine-exec] Migrate rhel.Dockerfiles to use ubi8 + install go-toolset RPMs https://github.com/eclipse/che/issues/19764
  - [x] https://github.com/eclipse-che/che-operator/pull/848
  - [x] https://github.com/eclipse-che/che-machine-exec/pull/164
- [x] .Failed to deploy Eclipse Che 7.29.2 on OpenShift 4.8.0-0.nightly-2021-05-07-075528 https://github.com/eclipse/che/issues/19770
  - [x] https://github.com/eclipse-che/che-operator/pull/855
- [x] .[che-operator] Add an ability to enable additional external devfile registry https://github.com/eclipse/che/issues/19781
  - [x] https://github.com/eclipse-che/che-operator/pull/845
- [x] .Ensure che-operator,che-machine-exec,chectl files contains correct license header https://github.com/eclipse/che/issues/19647
  - [x] https://github.com/che-incubator/chectl/pull/1280
  - [x] https://github.com/eclipse-che/che-machine-exec/pull/166
- [x] .It is not possible to update Eclipse Che by chectl if operator image contains registry port https://github.com/eclipse/che/issues/19860
  - [x] https://github.com/che-incubator/chectl/pull/1269
- [ ] [che-operator] Provides the ability to create backups/restore https://github.com/eclipse/che/issues/18703
  - [x] https://github.com/che-incubator/chectl/pull/1253
  - [x] https://github.com/che-incubator/chectl/pull/1272
  - [ ] https://github.com/eclipse-che/che-operator/pull/844
---
### Unplanned
- [x] .cheHostTLSSecret is not used to secure dashboard ingress/route when server.cheHost is set https://github.com/eclipse/che/issues/19888
  - [x] https://github.com/eclipse-che/che-operator/pull/856
  - [x] https://github.com/eclipse/che-docs/pull/2019
- [ ] Che-operator uses domain-name in spec.tls.hosts in all ingresses generated by che-operator's che-operator-cr-yaml file instead of fqdn of che-server https://github.com/eclipse/che/issues/19921
  - [x] https://github.com/eclipse-che/che-operator/pull/856
  - [x] https://github.com/che-incubator/chectl/pull/1281
  - [x] https://github.com/eclipse-che/che-operator/pull/862
  - [x] https://github.com/eclipse/che-docs/pull/2023
- [x] .chectl doesn't download templates for 7.31.0 version and above https://github.com/eclipse/che/issues/19915
  - [x] https://github.com/che-incubator/chectl/pull/1273
- [x] .Installation on nginx ingress leads to infinite redirect on dashboard https://github.com/eclipse/che/issues/19914
  - [x] https://github.com/eclipse-che/che-server/pull/20
  - [x] https://github.com/eclipse/che-docs/pull/2018
- [x] .Chectl sometimes failed on keycloak deployment with statusCode undefined https://github.com/eclipse/che/issues/19916
  - [x] https://github.com/che-incubator/chectl/pull/1275
- [x] .chectl 7.31.x contains nightly version of images for helmcharts https://github.com/eclipse/che/issues/19924
  - [x] https://github.com/che-incubator/chectl/pull/1276
- [x] .fix: Remove NON_PROXY from custom resource in disconnected tests https://github.com/eclipse-che/che-operator/pull/857
- [x] .Ensure that che-server's SA have enough permission to manipulate with devworkspaces resource on kubernetes https://github.com/eclipse/che/issues/19920
  - [x] https://github.com/eclipse-che/che-operator/pull/858
---
Previous sprint https://github.com/eclipse/che/issues/19708
