### ISSUE TITLE
Che Controller Sprint 202

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19861]
This issue collects work items of Controller Team for Sprint 202 (26 May - 15 June).
:notebook: Please note that this is a tentative plan, until sprint planning has been conducted.

The previous sprint https://github.com/eclipse/che/issues/19734

## Finalize from the previous sprint

- [x] Move storage type setting to devfile attributes https://github.com/devfile/devworkspace-operator/issues/392
- [x] Productize new container crw-dashboard-rhel8 https://issues.redhat.com/browse/CRW-1728
- [x] If metadata.name is changed for an existing devfile, an SQL error is shown and changes cannot be saved; Discard Changes does not refresh editor https://issues.redhat.com/browse/CRW-1717

</google-sheets-html-origin>

## Web Terminal
- [x] Figure out how DevWorkspace operator / webhooks server responds to heavy load https://github.com/devfile/devworkspace-operator/issues/398
- [ ] Add Web Terminal Operator to Sandbox https://issues.redhat.com/browse/CRT-938

## DevWorkspace

- [x] Prototype DevWorkspace as a dependency for WTO and CRW https://github.com/devfile/devworkspace-operator/issues/407
- [x] DWO should respect request and limit for cpu and memory https://github.com/devfile/devworkspace-operator/issues/429
- [ ] Productize DWO (devworkspace-controller) wrapped with its own operator + metadata &amp; publish to RHEC https://issues.redhat.com/browse/CRW-1730
- [ ] Add support for zip-type projects to project-clone init container https://github.com/devfile/devworkspace-operator/issues/416

## Dashboard
- [x] Project is not imported when using devfile v2 factory flow https://github.com/eclipse/che/issues/19371
- [x] Dashboard (or other clients like chectl) should provide metadata about the origin of the devfile with DevWorkspace https://github.com/eclipse/che/issues/19430
- [ ] Create backend for dashboard https://github.com/eclipse/che/issues/19116
- [ ] Workspace is not restarting when prompted to restart it https://github.com/eclipse/che/issues/19751
- [x] Deleting workspace doesn't work properly from Dashboard UI https://github.com/eclipse/che/issues/19833
- [ ] Dashboard should be able to group samples in dedicated groups https://github.com/eclipse/che/issues/19633

## Unplanned
- [ ] Create workspace page title should be fixed to Create Workspace https://github.com/eclipse/che/issues/19890
- [x] codeready-dashboard pod crashing due to /usr/local/bin/rhel.entrypoint.sh Permission denied https://issues.redhat.com/browse/CRW-1861
- [x] Dashboard should provision dashboard and plugin registry URLs into default DWT https://github.com/eclipse/che/issues/19933
- [x] project clone operation is taking too long to clone a repository https://github.com/devfile/devworkspace-operator/issues/446
- [x] project clone operation is altering files after the clone operation https://github.com/devfile/devworkspace-operator/issues/447
