### ISSUE TITLE
Che Platform Sprint 202

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19868]
#### Timeframe
May 26 - Jun 15

#### Team
| Name  | 
| ------------- |
| @sparkoo   | 
| @metlos   |  
| @mshaposhnik   |
| @xbaran4   |   
| @skabashnyuk  |  

#### Holidays / events:
- May 28 Recharge Day

#### CRW releases
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x
CRW 2.10 is based on Eclipse Che 7.32.x

---

### New features
- [x] Allow resolver API to resolve other files than [.]devfile.yaml | https://github.com/eclipse/che/issues/19540
- [x] Consider creating user namespaces with che-server's SA even when OpenShift OAuth is enabled | https://github.com/eclipse/che/issues/19717
- [x] Add an ability to use kubernetes API proxy on Kubernetes | https://github.com/eclipse/che/issues/19813

### Devworkspaces
- [x] Define how to map CheCluster configuration options to the properties needed by DWCO | https://github.com/eclipse/che/issues/19846
- [ ] Start using CheCluster in DWCO | https://github.com/eclipse/che/issues/19847

### Authentication and authorization in Eclipse Che 
- [x]  [che-auth] - implement new auth for devworkspaces on Openshift in che-server | https://github.com/eclipse/che/issues/19703
- [ ] [che-auth] - make it possible to deploy Che with new auth | https://github.com/eclipse/che/issues/19705

### Docs/Tehnocal debt/bugs
- [x] Eclipse che unable to configure AzureFiles as a static Persistent Volume | https://github.com/eclipse/che/issues/18469

### Unplanned
- [x] Failed to start a workspace on a OpenShift cluster https://github.com/eclipse/che/issues/19929
- [x] Update 2.1 devfile schema to a more recent one https://github.com/eclipse/che/issues/19733 
- [ ]  upport deploying devworkspaces on Kubernetes https://github.com/eclipse/che/issues/19944
