### ISSUE TITLE
Plugins Sprint 203

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19959]
## Sprint 203 (June 16th 2021 - July 7th 2021)
This sprint will result in the release of Che 7.33.

### CRW
* [ ] Update vscode-openshift-tools to the latest version #19597 @vinokurig 
    * [ ] Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733)
* [ ] Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) @sunix 
* [x] Fuse devfile Swagger UI not returning response body [CRW-1887](https://issues.redhat.com/browse/CRW-1887) @svor 
* [x] CRW IDE can't work with maven properties in pom.xml [CRW-1781](https://issues.redhat.com/browse/CRW-1781) @svor 
* [x] Delete deprecated asciidoctor-vscode plugin [CRW-1769](https://issues.redhat.com/browse/CRW-1769) @ericwill 
* [x] Update vscode-kubernetes-tools to 1.2.1 [CRW-1700](https://issues.redhat.com/browse/CRW-1700) @ericwill 
* [ ] Failed to run the php debug [CRW-1830](https://issues.redhat.com/browse/CRW-1830) @svor 
* [ ] Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) @sunix 
* [x] Fix any downstream plugin registry issues as they arise @ericwill 
* [ ] Downstream plugin registry should consume generator tool from upstream as an npm package [CRW-1928](https://issues.redhat.com/browse/CRW-1928) @ericwill 

### Bugs
* [x] Task terminal not revealed when started from the 'My Workspace view' #19805 @sunix 
* [ ] Plugins can't communicate properly if they are located in different sidecars #19686 @vinokurig 
* [x] [devfile-registry] Links (index.json, devfile.yaml) are not correct in Single Host mode #19140 @vitaliy-guliy 
* [x] Invalid plugin registry URL #19955 @vitaliy-guliy 
* [ ] TestNG suport for Theia #19828 @sunix 
* [ ] Frontend plugins are broken eclipse-theia/theia#6601 @vitaliy-guliy 

### Enhancements
* [ ] Labelling devfiles in the Dashboard #19953 @sunix / @vitaliy-guliy 
* [ ] Adapt the Secrets plugin API to use kubernetes secrets #19837 @vinokurig 
* [x] Help theia community member(s) with the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) @tsmaeder 
* [ ] Investigate the ability of adding of public key to Bitbucket and GitLab #19186 @vitaliy-guliy 
* [ ] Update Node Debugging Experience #19952 @tsmaeder 
    

### QE
* [ ] Rework the "che-plugin-registry" image build using multistage dockerfile #19554
* [x] CRW 2.9 release testing
* [ ] Test plugins on DevWorkspaces: https://www.eclipse.org/che/docs/che-7/installation-guide/enabling-dev-workspace-engine/ 

### Docs
* [x] Update Che docs with latest che-theia-plugins.yaml fields #19780 @ericwill 
* [x] Document how to customize available plug-ins/devfiles (rebuilding the registries) [RHDEVDOCS-2853](https://issues.redhat.com/browse/RHDEVDOCS-2853) @ericwill 

#### Tests
* [ ] [plugins] Cannot read property 'getExtension' of vscode.extensions #19172 @svor

#### Maintenance
* [ ] Review CustomExecution Lifecycle eclipse-theia/theia#9418 @tsmaeder 
* [x] Change default branch name from master to main for plugin and devfile registries @ericwill 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 13  | 8 |
| @vinokurig  | 13  | 8 |
| @ericwill | 13  | 8 |
| @tsmaeder | 14  | 8 |
| @svor | 13  | 6 |
| @sunix | 14 | 5 |
| @Ohrimenko1988 | 13  | 8 |

##### @ericwill
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Change default branch name from master to main for plugin and devfile registries |
| 2 | Downstream plugin registry should consume generator tool from upstream as an npm package [CRW-1928](https://issues.redhat.com/browse/CRW-1928) |
| 3  | Downstream plugin updates (asciidoc, kubernetes-tooling)  |
| 4 | Update Che docs with latest che-theia-plugins.yaml fields #19780 |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Help theia community member(s) with the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) |
| 2 | Review CustomExecution Lifecycle eclipse-theia/theia#9418 |
| 3  | Test plugins on DevWorkspaces: https://www.eclipse.org/che/docs/che-7/installation-guide/enabling-dev-workspace-engine/ |
| 4 | Update Node Debugging Experience #19952 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW IDE can't work with maven properties in pom.xml [CRW-1781](https://issues.redhat.com/browse/CRW-1781) |
| 2 | Fuse devfile Swagger UI not returning response body [CRW-1887](https://issues.redhat.com/browse/CRW-1887 |
| 2 | Failed to run the php debug [CRW-1830](https://issues.redhat.com/browse/CRW-1830) |
| 4 | [plugins] Cannot read property 'getExtension' of vscode.extensions #19172 |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Task terminal not revealed when started from the 'My Workspace view' #19805 |
| 2 | Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) |
| 3 | Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) |
| 4 | Labelling devfiles in the Dashboard #19953 |
| 5 | TestNG suport for Theia #19828 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Update openshift connector to latest version (support for devfile 2.0) [CRW-1733](https://issues.redhat.com/browse/CRW-1733) |
| 2 | Plugins can't communicate properly if they are located in different sidecars #19686  |
| 3 | Adapt the Secrets plugin API to use kubernetes secrets #19837 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | [devfile-registry] Links (index.json, devfile.yaml) are not correct in Single Host mode #19140 |
| 2 | Invalid plugin registry URL #19955 |
| 3 | Labelling devfiles in the Dashboard #19953 |
| 4 | Frontend plugins are broken eclipse-theia/theia#6601 |
| 5 | Investigate the ability of adding of public key to Bitbucket and GitLab #19186 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW 2.9 release testing |
| 2 | Rework the "che-plugin-registry" image build using multistage dockerfile #19554 |

**Comment by vitaliy-guliy** [comment]
Tried to reproduce, but haven't found any issues.

![Screenshot from 2021-06-18 18-29-52](https://user-images.githubusercontent.com/1655894/122584588-35547800-d063-11eb-8916-a7a848b8071a.png)

Che-Theia latest commit https://github.com/eclipse-che/che-theia/commit/661a6b8
I'm closing this issue as not relevant anymore (to be fair I haven't seen this problem before).

**Comment by svor** [comment]
Superseded by https://github.com/eclipse/che/issues/20055
