### ISSUE TITLE
[Cross-Project Epic] Switch from master to main as default branch in Che repos

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19968]
### Is your task related to a problem? Please describe.

Most Che projects have already migrated away from the old convention of using a master branch.

However a few remain, due to other priorities having been more urgent.

### Describe the solution you'd like

Projects that still need to migrate:

- [x] https://github.com/eclipse-che/che-theia/tree/master https://github.com/eclipse/che/issues/20000
- [x] https://github.com/che-incubator/configbump/tree/master
- [x] https://github.com/eclipse-che/che-devfile-registry/tree/master
- [x] https://github.com/eclipse-che/che-plugin-registry/tree/master
- [x] https://github.com/eclipse/che-release/tree/master - https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863#c10
- [x] https://github.com/che-incubator/kubernetes-image-puller/tree/master
- [x] https://github.com/eclipse/che-jwtproxy/tree/master - https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863#c9

Projects that could/should also migrate:

- [ ] https://github.com/eclipse/che-docs (also should this move to eclipse-che org?)
- [ ] https://github.com/che-samples/* 
- [ ] others? 

How to migrate:

Reopen https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863 and add additional repos to the bug

Followup work once migrated:

* update Che release process to use correct main branch when fetching code, commiting changes, etc.
* update CRW Jenkins jobs to use correct main branch when fetching code, updating dockerfiles, etc.

See also:

* https://github.com/eclipse/che/issues/18995 (previous migration)

**Comment by benoitf** [comment]
che-docs ?

**Comment by ericwill** [comment]
We should probably do all the sample project repos too, i.e. all the repos from https://github.com/che-samples

**Comment by azatsarynnyy** [comment]
Done for Che-Theia https://github.com/eclipse/che/issues/20000

**Comment by nickboldt** [comment]
> We should probably do all the sample project repos too, i.e. all the repos from https://github.com/che-samples

Are you offering to handle that one? should be 1 comment in BZ, then followup PR to update devfiles to use main branch... right?

**Comment by benoitf** [comment]
che-samples is own by eclipse che guys (so don't need to ping on BZ)

**Comment by ericwill** [comment]
Yes we can handle the che-samples (and I guess crw-samples as well) cases

**Comment by nickboldt** [comment]
Done:
* https://github.com/eclipse/che-release/tree/master - https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863#c10
*  https://github.com/eclipse/che-jwtproxy/tree/master - https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863#c9

TODO:
- [ ] https://github.com/che-incubator/configbump/tree/master - need to find a code owner who can do this
- [ ]  https://github.com/eclipse/che-docs (also should this move to eclipse-che org?)
- [ ] https://github.com/che-samples/*

**Comment by nickboldt** [comment]
Remaining TODOs moved to separate issues:

docs: https://github.com/eclipse/che/issues/20252
samples: https://github.com/eclipse/che/issues/20253
