### ISSUE TITLE
Che Controller Sprint 203

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19971]
This issue collects work items of Controller Team for Sprint 203 (16 June - 6 July).
:notebook: Please note that this is a tentative plan, until sprint planning has been conducted.

The previous sprint https://github.com/eclipse/che/issues/19861

## Sprint directions
- Productize DevWorkspace Operator and move WTO/Che/CRW to use it as a dependency;
- Stabilize devworkspace support on Dashboard & move forward to features parity;

### DevWorkspace Operator
- [ ] Productize DWO (devworkspace-controller) wrapped with its own operator + metadata & publish to RHEC https://issues.redhat.com/browse/CRW-1730
- [x] Add support for zip-type projects to project-clone init container https://github.com/devfile/devworkspace-operator/issues/416
- [x] Should Kubernetes references in plugin/parent resolve across the entire cluster? https://github.com/devfile/devworkspace-operator/issues/403
- [x] Elaborate a plan regard install modes https://github.com/devfile/devworkspace-operator/issues/456
- [ ] Errors during project clone are not reported https://github.com/devfile/devworkspace-operator/issues/457
- [x] Investigate project-clone CPU and memory requirements https://github.com/devfile/devworkspace-operator/issues/454

### Web Terminal
- [x] Adapt WTO to depends on DWO as olm dependency https://issues.redhat.com/browse/WTO-101
- [ ] Add Web Terminal Operator to Sandbox https://issues.redhat.com/browse/CRT-938

### Dashboard
- [x] Failed to save changes to devfile	https://github.com/eclipse/che/issues/19922
- [ ] Support factory create policies for devWorkspaces	https://github.com/eclipse/che/issues/19711
- [x] Create workspace page title should be fixed to Create Workspace https://github.com/eclipse/che/issues/19890
- [ ] Create backend for dashboard	https://github.com/eclipse/che/issues/19116
- [ ] Dashboard backend basic API https://github.com/eclipse/che/issues/19987
- [x] Workspace is not restarting when prompted to restart it	https://github.com/eclipse/che/issues/19751
- [ ] Dashboard should better handle devworkspace startup failure https://github.com/eclipse/che/issues/19684
- [x] Error message should be more helpful at creation a workspace	https://github.com/eclipse/che/issues/19945
- [x] Dashboard should recover name if it's removed with devfile editor	https://github.com/eclipse/che/issues/19878, https://issues.redhat.com/browse/CRW-1858

### Docs
- [x] Update docs according to new Quick Add page changes https://github.com/eclipse/che/issues/19949

### Unplanned
- [x] failure to start a devWorkspace with low memoryLimit https://github.com/devfile/devworkspace-operator/issues/462
- [x] Move dashboard contribution guide from CONTRIBUTING.md in che main repo to dashboard repohttps://github.com/eclipse/che/issues/16431
- [ ] Not able to start a devworkspace because namespace are not found https://github.com/eclipse/che/issues/20014
- [ ] Move conversion webhooks into the controller deployment rather than webhooks server https://github.com/devfile/devworkspace-operator/issues/470
- [ ] Document release process for DevWorkspace Operator https://github.com/devfile/devworkspace-operator/issues/468
- [x] What is target namespace for DWO? https://github.com/devfile/devworkspace-operator/issues/475
- [ ] Set up happy path test for Dashboard with DevWorkspaces enabled https://github.com/eclipse/che/issues/19982
- [ ] Deprecate v1alpha1 api group https://github.com/devfile/devworkspace-operator/issues/471
