### ISSUE TITLE
Che Platform Sprint 203

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19983]
#### Timeframe
 Jun 16 - Jul 6

#### Team
| Name  | 
| ------------- |
| @sparkoo   | 
| @metlos   |  
| @mshaposhnik   |
| @xbaran4   |   
| @skabashnyuk  |  

#### Holidays / events:
- Jun 21 Ukraine holiday
- Jun 28 Ukraine holiday

#### CRW releases
CRW 2.6 is based on Eclipse Che 7.24.x
CRW 2.7 is based on Eclipse Che 7.26.x
CRW 2.8 is based on Eclipse Che 7.28.x
CRW 2.9 is based on Eclipse Che 7.30.x
CRW 2.10 is based on Eclipse Che 7.32.x
CRW 2.11 is based on Eclipse Che 7.34.x

---
### Devworkspaces
 - [x] Start using CheCluster in DWCO | https://github.com/eclipse/che/issues/19847
 - [ ] Support deploying devworkspaces on Kubernetes | https://github.com/eclipse/che/issues/19944

### Authentication and authorization in Eclipse Che 
 - [x] [che-auth] - make it possible to deploy Che with new auth | https://github.com/eclipse/che/issues/19705
 - [x] [che-auth] - oauth-proxy can't put token into Authorization header | https://github.com/eclipse/che/issues/19704

### Docs/Technical debt/bugs
 - [x] Document creating a workspace with factory link and creating policy | https://github.com/eclipse/che/issues/19416
 - [x] Update documentation describing the Che workspaces architecture | https://github.com/eclipse/che/issues/19265

### Unplanned
- [x] [Factory acceptance] OAuth routine should not be triggered when it's not configured. https://github.com/eclipse/che/issues/19991
- [X] Unable to create workspace on Openshift 4.8  https://github.com/eclipse/che/issues/19988
- [ ] OpenShift internal registry does not work when user set container registry credentials https://github.com/eclipse/che/issues/19999
