### ISSUE TITLE
Switch Che-Theia default branch from `master` to `main`

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#20000]
### Is your task related to a problem? Please describe.
We need to switch the Che-Theia default branch from `master` to `main` to remove the divisive language.

### Sub-tasks
- [x] Reopen a ticket https://bugs.eclipse.org/bugs/show_bug.cgi?id=572863
- [x] Update the references in Che-Theia repo https://github.com/eclipse-che/che-theia/pull/1147
- [x] Update the references in Che repo https://github.com/eclipse/che/pull/20002

### Additional context
This issue is a part of an epic https://github.com/eclipse/che/issues/19968

**Comment by benoitf** [comment]
so it seems switch of branch occured
https://github.com/eclipse-che/che-theia/runs/2857295711?check_suite_focus=true
generator test is trying to clone master branch and fails

**Comment by azatsarynnyy** [comment]
just prepared a PR to adapt Che-Theia accordingly https://github.com/eclipse-che/che-theia/pull/1147
