### ISSUE TITLE
Provide Android Studio as a Che Editor on DevSandbox

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#20007]
During one of the Che Community calls, we've seen an interesting PoC of the hosted Android backend.
https://github.com/eclipse/che/wiki/Che-Dev-Meetings#31-may-2021

We need to check if there's an interest among the community in the Android backend in the cloud.

#### Sub-tasks:
- [ ] prepare an image with the Android Studio as a Che Editor and all the required toolings included https://github.com/eclipse/che/issues/19575
- [ ] add a custom stack/devfile on DevSandbox with the Android Studio Che Editor
- [ ] post an article on Red Hat Developer blog with the links to try the Android backend hosted on DevSandbox

**Comment by azatsarynnyy** [comment]
cc @gorkem

**Comment by ibuziuk** [comment]
There should be a possibility to enable the android studio from CRW in a reliable way. After that we can consider enabling it on workspaces.openshift.com

**Comment by vzhukovs** [comment]
Depends on https://github.com/eclipse/che/issues/19575
