### ISSUE TITLE
Plugins Sprint 204

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#20055]
## Sprint 204 (July 7th 2021 - July 28th 2021)
This sprint will result in the release of Che 7.34.

### CRW
* [ ] Downstream plugin registry should consume generator tool from upstream as an npm package [CRW-1928](https://issues.redhat.com/browse/CRW-1928) @vinokurig 
* [ ] Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) @sunix 
* [ ] Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593)  @sunix 
* [ ] Verify that registries are able to use RELATED_IMAGE_* values in operator-metatada image [CRW-1157](https://issues.redhat.com/browse/CRW-1157) @svor 
* [x] Failed to run the php debug [CRW-1830](https://issues.redhat.com/browse/CRW-1830) @svor

### Bugs
* [x] User defined tasks are not revealed when these are executed programmatically eclipse-theia/theia#9605 @tsmaeder  
* [ ] TestNG suport for Theia #19828 @sunix 
* [x] Frontend plugins are broken eclipse-theia/theia#6601 @vitaliy-guliy 
* [ ] Eclipse che - 7.29.2 | Mysql based workspace not working #19989 @vitaliy-guliy 
* [x] run automation throw error 'no such file or directory' in che-plugin-registry #19997 @vitaliy-guliy  
* [ ] Debug session failed to launch in workspace because of "No delegateCommandHandler for vscode java.startDebugSession" error #19880 @vitaliy-guliy 
* [ ] Failed to run debug session in the "NodeJS Express Web Application" based workspace #20075 @tsmaeder 

### Enhancements
* [ ] Adapt the Secrets plugin API to use kubernetes secrets #19837 @vinokurig 
* [ ] [devfile registry]: decouple oci image lifecycle #19695 @svor / @vinokurig 
* [ ] Update Node Debugging Experience #19952 @tsmaeder 
* [ ] Finish off the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) refactoring @tsmaeder 
    

### QE
* [ ] CRW 2.10 release testing
* [x] Put a schema for the "vscode-yaml" plugin to a place accessible from the internal network [CRW-1968](https://issues.redhat.com/browse/CRW-1968)

### Unplanned
* [x] Align CheWebviewEnvironment to upstream changes #20077 @vinokurig 
* [x] Unable to create workspace from sample on K8s due wrong URLs reported by devfile registry #20100 @svor 
* [ ] Investigate what work should be done to upgrade vscode-java extension #20134 @tsmaeder

### Open PRs From Last Sprint
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 15  | 9 |
| @vinokurig  | 13  | 8 |
| @tsmaeder | 10  | 6 |
| @svor | 14  | 8 |
| @sunix | 7  | 4 |
| @Ohrimenko1988 | 15  | 9 |

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Finish off the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) refactoring |
| 2 | User defined tasks are not revealed when these are executed programmatically eclipse-theia/theia#9605 |
| 3 | Failed to run debug session in the "NodeJS Express Web Application" based workspace #20075 |
| 4 | Update Node Debugging Experience #19952 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Verify that registries are able to use RELATED_IMAGE_* values in operator-metatada image [CRW-1157](https://issues.redhat.com/browse/CRW-1157) |
| 2 | [devfile registry]: decouple oci image lifecycle #19695 |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) |
| 2 | Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) |
| 3 | TestNG suport for Theia #19828 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Adapt the Secrets plugin API to use kubernetes secrets #19837 |
| 2 | Downstream plugin registry should consume generator tool from upstream as an npm package [CRW-1928](https://issues.redhat.com/browse/CRW-1928)  |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Frontend plugins are broken eclipse-theia/theia#6601 |
| 2 | run automation throw error 'no such file or directory' in che-plugin-registry #19997 |
| 3 | Eclipse che - 7.29.2 Mysql based workspace not working #19989 |
| 4 | Debug session failed to launch in workspace because of "No delegateCommandHandler for vscode java.startDebugSession" error #19880 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | CRW 2.10 release testing |
| 2 | Upstream test improvements |

**Comment by svor** [comment]
Superseded by #20186
