### ISSUE TITLE
Dashboard backend

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20129]
Currently, Dashboard and Che Server are run on the same host and Che Server is fully sufficient for Dashboard as backend for working with Che Workspaces (devfile v1).

But with DevWorkspaces (devfile v2), Che Server is not really managing them and misses some functionalities that Dashboard needs.

First of all, dashboard needs access to K8s API, and Che Server provides unsupported K8s API but it's meant to be a temporary solution.

![Screenshot_20210714_155724](https://user-images.githubusercontent.com/5887312/125625798-1e8c27b5-4795-4143-bb5b-a813413defcc.png)

So:
- [x] https://github.com/eclipse/che/issues/19116
- [x] https://github.com/eclipse/che/issues/19987
- [ ] ... (The API is not fully designed yet some info is available in https://docs.google.com/document/d/1Ydqu8GVgbjE6HAptAdwaB41Od3IUqWLzjVaLQqBh0cs/edit?usp=sharing)
- [ ] probably some issue for authentication is needed here as well

**Comment by sleshchenko** [comment]
the core is in place we can close it and make needed improvements separately.
