### ISSUE TITLE
Plugins Sprint 205

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#20186]
## Sprint 205 (July 28th 2021 - August 17th 2021)
This sprint will result in the release of Che 7.34.

### CRW
* [x] Downstream plugin registry should consume generator tool from upstream as an npm package [CRW-1928](https://issues.redhat.com/browse/CRW-1928) @vinokurig 
* [ ] Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) @sunix 
* [ ] Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) @sunix 
* [x] Verify that registries are able to use RELATED_IMAGE_* values in operator-metatada image [CRW-1157](https://issues.redhat.com/browse/CRW-1157) @svor 
* [ ] Errors notifications shown during trying to invoke the python language server functions [CRW-2063](https://issues.redhat.com/browse/CRW-2063) @sunix 
* [x] Failed starting DW 2.0 from a factory [CRW-2057](https://issues.redhat.com/browse/CRW-2057) @svor 
* [ ] The "openshift-connector" plugin failed to deploy application because of unable to access the "odo" image on the disconnected environment [CRW-2071](https://issues.redhat.com/browse/CRW-2071) @vinokurig 
* [ ] CRW commands are not ended properly sometimes (60%) [CRW-1782](https://issues.redhat.com/browse/CRW-1782) @svor 

### Bugs
* [x] Cannot open Jupyter notebook with the python extension #20057 @sunix 
* [ ] Tasks are not ended properly #19821 @tsmaeder 
* [x] Debug session failed to launch in workspace because of "No delegateCommandHandler for vscode java.startDebugSession" error #19880 @vitaliy-guliy 
* [x] Failed to run debug session in the "NodeJS Express Web Application" based workspace #20075 @tsmaeder 
* [x] che-plugin-registry devfile fails on workspaces.openshift.com (shellcheck plugin not found) #20125 @vitaliy-guliy 
* [ ] Errors notifications shown during trying to invoke the python language server functions #20093 @sunix 

### Enhancements
* [ ] Adapt the Secrets plugin API to use kubernetes secrets #19837 @vinokurig 
* [ ] A single dogfooding devfile for che-theia #18763 @sunix 
* [ ] [devfile registry]: decouple oci image lifecycle #19695 @vinokurig / @svor 
* [ ] Update Node Debugging Experience #19952 @tsmaeder 
* [x] Finish off the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) refactoring @tsmaeder 
* [ ] Add resource limits/requests to the devfiles and plugins in the registries #16685
   * [x] Specify che-theia-plugins memory requests in che-theia-plugin.yaml @vitaliy-guliy 
* [ ] Allow to build custom registries using OpenShift rather than local tools #20177 @svor 
    
### QE
* [x] Plugins tests on the openshift-ci fail because of unable to get a token #20117 @Ohrimenko1988 
* [x] Automate git server installation in Air Gap Mode [CRW-2028](https://issues.redhat.com/browse/CRW-2028)
* [ ] Rework the "che-plugin-registry" image build using multistage dockerfile #19554 @Ohrimenko1988 
* [x] Deploy own git or gitlab instance behind the restricted environment [CRW-2100](https://issues.redhat.com/browse/CRW-2100) @Ohrimenko1988 

### Unplanned
* [x] #20270 @svor
* [ ] #20229 @vinokurig 
* [x] #20287 @Ohrimenko1988
* [x] #20299 @Ohrimenko1988
* [ ] https://github.com/eclipse/che/issues/20083 @tsmaeder 

### Open PRs From Last Sprint
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559 @tsmaeder 
* [x] Refactor to hide VS Code interfaces behind core services eclipse-theia/theia#9727 @tsmaeder 
* [x] fix: update java mysql devfile https://github.com/eclipse-che/che-devfile-registry/pull/454 @vitaliy-guliy

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 10  | 6 |
| @vinokurig  | 12  | 7 |
| @tsmaeder | 14  | 8 |
| @svor | 14  | 8 |
| @sunix | 14  | 8 |
| @Ohrimenko1988 | 14  | 8 |

August 13 - Recharge Day
July 29-30 - Ihor Vinokur PTO
August 9-12 - Vitalii PTO

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Tasks are not ended properly #19821 |
| 2 | Failed to run debug session in the "NodeJS Express Web Application" based workspace #20075 |
| 3 | Update Node Debugging Experience #19952 |
| 4 | Finish off the [monaco upgrade](https://github.com/eclipse-theia/theia/issues/8969) refactoring |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Verify that registries are able to use RELATED_IMAGE_* values in operator-metatada image [CRW-1157] (https://issues.redhat.com/browse/CRW-1157) |
| 2 | Failed starting DW 2.0 from a factory [CRW-2057](https://issues.redhat.com/browse/CRW-2057) |
| 3 | [devfile registry]: decouple oci image lifecycle #19695 |
| 4 | Allow to build custom registries using OpenShift rather than local tools |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) |
| 2 | Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) |
| 3 | Errors notifications shown during trying to invoke the python language server functions [CRW-2063](https://issues.redhat.com/browse/CRW-2063) |
| 4 | Errors notifications shown during trying to invoke the python language server functions #20093 |
| 5 | A single dogfooding devfile for che-theia #18763 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Downstream plugin registry should consume generator tool from upstream as an npm package [CRW-1928](https://issues.redhat.com/browse/CRW-1928)Adapt the Secrets plugin API to use kubernetes secrets #19837 |
| 2 | Adapt the Secrets plugin API to use kubernetes secrets #19837 |
| 3 | The "openshift-connector" plugin failed to deploy application because of unable to access the "odo" image on the disconnected environment [CRW-2071](https://issues.redhat.com/browse/CRW-2071) |
| 4 | [devfile registry]: decouple oci image lifecycle #19695 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Debug session failed to launch in workspace because of "No delegateCommandHandler for vscode java.startDebugSession" error #19880 |
| 2 | che-plugin-registry devfile fails on workspaces.openshift.com (shellcheck plugin not found) #20125 |
| 3 |  Add resource limits/requests to the devfiles and plugins in the registries #16685 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Deploy own git or gitlab instance behind the restricted environment [CRW-2100](https://issues.redhat.com/browse/CRW-2100) |
| 2 | Automate git server installation in Air Gap Mode [CRW-2028](https://issues.redhat.com/browse/CRW-2028) |
| 3 | Plugins tests on the openshift-ci fail because of unable to get a token #20117 |
| 4 | Rework the "che-plugin-registry" image build using multistage dockerfile #19554 |

**Comment by svor** [comment]
Superseded by #20290
