### ISSUE TITLE
Use of "registry.devfile.io" devfile registry

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#20251]
### Is your task related to a problem? Please describe.
Che has a devfile registry since Che 7.x and devfile v1 and the devfile registry is providing the stacks/examples.

In the meantime, devfile that has been incubated in Che is now developed as a separate organization at https://github.com/devfile

For devfile v2, devfile people have developed a new OCI registry having REST api on top of it: https://registry.devfile.io/viewer

### Describe the solution you'd like

- [x] As a first iteration continue using che devfile registry:
  - https://github.com/eclipse/che/issues/20850
  - https://github.com/eclipse/che/issues/21063
  - https://github.com/eclipse/che/issues/20034
  - https://github.com/eclipse/che/issues/20738
- [x] DevWorkspace Operator and IDE issues to support registry devfiles
  - https://github.com/eclipse/che/issues/22103
  - https://github.com/devfile/devworkspace-operator/issues/1084
  - https://github.com/eclipse/che/issues/22525
  - https://github.com/eclipse/che/issues/22524
  - https://github.com/eclipse/che/issues/21514
  - https://github.com/devfile/api/issues/681
  - https://github.com/eclipse/che/issues/21778
  - https://github.com/eclipse/che/issues/22601
- [x] Che Dashboard and Operator issues to consume the new registry
  - https://github.com/eclipse/che/issues/22142
  - https://github.com/eclipse/che/issues/22485
  - https://github.com/eclipse/che/issues/22486
- [x] [Devfile registry](https://registry.devfile.io/) issues:
   - https://github.com/devfile/api/issues/1092
   - [x] OperatorHub availability
      - https://github.com/devfile/api/issues/1007 
      - https://github.com/devfile/api/issues/410 
  - https://github.com/devfile/api/issues/329
 - [ ] Fill the feature gap (not a blocker to switch to `registry.devfile.io`)
 	- [ ] In project starters add `.vscode/extensions.json`, `.vscode/launch.json` as needed
 	- [ ] Define`$DEBUG_PORT` where needed
 	- [ ] Set `exposure:none` for the debug endpoint

**Comment by l0rd** [comment]
Issue on the devfile org side to make those devfiles compatible with Che https://github.com/devfile/api/issues/681 (the list of problems is in [this comment](https://github.com/devfile/api/issues/681)). 

This is related to [odo and che different interpreations of the Devfile 2.x](https://github.com/devfile/api/issues/679).

**Comment by ibuziuk** [comment]
Closing the epic. Starting from 7.82.0 Eclipse Che is going to use registry.devfile.io by default
