### ISSUE TITLE
Plugins Sprint 206

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#20290]
## Sprint 206 (August 18th 2021 - September 6th 2021)
This sprint will result in the release of Che 7.35.

### CRW
* [ ] Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) @sunix 
* [ ] Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) @sunix 
* [ ] Errors notifications shown during trying to invoke the python language server functions [CRW-2063](https://issues.redhat.com/browse/CRW-2063) @sunix 
* [ ] CRW commands are not ended properly sometimes (60%) [CRW-1782](https://issues.redhat.com/browse/CRW-1782) @tsmaeder  
* [x] Security problem with vscode-java plugin (JDK 8 and 11) [CRW-2055](https://issues.redhat.com/browse/CRW-2055) @vitaliy-guliy
* [x] The autocomplete feature doesn't work for the vscode-xml plugin on the disconnected environment [CRW-1967](https://issues.redhat.com/browse/CRW-1967) @vitaliy-guliy 

### Bugs
* [ ] Tasks are not ended properly #19821 @tsmaeder 
* [ ] Errors notifications shown during trying to invoke the python language server functions #20093 @sunix 
* [ ] OpenShift Connector does not work on workspaces.openshift.com #20229 @vinokurig 
* [x] Cannot build che-theia with linkless build #20083 @tsmaeder 
* [x] TestNG suport for Theia #19828 @sunix 
* [x] Bottom panel is not displayed at running a task #19825 @vitaliy-guliy
* [x] Task terminal not revealed when started from the 'My Workspace view' #19805 @sunix  

### Enhancements
* [x] Adapt the Secrets plugin API to use kubernetes secrets #19837 @vinokurig 
* [ ] [devfile registry]: decouple oci image lifecycle #19695 @vinokurig
* [ ] A single dogfooding devfile for che-theia #18763 @sunix 
* [ ] Update Node Debugging Experience #19952 @tsmaeder  
* [x] Add resource limits/requests to the devfiles and plugins in the registries #16685 @vitaliy-guliy 
* [x] Ask users whether they trust the project contents when starting a workspace from a factory link #20249 @vitaliy-guliy 
* [ ] Update the vscode GitHub Pull-Requests plugin to latest. #18661 @vinokurig 
* [x] Support VSCode API version 1.52 https://github.com/eclipse-theia/theia/issues/9193 @tsmaeder 
    
### QE
* [ ] Rework the "che-plugin-registry" image build using multistage dockerfile #19554 @Ohrimenko1988 
* [x] The "VscodeKubernetesPlugin" unexpectedly fails on the openshift-ci #20321 @Ohrimenko1988
* [x] The "VscodeValePlugin" unexpectedly fails on the openshift-ci #20322 @Ohrimenko1988
* [ ] The "GitHubPullRequestPlugin" unexpectedly fails on the #20323 @Ohrimenko1988
* [ ] Release testing @Ohrimenko1988

### Unplanned
* [x] Image theia-endpoint-rhel8:2.11 not found [CRW-1782](https://issues.redhat.com/browse/CRW-2201) @sunix
* [x] Che-Theia build fails with Webpack error when CDN is enabled #20390 @tsmaeder 

### Open PRs From Last Sprint
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559 @tsmaeder 
* [x] Introduce lock to prevent parallel task execution eclipse-theia/theia#9858 @tsmaeder

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 12 | 7 |
| @vinokurig  | 13 | 8 |
| @tsmaeder | 14 | 8 |
| @svor | 2 | 1 |
| @sunix | 10 | 6 |
| @Ohrimenko1988 | 13 | 8 |

August 19 - September 6 - Valerii PTO
August 19-24 - Sun PTO
August 23 - Vitalii PTO
August 24 - Holiday in Ukraine (Independence day)
August 27 - HnH day

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Tasks are not ended properly #19821 |
| 2 | CRW commands are not ended properly sometimes (60%) [CRW-1782](https://issues.redhat.com/browse/CRW-1782) |
| 3 | Support VSCode API version 1.52 https://github.com/eclipse-theia/theia/issues/9193 |
| 4 | Update Node Debugging Experience #19952 |
| 5 | Introduce proper custom execution lifecycle eclipse-theia/theia#9559 |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 |  |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) |
| 2 | Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) |
| 3 | Errors notifications shown during trying to invoke the python language server functions [CRW-2063](https://issues.redhat.com/browse/CRW-2063) |
| 4 | Task terminal not revealed when started from the 'My Workspace view' #19805 |
| 5 | TestNG suport for Theia #19828 |
| 6 | A single dogfooding devfile for che-theia #18763 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Adapt the Secrets plugin API to use kubernetes secrets #19837 |
| 2 | Update the vscode GitHub Pull-Requests plugin to latest. #18661 |
| 3 | OpenShift Connector does not work on workspaces.openshift.com OpenShift Connector does not work on workspaces.openshift.com #20229 |
| 4 | [devfile registry]: decouple oci image lifecycle #19695 |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | Add resource limits/requests to the devfiles and plugins in the registries #16685  |
| 2 | Bottom panel is not displayed at running a task #19825 |
| 3 | Ask users whether they trust the project contents when starting a workspace from a factory link #20249 |
| 4 | The autocomplete feature doesn't work for the vscode-xml plugin on the disconnected environment [CRW-1967](https://issues.redhat.com/browse/CRW-1967) |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Release testing |
| 2 | The "VscodeKubernetesPlugin" unexpectedly fails on the openshift-ci #20321 |
| 3 | The "VscodeValePlugin" unexpectedly fails on the openshift-ci #20322 |
| 4 | The "GitHubPullRequestPlugin" unexpectedly fails on the #20323 |
| 2 | Rework the "che-plugin-registry" image build using multistage dockerfile #19554 |

**Comment by svor** [comment]
Superseded by #20433
