### ISSUE TITLE
Che Milestone 4.7.0

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2029]
## Milestone Overview
- [x] Configuration for using Docker and Docker Compose inside Che workspaces #2116 
- [x] Che CLI with profiles to quickly run multiple Che configurations #2116 
- [x] New command macros #953 

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **target August 26**
- GitHub release complete (QA verified) milestone: **target August 30**
- Eclipse signed release submitted (IP verified) milestone: **target August 31**
- Release shipped milestone: **target August 31**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release note blog / email completed
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live
#### Eclipse signed release complete (IP verified) milestone
- [x] Release signing submitted to Eclipse Foundation
- [x] Release information updated on Eclipse.org
- [x] Release updated on codenvy.com (Eclipse Che free cloud offering)
- [x] Public Factories on codenvy.com QA'ed
#### Release shipped milestone
- [x] Release blog live on che.eclipse.org
- [x] Marketing email / social notifications
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Epics and Issues
- [x] Remove native git implementation #2033 
- [x] Optimize che-launcher for perf #2105 
- [x] Rework UD to listen to environment channels #1648 
- [x] Changes to support che-in-che #2119
- [x] Update dashboard view #2245 
- [x] Enhancements to macros #953, #2230, #2232 
- [x] Deactivation of che-long-touch behaviour in navbar #2237
- [x] Placeholder for preview URL #1591
- [x] Let Che CLI compile Che #2239
- [x] Convert Vagrantfile to use Che Launcher syntax #2026
- [x] Update Vagrantfile #2236
- [x] Modify Error Message When Trying to Run Che Server Twice #2233
- [x] Dashboard's New Project wizard fails if workspace source type is 'location' #2134
- [x] Revamp list's header #2179
- [x] Simplify boxes' design for Dashboard page #2158
- [x] Fix invalid syntax in dashboard imports #2216
- [x] Split view for editor #1837, #1838, #1839, #1840, #1841 
- [x] Che script improvements #2211
- [x] Add support for chefile configuration #1895
- [x] Add che product name to CLI & launcher #2203
- [x] Changes to support che-in-che #2119, #2208
- [x] Update plugin sample #1882
- [x] Apply the new component #2010, #1780, #1779, #1765, #1764, #1763 
- [x] Improved tabbed terminals design #1888
- [x] [dashboard] Move project repository info from separate tab #2129
- [x] New layout for forms in UD #1770
- [x] Adapt Editor agent to manage multi parts #1840
- [x] Correct processing some operations for editor #1839
- [x] Sync content of the file for all opened tabs of this file #1838
- [x] Optimize che-launcher for perf #2105
- [x] Remove native git implementation (replaced with JGit) #2033
- [x] Add "+" button next to "Recent workspaces" #1768
#### Bugs
- [x] Project is not accessible in Dashboard: #2020 
- [x] Classpath not resolved when it's in a Maven container: #1964 
- [x] che-launcher self-destruct causes error: #2065 
- [x] Incorrect factory validation behavior when field value matches default for its type: #2022
- [x] Wrong behavior of targets widget #2002
- [x] Wrong behavior after starting workspace from snapshot #1933
- [x] Add "+" button next to "Recent workspaces" #1768 
- [x] Name of workspace is displayed incorrectly in the header #1848 
- [x] Path in the 'Parent' field presents incorrectly on the 'Project Configuration' window #1868 
- [x] Sometimes the org.eclipse.che.api.project.server.Project Service Test fails during build of the CHE #2006 
- [x] The whole git changed list opens if git compare called from file context menu #1866 
- [x] Che launcher debug prints wrong port / hostname for running server if variables change #2102 
- [x] After select an item in the Git compare widget the Compare button is disabled #1865 
- [x] che-launcher based provisioning with Vagrant doesn't restart the server #2066 
- [x] Fix bug with several IDEs on a page #1746 
- [x] Remove containers in case failed to create docker instance. #2007 
- [x] Error when running Che using CLI utility #2128 
- [x] che.sh trying to run 'docker.exe' on OSX #2248
- [x] Can not do CLI mount #2123 
- [x] Eclipse CHE is up on vagrant but not available on the browser #2235
- [x] Error when running Che using CLI utility #2128
- [x] Registry disappears from admin section #2082
- [x] Wrong icon for unknown filetype in editor #2183
- [x] New layout for forms in UD #1770
- [x] Name of workspace is displayed incorrectly in the header. #1848
- [x] Path in the 'Parent' field presents incorrectly on the 'Project Configuration' window #1868
- [x] Sometimes the org.eclipse.che.api.project.server.Project Service Test fails during build of the CHE #2006
- [x] The whole git changed list opens if git compare called from file context menu #1866
- [x] Che launcher debug prints wrong port / hostname for running server if variables change #2102
- [x] After select an item in the Git compare widget the Compare button is disabled #1865
- [x] che-launcher based provisioning with Vagrant doesn't restart the server #2066
- [x] Wrong behavior of targets widget #2002
- [x] che-launcher self-destruct causes error #2065
- [x] Project is not accessible in Dashboard #2020
- [x] Classpath not resolved when it's in a Maven container #1964
- [x] Incorrect factory validation behavior when field value matches default for its type #2022
- [x] Wrong behavior after starting workspace from snapshot #1933
- [x] Upgrade Codenvy on-prem to 4.6.2 broke workspaces and stacks #644

**Comment by bmicklea** [comment]
Updated date to reflect new release in late August.

**Comment by bmicklea** [comment]
Added overview

**Comment by bmicklea** [comment]
Updated issue because 4.7.0 will be released but not shipped. 4.7.1 will follow immediately after 4.7.0 and be the shipping release.
