### ISSUE TITLE
Plugins Sprint 207

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#20433]
## Sprint 207 (September 8th 2021 - September 27th 2021)
This sprint will result in the release of Che 7.36.2.

### CRW
* [x] Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) @sunix / @tsmaeder  
* [x] Please ensure python imports are recognized [CRW-1593](https://issues.redhat.com/browse/CRW-1593) @sunix 
* [x] Errors notifications shown during trying to invoke the python language server functions [CRW-2063](https://issues.redhat.com/browse/CRW-2063) @sunix 
* [x] CRW commands are not ended properly sometimes (60%) [CRW-1782](https://issues.redhat.com/browse/CRW-1782) @tsmaeder
* [x] Failed to run the php debug [CRW-1830](https://issues.redhat.com/browse/CRW-1830) @svor 
* [x] Python workspace gives "Python not installed" error [CRW-2143](https://issues.redhat.com/browse/CRW-2143) @sunix 
* [ ] Git plugin displays the "No repository found" message if use default repository [CRW-1936](https://issues.redhat.com/browse/CRW-1936) @vinokurig 
* [x] Starting the Qurkus project based on devfile v2 fails [CRW-2247](https://issues.redhat.com/browse/CRW-2247) @svor 

### Bugs
* [ ] Tasks are not ended properly #19821 @tsmaeder 
* [ ] Clone from GitHub is not possible using IDE UI #20316 @vinokurig 
* [x] Errors notifications shown during trying to invoke the python language server functions #20093 @sunix 

### Enhancements
* [ ] [devfile registry]: decouple oci image lifecycle #19695 @vitaliy-guliy 
* [ ] A single dogfooding devfile for che-theia #18763 @sunix 
* [x] Update Node Debugging Experience #19952 @tsmaeder  
* [ ] Update vscode-java extension to the latest version #20134 @tsmaeder 
* [ ] Allow to build custom registries using OpenShift rather than local tools #20177 @svor 
* [ ] Implement Inline and Named Pipe Debug Adapters eclipse-theia/theia#10006 @tsmaeder
* [x] Create v2 devfiles for Getting Started samples #19341 @svor  
    
### QE
* [x] The "VscodeYamlPlugin" fails on the openshift CI nightly job #20441 @Ohrimenko1988 
* [x] Update plugin tests for the disconnected infrastructure [CRW-2248](https://issues.redhat.com/browse/CRW-2248) @Ohrimenko1988 
* [x] Release testing @Ohrimenko1988

### Unplanned
* [ ] [Github PR plugin] The Sign in button is not present in the plugin's view #19621 @vinokurig 
* [x] The "TypescriptPlugin" test unexpectedly fails on the nightly CI job #20472 @Ohrimenko1988
* [ ] CRW doesn't allow MTA(Migration Toolkit for Applications) Plugin to show MTA configuration [CRW-2133](https://issues.redhat.com/browse/CRW-2133) @sunix 
* [ ] Clone from GitHub is not possible using IDE UI [CRW-2290](https://issues.redhat.com/browse/CRW-2290) @vinokurig 

### Open PRs From Last Sprint
* [ ] Introduce proper custom execution lifecycle eclipse-theia/theia#9559 @tsmaeder 

#### Availability
| Name  | Availability | 0.6x |
| ------------- | ------------- | ------------- |
| @vitaliy-guliy  | 5 | 3 |
| @vinokurig  | 5 | 3 |
| @tsmaeder | 10 | 6 |
| @svor | 14 | 8 |
| @sunix | 13 | 8 |
| @Ohrimenko1988 | 14 | 8 |

September 17 - HnH day
September 13-26 - Vitalii PTO
September 15 - October 1 - Igor V PTO
September 17 - Thomas PTO

##### @tsmaeder 
| Priority  | Item |
| ------------- | ------------- |
| 1 |  Update Node Debugging Experience #19952 |
| 2 | Implement Inline and Named Pipe Debug Adapters eclipse-theia/theia#10006 |
| 3 | Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857) |
| 4 | Eclipsecon presentation |
| 5 | Update vscode-java extension to the latest version #20134 |
| 6 | Tasks are not ended properly |

##### @svor 
| Priority  | Item |
| ------------- | ------------- |
| 1 | Starting the Qurkus project based on devfile v2 fails [CRW-2247](https://issues.redhat.com/browse/CRW-2247) |
| 2 | Create v2 devfiles for Getting Started samples #19341 |
| 3 | Failed to run the php debug [CRW-1830](https://issues.redhat.com/browse/CRW-1830) |
| 4 | Allow to build custom registries using OpenShift rather than local tools |

##### @sunix
| Priority  | Item |
| ------------- | ------------- |
| 1 | Errors notifications shown during trying to invoke the python language server functions #20093 |
| 2 | Jupyter Notebooks native support through the Python VS Code extension [CRW-1857](https://issues.redhat.com/browse/CRW-1857)  |
| 3 | Python workspace gives "Python not installed" error [CRW-2143](https://issues.redhat.com/browse/CRW-2143)  |
| 4 | Errors notifications shown during trying to invoke the python language server functions [CRW-2063](https://issues.redhat.com/browse/CRW-2063) |
| 5 | A single dogfooding devfile for che-theia #18763 |

##### @vinokurig  
| Priority  | Item |
| ------------- | ------------- |
| 1 | Clone from GitHub is not possible using IDE UI #20316 |
| 2 | Git plugin displays the "No repository found" message if use default repository [CRW-1936](https://issues.redhat.com/browse/CRW-1936) |

##### @vitaliy-guliy   
| Priority  | Item |
| ------------- | ------------- |
| 1 | [devfile registry]: decouple oci image lifecycle #19695 |

##### @Ohrimenko1988
| Priority  | Item |
| ------------- | ------------- |
| 1 | Release testing |
| 2 | The "VscodeYamlPlugin" fails on the openshift CI nightly job #20441 |
| 3 | Update plugin tests for the disconnected infrastructure [CRW-2248](https://issues.redhat.com/browse/CRW-2248) |

**Comment by svor** [comment]
Superseded by #20531
