### ISSUE TITLE
User Workspace SSH Improvements

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2059]
Workspaces by default are generated simple security with a user name and password. We need to allow users to have more tools to secure their workspace and simplify how their IDEs can access the workspace remotely.
- [x] when ws start, start the sshd agent
- [x] when a new workspace is created, generate an ssh keypair
- [X] allow a user in the IDE or dashboard or REST to retrieve the default private key https://github.com/eclipse/che/pull/2980
- [x] allow a user to remove the default keypair
- [x] provide unison agent
- [x] allow a user to upload their own public key
- [x] allow a user to generate a new public / private key pair from the IDE / dashboard
- [x] allow the user with the `che mount` utility to mount a drive using keys
- [x] whenever as a user I open up the SSH panel, it scrolls to the bottom in the IDE.  It should scroll to the top.  
- [x] it would be better that we do not encourage people to use putty / ssh.  Instead, can we have the utility print out both the commands for running: https://github.com/eclipse/che-dockerfiles/pull/38

```
     che action workspace-ssh <ws-id>
```
- [x] Update 'che mount' utility so that it can work with new SSH keys w/o asking for pwd. : eclipse/che-dockerfiles#38
- [X] Add banner in UD about ssh/workspace. If workspace has ssh key but ssh agent is not enabled => display banner. If ssh key is enabled but workspace machines are not started => display banner https://github.com/eclipse/che/pull/2980
- [X] Display checkbox for each machine of the workspace with ssh agent (ability to turn off/on ssh agent for each machine) https://github.com/eclipse/che/pull/2980
- [X] Update the IDE ssh link https://github.com/eclipse/che/pull/3045
