### ISSUE TITLE
Support for Language Server Protocol - part 2 

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#2109]
This is the second part of LS protocol implementation:
- [x]  Language Server Protocol: ShowMessage Notification feature #1793
- [x]  Language Server Protocol: ShowMessage Request feature #1794
- [x]  Language Server Protocol: Telemetry Notification #1796
- [x]  Language Server Protocol: DidChangeWatchedFiles Notification #1799
- [x]  Language Server Protocol: Document Highlights #1802
- [x]  Language Server Protocol: Push notification to client on new language server #1427
- [x]  Language Server Protocol: Ensure order of Events #1426
- [x]  Language Server Protocol: Rename feature #1806 _(depends on #5955)_

**Comment by TylerJewell** [comment]
@gazarenkov - before we implement this second phase, we need to consider the following usability improvements:
1. Softening some of the treatment of the phase 1 elements so that they have a more modern design to them vs. the heavy black lines.
2. End user acceptance / rejection / installation / uninstallation of LS agents from within the IDE.  LS will have licenses that require acceptance of the end user before they are installed into the ws. We should enable this capability in the UD & probably the IDE at the same time.
