### ISSUE TITLE
Iterative improvements to simplify usage of che in che scenarios

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#2116]
The goal is to minimize the steps that a user needs to take to get Che in Che working with our current architecture. Che in Che involves setting up a volume folder mount, getting a proper stack with Docker inside of it, having special build commands, and then additional macros in commands to simplify the discovery of the server for execution.
- [x] Add `machine.server.extra.volume` as CHE_ environment variable.  The logic to add would be in. Implemented initially with CLI improvement: #2239.  Will be added into the core Che server as well for #2175.
- [x] Improve `che-launcher` container to allow user to set the name of the `che-server` container that will be launched (and stopped). #2119
- [x] Add Docker  to the base alpine image, so that it is available in all workspaces.  #2119 
- [x] Add in missing macros for commands necessary for doing discovery. #953 
- [x] #2119 Create a Che stack that is optimized with alpine software needed to build Che in Che.  Include it as a ready-to-go stack in the default che distribution.
- [x] #2119 Add Che template - that allows to setup Che from our github repo along with commands to build 
- [x] Change ERROR to WARNING (yellow) message for two scenarios - when pulling a docker image remotely that is not present, and then switching to local.  And also when GitHub oAuth is not configured during ws-agent boot. #2135 
- [x] Extend this capability for artik ide. 

The expected end user scenario would be:
1: start che
2: create ws from che stack
3: select template for building all of che (maybe we hvae template for just extension in future)
4: let them build a module
5: have built-in command to run the new che-in-che with properly displayed preview

Test cases:
1: Start Che using che-launcher with extra volume folder set to /var/run/docker.sock using environment variable instead of setting che.properties file.

2: Launch a Che stack with Che template, get a clone of the Che repository.  Ability to build & run it with the embedded commands.

3: Ability to run two che on the same computer side-by-side by using Che CLI profile - create two profiles, set one, start change, change the profile, and start the second che.

4: Test ability to launch Che in superdev mode using Che-in-Che.
