### ISSUE TITLE
Simplify Stack management and authoring

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2205]
The goal of this epic is to simplify the management of Stacks and their authoring. 

_Current State:_
The list of stacks provided with Che can be extended and modified, but in order to do that, there are a lot of manual steps and manual interactions with the API. 

_Goals:_
- Provide easy way to add and register a new Stack in Che from the User Dashboard.
- Provide a way to edit the list of Stacks displayed in the User Dashboard
- Allow Stack authoring from the User Dashboard
- Provide mecanisms to guide the user in the authoring of a Stack

_Tasks:_
- [x] Add Stacks list under Che's Administration page #2206
- [x] Provide simple create/edit page for a Stack #2207 
- [x] Created stack by user is not listed in stack search result https://github.com/codenvy/codenvy/issues/795
