### ISSUE TITLE
Chefile Phase 2

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#2266]
Epic issue about improvements that should be made on Chefile
- [x] ECLIPSE CHE(dir) ECLIPSE CHE(action): format
- [x] table output for action list-workspaces / no log prefix on output
- [x] `che dir ssh`: if no ssh-agent display "The SSH agent has been disabled for this workspace"
- [x] Respect the environment variable values passed along from Che CLI
- [x] SSH improvements [for Che](https://github.com/eclipse/che/issues/2059) 
- [x] Provide Chefile for Che repository
  - [x] --> requires properties allowing several 'volumes mount' for current folder and docker socket (for now che.properties is only allowing one user custom volume) https://github.com/eclipse/che/pull/2264
  - [x] --> requires properties allowing several 'volumes mount' for current folder and docker socket (for now che.properties is only allowing one user custom volume) in new model of environment https://github.com/eclipse/che/pull/2288
  - [x] Allow to define custom recipe 
  - [x] Allow to set project type other than blank
  - [x] Allow to use macros in commands -- see new macro types
    - [x] => requires server-side macro handling
- [x] `che dir destroy` for removing workspace
- [x] `che dir ssh` to connect through ssh to remote machine
- [x] Add other projects than the `current dir` workspace (use of Project importers) : work in progress
- [x] Syntax coloring for Chefile editors? PR submitted https://github.com/eclipse/che/pull/2657
- [x]  `Chefile` Adapter
  - [x] requires DTO generation in Typescript (type checking for converting)
    - [x] https://github.com/eclipse/che-dependencies/pull/17
    - [x] https://github.com/eclipse/che/pull/2490
    - [x] https://github.com/eclipse/che/pull/2637
  - [x] Transform `Chefile` into `factory.json`
  - [x] Transform `factory.json` into `Chefile`
- [x] remote Che
  - [x] `che dir <tobedefined ?>` to connect with local workspace with Docker API (for example ssh is not defined) or as fallback to ssh
  - [x] Define set of files to be opened for clients like IDE for a given workspace
  - [x] => requires IDE enhancement
- [x] "che action".  In the docs, it says it should list all available actions.  But it just gives an error - asking you to provide an action.

New syntax

```
# Runtime to use for this workspace
workspace.runtime.docker.image="codenvy/alpine_jdk8"

workspace.runtime.docker.dockerfile= `
FROM ...
RUN ...
ENV ...
`

workspace.runtime.docker.composefile= `
version: 2
`

workspace.runtime.docker.location= "http://gist...../my-dockerfile"
```

```
# Configure project properties
workspace.projects[0].type = "maven"
```

**Comment by TylerJewell** [comment]
@benoitf - will you provide a template of all the new chefile syntax that will be introduced for these changes into the epic?  Thanks.

**Comment by benoitf** [comment]
@TylerJewell OK i will

**Comment by TylerJewell** [comment]
See the pull request for the new Chefile - https://github.com/eclipse/che/pull/2289

**Comment by benoitf** [comment]
Issue related to https://github.com/eclipse/che/issues/2059
