### ISSUE TITLE
5.0.0-M1 Milestone Plan

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2267]
## Milestone Overview
- Multi-machine workspaces with YAML syntax
- Bitnami pre-built stacks for additional languages
- Workspace agents to allow any Docker image to work in Che without additional syntax
- Che launcher profiles to simplify managing multiple Che configurations on the same machine
- Updated editor to Orion 12
## Upgrade and Migration

This is a pre-GA milestone in the new Che 5 stream.  Milestones will be sequentially numbered using a _M1, M2, Mn_ notation leading to GA.

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.1 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **September 14, 2016**
- GitHub release complete (QA verified) milestone: **September 16, 2016**
- Ship milestone: **September 17, 2016**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [ ] Docs reviewed and live
- [x] Release Docker images available (5.0.0-M1 tag)
#### Epics and Issues
- [x] IDE (client) - workspace agent (server) event transport service #1824
- [x] Mechanism to configure Che with configs from different sources #2175
- [x] Allow mounting of multiple volumes to mount properties #2264
- [x] Add ability to install Orion plugins inside the Che editor #1878
- [x] Add Bitnami stacks and blank project for use with the generators #2301
- [x] Improve workspace RAM settings for add project flow #2403
- [x] Machine Agent specification and implementation #1823
- [x] Adopt agents to new environment model #2285
- [x] Test agents over different containers #2138
- [x] Continuously upload new agent binaries to Codenvy Update Server #2137
- [x] Pack ssh agent #2156
- [x] Implement and pack Language Server Agents #2032
- [x] Implement Agent API #2008
- [x] Specify how to name, package and run Agent #2005
- [x] Make default workspace RAM setting to 2GB #2204
- [x] Make Che with debug flag use default log level instead of debug log level #2272
- [x] Add ability to preview an HTML file into another browser window #1883
- [x] File editor real time content update #1910
- [x] File explorer real time content update #1911
- [x] Git checkout operation notification #1912
- [x] Avoid using deprecated KeyboardEvent.keyIdentifier #2209
- [x] Change Workspace environment model #1818
- [x] Allow mounting of multiple volumes to mount properties #2264
- [x] Ways to mount folder inside host machine to auxiliary machine #2425
- [ ] Document model changes introduced in 1818 #2363
#### Bugs
- [x] che.sh does not run #2295
- [x] che.sh root script is not sh compliant #2303
- [x] Redrawing dashboard page when no workspaces #2275
- [x] Copy/Paste doesn't work in the Terminal (Firefox) #2178
- [x] CLI: Fix Mac tmp dir access #2269
- [x] Fix double output, workspace list, RAM displaying, add recipe format #2348
- [x] Avoid using deprecated KeyboardEvent.keyIdentifier #2209
- [x] Provide more space to the console when the workspace is booting #1757
- [x] Remove the current workspace runtime loader #1759
- [x] Display loading steps when booting ws from IDE #1758
- [x] There is no content of recipe into 'Operation Perspective' #2373
- [x] NullPointer when starting a multi machine workspace #2426
- [x] Creating new machine does not work #2300
- [x] Snapshoting of machines failed if snapshot made second time for given machine #2344
- [x] NPE after deleting multi-module project #1985
- [x] Workspaces that have been created before merge of the agents feature do not start #2385
- [x] Download project as Zip does not work #2377
- [x] Cannot launch a workspace after creation #2331
- [x] The size of workspase is not correctly displayed on the dashboard. #2333
- [x] che.sh root script is not sh compliant #2303
- [x] che.sh does not run #2295
- [x] fixup to che.sh #2306

**Comment by bmicklea** [comment]
Added recently closed issues and PRs

**Comment by bmicklea** [comment]
Updated delivery targets based on results from latest merge activities.

**Comment by bmicklea** [comment]
Release will not be shipped so removed those milestones.

**Comment by linuxd3v** [comment]
> Subsequent milestones leading to GA will be numbered with sequential M2..Mn notation.

So this makes me believe 5.0.0-M1 is not considered GA? Could u clarify what do you understand under GA (General availability)?

> Ship milestone: September 17, 2016

If  M1 is available in Dockerhub on September 17-th - wouldn't that mean it's GA by all means?

**Comment by TylerJewell** [comment]
release = passed QA tests, tagged, and images generated.
shipped = items made available on dockerhub, eclipse servers, and codenvy systems
ga = supported with hotfixes, github issues, etc.

5.0.0-M1 is a release. We are partially shipping it.  We are not supporting it.  We will wait to provide support on it until we get GA, which will be after a series of other milestones that we release and ship
