### ISSUE TITLE
Upgrade dashboard dependencies

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#22922]
### Is your task related to a problem? Please describe

Some essential dashboard dependencies need to be upgraded to the latest major versions.

### Describe the solution you'd like

- [ ] @patternfly/react-core, @patternfly/react-icons, @patternfly/react-table;
- [x] react, react-dom, react-router, react-router-dom;
  - [ ] remove react-tooltip (in favor of https://www.patternfly.org/components/tooltip);
- [x] redux, react-redux, redux-thunk;
- [x] reselect;
- [x] @testing-library/react, @testing-library/react, @testing-library/react, react-test-renderer;
- [ ] eslint;
