### ISSUE TITLE
Advanced stack configuration form

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2316]
_Goal:_
- Provide the ability to author a stack with advanced configuration options.
- Handle authoring for multi-containers based stack.
- Provide the ability to test the stack while authoring it.

_Preliminary:_
The scope of this issue is pretty large and will be handled step by step. It is the natural extension of the basic flow that we started with the issue #2207.

_Advanced Form_
The form is going to be extended with more and more parameters that are handled by the Environment Model.
This form will be used similarly to edit a stack.

![6 - stacks - create new](https://cloud.githubusercontent.com/assets/1636769/18203661/a124f6e0-7118-11e6-88a8-8a7bceba846e.png)

1- User provides the name for the stack

2- User can provide the source of the stack. He can either:
- customize a stack already registered in the system
- provide a dockerfile
- provide a composefile (for multi-container)
- start from a blank template.

3- User configures the machines composing the stack's environment. It can be single machine or multi-machine. The list of machines is collapsible/expendable. By expending a machine, its details and configuration options are displayed, 
Each machine have:
- a name
- RAM
- can be defined as dev-machine (meaning it will be the primary machine where Che will injects agents for IDE tooling) (it is a toggle, activating the dev-machine in one machine of the environment will toggle-off in the other machines)
- a list of agents (if selected, they'll be injected in the machine)
- configuration for environment variables
- configuration for ports
- a list of commands

4- User provides meta-datas for the stack:
- the category in which the stack will be displayed to other
- the list of components included in the stack
- the list of tags (which are used to filter the project templates)

5- User is able to see the raw JSON configuration of the stack.

_Test the Stack_
Once the user is done with the configuration of the stack, we provide the ability to test the stack with a temporary workspace, which will be used only for this purpose.
While editing the stack configuration, two buttons are displayed to the user to "test" the stack. Those buttons are displayed in the header and in the footer overlay.

![6 - stacks - testing - step 1](https://cloud.githubusercontent.com/assets/1636769/18206231/fb3327f8-7125-11e6-8958-28593b18a5a7.png)

When the user hits the "test" button, we show a popup where he can select the templates that are matching the tags he provided to the stack. This step is optional, user is not forced to inject project templates in the temporary workspace, he could also import projects from git, subversion sources.

![6 - stacks - testing - step 2](https://cloud.githubusercontent.com/assets/1636769/18206233/00a3c22e-7126-11e6-98c0-467aa0d4c1a5.png)

After this step is handle, the system boot the temporary workspace and use the stack. The IDE is displayed over the dashboard as it is a temporary one. If user closes the IDE view, the workspace is automatically destroyed. 
All machines outputs are displayed as usual inside of the "Consoles" panel.
- [x] Add source section to advanced stack page https://github.com/eclipse/che/issues/2514
- [x] Add ability to configure machines inside stack definition https://github.com/eclipse/che/issues/2515
- [x] Add ability to set stack's category (advanced, general) https://github.com/eclipse/che/issues/2516
- [x] Add ability to define stack's components https://github.com/eclipse/che/issues/2517
- [x] Add ability to list/edit stack's tags https://github.com/eclipse/che/issues/2518
- [x] User is able to see the raw JSON configuration of the stack https://github.com/eclipse/che/issues/2519
- [x] Manage stack testing https://github.com/eclipse/che/issues/2520
- [x] Import and configure batch of projects on stack testing https://github.com/eclipse/che/issues/3209

**Comment by bmicklea** [comment]
@slemeur who should this be assigned to?  Please take it yourself or assign to a team lead to asses.
