### ISSUE TITLE
4.7.1 Milestone Plan

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2354]
## Milestone Overview

This is a bug fix release.
- Add Bitnami Express 4.13.4 stack and blank project for use with express-generator #2301
- Bug fixes

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed release.
- Code complete milestone: **target September 7**
- GitHub release complete (QA verified) milestone: **target September 8**
- Release shipped milestone: **target September 9**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Release notes created
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live
#### Eclipse signed release complete (IP verified) milestone
- [x] Release signing submitted to Eclipse Foundation (non-blocking)
- [x] Release updated on codenvy.com (Eclipse Che free cloud offering)
- [x] Public Factories on codenvy.com QA'ed
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Epics and Issues
- [x] Separate CHE_VERSION from CHE_UTILITY_VERSION #2307
- [x] Allow Che CLI to run in directory w/o write permissions #2358
- [x] Machine tab does not have full output of the workspace boot #2325
- [x] Add Bitnami Express 4.13.4 stack and blank project for use with express-generator #2301
#### Bugs
- [x] ${workspace.name} macro should be include in gin configuration #2293
- [x] ${server.<name>} macro should provide full information about server #2292
- [x] Unexpected appearance of the second terminal after refresh #2249
- [x] Two terminal tabs appearing when workspace first loads #2324
- [x] Remote Che: terminal unavailable #2281
- [x] 'che-ip' tool returns an error in case when there is no 'ethn' interface #2284
- [x] After creation a new workspace the ssh button in the processes widget is absent #2278
- [x] Connection failed with terminal #2322
- [x] Allow Che CLI to run in directory w/o write permissions #2358
