### ISSUE TITLE
Environment Provider and Agent SPI

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#2355]
This issue related to https://github.com/eclipse/che/issues/1829 and includes next tasks

**Tasks**
- [ ] Create Environment Provider SPI #1826 (Phase 2)
- [ ] Docker Implementation of Environment Provider SPI #1828 (Phase 2)
- [x] Do not use machine API for machine handling #1929

**Comment by skabashnyuk** [comment]
Will be fixed in https://github.com/eclipse/che/issues/4736
