### ISSUE TITLE
5.0.0-M5 Milestone Plan

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2359]
## Milestone Overview
- Node.js debugging with GDB
- Improvments to stack editing
- PHP project type improvements
- Bug fixes
## Upgrade and Migration

This is a pre-GA milestone in the new Che 5 stream.

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.1 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live
#### Epics and Issues
- [x] Add Doc About Workspace Sharing #2557
- [x] Make username validation to use account name validation #2343
- [x] CLI Environment Variables #2560
- [x] Improve error handling when read a container logs #2498
- [x] Add property machine.docker.local_node_host.external #2402
- [x] Fix default PHP content #2721
- [x] Documentation for Workspace Administration - Runtime Stacks #2662
- [x] Add new example plugins provided by EclipseSource #2704
- [x] Add default content for PHP project #2710
- [x] Move 'Git' and 'Subversion' menus to the left #2447
- [x] Validate received Stacks #2055
- [x] Zend stack and project sample #2700
- [x] Allow to use -Dmaven.test.skip=true #2696
- [x] Improvements on DTO Typescript generator #2637
- [x] Adding Node.js info to the 'Requirements' section of the README.MD #2699
- [x] Add ability to download workspace starting outputs from IDE loader #1756
- [x] Enhance GDB debugger to work with node.js #2214
- [x] Add ability to list/edit stack's tags #2518
- [x] Updated getting started for Java/Maven #2674 
- [x] Updated introduction for Che docs #2673
- [x] Expose getCurrentBranch() method on git connection + rework gitvalueProviderFactory #2569
- [x] Do not use machine API for machine handling #1929 
- [x] Create a Che-specific loader to replace the vertical bars #1754 
- [x] Add property machine.docker.local_node_host.external #2402 
- [x] improve IDE iframe injection #2578 
- [x] Add editing mode in workspace view #2478 
- [x] Improve error handling when read a container logs #2498 
#### Bugs
- [x] Servers in machine config are not applied to runtime after workspace restart #2470 
- [x] Rename project doesn't work #1857 
- [x] Fix NPE in tests #2623 
- [x] Git checkout with start point is not working #2618 
- [x] Recursive ssh import does not work #2045 
- [x] "undefined" workspace name in modal dialog in case of error of starting workspace in Dashboard #2492 
- [x] Typo in name validation error message #2455 
- [x] After trying to delete predefined stack - message is not clear #2593
- [x] Workspace configurations are not saved on Che server restart #2670
- [x] Building and skipping tests with default maven goal is failing #2610 
- [x] When browser is resized, the content of the IDE terminal is missing partly #642
- [x] Running npm commands freeze the IDE #2608
- [x] Fix integration tests when uid/gid already exists in docker image for maven typescript generator #2711
- [x] Terminal wasn't opened after restart workspace (regression) #2702
- [x] Remote build context in compose file fails when using a git repo rather than a direct link to a Dockerfile #2684 
- [x] Workspace "learn more" link in UD is wrong #2551
- [x] Workspace name and RAM not respected when importing from workspace definition file #2477
- [x] After trying to delete predefined stack - message is not clear #2593
- [x] Servers in machine config are not applied to runtime after workspace restart #2470
- [x] Workspace configurations are not saved on Che server restart. #2670
