### ISSUE TITLE
4.7.2 Milestone Plan

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2401]
## Milestone Overview

This is a bug fix release.
- Bug fixes

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed release.
- Code complete milestone: **September 7**
- GitHub release complete (QA verified) milestone: **September 8**
- Release shipped milestone: **September 9**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Release notes created
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live
#### Eclipse signed release complete (IP verified) milestone
- [x] Release signing submitted to Eclipse Foundation (non-blocking)
- [x] Release updated on codenvy.com (Eclipse Che free cloud offering)
- [x] Public Factories on codenvy.com QA'ed
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Epics and Issues

(none, bug fix release only)
#### Bugs
- [x] The box 'boxcutter/centos72-docker' could not be found #2379
- [x] Update Vagrantfile to use base centos72 image #2388
