### ISSUE TITLE
Buttery smooth and simple solution for offline workspace sync

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2558]
As a developer I want to be able to use workspaces in my corporate Codenvy system and then use the same workspace in the same state on my laptop in Codenvy/Che where I can go offline. When I come back online I want to be able to sync/transfer the workspace state back to my corporate Codenvy system.

We kind of do this today but it's ugly and would involve exporting the workspace definition, plus transferring the snapshot. It's many steps, several of which are unintuitive.
## New Workflow

**On the corporate Codenvy system**
- Go to the workspace detail view for the workspace that will be synced and press a "Sync Ready" toggle so that the workspace is put into Sync Ready mode.
  - When a workspace is sync ready machines will always be snapshotted when the workspace is stopped.

**On the laptop's Che instance (online)**
- Go to the workspaces page on the UD and select a "Synced Workspaces" option.
- Enter an IP address of a remote Codenvy system and connect
  - Once connected a list of sync-ready workspaces will be shown. 
- Choose one of those workspaces and hit a "Pull Workspace" button.
  - Che checks to make sure the workspace is stopped (if it's not stopped a dialog pops up that says "The workspace must be stopped to be synced - stop it now?" with options to Stop or Cancel).
  - Che checks if there is a copy of the workspace with the same name on the local instance (if there is a dialog pops up "A workspace with that name already exists locally. We can overwrite the local workspace or you can rename the workspace on the remote system." with buttons for "Overwrite" or "Cancel").
- Once the workspace is stopped and there is no naming conflict, the workspace definition file and machine snapshots on the remote system are versioned, pulled to the local Che instance and started locally.

**On the laptop's Che instance (offline)**
- Work for several hours making changes to machines and source code.

**On the laptop's Che instance (online)**
- Go to the workspaces page on the UD and select a "Synced Workspaces" option.
- Enter an IP address of a remote Codenvy system and connect 
  - Once connected a list of sync-ready workspaces will be shown. 
- Choose the workspace the developer has been working on offline and hit a "Push Workspace" button.
  - Che checks to make sure the workspace is stopped (if it's not stopped a dialog pops up that says "The workspace must be stopped to be synced - stop it now?" with options to Stop or Cancel).
  - Che checks that the version of the workspace on the remote system is the same as what was pulled to the local instance (if not, a dialog pops up "The workspace on the remote system has changed since being pulled. Overwrite changes or rename workspace then push?" with buttons for "Overwrite" and "Rename and Push".  If rename is chosen then the workspace will be suffixed with "-1"
- Once the workspace is stopped and there is no other conflict, the workspace definition file and machine snapshots on the local system are versioned, pushed to the remote Codenvy instance and started remotely.
## Tasks
- [ ] Add a "Sync Ready" toggle to the workspace detail view.
- [ ] Add a "Synced Workspaces" section in the workspaces page of the user dashboard.
- [ ] Add a UI element that allows users to add known Codenvy remote hosts
- [ ] Create a table/list view for synced workspaces with search/filter and sortable columns that shows all "Sync Ready" workspaces on known Codenvy remote hosts.
- [ ] "Pull Workspace" and "Push Workspace" buttons.
- [ ] Check for running workspaces.
- [ ] Popup dialog to handle running workspaces.
- [ ] Check for naming conflicts with workspaces.
- [ ] Popup dialog to handle workspace naming conflicts.
- [ ] Check for workspace versions.
- [ ] Popup dialog to handle version mismatches.
- [ ] Mechanism to version workspaces.
- [ ] Mechanism to pull workspace definitions and snapshots from remote to local instance.
- [ ] Mechanism to push workspace definitions and snapshots from local to remote instance.
- [ ] Configuration parameter to allow admins to prevent the offline sync function from working `offline.sync.allowed` with default of allowed.
