### ISSUE TITLE
Enhance Java debugger functionality

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#2611]
To have fully functional java debugger we need to implement the following features:
- [x] show list of threads https://github.com/eclipse/che/issues/3708
- [x] Watch list via editor  https://github.com/eclipse/che/issues/6022
- [x] Run to Cursor enables you to jump to the cursor position ignoring existing breakpoints on the way. https://github.com/eclipse/che/issues/6547
- [x] Breakpoint with conditions https://github.com/eclipse/che/issues/6545

 To set the break condition, enable condition by selecting the appropriate check box, and enter the desired expression in the Condition field.
If the expression evaluates to true, the user-selected actions are performed. If the evaluation result is false, the breakpoint does not produce any effect.
![brealpoint-condition](https://user-images.githubusercontent.com/1636592/27909869-662b2908-625b-11e7-9c80-2561064b9ce0.png)

- [x] Suspend Breakpoints.  https://github.com/eclipse/che/issues/6846
Select this check box to enable suspend policy for a breakpoint. This screenshot taken and description taken from Intellij Idea, think we need similar  behavior
![suspend](https://user-images.githubusercontent.com/1636592/27911201-dbe49d6e-6260-11e7-88b9-2a5ad2ad820b.png)

Suspend policy | Description
-- | --
All | When a breakpoint is hit, all threads are suspended.
Thread | When a breakpoint is hit, the thread where the breakpoint is hit, is suspended.
Make default | Click this button if you want the suspend policy specified for the breakpoint in question to be used as the default one for the subsequently created breakpoints.

- [x] Disabling a breakpoint temporarily https://github.com/eclipse/che/issues/6845
- [x] Navigate to breakpoint https://github.com/eclipse/che/issues/6843
- [x] Java Debugger evaluates only simple expressions (investigation) https://github.com/eclipse/che/issues/7006
