### ISSUE TITLE
5.0.0-M4 Milestone Plan

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2615]
## Milestone Overview

This is primarily a bug fix release, it's release will be completed as soon as the list of bugs is fixed.
## Upgrade and Migration

This is a pre-GA milestone in the new Che 5 stream.

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.2 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [ ] Final release information updated on GitHub
- [x] Docs reviewed and live (https://eclipse-che.readme.io/v5.0)
#### Epics and Issues
- [x] CLI Environment Variables #2560
#### Bugs
- [x] Change JPA mapping for TEXT fields #2609
