### ISSUE TITLE
5.0.0-M2 Milestone Overview

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2640]
## Milestone Overview

This is a pre-GA milestone in the new Che 5 stream.
## Upgrade and Migration

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.2 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: 21-Sep-2016
- GitHub release complete (QA verified) milestone: 23-Sep-2016
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [ ] Docs reviewed and live
#### Epics and Issues
- [x] Fix LanguageServerException message for CSharp LS #2532
- [x] Use 1Gb RAM for db machine and remove ssh agent from it #2505
#### Bugs
- [x] Java Refactoring Rename feature broken after merging VFS Events and Split Editor features #2168
