### ISSUE TITLE
5.0.0-M3 Milestone Overview

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2641]
## Milestone Overview

This is a feature release which includes:
- New stack editor in the user dashboard
- Expanded workspace configuration in the dashboard
- Smoothing and simplifying of the user interface
- Support for the Codenvy/Microsoft/RedHat language server protocol standard
- Upgrade to Orion 12
- Consolidated database
## Upgrade and Migration

This is a pre-GA milestone in the new Che 5 stream.

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.2 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release is an internal-only release which will not be shipped or marketed. This will allow us to address any bugs found in post-release testing in the 5.0.0-M4 release before shipping.
- Code complete milestone: 26-Sep-2016
- GitHub release complete (QA verified) milestone: 27-Sep-2016
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
#### Epics and Issues
- [x] Documentation for preview HTML. #2597
- [x] Documentation for Mounting #2596
- [x] Publish StackPersistedEvent after stack is persisted #2582
- [x] Add section in workspace to handle the agents #1774
- [x] CLI: Use new che-mount & adds mechanism for CLI to update itself to new versions #2535
- [x] Soften lines/separator for dark theme #2142
- [x] Use tag instead of snapshot of the io.typefox.lsapi project #2506
- [x] Add support of BasicAuthentication Authentication to Git #1940
- [x] Provide Maven plugin for generating TypeScript DTO objects based on Java DTO #2490
- [x] Use of TypeScript instead of ES6 #1587
- [x] Add testing stack for Language Server agents #2541
- [x] Che CLI: added some parameters to execute che-mount #2523
- [x] Set CLI home directory to be ${CHE_MINI_PRODUCT_NAME} #2410
- [x] Update editor to Orion 12 #1900
- [x] Add syntax coloration to machine outputs when starting a workspace #1755
- [x] StackDao implementation on JPA #1795
- [x] Investigate strategies for removing cascading entities #1803
- [x] Merge model changes to JPA branch #2280
- [x] User password stores/updates without encoding #2136
- [x] Migrate local json-based storage to jpa #2016
- [x] Don't store account name as Workspace#namespace #1950
- [x] Integrate JPA components/tools with Che Infrastructure #1807
- [x] Add utils to parse environment recipe format #2213
- [x] Gray out menus until the workspace is not loaded or stopped #2286
- [x] Add Environment variables in the workspace configuration #1772
- [x] Add Ports section in the workspace configuration #1771
- [x] Provide simple create/edit page for a Stack #2207
- [x] Add Stacks page under Che's Dashboard #2206
- [x] CLI - che start is not selinux aware #2441
- [x] Proper C# support for Che #2274
- [x] Add c# project type #1808
- [x] Add .che to gitignore #2462
- [x] Merge LSP branch to the master #2279
- [x] Support for Language Server Protocol #2452
- [x] SnapshotDao implementation on JPA #1797
- [x] Create JPA based SshDao implementation #1810
- [x] RecipeDao implementation on JPA #1815
- [x] Implementation of workspace service storage on JPA #1813
- [x] FactoryService structural refactoring #1812 
- [x] Implement UserDao based on JPA #1811
- [x] Create/Use TCK for UserDao #1847
- [x] UserService structural refactoring #1846
#### Bugs
- [x] The editor hangs if a initializing server is not launched #2574
- [x] Fixes space issue with profile variables #2575
- [x] Fix editing machine's RAM on workspace creation #2570
- [x] Cannot start a workspace with alpine base image #2424
- [x] Remove duplicated dependency #2547
- [x] Item 'Clear list' was present earlier but it's absent now #2521
- [x] volumes_from does not work #2366
- [x] Impossible to change RAM when compose stack is selected #2494
- [x] Can't start workspace if it contains projects after it's stopped #2500
- [x] The one of editor tabs is not closed after stop workspace #2372
- [x] After invoking of some command in the IDE terminal - view may be broken #2353
- [x] Remove autostart LS agents #2484
- [x] Workspace environment page enhancement #2451
- [x] Allow for changes to workspace RAM to existing workspace #1918
- [x] Fix project creation page issues on dashboard #2416
- [x] Unexpected reloading the factories page after selecting #1922
- [x] ch.sh wrong permissions #2468
