### ISSUE TITLE
Rename Che Docker Images

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2737]
Currently, the Eclipse Che docker images are located in Codenvy organization on Docker Hub such as docker image "codenvy/che-launcher". We need to move all Che docker images to the Eclipse organization on Docker Hub which will rename all docker images and reference such as docker image "eclipse/che-launcher". This will effect all recipes as well so all Che stack configurations will need to be changed.
- [x] Create new repositories in the Eclipse's Docker Hub organization for all existing dockerfiles located at [https://github.com/codenvy/dockerfiles](https://github.com/codenvy/dockerfiles).
- [x] Update CLI to use new Docker image names.
- [x] Update all Eclipse Che stacks to refer to the new Docker image names.
- [x] Update documentation to refer to the new Docker image names.
- [x] [Migrate off of codenvy/dockerfiles](https://github.com/codenvy/infrastructure/issues/7)

**Comment by ghost** [comment]
@JamesDrummond are we talking about Che related images? Do we need to move all images that we use for runtimes to Eclipse org on DockerHub?

Who will control those automated builds? We often need to apply quick fixes to envs.

**Comment by TylerJewell** [comment]
Yes, correct.  Also, we should remove the codenvy dockerfiles github repository but still host the codenvy/ docker hub images for old versions of the product.

The Che project controls the builds.  We have update access to the eclipse dockerhub the same way we have for codenvy.

**Comment by ghost** [comment]
@TylerJewell So @ddementieva and myself will be able to update any Che and Codenvy images at any point of time? If so, then this is just some work to do - create all of the automated builds in Eclipse DockerHub account and point them to che-dockerfile repo.

**Comment by TylerJewell** [comment]
Yes
