### ISSUE TITLE
5.0.0-M6 Milestone Plan

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2740]
## Milestone Overview
- Bug fixes and cleanup
## Upgrade and Migration

This is a pre-GA milestone in the new Che 5 stream.

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.1 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live
## Target Milestone Issues
- [X] Find in path does not work kind/bug severity/blocker #2816  
- [X] Some commands that have worked through bash shell, can work wrong (regression) kind/bug severity/blocker #2811  
- [X] Unexpected error message 'Machine id' not found after refreshing a browser (regression) kind/bug severity/blocker #2794  
- [X] Amount of machines is not correctly displayed in process tree [Regression] kind/bug severity/blocker#2775  
- [X] Implement args syntax of build section in compose environment kind/enhancement #2661  
- [X] Documentation for Workspace Administration - Intro kind/docs #2659  
- [X] Leak of open file descriptors kind/bug #2633  
- [X] Do not try to connect to terminal if terminal agent not found in machine config kind/enhancement #2472  
- [X] Send schema associations to JSON language server kind/enhancement #2471  
- [X] Dev agent is not deployed to all machines kind/bug #2467  
- [X] svn switch missing from svn menu kind/enhancement #2456  
- [X] Stop workspaces before user removal kind/task #2438  
- [X] Projects are not removed after deleting a workspace kind/bug #2435  
- [X] Notify a user when he loses connection with Workspace Agent kind/enhancement #2369  
- [X] Wrong behavior after run command 'Delete' in Subversion plugin kind/bug #2350  
- [X] Improved tabbed editor design kind/enhancement #1841  
- [X] Make workspace creation and edit screens identical kind/enhancement #1769
