### ISSUE TITLE
Openshift Plugin Update

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2834]
Changes to Che and Openshift has caused plugin to break. The following are a list of items related to the Openshift plugin update and issues [https://github.com/codenvy/plugin-openshift/issues/36](https://github.com/codenvy/plugin-openshift/issues/36), [https://github.com/codenvy/plugin-openshift/issues/40](https://github.com/codenvy/plugin-openshift/issues/40) & [https://github.com/codenvy/plugin-openshift/issues/41](https://github.com/codenvy/plugin-openshift/issues/41).
- [x] Connect/Disconnect Account - 5.0.0-M6
- [x] Create Application From Template - 5.0.0-M6
- [x] Import Application - 5.0.0-M6
- [x] Unlink Project - 5.0.0-M6
- [x] Delete Project - 5.0.0-M6
- [x] Manage Configs - 5.0.0-M6
- [x] Start Build - Next Sprint after M7  [https://github.com/codenvy/plugin-openshift/issues/40](https://github.com/codenvy/plugin-openshift/issues/40)
- [x] Add Service - Next Sprint after M7 [https://github.com/codenvy/plugin-openshift/issues/41](https://github.com/codenvy/plugin-openshift/issues/41)
- [x] Deploy New Application - 5.0.0-M6
- [x] Link With Existing Application - 5.0.0-M6
- [x] [Update Docs](https://eclipse-che.readme.io/v5.0/docs/openshift-user-guide)

Current "Start Build" and "Add Service" issue:
`Response from the OpenShift API: {"message":"deploymentconfigs \"configname\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again"}`

We need to run our own instance of openshift locally to test.

**Comment by JamesDrummond** [comment]
@eivantsov @ddementieva Can you label this kind/bug current-sprint team/plugin.

**Comment by ashumilova** [comment]
@JamesDrummond appropriate issues are included to current sprint of plugin team and have those labels:
- [start build fail](https://github.com/codenvy/plugin-openshift/issues/40)
- [add service fail](https://github.com/codenvy/plugin-openshift/issues/41)

**Comment by bmicklea** [comment]
@JamesDrummond can you update the actual epic definition to includes links to each of the issues for items you have checkboxes for?
