### ISSUE TITLE
Command Explorer + Command Editor

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#2898]
Need to implement Commands Explorer for managing commands.
Should be possible to manage workspace commands and project commands.

## Subtasks:
- [x] Command Explorer Panel #2995
- [x] Command Editor - Info view #2996
- [x] Command Editor - Arguments view #2997
- [x] Command Editor - PreviewURL view #2999

**Comment by TylerJewell** [comment]
@azatsarynnyy @slemeur - link into epic on intelligent commands.

**Comment by slemeur** [comment]
@azatsarynnyy + @vparfonov : Would it be okay for you if I split this issue into the following sub-tasks:
- Command Explorer panel
- Command Editors
  - Info view
  - Arguments view
  - PreviewURL view

Would make it simpler to follow - but it is up to you guys ;)

**Comment by azatsarynnyy** [comment]
I'm OK with it
