### ISSUE TITLE
5.0.0-M7 Milestone Plan

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#2935]
## Milestone Overview
- Visual stack editor
- SSH improvements
- Improved Che mount container utility
- Compose improvements
- Clarified snapshotting language

## Upgrade and Migration

This is a pre-GA milestone in the new Che 5 stream.

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.1 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **Target: November 9, 2016**
- GitHub release complete (QA verified) milestone: **Target: November 11, 2016**
#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete
#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live
## Target Milestone Issues
- [x] User Workspace SSH Improvements #2059
- [x] Change ssh text displayed in the IDE #3045
- [x] File watchers don't always work as expected #2876
- [x] CODENVY-804 : Use of userManager to get the userId (when injecting ssh keys) #3036
- [x] Cannot save previewURL into a command (regression) #2966
- [x] cli: che ssh and che mount commands #3033
- [x] Revert changes after #2867 #3015
- [x] The number of machines is not correctly displayed in the tree if you add workspace using URL #2892
- [x] Terminal is not available after restart workspace (regression) #2983
- [x] Windows boot2docker fails starting new che-server under certain conditions #3024
- [x] CHE-2059 Add ssh view for workspace in UD #2980
- [x] Fixes #2728: Respect user settings when sending formatting options to LS #2735
- [x] Wrong behavior of panel 'Processes' after refresh (regression) #3001
- [x] CHE-2454: add replacing of double underscores #2664
- [x] A lot of space is used for empty panel #2987
- [x] Multi-Machine Workspace creation #2979
- [x] CHE-2979: fix display machines name in RAM widget #3009
- [x] Not all editor tabs are closed after stopping workspace (regression) #2372
- [x] Predefined commands do not appear in the command widget (regression) #2984
- [x] Contribute PatternFly starter template #2990
- [x] CHE-2059 Add unison agent for che-mount utility #2978
- [x] CHE-2059 : Each time a workspace is created, register/associate ssh key #2949
- [x] Upgrade gulp-stylus version #2814
- [x] "No workspace selected. Unable to open IDE" displayed while opening the IDE #2820
- [x] CHE-2820: Don't show "No workpsace selected" message when IDE is loading #2957
- [x] Fix links for websockets #2964
- [x] Simplify names of che.properties to be user friendly #2015
- [x] Make agents list fit the styles of other lists in machine's section #2824
- [x] CHE-2824: fix agents list #2956
- [x] OAuth protocol from github does not work #2944
- [x] Improve selected state in textfield for dark theme #2689
- [x] fix usage of CHE_DATA in Che Server #2941
- [x] Detect and stop/remove Machines not counted by API (regression) #2927
- [x] Latest X>5 che-pullrequests-build failed due to git tests #2888
- [x] Samples configuration improvements #2883
- [x] #2059 SSH improvement : whenever as a user I open up the SSH panel, i… #2903
- [x] Compose Syntax Links Not Working. #2687
- [x] Remove workspace id from websocket connection path to master #1787
- [x] Resolve project type after adding all commands #2928
- [x] CODENVY-1007: add erb extension support as ruby template #2947
- [x] Array format unsupported for environment in compose file #2624
- [x] Incorrect alignements in Stack screen #2893
- [x] Add servers to Agent description and propagate them to Workspace Runtime #2832
- [x] Display raw JSON configuration of the stack #2519
- [x] Add ability to define stack's components #2517
- [x] Wrong behavior with stack bulk operation #2727
- [x] Add ability to set stack's category (advanced, general) #2516
- [x] Add ability to configure machines inside stack definition #2515
- [x] Add ability to configure machines inside stack definition [CHE-2515] #2734
- [x] CHE-2654: Changing Agent REST API (adding 'id' and 'description' fiel… #2861
- [x] Simplify Tomcat che.sh bootsrap script #2786
- [x] CHE-2015 Rename configuration properties #2707
- [x] Introduces changes needed to be used by teams in codenvy #2918
- [x] Suppress talkative log output #2896
- [x] Remove UD notification when workspace is created #2627
- [x] Add SNAPSHOTTING status tracking and remove obvious notifications #2875
- [x] Che launcher: not clear error message #2777
