### ISSUE TITLE
Project Samples Management in Dashboard

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#2970]
We recently added the ability to manage the Stacks from the dashboard.

We need to provide the ability to manage the Samples.

Tasks:
- [ ] List for samples #2967
- [ ] Ability to edit/create samples #2968
- [ ] Advanced configuration for samples #2969

**Comment by TylerJewell** [comment]
When working on the latest documentation, I was finding the word "Samples" to be confusing, because I kept thinking it was a "workspace sample". So, to be clear in documentation and in our product, we are going to need to always call it Project Samples for clarity.

**Comment by gorkem** [comment]
@slemeur Is this epic still valid?

**Comment by slemeur** [comment]
It is still relevant in the context of an hosted Che.

If I'm providing a Che instance to my team - as an admin, I'd like to customize the list of available stacks and project samples. So I can remove the stacks that I don't need and add the one that are needed for my developers. Similarly, I will edit the list of pre-defined samples so that developers have the right set of project samples when they create new workspaces with the stacks that I defined. 

This will need to be manage in the same fashion as we did for stacks.

**Comment by ghost** [comment]
@slemeur do you suggest we need samples API similar to stacks?

**Comment by slemeur** [comment]
Yes, the same approach: API + UI under dashboard.

**Comment by gazarenkov** [comment]
-1
IMO it will make the things more complex and I do not see a lot of profit with this API.
Moreover, I would reconsider the Stacks, considering merging stacks and factories and make one **persisted workspace with additional metadata** (things for automation (elements from factory) and tags (from stacks) entity

**Comment by slemeur** [comment]
Can you describe the use case you have in mind?
