### ISSUE TITLE
Simplify flows when creating a workspace

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#3048]
We are currently having the ability for a user to create a workspace and define the workspace runtime definition at the same time. The experience is not efficient for various reasons:
- Defining the runtime needs the user to go into the "Runtimes" tabs
- While we provide the ability to edit the recipe, we should show correct error messages about the syntax that we are supporting
- The flow to configure the different machines is 
- There is no capabilities to test the runtime

We are about to merge a better experience, dedicated to the creation of stacks #2316 + add a new stack library widget #2971. 

In order to simplify the usability of the creation workspace flow, we will do the following improvements:
- [x] Remove the ability create a workspace from a custom stack 
- [x] Remove ability to use a recipe from a URL 
- [x] Add button to "Add Stack" which will redirect to #2971 screens
- [x] Restyle label container in dashboard https://github.com/eclipse/che/issues/3212
- [x] Restyle input field in dashboard https://github.com/eclipse/che/issues/3213
- [x] Create spinner widget https://github.com/eclipse/che/issues/3214
- [x] Create widget for displaying advanced filter https://github.com/eclipse/che/issues/3392
