### ISSUE TITLE
5.0.0 Milestone Overview

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3093]
## Milestone Overview
- GA release for 5.0.0

## Upgrade and Migration

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.1 workspaces to 5.0.0 .

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **Target: January 7, 2017**
- GitHub release complete (QA verified) milestone: **Target: January 7, 2017**

#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete

#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live

## Target Milestone Issues
- [x] Fix package/deploy issue of docs. kind/task #3563  
- [x] Privileged mode does not work kind/bug  #3549  
- [x] Not all files are deleted from editor after deleting parent folder(regression) kind/bug #3536  
- [x] File unexpectedly disappears from editor after rename (regression) kind/bug severity/blocker  #3535  
- [x] Content of file is not update after git checkout (regression) kind/bug severity/blocker  #3532  
- [x] Change access to docs from dashboard #3524  
- [x] Docs maven build kind/docs #3510  
- [x] The editor is empty after restart workspace(regression) kind/bug severity/blocker #3499  
- [x] Unexpected notification 'Running tests' after call 'Navigate to File' kind/bug #3478  
- [x] Unexpected appearance of empty split panel after first starting of workspace kind/bug #3460  
- [x] Add Servers section to machine details kind/enhancement   #3456  
- [x] Clarify how Che uses private docker registry for snapshots kind/docs kind/task   #3442  
- [x] We have red output after launching tomcat for the Spring project kind/bug  #3439  
- [x] After applying new exec agent some commands may be invalid kind/bug severity/blocker #3438  
- [x] Any command is not performed in the not dev-machine (regression) kind/bug severity/blocker  #3435  
- [x] The command line is empty into console after run (regression) kind/bug severity/blocker  #3434  
- [x] Preview URL is lost after refresh page(regression) kind/bug severity/blocker  #3433  
- [x] Cannot open package in a particular project kind/bug severity/blocker #3426  
- [x] Update CI Systems kind/task  #3423  
- [x] Revamp Che docs for 5 kind/docs  #3406  
- [x] CLI Docker Daemon Check kind/bug severity/blocker  #3384  
- [x] Impossible to delete existing workspace kind/bug severity/blocker  #3372  
- [x] Can't select text in the terminal panel kind/bug severity/blocker #3370  
- [x] Git history panel is not opened (regression) kind/bug severity/blocker   #3369  
- [x] Can't connect to Che server with debug session kind/bug severity/blocker  #3367  
- [x] Sometimes workspace fails to start or projects are failed to initialize kind/bug severity/blocker #3363  
- [x] Git History blocks with large projects kind/bug  #3353  
- [x] Che does not start after toggling dev mode on / off from CLI kind/bug severity/blocker  #3351  
- [x] CHE_HOST variable is not working as expected kind/bug severity/blocker #3350  
- [x] Configure Master & Agent JVMs to Inherit Proxy Settings kind/bug severity/blocker  #3319  
- [x] Workspace RUNNING status event is not published after SNAPSHOTTING status kind/bug  #3314  
- [x] Can't resize process window when there is download file in chrome browser kind/bug  #3298  
- [x] Make process of snapshot removal asynchronous. kind/task   #3258  
- [x] Display version number in dashboard kind/enhancement  #3257  
- [x] Mark org.eclipse.che.ide.api.resources.VirtualFile#getMediaType as deprecated kind/task  #3235  
- [x] Remove deprecated org.eclipse.che.ide.api.resources.VirtualFile#getPath kind/task  #3233  
- [x] Open of new terminal doesn't show processes tab kind/bug   #3223  
- [x] Open create workspace failed. kind/bug  #3183  
- [x] HotKeys hints for import/create projects does not appear in browser under anonim mode kind/bug #3167  
- [x] Che version should be visible on the user dashboard kind/enhancement  #3154  
- [x] Cannot select an item in the terminal kind/bug #3140  
- [x] After reset or shut down computer CHE networks still exist. kind/bug  #3135  
- [x] Project can't be created without Z option kind/bug kind/question #3129  
- [x] Issues with Language Servers kind/bug    #3127  
- [x] Maven dependency resolver continues to run after workspace is stopped kind/bug  #3121  
- [x] Add Sourcegraph TypeScript Language Server to the Che kind/task   #3119  
- [x] Access to workspace freezes when loading moderately big maven project kind/bug severity/blocker  #3115  
- [x] Websocket connection fails on workspace kind/bug  #3109  
- [x] machine.getOwner() should return userId and not namespace kind/bug #3042  
- [x] Eclipse Che CLI Refactoring + Improvements kind/epic #2977  
- [x] Use base images from eclipse DockerHub organization kind/task  #2942  
- [x] Better handle "Process Panel" when commands are long kind/enhancement  #2911  
- [x] Improve "Recent Workspaces" behaviors kind/enhancement  #2908  
- [x] Wrong hover tooltip behavior kind/enhancement  #2846  
- [x] The newly created worksapce is not removed on Dashboard kind/bug  #2819  
- [x] Language Server formatting options are hardcoded kind/bug #2728  
- [x] IDE is trying to get projects while the workspace is not started kind/bug  #2629  
- [x] Project import/creation performance issues kind/bug  #2602  
- [x] Separate commands execution API from main API kind/task   #1946  
- [x] Execute commands directly on machine kind/enhancement kind/epic #1944  
- [x] Language Server Protocol: ShowMessage Notification feature kind/enhancement  #1793

**Comment by riuvshin** [comment]
@bmicklea should we close this?
