### ISSUE TITLE
5.0.0-M8 Milestone Overview

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#3094]
## Milestone Overview
* Create and edit workspace using raw config
* REST method improvements for Projects
* Improved highlight in project explorer
* Use OpenJDK in che-server
* Updated .NET Core Template

## Upgrade and Migration

This is a pre-GA milestone in the new Che 5 stream.

Due to a fundamental model change that allows us to deliver multi-machine support, it will only be possible to migrate 4.7.1 workspaces to 5.0.0 at GA (users who wish to try 5.0.0 milestone releases today will have to create new workspaces).

**Docker Image Tags**
While 5.0 is pre-GA the `:latest` tags on our Docker images will continue to point to 4.7.1. We will also create a new `5.0.0-latest` tag to make it easier to try each 5.0.0 milestone release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule

This release will be an Eclipse-signed and marketed release.
- Code complete milestone: **Target: November 9, 2016**
- GitHub release complete (QA verified) milestone: **Target: November 11, 2016**

#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs complete

#### GitHub release complete (QA verified) milestone
- [x] Release completed and QA verified
- [x] Release notes updated
- [x] Final release information updated on GitHub
- [x] Docs reviewed and live

## Target Milestone Issues
- [x] Import project from dashboard does not work kind/bug severity/blocker #3226  
- [x] Apaide? Should maybe be Apache? kind/bug #3205  
- [x] "Restoring project structure..." loader doesn't hide in the workspace without projects. kind/bug #3181  
- [x] The editor has wrong behavior after restart workspace kind/bug severity/blocker  #3175  
- [x] Workspace does not start from 'Bitnami Codeigniter' stack on dashboard kind/bug #3173  
- [x] org.eclipse.che.ws-agent should check java version before starting kind/bug severity/blocker #3137  
- [x] Cannot start workspace kind/bug severity/blocker   #3062  
- [x] Remove temporary workspaces on server shutdown kind/task   #3044  
- [x] Create and edit workspace using raw config kind/enhancement  #3025  
- [x] The expanded project is collapsed when workspace is restarted (regression) kind/bug   #3021  
- [x] Unexpected enabling of the button create workspace kind/bug #3019  
- [x] Cannot start a workspace from centos:6.6 kind/bug severity/blocker #3011  
- [x] Cascade deletion of projects with the same storage fails kind/bug   #2993  
- [x] Adding ssh key by OAuth GitHub form does not work kind/bug  #2988  
- [x] REST method for batch creating Projects suitable for both import and generate kind/enhancement  #2937  
- [x] Switching editor tabs should move the highlight in the project explorer kind/enhancement  #2934  
- [x] Docker networks are not deleted when the corresponding workspace is stopped kind/bug severity/blocker  #2930  
- [x] Git history area is not restored after refresh page (regression) kind/bug  #2924  
- [x] Use OpenJDK in che-server CentOS Dockerfile kind/task #2916  
- [x] can not clone from IP address in the URL kind/bug  #2915  
- [x] Updating .NET Core Template and Maintainer kind/enhancement #2862  
- [x] Find in path does not work kind/bug severity/blocker  #2816

**Comment by bmicklea** [comment]
@JamesDrummond - can you update the milestone overview section - we need that for the release summary.
