### ISSUE TITLE
Refactor org.eclipse.che.ide.api.resources.Resource

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#3244]
- [x] Add utility methods for casting resources to their particular types https://github.com/eclipse/che/issues/3239
- [ ] Add copy/move/delete methods with caller object https://github.com/eclipse/che/issues/3241
- [x] Change signature of the org.eclipse.che.ide.api.resources.Resource#getParent https://github.com/eclipse/che/issues/3242
- [x] Add method for getting project https://github.com/eclipse/che/issues/3243
- [ ] Remove deprecation related to getRelatedProject() in Resource https://github.com/eclipse/che/issues/4012
