### ISSUE TITLE
Resource manager framework refactoring and unit test covering

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#3248]
#### The main goals of refactoring resource manager component is to:

- Clean up the existed codebase, which includes in removing deprecated methods from the model interfaces
- Freezing method signatures that were marked as `com.google.common.annotations.Beta` in main model interfaces
- Separate _**user level**_ and _**service level**_, this means that _**user level**_ should be responsible for providing interfaces to the user to operate directly with resources objects, that represent file objects on the virtual file system. In the same time, _**service level**_ should be responsible for providing and interface which will communicate with real implementation of particular resource manager. In this case resource manager definition can describe mechanism which operates with file system over http, java libraries, etc.
- Unit tests covering

### Analyzing tasks that should be completed during refactor process:
- [ ] Refactor `org.eclipse.che.ide.api.resources.Resource` https://github.com/eclipse/che/issues/3244
- [ ] Mark `org.eclipse.che.ide.api.resources.VirtualFile#getContentUrl` and create `org.eclipse.che.ide.api.resources.VirtualFile#getURL` https://github.com/eclipse/che/issues/3236
- [x] Mark `org.eclipse.che.ide.api.resources.VirtualFile#getMediaType` as deprecated https://github.com/eclipse/che/issues/3235
- [x] Remove `org.eclipse.che.ide.api.resources.VirtualFile#getMediaType` deprecated method https://github.com/eclipse/che/issues/3321
- [x] Remove deprecated `org.eclipse.che.ide.api.resources.VirtualFile#getPath` https://github.com/eclipse/che/issues/3233
- [ ] `ProjectServiceClient` refactoring https://github.com/eclipse/che/issues/4221
