### ISSUE TITLE
Desktop Installations of Che & Assemblies

### ISSUE THREAD

**Issue by TylerJewell** [eclipse-che/che#3250]
We will package up the Che client and associated dependencies as an Electron application suitable for offline installation on Windows, Mac, and Linux.

The general idea is that we can create native installers for different operating systems that include an Electron client, an optional installation for Docker Engine, and other dependencies that would be required to install and run Che in an offline mode, not connected to the Internet.

The electron client will run locally on the desktop and it's lifecycle will be dictated by the user double clicking the core icon, or closing the client window. These actions will drive events to the local Che.

It will also be possible with various onboarding workflows to use the electron client with remote Che instances, such as Codenvy.io or Artik.io.

- [x] Create electron client packaging for Windows (exe), Mac (dmg), and Linux (zip / tgz).  The electron packagaing should have a nice icon for the product that it represents, provide minimize / maximize, and also have an icon that appears in the system tray when minified.
https://github.com/eclipse/che/issues/3308

- [ ] Design and implement a new onboarding workflow when a user opens the electron client. The onboarding workflow can be configured differently for different Che assemblies.  For ARTIK, the onboarding should assume that a user can either run ARTIK IDE locally, or they can connect to a remote ARTIK IDE server. If connecting to a remote server, the URL + PORT would be needed, but no user name or password.  For Che + Codenvy, this should be a common onboarding flow, and there would be a sequence for connecting locally, to a remote che (no user / pass), or to a remote codenvy (requires user / pass).  In the Codenvy scenario, if a user wants to connect their electron client to codenvy.io or another codenvy system AND they do not have an account, we should provide a link in the electron client that the user can select to take them to an iframe where they can create an account on that Codenvy system.

- [ ] If the electron client is connecting to a local Che, then the electron client should have some basic configuration saved within it for the CHE_HOST and the CHE_PORT. It will first test to see if a Che server is running on that host + port. If there is one running, then connect to it.  If there is not one running, then it should use the Che docker CLI to start a new one, and then connect to it.  We will need PM to design intelligent loaders to let the user know that the Che server is starting in the background, and if it fails, we should let them see the logs of the failure. 

- [ ] When closing the Electron client, we should have two modes, saved in the electron configuration locally. If using a local Che server, when closing the client, we should stop the local Che server. We can provide a configuration property of the electron client that determines if the Che server should be stopped or not overriding default behavior.  If the electron client is connected to a remote workspace, we should automatically stop all of the workspaces that we are connected to.  We can provide a configuration property of the electron client that determines if the workspaces should be automtaically stopped or not when the electron client is closed.

- [ ] As part of the .exe, .dmg wizard installers, we should include Docker for Windows and Docker for Mac. When doing an installation of the electron packaging on the system, we should test to see if Docker 1.11 is already present.  If it is not, and you are on a valid system where we can install Docker for Windows or Mac, we should offer to instlal it and launch the installers.  If not, then we should give users a link to the web site where they can install Docker Toolbox or the right configuration.
https://github.com/codenvy/artik-ide/issues/237
https://github.com/codenvy/artik-ide/issues/138
https://github.com/eclipse/che/issues/3386

- [ ] The installation should include TAR files for all of the images necessary to run Che for that particular version and the Che / Codenvy CLI. These would be the same images that are generated according to the docs today when we do 'cli offline'. We will also include at least one stack image as part of this.  If  it is ARTIK, we would include the ARTIK SDK stack image. If a user runs Che and it is not connected to the internet, it should try and use the locally saved images that were provided in the installation.
https://github.com/codenvy/artik-ide/issues/264
https://github.com/eclipse/che/issues/3391

- [ ] We should modify the user dashboard to be smarter about offline mode. If the system is not connected to the internet (or explicitly started in offline mode), we should gray out stacks that are not available in local TAR files. This would require us to add meta data to each of the stack's to indicate the list of docker images that are needed to run that stack, and then we could parse that list to detect if those images are available locally or not.

- [ ] We need to gracefully help users configure the electron client and how it interacts with the outside world.  The items of configuration that a user may need to configure could be done in a local configuration file, or perhaps as part of the onboarding GUI in a preferences window.  The configuration items include:
  - [ ] CHE_HOST / ARTIK_HOST / CODENVY_HOST
  - [ ] Local Only: CHE_PORT / ARTIK_PORT
  - [ ] Proxy Config: ALL_PROXY, HTTP_PROXY, HTTPS_PROXY, NO_PROXY (test conn to dockerhub)
  - [ ] Config property for stopping client: stop all remote workspaces?  yes / no
  - [ ] Config property for stopping client: stop local che server? yes / no
  - [ ] Default onboarding flow (local, remote)? --- skips onboarding screens
https://github.com/eclipse/che/issues/3390

- [ ] The installation should support uninstallation, which would delete the Electron client, any locally running Che servers, but leave the Che workspace data behind. We  would not uninstall Docker.
https://github.com/eclipse/che/issues/3387

- [ ] We would need a way to support upgrades. If a user gets a new version of the .exe installation and already has an electron client installed, how would the upgrade process work?  We should also verify that electron clients can be installed and run in Windows folders with spaces in the names.  We should also test this on Windows 7.
https://github.com/eclipse/che/issues/3388

- [ ] Update CI systems to generate specialized packages for Che, Artik, and Codenvy. These packages should be generated on each tagged release and made avaialble for download. If Che, then the download should also e posted on the Eclipse download servers.
https://github.com/eclipse/che/issues/3389
https://github.com/codenvy/artik-ide/issues/263

-  [ ] For docs and the eclipse.org/che web site, we will modify all of our getting started workflows for people who are running Che locally. We will need them to first start by installing the electron client, and then optionally they can install the docker version separately.

**Comment by kaloyan-raev** [comment]
One comment on this:

> The installation should support uninstallation, which would delete the Electron client, any locally running Che servers, but leave the Che workspace data behind. We would not uninstall Docker.

Is it possible to have user options for:
- delete Che workspace data too
- uninstall Docker too

It's really annoying when the uninstaller does not clean up everything. It would be appreciated if there is an option for the user to do so, if this is really wanted.

**Comment by TylerJewell** [comment]
Maybe - need to think about it some. We are going to have scenarios where sometimes we install Docker and sometimes we do not. So at a minimum, we would only offer to uninstall docker if we installed it in the first place. But this is really tricky stuff.

I am already really resistant to having an installer that installs Docker for our customers. I would much prefer that the customer installs and manages Docker on their own, especially when you are behind a firewall or a proxy. But we have customers that see us as a packaged solution so we are being pulled in this direction, though fairly reluctantly.

Docker is already tricky enough, so for us to take total ownership of the install / uninstall is wading into an area that feels like too broad of a scope.

**Comment by guiguan** [comment]
An option can be always provided (enabled by default) in the installer to install docker for a user :). Docker is too good to be abandended

**Comment by TylerJewell** [comment]
I think it's fairly apparent that we will need to track everything that we install, and during uninstall give the user clear list of what has been installed, and which software they want to install.  The list of installed software would be: a) Docker, b) Che, c) Che's OS-specific electron clients, d) Che's Docker images that it uses to run Che, e) local folder where workspaces are saved, f) electron client configuration.

**Comment by TylerJewell** [comment]
@bmicklea - the engineering work for artik should not be started until this epic is consolidated and clear with the other one.

**Comment by sr229** [comment]
I think the [Eclipse Two IDE Project](https://github.com/dschaefer/eclipse-two) has a great overview and potential for the issue.

**Comment by TylerJewell** [comment]
I think that project died before it ever got started - a week of intense commits and then stoppage.

**Comment by sr229** [comment]
still a good basis on what we want for the Electron Client though, although we may have to write from scratch entirely or base from that and rewrite everything

**Comment by TylerJewell** [comment]
What is more valuable to you?  It could be a desktop packaging with electron clients, which imposes certain memory and Node installation onto each desktop.  Or, the componentization of the IDE and workspace?  With the latter it becomes possible to partial load workspaces and the IDE within other products.  Imagine a GitHub style editor embedded on a web site with full language server and git support.

**Comment by sr229** [comment]
that idea would be nice since the current site editor is too minimal IMO, I'm all in for compnentinization since we can reuse some parts of Che in other projects without having pain to reinplement them

**Comment by TylerJewell** [comment]
I am not sure yet, but it may be the case that the series of optimizations that we would start to make around componentization of the IDE cause us to move in a direction that makes electonifying the client.  Though I am not sure yet.

Also there are some early efforts around writing a pure JavaScript client using electron in the eclipse foundation that could be hot deployed into a Che workspace.  It would be both a web and desktop client at the same time.

**Comment by sr229** [comment]
I also found this project but unfortunately, it's a non-Eclipse project but they have pretty much have compnentinized the IDE frontend and the server backend. It's called [Coding WebIDE](https://github.com/Coding/WebIDE). Could be worth looking as refrence?

**Comment by sr229** [comment]
Also my other concern is some Windows users doesn't have the proper edition to use Docker for Windows @TylerJewell , maybe include Docker Toolbox as fallback or introduce a build with Toolbox instead of D4W

**Comment by TylerJewell** [comment]
There is also this brand new project.  The architecture is cleaner but it imposes its own node server side which would be in parallel or in competition to the ws agents that we run.

https://github.com/theia-ide/theia

We have experience with doing wizard installers that include configuring or installing docker for the specific platform.  It made us build dozens of different type of packages for different installation scenarios on different OS, is not consistent between Linux, Mac, and Window, and made upgrade along with uninstall a real challenge.  Net - it was a lot of overhead to impose upon our engineering teams and for end user desktops for a use case that is not universally desired.

I am not waving the idea off, just trying to get you to understand that desktop installation and smooth operation requires a lot of clever engineering to make it light and predictable.

**Comment by sr229** [comment]
that would make perfect sense since it's really tricky to cover a wider audience while keeping the package small enough for people to donwload properly.
