### ISSUE TITLE
Custom Java formatting rules

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#339]
User should be able to choose which formatting rules to use
- at least basic rules, like use tab or 2 spaces for indent
- the best: import Eclipse formatting rule

Also need to make possible set formatting per project 
- [x] Add ability set formatting per project and for workspace #5724
- [x] Develop UI panel for changing Java code formatter preferences #5720
- [x] Develop service for importing Java formatter preferences form the file #5721

**Comment by sunix** [comment]
Sorry @TylerJewell , this is still a major issue, I am reopening it.

**Comment by sunix** [comment]
To me this is fixed with https://github.com/eclipse/che/pull/6077
I managed to import the google java formatter for eclipse from https://github.com/google/styleguide
and it seems to work well
