### ISSUE TITLE
Replace with old terminal UI based on  term.js to UI based on xterm.js

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#3529]
We will replace with old terminal UI based on  term.js to UI based on xterm.js. 
This epic consists of steps:
- [x] Investigate correct working xtermjs with requirejs  https://github.com/eclipse/che/issues/3517.
- [x] Integration  xterm.js to GWT code. https://github.com/eclipse/che/issues/3525
- [x] Improve xterm.js css styles to nice view. https://github.com/eclipse/che/issues/3526
- [x] Improve build xterm js using gulp tasks.We need it because native build based on bash script and this platform dependent solution. Gulp tasks is platform independent and we had already used this tool for user dashboard. Also we can contribute gulp build to xterm.js, because community is thinking about using this tool. https://github.com/eclipse/che/issues/3527
- [x] Fix losing text selection: https://github.com/eclipse/che/issues/3757. This is not bug of the xterm.js. This bug of the code integration.
- [x] Pass QA cycle.

**Comment by AndrienkoAleksandr** [comment]
xterm.js merged.
