### ISSUE TITLE
Machine API related house keeping

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#3612]
It is umbrella epic to cover cleaning all the machine API related things.

The problem is that as a result of evolution of our vision many abstractions, classes, UI components and even API(s) now looks odd.
It is a quite big pile of code which we do not effectively use but have to support, test and package.
But the even bigger problem is that such a code makes a big deal of confusing for community developers who is not familiar with the history.

- [x] Remove explicit workspace snapshot creation from IDE #3611
- [x] Remove machine API since it is not used anymore #3616
- [x] Remove Machine Perspective #3619 
- [x] Remove client side Machine API form IDE #3620
- [x] Move SSH machine implementation to separate plugin #3621
- [x] Move WsAgent and Terminal Checkers to agents module, check and clean #3827

**Comment by vazexqi** [comment]
Could you clarify on what "remove machine API since it is not used anymore" means?

Based on an earlier comment at https://github.com/eclipse/che/issues/2847#issuecomment-268334809
it seems that the Machine API can be used to create machines that are not just docker-based. Are you removing this feature and making an assumption that all machines in the future will be docker-based?

**Comment by TylerJewell** [comment]
no no - definitely keeping the ability to swap out docker runtimes for other runtimes. We depend upon that in a number of ways.  I think it was just a language thing in his explanation of how the API will be refactored.

**Comment by vazexqi** [comment]
Thanks for the clarification @TylerJewell.

**Comment by TylerJewell** [comment]
BTW - the 5.0.0 release has been made, though we have a lot of cleanup stuff around docs and other areas before we ship it. So you are seeing a lot of housekeeping issues being created as we are taking the next couple months to focus on performance, code cleanup, and other things to make the project easier to manage.
