### ISSUE TITLE
Show list of threads when debug is suspended

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#3707]
Show list of threads when debug is suspended.
It requires UI changes as well.

- [ ] JDB https://github.com/eclipse/che/issues/3708
- [ ] GDB https://github.com/eclipse/che/issues/3709
- [ ] Zend Debugger https://github.com/eclipse/che/issues/3710
- [ ] NodeJs Debugger https://github.com/eclipse/che/issues/3711
- [ ] UI  https://github.com/eclipse/che/issues/3712

**Comment by TylerJewell** [comment]
Consolidating this with the parent epic #2611 - we will track all debugger items in a single location.
