### ISSUE TITLE
Performance optimization activity

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#3792]
The goal of this epic is to collect all activities that can optimize performance of the product

- [x] Reduce amount of calls on get workspaces API call  https://github.com/eclipse/che/issues/3082
- [x] Investigate the ways to measure bootstrap performance using jvisualvm for codenvy in docker  https://github.com/codenvy/codenvy/issues/1466 
- [x] Avoid caching problem in http resources https://github.com/eclipse/che/issues/3492 
- [x] Revise referencing side of foreign keys https://github.com/eclipse/che/issues/3876
- [x] Dto streaming   https://github.com/eclipse/che/pull/3103
- [x] Consider to disable sendfile capability in Tomcat configuration https://github.com/eclipse/che/issues/3791
- [x] Remove unused GWT compiler permutation https://github.com/eclipse/che/issues/3784

**Comment by dyrone** [comment]
it's a great motion~ ^_^
