### ISSUE TITLE
Improve performance and usability of File Management System 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#4250]
The big part of IDE functionality is concentrated around file management operations. The most common operations performed on files or groups of files include creating, viewing, editing, renaming (including refactoring), moving or copying, deleting and searching. Folders and files may be displayed in a project tree based on their directory structure. Current implementation has some week places in our product, this issue is an umbrella issue for fixing those problems. 

- [x] Replace previous implementation of file watchers that is used for search index (based on inotify) with  scheduled file tree walking #4248
- [x] Client side resource management framework refactoring #3248
- [x] Remove redundant VFS layer #4249

**Comment by TylerJewell** [comment]
Closed this as it wasn't really a feature-driven epic definition.  It was just a loose collection of various other issues.
