### ISSUE TITLE
Factory and PR panel in che

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4290]
This is an epic to control work on Factory and PR panel implementation in Che

- [x] Move factory functionality from codenvy to che except dashboard part https://github.com/eclipse/che/issues/4091
 - [x] Init factory schema in che database https://github.com/eclipse/che/pull/4192
 - [x] Move dashboard part of factory functionality from codenvy to che https://github.com/eclipse/che/issues/4092
- [x] Move plugin-pullrequest from Codenvy to che  https://github.com/eclipse/che/issues/4093
- [x] Factory validations in Dashboard.  https://github.com/eclipse/che/issues/4291
- [x] Make sure dashboard are inherited factory functionality from che https://github.com/codenvy/codenvy/issues/1864
- [x] Make sure codenvy are inherited factory functionality from che  https://github.com/codenvy/codenvy/issues/1865

Adoption and adaptation of Factories for Che:
- [x] Rename `.codenvy.json` - https://github.com/eclipse/che/issues/4498
- [x] Rename `.codenvy.dockerfile` - https://github.com/eclipse/che/issues/4499
- [x] Remove {username} from named URL factories - https://github.com/eclipse/che/issues/4500
- [x] Make factory name mandatory https://github.com/eclipse/che/issues/4372  
- [x] Replace factory button - https://github.com/eclipse/che/issues/4501
- [x] Update link to factory docs - https://github.com/eclipse/che/issues/4502

QA on Factories for Che:
- [ ] QA on Factories for Che - https://github.com/codenvy/qa/issues/711

Documentation Items for Factories for Che:
- [x] Documentation for Workspace JSON object - https://github.com/eclipse/che-docs/issues/174
- [x] Explain how factories are handled when upgrading to a new version of Che - https://github.com/eclipse/che-docs/issues/175

**Comment by skabashnyuk** [comment]
@slemeur  can we close this issue. Or you want to close it after codenvy/qa#711 ?

**Comment by slemeur** [comment]
QA tests are part of the epic and definition of done. Epic will be closed once QA will be completed.
