### ISSUE TITLE
Improved Eclipse Che extensions development flow

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#4370]
The goal of this task is to provide up-to-date view how to build Eclipse Che extension. Before we can do that we would like to optimise couple of things.

1. ~~We need to have strong definition of the things that user can override and that is not.
Basically users don't have a choice to override Orion editor or docker. So it's not a plugin.
And giving them ability to override any components may be risky~~. #4430  

2. Setup of GWT compilation is quite long. https://github.com/eclipse/che/blob/871ef34f84ceb1a729faf1f12c8430e4e26d042f/assembly/assembly-ide-war/pom.xml#L345-L417 We agree with Florent's opinion that it would be nice
to combine all of that in single maven plugin  che-gwt-maven-plugin. 
The goal of this plugin is to provide any necessary actions for GWT compilation in single place.
Also it should fail fast if some gwt components are missing with good error message. GWT error messages is quite hurd to read. https://github.com/eclipse/che/issues/4373

3. ~~We also would like to make a two concept "Base" and "Default" assembly of agent-server and
agent-client.
   "Basic" - means the minimum set of components necessary to run IDE and edit file.
   "Full" - means default functionality of Che or Condenvy.
In this way users may decide: does they want to have something really small and simple or
they want to extend che or Codenvy  https://github.com/eclipse/che/issues/4403~~
 
4. Add to @org.eclipse.che.ide.api.extensio.Extension parameter that will describe path to the gwt.xml file for corresponding module. By default if this parameter is not set try to use file with same name like annotated class but with extension gwt.xml. This allows us before GWT compilation phase check all inherits and throw exception if declared module not found in classpath.  https://github.com/eclipse/che/issues/4404

- [x]  Move plugin-dashboard to ide core https://github.com/eclipse/che/issues/4614
- [x] Move che-plugin-machine-ext-client to IDE core https://github.com/eclipse/che/issues/4596
- [X] Find a better place for classes from che-plugin-sdk-env-local https://github.com/eclipse/che/issues/4595
- [X] Make che-plugin-product-info optional for IDE core https://github.com/eclipse/che/issues/4594
- [x] Move into separate module OAuthTokenProvider from che-core-api-auth https://github.com/eclipse/che/issues/4462
- [x] Plugin-docker is not a plugin  #4432
- [X] Make plugin-factory part of ide core and wsagent https://github.com/eclipse/che/issues/4619
