### ISSUE TITLE
Replace everrest based Websocket calls with new RPC framework. 

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#4459]
The goal is to dismiss `Everrest` mechanism which opens Websocket channel to output long-lived async calls and use new JSON-RPC on top of Websockets instead (the one we currently use for FS Watchers and Exec agent).

This should be applied to every side of a triage: client-machine-master.
Proposed tactic is following:

- [x] Add it to the master side and use for IDE-Master connection. The goal - to clean IDE removing Master Message Bus entities and prepare removing Everrest WS (EWS) components from the Master.  
  - #4275 - Rework client for Project service in order to avoid using Everrest based Websocket calls - **DONE**
- [x] (may be performed in parallel with 1) Do the same for Machine (Agent) - IDE connection, remove Machine Message Bus from IDE (according to priority)
  - #4591 - Switch project importing output to the websocket JSON-RPC API endpoint - **DONE**
  - #4593 - Switch Debugger functionality to the websocket JSON-RPC API endpoint - **DONE**
  - #5346 - Rework client for Git service to avoid using `Everrest` based Websocket calls -  **DONE**
  - #5349 - Rework Java plugin to avoid using `Everrest` based Websocket calls - **DONE**
  - #5350 - Rework Maven plugin to avoid using `Everrest` based Websocket calls - **DONE**
  - #5351 - Rework Testing plugin to avoid using `Everrest` based Websocket calls - **DONE**
  - #5348 - Rework Composer plugin to avoid using `Everrest` based Websocket calls - **DONE**
  - #5352 - Rework importing a project while consuming Factory to avoid using `Everrest` based  Websocket calls - 2d - **DONE**
  - #5522 - Rework Navigate to File feature to avoid using Everrest based Websocket calls - **DONE**
  - #5523 - Rework Find Usages feature to avoid using Everrest based Websocket calls - **DONE**
  - #5524 - Rework Language Server plugin to avoid using Everrest based Websocket calls - **CANCELLED**
- [ ] (depends on 1) Declare `EWS` mechanism/components as deprecated, apply new implementation for UD - Master connection and remove `EWS` using there in 4 weeks. 
  - https://github.com/eclipse/che/issues/4763 - [dashboard] Use JSON RPC instead websocket requests on master API - **ANALYZING**
- [ ] (depends on 2) same as 3 for Machine (Ws-Agent).   
  - https://github.com/eclipse/che/issues/5358 - [dashboard] Use JSON-RPC instead websocket requests on workspace agent API - **ANALYZING**
- [ ] Remove EWS from workspace master in SPI branch 
  - https://github.com/eclipse/che/issues/5357 - Clean workspace master of `EWS` - **ANALYZING**
- [x] Rework CLI to avoid using Everrest based Websocket calls #5841

**Comment by azatsarynnyy** [comment]
I've added three more tasks (#5522, #5523, #5524) to this epic since several features which use Everrest based Websocket calls were found recently.

**Comment by benoitf** [comment]
I think there are missing clients in the list (like CLI) and maybe others

**Comment by skabashnyuk** [comment]
@benoitf  CLI use Websockets ?

**Comment by benoitf** [comment]
@skabashnyuk AFAIK yes 
https://github.com/eclipse/che/blob/master/dockerfiles/lib/src/spi/websocket/messagebus.ts
https://github.com/eclipse/che/blob/master/dockerfiles/lib/src/api/wsmaster/workspace/workspace.ts#L124-L134

maybe there are other clients as well

**Comment by vparfonov** [comment]
@benoitf Can you take a look  https://github.com/eclipse/che/issues/5841? Looks like you are best person for it.
