### ISSUE TITLE
Actual bugs for intelligence commands

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#4511]
In the developing we have new command widget . Actual bugs : 
- [x] After deleting project with related process - process still presents https://github.com/eclipse/che/issues/4512
- [x] If the page refresh the Command Explorer closed with all commands tabs https://github.com/eclipse/che/issues/4514
- [x] After deleting project , project commands still present https://github.com/eclipse/che/issues/4515 
- [x] Add new goal with existing name  https://github.com/eclipse/che/issues/4516
- [ ] There is a error notification when create a new command after a project renaming https://github.com/eclipse/che/issues/4519
- [x] New created commands not added to the toolbar drop-down list https://github.com/eclipse/che/issues/4533
- [x] Can not clone or delete some default commands https://github.com/eclipse/che/issues/4540
- [x] Intelligence Command toolbar becomes broken when we consume a factory with incorrect commands parameters in json https://github.com/codenvy/codenvy/issues/2017
- [x] The EXEC widget is broken when a command name is very long https://github.com/eclipse/che/issues/4628
- [x] Randomly not work restore editor feature https://github.com/eclipse/che/issues/4627
- [x] If click on stop/rerun button drop-dawn list will be open https://github.com/eclipse/che/issues/4626
- [x] Not correctly work shortcuts for default "Run" and "Debug" commands (Alt+R , Alt+D) https://github.com/eclipse/che/issues/4625
- [x] Wrong text in tooltip https://github.com/eclipse/che/issues/4674

**Comment by musienko-maxim** [comment]
@slemeur, @TylerJewell   So, QA team are finishing cover the intelligence commands feature with selenium tests. For us very important - our test plan meet acceptance criteria for intelligence commands. Is there  sufficient coverage of functionality of this one? Please take a look on this document: https://github.com/codenvy/qa/wiki/Test-plan-of-intelligence-commands-feature

**Comment by slemeur** [comment]
Ok thanks.

I have reviewed the issues and closed few that are not bugs.

About the test plan:
- you need to consider tests around factories used cases (I tested them and they were working).

**Comment by musienko-maxim** [comment]
In this document describe short user story implemented in the selenium tests: https://docs.google.com/document/d/1zDEEWmxOu53omnkxnG8n3eyii-79utk5qeEZscTeGWg/edit?userstoinvite=ashmaraev@codenvy.com&ts=58db655a
Please answer: will it enough for acceptance?

**Comment by musienko-maxim** [comment]
Please review the tests for factories may be one of them cover workflow with I.C. If we do not have some usecases, please, provide this one for us. We do this

**Comment by slemeur** [comment]
This doc is covering usual factories flows. It is not covering how the new commands are handled in factories.

You should have those user stories related to Intelligent Commands:
- As a user, I have configured a workspace with commands. Commands are assigned to particular goals. When I'm going to the factories on dashboard, and creating a factory from that workspace I can use that factory and find the commands with the exact same configuration in the newly created workspace.

- As a user, I'm authoring a factory in json. When I'm defining commands, I can define the goal for each of the commands. When I'm using the factory, the commands are defined to the proper goals.

- As a user, I have configured a workspace with multiple project and multiple commands. I define a command to be scoped to only a single project. When I'm creating a factory from that workspace, and using it I can see this command only scoped to the same project. 

- As a user, I'm authoring a factory in json. When I'm defining commands, I can define the scope for applicable projects. When I'm using the factory, the commands are properly scoped to the right projects. 

- As a user, I can create my custom goal for commands in my workspace. When I'm creating a factory from that workspace, and using it, I can see commands defined in my custom goal.

- As a user, I'm authoring a factory in json. If I'm not providing goals to the commands, then when using the factory, the commands will be in the `Common` goal in the newly created workspace.

**Comment by musienko-maxim** [comment]
Ok, i will try add this one in the autotests. On this moment we will do this in manual mode.

**Comment by TylerJewell** [comment]
In future, we should reserve epics for end user stories and not really use them as just a collection of like-minded bugs.  

It was really impressive how much we did here, though.
