### ISSUE TITLE
Workspace Infrastructure SPI for v6

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#4736]
Current SPI which provides machines instances is outdated.
Originally it was reworked from v3 implementation where we used it for shared builder/runner.
Then we were oriented to one machine (mostly Docker container) workspace.
As a result it is not good adopted (too stricted) to new requirements such as multi-machine (Compose described) or other nature of infrastructure (such as Kubernetes/OpenShift) and we have to spend a lot of effort for workarounds trying to adopt it.

Base idea of new SPI is that interfaces to implement should be really light, contract not that stricted and as a result the main functional loading is put to concrete Infrastructure implementation.

Pilot implementation of this concept is placed in the "spi" branch.
https://github.com/eclipse/che/tree/spi
- [x] First draft of SPI specification https://github.com/eclipse/che/issues/5035 
- [x] Implement snapshotting concept in Docker SPI implementation https://github.com/eclipse/che/issues/5101
- [x] Rework SPI components to allow clients to get current state of Runtime while it is still starting https://github.com/eclipse/che/issues/5092
- [x] Create POC of Codenvy implementation of SPI https://github.com/eclipse/che/issues/5100
- [x] Rework Agent installation https://github.com/eclipse/che/issues/3971
- [x] Rework server pinging to make it more interactive and fast #5420
- [x] Specify IDE Application state phases and make it more clear https://github.com/eclipse/che/issues/4900
- [x] Provide all endpoints of an server as separate servers in Runtime #5609
- [x] Termination of workspace infrastructure #5570
- [x] Implement mechanism for providing unique ids for json rpc clients https://github.com/eclipse/che/issues/5439 (Dmitrii)
- [x] Investigate how to run IDE tooling in separate containers #5623
- [x] Che master doesn't restart properly in SPI branch #5610 
- [x] Provide links of the workspace to the client #5581
- [x] Add server health concept into infrastructure workflow. https://github.com/eclipse/che/issues/5093 
- [x] Run QA in SPI branch and figure out what should be done to adapt QA to SPI
###### TODO

Related epics & issues:
* Adapt che dashboard in the spi branch #5887
* SPI 6 Docker implementation #5639 
* OpenShift infrastructure implementation of SPI #5098

**Comment by benoitf** [comment]
I would say that usually we add diagram or concepts to explain the pros/cons and explain the new vision, we don't give a pointer to a branch

**Comment by gazarenkov** [comment]
@benoitf of course there will be more details and sub-issues very soon. Actually, it is quite clear for people who feel this pain. Let me know if you have some concrete questions or want to help.

**Comment by sunix** [comment]
@gazarenkov sorry it is actually quite UNclear. Is this related to having workspace agents in their own container ?

**Comment by gorkem** [comment]
@gazarenkov @garagatyi I understand the problem you are trying to solve but it is very hard to see how you intend to fix it. I think we need some more material for communicating this with others.
