### ISSUE TITLE
Add Commands Targets

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4964]
# Goals
Commands are applicable to certain contexts, projects and targeted machines. With the work we did with the issue #2681 we have introduced only a part of the context that is related to a single command - only the project. In the current implementation, when the user is in a multi-machine workspace, the user has to select the target machine before the execution of the command is triggered. 

The goal of this issue, is to allow the user to default the targets of a commands - so that the user is not asked to which machine, the command have to be executed accross. 

## Sub-tasks
- [x] Allow the user to default the targets of the command in its editors
We will handle that exactly the same way as we handle the projects:
- [x] When no targets defined, we need to continue to show the popup to select the target
- [ ] When multiple machines are defined as targets, we will show the popup to select the target once execution of the command is requested.

**Comment by skabashnyuk** [comment]
@slemeur do you want to keep this issue?

**Comment by slemeur** [comment]
Yes this is still valuable with new Theia IDE and workspace.next.
cc @azatsarynnyy

**Comment by gorkem** [comment]
@slemeur Is there anything else left to do for this one? Can we close it?

**Comment by azatsarynnyy** [comment]
Everything is done in Che 6.
Closing as Che 6 editor is no longer under active development.
