### ISSUE TITLE
Add ability for user to select command goals to be displayed in command controller

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#4965]
# Goal
The goal of this enhancement is to allow a user to select the goals to be displayed in the controller bar. At this moment, we are showing "Run" and "Debug" goals, but some users may want to display other buttons for the other goals. 

We will:
- Add the "Build" button in the default set of buttons displayed.
- Add ability in the preferences of the IDE to configure the command controller.

##  Sub-tasks
- [ ] Goals button to be displayed will be configured per workspace and per user (in case the workspace is shared). When sharing a workspace (or a factory), the buttons displayed will be shared as well with same the user's configuration.
- [ ] Add the "Build" button in the default set of buttons displayed.
- [ ] Add ability in the preferences of the IDE to configure the command controller. We will add a new section in IDE, called "Commands". Text in the page will be "Select command goals to display in controller bar:" and then we will add one option for each goals with a checkbox.

**Comment by skabashnyuk** [comment]
@slemeur do you want to keep this issue?

**Comment by slemeur** [comment]
Close as won't be fixed with the switch to Theia IDE
