### ISSUE TITLE
OpenShift infrastructure implementation of SPI

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#5098]
Implement Che6 Infrastructure for K8s/OpenShift environment
- [x] Implement initial state for Openshift spi https://github.com/eclipse/che/issues/5686
- [x] Link recipe and configuration machines https://github.com/eclipse/che/issues/5687
- [x] Rework resolving of machine's servers https://github.com/eclipse/che/issues/5688
- [x] Add health checks for servers in openshift spi https://github.com/eclipse/che/issues/5689
- [x] Implement environment provisioning in openshift spi https://github.com/eclipse/che/issues/5690
- [x] Add using of persistent volumes for storing sources of projects https://github.com/eclipse/che/issues/5691
- [x] OpenShift infrastructure doesn't work on Minishift because of dependency on Docker runtime #6085
- [x] Remove old workspaces volumes in OpenShift infrastructure #6081 
- [x] Prefix names of objects in OpenShift recipe on provisioning step https://github.com/eclipse/che/issues/5963
- [x] Ignore Routes that are specified in OpenShift recipe https://github.com/eclipse/che/issues/6216
- [x] Implement stop of OpenShift workspace when one of machine is crashed https://github.com/eclipse/che/issues/5922
- [x] Add ability to create all user's workspaces in one OpenShift project https://github.com/eclipse/che/issues/6284
- [x] Investigate why OpenShift SPI doesn't work on OCP https://github.com/eclipse/che/issues/6607
- [x] Check machine entries in workspace config on estimation in OpenShift infra implementation https://github.com/eclipse/che/issues/6274
- [x] Show workspace Pod events in the IDE https://github.com/eclipse/che/issues/6356
- [x] Rework injecting of machine token into OpenShift machine https://github.com/eclipse/che/issues/6587
- [x] Modify selenium tests to test OpenShift infrastructure #6083
- [x] Fix leak of connection to OpenShift https://github.com/eclipse/che/issues/5902
- [x] Support recipes of type dockerimage #5904
- [x] Add "openshift" recipe processing on dashboard https://github.com/eclipse/che/issues/6629
- [x] [CHE 6] Implement different strategies of PVC for OpenShift infra https://github.com/eclipse/che/issues/6774
- [x] Make bootstrapping of OpenShift machines parallel https://github.com/eclipse/che/issues/7067
- [x] Add an ability to match machine configuration to OpenShift container by annotations https://github.com/eclipse/che/issues/7308
- [x] Foreign containers events are shown while a workspace starting https://github.com/eclipse/che/issues/7367
- [x] Che 6 on OCP: Failed Workspace Start https://github.com/eclipse/che/issues/7418 #
- [x] Move creation of folders in PVCs into start runtime phase https://github.com/eclipse/che/issues/7601
