### ISSUE TITLE
Java 9 Support 

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#5326]
Study and determine the tasks for Che to fully support Java 9

Issues reported by @benoitf at date of 16 october 2017:

compiling che with Java 9 blocker : 
- [x] Gwt and its maven plugin are not working with Java9
 need to update to HEAD-MASTER (2.8.2) and new gwt plugin
 https://github.com/eclipse/che/issues/6602

compiling issues with Java9 : plug-Ins errors with workarounds :

- [x] error-prone is not handling Java9 for now (ok with newer version
   + https://github.com/google/error-prone/issues/448

- [x] lot of maven plug-Ins need to be updated to their latest version to handle Java9 correctly
    + [x] https://github.com/eclipse/che/pull/5490 Avoid deprecated configuration for maven assembly plugin

- [x] tools.jar is referenced in debugger server (but tools.jar is gone with Java9)

- [x] plexus-component-metadata needs to be updated as well https://github.com/eclipse/che/blob/513aa19ebd121093746209fcc4b31697b1424331/plugins/plugin-maven/maven-server/maven-server-impl/pom.xml#L214-L217

- [x] eclipselink failures on Java9. Updating to EclipseLink 2.7.0 solves some issues
- [x] Mockito failures on Java9. We should update to a recent version of Mockito (2.10 release)
    - [x] mockito-all artifact is no longer existing
    - [x] mockitong incompatible with Mockito 2.x (usage of removed annotations)

- [x] gwt mockito is not working with Java9
I've provided https://github.com/google/gwtmockito/pull/73 but required to release a new version

- [x] Lucene failures on Java9. Updating to Lucene 7.0.0 solves some issues (current=5.2.1)

- [x] Usage of internal classes of JMX stuff
    - https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/util/SystemInfo.java#L76-L79

- [x] org.reflections and usage of Classpath (assuming that for example current classloader is a URLClassLoader is not working on Java9 as boot classloader is not anymore a URLClassLoader)

### Runtime

- [ ]: wrong path of logging.properties in Tomcat
          http://tomcat.10.x6.nabble.com/svn-commit-r1809434-in-tomcat-trunk-java-org-apache-juli-ClassLoaderLogManager-java-webapps-docs-chal-td5067587.html

(fixed in new Tomcat release)

**Comment by benoitf** [comment]
blocker : 
- Gwt and plugin is not working with Java9

workarounds:

- error-prone is not handling Java9 for now (we could use in a profile)
   - https://github.com/google/error-prone/issues/448

FindBugs maven plugin in 3.0.5 should fix Java9 support (not yet released)
- https://github.com/gleclaire/findbugs-maven-plugin/pull/53
- https://github.com/gleclaire/findbugs-maven-plugin/issues/52

- lot of maven plug-Ins need to be updated to their latest version to handle Java9 correctly

- tools.jar is referenced in debugger server (but tools.jar is gone with Java9)

- plexus-component-metadata needs to be updated as well https://github.com/eclipse/che/blob/513aa19ebd121093746209fcc4b31697b1424331/plugins/plugin-maven/maven-server/maven-server-impl/pom.xml#L214-L217

**Comment by TylerJewell** [comment]
Please move each of the issues into the main description, and then create sub-tasks for each item that we should pursue.

**Comment by gorkem** [comment]
@fbricon some more Java 9 stuff to follow up :)

**Comment by skabashnyuk** [comment]
Any idea how to deal with ```tools.jar is referenced in debugger server (but tools.jar is gone with Java9)```?

**Comment by benoitf** [comment]
@skabashnyuk in my experiment I was able to compile debugger server without tools.jar (I kept tools.jar dependency only in a profile enabled on java 1.8)

**Comment by azatsarynnyy** [comment]
FYI in Che6 we don't depend on the legacy mojo's gwt-maven-plugin anymore (which is tightly linked to a specific version of GWT). GWT 2.8.2, which supports running in Java 9, is already released.

**Comment by benoitf** [comment]
@azatsarynnyy yep, I already filed CQs for GWT 2.8.2 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14599

**Comment by azatsarynnyy** [comment]
@benoitf thanks, I've added CQ link to the issue https://github.com/eclipse/che/issues/6859

**Comment by benoitf** [comment]
I'm able to use GWT 2.8.2 + gwt mockito with a fix that I've provided upstream (https://github.com/google/gwtmockito/pull/73)
--> need to wait gwt mockito 1.1.8

**Comment by benoitf** [comment]
gwt mockito released a new version including my fix.
It has been merged in che-dependencies repository
so now, Che6 branch can be compiled by using JDK 9 as it was the last missing PR

**Comment by slemeur** [comment]
Closing : 
- The work needed to be done to be able to compile Che using JD9 has been completed.
- In order to provide Java9 support for end-users we will need https://github.com/eclipse/che/issues/6157

**Comment by dmytro-ndp** [comment]
@slemeur: it has turned out recently that our automated functional tests doesn't support Java 9 (issue #8852).
