### ISSUE TITLE
Test runner plugin improvement  

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#5429]
Tests maybe the most important part of development process, so we want to improve this feature and make it more useful. This is container issue for several tasks like UX improvement for test panel, debug test, incremental compiling and etc. 

- [x] Test runner launch tests on the same JVM with dev-machine #4679
- [x] Add ability to start tests for TestNG in debug mode #5316
- [x] Make possible to run all tests from project and package https://github.com/eclipse/che/issues/5725
- [x] Run JUnit tests which were included to @Suite.SuiteClasses annotation https://github.com/eclipse/che/issues/5728
- [x] Adapt JUnit4 runner according new test runner API #5473
- [x] Add ability to start tests for JUnit4 in debug mode #5475
- [x] Adapt PHP test runner according new API https://github.com/eclipse/che/issues/5729
- [x] Run custom set of tests https://github.com/eclipse/che/issues/5737
- [x] Run XML test suite for TestNG https://github.com/eclipse/che/issues/5886
- [x] Add an action for running to the editor context menu https://github.com/eclipse/che/issues/5890
