### ISSUE TITLE
Generic telemetry events infrastructure

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#5483]
Che should provide APIs for plugins that can be used to hook telemetry events generated by plugins and core parts of Che to different analytics systems. This should allow 

- [ ] Che assemblies to configure and use different data sinks 
- [ ] Plugins to publish their own telemetry events
- [x] LSP implementation should also be included #1796

**Comment by skabashnyuk** [comment]
@gorkem Do you think we should start thinking about some POC?

**Comment by gorkem** [comment]
@skabashnyuk let's revisit on prioritization.

**Comment by skabashnyuk** [comment]
may be related to this https://github.com/eclipse/che/issues/10288

**Comment by skabashnyuk** [comment]
Close in favor of 
https://github.com/eclipse/che/issues/10298 Che Tracing
https://github.com/eclipse/che/issues/10329 Che Monitoring
https://github.com/eclipse/che/issues/10290 Che Logging
