### ISSUE TITLE
Dogfooding improvements to use Che to build Che

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#5529]
Development experience is a topic of constant improvement and currently there is a bunch of issues that covers the most valuable features that are planned to be improved.
- [ ] Self-Hosting Che for Che development #6713
- [x] Enhance Java debugger functionality #2611
- [x] Add: Java refactoring "extract to method" #324
- [x] Test runner plugin improvement #5429 - depends on #6157
- [x] Improving search results #5174 - [DONE]
- [ ] Delete Java class from Project Explorer should consider as Refactoring #5549

For GWT (important for IDE client development)
- [x] GWT SuperDev Mode command does not work #2595 [INPROGRESS]

For JS/TS (important for User Dashboard development)
- [x] TypeScript project: autocomplete, go to declaration, find usages #5146

**Comment by gazarenkov** [comment]
Considered as Important for day-by-day using

**Comment by gazarenkov** [comment]
Here is some context:

In order to preparation discussion in Cherkassy.

Here is the list of IDE issues R&D consider as *critical* for Che internal using.

Common:
- slow and not reliable project explorer (especially with big project tree)
- fully reliable search/ file navigation
- code formatting
For Java
- not reliable class delete/rename/move feature
- debugger not stable enough and missed several important features
- unstable test unit runner
- autocompletion performance 
For GWT (important for IDE client development)
- broken Super Dev Mode
For JS/TS (important for User Dashboard development)
- TypeScript project: autocomplete, go to declaration, find usages

PMs' perceptions of it (comparing with other) would be really useful.

--------------

Thank you to the team for thoughtful preparation of this.

I have some learning questions:
1. How is our search unreliable today?
2. How is test runner unstable?
3. What is broken on super dev mode?

----------------

1. How is our search unreliable today?
 
Here problem not only in search, but in file navigation too. We already have several issues with project tree performance like this https://github.com/eclipse/che/issues/3891 . 
To make search more reliable we open file watching processes on all directorates/files in /projects this leads to this issue https://github.com/codenvy/codenvy/issues/1723 
 
2. How is test runner unstable?

It works ok for small project but useless for big project like Che with multi-module structure. 

 
3. What is broken on super dev mode?

Here also problem with multi-module project with many code source folders. When we develop first version of super-dev mode for Che we hardcoded all modules name in special command but when we add/remove/replace some Maven module this command won't work. So we need to in some way build those paths automatically. 

-------------------

In critical IDE issue I would add the simple text editing completion that is scrolling up my edit window.
When I ask for completion, my browser/edit windows is moving from where it was

here is a simple screencast
after I select code completion and hit enter with selected completion, my whole screen scrolls
Editor lines was from lines 65-95 and after I hit code completion the lines are 54-84

**Comment by gazarenkov** [comment]
![code-completion-move-my-screen](https://user-images.githubusercontent.com/578124/27896776-cd457e40-6224-11e7-91a3-396b583ad296.gif)

**Comment by benoitf** [comment]
@gazarenkov AFAIK the screencast you used is coming from the issue I created there https://github.com/eclipse/che/issues/4397 but this problem should have been fixed right now by https://github.com/eclipse/che/pull/4669


Yes we can't reproduce it anymore

**Comment by vparfonov** [comment]
Few comments:
1. slow and not reliable project explorer (especially with big project tree) - already fixed
2. About search we have good request here #5174
3. code formatting problem is  - user can't setup own rules for code format #339
4. not reliable class delete/rename/move feature - #5549
5. unstable test unit runner - not good description for problem can find more here #5429
6. autocompletion performance - looks like work fine for now can be depend on network

**Comment by sunix** [comment]
I've added #340 Formatting xml files as part of `Code formating`

**Comment by vparfonov** [comment]
Remove code formater because in current state this not critical for Dogfooding you always can format code with `mvn fmt:format`

**Comment by sunix** [comment]
@vparfonov can we format xml files with mvn fmt:format ?

**Comment by vparfonov** [comment]
@sunix I am not usre about any XML but pom.xml ypu can format with mvn sortpom:sort
