### ISSUE TITLE
Stabilize workspace creation flow from QA feedback

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#5597]
## Bugs
- [x] There is not an error notification while creating a workspace with wrong name https://github.com/eclipse/che/issues/5600
- [x] Workspace is not started when RAM not in 0.5 step and error message is not shown https://github.com/eclipse/che/issues/5601
- [x] Can't move intelligence command to another goal https://github.com/eclipse/che/issues/5606
- [x] Creating workspaces/stacks from a custom recipe is missing from UD https://github.com/eclipse/che/issues/5616
- [x] Error message is not shown when used not valid WS name https://github.com/eclipse/che/issues/5647
- [ ] Creating stacks names with symbols : "-" , "+" , "." is possible https://github.com/eclipse/che/issues/5649
- [ ] Wrong stacks sorting https://github.com/eclipse/che/issues/5650
- [x] A project, imported from github by url without '.git' ending, is not added to a workspace https://github.com/eclipse/che/issues/5640
- [ ] No error notification appears when trying to create a workspace while there is not available RAM https://github.com/codenvy/codenvy/issues/2325

## Enhancements
- [x] Create a new workspace: show quick starts tab first https://github.com/eclipse/che/issues/5591
- [x] Improve experience when adding projects: https://github.com/eclipse/che/issues/5633
- [x] Filters widget improving: https://github.com/eclipse/che/issues/5599
- [ ] Can't quick select the user's custom created stack https://github.com/eclipse/che/issues/5602
- [ ] Add stack with predefined options https://github.com/eclipse/che/issues/5605

**Comment by dmytro-ndp** [comment]
From the end user point it would be quite useful to restore an ability to just create workspace but doesn't run it instantly (by default):
- in case of lack of system memory
- in case of first time of Che usage when user doesn't ready to launch workspace
- in case of Codenvy license has reached user limit, and run of workspace is forbidden (an issue https://github.com/codenvy/codenvy/issues/2329).

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa are you interested in this epic?
