### ISSUE TITLE
SPI 6 Docker implementation

### ISSUE THREAD

**Issue by gazarenkov** [eclipse-che/che#5639]
The goal is to create (local) Docker implementation of SPI https://github.com/eclipse/che/issues/4736 (partially adopt, partially rewrite v5 one)

As for the time being it is already implemented and requires improvements only, I just would like to decouple Docker issues from SPI issue (which contains big amount of sub-tasks already) itself to make it clear.

- [x] Cleanup Docker implementation https://github.com/eclipse/che/issues/5095
- [x] Make Docker SPI implementation pass events to master that should pass it to clients #5125
- [x] Implement channel with infrastructure specific messages/logs in Docker SPI implementation. https://github.com/eclipse/che/issues/5102
- [x] Revise Docker infrastructure implementation code to find what should be fixed or implemented #5423
- [x] Stop Docker runtime in case of appearance of internal error like OOM #5419
- [x] Serialize machine required fields as docker container labels #4104
- [x] Make Docker SPI impl work on Mac and Windows again https://github.com/eclipse/che/issues/5099 (should be fixed by URLRewriter, close)
- [x] Implement Runtimes restoring in Docker implementation. https://github.com/eclipse/che/issues/5097
- [x] Implement workspace start interruption for Docker backend #5644 
- [x] Implement URLRewriter for Docker infrastructure #5684
- [x] Move docker container settings applying from DockerMachineStarter #5871
- [x] Implement Environment estimation in Docker SPI implementation. https://github.com/eclipse/che/issues/5096 (blocked by refactoring of estimation place)
###### TODO (important for this epic, please do not change w/o discussion)
- [x] Move docker infrastructure related code from docker-plugin to docker infrastructure #6404
- [x] Test docker infrastructure #5575
