### ISSUE TITLE
Important Git enhancements

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#5753]
Customer requests and enhancements for Git functionality:

- [x] Ability to Filter Git Branches in the branches pop up https://github.com/eclipse/che/issues/4678
- [x] Support `git pull --rebase` https://github.com/eclipse/che/issues/3415
- [x] Support `git push -f` https://github.com/eclipse/che/issues/3416
- [x] Show current git branch in the IDE https://github.com/eclipse/che/issues/5335
- [x] Mark with colour Git changed files in project explorer https://github.com/eclipse/che/issues/5339
- [x] Implement coloured marks in editor to show Git changed lines  https://github.com/eclipse/che/issues/5340
- [x] Add 'Git revert commit' action https://github.com/eclipse/che/issues/6024
- [x] Use hotkeys where it is possible https://github.com/eclipse/che/issues/5925

- [x] Navigation in the diff window to the next/prev file https://github.com/eclipse/che/issues/5892
- [x] Improve files selection model in commit window https://github.com/eclipse/che/issues/6255
