### ISSUE TITLE
SPI Kubernetes infrastructure

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#5908]
Currently only Docker and OpenShift infrastructure have been implemented. Once OpenShift infrastructure is mature enough we should extract the Kubernetes parts and make a new infrastructure. OpenShift infrastructure should be an extension of Kubernetes. 
- [x] Support Docker images recipes
- [x] Support k8s recipes
- [x] Implement a deployment yml to deploy Che on minikube using kubectl
- [x] Provide the documentation to run Che on `minikube`
- [x] Che Volumes don't work because of PVC permissions issue https://github.com/kubernetes/minikube/issues/1990. 
As a workaround added an ability to configure context security for pods. Setting runAsUser and FsGroup to 0 fixes issue on `minikube`.
- [x] Add nginx connection configuration that doesn't kill websocket connections
- [x] Improve `Kubernetes` infrastructure by adding an ability to configure ingresses implementation (now `nginx` is hardcoded)
- [x] Improve `Kubernetes` infrastructure by adding an ability to configure `TLS` for ingresses
- [x] Implement a Helm Kubernetes Chart to distribute Che
- [x] Improve dashboard to support `kubernetes` recipes
- [x] Run QA on `kubernetes` infrastructure
- [x] ~~Maybe we need minikube addon for Che~~
- [x] Improve `Kubernetes` infrastructure by adding an ability to set hostname for ingresses (hostname based single port)
- [ ] Add checking that Kubernetes installation is configured with all components for Che Kubernetes infrastructure (like ingress controllers, DNS service discovery)
- [ ] Kubernetes secret token is mounted to all workspaces pods. It gives access to Kubernetes API from `Pods`. Check whether it is a problem and disable mounting of the token if it is possible
- [x] Dashboard doesn't reconnect to a WebSocket endpoint if the previous connection failed https://github.com/eclipse/che/issues/8675
- [x] Add an ability to use host-based routing instead of path-based for k8s infra https://github.com/eclipse/che/issues/8694
- [x] Add an ability to deploy Multiuser Che on Kubernetes https://github.com/eclipse/che/issues/8745
- [x] https://github.com/eclipse/che/issues/9131 add ability to configure workspace external IP on k8s infra

**Comment by garagatyi** [comment]
@l0rd @gorkem 
Currently, I'm thinking how to implement k8s infra and it would be very useful to understand what for it is needed.
Do you have any inputs on what are requirements for this infra? Or maybe you have user stories?

**Comment by gorkem** [comment]
I think `minikube` and `kubeadm` are the environments that we are targeting for this work. This SPI will be used by those who wants to have an independent k8s installation to run Che or as a starting point for the other k8s based solutions.

**Comment by l0rd** [comment]
Here is a list of things I think we should implement:
- [ ] Support Docker images recipes
- [ ] Support k8s recipes
- [ ] Implement a deployment yml to deploy Che on `minikube` using `kubectl`
- [ ] Implement a Helm Kubernetes Chart to distribute Che
- [ ] Provide the documentation to run Che on `minikube`

@garagatyi I planned to work on that too next sprint and we may work together on these tasks wdyt?

@gorkem maybe you meant `kubectl` instead of `kubeadm`?

**Comment by garagatyi** [comment]
We can share these tasks, sure. But this is probably needed to be decided on a teams level to achieve better utilization of resources of teams. @skabashnyuk WDYT?

**Comment by gorkem** [comment]
@l0rd I think `kubeadm` is the one used for installing clusters right?

**Comment by andrewhowdencom** [comment]
There's a certified conformance program if you're looking for a "standard Kubernetes": https://github.com/cncf/k8s-conformance

heptio/buoy checks clusters against a checklist, might help here. Could use the rule "where heptio/buoy passes, this should work"

**Comment by garagatyi** [comment]
@andrewhowdencom sorry, I didn't get what issue suggested solution is supposed to solve, can you elaborate?

**Comment by andrewhowdencom** [comment]
> I think minikube and kubeadm are the environments that we are targeting for this work. This SPI will be used by those who wants to have an independent k8s installation to run Che or as a starting point for the other k8s based solutions.

It was my understanding that there was some notion of defining what a suitable test environment for the API work for che should be.

To determine in what environments Kubernetes is supposed to work, you could use the guideline "Does it adhere to the Kubernetes Conformance guidelines". In this case, it would not rather be `kubeadm`, `gke` or any other specific cluster, but rather clusters that are "known correct". 

The point about heptio/buoy was to resolve any ambiguity whether it should be some handling built in to che to handle ambiguity between k8s environments (for example, rbac here and not there, or alpha features being enabled). The goal being "Che should operate in environments in which buoy indicates there are no issues":

Reference: https://github.com/heptio/sonobuoy

If I misread this, I'm sorry <3 I was just trying to pass on information that I thought may be useful. I'm excited to see this work completed!

**Comment by garagatyi** [comment]
@andrewhowdencom thank you for the explanation. Not sure we need to test environment for the compatibility with k8s TCK. Anyone can correct me if I missed something.
If you are referring discussion from the Che bi-weekly meeting about testing k8s infrastructure we were discussing TCK for Che SPI itself, not k8s.

**Comment by gorkem** [comment]
@garagatyi I think the question is what kubernetes platform/distribution should we test Che SPI against. There are over 50 of those nowadays and we can not test them all. 

@andrewhowdencom Thanks for bringing up `sonobuoy`, it is interesting. I think we should study it.

**Comment by sleshchenko** [comment]
So, @garagatyi and I did some investigation and work on Kubernetes infrastructure.

Today we have a branch with Kubernetes infrastructure. There are few more pieces of stuff that required to be reworked a bit. PR will be created soon.
So `Kubernetes` infrastructure supports `dockerimage` and `kubernetes`(yaml list with kubernetes objects) recipes.
I've tested it using the following configuration:
Che is running on Docker on my localhost. Kubernetes infrastructure is configured to start workspaces on my local minikube (Che will create workspaces Kubernetes Objects on a minikube).

OpenShift infrastructure extends Kubernetes and supports `dockerimage`, `kubernetes`, `openshift` recipes.

What is left to do:
- [ ] Implement a deployment yml to deploy Che on minikube using kubectl
- [ ] Implement a Helm Kubernetes Chart to distribute Che
- [ ] Provide the documentation to run Che on `minikube`
- [ ] Improve dashboard to support `kubernetes` recipes
- [ ] Run QA on `kubernetes` infrastructure
- [ ] Maybe we need minikube addon for Che
- [ ] Improve `Kubernetes` infrastructure by adding an ability to set hostname for ingresses 
- [ ] Improve `Kubernetes` infrastructure by adding an ability to configure ingresses implementation (now `nginx` is hardcoded)
- [ ] Improve `Kubernetes` infrastructure by adding an ability to configure `TLS` for ingresses (there is implemented initial state, but it is not tested)
- [ ] Add checking that Kubernetes installation is configured with all components for Che Kubernetes infrastructure (like ingress controllers, DNS service discovery)
- [ ] Kubernetes secret token is mounted to all workspaces pods. It gives access to Kubernetes API from `Pods`. Check whether it is a problem and disable mounting of the token if it is possible.

**Comment by sleshchenko** [comment]
So, [PR](https://github.com/eclipse/che/pull/8559) with k8s infrastructure is merged.
I've updated tasks list in my [comment](https://github.com/eclipse/che/issues/5908#issuecomment-361632430) above.
What's new there:
- Dashboard doesn't reconnect to a WebSocket endpoint if the previous connection failed https://github.com/eclipse/che/issues/8675
Because of some reason WebSocket connections are interrupted often, it's not an issue for IDE because it reconnects automatically. But Dashboard doesn't do it and loses events from workspace master. So Dashboard should be improved. And maybe it makes sense to investigate why WebSocket connections are interrupted.

- One more issue that I've faced is PVC permissions issue on minikube. Che Volumes is mounted in containers with root permissions even when precreate subpaths feature is turned on. I guess it is related to https://github.com/kubernetes/minikube/issues/1990. As a workaround added an ability to configure security context for pods, and for minikube `root` user is configured.

- Add an ability to use host-based routing instead of path-based for k8s infra https://github.com/eclipse/che/issues/8694
Without this feature, workspaces start well but some of the sample applications fail to work correctly.

- @riuvshin is working on Run QA on kubernetes infrastructure

- Here is an [PR](https://github.com/sleshchenko/che/pull/8) for issue `Implement a Helm Kubernetes Chart to distribute Che`. @perspectivus1 should recreate it in Eclipse Che repository

**Comment by sleshchenko** [comment]
Update: 
- Moved tasks into the epic issue description.
- Added an issue for deploying Multi-User Che on a Kubernetes.

**Comment by riuvshin** [comment]
linked issue that blocks us to run QA tests on CI against k8s infra https://github.com/eclipse/che/issues/9131, as I understand this PR: https://github.com/eclipse/che/pull/8822 should cover it.

**Comment by l0rd** [comment]
@carloreggiani you can use the Helm Chart https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/readme.md

**Comment by carloreggiani** [comment]
It was my firts try, @l0rd, but I'm trying to understand how to configure on Docker EE kubernetes the RBCA prerequisite steps (I'm connected ad admin user to the cluster):

```
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
error: no matches for rbac.authorization.k8s.io/, Kind=ClusterRoleBinding
```

**Comment by garagatyi** [comment]
Closing the issue since it is already implemented.
