### ISSUE TITLE
Adapt existing selenium tests for SPI assembly

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#5996]
Try running selenium tests for Che SPI assembly, analyze and resolve all compatibility issues
 - [x] Adapting existing selenium tests from "editor" , "intelligencecommand" packages according to changes in SPI #6188
 - [x] Adapting existing selenium tests from "preferences", "editor.autocomplete" packages according to changes in SPI branch #6225
 - [x] Adapting existing selenium tests from 'miscellaneous' according to SPI branch #6248

**Comment by gazarenkov** [comment]
@musienko-maxim 
Could you please provide numbers about how many tests (%) are failed?
Can we start it with identifying "big reasons" for failing tests?
Thanks

**Comment by musienko-maxim** [comment]
Ok, i am preparing launching of the selenium tests for SPI branch after latest changes. After getting the report, we will analyze it, and report about current state. I will plan do this today about 2-3 PM.

**Comment by slemeur** [comment]
Removing the "epic" label as this is a sub-tasks from the new SPI epic https://github.com/eclipse/che/issues/5639.
