### ISSUE TITLE
Fix unstable and outdated selenium tests

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#6346]
There are several selenium tests which are unstable, that are fail from time to time, or outdated.
According to the [for recent build 43 result](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/43/#showFailuresLink) we have 71 tests failures.
We need to sort out regular tests execution result to recognize those of them which failed because of inaccurate code to achieve 100% selenium tests success execution:
- [x] [CheckBasicFunctionalityInCommandsExplorerTest.shouldCreateAndRunBuildCommand](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/64/testReport/junit/org.eclipse.che.selenium.intelligencecommand/CheckBasicFunctionalityInCommandsExplorerTest/shouldCreateAndRunBuildCommand/)
- [x] [CheckBasicFunctionalityInCommandsExplorerTest.shouldCreateDifferentTypesCommandsInDifferentGoals](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/64/testReport/junit/org.eclipse.che.selenium.intelligencecommand/CheckBasicFunctionalityInCommandsExplorerTest/shouldCreateDifferentTypesCommandsInDifferentGoals/)
- [x] [CheckFindActionFeatureInCheTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/56/testReport/junit/org.eclipse.che.selenium.editor/ContextMenuEditorTest/) (#6524)
- [x] [CommandsPaletteTest.newCommandTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/55/testReport/org.eclipse.che.selenium.intelligencecommand/CommandsPaletteTest/newCommandTest/) It looks like this bug has been fixed by https://github.com/eclipse/che/pull/6511.
- [x] [ContextMenuEditorTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/56/testReport/junit/org.eclipse.che.selenium.editor/ContextMenuEditorTest/) (#6524)
- [x] [CreateNamedFactoryFromDashBoard.createFactoryFromDashBoard](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/50/testReport/org.eclipse.che.selenium.factory/CreateNamedFactoryFromDashBoard/createFactoryFromDashBoard/) (#6440)
- [x] DebugExternalClassTest
- [x] [DeleteProjectsTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/55/testReport/junit/org.eclipse.che.selenium.projectexplorer/DeleteProjectsTest/)
- [ ] DiffViewTest (#6452)
- [x] DirectUrlFactoryWithRootFolder (#6440)
- [x] [Eclipse0093Test.test0093](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/56/testReport/junit/org.eclipse.che.selenium.opendeclaration/Eclipse0093Test/test0093/)
- [ ] Eclipse0115Test
- [x] Eclipse0120Test
- [x] FileStructureNodesTest (https://github.com/eclipse/che/issues/6436)
- [x] FindUsagesBaseOperationTest (https://github.com/eclipse/che/issues/6436)
- [x] [FormatterTest.formatterTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/50/testReport/junit/org.eclipse.che.selenium.editor.autocomplete/FormatterTest/formatterTest/)
- [x] [ImportProjectIntoSpecifiedBranchTest.checkImportProjectInBranchByHttpsUrl](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/47/testReport/org.eclipse.che.selenium.git/ImportProjectIntoSpecifiedBranchTest/checkImportProjectInBranchByHttpsUrl/)
- [x] [ImportProjectIntoSpecifiedBranchTest.checkImportProjectInBranchBySshUrl](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/47/testReport/org.eclipse.che.selenium.git/ImportProjectIntoSpecifiedBranchTest/checkImportProjectInBranchBySshUrl/)
- [x] [ImportProjectIntoSpecifiedBranchTest.checkImportProjectInBranchFromGitHub](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/56/testReport/org.eclipse.che.selenium.git/ImportProjectIntoSpecifiedBranchTest/checkImportProjectInBranchFromGitHub/)
- [x] [ImportRecursiveSubmoduleTest.checkImportProjectSubmoduleByHttpsUrl](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/53/testReport/junit/org.eclipse.che.selenium.git/ImportRecursiveSubmoduleTest/checkImportProjectSubmoduleByHttpsUrl/)
- [x] [ImportRecursiveSubmoduleTest.checkImportProjectSubmoduleBySshUrl](ImportRecursiveSubmoduleTest.checkImportProjectSubmoduleBySshUrl)
- [x] [ImportRecursiveSubmoduleTest.checkImportProjectSubmoduleFromGithub](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/53/testReport/junit/org.eclipse.che.selenium.git/ImportRecursiveSubmoduleTest/checkImportProjectSubmoduleFromGithub/)
- [x] JavaTestPluginJunit4Test -  - depends on #6497
- [x] [JavaTestPluginTestNgTest.shouldExecuteTestClassSuccessfully](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/39/testReport/junit/org.eclipse.che.selenium.testrunner/JavaTestPluginTestNgTest/shouldExecuteTestClassSuccessfully/) - depends on https://github.com/eclipse/che/issues/6497
- [x] [JavaTestPluginTestNgTest.shouldExecuteTestMethodsSuccessfully](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/41/testReport/junit/org.eclipse.che.selenium.testrunner/JavaTestPluginTestNgTest/shouldExecuteTestMethodsSuccessfully/) - depends on https://github.com/eclipse/che/issues/6497
- [x] [JustCreatedFileNotExistIntoEditorAfterDeleteTest.deleteFileTest](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test/36/testReport/org.eclipse.che.selenium.projectexplorer/JustCreatedFileNotExistIntoEditorAfterDeleteTest/deleteFileTest/)
- [x] KeepDirectoryGitImportTest (#6486)
- [x] KeyBindingsTest
- [x] [MoveItemsTest.checkMoveItem5](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/55/testReport/junit/org.eclipse.che.selenium.refactor.move/MoveItemsTest/checkMoveItem5/)
- [x] MoveJavaFileInNewSourceFolderTest
- [x] [PhpProjectDebuggingTest.shouldDebugCliPhpScriptFromFirstLine](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/56/testReport/junit/org.eclipse.che.selenium.debugger/PhpProjectDebuggingTest/shouldDebugCliPhpScriptFromFirstLine/) (#6123)
- [x] [PhpProjectDebuggingTest.shouldDebugWebPhpScriptFromNonDefaultPortAndNotFromFirstLine](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/56/testReport/junit/org.eclipse.che.selenium.debugger/PhpProjectDebuggingTest/shouldDebugWebPhpScriptFromNonDefaultPortAndNotFromFirstLine/) (#6123)
- [x] PlainJavaProjectConfigureClasspathTest
- [x] [PushChangeNotUpdatedRepoTest.pushNoneUpdateTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/45/testReport/junit/org.eclipse.che.selenium.git/PushChangeNotUpdatedRepoTest/pushNoneUpdateTest/)
- [x] [PushingChangesTest.pushChangesTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/45/testReport/junit/org.eclipse.che.selenium.git/PushingChangesTest/pushChangesTest/)
- [x] RenameWorkspaceTest
- [x] SwaggerTest (#6532)
- [x] [TestEnumerationsTest.testEnum1](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/41/testReport/junit/org.eclipse.che.selenium.refactor.types/TestEnumerationsTest/testEnum1/)
- [x] [TransitiveDependencyTest.transitiveDependencyTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/55/testReport/junit/org.eclipse.che.selenium.projectexplorer.dependencies/TransitiveDependencyTest/transitiveDependencyTest/)
- [ ] UpdateToRevisionTest (#6452)
- [x] [WorkingWithNodeWsTest.checkNodeJsWsAndRunApp](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test/39/Selenium_tests_report/) (#6524)
- [x] [WorkingWithPullConflictsTest.pullConflictsTest](https://ci.codenvycorp.com/view/qa/job/che-integration-tests/45/testReport/junit/org.eclipse.che.selenium.git/WorkingWithPullConflictsTest/pullConflictsTest/)
---
- [x] CheckBitnamiCodeIgniterFactory (https://github.com/eclipse/che/pull/6458)
- [x] CheckBitnamiLaravelFactoryTest (#6437)
- [x] CheckBitnamiSwiftFactory (#6437)
- [x] CheckFactoryWithSparseCheckoutTest
- [x] CheckIntelligenceCommandFromToolbarTest
- [x] CheckRecentFilesAndRevealResourceTest
- [x] CheckRestoringOfSplitEditor
- [x] CheckStoppingWsByTimeoutTest, EditorSettingsTest - fails while creating test workspace (#6298);
- [x] CheckWsAgentAfterStopProcessTest (#6442)
- [x] CommandsEditorTest
- [x] CommitFilesTest
- [x] FindTextFeatureTest (https://github.com/eclipse/che/issues/6232)
- [x] GitPullTest
- [x] NavigateToFileTest(fixed by https://github.com/eclipse/che/pull/6266))
- [x] PreviewRefactoringTest

**Comment by tolusha** [comment]
Glad to see this important issue finally.
Could you provide the criteria for unstable tests?

**Comment by dmytro-ndp** [comment]
I propose to consider test as unstable if it fails 1-2 times during the last 3 execution on CI https://ci.codenvycorp.com/view/qa/job/che-integration-tests/

**Comment by dmytro-ndp** [comment]
Fresh list of unstable tests according to the results of testing jobs 87-93:
```
org.eclipse.che.selenium.debugger.CheckBreakPointStateTest.checkStateAfterDeletionProject
org.eclipse.che.selenium.debugger.NodeJsDebugTest.debugNodeJsTest
org.eclipse.che.selenium.debugger.StepIntoStepOverStepReturnWithChangeVariableTest.changeVariableTest
org.eclipse.che.selenium.editor.autocomplete.AutocompleteProposalJavaDocTest.shouldReflectChangesInJavaDoc
org.eclipse.che.selenium.factory.CheckFactoryWithUntilPolicyTest.checkFactoryAcceptingWithUntilPolicy
org.eclipse.che.selenium.factory.CreateFactoryFromUiWithKeepDirTest.createFactoryFromUiWithKeepDirTest
org.eclipse.che.selenium.factory.DirectUrlFactoryWithSpecificBranch.factoryWithDirectUrlWithSpecificBranch
org.eclipse.che.selenium.git.GitColorsTest.testFileColorsAfterCommitFromMenu
org.eclipse.che.selenium.git.KeepDirectoryGitImportTest.keepDirectoryImportFromGitHub
org.eclipse.che.selenium.git.RevertCommitTest.shouldRevertCommit
org.eclipse.che.selenium.intelligencecommand.CheckBasicFunctionalityInCommandsExplorerTest.shouldCreateAndRunBuildCommand
org.eclipse.che.selenium.intelligencecommand.CheckBasicFunctionalityInCommandsExplorerTest.shouldCreateAndRunCustomCommand
org.eclipse.che.selenium.mavenplugin.CheckMavenPluginTest.mavenStatusBarShouldDisplayResolvingProjectMessage
org.eclipse.che.selenium.mavenplugin.CheckMavenPluginTest.shouldExecuteCommandAndWaitTextInConsole
org.eclipse.che.selenium.miscellaneous.CheckRestoringWorkspaceAfterStoppingWsAgentProcess.checkRestoreIdeItems
org.eclipse.che.selenium.miscellaneous.CheckRestoringWorkspaceAfterStoppingWsAgentProcess.checkRestoreWsAgentByApi
org.eclipse.che.selenium.opendeclaration.Eclipse0115Test.test0115
org.eclipse.che.selenium.opendeclaration.Eclipse0121Test.test0121
org.eclipse.che.selenium.refactor.packages.RenamePackageSpringTest.checkRenamePackageSpringApp
org.eclipse.che.selenium.refactor.packages.RenamePackageTest.checkTest7
org.eclipse.che.selenium.refactor.types.IllegalTypeNameTest.illegalTypeName4
org.eclipse.che.selenium.subversion.LockFileTest.lockFileTest
org.eclipse.che.selenium.swagger.SwaggerTest.checkNameProjectTest
org.eclipse.che.selenium.workspaces.ProjectStateAfterRefreshTest.checkRestoreStateOfProjectAfterRefreshTest
```

**Comment by musienko-maxim** [comment]
Main fixes have been done on this moment this issue is not actual
