### ISSUE TITLE
Provide basic support for tablets

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#6527]
With the release of larger format tablets and extensions keyboards there are more developers (consultants, speakers, freelancers,...) using tablets to do their work. Although most prefer to do long coding sessions on a laptop, a remote Che server does promise to make it quick and easy to code up a small app or example from a mobile device.

We should be testing Che on tablets at a minimum to ensure that the majority of functions can be executed on those devices and documenting the areas of the product that cannot be effectively used from a tablet.

### Tasks
- [ ] QA: Test Che on a tablet and document the areas that do not work today
- [ ] PM: Based on the above prioritize the areas that should be usable on a tablet
- [ ] Replace double-click actions from projects/commands explorer https://github.com/eclipse/che/issues/5627
