### ISSUE TITLE
[WIP] Improve Che IDE extensibility model 

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#6642]
## Problem

The current Eclipse Che architecture for the client side IDE is using GWT and Guice/Gin for the dependency injection. Eclipse Che IDE is composed of API Core functions and plugins. With GWT, all plugins are statically linked at compile time, it means that adding a plugin to the assembly requires to build each time this build take long time 

## Goals

1. Need to allow developer develop only own plugin and include it to the compiled Che IDE without rebuild all app
2. Make possible develop client-side plugin on pure JavaScript
3. Consider Che plugin as single artifact which contains:
- server side code;
- client side code; 
- some meta information; 

## Tasks
- [ ] Investigate ability build each core module and plugin  like GWT application (compiled to javascript) and embed them to the web app like ready to go resources https://github.com/eclipse/che/issues/8252
- [ ] Provide JavaScript API for each existing client side API developed with GWT technology [with JsType feature](http://www.gwtproject.org/javadoc/latest/jsinterop/annotations/JsType.html)  #6647
- [ ] Generate JavaScript template for plugin https://github.com/eclipse/che/issues/7857
- [ ] Move directory with installed Che JS Plugin from the WS Master instance to the separate service #8221

**Comment by benoitf** [comment]
About #2, I would like to see what it will be before trying to do a direct 1-1 mapping.

I'm interested in the simplicity of the API and if it will match the full the loading/unloading sequence of a plugin


For reference, here are two documents I've provided
https://docs.google.com/document/d/1OcC8cnmPzwQybSi58OSQKTngXEqV46oFEyGn6phpB6U/edit
https://docs.google.com/document/d/1t7bOjC6MkgJdv14KSwcYqh2xBrWQWaYCgkatRUmZzfc/edit

**Comment by bmicklea** [comment]
@vparfonov can you please add and link the tasks in the Tasks section?

**Comment by slemeur** [comment]
Will be addressed by #8266
