### ISSUE TITLE
Provide JavaScript API for each existing client side API

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#6647]
Provide JavaScript API for each existing client side API developed with GWT technology [with JsType feature](http://www.gwtproject.org/javadoc/latest/jsinterop/annotations/JsType.html) ([here list of existed client side API](https://docs.google.com/spreadsheets/d/1ijapDnl1G7svy7sIKgTntyTuVsnd9nFcH0-357C0MxE/edit#gid=0)) (new issues will be added soon) 
- [x] POC for Action API and loader for JavaScript plugins #6649
- [x] Adapt IDE Themes API for the JavaScript endpoint #7077 
- [x] POC for IDE Part API for the JavaScript endpoint #7411 
- [x] JavaScript endpoint for IDE EventBus ans Application Context #7441 
- [x] JavaScript endpoint for Project/File management  #7842 
- [x] JavaScript endpoint for Editor #7853 
- [x] JavaScript endpoint for Dialog API #7879 
- [x] JavaScript endpoint for Notification API #8106
