### ISSUE TITLE
Release Eclipse Che 6.0.0-M1

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#6938]
### Description
We would like to make a first M release of our new Eclipse Che6 https://github.com/eclipse/che/pull/6698

#### TODO
- [x] [SPI] Enable authentication in golang based agents	https://github.com/eclipse/che/issues/6577 
- [x] Ports should not be exposed automatically, but rather be explicitly defined in workspace config 	https://github.com/eclipse/che/issues/6124 
- [x] [CHE 6] Rename environment variable with machine token to `CHE_MACHINE_TOKEN` https://github.com/eclipse/che/issues/6730
- [x] [CHE 6] Implement different strategies of PVC for OpenShift infra  https://github.com/eclipse/che/issues/6774

#### Known issues
**related on failed tests:**
- [x] [CHE6 branch] Wrong macros in the default maven command #6197
- [CHE6 branch] Macros for creating preview URL is not exist #6215 
- [CHE6 branch] Pull Request plugin does not work #6237
- [CHE6 branch] Nothing is displayed after stop workspace by command #6329
- [CHE6 branch] Actions are disabled when to switch tabs on the panel 'Console' #6370
- [x] [CHE6 branch] Unexpected error notification when create command #6734
- [CHE6 branch] Git color for files works incorrectly #6741
- [CHE6 branch] Macros in commands editor does not returns expected output #6880
- [CHE6 branch] The Yaml language server doesn't exist in the Installers tab #6912 
- [CHE6 branch] A file is not scroll to cursor position in the Editor after refreshing of web page #6915
- [CHE6 branch] The 'Navigate To File' works incorrectly #6948
- [CHE6 branch] Cannot create a workspace with name more than 20 symbols #6986
- [x] [CHE6 branch] Factory by direct urls feature works wrong #6972
- [x] [CHE6 branch] Factory actions do not work properly #6999
- [CHE6 branch] The active tab from the Processes area isn't restored correctly after refreshing web page #7072
- [CHE6 branch] All content of panel menu is not displayed #7095

**not related to selenium tests:**
- [CHE6 branch] ProjectTreeTracker NPE exception #6825
- [CHE6 branch] Terminal width doesn't adapt to the width of Che window #6837
- [CHE6 branch] The diagnostics feature doesn't work #6919
- [CHE6 branch] Browser tab freezes when setting up CHE project as a maven project #6831
- [CHE6 branch] Git command output console is not consistent #6817
- [CHE6 branch] Panel's buttons don't work properly after hiding/restoring a panel #6842
- [CHE6 branch] Exceptions are displayed in the "dev-machine" terminal #6947

**Comment by riuvshin** [comment]
done, tag 6.0.0-M1 is available.
