### ISSUE TITLE
Che 6 on OpenShift - Phase 1

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#7321]
The goal of this epic is to track the readiness of Che 6 on OpenShift (OCP, OSD and minishift). 

### OpenShift SPI Implementation
- [x] OpenShift infrastructure implementation of SPI - #5098
- [x] Che Deployment on OpenShift should be as easy as on Docker - #6097

### Packaging
- [x] Che 6 OpenShift template - #7318 
- [x] Che 6 MiniShift add-on - https://github.com/redhat-developer/rh-che/issues/506 
- [x] Docs: Deploy with OpenShift template / MiniShift add-on

### Requirements on workspace runtimes
- [x] Display message in dashboard related to the restrictions on the recipes
- [x] Che5 default set of stacks adapted and running on Che 6 on OpenShift
- [x] Docs: Explain OpenShift recipe type 
- [x] Docs: Explain Kubernetes recipe type 
- [x] Docs: Document impacts on Che agents
- [x] Docs: Explain the impacts on agents, server and environment variables

### Multi-user and Multi-tenancy
- [x] Docs: Provide basic infrastructure diagram explaining how Che is deployed on OpenShift 
- [x] Docs: Provide scalability documentation and methodology

### Adapted Features and Capabilities
- [x] Explain how to SSH into the workspace (via `oc rsh`?) / Docs and maybe update to SSH button in workspace #7664 

### Configuration and Requirements
- [x] Docs: on user's permissions on files/folders to be defined in OS
- [x] Docs: on unprivileged containers and impacts of no `sudo` access
- [x] Docs: on how to configure TLS Support
- [x] Docs: on how to configure a private docker registry
- [x] Docs: on how to configure distributed volumes

### Administration
- [x] Docs: on how to get logs of Che server. 
- [x] Docs: on how to limit user’s resources 

### Linked Issues
https://github.com/codenvy/codenvy/issues/2517

**Comment by garagatyi** [comment]
@slemeur `Support dockerfile recipes ` is not supported in Che5, so I see no reason to make it a requirement on workspace runtimes.

**Comment by garagatyi** [comment]
The same for compose

**Comment by garagatyi** [comment]
@slemeur As for me, it looks like most of these points are not covered on Che5. Can you elaborate on why they should be requirements for Che6?

**Comment by slemeur** [comment]
@garagatyi : It's not because it is not in Che 5 openshift connector that we should not do it in Che 6. You maybe have in mind only the requirements for Che 6 to run on OSIO - but keep in mind that all codenvy customers are waiting for a migration path from Codenvy to Che 6 on Openshift (https://github.com/codenvy/codenvy/issues/2517). For those who were using Che on Docker in the past and willing to use an OpenShift based infrastructure, the support of the different recipe types is important.

**Comment by garagatyi** [comment]
@slemeur I see. I definitely thought about OSIO use-case, not the most common one. Thank you for the explanation

**Comment by skabashnyuk** [comment]
@slemeur  can you elaborate a bit more on " Docs: on user's permissions on files/folders to be defined in OS" what do you mean?

**Comment by slemeur** [comment]
When discussing with @eivantsov , it sounds that there could be limitation applied to the file system which would prevent Che to behaves properly.
This point was to mention the different settings and configuration option which might be needed.

**Comment by ghost** [comment]
https://www.eclipse.org/che/docs/6/che/docs/openshift-config.html#filesystem-permissions

**Comment by skabashnyuk** [comment]
@slemeur can you confirm that this epic is complete and we can close it?

**Comment by slemeur** [comment]
Done !
