### ISSUE TITLE
Che 6 on OpenShift - Phase 2

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#7556]
Following issue #7321 

### Requirements on workspace runtimes
- [ ] Support dockerfile recipes - #5906
- [ ] Support composefile recipes - #7860
- [ ] Display message in dashboard related to the restrictions on the recipes

### Adapted Features and Capabilities
- [ ] Disable Agents configuration from dashboard when unprivileged containers are used

 ### Administration
- [ ] Docs: Provide runbook similar to https://codenvy.io/docs/admin-guide/runbook/index.html

### Linked Issues
https://github.com/codenvy/codenvy/issues/2517
