### ISSUE TITLE
Set up OpenShift workspace with LS in a parallel container

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#8171]
### Description
A workspace with LS in a parallel container works fine on Docker infrastructure.
It is needed to prepare workspace configuration of OpenShift workspace where LS will be in a parallel container.

**Comment by sleshchenko** [comment]
Here is an OpenShift workspace config with LS in parallel container:
<details>
<summary>Workspace Config</summary>

```json
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "ws/typescript-ls": {
          "attributes": {},
          "servers": {
            "ls": {
              "attributes": {
                "internal": "true",
                "type": "ls",
                "config": "{\"id\":\"https://github.com/sourcegraph/javascript-typescript-langserver\", \"languageIds\":[typescript]}"
              },
              "port": "4417",
              "protocol": "tcp"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.terminal"
          ],
          "env": {}
        },
        "ws/dev": {
          "attributes": {},
          "servers": {
            "codeserver": {
              "attributes": {},
              "port": "9876",
              "protocol": "http"
            }
          },
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [
            "org.eclipse.che.exec",
            "org.eclipse.che.terminal",
            "org.eclipse.che.ws-agent"
          ],
          "env": {}
        }
      },
      "recipe": {
        "type": "openshift",
        "content": "---\nkind: List\nitems:\n-\n  apiVersion: v1\n  kind: Pod\n  metadata:\n    name: ws\n  spec:\n    containers:\n      -\n        image: eivantsov/tsls\n        name: typescript-ls\n      -\n        image: eclipse/ubuntu_jdk8\n        name: dev",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [
    {
      "links": [],
      "name": "greeter",
      "attributes": {},
      "type": "typescript",
      "source": {
        "location": "https://github.com/Microsoft/TypeScriptSamples.git",
        "type": "git",
        "parameters": {
          "convertToTopLevelProject": "true",
          "keepVcs": "false",
          "keepDir": "greeter"
        }
      },
      "path": "/greeter",
      "problems": [],
      "mixins": []
    }
  ],
  "name": "TypeScript_LS_Demo",
  "commands": [],
  "links": []
}
```
</details>

Faced with the following issues while starting of described workspace:
- [x] OpenShift multi-container workspace fails to start https://github.com/eclipse/che/issues/7922
- [x] OpenShift multi-container workspace fails to start if unique strategy PVC is used  https://github.com/eclipse/che/issues/8161 (to make workspace working it is possible to configure common PVC strategy)
- [x] Installers fail in OpenShift multi-container workspace https://github.com/eclipse/che/issues/7927 (to make workspace working it is possible to disable all installers in ls machine) 
- [ ] Can not access to container port via service on local OCP https://github.com/eclipse/che/issues/8134
  
So, it will be possible to run workspace with LS in a parallel container if:
- ~the first issue will be fixed~ fixed;
- ~common PVC strategy is configured while the corresponding issue is not resolved~ fixed;
- ~LS machine doesn't have the same installers as dev machine has~ fixed;
- Che Server is deployed not on local OCP like https://console.codenvy.openshift.com/;

See demo:

![openshift_ls_demo](https://user-images.githubusercontent.com/5887312/34559442-928cf1ec-f14a-11e7-8d6b-d1a905525b46.gif)
