### ISSUE TITLE
Self hosting milestone for next gen Che

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#8267]
# Description

## Motivations
As we are defining the new generation Che (see #8266), we also need to nail down the developer experience of Che as well as all the necessary capabilities and features nedeed to make Che, the best IDE to create and author Che plugins.

We are targeting an initial milestone for the new generation Che which will provide the basic capabilities so that the new generation of Che can be used to build it. 

### Run Theia on workspace as a sidecar
Che's ide will be provided as a sidecar container from the workspace's runtime.

**Linked Issues:**
- [x] https://github.com/eclipse/che/pull/8600

### Workspace Loader UI
The new Che's IDE will be running in a sidecar container. When the user will be starting a workspace, the system will prepare the sidecar to provide the IDE to the user. The system will pull the sidecar's image, start the container and once running, the system will be able to provide the IDE. 

Until the sidecar for the IDE is ready, there will be loading step which will be displaying to the user, what the system is actually doing. 

**Linked Issues:**

### Terminal Agent 
The terminal agent will need to be adapt so that it can work properly in the sidecar situation. 
- update to theia for working with terminal server
- solve launching terminal server on runtime container 

**Linked Issues:**
- [ ] https://github.com/eclipse/che-theia-terminal-plugin

### Debugger 
In order to be able to develop plugins for the next gen Che, the debugger needs to be present in the IDE.  

**Linked Issues:** https://github.com/eclipse/che/issues/8383

### Host Mode
We will need to provide a complete host mode within Che.
As the nature of the plugins might be different, we need to handle the various situation
- Client side only plugin
- Server side only plugin
- Client and Server side plugin
- Client and Server as sidecar plugin

The host mode, will have to handle those various scenarios.

A specific set of commands will be documented to allow the developer to build, run, debug and package his plugin.

**Linked Issues:**
- [ ] Run separate instance of Theia server with plugin that is developing https://github.com/eclipse/che/issues/9212
- [ ] Add UI to differ developer mode in Theia https://github.com/eclipse/che/issues/9214

### Language servers 
Implementation of the Language servers for the next gen Che will need some work:
- The support of the Language Server in Theia is not a completed as in Che
- The LS running in sidecars, there will be a different mecanism for launching the language servers and activating them on the client-side. 
- Architectural differences

**Linked Issues:** https://github.com/eclipse/che/issues/8514

### Plugin model for next gen Che
We need to define the plugin model for next gen Che.
See: https://github.com/theia-ide/theia/issues/1482

A plugin will be be packaged in a way to allow those different cases. 

**Linked Issues:**

### CI job from master for use with Che workspace

**Linked Issues:**

### Developer mode target platform
Developer mode in Che must be running on OpenShift and other infrastructures.

### Linked issues
https://github.com/eclipse/che/issues/8266
https://github.com/eclipse/che/issues/6713

**Comment by dneary** [comment]
Just to clarify: "Self-hosting Che" means developing Che in Che? Or does it mean something more?

I have had some issues with workspaces failing to open with no obvious error, and no real indication of how to fix it, for both Che and Che + Theia. Would ennumerating issues related to this be in-scope for this issue?

**Comment by PavelSosin** [comment]
Do you know some running projects of DAP services containerization? Until, at least, DAP services for java and nodejs will be conteinerized it is impossible to proceed to IDE integration. The minimal requirement for DAP debugger delivery to customer is deployment of Docker stack built from DAP Server and NGINX proxy to very basic swarm. I also can't find statement how DAP server  is integrated:  side-car with mapping to workspace, like jdt in eclipse  or separate pod? Other combinations either have very poor protocol stability or non-secure.
All orchestration issues can be solved very fast.

**Comment by slemeur** [comment]
closing as out of date epic
