### ISSUE TITLE
Commands support in next gen Che

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#8382]
## Goals
Provides commands support for the next generation Che's IDE.

### Description
Theia will be used for the foundation of the new IDE provided with the next gen Che. This new IDE does not support Che's commands. There is a concept of Tasks that is getting in place, but workspace commands that are core to Che's workspace will need to be integrated in the new IDE.

### Tasks
- [x] Define a plan and specification for commands support in Theia IDE.
- [x] Variable Resolver Extension - https://github.com/theia-ide/theia/pull/1581
- [x] Support Variables in Theia's tasks - https://github.com/theia-ide/theia/issues/1596
- [x] Provide set of "built-in" variables for Theia's tasks - https://github.com/theia-ide/theia/issues/1598
- [x] Provide Tasks API in Theia - https://github.com/theia-ide/theia/issues/1698
- [x] Support Commands macro in Theia IDE - https://github.com/eclipse/che/issues/8974
- [x] Support target (define in command context: source code + container) for the command
- [x] Ability to define preview URL #9273
- [x] Ability to visualize preview URL #9273
- [x] Make a command's target optional for Che tasks #10135
- [ ] Che task in Theia may have the multiple targets defined #10136
- [x] Show info about the running Che task in Theia's terminal widget #10137
- [x] Open a preview URL in an embedded panel in Theia #10738

**Comment by slemeur** [comment]
@vparfonov : Could you please link all the issues you created related to this epic (I found few, like https://github.com/eclipse/che/issues/8974) . Thanks

**Comment by slemeur** [comment]
@vparfonov + @azatsarynnyy : Could you please use this epic to create subtasks and follow-up on the progress you are making on support commands in Theia?

**Comment by gorkem** [comment]
@slemeur I am closing this one everything else is followed up on their own tasks.
