### ISSUE TITLE
Complete the support for Microsoft Debugger Adapter Protocol in Theia

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#8383]
## Goals
Provides debugger support for the next generation Che's IDE.

### Description
Theia will be used for the foundation of the new IDE provided with the next gen Che (#8266). This new IDE does not provide Debugger capabilities for the time being. There are some plans to implement the Debug Adapter Protocol (https://github.com/Microsoft/vscode-debugadapter-node), but we'll need to study how this will impact the next generation Che. 

https://code.visualstudio.com/docs/extensions/example-debuggers

### Tasks

**Establish Debug Sessions**
  * [x] Connect/Disconnect remote target #8929
  * [x] Start/Stop debug targets

**Threads**
  * [x] Show threads of debug targets #9421
  * [x] Show Stack of Suspended Threads #9423 
  * [x] Show Source for Suspended Threads #10048

**Suspend/Resume Actions**
  * [x] Suspend/Resume Actions #9424 

**Stack Frame Variables**
  * [x] Display #9819
  * [x] Modify #9820

**Watch expressions**
   * [ ] add/remove/edit watch expressions, evaluate them automatically in selected frame.

**Step actions**
  * [x]  In/out/over https://github.com/eclipse/che/issues/10076
  * [ ] Into selection
This is not possible with DAP only, as we do not know the structure of the text at the selection
  * [ ] Run to Line  https://github.com/theia-ide/theia/issues/3424

**Breakpoints**
  * [x] #9809 Show list of Breakpoints
  * [x] Enable/Disable
  * [x] Remove Breakpoint

 _Line Breakpoint_
  * [x] DAP Create Line Breakpoint #10077
  * [x] display in editor

_Function Breakpoint_ https://github.com/theia-ide/theia/issues/3312 (Typefox)
  * [ ] create
  * [ ] display in editor

**Comment by tolusha** [comment]
@tsmaeder 
I've added a list of tasks without clarification to know if we go in right direction.

**Comment by tsmaeder** [comment]
Here are a couple of thoughts about self hosting:
* We need to be able to debug sidecars.
  * How do we connect to them. 
  * How is che-in-che launched? 
  * How do we launch debug adapters (if necessary)? 
  * How do we connect to the debug network addresses?
* Minimal Feature list
  * Multiple debug targets at the same time (minimum: Theia, Che server, jdt.ls sidecar)
  * Connect to che in che debug targets
  * Line breakpoints
  * List of threads
  * Source lookup & display line 
  * Display Call stack of stopped thread
  * Display stack frame variables
  * Thread Stop/Resume action
  * Step over/into(/out)

**Comment by mkwork** [comment]
Hello.
I've reviewed debug adapter protocol in case of it's integration with vim or emacs and find out some vendor lock in.
While in LSP all capabilities and possible outputs are defined in protocol itself, vscode debugging api is split into two parts:
* D(ebug)A(adapter)P(protocol) server
* Extension part with full support of vscode api

While DAP part implementation strategy is clear, Extension part can potentially call any of vscode api. So there no way to reuse vscode extensions without support of vscode api in general.

Please be aware of this.

I think, that DAP protocol part could be got as some kick start part of really open specification. Humble individual like me can't support and promote such great thing, contribute only. But I believe project like yours is able to implement such great effort.

**Comment by mkwork** [comment]
@tsmaeder Yep. I talk about reusing debug adapters. Them can be rely on vscode extension part. Imho, thats a reason why there are tons of open LSP extensions, and few open extensions for DAP. And no more frontends for DAP as I know.

**Comment by tsmaeder** [comment]
Implementation task & epics

https://github.com/eclipse/che/issues/8929 Connect to Debug Target

**Comment by benoitf** [comment]
@tolusha @tsmaeder should we close this issue ?

**Comment by tsmaeder** [comment]
I guess that would be up to @slemeur
