### ISSUE TITLE
Analyze Selenium Test Failures for jdt.ls

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8414]
We need to go through failures in Selenium tests with the jdt.ls branch and analze whether

1. The behavioural difference is acceptable and the test should be changed accordingly.
This needs to be accepted by product managment (@slemeur)
2. The behaviour is wrong with jdt.ls
We need a taks created and planned for fixing.

In case we issues that block running tests, we migh have to interrupt this task until the blocking issue has been resolved.
- [x] Adopt selenium tests for JDT LS https://github.com/eclipse/che/issues/8466
- [x] LS hover in editor overlaps dialog windows https://github.com/eclipse/che/issues/8555
- [x] JDT LS doesn't resolve maven multi-module project after import 
 https://github.com/eclipse/che/issues/8510
- [x] Organize Imports action doesn't show an import dialog if more than one import is possible for unresolved reference https://github.com/eclipse/che/issues/8593
- [x] JDT LS autocomplete selection doesn't finish the code statement, brackets are missing https://github.com/eclipse/che/issues/8609
- [x] JDT LS Quick Fix action doesn't show any proposals https://github.com/eclipse/che/issues/8617
- [x] Method parameters hints https://github.com/eclipse/che/issues/8532
- [x] Commands do not work if the JDT LS is not started https://github.com/eclipse/che/issues/8673
