### ISSUE TITLE
Create the list of features which are not covered by functional tests 

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#8434]
On this moment we have more than 500 E2E tests that cover main functional units. But some new features still not covered, We should find this one and add to list for  watching.
- [ ] Hot update on OCP https://github.com/eclipse/che/issues/9646
- [ ] Control + P feature for hints of arguments methods.
- [ ]  Add usecase for filewatcher after refreshing page according to issue: https://github.com/eclipse/che/issues/9541
- [ ] Add tests for covering LS. features according to test plan: [test plan for LS:](https://github.com/eclipse/che/wiki/Test-plan-for-checking-Language-servers)
- [ ] Complete covering of  Dashboard features according test plan:  [Dashboard testplan](https://docs.google.com/document/d/1HbU9rzto8wT-6CFE8GFPi3BEW60suVmSmxDkomqbxwQ/edit)
- [ ] Create selenium test for checking add maven project and module https://github.com/eclipse/che/issues/6905
- [ ] Create selenium test for check interactions between machine processes https://github.com/eclipse/che/issues/6242
- [ ] Create E2E test for checking Hot update feature for wsmaster
- [ ] Using other gitproviders with factories (gitlab, bitbacket) -?
- [ ] Console/machine statements
- [ ] Consoles buttons and scroll
- [ ] Consoles selection test -?
- [ ] Uploading key
- [ ] WS. status widget
- [ ] Show/hide toolbar. Toolbar commands cut/copy/delete
- [ ] Import from che config file (Project menu)
- [ ] GWT superdevmode -?
- [ ] Items from context menu (cut/copy/delete, git commands etc.)
- [ ] Clarify how test runner we are using. Complete php runner test
- [ ] DialogAbout community menu
- [ ] Searching content with irregular encoding (for example umlauts in german lang.)
- [ ] Nav. bar (many features, clarify most valuable)
- [ ] Check git features in the  bottom bar
- [ ] Implement the test described [here :](https://github.com/eclipse/che/issues/9770)
- [ ] Implement the test described [here :](https://github.com/eclipse/che/pull/9689)
- [ ] Add/Delete remote repository
- [ ] Add second remote repository
- [ ] Merge local branch
- [ ] Rename local branch
- [ ] Remove from index
- [ ] Add to index by multi-select
- [ ] Import a private repository
---------------------------
**Preferences:**
- [ ] Customizing codeformatter
- [ ] Editor settings - clarify how use cases should be included (because many variants)
- [ ] Welcome enable/disable -?
- [ ] Plugin list
- [ ] Maven checkbox Show artifact id in project explorer
- [ ] Customizing yaml schema and interaction with YAML LS.
- [ ] Contribute #9852

**Comment by musienko-maxim** [comment]
Not covered features on Dashboard:

the Diagnostic feature(for Che 6.2.0 it doesn't work - eclipse/che#8501);
Che documentation(we need to check at least documentation links);
the Stacks list page;
a new stack page;
a stack details page;
a factory details page;
Volumes, Config, Share and SSH tabs on workspace details page.

**Comment by dmytro-ndp** [comment]
@musienko-maxim: I have published list of non-covered features [here](https://github.com/eclipse/che/wiki/List-of-Eclipse-Che-6-features-which-haven't-been-covered-by-selenium-tests-yet)
