### ISSUE TITLE
Theia/Che LSP Feature Gap

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8514]
Stuff to do for languages team
### JDT.LS specific features
* Usages View 
* [ ] Reuse jdt.ls workspace #10325 
* [x] File Structure View #10326
Che file structure is different from "document symbols" in that it shows a tree and inherited members.
* [x] Implementers Search https://github.com/eclipse/che/issues/10324
* [x] Libraries https://github.com/eclipse/che/issues/8965
* [x] Che/Java Theia Contribution https://github.com/eclipse/che/issues/8940
* [x] Show class files for Java https://github.com/eclipse/che/issues/9972
* UI for simple projects
  * [ ] Show classpath in dialog for java projects #10327 
  * [ ] Implement add jar
  * [ ] implement add source folder
  * [ ] Mark/Unmark as source folder actions 
  * [ ] implement "create simple project wizard" (if applicable)
* Testing IDE ("run unit tests")
* Launching jdt.ls without opening a file
This is trivial if we control the Java front end contribution: activation is done when a promise is fullfilled that the front end language contribution controls.
* Rename Refactoring
Che offers extended UI (in particular a wizard with options and preview and structural changes) for renaming things. We have a custom command in che-ls-jdt that implements the back end for this. One thing that we will need to port is a way to apply those structural changes to the theia workspace.
* Move Refactoring
A custom command will be implemented analogous to rename. UI will need to be written.
* [x] Addressing a particular LS (aka jdt.ls) to use specific protocol extensions. https://github.com/eclipse/che/issues/8941
* [x] Suport jdt.ls Status Reports https://github.com/eclipse/che/issues/9970. Let's us see when jdt.ls is ready. 
* [ ] Support jdt.ls Progress Reports https://github.com/eclipse/che/issues/9971

### Langugage servers
Might need to work on language servers or implement launcher plugins for them.
* [x] Go integrated throught https://github.com/eclipse/che/pull/9803
* [x] Typescript Theia includes a TS language server
* [ ] Python
* [ ] C++ via https://github.com/eclipse/che/pull/7516/files
### Architectural diffs lsp related
* Theia IDE talks directly to language servers running on the back end (via a JSONRPC proxy endpoint running in the back end). The back end language contribution is responsible for starting the language server and setting up a forwarding connection for the front end. As a consequence, Theia runs a new copy of a language server for each instance of the Theia front end running (open Theia in a second tab, for example). Currently, this means that a new eclipse workspace is allocated each time Theia starts jdt.ls, which is not acceptable for Che-in-Che (10 min startup time).
* Registration similar to VSCode
Registration of languages and language servers is in the front end and based on Monaco languages and VSCode document selectors. When a language contribution is activated, a connection to the back end is activated that establishes a connection to an instance of the langugage server.
