### ISSUE TITLE
Hot update for wsmaster

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#8547]
### Description
Update Che server without restarting currently running workspaces.
Solve the issue generically for all SPIs and test on OSIO.
Support rolling-updates on OpenShift

- [x] Machine tokens become invalid when workspaces are recovered https://github.com/eclipse/che/issues/7785
- [x] Implement recovery for OpenShift infrastructure https://github.com/eclipse/che/issues/5919
- [x] Create a list of stateful components of ws-master  https://github.com/eclipse/che/issues/8870
- [x] Study possible ways to replicate JPA cache https://github.com/eclipse/che/issues/8922
- [x] Study possible ways to replicate HTTP sessions  https://github.com/eclipse/che/issues/8923
- [x] Rewrite auth mechanism for go agents https://github.com/eclipse/che/issues/9028
- [x] Do not use data volume to store agents on OpenShift/Kubernetes https://github.com/eclipse/che/issues/9040
- [x] Json RPC on ws-master in cluster mode | https://github.com/eclipse/che/issues/9201
- [x] Add an ability to use distributed cache for storing workspace statuses in WorkspaceRuntimes https://github.com/eclipse/che/issues/9206
- [x] Adapt ServiceTermination functionality to workspaces recovering    https://github.com/eclipse/che/issues/9317
- [x] Workspace Start/Stop failed while tomcat shutdown    https://github.com/eclipse/che/issues/9452
- [x] Adapt ServiceTermination functionality to workspaces recovering https://github.com/eclipse/che/issues/9317
- [x] Hot update testing on working master  https://github.com/eclipse/che/issues/9415
- [x] Document procedure of Recreate Hot Update https://github.com/eclipse/che/issues/9414
- [x] Remove the code which deletes CHE_DATA/lib in entrypoint.sh | https://github.com/eclipse/che/issues/9276
- [x] Server checkers works incorrectly when s8k/os workspaces are recovered 
 https://github.com/eclipse/che/issues/9453
- [x] Servers checkers won't be started if a workspace is started by another Che Server instance 
 https://github.com/eclipse/che/issues/9502
- [x] Document procedure of Rolling Hot Update  #9630
- [x] Temporary workspaces are removed after rolling update https://github.com/eclipse/che/issues/9663
