### ISSUE TITLE
IDE2-2018-03-06 (Sprint: 145)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#8702]
### Sprint Goals:
- Workspace loading application
- Run Theia with predefined list of plugins
- Create libs for Che API interactions

### Issues 
**Ann:**
- [ ] Manage the list of IDE plugins from dashboard https://github.com/eclipse/che/issues/8695

**Mykola:**
- [x]  [navigator] add a toggle to sync the editor and navigator selections https://github.com/theia-ide/theia/issues/227
- [x] Create Theia plugin for interactions with Che workspaces https://github.com/eclipse/che/issues/8697

**Oleksandr:**
- [x] Create Theia plugin for accessing Che workspace terminals https://github.com/eclipse/che/issues/8698

**Oleksii K.:**
- [x] Create TS lib implementing JSON RPC client https://github.com/eclipse/che/issues/8699
- [x] Create TS lib for Che workspace API communication https://github.com/eclipse/che/issues/8700 

**Oleksii O.:**
- [x] [Multiuser] Error when add a workspace to organization https://github.com/eclipse/che/issues/8497
- [x] Make UD permissive to unknown workspace recipes types which are supported by server side https://github.com/eclipse/che/issues/8571
- [x] [CHE 6] There is an error when open the workspace details of workspace created in suborganization https://github.com/eclipse/che/issues/7925
- [ ] Dashboard doesn't reconnect to a WebSocket endpoint if the previous connection failed  https://github.com/eclipse/che/issues/8675

**Sun:**
- [x] Creating a first minimal viable feature of pair programming with Che-Atom teletype https://github.com/redhat-developer/rh-che/issues/517

**Vitalii:**
- [x] UI for workspace loading application https://github.com/eclipse/che/issues/8682
- [ ] Investigation the Theia themes management https://github.com/eclipse/che/issues/8775

**Yevhen:**
- [x] Launch Theia IDE inside Che workspace based on the provided list of plugins https://github.com/eclipse/che/issues/8701
- [ ] Improving syntax highlighting in Theia https://github.com/eclipse/che/issues/8774

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova | 10 |
| Mykola Morhun| 13 |
| Oleksandr Andriienko | 13 | 
| Oleksii Kurynniy | 13 |
| Oleksii Orel | 10 |
| Sun Tan | 13 |
| Vitaliy Guliy | 13 |
|Yevhen Vydolob| 13 |
| **Total Budget** | **98** |
### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  98 | - |
| **Velocity** | - | - |
| **Focus Factor** | - | - |
