### ISSUE TITLE
Platform-2018-03-06 (Sprint: 145)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#8704]
### New Features
- [ ] Machine tokens become invalid when workspaces are recovered #7785   13sp

### Technical debts and bugs

- [x] Compose recipe doesn't respect mem_limit values other that plain number of bytes | https://github.com/eclipse/che/issues/8232 5sp
- [x] Remove exec/terminal agents from dependencies of ws-agent https://github.com/eclipse/che/issues/7482 5sp
- [x]  Stopping of inactive workspaces by timeout doesn't work in Eclipse Che https://github.com/eclipse/che/issues/8487 8sp
- [x] Display a meaningful error message when OS token has expired https://github.com/eclipse/che/issues/8223 8sp

### Finalize issues started in the previous sprint.
- [x] Make bootstrapping of OpenShift machines parallel https://github.com/eclipse/che/issues/7067  8sp 
- [x] Che should pull images in parallel when pulling docker images | https://github.com/eclipse/che/issues/7102 5sp
- [x] Failed to start the workspace when double-launching https://github.com/eclipse/che/issues/8306  5sp

### Unplanned
- [x] Authorize an application on GitHub from the 'Import GiitHub' does not work https://github.com/eclipse/che/issues/8288
- [x] Remove data about model entities/fields removed in Che6 from Che DB https://github.com/eclipse/che/issues/7634
- [x] Create a list of stateful components of ws-master  https://github.com/eclipse/che/issues/8870
- [x] Allow Logback logger  configuring with environment variables https://github.com/eclipse/che/issues/8997 
- [x] Unable to manage users by an admin https://github.com/eclipse/che/issues/9010
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 14d |
| Max Shaposhnik | 14d | 
| Michail Kuznyetsov | 14d | 
| Sergii Leshchenko | 14d | 
| Anton Korneta| 14d |
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 57 | 44 |

**Comment by skabashnyuk** [comment]
### Removed
Make progress in Hot update for wsmaster https://github.com/eclipse/che/issues/8547 - Epic is too big for 1 sprint, added one of the issues
### Added
Machine tokens become invalid when workspaces are recovered #7785

**Comment by skabashnyuk** [comment]
### Added Technical debts and bugs
- [ ] Make bootstrapping of OpenShift machines parallel https://github.com/eclipse/che/issues/7067  8sp 
- [ ] Che should pull images in parallel when pulling docker images | https://github.com/eclipse/che/issues/7102 5sp
- [ ] Failed to start the workspace when double-launching https://github.com/eclipse/che/issues/8306  5sp

**Comment by skabashnyuk** [comment]
### Added Technical debts and bugs
- [ ] Display a meaningful error message when OS token has expired https://github.com/eclipse/che/issues/8223 8sp

**Comment by skabashnyuk** [comment]
### Removed 
-  Abstraction level above workspace service layer https://github.com/eclipse/che/issues/8703 21sp
