### ISSUE TITLE
QE-2018-03-06 (Sprint: 145)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#8707]
### Issues tied to objectives
- [ ] Check that issues with the selenium/failure label have actual description https://github.com/eclipse/che/issues/8330 5sp
- [ ] Investigate reason of failing StepIntoStepOverStepReturnWithChangeVariableTest on CI https://github.com/eclipse/che/issues/8105 3sp
- [x] Save ws-agent logs of test workspaces which were used by failed selenium tests https://github.com/eclipse/che/issues/7889 1sp
- [x] Print selenium test statistics in the test log during the tests execution https://github.com/eclipse/che/issues/7719 2sp
- [x] Investigate reasons of randomly not parsed java files in the selenium tests https://github.com/eclipse/che/issues/8527 3sp
- [ ] Unexpected failing of NavigateToFileTest selenium test on CI https://github.com/eclipse/che/issues/8465 2sp
- [x] Improve NavigateToFileTest selenium test to find files using '*' and '?' characters https://github.com/eclipse/che/issues/8765 2sp
- [x] Create selenium test to cover creating of workspaces for organizations https://github.com/eclipse/che/issues/8763 2sp
- [ ] Log related test class name when creating test workspace https://github.com/eclipse/che/issues/8733 1sp
- [ ] Create optional selenium tests of work with private repo and organization https://github.com/eclipse/che/issues/8645 3sp
- [ ] Add ability to exclude github-specific selenium tests from test execution https://github.com/eclipse/che/issues/8634 3sp
- [ ] Create the list of features which are not covered by functional tests https://github.com/eclipse/che/issues/8434 5sp
- [x] Unexpected fail of ShowHintsCommandTest selenium test https://github.com/eclipse/che/issues/8770 1sp
 
### Unplanned 
- [ ] Investigate the failing selenium tests on CI jobs with unexpected 'keycloak refused' https://github.com/eclipse/che/issues/8788 3sp
- [x] Apply expand project tree by native clicks in the selenium tests related with bug #7161 for increase stability  https://github.com/eclipse/che/issues/8793 1sp
- [x] Method "ProjectExplorer#openItemByPath()" is closing items which are have been already opened before https://github.com/eclipse/che/issues/8802 1sp
- [x] [OCP-single] Investigate the failing selenium tests related to authorization on GitHub on CI job https://github.com/eclipse/che/issues/8831 3sp
- [x] Improve and rework selenium test 'WorkingWithPullConflictsTest'  https://github.com/eclipse/che/issues/8832 2sp
- [x] Create method for refreshing browser by JavaScript https://github.com/eclipse/che/issues/8841 1sp
- [x] Unexpected fail of selenium tests from organization package https://github.com/eclipse/che/issues/8828 1sp
- [ ] Sometimes the message about deleted file under filewatcher is absent in the events panel https://github.com/eclipse/che/issues/7339 2sp
- [x] Rework "ProjectExplorer" page object with "SeleniumWebDriverHelper" and "WebDriverWaitFactory" https://github.com/eclipse/che/issues/8854 3sp
- [x] Unexpected fail of WorkingWithTerminalTest selenium tests https://github.com/eclipse/che/issues/8858 1sp
- [x] Unexpected fail of ResolveDependencyAfterRecreateProjectTest selenium test https://github.com/eclipse/che/issues/8791 1sp
- [x] Fix creation of test users for selenium testing https://github.com/eclipse/che/issues/8871 1sp
- [x] Improve and rework selenium test 'FetchUpdatesAndMergeRemoteBranchIntoLocalTest' https://github.com/eclipse/che/issues/8875 3sp
- [x] Cover creating factories from the Dashboard by selenium test https://github.com/eclipse/che/issues/8891 3sp
- [x] EditFilesWithTabsTest opens redundant chromium window which doesn't close https://github.com/eclipse/che/issues/8902 3sp
- [x] Investigate an ability to decrease time of selenium test execution on CI by increasing number of test threads https://github.com/eclipse/che/issues/8863 1sp
- [x] Group locators from "CodenvyEditor" page object to enumerations, and remove redundant locators https://github.com/eclipse/che/issues/8950 1sp
- [x] Selenium tests of package 'org.eclipse.che.selenium.factory' are trying to delete not existed workspace https://github.com/eclipse/che/issues/8667 1sp
- [x] Change of user story flow for ProjectStateAfterRefreshTest selenium test https://github.com/eclipse/che/issues/8433 2sp
- [x] Unexpected fail of CreateAndDeleteProjectsTest selenium test https://github.com/eclipse/che/issues/8433 1sp
- [x] Investigate unexpectedly stopping a workspace after consuming DirectUrlFactoryWithSpecificBranch https://github.com/eclipse/che/issues/8616 1sp
- [ ] Create the list of features which are not covered by functional tests  https://github.com/codenvy/codenvy/issues/2604 2sp
- [x] Study possibility of catching logs networks from WebDriver https://github.com/eclipse/che/issues/8857 3sp
- [x] Rework methods from "CodenvyEditor" page object with using "SeleniumWebDriverHelper" and "WebDriverWaitFactory" classes https://github.com/eclipse/che/issues/8962 2sp
- [ ] Improve and rework selenium test 'CheckoutToRemoteBranchTest'  https://github.com/eclipse/che/issues/8986 3sp
- [ ] Improve and rework selenium test 'RevertCommitTest' https://github.com/eclipse/che/issues/8987 2sp
- [x] Add new methods to the SeleniumWebDriverHelper class https://github.com/eclipse/che/issues/8988 1sp
- [x] Update javadocs to actual state in the "SeleniumWebDriverHelper" class https://github.com/eclipse/che/issues/8999 1sp
- [ ] Inspect methods logic in the "CodenvyEditor" pageobject https://github.com/eclipse/che/issues/9006 3sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 16 |
| Maxim Musienko | 16 |
| Dmytro Nochevnov | 16 |
| Igor Ohrimenko | 16 |
| Sergey Skorik | 16 |
| Total | 80 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 33 | 11 |

### Retrospective Comments
- 98% tests success rate on single-user on docker assembly has been achieved;
- it needs to plan less SP in next sprint because of daily routing tasks and a lot off urgent unplanned issues we have usually each sprint;
- pay attention to new warning messages may occur during building the Selenium project. Don't merge such PRs.
