### ISSUE TITLE
Languages Sprint 145 issue

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8708]
Issues for sprint 145 ordered by priority.
# Availability 
@svor 15d
@tolusha 15d
@tsmaeder 4d
@bdshadow 7d
@JPinkney 15d
@vrubezhny 11d

# In Progress
- [x] https://github.com/eclipse/che/issues/8532
- [x] https://github.com/eclipse/che/issues/8510
# Candidates (by priority)
- [ ] https://github.com/eclipse/che/issues/8335 5d  @bdshadow 
- [x] https://github.com/eclipse/che/issues/8580 2d 
- [x] https://github.com/eclipse/che/issues/8593 2d @tolusha 
- [x] https://github.com/eclipse/che/issues/8412 Progress UI for Language Servers 6d
- [x] https://github.com/eclipse/che/issues/8383 Debug Adapter Protocol 6d  @tsmaeder @tolusha 
- [x] https://github.com/eclipse/che/issues/8720 Set up Theia Debugger Project 5d @tolusha 
- [ ] https://github.com/eclipse/eclipse.jdt.ls/issues/522 Allow custom notifications 0.5d
- [ ] https://github.com/eclipse/che/issues/8721 Update Libraries, etc. based on JDT notifications 8d @vrubezhny 
- [ ] https://github.com/eclipse/che/issues/8666 Cleanup unused Java support Part 2) 3d
- [x] https://github.com/eclipse/che/issues/8572 Use formatter custom option 5d @svor 
- [ ] https://github.com/eclipse/che/issues/8557 Formatter is broken 3d
- [x] https://github.com/eclipse/che/issues/8436 Open Symbol is broken in jdt.ls Branch 2d @JPinkney 
- [ ] https://github.com/eclipse/che/issues/8467 Quick documentation is broken when use java language server 7d @JPinkney 

74 d total

**Comment by tsmaeder** [comment]
My priorities:

    Rename/Move refactorings
    Progress on progress
    Che-in-Che
    Fix bugs.

**Comment by tsmaeder** [comment]
Rename: gorkem
Progress: decide on implementation/filtering->merge PR on jdt.ls, implement on Che side.
Che-in-che: implement not sending updateProject so often-> should reduce RAM to < 3Gig.

-> Anatoli->familiarize with debug protocol, Theia , Thomas/Anatolii-> define MVP for Theia self-hosting.
-> Josh continue with YAML LS, after (either jdt.ls or Theia debugger-> talk to josh).

**Comment by tsmaeder** [comment]
I will make up a list of candidate tasks on monday for planning.
