### ISSUE TITLE
IDE-2018-03-06 (Sprint: 145)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8728]
### Goals

- [ ] Create Theia plugin for management SSH keys #8727
- [ ] Create Theia plugin for GitHub #8740

#### Artem 
- [ ] _[Theia]_ UI Widget for SSH key management for Theia #8737
- [x] No code validation for C# files after workspace restart #6355
- [x] Command Editor fails to properly initialize its Dirty state after it's saved #8475
- [x] Editor lose focus at switching of displaying panels mode #7616

#### Dmytro 
- [ ] _[Theia]_ Develop server-side for SSH key management for Theia #8738
- [x] Thread-unsafe collections used for subscription contexts #7700
- [x] Uploading zip file corrupts file #8416

#### Roman 
- [ ] _[Theia]_ Client side OAuth Authorizations API for Theia #8739
- [x] Project explorer should not show hidden folders from `/projects` #7302
- [x] Cursor jumps at java refactoring renaming in linked mode #8136
- [x] Expected items are not present in the "Navigate File Structure" form #7947
- [x] The 'Navigate To File' works incorrectly with '*' symbol #8735

#### Vitalii 
- [ ] Unexpected the hanging of the Loader after actions #8300
- [x] Download sources for some libs failed #6334
- [x] [Regression] PHP language server fails on code completion apply #5377

#### Vlad
- [ ] _[Theia]_ Create widget for showing github repository by user for Theia IDE #8741
- [x] Browser with IDE hang after git hard resetting #7773
- [x] Refactoring method does not work properly in certain case #7768
- [x] Make an ability to handle focus and key press event on CustomListBox #8574
- [x] 'Java refactoring rename' dialog does not handle pressing Enter key #8124

#### Igor 
- [x] _[Theia]_ Create server side component for GitHub API communications for Theia IDE #8742
- [x] The hidden folder becomes visible after applying custom formatting to a workspace #8575
- [x] Unexpected hanging of a browser during using of CHE #7534
- [ ] [OCP] Cannot stop a process in the Terminal by Ctrl+C #8390

### Merge-ready PRs
- [ ] add error markers in Project Explorer #7576 (need to adapt GitColorsTest)

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 15 |  
| Vlad |15 |  
| Dmytro  | 15 |   
| Roman  |15 | 
| Vitalii  |15|    
| Igor |15 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 90/70   |  |
| **Velocity** | |  |
