### ISSUE TITLE
Reduce size of one-thread selenium tests to decrease time of test execution

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#8903]
### Description
Now we have test suite ['One-thread Eclipse Che selenium tests'](https://github.com/eclipse/che/blob/6.1.0/selenium/che-selenium-test/src/test/resources/suites/CheOneThreadTestsSuite.xml) which contains 48 tests and its execution lasts about 1 hour.
This is kind of bottle-neck for decreasing overall time of tests execution by increasing number of test threads.

### Sub tasks
- [x] Rework git-selenium tests for ability launching in multithreaded mode (#8153)
- [x] Move creation of test user from test launcher to selenium tests framework (#9277)
- [x] Rework organization-related tests to be executed in multi-thread mode (#9019)
- [x] Rework factory-related tests to be executed in multi-thread mode (#9020)

Related issue: #8863

**Comment by dmytro-ndp** [comment]
After update we have:
- 19 tests (was 48 tests);
- [25 minutes](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/195/consoleText) for _Multiuser Eclipse Che on OCP_ (was 1 hour).

Next test classes are remained in one-thread suite because they require additional admin user:
- CreateRootOrganizationTest
- DeleteOrganizationByBulkTest
- DeleteOrganizationInListTest
- SystemAdminOrganizationTest

Next test classes are remained in one-thread suite because they require additional github users:
- AuthorizeOnGithubFromDashboardTest
- AuthorizeOnGithubFromPreferencesTest
- CheckoutToRemoteBranchTest
- PullRequestPluginTest
- PullRequestPluginWithForkTest
- PushChangeNotUpdatedRepoTest
- PushingChangesTest
- ImportProjectFromGitHubTest
- DirectUrlFactoryWithKeepDirectoryTest
