### ISSUE TITLE
Languages Sprint 146

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#8910]
# Availability
@tsmaeder: 13d
@tolusha 
@svor 
@vrubezhny 
@JPinkney 

Topics: Finish up hurdles to merging to master, Get started with Theia development
Priority list:

- [ ] https://github.com/eclipse/che/issues/8929 Connect to Debug Target
  *  [x]  #8953 
  *  [x]  #8954  
  *  [ ] #8955 
  *  [ ] #8956 
  *  [ ] #8957 
- [x] https://github.com/eclipse/che/issues/8881 Update LSP4J to latest
- [ ] https://github.com/eclipse/che/issues/6748 Implement Move Refactoring
- [ ] https://github.com/eclipse/che/issues/8939 Rename Refactoring
- [x] https://github.com/eclipse/che/issues/8673 Commands to not work when jdt.ls not started
- [ ] https://github.com/eclipse/che/issues/8964 LS per Project issue
- [ ] https://github.com/eclipse/che/issues/8880 Update Che Doc for jdt.ls use
- [ ] https://github.com/eclipse/che/issues/8940 Create Che Java Contribution
- [ ] https://github.com/eclipse/che/issues/8941 Address jdt.ls specifically
- [ ] https://github.com/eclipse/che/issues/8965 Implement jdt.ls "libraries" feature
- [ ] https://github.com/eclipse/che/issues/8966 Sidecar extensibility story
- [ ] https://github.com/eclipse/che/issues/8874 Run jdt.ls as a sidecar

Copied from Sprint #145
- [ ] https://github.com/eclipse/che/issues/8335 Determine Che-in-Che Resource Requirements with jdt.ls
- [x] https://github.com/eclipse/eclipse.jdt.ls/issues/522 Allow custom notifications
- [ ] https://github.com/eclipse/che/issues/8721 Update Libraries, etc. based on JDT notifications
- [x] https://github.com/eclipse/che/issues/8557 Dto Generation is broken for Formatter Options
- [ ] https://github.com/eclipse/che/issues/8467 Quick documentation is broken when use java language server

**Comment by tsmaeder** [comment]
What needs to be done before jdt.ls merge
* Rename
* Move
* Cleanup (remove jdt stuff)
* Start jdt.ls when running java commands

Initial tasks for theia/che
 * set up extension to consume che-jdt.ls instead of jdt.ls
 * find way to run jdt.ls without opening file
 * find way to address jdt.ls specfically

**Comment by slemeur** [comment]
LGTM
