### ISSUE TITLE
IDE2-2018-03-27 (Sprint: 146)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#8959]
### Sprint Goals:
1. Extensibility model implementation
2. Theia plugin with widget that gives ability to connect to workspace's machine with terminal.
3. Finish work on library for workspace API communication and use it in existing projects.
4. Factories support in Theia IDE
5. Display machines information in Theia 

## 1. Extensibility model implementation
- [x] Implement the proxy for plugins API https://github.com/eclipse/che/issues/9063 **Yevhen**
- [ ] Look the extensions manager in Theia to be able to implement another one for supporting introduced extensibility model https://github.com/eclipse/che/issues/9064 **Mykola**
- [x] Investigate the better way for providing list of plugins to web worker https://github.com/eclipse/che/issues/9068 **Oleksii K.** and **Yevhen**

## 2. Theia plugin with widget that gives ability to connect to workspace's machine with terminal.
- [x] Create Theia plugin for accessing Che workspace terminals https://github.com/eclipse/che/issues/8698 **Oleksandr**

## 3. Finish work on library for workspace API communication and use it in existing projects.
- [x] Finish work on https://github.com/eclipse/che/issues/8700 **Oleksii K.**
- [x] Use the library https://github.com/eclipse/che/issues/8700  inside UD **Oleksii K.** 
- [x] Dashboard doesn't reconnect to a WebSocket endpoint if the previous connection failed  https://github.com/eclipse/che/issues/8675 **Oleksii K.**
- [ ] Use the library https://github.com/eclipse/che/issues/8700  inside application loader **Vitalii**

## 4. Factories support in Theia IDE
- [ ] Make factories work with Theia IDE https://github.com/eclipse/che/issues/9074 **Sun**

## 5. Display machines information in Theia 
- [x] Widget to display the state of the different containers of the workspace https://github.com/eclipse/che/issues/8993 **Oleksii O.**

## Other  issues: 
**Mykola:**
- [x] Fix feedbacks on https://github.com/theia-ide/theia/pull/1375

**Vitalii:**
- [ ] Support for EditorConfig https://github.com/eclipse/che/issues/7588

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova | 5 |
| Mykola Morhun| 12 |
| Oleksandr Andriienko | 12 | 
| Oleksii Kurynniy | 12 |
| Oleksii Orel | 12 |
| Sun Tan | 10 |
| Vitaliy Guliy | 10 |
|Yevhen Vydolob| 12 |
| **Total Budget** | **85** |
### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 85 | - |
| **Velocity** | - | - |
| **Focus Factor** | - | - |
### Retrospective Comments
The retrospective [details](https://docs.google.com/drawings/d/19zVO5jMI5QOpZNbxQsGrfbtff-77e36qOevSUcJEoA0/edit)
