### ISSUE TITLE
Platform-2018-03-27 (Sprint: 146)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#8971]
### Features related to Hot update for wsmaster
- [x] Implement recovery for OpenShift infrastructure | https://github.com/eclipse/che/issues/5919 21sp
- [x] Machine tokens become invalid when workspaces are recovered #7785   2 sp
- [x] Study possible ways to replicate JPA cache https://github.com/eclipse/che/issues/8922 2sp
- [x] Rewrite auth mechanism for go agents | https://github.com/eclipse/che/issues/9028 8sp
- [x] Do not use data volume to store agents on OpenShift/Kubernetes | https://github.com/eclipse/che/issues/9040 13sp

### Technical debts and bugs
 - [x] Cannot register a user after it has been deleted in Keycloak | https://github.com/eclipse/che/issues/8081 8sp
- [ ]  Unable to override idle timeout for a particular user | https://github.com/eclipse/che/issues/8951 8sp 
- [x] Provide some meneful error message during user manipulation operation in case if Che is configured to work with Keycloak | https://github.com/eclipse/che/issues/9015 8sp
- [x] Document how to configure JDBC datasource of workspace master | https://github.com/eclipse/che/issues/9037 5sp

### Unplanned
 - [x] Review indexes on che_worker, che_member_actions, che_organization, che_worker_actions, che_member https://github.com/eclipse/che/issues/9076
- [x]  Store workspace expiration times into DB https://github.com/eclipse/che/issues/9014  
- [ ] Add external che api url as workspace environment variables https://github.com/eclipse/che/issues/9323
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 12d |
| Max Shaposhnik | 12d | 
| Michail Kuznyetsov | 12d | 
| Sergii Leshchenko | 12d | 
| Anton Korneta| 12d |
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 75 | 59 |

**Comment by skabashnyuk** [comment]
### Added
- Cluster mode for periodical jobs on ws-master | https://github.com/eclipse/che/issues/9014
- Provide some meneful error message during user manipulation operation in case if Che is configured to work with Keycloak | https://github.com/eclipse/che/issues/9015

**Comment by skabashnyuk** [comment]
### Added
- Rewrite auth mechanism for go agents | https://github.com/eclipse/che/issues/9028 
- Do not use data volume to store agents on OpenShift/Kubernetes | https://github.com/eclipse/che/issues/9040 
- Document how to configure JDBC datasource of workspace master | https://github.com/eclipse/che/issues/9037 



### Removed 
- Cluster mode for periodical jobs on ws-master | https://github.com/eclipse/che/issues/9014 
- Implement supporting of compose based recipes by OpenShift infrastructure | https://github.com/eclipse/che/issues/7860
