### ISSUE TITLE
IDE-2018-03-27 (Sprint: 146)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#8979]
#### Finalize:
- [x] Create Theia plugin for management SSH keys #8727

#### Start work on new Theia improvement: 

- [ ] Support commands macro in Theia tasks #8974
- [ ] Ability to quickly find the preferences (from menu or command palette) #8981
- [ ] Show/hide hidden files in Theia #8977
- [ ] Ability to visualize the maven modules in Theia Project Explorer #8978

#### Artem 
- [x] _[Theia]_ UI Widget for SSH key management for Theia #8737 (finalize)
- [ ] _[Theia]_ Support commands macro in Theia tasks #8974
- [x]  Import of zipped project causes 'Can't find project' ws-agent exception #8759 

#### Dmytro 
- [x] _[Theia]_ Develop server-side for SSH key management for Theia #8738 (finalize)
- [ ] _[Theia]_ Theia Command Palette Improvement #8976
- [ ] Not possible to add new file extension to make it work with LS. "documentFilters" does not work #8925
- [x] File Watcher exclude feature doesn't work after restarting workspace #6487 

#### Roman 
- [ ] _[Theia]_ Client side OAuth Authorizations API for Theia #8739
- [x] Deleted through terminal project is still present in the Project Explorer after web page updating #8969 
- [x] Error/Warnings items list doubles after restarting workspace #8958
- [x] Unexpected fails of selenium tests after web page refreshing #7551

#### Vitalii 
- [ ] _[Theia]_ Ability to quickly find the preferences (from menu or command palette) #8981
- [ ] Unexpected the hanging of the Loader after actions #8300
- [x] Fix a sample assembly with custom plugins  #7907
- [ ] JAVA_HOME is null when running test via UI #9105 (unplanned)

#### Vlad
- [ ] _[Theia]_ Create widget for showing github repository by user for Theia IDE #8741
- [ ]  _[Theia]_ Show/hide hidden files in Theia #8977
- [ ] Project import is not tracked on multiple browsers #2428

#### Igor 
- [ ] _[Theia]_ Ability to visualize the maven modules in Theia Project Explorer #8978
- [x] It is impossible to add a sample as an internal module #8752 

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 15 |  
| Vlad |15 |  
| Dmytro  | 15 |   
| Roman  |15 | 
| Vitalii  |15|    
| Igor |15 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 90/70   |  |
| **Velocity** | |  |
