### ISSUE TITLE
QE-2018-03-27 (Sprint: 146)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#9013]
### Issues tied to objectives
- [x] Investigate reason of failing StepIntoStepOverStepReturnWithChangeVariableTest on CI https://github.com/eclipse/che/issues/8105 3sp
- [x] Unexpected failing of NavigateToFileTest selenium test on CI https://github.com/eclipse/che/issues/8465 2sp
- [x] Inspect methods logic in the "CodenvyEditor" pageobject https://github.com/eclipse/che/issues/9006 3sp
- [x] Improve and rework selenium test 'CheckoutToRemoteBranchTest'  https://github.com/eclipse/che/issues/8986 3sp
- [x] Improve and rework selenium test 'RevertCommitTest' https://github.com/eclipse/che/issues/8987 2sp
- [ ] Rework organization-related tests to be executed in multi-thread mode https://github.com/eclipse/che/issues/9019 3sp
- [ ] Rework factory-related tests to be executed in multi-thread mode https://github.com/eclipse/che/issues/9020 1sp

### Unplanned 
- [x] Cover Volumes, SSH and Share tabs in workspace details by selenium test https://github.com/eclipse/che/issues/9041 3sp
- [x] Delete the 'try/catch' from the tests in the 'opendeclaration' package https://github.com/eclipse/che/issues/9057 1sp
- [x] Apply expand the project tree by native clicks in the 'Eclipse0120Test' https://github.com/eclipse/che/issues/9058 1sp
- [x] Add new common methods to the "SeleniumWebDriverHelper" class https://github.com/eclipse/che/issues/9061 1sp
- [x] Update javadocs to actual state in the "CodenvyEditor" class https://github.com/eclipse/che/issues/9085 3sp
- [x] Change the methods in the 'GitRevertCommit' using the classes 'SeleniumWebDriverHelper' and 'WebDriverWaitFactory' https://github.com/eclipse/che/issues/9104 1sp
- [x] Participation in openshift.io manual testing session. https://github.com/eclipse/che/issues/9106 8sp
- [ ] Unexpected failure of selenium tests which are create workspaces from Dashboard https://github.com/eclipse/che/issues/9100 2sp
- [x] Make sure GitHub test repo has been created in selenium tests https://github.com/eclipse/che/issues/9125 1sp
- [x] Remove inheriting between "CodenvyEditor" and "CommandsEditor" https://github.com/eclipse/che/issues/9135 3sp
- [x] Inspect methods logic in the "CommandsEditor" pageobject https://github.com/eclipse/che/issues/9169 2sp
- [ ] Return the test for checking activity a workspace https://github.com/eclipse/che/issues/9166 2sp
- [x] Delete not actual "known issue" from "editor" and "projectexplorer" test packages. https://github.com/eclipse/che/issues/9209 1sp
- [x] Update javadocs to actual state in the "CommandsEditor" class https://github.com/eclipse/che/issues/9238 2sp
- [x] Unexpected fail of CheckRestoringWorkspaceAfterStoppingWsAgentProcess selenium test on OCP https://github.com/eclipse/che/issues/9202 1sp
- [x] Add new methods to the "SeleniumWebDriverHelper" class https://github.com/eclipse/che/issues/9247 1sp
- [x] Rework static classes "CommandsEditorType" and "CommandsMacrosLinkType" to enumerations https://github.com/eclipse/che/issues/9253 1sp
- [ ] Unexpected fail of TransitiveDependencyTest in the selenium tests https://github.com/eclipse/che/issues/9258 1sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 13 |
| Maxim Musienko | 13 |
| Dmytro Nochevnov | 13 |
| Igor Ohrimenko | 13 |
| Sergey Skorik | 13 |
| Total | 65 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 17 | 13 |

### Retrospective Comments
- Debugger related issue https://github.com/eclipse/che/issues/8105 took more time than it supposed to.
