### ISSUE TITLE
Factories Support in IDE.Next

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9074]
## Goal
Factories are templates containing information to automate the generation of a new workspace from a URL. Factories can be used to create workspace replicas of existing workspace or automate the provisioning of dynamically defined workspaces. Factories are key to the value of Eclipse Che.

Factories are oftenly used to provide a ready-to-code workspace, containing a project, a set of commands associated with pre-configured runtimes and debuggers. They provide value to users, contributors and the community overall as it allows to provide sample workspace with a pre-defined technology set. 

We should have Factories working with Theia IDE with the same capabilities that we currently have with the GWT.IDE. 

## Description
Most of the staff of factory accepting is done by the dashboard (checking policies, workspace creation) - we will keep it there. The Theia should be able to import factory project(s) and execute provided IDE actions.

## Features

 **Import**
- [x] From master
- [x] From a branch
- [ ] With sparse checkout
- [ ] Private repositories

**Workspace Configuration**
- [ ] Commands

 **Events**
- [ ] Redefine the different workspace lifecycle events:
OnIDELoading, OnIDELoaded, OnWorkspaceRunning, OnWorkspaceStopping, OnWorkspaceStopped

**Actions**
- [x] Run Command
- [x] Open File(s) at a Line
- [ ] Warn on Uncommitted Changes

## Tasks

- [x] spike, testing what is working and what is not: https://docs.google.com/document/d/1kZQsD6rOzv6uSLKkpCPTHjyYSv8YCnwwA3M43GuzfKk/edit?usp=sharing
- [x] Import projects in theia IDE from a factory: implement git import in Theia node (server) as a rest service #9218
- [x] Import projects in theia IDE from a factory: read factory metadata from the client side #9221
- [x] branch checkout during clone https://github.com/eclipse/che/issues/9837 
- [x] git clone is randomly failling https://github.com/eclipse/che/issues/9838
- [x] run commands https://github.com/eclipse/che/issues/9840
- [x] optimizing che-theia-factory loading https://github.com/eclipse/che/issues/10062

**Comment by sunix** [comment]
from stevan:
1. look at what is working and not
  - Factories with Theia IDE should be working the same
  - Import from URL for Master, Branch and Subfolder

2. Factory Actions
Redefine the different workspace lifecycle events:
OnIDELoading, OnIDELoaded, OnWorkspaceRunning, OnWorkspaceStopping, OnWorkspaceStopped
Actions:
    - Run Command
    - Open File at a Line
    - Warn on Uncommitted Changes

**Comment by sunix** [comment]
Missing import project (from factory definition AND workspace definition)
start from https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/factory/utils/FactoryProjectImporter.java ?
I guess we won't use the wsagent import project services anymore but the clone from theia right ?

**Comment by slemeur** [comment]
Closed in favor of https://github.com/eclipse/che/issues/12925
