### ISSUE TITLE
QE-2018-04-17 (Sprint: 147)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#9129]
### Issues tied to objectives
- [x] Improve and rework the 'CheckoutReferenceTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9139 2sp
- [x] Improve and rework the 'CheckoutToRemoteBranchWhichAlreadyHasLinkedLocalBranchTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9140 1sp
- [x] Improve and rework the 'ImportProjectIntoSpecifiedBranchTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9149 2sp
- [x] Improve and rework the 'ImportRecursiveSubmoduleTest' for ability to launching in multi-threaded mod https://github.com/eclipse/che/issues/9150 2sp
- [x] Improve and rework the 'KeepDirectoryGitImportTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9151 3sp
- [x] Improve and rework the 'PullRequestPluginTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9152 2sp
- [x] Improve and rework the 'PullRequestPluginWithForkTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9155 2sp
- [x] Improve and rework the 'PushChangeNotUpdatedRepoTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9156 3sp
- [x] Improve and rework the 'PushingChangesTest' for ability to launching in multi-threaded mode https://github.com/eclipse/che/issues/9157 2sp
- [ ] Rework organization-related tests to be executed in multi-thread mode https://github.com/eclipse/che/issues/9019 2sp
- [x] Investigate an ability to run selenium tests suites in parallel threads https://github.com/eclipse/che/issues/9279 3sp
- [x] Move creation of test user from test launcher to to selenium tests framework https://github.com/eclipse/che/issues/9277 3sp

### Unplanned 
- [x] Error of binding of GitHub optional properties into selenium tests https://github.com/eclipse/che/issues/9338 1sp
- [ ] Create selenium test for checking text selection and a copy-paste functions in console https://github.com/eclipse/che/issues/6239 2sp
- [x] Unexpected failure of selenium tests which are create workspaces from Dashboard https://github.com/eclipse/che/issues/9100 2sp
- [x] Clarify reason of failing the CheckGeneratingMavenArchetypeTest https://github.com/eclipse/che/issues/9365 1sp
- [x] Unexpected fail of CheckRestoringWorkspaceAfterStoppingWsAgentProcess selenium test https://github.com/eclipse/che/issues/9388 1sp
- [x] Add known issue #9393 to the "RenameProjectTest" selenium test https://github.com/eclipse/che/issues/9394 1sp
- [x] Remove catching issue #7551 from selenium tests https://github.com/eclipse/che/issues/9403 1sp
- [x] Unexpected fail of UpdateListOfLibraryTest selenium test https://github.com/eclipse/che/issues/9413 1sp
- [x] Unexpected fail of "CheckRestoringSplitEditorTest" selenium test https://github.com/eclipse/che/issues/9432 2sp
- [ ] Eclipse Che selenium tests failed on OSIO because of inaccessible admin account https://github.com/eclipse/che/issues/9454 1sp
- [ ] Investigate execution of Eclipse Che dashboard related selenium tests on OSIO https://github.com/eclipse/che/issues/9374 3sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 14 |
| Maxim Musienko | 14 |
| Dmytro Nochevnov | 14 |
| Igor Ohrimenko | 14 |
| Sergey Skorik | 14 |
| Total | 70 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 27 | 25 |

### Retrospective Comments
Almost all planned tasks finished.
- [ ] Rework organization-related tests to be executed in multi-thread mode https://github.com/eclipse/che/issues/9019 moved to next sprint
