### ISSUE TITLE
Platform-2018-04-17 (Sprint: 147)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9199]
### Features related to Hot update for wsmaster

- [x] Implement recovery for OpenShift infrastructure | https://github.com/eclipse/che/issues/5919  21sp
- [x] Add an ability to use distributed cache for storing workspace statuses in WorkspaceRuntimes https://github.com/eclipse/che/issues/9206  13sp
- [x] Json RPC on ws-master in hot-update mode | https://github.com/eclipse/che/issues/9201  13sp

### Technical debts and bugs

- [x] Make it possible to specify non-default timeout for building docker image | https://github.com/eclipse/che/issues/9130 | 13sp
- [x] Unable to override idle timeout for a particular user | https://github.com/eclipse/che/issues/8951 | 8sp
- [x] Provide some meneful error message during user manipulation operation in case if Che is configured to work with Keycloak | https://github.com/eclipse/che/issues/9015 | 8sp
- [x] Provide logs from bootstrapping exec into ws pod | https://github.com/eclipse/che/issues/9180 | 8sp
- [x] Cannot register a user after it has been deleted in Keycloak | https://github.com/eclipse/che/issues/8081 | 8sp

### Unplanned
- [x] Workspace PVCs aren't deleted when pods get created in one namespace https://github.com/eclipse/che/issues/9431

#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 15d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15d | 
| Sergii Leshchenko | 15d | 
| Anton Korneta| 15d |
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 84 | 84 |

**Comment by bmicklea** [comment]
I think you're missing a link for:
>workspace runtimes over the cluster 13sp

**Comment by skabashnyuk** [comment]
@bmicklea 
### Updated
workspace runtimes over the cluster 13sp - > https://github.com/eclipse/che/issues/9206  Add an ability to use distributed cache for storing workspace statuses in WorkspaceRuntimes  13sp
