### ISSUE TITLE
Plugin model for next gen Che

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9203]
We need to define the plugin model for next gen Che:
- Client side only plugin
- Server side only plugin
- Client and Server side plugin
- Client and Server as sidecar plugin
A plugin will be be packaged in a way to allow those different cases.

The more details are described in the [document](https://docs.google.com/document/d/1oGYDleMWM3A5kQDOuIxBwYQ9xbfK0h4ybfNqVdcrlr4/edit#heading=h.o7b8aqo1hebm)

And here is the list of tasks that should be investigated and implemented to archive the new plugin model:
- [x] Implement the proxy for plugins API https://github.com/eclipse/che/issues/9063
- [x] Investigate the better way for providing list of plugins to web worker https://github.com/eclipse/che/issues/9068
- [ ] Create Theia plugin that introduces new extension model https://github.com/eclipse/che/issues/9064
- [ ] POC of server communication with the server plugin and browser https://github.com/eclipse/che/issues/9183
- [ ] Add support for plugins registry https://github.com/eclipse/che/issues/9208
- [ ] Define plugin's metadata and it's storage https://github.com/eclipse/che/issues/9210
- [ ] Refresh frontend/backend plugin parts on plugin disabled state https://github.com/eclipse/che/issues/9211
- [ ] Plugin API definition and impelementation https://github.com/eclipse/che/issues/9215

**Comment by skabashnyuk** [comment]
Please note, to avoid problems with CORS, authentication and port range. It would be great to organize client plugins so they communicate server with a single port.
