### ISSUE TITLE
IDE-2018-04-17 (Sprint: 147)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#9204]
#### Theia improvement: 

- [ ] Ability to quickly find the preferences (from menu or command palette) #8981
- [ ] Show/hide hidden files in Theia #8977
- [ ] Theia Command Palette Improvement #8976

#### Artem 
- [ ] _[Theia]_ Support commands macro in Theia tasks #8974
- [ ] _[Theia]_ Ability to define/see preview URL #9273
- [ ] _[Theia]_ Theia Command Palette Improvement #8976

#### Dmytro 
- [ ] _[Theia]_ Navigation from Stack Trace from posted output to the files in opened workspace #9248
- [ ] Not possible to add new file extension to make it work with LS. "documentFilters" does not work #8925
- [x] "Created" Notifications for existing Files on Startup #9294

#### Roman 
- [ ] _[Theia]_ Theia Editor Key Bindings switching (Default, VI, Emacs) #9244
- [x] _[Theia]_ Client side OAuth Authorizations API for Theia #8739

#### Vitalii 
- [ ] _[Theia]_ Ability to quickly find the preferences (from menu or command palette) #8981
- [ ] Unexpected the hanging of the Loader after actions #8300
- [x] JAVA_HOME is null when running test via UI #9105 

#### Vlad
- [x]  _[Theia]_ Show/hide hidden files in Theia #8977
- [x] Unexpected failing of NavigateToFileTest selenium test on CI #8465
- [x] Project import is not tracked on multiple browsers #2428

#### Igor 
- [x] _[Theia]_ Ability to visualize the maven modules in Theia Project Explorer #8978 
- [x] _[Theia]_ Disable autosave in Theia #9245
- [x] Unexpected fail of CreateNewPackagesWithHelpCreationJavaClassTest selenium test #8122
- [x] Wrong author name when perform 'git revert commit' #9066

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 15 |  
| Vlad |15 |  
| Dmytro  | 15 |   
| Roman  |15 | 
| Vitalii  |15|    
| Igor |15 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 90/70   |  |
| **Velocity** | |  |
