### ISSUE TITLE
IDE2-2018-04-17 (Sprint: 147)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9220]
### Sprint Goals:
1. Plugin model implementation
2. Hosted mode with Theia in Che
3. Factories support in Theia IDE
4. Codebases and Workspaces UI finalizing

## 1. Extensibility model implementation
- [x] POC of server communication with the server plugin and browser https://github.com/eclipse/che/issues/9183 8 sp ( Yevhen)
- [ ] Define plugin's metadata and it's storage https://github.com/eclipse/che/issues/9210 20sp (Oleksii K)
- [x] Introduce Command Manager Plugin API https://github.com/eclipse/che/issues/9283 10sp (Yevhen)
- [x] Introduce Notification Manager Plugin API https://github.com/eclipse/che/issues/9284 25sp (Oleksii O)
- [ ] Introduce Menu Manager Plugin API https://github.com/eclipse/che/issues/9285 25sp 
- [x] Introduce Command palette Plugin API https://github.com/eclipse/che/issues/9286 35sp (Yevhen)

## 2. Hosted mode with Theia in Che
- [ ] Run separate instance of Theia server with plugin that is developing https://github.com/eclipse/che/issues/9212 50sp (Mykola) 
- [ ] Add UI to differ developer mode in Theia https://github.com/eclipse/che/issues/9214 20sp

## 3. Factories support in Theia IDE
- [ ] Import projects in theia IDE from a factory: implement git import in Theia node (server) as a rest service #9218 15sp (Sun)
- [ ] Import projects in theia IDE from a factory: read factory metadata from the client side #9221 25sp

## 4.  Codebases and Workspaces UI finalizing
- [ ] Add repositories layouts according to new designs https://github.com/openshiftio/openshift.io/issues/1434 25sp (Ann)
- [x] Refresh the branches source code 5sp

## Other  issues: 
- [x] Finish work on support for EditorConfig https://github.com/eclipse/che/issues/7588#issuecomment-376845049 25sp (Vitalyi)
- [ ] Finalize Theia terminal stuff by adding missing features https://github.com/eclipse/che/issues/9265 25sp (Oleksandr)
- [x] Ability to do websocket connection on che-workspace-client library https://github.com/eclipse/che/issues/8699#issuecomment-376877400 25sp (Oleksii K)
- [ ] GitHub oAuth does not work when invoked from User Dashboard https://github.com/eclipse/che/issues/9231 4sp
- [x] Remove the dev machine validation in UD https://github.com/eclipse/che/issues/9299 (Oleksii O)

**Total planned = 337sp**

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova | 5 |
| Mykola Morhun| 13 |
| Oleksandr Andriienko | 13 | 
| Oleksii Kurynniy | 13 |
| Oleksii Orel | 13 |
| Sun Tan | 10 |
| Vitaliy Guliy | 13 |
|Yevhen Vydolob| 12 |
| **Total Budget** | **92** |

**Total SP budget = 92*5=460**
### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 92 | - |
| **Velocity** | - | - |
| **Focus Factor** | - | - |
### Retrospective Comments
[Sprint Retrospective](https://docs.google.com/drawings/d/1sELnGiwNmsOlwPWRxGp4gM5Z0IDQXG7zPwLZmPYmBrU/edit)

**Comment by slemeur** [comment]
LGTM
