### ISSUE TITLE
Languages Sprint 147

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9224]
# Availability
@tsmaeder: 7d
@tolusha 7d
@svor 14d
@vrubezhny 9d
@JPinkney 13d

Topics: Finish up hurdles to merging to master, Get started with Theia development
Priority list:

- [ ] https://github.com/eclipse/che/issues/8929 Connect to Debug Target
  *  [x]  #8953 
  *  [x]  #8954  
  *  [ ] #8955 3d @tolusha 
  *  [ ] #8956 3d
  *  [ ] #8957 1d
* [ ] https://github.com/eclipse/che/issues/8939 Rename Refactoring @svor 
  * [ ] https://github.com/eclipse/che/issues/9112 Implement Custom Rename Refactoring Command 4d
  * [ ] https://github.com/eclipse/che/issues/9113 Port Rename Wizard to use WorkspaceEdit 4d
  * [ ] https://github.com/eclipse/che/issues/9114 Extend ApplyWorkspaceEditAction to Support File Level Changes  6d 
- [ ] https://github.com/eclipse/che/issues/8874 Run jdt.ls as a sidecar 5d @JPinkney 
- [ ] https://github.com/eclipse/che/issues/8940 (Theia) Create Che Java Contribution 3d @tsmader
- [ ] https://github.com/eclipse/che/issues/8941 (Theia) Address jdt.ls specifically 3d
- [ ] https://github.com/eclipse/che/issues/8335 Determine Che-in-Che Resource Requirements with jdt.ls 3d @tsmaeder
- [ ] https://github.com/eclipse/che/issues/8880 Update Che Doc for jdt.ls use 1d
- [ ] https://github.com/eclipse/che/issues/8721 Update Libraries, etc. based on JDT notifications 7d @vrubezhny 

Previous sprint: https://github.com/eclipse/che/issues/8708

**Comment by slemeur** [comment]
The sprint plan is looking good, but it feels there are a lot of tasks that are "big" and which would probably need to be split into smaller chunks once we get start on them.
