### ISSUE TITLE
Authentication and security in Theia IDE

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#9383]
### Description
Communications between Theia integrated within Che and Che Server as well as workspace's containers should be secured.

### Sub-tasks
- [x] Study :Authentication with jwtproxy https://github.com/eclipse/che/issues/9843
- [x] Cover ws-agent/exec-agent/terminal with JWT proxy | https://github.com/eclipse/che/issues/10081
- [x] Create CQ for jwtproxy | https://github.com/eclipse/che/issues/10078
- [x] Make a unique nonce as optional check in jwtproxy | https://github.com/eclipse/che/issues/10090
- [x] Make it possible for Go agents to accept authentication tokens from header | https://github.com/eclipse/che/issues/10101
- [x] Make aud claim optional StringOrURI in JWTProxy https://github.com/eclipse/che/issues/10308
- [x] Create exclude rules for jwtproxy https://github.com/eclipse/che/issues/10312
- [x] Authentication cookie set up mechanism https://github.com/eclipse/che/issues/10349
- [x] Add an ability to configure public accessible paths for Che secure servers https://github.com/eclipse/che/issues/10400
- [x] A lot of failing Selelnium tests with jwtproxy auth enabled https://github.com/eclipse/che/issues/10490
- [x] JwtProxy: initial authentification redirect https://github.com/eclipse/che/issues/10493
- [x] JwtProxy: authenticate method https://github.com/eclipse/che/issues/10494
- [x] Generic authentication/authorization components https://github.com/theia-ide/theia/issues/2126
- [x] Make loader page URL configurable within property  https://github.com/eclipse/che/issues/10611
- [x] Rework JwtProxyConfigBuilder to use Objects instead of formatting string config template https://github.com/eclipse/che/issues/10402
- [x] Add an ability to configure a jwtproxy image  https://github.com/eclipse/che/issues/9383
- [x] Make public/private signing keys pair per-workspace and synch with workspace runtime (renew pair on each workspace restart)  https://github.com/eclipse/che/issues/10074
- [x] Add an ability to configure if a secure server should supports authentication with a cookie or not https://github.com/eclipse/che/issues/10725
- [x] Add an ability to configure a jwtproxy image https://github.com/eclipse/che/issues/10733
- [x] Document "Authentication and security in Theia IDE" feature https://github.com/eclipse/che/issues/10762

**Comment by skabashnyuk** [comment]
I see such points here.
- we should have some sort of request factory that can add tokens to request headers
- we should add a component to get token in case if a header is not an option (example initial OAuth request) 
- we should protect our infrastructure with some software that checks tokens. I would like to try https://github.com/coreos/jwtproxy in this role.

**Comment by garagatyi** [comment]
Note that we also need a guide for plugins/features/LSs developers.

**Comment by slemeur** [comment]
Thanks @skabashnyuk and @garagatyi ! Adding to the issue description.

**Comment by skabashnyuk** [comment]
This epic complete for OS/K8s infrastructure.
Docker infrastructure would be covered under this issue https://github.com/eclipse/che/issues/10242
