### ISSUE TITLE
Languages Sprint 148

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9404]
# Availability
@tsmaeder: 6d
@tolusha 14d
@svor 13d
@vrubezhny 13d
@JPinkney 13d
@fbricon 10d
(@snjeza 13d)

72d * 0.7= 51d

Topics: Finish up hurdles to merging to master, Get started with Theia development
Priority list:

- [x] https://github.com/eclipse/che/issues/8929 Connect to Debug Target
  *  [x]  #8953 
  *  [x]  #8954  
  *  [x] #8955 3d @tolusha 
  *  [x] #8956 5d
  *  [x] #8957 2d
* [ ] https://github.com/eclipse/che/issues/8939 Rename Refactoring @svor 
  * [ ] https://github.com/eclipse/che/issues/9112 Implement Custom Rename Refactoring Command 3d
  * [ ] https://github.com/eclipse/che/issues/9113 Port Rename Wizard to use WorkspaceEdit 4d
  * [ ] https://github.com/eclipse/che/issues/9114 Extend ApplyWorkspaceEditAction to Support File Level Changes 5d
- [ ] https://github.com/eclipse/che/issues/8874 Run jdt.ls as a sidecar 8d @JPinkney 
- [ ] https://github.com/eclipse/che/issues/8940 (Theia) Create Che Java Contribution 5d  @tsmaeder
- [ ] https://github.com/eclipse/che/issues/8880 Update Che Doc for jdt.ls use 1d
- [ ] https://github.com/eclipse/che/issues/8721 Update Libraries, etc. based on JDT notifications 7d @vrubezhny 
- [ ] https://github.com/eclipse/eclipse.jdt.ls/issues/569 On Type Formatting 3d @fbricon
- [x] https://github.com/eclipse/eclipse.jdt.ls/issues/623 Support formatter options 8d

54d 

Estimated, but not planned: 
* [x] https://github.com/eclipse/che/issues/8964 LS per project issue 5d
* [ ] https://github.com/eclipse/che/issues/9423 Display Stack Frames 5d 
* [ ] https://github.com/eclipse/che/issues/9424 Suspend/Resume Action 3d
* [ ] https://github.com/eclipse/che/issues/9421 Show Threads 5d
* [ ] https://github.com/eclipse/che/issues/8941 (Theia) Address jdt.ls specifically 3d

Previous sprint: https://github.com/eclipse/che/issues/9224
