### ISSUE TITLE
Phase 1 of Workspace.Next implementation

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9406]
### Description
As announced here https://github.com/eclipse/che/issues/8265#issuecomment-377217641
Goals of Phase 1 will be
 - [x]  We will store features list in workspace 6 attributes
 - [x]  We will teach Kubernetes/Openshift infrastructures to adjust workspace runtime with containers that are come from features. https://github.com/redhat-developer/rh-che/issues/610
- [x] Workspace.Next/Phase 1 - CheService/CheFeature model https://github.com/eclipse/che/issues/9292
- [x] Here #9292 we are going to discuss object details
- [x] Initial feature and service list https://github.com/eclipse/che/issues/9408
- [x] Not able to run eclipse/che-theia-* plugins in Che Theia stack https://github.com/eclipse/che/issues/9481
- [x] Implement GET methods for features and services https://github.com/eclipse/che/issues/9491
- [x] Create CQ for golang dependencies for a server that provides features and services https://github.com/eclipse/che/issues/9844

**Comment by garagatyi** [comment]
We figured out that we had different understandings of how Che tooling containers should run in Workspace.Next.
I tried to put all the tooling containers into a single pod since these containers might need to mount the same volume to access files.
The Mario added that we should add tooling containers into the POD from the user's recipe since a user might need sources of the application run in that pod while they are edited in tooling containers. 
On the other hand what if a user has 2 pods, in which pod we should add tooling containers? 
Should we enforce the user to use a single pod? Or maybe we can allow a user to use several pods but ask him to choose a pod in which we will run tooling containers. 
BTW we should not use just pod notion here because Che might run workspaces on the Docker infrastructure. 

@gorkem @l0rd @skabashnyuk WDYT?

**Comment by skabashnyuk** [comment]
@garagatyi I think in Phase 1 we should go in the easiest direction we can. If it's a requirement to have only 1 pod then let's go in this way.

**Comment by garagatyi** [comment]
We might want to include next issues to this epic:
https://github.com/eclipse/che/issues/9870
https://github.com/eclipse/che/issues/9871

@slemeur WDYT?

**Comment by slemeur** [comment]
Yes you are right @garagatyi, the issues you created should be considered in this epic.

**Comment by garagatyi** [comment]
> Create CQ for golang dependencies for a server that provides features and services

I believe that we don't have to put this server under Eclipse foundation for the time, so this might not be mandatory for this phase.
