### ISSUE TITLE
Introduce Editor Plugin API

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9409]
The new plugin model should contain API for accessing Editor from Theia core. The task includes following items to be done:
- [x] define the API of the Editor operations
- [x] document the API
- [x] develop the defined API
- [x] test it on the sample plugin

The editor API definition could be divided into following parts: 
- [x] Provide API for Editor window events https://github.com/eclipse/che/issues/9433
- [x] Editor API should contain the definition of the main Editor Objects https://github.com/eclipse/che/issues/9434
- [x] Implement the main methods of the Editor https://github.com/eclipse/che/issues/9435
