### ISSUE TITLE
IDE2-2018-05-08 (Sprint: 148)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9410]
### Sprint Goals:
1. Plugin model implementation
2. Hosted mode with Theia in Che
3. Factories support in Theia IDE

## 1. Extensibility model implementation
- [x] Define plugin's metadata and it's storage https://github.com/eclipse/che/issues/9210 20sp (Oleksii K)
- [x] Implement launching plugins from defined place https://github.com/eclipse/che/issues/9476 55sp
- [ ] Provide API for Editor events https://github.com/eclipse/che/issues/9433 25sp
- [ ] Main editor objects and it's methods definition https://github.com/eclipse/che/issues/9434 80sp (cannot be split - only part will be done by the end of sprint)
- [ ] Introduce the Status bar API https://github.com/eclipse/che/issues/9494 40sp 

## 2. Hosted mode with Theia in Che
- [x] Add UI to differ developer mode in Theia https://github.com/eclipse/che/issues/9214 25sp
- [x] Add info about Dev mode instance to the main Theia one  https://github.com/eclipse/che/issues/9402 40sp

## 3. Factories support in Theia IDE
- [ ] Import projects in theia IDE from a factory: implement git import in Theia node (server) as a rest service #9218 15sp (Sun)
- [ ] Import projects in theia IDE from a factory: read factory metadata from the client side #9221 25sp

## Other  issues: 
- [x] Finalize Theia terminal stuff by adding missing features https://github.com/eclipse/che/issues/9265 (Oleksandr)
- [x] GitHub oAuth does not work when invoked from User Dashboard https://github.com/eclipse/che/issues/9231 4sp (Ann)
- [ ] Diagnostics broken https://github.com/eclipse/che/issues/9234
- [x] Sometimes a black screen appears in project details after workspaces starting https://github.com/eclipse/che/issues/8931
- [ ] Workspace is not started automatically from Dashboard after clicking "Open in IDE" button https://github.com/eclipse/che/issues/9381

**Total planned = [todo]sp**

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun| 13 |
| Oleksandr Andriienko | 11 | 
| Oleksii Kurynniy | 8 |
| Oleksii Orel | 13 |
| Sun Tan | 10 |
| Vitaliy Guliy | 13 |
|Yevhen Vydolob |  13 |
| **Total Budget** | **** |

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | - | - |
| **Velocity** | - | - |
| **Focus Factor** | - | - |
### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1uzI2faocbKmAdFny1fQw_qFaoIVOhyIvu2gyGYLH1z4/edit)
