### ISSUE TITLE
Platform-2018-05-08 (Sprint: 148)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9412]
### Features related to Hot update for wsmaster

- [x] Adapt ServiceTermination functionality to workspaces recovering    https://github.com/eclipse/che/issues/9317 5sp
- [x] Workspace Start/Stop failed while tomcat shutdown    https://github.com/eclipse/che/issues/9452 8sp
- [x] Server checkers works incorrectly when s8k/os workspaces are recovered | https://github.com/eclipse/che/issues/9453 8sp
- [x] Hot update testing on working master | https://github.com/eclipse/che/issues/9415 13sp
- [x] Document procedure of hot update | https://github.com/eclipse/che/issues/9414 8sp
- [ ] Implement interruption of start for OpenShift workspaces | https://github.com/eclipse/che/issues/5918 13sp
- [x] Remove the code which deletes CHE_DATA/lib in entrypoint.sh | https://github.com/eclipse/che/issues/9276 3sp

### Features related to Workspace.Next Phase 1

- [x] Workspace.Next/Phase 1 - CheService/CheFeature model | https://github.com/eclipse/che/issues/9292 8sp
- [x] Initial feature and service list | https://github.com/eclipse/che/issues/9408 5sp
- [x] Implement GET methods for features and services  https://github.com/eclipse/che/issues/9491

### Technical debts and bugs

- [x]  Add external che api url as workspace environment variables. | https://github.com/eclipse/che/issues/9323 13sp

### Unplanned
 - [x] Recreate Hot Update  https://github.com/eclipse/che/issues/9528
- [x] Error of removal of workspace created from factory in Eclipse Che on Docker infrastructure https://github.com/eclipse/che/issues/9599
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 13d |
| Max Shaposhnik | 13d | 
| Michail Kuznyetsov | 13d | 
| Sergii Leshchenko | 13d | 
| Anton Korneta| 8d |
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 84 | 71 |

**Comment by skabashnyuk** [comment]
## Removed 
 - Unable to override idle timeout for a particular user https://github.com/eclipse/che/issues/8951
