### ISSUE TITLE
Main editor objects and it's methods definition

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9434]
Such important objects of the Editor API should be covered along with their methods: 
- [x] TextEditor -  an editor that is attached to a text document
- [x] TextDocument - a source file, that has lines and knowledge about an underlying resource like a file
- [x] TextLine - a line of source code
- [x] Range - an ordered pair of two positions - start and end
- [x] Position - a line and character position, such as the position of the cursor
- [x] Selection - text selection in an editor

Subtasks:
- [ ] Define the editor api workflow needed to implement teletype plugin #9679
- [ ] Implement Editor API needed for a teletype plugin #9680
- [ ] Implement a simple teletype plugin that would use the editor api #9681
