### ISSUE TITLE
QE-2018-05-08 (Sprint: 148) 

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#9438]
### Sprint goals
- Rid of manual tests by creating Selenium tests covering these usecases.
- Adopt Selenium test suit for testing RH-CHE on OSIO

### Issues tied to objectives
- [x] Create Test Plan for testing "Dashboard" functionality https://github.com/eclipse/che/issues/9447 8sp
- [x] Rework the 'RunPlainJavaProjectTest' by use the 'kohsuke Github' library https://github.com/eclipse/che/issues/9458 1sp
- [x] Rework the 'GitCompareTest' by use the 'kohsuke Github' library https://github.com/eclipse/che/issues/9459 2sp
- [ ] Create the list of features which are not covered by functional tests https://github.com/eclipse/che/issues/8434 5sp
- [x] Create selenium test for covering git reset features https://github.com/eclipse/che/issues/9353 3sp
- [x] Adapt Eclipse Che selenium tests from dashboard package to execute on OSIO https://github.com/eclipse/che/issues/9455 2sp
- [x] Rework organization-related tests to be executed in multi-thread mode https://github.com/eclipse/che/issues/9019 2sp

### Unplanned 
- [x] Change the methods in the 'GitCompare' using the classes 'SeleniumWebDriverHelper' and 'WebDriverWaitFactory' https://github.com/eclipse/che/issues/9516 2sp
- [x] Cover the Stacks list by selenium test https://github.com/eclipse/che/issues/9517 2sp
- [x] Eclipse Che selenium tests doesn't stop execution in local mode when version of browser doesn't comply version of webdriver https://github.com/eclipse/che/issues/9507 1sp
- [ ] Create test for checking Download projects/folders feature https://github.com/eclipse/che/issues/9538 5sp
- [x] Create test plan for checking Language servers https://github.com/eclipse/che/issues/9540 3sp
- [x] Rework factory-related tests to be executed in multi-thread mode https://github.com/eclipse/che/issues/9020 2sp
- [x] Unexpected PreDestroy event triggered in selenium test when '@Test(dependsOnMethods)' attribute is used https://github.com/eclipse/che/issues/9584 2sp
- [ ] Add Eclipse Che build info into the selenium tests log https://github.com/eclipse/che/issues/9607 2sp
- [x] Unexpected fail of selenium tests from 'refactor.types' package https://github.com/eclipse/che/issues/9623 2sp
- [ ] Review the known issues of the Che https://github.com/eclipse/che/issues/9643 2sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 13 |
| Maxim Musienko | 13 |
| Dmytro Nochevnov | 13 |
| Igor Ohrimenko | 13 |
| Sergey Skorik | 13 |
| Total | 65 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 23 | 20 |

### Retrospective Comments
- [ ] Create the list of features which are not covered by functional tests https://github.com/eclipse/che/issues/8434 moved in next sprint
