### ISSUE TITLE
Languages Sprint 149

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9589]
# Availability
@tsmaeder: 6d
@tolusha 13d
@svor 13d
@vrubezhny 13d
@JPinkney 14d
@fbricon 13d
(@snjeza )

72 * 0.7= 50d

#8939 Rename Refactoring @svor 2d

Topics: Finish up hurdles to merging to master, Get started with Theia development

* [ ] https://github.com/eclipse/che/issues/9526 Simple Java project is not recognized 3d (@vrubezhny)
* [x] #8880 Update Che Doc for jdt.ls use 1d
* [ ] https://github.com/eclipse/che/issues/8666 Cleanup unused Java support Part 2 2d
* [ ] https://github.com/eclipse/che/issues/6748 Implement Move Refactoring 15d @svor 
* [ ] https://github.com/eclipse/che/issues/9591 Address Selenium Test Merge Blockers 5d (@tsmaeder)
* [x] https://github.com/eclipse/che/issues/9423 Display Stack Frames 5d 
* [ ] https://github.com/eclipse/che/issues/9424 Suspend/Resume Action 3d (@JPinkney)
* [x] https://github.com/eclipse/che/issues/9421 Show Threads 5d (@tolusha)
* [ ] https://github.com/eclipse/che/issues/8941 (Theia) Address jdt.ls specifically 3d
* [x] https://github.com/eclipse/eclipse.jdt.ls/issues/569 Implement `textDocument/onTypeFormatting` support (2d) (@fbricon)
* [x] https://github.com/eclipse/eclipse.jdt.ls/issues/649 Only return jdt:// urls if clients support it (2d)
* [x] https://github.com/eclipse/eclipse.jdt.ls/issues/653 Update lsp4j to 0.4.0 (3d)
* [x] https://github.com/eclipse/eclipse.jdt.ls/issues/654 Autocompletion should return javadoc in Markdown (3d)
* [x] https://github.com/eclipse/eclipse.jdt.ls/issues/128 Enable Annotation Processing (1d)
* [ ] https://github.com/eclipse/eclipse.jdt.ls/issues/446 Add quickfix for accessing non visible references (1d)

Previous sprint: https://github.com/eclipse/che/issues/9404

**Comment by fbricon** [comment]
Fred 13d
