### ISSUE TITLE
Platform-2018-05-29 (Sprint: 149)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9606]
### Features related to Hot update for wsmaster
- [x] Hot update testing on working master https://github.com/eclipse/che/issues/9657 8sp
- [x] [hot_update] Find way to avoid errors in the moment when Che server pending HTTP requests during update  https://github.com/eclipse/che/issues/9624 5sp
- [x] Servers checkers won't be started if a workspace is started by another Che Server instance https://github.com/eclipse/che/issues/9502 8sp
- [x] Document procedure of Rolling Hot Update https://github.com/eclipse/che/issues/9630 8sp

### Technical debts and bugs

- [x] Default profile of an integration-tests module should not depend on tests artifacts | https://github.com/eclipse/che/issues/9462  5sp
- [x] Allow switching between KeycloakOAuthAuthenticationService and OAuthAuthenticationService in multi-user Che | https://github.com/eclipse/che/issues/9461  8sp
- [x] Rework ws-agent activity notification mechanism | https://github.com/eclipse/che/issues/9126  5sp

### Unplanned
- [x] OpenShift/K8S: Log installer errors in wsmaster log https://github.com/eclipse/che/issues/9641
- [x] Temporary workspaces are removed after rolling update https://github.com/eclipse/che/issues/9663 
- [x] Remove current analytics mecanism https://github.com/eclipse/che/issues/9792
- [x] Provide machine name as a machine's environment variable https://github.com/eclipse/che/issues/96537
- [ ] Implement interruption of start for OpenShift workspaces https://github.com/eclipse/che/issues/5918
- [ ] Servers that don't have servers checks or liveness probes don't contain status field if Che runs docker infrastructure https://github.com/eclipse/che/issues/9094
- [ ] Track OpenShift pods failures on the start of a workspace https://github.com/eclipse/che/issues/7926
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 4d |
| Max Shaposhnik | 9d | 
| Michail Kuznyetsov | 14 d | 
| Sergii Leshchenko | 14 d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 47 | 47 |
