### ISSUE TITLE
QE-2018-05-29 (Sprint: 149)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#9626]
### Issues tied to objectives
- [x] Add the 'try/catch' block to the 'PullRequestPluginTest' acording to the known issue  https://github.com/eclipse/che/issues/9639 1sp
- [x] Replace the known issue in the 'try/catch' block in the TestWorkspaceImpl https://github.com/eclipse/che/issues/9647 1sp
- [x] Rework the 'ImportWizardFormTest' to use the 'kohsuke Github' library https://github.com/eclipse/che/issues/9654 2sp
- [x] Create the list of features which are not covered by functional tests https://github.com/eclipse/che/issues/8434 5sp
- [x] Create test for checking Download projects/folders feature https://github.com/eclipse/che/issues/9538 5sp
- [ ] Add Eclipse Che build info into the selenium tests log https://github.com/eclipse/che/issues/9607 2sp
- [x] Review the known issues of the Che https://github.com/eclipse/che/issues/9643 2sp

### Unplanned 
- [x] Replace the 'mockito.jar' library from the 'run-plain-java-project' in the resources https://github.com/eclipse/che/issues/9633 2sp
- [x] Cover Python LS functionality by selenium test https://github.com/eclipse/che/issues/9682 2sp
- [x] Rework the 'ImportProjectFromGitHubTest' to use the 'kohsuke Github' library https://github.com/eclipse/che/issues/9755 1sp
- [x] Rework the 'ImportMavenProjectFromGitTest' to use the 'kohsuke Github' library https://github.com/eclipse/che/issues/9756 1sp
- [x] Rework the 'ImportProjectFromZipTest' to use the 'kohsuke Github' library https://github.com/eclipse/che/issues/9766 2sp
- [x] Create selenium test for covering PHP language server https://github.com/eclipse/che/issues/9760 3sp
- [x] Rework "NewWorkspace" selenium page object by "SeleniumWebDriverHelper" class https://github.com/eclipse/che/issues/9801 1sp
- [ ] Revise and update 'Dashboard' selenium tests in the 'Factory' section https://github.com/eclipse/che/issues/9785 5sp
- [x] Cover Clangd LS functionality by selenium test https://github.com/eclipse/che/issues/9811 2sp

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 13 |
| Maxim Musienko | 13 |
| Dmytro Nochevnov | 13 |
| Igor Ohrimenko | 13 |
| Sergey Skorik | 13 |
| Total | 65 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 18 | 16 |

### Retrospective Comments
- [ ] Add Eclipse Che build info into the selenium tests log https://github.com/eclipse/che/issues/9607 moved to next sprint
