### ISSUE TITLE
IDE-2018-05-29 (Sprint: 149)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#9628]
#### Theia improvement: 

- [ ] Preferences System for Che with Theia IDE #9336 
- [ ] Che Plugin Marketplace - Phase 1 #8282
- [ ] Support commands macro in Theia tasks #8974

#### Artem 
- [ ] _[Theia]_ Support commands macro in Theia tasks #8974

#### Dmytro 
- [x] Newer Go and C# language servers do not work with Che LSP client #9351
- [ ] _[Theia]_ Navigation from Stack Trace from posted output to the files in opened workspace #9248

#### Roman 
- [ ] _[Theia]_ Theia Editor Key Bindings switching (Default, VI, Emacs) #9244 
- [ ] In case ws-agent stopped unexpectedly all editors should become in readonly mode or close them #9620
- [x] Pull Request panel does not open when select to the project #9484
- [ ] After refresh browser the split editor tab is in the different state than before #9456

#### Vitalii 
- [ ] Che IDE locks up #9477
- [x] IDE memory consumption grows and the tab becomes crashed #7151
- [ ] Che Plugin Marketplace - Phase 1 #8282
- [x] There are possible places of failure due to not closing InputStreams #6841

#### Vlad
- [ ] Sometimes Selenium cannot open workspace page after invocation of the straight URL and login. #8468
- [x] Unexpected failing of NavigateToFileTest selenium test on CI #8465
- [ ] Files created in terminal don't appear in the project explorer #9026
- [x] Scroll button click on file tab closes tab and puts buffer content into the following active tab editor #6840 

#### Igor 
- [ ] _[Theia]_ Ability to quickly find the preferences (from menu or command palette) #8981 (see also : (theia-ide/theia#1433 and theia-ide/theia#1434)
- [x] Update Project Configuration should be available regardless of what project level is selected #6109

### Merge-ready PRs
- [x] [WIP] Several improvements to the way remote language servers may be configured through workspace configuration #9387 

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 15 |  
| Vlad |15 |  
| Dmytro  | 15 |   
| Roman  |15 | 
| Vitalii  |15|    
| Igor |15 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 90/70   |  |
| **Velocity** | |  |

**Comment by slemeur** [comment]
The sprint looks like it's the same as the previous one. @vparfonov Are you updating it?

**Comment by vparfonov** [comment]
Yes, in progrees
