### ISSUE TITLE
IDE2-2018-05-29 (Sprint: 149)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9631]
### Sprint Goals:
1. Plugin model implementation
2. Hosted mode with Theia in Che
3. Factories support in Theia IDE

## 1. Extensibility model implementation
- [x] Provide API for Editor events https://github.com/eclipse/che/issues/9433 20sp
- [ ] Define the editor api workflow needed to implement teletype plugin https://github.com/eclipse/che/issues/9679
- [x] Introduce the Status bar API https://github.com/eclipse/che/issues/9494 20sp
- [x] Introduce the plugin API for terminal https://github.com/eclipse/che/issues/9595 40sp
- [x] Introduce the Window state API https://github.com/eclipse/che/issues/9596 50sp
- [ ] Introduce the Preferences API https://github.com/eclipse/che/issues/9597 40sp

## 2. Hosted mode with Theia in Che
- [ ] Run separate instance of Theia server on OCP https://github.com/eclipse/che/issues/9676 25sp

## 3. Factories support in Theia IDE
- [x] Import projects in theia IDE from a factory: read factory metadata from the client side #9221 20sp

## Other  issues: 
- [ ] Update xterm.js to the newer version. https://github.com/eclipse/che-lib/issues/57
- [ ] Impossible to copy/paste into Terminal https://github.com/eclipse/che/issues/9398 - X
- [x] Diagnostics broken https://github.com/eclipse/che/issues/9234 10sp
- [ ] Workspace is not started automatically from Dashboard after clicking "Open in IDE" button https://github.com/eclipse/che/issues/9381 10-20sp
- [x] Several "dev-machine" are created after several changes the name in the "Edit the machine" form https://github.com/eclipse/che/issues/9537 
- [x] It is possible to create a workspace with project which has no name, or it has a special characters in the name https://github.com/eclipse/che/issues/9518
- [x] Use the fixed version of Theia in eclipse/che-theia image 

## Unplanned  issues: 
- [x] Use the fixed version of Theia in eclipse/che-theia image https://github.com/eclipse/che/issues/9716 

**Total planned = [todo]sp**

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun| 12 |
| Oleksandr Andriienko | 12 | 
| Oleksii Kurynniy | 10 |
| Oleksii Orel | 12 |
| Sun Tan | 8 |
| Vitaliy Guliy | 2 |
| Yevhen Vydolob |  12 |
| **Total Budget** | **** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/121N4yz-VzsBkk2edor71Hfe9JUbhJTaSrOMQn0B7it8/edit?usp=sharing)
