### ISSUE TITLE
Languages Sprint 150

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9804]
# Availability
@tsmaeder: 6d
@tolusha 15d
@svor 13d
@vrubezhny 15d
@JPinkney 15d
@fbricon 6d
@snjeza 13d

72 * 0.6= 54d
- [x] #9526 Simple Java project is not recognized 5d (@vrubezhny)
- [ ] #8666 Cleanup unused Java support Part 2 2d (@JPinkney )
- [x] #6748 Implement Move Refactoring 4d @svor
- [x] #9424 Suspend/Resume Action 1d (@JPinkney )
- [x] #8941 (Theia) Address jdt.ls specifically 3d 
- [x] eclipse/eclipse.jdt.ls#446 Add quickfix for accessing non visible references (0.5d)
- [ ] #8940 (Theia) Create Che Java Contribution 3d @tsmaeder

15.5 d => 38.5

- [x] https://github.com/eclipse/eclipse.jdt.ls/i[]ssues/669 No completion doc for methods with params
- [x] #9807 Rebase 5730_java_ls_poc on master 1.5d (@tsmaeder)
- [ ] #8965 Theia: Implement Java "libraries" feature (8d) (@JPinkney)
- [x] #8941 Theia: Addressing a particular LS (aka jdt.ls) to use specific protocol extensions. (3d)
- [ ] #9591 Address Selenium Test Merge Blockers (timeboxed: 17.5d)
  - [x] #10034 Fix Rename Selenium Failures (@svor)
  - [ ] #10052 Selenium: Source Folder Paths have wrong base (@tsmaeder)
- [x] #9819 Display stack frame variables 5d (@tolusha )
- [x] #9820 Modify stack frame variables 3d

In case we finisht early, I'd like to start on these:
- [ ] #9972 Open Editor on Library Class Files in Theia (@svor)
- [ ] #9970 Support jdt.ls Status Reports 

Open PR's
- [x] https://github.com/eclipse/che/pull/9670 Fix for YAML language server not displaying hover
- [x] https://github.com/eclipse/che/pull/9650 Update Libraries, etc. based on JDT notifications 
- [x] https://github.com/eclipse/che/pull/9636 Support Rename refactoring kind/enhancement
- [ ] https://github.com/eclipse/che/pull/9616 Custom socket provider and java language server in sidecar

Previous sprint: https://github.com/eclipse/che/issues/9589

**Comment by tolusha** [comment]
@bazko 15d

**Comment by svor** [comment]
@svor 13d
