### ISSUE TITLE
QE-2018-06-19 (Sprint: 150)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#9822]
### Sprint goals
- Create new Selenium tests according to test plan.

### Issues tied to objectives
- [x] Cover workspace creating from organization details page by selenium test https://github.com/eclipse/che/issues/9821 2sp
- [x] Create test for covering usecase described in the issue 8674 https://github.com/eclipse/che/issues/9770 3sp
- [ ] Add Eclipse Che build info into the selenium tests log https://github.com/eclipse/che/issues/9607 3sp
- [ ] Revise and update 'Dashboard' selenium tests in the 'Factory' section https://github.com/eclipse/che/issues/9785 5sp
- [ ] Fix E2E tests to verify creation of OpenShift objects under the current user account on OCP https://github.com/eclipse/che/issues/9818 5sp
- [ ] Create E2E test for checking Hot update feature for wsmaster https://github.com/eclipse/che/issues/9646 5sp
- [ ] Update the 'CreateFactoryTest' according to the test plan https://github.com/eclipse/che/issues/9841 3sp
- [x] Create selenium test to cover the 'Contribute' in the 'Preferences' https://github.com/eclipse/che/issues/9852 2sp
- [x] Revise and update 'Dashboard' selenium tests in the 'Factory' section https://github.com/eclipse/che/issues/9785 5sp
Unexpected fails of "CreateWorkspaceTest", "AddWorkspaceToOrganizationTest", "ShareWorkspaceTest" selenium tests https://github.com/eclipse/che/issues/9860 1sp

### Unplanned 
- [x] Delete the 'try/catch' block from the 'PullRequestPluginTest' according to close the issue #9484 https://github.com/eclipse/che/issues/9889 1sp
- [x] Delete the 'try/catch' block from the 'TestWorkspaceImpl' according to close the issue #9556 https://github.com/eclipse/che/issues/9890 1sp
- [x] Create selenium test for covering TypeScript language server https://github.com/eclipse/che/issues/9918 3sp
- [ ] Adapt C# language server test according new configuration https://github.com/eclipse/che/issues/9925 2sp
- [x] Rewrite the methods in the 'PullRequestPanel' using the 'SeleniumWebDriverHelper' https://github.com/eclipse/che/issues/9957 1sp
- [ ] Rewrite the methods in the 'Preferences' using the 'SeleniumWebDriverHelper https://github.com/eclipse/che/issues/9967 1sp
- [x] Create test user in Eclipse Che on OCP which is run remotely https://github.com/eclipse/che/issues/9878 3sp
- [x] Revise and update "Dashboard" selenium tests in "Workspaces" section https://github.com/eclipse/che/issues/9652 8sp
- [ ] Add a selenium test case to create the Pull Request from non-default branch https://github.com/eclipse/che/issues/10000 2sp
- [x] Add the 'try/catch' block to the 'ImportWizardFormTest' according to the known issue (#10012) https://github.com/eclipse/che/issues/10013 1sp
- [x] Add the 'try/catch' block to the 'ContributeTabTest' according to the known issue(#10019)  https://github.com/eclipse/che/issues/10020 1sp
- [x] Selenium: add option not to start test workspaces after creation https://github.com/eclipse/che/issues/10008 1sp
- [x] Unexpected fail of selenium tests from 'dashboard' package  https://github.com/eclipse/che/issues/10011 2sp
- [x] Correct the 'AfterMethod' in the 'ContibuteTabTest' https://github.com/eclipse/che/issues/10067 1sp

### PR under review 
- [ ] https://github.com/eclipse/che/pull/8906
- [x] https://github.com/eclipse/che/pull/9803
- [x] https://github.com/eclipse/che/pull/9793
- [x] https://github.com/eclipse/che/pull/9931
- [x] https://github.com/eclipse/che/pull/9912
- [x] https://github.com/eclipse/che/pull/9793
- [x] https://github.com/eclipse/che/pull/9816
- [x] https://github.com/eclipse/che/pull/9985
- [x] https://github.com/eclipse/che/pull/9960
- [x] https://github.com/eclipse/che/pull/10005

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 14 |
| Maxim Musienko | 14 |
| Dmytro Nochevnov | 14 |
| Igor Ohrimenko | 14 |
| Sergey Skorik | 8 |
| Total | 64 | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 34 | 8 |
