### ISSUE TITLE
IDE2-2018-06-19 (Sprint: 150)

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9835]
### Sprint Goals:
1. Plugin model implementation
2. Hosted mode with Theia in Che
3. Factories support in Theia IDE

## 1. Extensibility model implementation
- [x] Introduce the Preferences API https://github.com/eclipse/che/issues/9597 40sp
- [x] Main editor objects and it's methods definition https://github.com/eclipse/che/issues/9434 50sp
- [x] Add Close the document to Editor API https://github.com/eclipse/che/issues/9906 10sp
- [x] Add Save the document to Editor API https://github.com/eclipse/che/issues/9907 10sp
- [x] Introduce Output channel API https://github.com/eclipse/che/issues/9836 40sp
- [x] Introduce Plugin API for workspace folders https://github.com/eclipse/che/issues/9839 40sp
- [x] Introduce new namespace for current environment in Plugins API https://github.com/eclipse/che/issues/9845 40sp

## 2. Hosted mode with Theia in Che
- [ ] Create new stack for the new plugins model flow https://github.com/eclipse/che/issues/9710 (Florent on it)

## 3. Factories support in Theia IDE
- [x] Factory with Theia: implement branch checkout while cloning a project defined in the factory definition https://github.com/eclipse/che/issues/9837 15sp
- [ ] Git clone is randomly failling https://github.com/eclipse/che/issues/9838 20sp
- [ ] Do investigation on: run commands https://github.com/eclipse/che/issues/9840 20sp

## Other  issues: 
- [ ] Update xterm.js to the newer version. https://github.com/eclipse/che-lib/issues/57 20sp awaiting QA: [Fix selenium test for newer terminal](https://github.com/eclipse/che/issues/9909)
- [x] Multi User Che: Can't use identiy provider delegation for login because the che theme doesn't support it https://github.com/eclipse/che/issues/7371 40sp
- [x] Hosted plugin manager for wiptheia doesn't start a plugin instance https://github.com/eclipse/che/issues/9644 5sp
- [x] Failing of a build of Theia in Theia image produces an invalid image https://github.com/eclipse/che/issues/9649 10sp
- [ ] Load Theia in Workspace.Next workspaces https://github.com/eclipse/che/issues/9870

**Total planned = [todo]sp**

### Pending PRs
- [x] https://github.com/theia-demo-plugins/theia-backend-plugin/pull/4
- [x] https://github.com/theia-demo-plugins/theia-frontend-plugin/pull/5
- [x] https://github.com/eclipse/che-theia-hosted-plugin-manager-extension/pull/1
- [ ] https://github.com/eclipse/che-theia-terminal-plugin/pull/1 - X [Moby CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187tps://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16187)
- [x] https://github.com/eclipse/che-theia-machines-plugin/pull/2
- [x] https://github.com/theia-demo-plugins/wiptheia/pull/13
- [x] https://github.com/theia-ide/theia/pull/1840

### Team availability

| Name | Days |
| :-- | --: |
| Ann Shumilova |  |
| Mykola Morhun|  |
| Oleksandr Andriienko |  | 
| Oleksii Kurynniy |  |
| Oleksii Orel |  |
| Sun Tan |  |
| Vitaliy Guliy |  |
| Yevhen Vydolob |   |
| **Total Budget** | **** |

### Retrospective Comments
[Retrospective document](https://docs.google.com/drawings/d/1alI742hQtr1FfjND-8_1iVLrzkzmf5hioFiC1SIpFAY/edit?usp=sharing)

**Comment by gorkem** [comment]
Do we have a complete list of APIs that we are planning to implement?

**Comment by ashumilova** [comment]
@gorkem yes, the list is [here](https://docs.google.com/spreadsheets/d/15UvXvhesbvn_D0K7YUweN45uayKpFIXqhL_ip0Q5Dkk/edit#gid=0)
