### ISSUE TITLE
Factory in Theia: process IDE customization

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#9840]
### Description
subtask of #9074

Implement run commands defined in factory definition
at the moment (legacy GWT IDE), commands are launch at start up of a factory thanks to and action:

```
  "ide": {
    "onProjectsLoaded": {
      "actions": [
        {
          "properties": {
            "file": "/web-java-spring-petclinic/src/main/java/org/springframework/samples/petclinic/model/Pet.java"
          },
          "id": "openFile"
        },
        {
          "properties": {
            "name": "build and run"
          },
          "id": "runCommand"
        }
      ]
    }
  },
``` 

- [x] List the actions and IDE events, that are already defined for GWT IDE https://github.com/eclipse/che/issues/10160 - 10sp
- [x] Implement the factory events handing in Theia https://github.com/eclipse/che/issues/10162 25sp
- [x] propose the Theia mechanizm, that can handle the factory actions, as an example use OpenFile action 25sp
- [x] add handler of the factory actions
