### ISSUE TITLE
Platform-2018-06-19 (Sprint: 150)

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9842]
### Features related to Authentication and security in Theia IDE https://github.com/eclipse/che/issues/9383
- [x]  Authentication with jwtproxy | https://github.com/eclipse/che/issues/9843  13

### Features related to Workspace.Next Phase 1
- [x] Create CQ for golang dependencies for a server that provides features and services  https://github.com/eclipse/che/issues/9844  5

### Technical debts and bugs

- [x] Track OpenShift pods failures on the start of a workspace https://github.com/eclipse/che/issues/7926  8sp
- [x] Implement interruption of start for OpenShift workspaces https://github.com/eclipse/che/issues/5918  8sp
- [x] Servers that don't have servers checks or liveness probes don't contain status field if Che runs docker infrastructure  https://github.com/eclipse/che/issues/9094  8sp
- [x] Document the different places where the authentication is taking place in the code  https://github.com/eclipse/che/issues/9036  13sp
- [x]  Ide cannot run with che-samples/che-plugin-json  https://github.com/eclipse/che/issues/9810  8sp

### Unplanned
- [x] Docker infrastructure must report that it doesn't supports workspaces recovery https://github.com/eclipse/che/issues/9885
#### Availability

| Name | Available | 
| :-- | --: | 
| Sergii Kabashniuk | 11d |
| Max Shaposhnik | 15d | 
| Michail Kuznyetsov | 15 d | 
| Sergii Leshchenko | 15 d | 
#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 63 | 63|
