### ISSUE TITLE
IDE-2018-06-19 (Sprint: 150)

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#9849]
#### Theia improvement: 

- [x] Preferences System for Che with Theia IDE #9336 
- [x] Support commands macro in Theia tasks #8974

#### Artem 
- [x] _[Theia]_ Ability to define/see preview URL for Theia tasks #9273 4d
- [x] _[Theia]_ Make it possible to use Theia's terminal widget for displaying Che Task's output #9847 8d

#### Dmytro 
- [x] Go language server: wrong file name in editor tab #9784 3d
- [x] Go language server: no hovers and docs #9781 2d
- [x] Need to remove extra dependency lib-gwt-svg #9851 1d
- [x] Lost Test Coverage for LanguageServerFileWatcher and ShowMessageRequest #9831 1d
- [ ] Make LSP client proxy support dynamicRegistration for client capabilities #9797 5d
- [ ] Cannot register LSP editor for jdt urls #9856 [analyzing]

#### Roman 
- [ ] _[Theia]_ Theia Editor Key Bindings switching (Default, VI, Emacs) #9244 6d
- [x] In case ws-agent stopped unexpectedly all editors should become in readonly mode or close them #9620 3d
- [x] Fail to create pull request #9987 [unplanned]

#### Vitalii 
- [x] Building rh-che fails with Che 6.6.0-SNAPSHOT redhat-developer/rh-che#681
- [x] Investigate Mozilla Addons Server repository #9863 5d
- [x] Unexpected exceptions in the dev-machine console after initialization LS for GO lang #9796 2d
- [ ] Formatting for python editor does not apply properly in a workspace with enabled python LS #9854 2d
- [ ] Upgrade lsp4j to the v0.4.1 #9864 2d

#### Vlad
- [x] Files created in terminal don't appear in the project explorer #9026 3d
- [x] Cannot select text in dialogs #9727 1d
- [x] Add ability to see/copy full commit SHA #7408 3d

#### Igor 
- [x] _[Theia]_ Preferences UI for Theia IDE #9730 5d
- [x] Scroll button click on file tab closes tab and puts buffer content into the following active tab editor #6840 3d
- [x] _[Theia]_ Rework SSH extension to SSH plugin #9720 6d
- [x] Unexpected fail of CreateNewPackagesWithHelpCreationJavaClassTest selenium test #8122
- [x] Error when creating project from archetype #8164 3d

#### Availability

| Name | Available | 
| :-- | --: |
| Artem | 14 |  
| Vlad |14 |  
| Dmytro  | 14 |   
| Roman  |11 | 
| Vitalii  |14|    
| Igor |14 |  

#### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 71/65 |  |
| **Velocity** | |  |
