### ISSUE TITLE
QE-2018-07-10 (Sprint: 151)

### ISSUE THREAD

**Issue by vkuznyetsov** [eclipse-che/che#9995]
### Sprint goals
- Create new Selenium tests according to test plan.

### Issues tied to objectives
- [x] Cover workspace creation from Blank stack by selenium test https://github.com/eclipse/che/issues/10144 1sp
- [x] Create test plan for testing workspace creation from predefined Eclipse CHE stacks https://github.com/eclipse/che/issues/10169 3sp
- [x] Set the GitHub username to lowercase when compared to the 'Federated Identity' in the 'Keycloak' https://github.com/eclipse/che/issues/10156 1sp
- [x] Adapt C# language server test according new configuration https://github.com/eclipse/che/issues/9925 3sp
- [x] Unexpected fail of "RollingUpdateStrategyWithWorkspacesStartStopTest" selenium test https://github.com/eclipse/che/issues/10209 1sp
- [x] Create selenium test to cover the 'Upload Folder/File' feature https://github.com/eclipse/che/issues/10204 5sp
- [x] Wait timeout is not enough to closing git menu when test runs on the CI job https://github.com/eclipse/che/issues/10130 2sp
- [x] Get message from git status bar is fail when selenium test runs on the CI job https://github.com/eclipse/che/issues/10130 2sp
- [x] Remove "Known issue" which catches #8122 bug https://github.com/eclipse/che/issues/10058 1sp
- [x] Implement usecase which covers opening a file from libraries after refreshing https://github.com/eclipse/che/issues/9992 1sp

### Unplanned 
- [x] Unexpected fail of "ContributeTabTest" selenium test https://github.com/eclipse/che/issues/10043 1sp
- [x] Unexpected fail of "AddOrImportProjectFormTest" selenium test https://github.com/eclipse/che/issues/10111 1sp
- [x] Investigate reason of failing the "RollingUpdateStrategyWithEditorTest" selenium test https://github.com/eclipse/che/issues/10251 2sp
- [x] Cover workspace creation from CentOS stacks by selenium tests https://github.com/eclipse/che/issues/10250 2sp
- [x] Unexpected fail of "NewWorkspacePageTest" selenium test https://github.com/eclipse/che/issues/10281 1sp
- [x] Cover workspace creation from Ubuntu stacks by selenium tests https://github.com/eclipse/che/issues/10270 2sp
- [x] Create selenium test for covering issue #9620 "In case ws-agent stopped unexpectedly all editors should become in readonly mode or close them" https://github.com/eclipse/che/issues/9950 1sp
- [x] Unexpected fail of PhpFileEditingTest selenium test https://github.com/eclipse/che/issues/10330 2sp

### PR under review
- [x] https://github.com/eclipse/che/pull/10244
- [x] https://github.com/eclipse/che/pull/10266

#### Availability

| Name | Available |
| --- | :-: |
| Aleksandr Shmaraiev | 14 |
| Maxim Musienko | 14 |
| Dmytro Nochevnov | 14 |
| Igor Ohrimenko | 14 |
| Sergey Skorik | 8 |
| Total |  | 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 20 | 20 |
